### ISSUE TITLE
[Mod V3] Warning system

### ISSUE THREAD

**Issue by calebj** [Cog-Creators/Red-DiscordBot#1001]
Self-assigning this from #488 and #490. Pulls will be made to [palmtree5/Red-DiscordBot:v3-mod](/palmtree5/Red-DiscordBot/tree/v3-mod) as per #785.

**Comment by palmtree5** [comment]
If you're still planning on doing this, make a new PR since #785 has been merged

**Comment by tekulvw** [comment]
#1173 was merged
