### ISSUE TITLE
[p]imgur

### ISSUE THREAD

**Issue by Manocsak** [Cog-Creators/Red-DiscordBot#1007]
It's not really an issue, but I didn't found the solution so this is a place to ask.

If I use [p]imgur random the bot gives me a random imgur site it's fine, but my problem it's don't have a preview, and I'd really like that, Anyone knows how to do that?

If I copy-paste the same link it's do the preview stuff.
Sorry for the not really important question but I'd really want to know that.

**Comment by Kowlin** [comment]
What I think is happening is that the bot cannot embed previews due the fact that it missing the ``Embed Links`` permission. I'm not sure about this, but this is the only logical thing that comes in my mind.

**Comment by Manocsak** [comment]
Nice, after a little google-ing I found it's a simple channel issue pretty much nothing to do with bots... that why I didn't found the solution in the first place because I was so obsessed with the bot.

So not just the bot, but noone could emblem link on my server, changed that and it's done.
Thank you for your time! :D
