### ISSUE TITLE
Shop cog issues.

### ISSUE THREAD

**Issue by LenaOxton** [Cog-Creators/Red-DiscordBot#1008]
I'm using the shop cog for my DND group as a fun way to try and help with immersion and to keep track of items and such we have, but it's not letting me rename the shop regardless of what I do. The wiki said to just use the shop prefix and 'name' to change it, but it's not working.

[Screenshot here.](https://prnt.sc/gwo3uu)

It's not a pressing issue and we can live without it but I've tried different ways to change it and have had no luck. :( Thank you for your time.

**Comment by Kowlin** [comment]
Hi there, I'm sorry to hear about your problems with this cog, but this repository only covers the main bot and its included cog. So sadly this is not supported by us, you can get support by joining the [3rd party cog support server](https://discord.gg/GET4DVk) or opening a issue on the creator's repository.

**Comment by LenaOxton** [comment]
Thank you! Sorry for the wrong place, it's my first time poking around.
