### ISSUE TITLE
[V3] To-Do List

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#1010]
Hey everyone, people have been asking for this and we feel like it'd be a good way to get some external contributions happening so here it is. Core devs feel free to add onto this as you see fit.

## Alias
* Finish internationalizing strings

## Audio
Contact FlapJack#5505 in Red support server if you're interested in contributing. There's a lot of groundwork yet to be done here.

## Config
* Mongo DB driver support
  * This PR already exists but we need to write code to store db settings on initial setup. Stuff like db server url, port, credentials etc.
* Other db drivers

## Core
* ~~Sharding option~~ (we're now autosharding #1027)

## Downloader
* Implement support for checking cogs minimum version requirement.
* Pip installable cog repos
  * Need to define an "entry_points" package within this repo for cog repos to hook into
    * `redbot.ext`?
  * Template repo for cog creators
  * Docs, instructions, basic tutorials for creating the repo and uploading to pypi?
    * Figure out how to enumerate cogs so downloader knows what's in a repo
    * Figure out how the fuck to use `pkg_resources to do this

## Help command
* ~~Convert to embedhelp~~ (#1106)
* After embedhelp we will need to work on internationalizing help docstrings
* Fuzzy support search #697

## i18n
* Docs for 3rd party cog translations
* How the hell do we generate translation on Macs? Right now we're using `pygettext` which *should* be present in all Python installations but for some reason is not appearing on OS X.

## Streams
* Various bugs to fix.

**Comment by Kowlin** [comment]
What about Fuzzy search support #697?

**Comment by tekulvw** [comment]
Removing this in favor of the Zenhub boards
