### ISSUE TITLE
"No module named cogs.utils" error

### ISSUE THREAD

**Issue by francescolf** [Cog-Creators/Red-DiscordBot#1014]
When I start the bot I get an `ImportError`

This is my pip freeze output:
`automationhat==0.0.4
blinker==1.3
blinkt==0.1.0
Cap1xxx==0.1.3
chardet==2.3.0
colorama==0.3.2
decorator==4.0.11
drumhat==0.0.5
envirophat==0.0.6
ExplorerHAT==0.4.2
ez-setup==0.9
Flask==0.10.1
fourletterphat==0.0.2
gpiozero==1.4.0
html5lib==0.999
imageio==2.1.2
itsdangerous==0.24
Jinja2==2.7.3
lxkeymap==0.1
MarkupSafe==0.23
microdotphat==0.1.3
mote==0.0.3
motephat==0.0.2
moviepy==0.2.3.2
music21==4.1.0
ndg-httpsclient==0.3.2
numpy==1.8.2
phatbeat==0.0.2
pianohat==0.0.5
picamera==1.13
picraft==1.0
pifacecommon==4.2.1
pifacedigitalio==3.1.0
piglow==1.2.4
pigpio==1.35
Pillow==2.6.1
pyasn1==0.1.7
pygame==1.9.2a0
pygobject==3.14.0
pyinotify==0.9.4
pyOpenSSL==0.13.1
pyserial==2.6
python-apt==0.9.3.12
rainbowhat==0.0.2
requests==2.4.3
RPi.GPIO==0.6.3
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.0.1
sense-emu==1.0
sense-hat==2.2.0
six==1.8.0
skywriter==0.0.7
smbus==1.1
sn3218==1.2.7
spidev==3.0
touchphat==0.0.1
tqdm==4.11.2
twython==3.1.2
unroll==0.1.0
urllib3==1.9.1
Werkzeug==0.9.6`

**Comment by Stylite** [comment]
Install the requirements of the bot from the launcher it seems like you are missing discord.py and the other requirements.

**Comment by francescolf** [comment]
I already installed them

**Comment by Stylite** [comment]
It doesn't look like you did

**Comment by francescolf** [comment]
I did.

**Comment by Kowlin** [comment]
@atiwiex. The reason that their not in the above list is due the fact that Red installs the libs locally to the red folder it self if done by the launcher.

@ItalianRedstone. We need additional information, as example how do you start the bot.

**Comment by francescolf** [comment]
`python3.5 launcher.py`, I select `start red` and then I get the error with exit code 1.

**Comment by tekulvw** [comment]
Please join the Red support server for more assistance if this issue is still present.
