### ISSUE TITLE
Horrible audio quality when playing from soundcloud

### ISSUE THREAD

**Issue by mio9** [Cog-Creators/Red-DiscordBot#1035]
Everything is working fine and the sound quality when playing through youtube is all fine, and even there is compression, the effect is nearly negligible to us (at least to those gamers), but for some reason, when playing through sound cloud, the audio quality went wild, and a lot of my other members in the room spot there is a dramatic drop in audio quality (featuring lags, and cut off of frequency with a very ugly way).

Is there anything we could work around this?

**Comment by tekulvw** [comment]
All audio files in V2 are downloaded and stored on the bot's local machine before being transmitted to discord. This is either a sign of your internet connection going wacky or 64kbps not being enough or the bot not having enough processing power to re-encode audio in realtime. Sadly, no part of this will be changed in V2 as it's feature locked. Feel free to leave a comment on #623 so we check on this for V3.
