### ISSUE TITLE
[V3] When installed with #egg=red-discordbot[voice], the start screen indicates no voice support.

### ISSUE THREAD

**Issue by tmercswims** [Cog-Creators/Red-DiscordBot#1045]
### To reproduce:
* Create a new virtualenv.
* Install V3 with the following command:
```bash
pip3.5 install --process-dependency-links -U git+https://github.com/Cog-Creators/Red-DiscordBot@V3/develop#egg=red-discordbot[voice]
```
* Run `redbot-setup` and complete the setup process.
* Run `redbot <instance-name>`.

### Expected:
The startup screen shows `√ Voice`.

### Actual:
The startup screen shows `X Voice`.

For the record, I've yet to check if voice support is actually missing; my setup is not complete yet. I'll update this issue as I discover more.

**Comment by Redjumpman** [comment]
Yup, that was my mistake Tmerc. I'll have a PR put in to fix it as soon as I can.

**Comment by palmtree5** [comment]
fixed in https://github.com/Cog-Creators/Red-DiscordBot/commit/10647f14b2752a0504ad7f8515b648471b37464c
