### ISSUE TITLE
[V3] Allow specifying optional database name for mongo setup

### ISSUE THREAD

**Issue by skeith** [Cog-Creators/Red-DiscordBot#1047]
IIRC, mongo allow access without auth when accessed locally. The current redbot-setup will fail when we supply mongodb user and pass for a database we have created beforehand. 

![image](https://user-images.githubusercontent.com/340284/31891995-8267402c-b83a-11e7-92ca-5a98b26df422.png)

As seen above, I made `red` database but since the user for it keep failing, I use no user and password (empty) for the setup and it created `RED_<instance_name>` database

**Comment by Kowlin** [comment]
In summery: bot fails to check for existing DB by same name.

**Comment by tekulvw** [comment]
Fixed with #1355
