### ISSUE TITLE
Custom commands cannot be displayed past the 2000 character limit

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#105]
So...the server I run has a _lot_ of custom commands. We have far surpassed the 2000 character limit in Discord and the bot and no longer give us a full list.

Please make it so the bot can post custom commands as multiple messages once a single message reaches the 2000 char limit.

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/cab5b23b0b19de10fe60be73e47263cfc736a30b
