### ISSUE TITLE
[V3 Modlog] Duplicate cases created on bans

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1052]
Duplicate cases are being created when using the `ban` command. This is likely due to the `on_member_ban` event in `Mod`

**Comment by Kowlin** [comment]
I think that this can be fixed by adding a condition that checks if a ban is issued by the current bot account.
As example: grab the newest ban event, check if the user is the current bot and then assign logic based on that.

**Comment by VaronBros** [comment]
I don't have that issue, is it because of a corrupted script installed?

**Comment by palmtree5** [comment]
Are you using the rewrite?

**Comment by Kowlin** [comment]
Solved in https://github.com/Cog-Creators/Red-DiscordBot/commit/d6fce3c14504becbb960ee71c123d12a076ecf97

**Comment by palmtree5** [comment]
Reopening because this is still happening on beta 2

**Comment by palmtree5** [comment]
Fixed by #1102
