### ISSUE TITLE
[V3 CustomCom] cc list errors

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1087]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem

`AttributeError: 'Red' object has no attribute 'whisper'` when running `cc list`

### Expected behavior

It should DM the custom command list

### Actual behavior

Error posted in the channel the command was run in

### Steps to reproduce

1. Create enough custom commands that the custom command list would be sent by DM
2. Do `cc list`
3. See error message

Fix is pretty simple. [This line](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/cogs/customcom/customcom.py#L320) is what is causing the error. It's code from v2 that was never converted for v3

**Comment by tekulvw** [comment]
Fixed with #1149
