### ISSUE TITLE
[v3] Bankset global error

### ISSUE THREAD

**Issue by IdkGoodName** [Cog-Creators/Red-DiscordBot#1093]
# Bankset global error
### I kept getting this error when i want to set bank to global on my red v3

> ``` [11/11/2017 19:53] ERROR events on_command_error 159: Exception in command 'bankset toggleglobal'
> Traceback (most recent call last):
>   File "c:\users\*****\appdata\local\programs\python\python35\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
>     ret = yield from coro(*args, **kwargs)
>   File "C:\Users\*****\Desktop\bots\redbot v3\cogs\bank\bank.py", line 66, in bankset_toggleglobal
>     await bank.set_global(not cur_setting)
> TypeError: set_global() missing 1 required positional argument: 'user'

**Comment by palmtree5** [comment]
#1084 fixes this

**Comment by tekulvw** [comment]
#1084 got merged
