### ISSUE TITLE
[V3] No cogs on initial load

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1096]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug (?)

### Brief description of the problem

The bot currently does not load its default cogs on the first time boot, since there isn't anything that tells it to load.

**Comment by Tobotimus** [comment]
Pretty sure we've decided this is desired behaviour, especially considering how many core cogs we now have. Can be reopened if the status quo changes
