### ISSUE TITLE
More Casino Type minigames

### ISSUE THREAD

**Issue by franc-ist** [Cog-Creators/Red-DiscordBot#110]
I have had multiple requests on my fairly large server for more Casino games like slots.

**Comment by irdumbs** [comment]
want to suggest some?

**Comment by Kowlin** [comment]
Done!
![](http://i.imgur.com/MLwSsJn.png)

**Comment by irdumbs** [comment]
fuuuu

**Comment by franc-ist** [comment]
Roulette

Kappa

**Comment by ddday** [comment]
I agree

**Comment by AtticusTG** [comment]
The old Lemonade Stand game would be a decent idea, moving money around and such, and it supported up to 30 people, all being text based (basically)
For reference: https://en.wikipedia.org/wiki/Lemonade_Stand

**Comment by Novabella** [comment]
A cool idea would be maybe have queues cost credits, so people don't spam crap videos from youtube, and gives them a use for credits in slots. (Obviously) it might also be a good idea to make this a set-able price, as is everything else in economy.py

**Comment by irdumbs** [comment]
might as well make all commands a settable price
might be doable easily actually
of course everything is default to 0
anybody want this?
would need to edit red.py and alias.py

**Comment by ddday** [comment]
That would be nice if it notified you in your pms who bought something, or
kept a log.
Or maybe give them a tag?

**Comment by TheNarwhal** [comment]
Russian Roulette would be a fun game to play.
Maybe have like a betting pot where everyone puts in some credits, and whoever wins gets the pot.

**Comment by irdumbs** [comment]
and if they lose? they get banned?
I approve

**Comment by Novabella** [comment]
@irdumbs I would love that, thank you. I'll PM you in discord (because things are easier there.)

**Comment by irdumbs** [comment]
lol it was a joke.. but.. could do it ( ͡° ͜ʖ ͡°)

**Comment by Novabella** [comment]
Oh... I mean, it would be nice tho. Less spam, and no more "Spam warnings" from discord.

**Comment by irdumbs** [comment]
@Novabella if you mean commands costing points, @Kowlin is working on that.

**Comment by ayshunstyle** [comment]
roulette pls 😄

**Comment by franc-ist** [comment]
#216
