### ISSUE TITLE
[Suggestion] Stream titles included in live notifcations + Offline alerts

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#111]
Notify channel when offline + get stream titles and display it in online messages eg: %username% is now live at %link% With the title %streamtitle%

**Comment by MadMakz** [comment]
Here's an quick and stupid but working patch for online twitch streams. I'm new to python so it's pretty much not production ready :)

Since (zip) attachements are broken for me, here's a link: https://www.dropbox.com/s/unrbvriwjoy1r2p/red-discordbot--streams.py.diff?dl=0

![streams py](https://cloud.githubusercontent.com/assets/3930214/14410103/4daea9ca-ff26-11e5-8509-db6a0d7d65a1.jpg)

**Comment by irdumbs** [comment]
don't forget currently playing game ;)

**Comment by MadMakz** [comment]
[streams.py](https://code.spiffytek.de/MadMakz/Red-DiscordBot-Custom/raw/master/cogs/streams.py) fixed triggering on "error" and fixed streamalert. No game yet

**Comment by franc-ist** [comment]
@MadMakz can confirm this works. I suggest making a PR

**Comment by MadMakz** [comment]
![red-discordbot-i111-p198](https://cloud.githubusercontent.com/assets/3930214/14833214/6b6575e0-0bfe-11e6-977f-93b1daa2abe0.png)

Pull #198 

Possibly needs a failcheck if "No Game/No Title" is set. I won't take care about Hitbox or Beam.

**Comment by tekulvw** [comment]
Closing because requested functionality is in #198

**Comment by MadMakz** [comment]
Shouldn't be closed as #198 is Twitch only.

OP didn't ask specificialy for Twitch but for general support i think.
Unless Beam & hitbox recive the same feature it should remain open.

**Comment by FishyFing** [comment]
@MadMakz we will add that functionality to all streams, not just twitch, which is why it was closed

**Comment by tekulvw** [comment]
Oh, gotcha, reopening then

**Comment by Twentysix26** [comment]
I don't see much of a point in offline alerts. The rest has been implemented.

https://github.com/Twentysix26/Red-DiscordBot/commit/b69b5b30056c5b4fb213b20ee0970f22de5c0503
