### ISSUE TITLE
[V3 Admin] Selfrole add is limited only to those with manage_roles

### ISSUE THREAD

**Issue by Aioxas** [Cog-Creators/Red-DiscordBot#1113]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [X ] Bug

### Brief description of the problem

V2 Admin had no restrictions on permissions for adding selfroles to a user. This one has @commands.has_permission(manage_roles=True)

### Expected behavior
User inputting command to add selfrole and getting role added.
### Actual behavior
User inputting command to add selfrole and getting a "not authorized to use this command" message instead.
### Steps to reproduce

1. normal (non-manage_roles allowed) user tries using selfrole add or uses selfrole command and sees what commands are available
2. Selfrole add shows as forbidden. Selfrole shows as only listing remove or list.
3. ???
4. Profit?

**Comment by tekulvw** [comment]
Just as in V2, the syntax for adding a selfrole to yourself is `selfrole <rolename>`. `selfrole add` is for adding a role to the list of roles available to users.
