### ISSUE TITLE
[V2] Multiple bans at same time breaks log

### ISSUE THREAD

**Issue by Soulrift** [Cog-Creators/Red-DiscordBot#1114]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
When multiple moderators ban the same user at the same time (via right click ban), Red fails to register the ban.  This results in no modlog entry/case and no cleanup.

### Steps to reproduce

1.  Have two or more moderators ban the same user at the exact same time
2.  ?
3.  Profit

**Comment by tekulvw** [comment]
Sorry Fortnite, gonna have to wait for V3 for a true fix.
