### ISSUE TITLE
[V3 Alias] using symbols for aliases

### ISSUE THREAD

**Issue by Aioxas** [Cog-Creators/Red-DiscordBot#1118]
### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
in V2 you could use symbols such as ?, !, etc to make aliases, now it's not allowed. Any explanation for this change?
### Expected behavior
Alias adds an alias with a symbol.
### Actual behavior
Doesn't allow the symbol alias to be added.
### Steps to reproduce

1. Try to make an alias with a symbol such as [p]alias add ? profile na
2. Get denied
3. ????
4. Profit

**Comment by Kowlin** [comment]
So far I cannot find out if this is intended or a bug, its related to the ``isidentifier()``

https://github.com/Cog-Creators/Red-DiscordBot/blob/064e9b6bd0b0152f162c555e01bcfa5947f04a36/redbot/cogs/alias/alias.py#L78

**Comment by Tobotimus** [comment]
Fixed in eb10508.
