### ISSUE TITLE
[V3 Config] Suggestions

### ISSUE THREAD

**Issue by DeltaSigma130** [Cog-Creators/Red-DiscordBot#1120]
I have two suggestions for feature enhancements for Config.  The first seems pretty core to me while the second is definitely a stretch type goal.

1)  Add `__contains__` to Value class, and hence Group, to allow `key in cfg`.  This is especially helpful for settings type Config where an end user is allowed to change settings that are stored in Config.  It would allow easy testing for data validation as one example.   If necessary for it to be async, I think `await cfg.contains(key)` type construct would be acceptable too.

2)  In the spirit of data validation, allow values to be registered as acceptable inputs.  For example min/max values for numeric inputs, or a set to be defined for a choices type Config (e.g. {'sci', 'eng', 'prefix'} as acceptable choices for a "format" type config).  This would allow streamlined code for a good subset of use cases.

**Comment by tekulvw** [comment]
I don't think we'll be implementing these any time soon. Data validation is definitely on the table but I'll end up making a new issue when the time comes to further explore it.
