### ISSUE TITLE
Bot does not want to execute info command

### ISSUE THREAD

**Issue by Jerlag01** [Cog-Creators/Red-DiscordBot#1122]
Bot doesn't want to accept the info command. It returns following error in the console:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/jerlag/discord/ZNRED/cogs/owner.py", line 871, in info
    embed = discord.Embed(colour=discord.Colour.red)()
AttributeError: module 'discord' has no attribute 'Embed'

**Comment by xXFireBunnyXx** [comment]
@Jerlag01 have u tried updating the requirements from the launcher?

**Comment by Jerlag01** [comment]
Yeah, there is also another bot running with the same red bot source code and that one is just running fine, they both run on the same machine. So all the requirements are installed

**Comment by Kowlin** [comment]
Please keep in mind that Red installs to their own lib folder, unless the packages are installed globally on the system, you're required to update the bot each time or install it globally by running ``pip install -r requirements.txt`` in a bot folder.

**Comment by Jerlag01** [comment]
I'll check it in a moment

**Comment by Jerlag01** [comment]
The requirements weren't installed globally...
Thanks for the help
