### ISSUE TITLE
'pip3' is not recognized as an internal or external command, operable program, or batch file

### ISSUE THREAD

**Issue by AstroA** [Cog-Creators/Red-DiscordBot#113]
I was trying to do the initial install of the bot's requirements, when I came across this:
`'pip3' is not recognized as an internal or external command, operable program, or batch file.`
I've installed everything necessary to run the bot, and checked it over. Still no luck. Did I forget to do something along the way or is it something else?

EDIT:
Ok, after editing the %PATH% I solved the problem, but now when I run the command it gives me this:

C:\Program Files (x86)\Python 3.5\Scripts>pip3 install git+https://github.com/Rapptz/discord.py@async
Collecting git+https://github.com/Rapptz/discord.py@async
  Cloning https://github.com/Rapptz/discord.py (to async) to c:\users\paul\appdata\local\temp\pip-dxueyaai-build
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/Rapptz/discord.py C:\Users\Paul\AppData\Local\Temp\pip-dxueyaai-build
Cannot find command 'git'

**Comment by Twentysix26** [comment]
Needs git in your path
