### ISSUE TITLE
[V3 Beta 3 Streams] 'Task' Object has no attribute 'append' when

### ISSUE THREAD

**Issue by Wolfieheart** [Cog-Creators/Red-DiscordBot#1132]
### Type:

Bug

### Brief description of the problem

`!streamalert twitch channel <channel_name>` gives error `'Task' object has no attribute 'append'` 

### Expected behavior

Add a stream to the list of channels to be alerted for

### Actual behavior

Error...

### Steps to reproduce

1. Execute command `!streamalert twitch channel` with any (valid) stream name

### Observations

Line 44 of `cogs/streams/main.py`'s assignment to `self.streams` from `self.bot.loop.create_task` returns a `Task` object instead of a `list` or similar. (No other object assignments found).

**Comment by tekulvw** [comment]
Fixed with #1135
