### ISSUE TITLE
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by ufilme** [Cog-Creators/Red-DiscordBot#1136]
I don't know how to solve this :/

when run: python3.6 launcher.py
I get this:
https://prnt.sc/hijzvc

**Comment by Twentysix26** [comment]
Some context please.

**Comment by pippognetow** [comment]
https://prnt.sc/hijzvc better? 
@Twentysix26

**Comment by Twentysix26** [comment]
@pippognetow Sorry, I missed the part where you said "when running: python3.6 launcher.py"  
Sadly I've never seen that particular issue

**Comment by ufilme** [comment]
nice...

**Comment by tekulvw** [comment]
You may want to try updating setuptools, `pip install -U setuptools pkgresources`

**Comment by ufilme** [comment]
Doesn't work @tekulvw

**Comment by palmtree5** [comment]
and what's the error?

**Comment by tekulvw** [comment]
No response, no repro.

**Comment by richardlin047** [comment]
I get this error when I'm trying to install dotenv
> AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

So I tried @tekulvw 's answer `pip install -U setuptools pkgresources` but then this error shows up
`Collecting pkgresources`
`Could not find a version that satisfies the requirement pkgresources (from versions: )`
`No matching distribution found for pkgresources`

Do you know why?
