### ISSUE TITLE
[Suggestion] add !quote for random quotes

### ISSUE THREAD

**Issue by Instantducks** [Cog-Creators/Red-DiscordBot#114]
Make a cog that we can use to put random quotes of our choosing in the config.

**Comment by Redjumpman** [comment]
You can check out my pull request  where I added a fortune cog using the command !fortune or !cookie. The code is super simple and could be modified to do a quote instead. Hope that helps.

**Comment by franc-ist** [comment]
@Teravainen https://github.com/tekulvw/Red-DiscordBot/blob/develop/cogs/quotes.py

**Comment by irdumbs** [comment]
that's not an official cog. try to avoid linking to random python files on the internet when responding to someone's request
