### ISSUE TITLE
[V3] [p]mock doesn't work with aliases

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1140]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Attempting to run an alias as another user with `[p]mock` does nothing

### Expected behavior
It should run the command the alias is for

### Actual behavior
It does nothing
### Steps to reproduce

1. Create an alias (for example, `[p]alias add c contact`
2. Try to use mock with it (`[p]mock <user> c`)
3. Nothing happens

**Comment by tekulvw** [comment]
Fixed with #1156
