### ISSUE TITLE
[V3] Pip voice extra doesn't work

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#1147]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Steps to reproduce

1. 
2. 
3. 
4.

**Comment by tekulvw** [comment]
I can't actually reproduce this myself, can someone who has this issue please respond.

**Comment by Kowlin** [comment]
No Repro in a month, closing.
