### ISSUE TITLE
[V3 Sentry] Filter out asyncio errors on exit

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#1148]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [ ] Bug

### Brief description of the problem
Right now we're seeing `asyncio.CancelledError` and `websockets.ConnectionClosed` in our error log. These are the result of shutting the bot down and should be caught and handled or at worst, filtered out of sentry.

**Comment by Kowlin** [comment]
From doing a small bit of research, it seems that there really is no clean way to exit Sentry. The closest that I found that could be a possible solution to this would be [this GitHub comment](https://github.com/getsentry/raven-python/issues/489#issuecomment-54791467)

**Comment by Tobotimus** [comment]
Correct me if I'm wrong, but I believe these were resolved in ef72167

**Comment by Tobotimus** [comment]
Looking through the Sentry issues, all `asyncio.CancelledError` and `websockets.ConnectionClosed` errors were from prior to `ef72167`, closing.
