### ISSUE TITLE
Cannot find command 'git'

### ISSUE THREAD

**Issue by Qwerty1Verified** [Cog-Creators/Red-DiscordBot#1154]
![image](https://user-images.githubusercontent.com/34402846/33798585-1302764a-dd13-11e7-87e1-abcea146c7d9.png)
  
I tried installing basic and audio which is "1" but i get this error. I have rebooted my computer so im unsure.

**Comment by Qwerty1Verified** [comment]
In the picture i tried 2 aswell.

**Comment by DannyB5544** [comment]
You didn't install git. Go install git.
https://git-scm.com/downloads

**Comment by Qwerty1Verified** [comment]
I did.. maybe i should update it. Because i installed the bot via git bash

**Comment by DannyB5544** [comment]
Oh ok then... What version of Python?

**Comment by iCancerous** [comment]
It would be because git isn't installed to Window terminal to read as a command.

**Comment by Tobotimus** [comment]
Please direct all support questions to the support server: https://discord.gg/red

Closing this issue now. If you are sure this is an issue with the bot itself, you can comment here and the issue may be re-opened.
