### ISSUE TITLE
[V3 Core] Role blacklist

### ISSUE THREAD

**Issue by Qwerty1Verified** [Cog-Creators/Red-DiscordBot#1158]
Is there a way to blacklist roles because I want certain roles to be able to use audio commands but not normal users.

**Comment by mikeshardmind** [comment]
There's still no true role blacklist in the bot yet, but between the audio DJ role, and the permissions cog, your use case has solutions currently. I'll be making a PR soon which incorporates this and a bit more.

**Comment by tekulvw** [comment]
This is implemented in the permissions cog and audio DJ role.
