### ISSUE TITLE
[V3] Offers cli flags after invalid input

### ISSUE THREAD

**Issue by Sitryk** [Cog-Creators/Red-DiscordBot#1161]
### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
Launcher still asks for cli flags after fail

### Expected behavior
When selecting an instance index, if the input is invalid, don't ask for cli flags

### Actual behavior
Using the redbot-launcher, when selecting choice 1 or 2 to start an instance, if an invalid value is given, the launcher still asks for cli flags

### Steps to reproduce

1. redbot-launcher
2. 2
3. type random stuff on input for which instance you'd like to start

![image](https://user-images.githubusercontent.com/23440577/33813731-a3c24980-de8a-11e7-9043-bf3a6802bc60.png)

**Comment by Tobotimus** [comment]
Fixed in 4ac606b.
