### ISSUE TITLE
[V3 Core] Include proper way to show admin/mod role in current guild

### ISSUE THREAD

**Issue by Aioxas** [Cog-Creators/Red-DiscordBot#1175]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [X] Suggestion
- [ ] Bug

### Brief description of the problem
No way to see current admin/mod roles or if any have been set up. Toby posted a way to use an eval to return the names but it would be easier if it was either a command or something shown when running the mod/adminrole command without arguments or if another method.
```py
[p]eval
`id = await bot.db.guild(ctx.guild).admin_role()
return next(r for r in guild.roles if r.id == id)`
```
### Expected behavior
Command showing the current guild's admin/mod role where the command is being used.
### Actual behavior
Nothing

**Comment by tekulvw** [comment]
Fixed with #1475
