### ISSUE TITLE
prefixes that are prefixed by other prefixes don't work

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#118]
!set prefix ! "! " 
! flip
^ no output
!flip
^ output

!set prefix ! !!
etc

**Comment by irdumbs** [comment]
@tekulvw proposed we sort prefixes by length before saving them. (or bother discord.py to do the same)

**Comment by tekulvw** [comment]
I'd be pretty a-ok with disallowing spaces in prefixes except for the name reference prefix

**Comment by irdumbs** [comment]
#125
