### ISSUE TITLE
[V3 Streams] Preceding comma in stream alert messages

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1192]
### Type:

- Bug

### Brief description of the problem
When a stream alert is sent, the bot's message contains an unnecessary preceding comma:
![image](https://user-images.githubusercontent.com/7438501/34086913-d4d07ca4-e3f3-11e7-8619-9ac90f9be9ff.png)

**Comment by mrfizzl3** [comment]
Do you have the bot set to mention @here or @everyone?

**Comment by dsvobo** [comment]
https://github.com/Cog-Creators/Red-DiscordBot/blob/c737785114586ce609b967e95735bd32106ede34/redbot/cogs/streams/streams.py#L447-L448
Do you have the bot setup to mention either ``@here`` or ``@everyone`` when a stream goes online?

**Comment by Tobotimus** [comment]
@mrfizzl3 No, this is simply a logic error which occurs when the mention settings are turned off. If they are on, the mentions should appear before the comma.

**Comment by Tobotimus** [comment]
Fixed in d83f14d.
