### ISSUE TITLE
[V3 Streams] Twitch Communities are broken

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1196]
### Type:

- Bug

### Brief description of the problem
Twitch communities simply don't work in their current state. This is largely due to missed refactors, missing awaits, and general oversights on design.

I've discovered there is no framework set up to prevent duplicate alerts when streams go online for a community, meaning that alerts will be sent every 60 seconds as long as a stream is online.

**Comment by tekulvw** [comment]
Fixed with #1426
