### ISSUE TITLE
Following linux installation instructions, have a problem.

### ISSUE THREAD

**Issue by jubilus** [Cog-Creators/Red-DiscordBot#120]
Following the [instructions here](https://github.com/Twentysix26/Red-DiscordBot/wiki/Installing-on-Linux), I've encountered an error I don't know how to fix. 

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-khslnsr6/PyNaCl/

I get this error when I try the step:

> sudo pip3.5 install git+https://github.com/Rapptz/discord.py@async

Any suggestions?

**Comment by Twentysix26** [comment]
`sudo apt-get install python3.5-dev build-essential libssl-dev libffi-dev`

**Comment by jubilus** [comment]
That fixed it, thanks!

**Comment by gnarf** [comment]
> sudo apt-get install python3.5-dev build-essential libssl-dev libffi-dev

I just ran into the same problem; has this been updated in the install instructions? Could you add something about needing to install libffi-dev ?

**Comment by gnarf** [comment]
P.S. I think this is the first time I had trouble with the linux install instructions; but the Mac ones work perfectly!

Thanks for the solid docs!

**Comment by Kowlin** [comment]
You're commenting on a issue that is a year old, please consider opening a new one with more details about your OS and instructions you're following.

**Comment by gnarf** [comment]
#744 - I just found the trouble in the docs and opened a new issue
