### ISSUE TITLE
My Friend Shared Discord Red Bot With Me, But It Didn't Work When I Tried To Start It Up.

### ISSUE THREAD

**Issue by BrambleTakato** [Cog-Creators/Red-DiscordBot#1207]
Greetings!
So, my friend Sammy has the Red DiscordBot and decided to send him to me so that I can help to operate it. The thing is, when I got the files, this message appears whenever I try to start him up.
![image](https://user-images.githubusercontent.com/34751326/34270465-4577101c-e656-11e7-8c45-40acebaa8595.png)
I did the start_red file.
I have the same python version as my friend, which is 3.5.2
I have NOT installed the audio version of the requirements, but my friend did.
I don't know about our GitBash versions, but we both followed the same video, so it must be the same.
And I manually added Python to PATH because it didn't give me the PATH option.
Can someone please help me? I want to be able to run it when my friend is away so that our 100+ server can remain happy while she is gone.
Thank you!
Files;
![image](https://user-images.githubusercontent.com/34751326/34270618-c421bcdc-e656-11e7-98c4-d2615afde490.png)

Location;
C:\Users\Bramble\Desktop\Jaybot

Platform;
Windows 10 64 bit

**Comment by calebj** [comment]
The launcher generates `start_red.bat` and `start_red_autorestart.bat` dynamically. Notice how it's looking for the folder of a user named Sammy? Delete those two files, then run `start_launcher.bat`

**Comment by Kowlin** [comment]
As explained above, deleting the files will solve this issue, closing.

**Comment by BrambleTakato** [comment]
Ah, thank you so much! ^^
