### ISSUE TITLE
Per server mod/admin role

### ISSUE THREAD

**Issue by OKEPlazmA** [Cog-Creators/Red-DiscordBot#1208]
In the launcher the bot asks for the name of the roles to give permissions, well, I was wondering if the bot was in multiple servers would i just be able to cut that part out so anyone with Administrator and Manage server perms can use the Moderation commands?

**Comment by palmtree5** [comment]
those roles can be set per-server. Also commands can be run by anyone with the required permissions

**Comment by OKEPlazmA** [comment]
With some of the cogs such as warn, the command isn't able to function without the specified roles. How do you set the roles per-server?

**Comment by palmtree5** [comment]
`[p]set adminrole` and `[p]set modrole`

**Comment by Kowlin** [comment]
We do not support 3rd party cogs. Please contact the author of that cog for permission based commands. As for per server mod and admin roles, this already exists as explained above.
