### ISSUE TITLE
[V3 Sentry] Exceptions from 3rd party cogs are not being filtered

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1215]
### Type:

- Bug

### Description
Sentry is receiving all error logs from all cogs, not just from within the `redbot` package.

This occurs from errors in both `on_error` and `on_command_error`, as well as syntax errors being propagated from the `reload` command.

**Comment by Tobotimus** [comment]
Adding #1214 as a dependency since it involves a redesign of the sentry logging interface. This will make resolving this issue easier.

**Comment by tekulvw** [comment]
Fixed with #1353
