### ISSUE TITLE
cant find git command and a massage

### ISSUE THREAD

**Issue by VasilisThePikachu** [Cog-Creators/Red-DiscordBot#1218]
the app says it cant find a git command and before i start to install (at the home sreen) i get this massege
 Git not found. This means that it's either not installed or not in the PATH environment variable like requested in the guide

can you help me sreen shots
 
https://imgur.com/a/MCpud

**Comment by VasilisThePikachu** [comment]
i forgot to say that im greek so if you want to read the red one translate it if you can

**Comment by Twentysix26** [comment]
Please follow the windows installation guide step by step. You're supposed to install Red using git. I'd recommend to start over. If you have issues with git not being in PATH a reboot might fix it

**Comment by VasilisThePikachu** [comment]
hello i did not wanted to make a new issue but i made the bot do basic stuff like shutdown restart and more but i cant use music commands

i have 2 provlems

1:i dont know if i run the wrong command i watch a video and it sead it is "yt" is the command need to do is it true
2:i installed ffmpeg 64bit (my pc is 64bit) and i install basic and audio requirements do have to do something else or i im ok?

sorry if i needed to make a new issue but just tell me

**Comment by Tobotimus** [comment]
@vascreeperGR Please direct support questions to the discord server, https://discord.gg/red . Issues are generally for problems (e.g. bugs) with the bot itself.
