### ISSUE TITLE
[v3 Core] Suggestion

### ISSUE THREAD

**Issue by IdkGoodName** [Cog-Creators/Red-DiscordBot#1222]
4 words 

Leveling should be core

**Comment by skeith** [comment]
no,
it should always be a cog because Red is a modular bot

**Comment by Bakersbakebread** [comment]
I agree.

Core features need to be _essential_ features. The development of a leveller should be handled by said Dev. Also, with the leveler being a cog allows competition and innovation

**Comment by Tobotimus** [comment]
As I've stated before, you need to back up your suggestions or else they won't be considered. If you have something to support your argument, you can comment it here. Closing this for now.

Regardless, I don't see any reason why levelling should be core.
