### ISSUE TITLE
[V3 Filter] The filter seems to be global

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1228]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Filter is being applied across all servers the bot is in
### Expected behavior
Filtered words should only be filtered in the server the command was run in
### Actual behavior
A filtered word in one server is being deleted in others
### Steps to reproduce

1. Add a word to the filter
2. Go post a message containing the filtered word in another server the bot has perms to delete messages in
3. Witness issue

**Comment by palmtree5** [comment]
Closing because I'm not able to reproduce this anymore

**Comment by Kowlin** [comment]
Related to #1294
