### ISSUE TITLE
[V3 Install] - setuptools missing

### ISSUE THREAD

**Issue by Bakersbakebread** [Cog-Creators/Red-DiscordBot#1229]
### Type:

- [x] Suggestion
- [x] Bug

Brief description of the problem:
Red fails to install using pip install --process-dependency-links -U Red-DiscordBot if setuptools is not installed.

Fix:

Adding a prompt for user to : pip install --upgrade setuptools or add to requirements.txt

**Comment by Tobotimus** [comment]
I'm not so sure about this. `setuptools` is a pretty essential package for python environments, most should come with it already installed, including virtual environments.

Not only that, but when setuptools isn't installed, I do in fact get a clear enough prompt to install it on pip 9.0.1:
```
>pip install --upgrade --process-dependency-links Red-DiscordBot
Collecting Red-DiscordBot
  Using cached Red-DiscordBot-3.0.0b5.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.
```
