### ISSUE TITLE
Help message

### ISSUE THREAD

**Issue by Qwerty1Verified** [Cog-Creators/Red-DiscordBot#1231]
Hello, Is there a way to change the help text the bot messages you when you type [PREFIX]help  ?

**Comment by Zephyrkul** [comment]
There is no help command in the code. The help is handled by discord.py's command extension and it's dynamically generated from the loaded cogs / commands. Don't worry, your users will only see the commands they can use. 
**B-but what if I still want to modify it then?**
¯\_(ツ)_/¯ GLHF (We're not helping you if you break the bot)
*Oh and if you remove the credit built into the help command, you're breaking our rules and up for a ban.*

**Comment by Tobotimus** [comment]
Please join the support server (https://discord.gg/red) for further questions.
