### ISSUE TITLE
[V3 Economy] Slots fails to run

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1246]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Slots fails to run if the user has the exact amount of money to run the slots.

**Comment by mikeshardmind** [comment]
This should be fixed with PR #1234
