### ISSUE TITLE
Error when trying to install requirements.

### ISSUE THREAD

**Issue by alexandzors** [Cog-Creators/Red-DiscordBot#1250]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Installed Python + Git and when I try to install the requirements for the bot I get an error.

### Expected behavior
Installation of requirements works.
### Actual behavior
Installation of requirements fails.
### Steps to reproduce

1. Install Python 3.6.4 on Windows Server 2012 R2
2. Install Git for Windows
3. Clone the repo and run the launcher bat and select option for requirements.
4. Select Basic with no audio.

Attached file is the output showing the error.
[Error.txt](https://github.com/Cog-Creators/Red-DiscordBot/files/1629025/Error.txt)

**Comment by Twentysix26** [comment]
As the guide says you need Python 3.5

**Comment by alexandzors** [comment]
Not sure how I missed that, thanks.
