### ISSUE TITLE
Editing the Help Command

### ISSUE THREAD

**Issue by 7ekhed** [Cog-Creators/Red-DiscordBot#1263]
### Brief description of the problem

When I press help, it DM's me and it says Red-Bot on the top. Is this able to be changed some how?

**Comment by Zephyrkul** [comment]
There is no help command in the code. The help is handled by discord.py's command extension and it's dynamically generated from the loaded cogs / commands. Don't worry, your users will only see the commands they can use. 
**B-but what if I still want to modify it then?**
¯\\\_(ツ)_/¯ GLHF (We're not helping you if you break the bot)
*Oh and if you remove the credit built into the help command, you're breaking our rules and up for a ban.*

**Comment by 7ekhed** [comment]
oh ok sry, but Is it possible to make it post the help in chat instead of a DM?

**Comment by Kowlin** [comment]
@7ekhed the bot will post the help in chat when it doesn't take up too much space, as soon as it starts taking up more then half a screen it will spit it out to DM.
