### ISSUE TITLE
[V3 Core] Setup should warn if replacing existing instance.

### ISSUE THREAD

**Issue by Aioxas** [Cog-Creators/Red-DiscordBot#1265]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [x] Suggestion
- [ ] Bug

### Brief description of the problem
Running redbot-setup with an existing redbot instance doesn't trigger any warnings, it just replaces it.
### Expected behavior
Warnings before anything is done and options to cancel or continuing.
### Actual behavior
Nothing, it continues as it is and replaces the existing instance values with the new instance values (same name)
### Steps to reproduce

1. Run redbot-setup
2. follow the instructions on creating a new instance.
3. Make a new instance
4. Check config.json or the flags for details on the instances...is there even one?
5. Repeat Steps 2-4 for another instance and check.

**Comment by tekulvw** [comment]
Fixed with #1469
