### ISSUE TITLE
V3 Beta 8

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1274]
V3 Beta 8 is due to be released on Sunday, February 11, 2018.

This will be updated as we further discuss the focus for this release.

**Comment by xxCoolxx18** [comment]
Great, awesome!

**Comment by palmtree5** [comment]
Changelog (also to be used for the announcement in Discord):

Enhancements:
- `[p]userinfo` now has support for the "Listening" and "Watching" statuses
- `[p]set listening` and `[p]set watching`
- Instances can now be removed without needing to take a backup
- `[p]cogs` now uses embeds
- The message given when a command raises an unhandled exception is now a fallback. Cogs that have a function called `__error` will use that instead of the fallback message
- Shared libraries support + smarter repo handling
- A prompt when trying to delete more than 100 messages at once using `[p]cleanup`
- setup functions for cogs can now be coroutines
- Automation of releases and uploading string sources to Crowdin for translation
- Cleanup of the config driver code
- Errors from `[p]load` and `[p]unload` are now viewable in `[p]traceback`

Bugfixes:
- Pinned nearly all dependencies to cut down on conflicts
- Fixed a bug with list defaults in config
- Fixed a typo in CogManagerUI
- Fixed TimeoutError in `[p]servers`
- Moved the `distro` dependency out of requirements.txt because of issues on Windows
