### ISSUE TITLE
[V2 Streamalert] Wrong error provided

### ISSUE THREAD

**Issue by PenguinNexus** [Cog-Creators/Red-DiscordBot#1287]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem

When using $streamalert twitch #testing, even after setting the Twitch Client-ID it generates an error.

### Expected behavior

Steam Alerts channel should be set to the stated channel

### Actual behavior

Error Returned: Owner: Client-ID is invalid or not set. See $streamset twitchtoken

### Steps to reproduce

1. Follow steps from https://twentysix26.github.io/Red-Docs/red_guide_twitch_clientid/
2. $streamset twitchtoken <token>
3. You will get the message "Twitch Client-ID set."
4. Execute the command $streamalert twitch #testing
5. You will get the error message "Owner: Client-ID is invalid or not set. See $streamset twitchtoken"

This has been confirmed by Yukirin from the support channel and it has been confirmed by testing.

**Comment by Twentysix26** [comment]
This is not how the command works. It sets the alert in the channel you're issuing the command in.
```
?streamalert twitch <stream>

Adds/removes twitch alerts from the current channel
```

The actual issue here is Red throwing an incorrect error and for that I'm leaving this issue open

**Comment by PenguinNexus** [comment]
Oh right, thanks :) I did however work from the documentation, so could that please be updated? :)

**Comment by Twentysix26** [comment]
Done

**Comment by PenguinNexus** [comment]
Thank you :)
