### ISSUE TITLE
[V2] Audio.py - Cache manager appears to remove youtubedl partial downloads.

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1297]
### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
Looks like we might have a possible race condition between youtube-dl and the cache manager in audio.py
Youtube-dl downloads to a .part then renames, cache manager seems to be dumping .part files (`_cache_required_files()` doesn't seem to include these)

https://github.com/Cog-Creators/Red-DiscordBot/blob/a3bd757120ee99429a59893db7e07dcdb04e9671/cogs/audio.py#L538-L568
There's the cache dump

Here's where the file's required are defined:
https://github.com/Cog-Creators/Red-DiscordBot/blob/a3bd757120ee99429a59893db7e07dcdb04e9671/cogs/audio.py#L374-L383

I'm not 100% sure I've properly tracked the issue back though, and would definitely appreciate a second set of eyes on this before I make a PR of any sort to audio.
### Expected behavior
Things still needed in the cache shouldn't get removed until they are no longer needed.

### Actual behavior
(copied from the support channel in discord)
```
Feb 10 19:06:11 inxa-bot python3.5[25727]: ERROR: unable to rename file: [Errno 2] No such file or directory: 'data/audio/cache/xvJKMyMzjos.part' -> 'data/audio/cache/xvJKMyMzjos'
Feb 10 19:06:12 inxa-bot python3.5[25727]: data/audio/cache/xvJKMyMzjos: No such file or directory
```

**Comment by brownmike** [comment]
I'm experiencing this exact issue right now. Typically seems to happen when the download is larger than normal.

**Comment by tekulvw** [comment]
Same issue as #844. Not sure if this is a large enough issue to revisit a fix for. Try setting your max cache size to a larger number.

**Comment by mikeshardmind** [comment]
#1481 should fix the issue.
