### ISSUE TITLE
[Mongo Driver] Cleanup inactive connections

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1300]

**Comment by Kowlin** [comment]
After doing some research it appears that the connection in reality is already a ConnectionPool. However its limited to 100 connections which is fine so long we clean up the connections every so often, and currently we don't. Once the limit of 100 connections is reached the driver will not send out any more information to the DB.

**Comment by tekulvw** [comment]
Fixed with #1356
