### ISSUE TITLE
Set delete delay to particular commands

### ISSUE THREAD

**Issue by Cazed** [Cog-Creators/Red-DiscordBot#1302]
Hi,

I would like to be able to set a delete delay for only particular commands, mainly one. How would this be possible to go about this?

If you cannot assist or really cannot be bothered, I understand. If you can point me in the right direction for help that would be fantastic.

Cazed

**Comment by calebj** [comment]
This would probably be implemented as a cog. See if someone has already made one and, if nobody has, post a request on the [cog board](https://github.com/Cog-Creators/Cog-Board/issues).

**Comment by tekulvw** [comment]
Agreed.
