### ISSUE TITLE
[V3] Downloader errors out on existing repo name conventions

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#1303]
### Type:

- [X] Suggestion
- [ ] Bug

### Brief description of the problem
Downloader will error out when given a repo name that contains dashes, like "aikaterna-cogs", when adding a repo. 

### Expected behavior
v3 Downloader should behave like v2 Downloader and allow a dash in repo names.
v3 Downloader specifically says in its help string: "Name can only contain characters A-z, numbers and underscore" but I feel like this should be addressed for ease of use with existing conventions.

### Actual behavior
Downloader will show `[p]repo add` command help instead of adding the repo.

### Steps to reproduce
1. Add a repo with a dash in the repo name
2. Type "I agree" to agree to the repo addition
3. Bot will display help message for repo add and not add the repo

**Comment by skmendez** [comment]
This is due to [the converter](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/cogs/downloader/repo_manager.py#L534) for RepoNames which checks to make sure they are Python identifiers. I am unsure of the purpose of this, but you could use "aikaterna_cogs".

**Comment by tekulvw** [comment]
Fixed with #1349
