### ISSUE TITLE
[v3] Add bot.pip_install

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#1306]
### Type:

- [x] Suggestion
- [ ] Bug

### Brief description of the problem
Red v3 has no equivalent of bot.pip_install yet

### Expected behavior
Would be nice to be able to load deps this way like v2

### Actual behavior
An error message.

### Steps to reproduce
1. Do [p]debug bot.pip_install
2. Cry a little on the inside when you get "AttributeError: 'Red' object has no attribute 'pip_install'"

**Comment by tekulvw** [comment]
Would it be alright if we added an actual command for this?

**Comment by aikaterna** [comment]
That would be great, and a little cleaner than using debug for it.

**Comment by tekulvw** [comment]
Added with #1354
