### ISSUE TITLE
Create second account in discord?

### ISSUE THREAD

**Issue by keltharthelegend** [Cog-Creators/Red-DiscordBot#131]
so it says to create a second account in discord not to use your own but then how do you sign into both at the same time?

**Comment by Kowlin** [comment]
The bot makes a session for its own account. As long as you run the bot from the .bat you'll run the bot
For more information feel free to drop by the support server.
https://discord.gg/0k4npTwMvTrnAaO1

**Comment by Twentysix26** [comment]
Make a new account on discordapp.com, join your server with it, logout. Use those account details when you do the configuration process. This will be the bot's account.
