### ISSUE TITLE
How would I make a variable in *my* `discord.py` bot that doesn't transfer across servers?

### ISSUE THREAD

**Issue by keeganjk** [Cog-Creators/Red-DiscordBot#1310]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [ ] Bug

### Steps to reproduce

1. 
2. 
3. 
4. 

I guess this isn't really an *issue*, but... How would I make a variable in *my* `discord.py` bot that doesn't transfer across servers?-- an example: I could make a customizable prefix, but when it's changed it changes on every server its connected to. How would I do this?

**Comment by Twentysix26** [comment]
>I guess this isn't really an issue  

Exactly

**Comment by keeganjk** [comment]
@Twentysix26 Could my question be answered, though?

**Comment by Twentysix26** [comment]
Not relevant to this repository

https://discord.gg/r3sSKJJ
https://discord.gg/discord-api
https://github.com/Rapptz/discord.py/
