### ISSUE TITLE
[v3] aiohttp-json-rpc has version conflict with aiohttp

### ISSUE THREAD

**Issue by NNTin** [Cog-Creators/Red-DiscordBot#1311]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem

Current requirements: yarl==0.18.0, **aiohttp>=2.0.0,<2.3.0**, appdirs, youtube_dl, raven, colorama, aiohttp-json-rpc, pyyaml, Red-Trivia
Installing aiohttp-json-rpc requires `aiohttp>=3,<3.1`, see here: https://github.com/pengutronix/aiohttp-json-rpc/blob/0a36f049e924994353f0de9064b4136f845858ec/setup.py

### Expected behavior

Installing Redv3 works fine and you can run `redbot-setup`.

### Actual behavior

It throws an error and asks for aiohttp>=3,<3.1: https://cdn.discordapp.com/attachments/387398816317440000/413839043277881345/unknown.png

### Steps to reproduce

1. Install Redv3
2. python3 -m pip install aiohttp-json-rpc==0.9.1
3. Run `redbot-setup`

### Fix

Lock aiohttp-json-rpc to an older version.

**Comment by wxMichael** [comment]
Latest working version in my testing was aiohttp-json-rpc==0.8.7

**Comment by Kowlin** [comment]
fixed with #1312, currently only on develop. Will be on Beta 8
