### ISSUE TITLE
[p]names <user> lists all server names not just user V3

### ISSUE THREAD

**Issue by unseenmagik** [Cog-Creators/Red-DiscordBot#1322]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [ X Bug

### Brief description of the problem
When running the command [p]names <user> on Redbot V3 Beta8 the list of previous names are shown for the server and not for that user. 

### Expected behavior
The previous names should be for the user you select only. 

### Actual behavior
When running the command [p]names <user> on Redbot V3 Beta8 the list of previous names are shown for the server and not for that user. What do you see. I see a list of all previous names that have been used for any one user on the server. it does not matter what user you select to check, the results are the same. 
![2018-02-19 14_51_59- bot_commands - discord](https://user-images.githubusercontent.com/30931287/36383588-8112d7ca-1584-11e8-8f13-9d2b14ab322b.png)

### Steps to reproduce

1.  run redbot v3 beta8
2.  command [p]names <user>
3.  results for previous names are not for that user but for the server. 
4.

**Comment by tekulvw** [comment]
This should have been fixed with #1308. You may need to reset your data file to get rid of bad previous data.

**Comment by unseenmagik** [comment]
I can confirm this is working now after a clean up of the data file. 
Closing
