### ISSUE TITLE
 'ClientUser' object has no attribute 'status'

### ISSUE THREAD

**Issue by Kio-td** [Cog-Creators/Red-DiscordBot#1328]
### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
Whilst trying to set what RED is listening to, she chooses to rather error out than be of use.
### Expected behavior
Show the documentation for [p]set listening
### Actual behavior
```
AttributeError: 'ClientUser' object has no attribute 'status'
[20/02/2018 01:34] ERROR events on_command_error 165: Exception in command 'set listening'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/core_commands.py", line 379, in _listening
    status = ctx.me.status
AttributeError: 'ClientUser' object has no attribute 'status'
```
### Steps to reproduce
(Edited)
1. Type one of the following:

- [p]set listening
- [p]set watching

**Comment by tekulvw** [comment]
Just FYI those commands can only be run while in a server. The PR to fix this will make sure you don't get an error message in the future.

**Comment by tekulvw** [comment]
I lied, that PR will now let the command run anywhere as long as the bot is in at least 1 server.

**Comment by Kio-td** [comment]
Heh. Luckily for me, I'm in 40. :3 
I'll update once released. Thanks~
