### ISSUE TITLE
[V3] Unable to find specified path

### ISSUE THREAD

**Issue by MorsVeVitae** [Cog-Creators/Red-DiscordBot#1329]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [  ] Suggestion
- [X] Bug

### Brief description of the problem
On load of cogs fresh from install everything seemed to work and load fine but checking my console it said that it couldn't find the path specified, even though it was suggested (this was when I noticed it)
### Actual behavior
Error, though it does not seem to have any effect on the bot:

```
Task exception was never retrieved
future: <Task finished coro=<RepoManager._load_repos() done, defined at C:\Users\fried\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\redbot\cogs\downloader\repo_manager.py:647> exception=FileNotFoundError(2, 'The system cannot find the path specified')>
Traceback (most recent call last):
  File "C:\Users\fried\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\redbot\cogs\downloader\repo_manager.py", line 649, in _load_repos
    for folder in self.repos_folder.iterdir():
  File "C:\Users\fried\AppData\Local\Programs\Python\Python36-32\lib\pathlib.py", line 1059, in iterdir
    for name in self._accessor.listdir(self):
  File "C:\Users\fried\AppData\Local\Programs\Python\Python36-32\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\fried\\AppData\\Local\\Red-DiscordBot\\Red-DiscordBot\\cogs\\RepoManager\\repos'
```
### Steps to reproduce

1. Install from command prompt - no voice
2. set up, suggested path, json
3. load cleanup, downloader, image, admin, mod, general, customcom, alias, modlog
4.

**Comment by tekulvw** [comment]
Fixed in #1330
