### ISSUE TITLE
How do I get Red to install on Fedora 23

### ISSUE THREAD

**Issue by Yandols** [Cog-Creators/Red-DiscordBot#133]
The linux install instructions on the wiki page are for an Ubuntu distro. I am using Fedora 23, how do I get it to work?

I already have Package `python-2.7.11-3.fc23.x86_64` and Package `git-2.5.5-1.fc23.x86_64` installed. What else do I do?

**Comment by franc-ist** [comment]
https://twentysix26.github.io/Red-Docs/red_install_fedora/

**Comment by Kowlin** [comment]
Fixed in support server.
