### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by natejb2003** [Cog-Creators/Red-DiscordBot#1338]
### Type:

- [ ] Bug

### Brief description of the problem

The Bot is offline in my server, and when running the launcher and Red, it says this:
`[Errno 1] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)]]
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /Users/<myname>/Documents/Folder/Discord Bots/Red-DiscordBot/cogs/streams.py:617> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x106d0a5e8>()]>>`

### Expected behaviour

The bot should be online and receiving commands

### Actual behaviour

Offline bot, no sign of life

### Steps to reproduce

1. Run launcher
2. Press "2" and enter
3. Done

**Comment by Twentysix26** [comment]
Check this #581
