### ISSUE TITLE
[V3] Load locale.po files with the encoding specified in their header

### ISSUE THREAD

**Issue by ZeLarpMaster** [Cog-Creators/Red-DiscordBot#1341]
### Type:

- [X] Suggestion
- [ ] Bug

### Description of the problem
Localized files are currently loaded in whatever encoding [locale.getpreferredencoding()](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding) returns (as specified in [open's documentation about encoding](https://docs.python.org/3/library/functions.html#open)) which may or may not be the right encoding depending on the platform.

### Potential solution
My suggested solution would be using the encoding specified in the locale.po's header with a fallback on chardet to guess the encoding.

**Comment by ZeLarpMaster** [comment]
I can try to implement it myself if this is deemed relevant.

**Comment by Tobotimus** [comment]
I like this proposal. It's not clear in Crowdin's documentation how they encode their files either, however taking a quick look at our current `.po` files it seems to be UTF-8. Either way, this sort of check can't hurt.

By all means, open a PR for this if you feel you can.

Just to confirm, this is the line you're looking at in the PO header:
```po
"Content-Type: text/plain; charset=UTF-8\n"
```

**Comment by Tobotimus** [comment]
Actually, it looks as though this was updated by #1365. Now all `.po` files are opened as UTF-8, not `locale.getpreferredencoding()`, which *should* work for the `.po` files we download from Crowdin.

However I'm going to leave this open since this issue addresses more than just using a standard encoding.

**Comment by tekulvw** [comment]
With the changes in #1365 I don't think this is strictly necessary anymore. If we run into future issues we can revisit this.
