### ISSUE TITLE
Playing audio files with no duration metadata

### ISSUE THREAD

**Issue by ebetica** [Cog-Creators/Red-DiscordBot#135]
https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/audio.py#L620

will crash and won't play audio files with no duration data (L623 also crashes). I hotfixed it on my private sever by replacing it with v.get('duration', 0), but that doesn't seem to be the most secure thing to do. Probably have an option to let people do that but set it off by default.

**Comment by irdumbs** [comment]
it shouldn't crash. It should spit out an error and then skip that video.

if there's no duration, how can you make sure the song is shorter than MAX_LENGTH?

**Comment by ebetica** [comment]
Yea, you're right, I never tested queuing more videos after it.

You can't, but some people would like the option to play things without a duration field. My specific use case is playing some .mp3 songs, which youtube-dl allows you to do and you can allow it in the server by adding the regex to the allowed links json file. Perhaps having an option to disable duration checking would work?

**Comment by tekulvw** [comment]
Encompassed by #185
