### ISSUE TITLE
[V3 Suggestion] pip uninstall

### ISSUE THREAD

**Issue by TheWyn** [Cog-Creators/Red-DiscordBot#1358]
V3 Beta 9 introduced pip install in downloader, why not include pip uninstall as well?

**Comment by Kowlin** [comment]
Mostly due the fact that cogs don't really need to uninstall python packages, if a user wants to uninstall a package, he might as well do it with Pip it self.

**Comment by tekulvw** [comment]
Not gonna add this. The pip install command installs to a folder containing bot data and as such, uninstall isn't really feasible.
