### ISSUE TITLE
[V3/Streams] Add youtube live to stream alerts

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#1359]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [x] Suggestion
- [ ] Bug

### Brief description of the feature
Add stream alerts for youtube. I have seen it requested a lot for v2, so I am moving the request over to v3.

**Comment by palmtree5** [comment]
#1385

**Comment by tekulvw** [comment]
Added with #1385
