### ISSUE TITLE
[Economy] A way to purchase things from a store with economy.py points

### ISSUE THREAD

**Issue by ddday** [Cog-Creators/Red-DiscordBot#136]
it would be nice if there were ways to spend points.
otherwise the money is useless except for slots.
Thanks for considering/taking a look!

**Comment by Kowlin** [comment]
Related to #110

**Comment by irdumbs** [comment]
a temporary solution:
my server really likes to !eat all their points... don't ask me..
is that a command other people want also? or are my buddies all just weird?

**Comment by ddday** [comment]
Well that would be nice if it kept a log of who eats how much

**Comment by ddday** [comment]
@irdumbs I've heard about your cogs, they're awesome

**Comment by irdumbs** [comment]
>.>
that is creepy

**Comment by ddday** [comment]
How so?
You're a legend <.<

**Comment by Novabella** [comment]
I've only seen one or two of your own commands @irdumbs . I would like to know what else you've made, and maybe if you're willing to share..?

**Comment by jaythesheep** [comment]
Agreed! Would be cool to have an advantaged economy system :)

**Comment by Kowlin** [comment]
A status update on this. 3rd party cogs can now use the economy API to give, take and check currency from a user. Example code is given below.

https://github.com/Kowlin/refactored-cogs/blob/master/buyrole/buyrole.py#L32-L85

**Comment by tekulvw** [comment]
Is this a feature we'd like to have in core v3 or should we leave this up to third party cog creators?

**Comment by palmtree5** [comment]
Let's leave this for third-party cogs
