### ISSUE TITLE
[V3 Downloader] [p]pipinstall has confirmation on empty value

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#1361]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Run [p]pipinstall with no arguments, bot will return "Libraries installed."

### Expected behavior
Run [p]pipinstall with no arguments, bot replies that it needs a package name

### Actual behavior
[p]pipinstall will have a confirmation message for no package specified.

### Steps to reproduce

1. [p]pipinstall

**Comment by tekulvw** [comment]
This is a leftover issue from #1313. You'll need to delete your downloader data files as the structure changed in #1313. Then if you want find cog to work you'll need to re-install the cogs you currently have installed so downloader will know about them.
