### ISSUE TITLE
[V3 Beta 9] [p]cogs and [p]repo list are not alphabetically listed

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#1363]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
The cog and repo lists are listed in a non-alphabetical order.

### Expected behavior
Should be alphabetical.

### Actual behavior
It isn't.

### Steps to reproduce
1. Try either command.

**Comment by tekulvw** [comment]
Fixed with #1424
