### ISSUE TITLE
[V3/Config] Clearing a registered data group when no data has been set results in a KeyError.

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#1364]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
When attempting to use methods such as `.clear_all_members` and `.clear_all_globals`, when no data has been set, will result in a KeyError being raised.
### Expected behavior
Silently passes
### Actual behavior
Key Error is raised.
### Steps to reproduce

1. register some data
2. try to clear all data from that scope
3. Key error is raised
4. You cry

**Comment by Tobotimus** [comment]
Fixed in #1374.
