### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by zubairfazal** [Cog-Creators/Red-DiscordBot#1368]
### Type:
- [x] Suggestion

### Brief description of the problem
Can we add sharding to redbot?

### Expected behavior
My bot is about to be in 2500 servers and I need sharding

**Comment by tekulvw** [comment]
This isn't possible in V2 because it will result in data corruption/loss.

**Comment by Kowlin** [comment]
Sharding is supported in v3, and done automatically. Sharding will not be back ported into v2, Closing.
