### ISSUE TITLE
Error at runtime

### ISSUE THREAD

**Issue by noidea88** [Cog-Creators/Red-DiscordBot#1369]
im getting this error when running on cento's 6. 

with the command: python3.5 launcher.py

==========================
Red Discord Bot - Launcher
==========================

1. Run Red /w autorestart in case of issues
2. Run Red
3. Update
4. Install requirements
5. Maintenance (repair, reset...)

0. Quit
> Traceback (most recent call last):
  File "launcher.py", line 570, in <module>
    main()
  File "launcher.py", line 528, in main
    choice = user_choice()
  File "launcher.py", line 408, in user_choice
    return input("> ").lower().strip()
EOFError: EOF when reading a line

Thanks

**Comment by tekulvw** [comment]
What key combo did you hit? Ctrl+D?

**Comment by noidea88** [comment]
didin't entered any key combo, just copy/paste the line like in tutorial : python3.5 launcher.py ; and generate this menu and give that error without i press any key

**Comment by Kowlin** [comment]
Perhaps don't copy & paste then and just type it over. Sometimes you will copy a new line into it.

**Comment by tekulvw** [comment]
Not fixing this, for now at least
