### ISSUE TITLE
Economy output overhaul

### ISSUE THREAD

**Issue by Stradinius** [Cog-Creators/Red-DiscordBot#1371]
### Type:

- [X] Suggestion
- [ ] Bug

This suggestion specifically refers to the payday command. I'd like to have payday show the following lines all within one message:

Here, take some credits. Enjoy! (+ {(Credits gained)} credits)
You currently have {(Current balance)} credits.
You're currently #{(Position on the leaderboard, only if the user is actually on the leaderboard)} on the leaderboard!  Congrats!

I imagine the one that would present the most issue is the leaderboard position, though I'm not sure.

Having the user use payday and then making them use [p]bank balance after the fact to see how many credits they have feels like it could get annoying.

Also, a question.  If I were to make these changes locally, considering they're part of a core cog, would an update to the economy cog on the developer's side overwrite my changes?  And if so, is there any way to prevent this?

(Moved from Red-Docs, because I was stupid and didn't realize I was posting it there.  When I brought this up in #coding, I was told to make an issue here.)

**Comment by tekulvw** [comment]
Suggestions added in #1386
