### ISSUE TITLE
Cant instal aiohttp

### ISSUE THREAD

**Issue by Malvert223** [Cog-Creators/Red-DiscordBot#1377]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [-] Bug

### Brief description of the problem
When i try to instal requeriments the bot try to install aiohttp and other things, but when the aiohttp start the installation say that (  Running setup.py install for aiohttp ... error
Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 11: invalid continuation byte
### Steps to reproduce

1. 
2. 
3. 
4.

**Comment by tekulvw** [comment]
Not really an issue we can do anything about, try installing again or reaching out to the aiohttp project.
