### ISSUE TITLE
[Sugestion] Using string constants for bot translation

### ISSUE THREAD

**Issue by DiEVeXx** [Cog-Creators/Red-DiscordBot#139]
It would be amazing to have all the constant strings in order to perform the translation of the bot into several languages.

It would be a quick cut and paste for translating the bot in future updates.

Thanks for ur time
And sorry for my bad english :P

**Comment by Kowlin** [comment]
The idea is interesting in it self. But as far as I remember the bot will need to be rewritten to account for that.

**Comment by Twentysix26** [comment]
Probably not a total rewrite but it would require massive changes that I'm not willing to do
