### ISSUE TITLE
V3 Third party cog list

### ISSUE THREAD

**Issue by bobloy** [Cog-Creators/Red-DiscordBot#1398]
## (dev edit): GO TO https://index.discord.red INSTEAD FOR AN INDEX OF THIRD-PARTY REPOS

**Comment by TrustyJAID** [comment]
https://github.com/TrustyJAID/Trusty-cogs/tree/V3

**Comment by Aioxas** [comment]
https://github.com/Aioxas/ax-cogs/tree/V3 meow

**Comment by Redjumpman** [comment]
https://github.com/Redjumpman/Jumper-Plugins/tree/V3

**Comment by tmercswims** [comment]
https://github.com/tmercswims/tmerc-cogs/tree/v3

**Comment by retke** [comment]
https://github.com/retke/Laggrons-Dumb-Cogs branch `v3`

**Comment by hatred2k** [comment]
https://github.com/hatred2k/hatredv3-cogs

**Comment by PaddoInWonderland** [comment]
Just a recent name change: https://github.com/PaddoInWonderland/ValeOfMushrooms

**Comment by Wyn10** [comment]
https://github.com/Wyn10/Wyn-RedV3Cogs

**Comment by retke** [comment]
List of available cogs:

## Fox-V3

- ccrole
- chatter
- coglint
- fight
- hangman
- howdoi
- leaver
- lseen
- reactrestrict
- sayurl
- secrethitler
- stealemoji
- werewolf

## Sinbad-Cogs

- bansync
- calculator
- embedmaker
- genreplace
- guildblacklist
- guildwhitelist
- messagebox
- relays
- roomtools
- tabletoputils

## ValeOfMushrooms

- grenzpolizei
- lastfm

## palmtree5-cogs

- banrole
- eventmaker
- hpapi
- lockdown
- tweets
- mcsvr
- messagepinner
- reddit
- slowmode
- srrecords
- tweets

## aikaterna-cogs

- pingtime
- chatchart
- away

## Squid-Plugins

- hipchat_relay
- logger
- reactrole
- tippr

## ZeCogsV3

- roles_react

## Trusty-cogs

- activity
- addimage
- anime
- autorole
- backup
- badges
- blockchain
- chatter
- cleverbot
- conversions
- covfefe
- decode
- dev
- emojireact
- faces
- gab
- halo
- hockey
- hue
- imagemaker
- imgflip
- insult
- juche
- mock
- modlogs
- pillconvert
- qposts
- reee
- rekt
- starboard
- stickyroles
- tarot
- translate
- trump
- trustyavatar
- trustybot
- tweets
- weather
- welcome

## ax-cogs

- advgoogle
- emote
- geico
- horoscope
- loot
- lootbox
- points
- strawpoll
- trove
- welcome

## Jumper-Plugins

- animelist
- casino
- dicetable
- jisho
- russianroulette
- shop

## tmerc-cogs

- catfact
- lenny
- massdm
- nestedcommands
- randimals
- streamrole
- welcome

## Laggrons-Dumb-Cogs 

- instantcommands
- roleinvite
- say

## hatredv3-cogs

- fortnite
- randomanimal
- screenshot
- urlshortener

## Wyn-RedV3Cogs

- anisearch
- sysinfo

**Comment by HarukiGrande** [comment]
https://github.com/HarukiGrande/GrandeCogs-V3

**Comment by mikeshardmind** [comment]
Not sure who scraped my repo, but there's an awful lot on there that isn't valid cog installation targets.
Here's an up to date list on mine:

+ bansync: Synchronize bans
+ calculator: Safely allow math evals
+ embedmaker: Embeds
+ guildblacklist: server join blacklist
+ guildwhitelist: server join whitelist
+ messagebox: replaces contact with a command dumping stuff in a channel
+ polling: polling via emoji utils
+ quotetools: Quote messages by ID
+ relays: Forwards messages
+ rolemanagement: Role Management tools
+ roomtools: Tools for temporary rooms
+ stickyroles: No role evasion

**Comment by The-Tasty-Jaffa** [comment]
My v3 cogs are at `https://gitlab.com/The_Tasty_Jaffa/Tasty-Jaffa-cogs` and the branch is `v3/release`
(Note: It's a Gitlab repo not Github as I have moved my development to Gitlab (so many new features to me))

**Comment by javascripto** [comment]
https://github.com/javascripto/syxcogs V3 Cogs, simple and clean but haven't seen such as them.

**Comment by coltoutram** [comment]
https://github.com/coltoutram/Colts-Cogs v3 cogs are in main branch, develop branch is what I'm testing so dont include those cogs.

**Comment by bobloy** [comment]
Added all the posted repos besides the V2 one

**Comment by coltoutram** [comment]
Hey you put mine up as liante-cogs instead of Colts-Cogs 🤔

**Comment by The-Tasty-Jaffa** [comment]
Ah, ever so slight issue with cogs that are available in my repo.
Currently "rolealert" (Which used to be called rolenotifier) is the only cog available for v3 (for now). (Sends alerts to channels and or users when they gain a set role).


Side note: I'm not sure about separating github from gitlab repos, although it does make the slight difference clear.

**Comment by unseenmagik** [comment]
Good day all, Here is the repo for my v3 cogs. 

https://github.com/unseenmagik/MagikCogsv3

Corrently 4 available

Avatar
Battleship
Distance
Members

**Comment by unseenmagik** [comment]
Why was my repo deleted ?

**Comment by PaddoInWonderland** [comment]
Several cogs have been added to my repo, including:

- customroles
- invoice
- openweather
- tickets

**Comment by Tobotimus** [comment]
I've finally added my own cogs to the list as well, https://github.com/Tobotimus/Tobo-Cogs branch V3

**Comment by zephyrkul** [comment]
https://github.com/zephyrkul/FluffyCogs

- act: Lets you command the bot to perform an action on someone else.
- skyrim: Say a random line from Skyrim. WARNING: Spoilers for Skyrim.
- theme: Allows you to set themes to easily play accross all servers.

**Comment by thisisjvgrace** [comment]
made this improved updated version of V3 cogs list in table format. Table for Fox-V3 cogs taken from it's repo README, not my work but it inspired me to make this. :D 
Please improve further if you guys feel like.


# List of Available Cogs for Red-DiscordBot V3:

## [Fox-V3](https://github.com/bobloy/Fox-V3)

| Name | Status | Description (Click to see full status)
| --- | --- | --- | 
| ccrole | **Beta** | <details><summary>Create custom commands that also assign roles</summary>May have some bugs, please create an issue if you find any</details> |
| chatter | **Alpha** | <details><summary>Chat-bot trained to talk like your guild</summary>Missing some key features, but currently functional</details> |
| coglint | **Alpha** | <details><summary>Error check code in python syntax posted to discord</summary>Works, but probably needs more turning to work for cogs</details> |
| fight | **Incomplete** | <details><summary>Organize bracket tournaments within discord</summary>Still in-progress, a massive project</details> |
| flag | **Alpha** | <details><summary>Create temporary marks on users that expire after specified time</summary>Ported, will not import old data. Please report bugs</details> |
| forcemention | **Alpha** | <details><summary>Mentions unmentionable roles</summary>Very simple cog, mention doesn't persist</details> |
| hangman | **Alpha** | <details><summary>Play a game of hangman</summary>Some visual glitches and needs more customization</details> |
| howdoi | **Incomplete** | <details><summary>Ask coding questions and get results from StackExchange</summary>Not yet functional</details> |
| leaver | **Alpha** | <details><summary>Send a message in a channel when a user leaves the server</summary>Just released, please report bugs</details> |
| lseen | **Alpha** | <details><summary>Track when a member was last online</summary>Alpha release, please report bugs</details> |
| reactrestrict | **Alpha** | <details><summary>Removes reactions by role per channel</summary>A bit clunky, but functional</details> |
| sayurl | **Alpha** | <details><summary>Convert any URL into text and post to discord</summary>No error checking and pretty spammy</details> |
| secrethitler | **Incomplete** | <details><summary>Play the Secret Hitler game</summary>Concept, no work done yet</details> |
| stealemoji | **Alpha** | <details><summary>Steals any custom emoji it sees in a reaction</summary>Some planned upgrades for server generation</details> |
| timerole | **Alpha** | <details><summary>Add roles to members after specified time on the server</summary>Upgraded from V2, please report any bugs</details> |
| tts | **Alpha** | <details><summary>Send a Text-to-Speech message as an uploaded mp3</summary>Alpha release, please report any bugs</details> |
| qrinvite | **Alpha** | <details><summary>Create a QR code invite for the server</summary>Alpha release, please report any bugs</details> |
| werewolf | **Alpha** | <details><summary>Play the classic party game Werewolf within discord</summary>Another massive project currently being developed, will be fully customizable</details> |

## [SinbadCogs](https://github.com/mikeshardmind/SinbadCogs)

| Name | Description
| --- | --- | 
| antimentionspam | <details><summary>mass mention filter</summary>This is an initial bare bones port of the v2 cog, more to come on this.</details> |
| bansync | <details><summary>Ban a user across all servers the bot is in, or sync bans between multiple servers</summary>Read the help first, this has some dangerous commands when misused</details> |
| calculator | <details><summary>Uses resource limited subprocess and asteval to (safely) parse math</summary>This only works on bots running as root (setrlimit syscall)...</details> |
| embedmaker | Highly featured embed creation |
| guildblacklist | blacklist guilds by guild or owner ID |
| guildwhitelist | whitelist guilds by guild or owner ID |
| linkjoinkiller | <details><summary>Kills users joining with an invite link in name</summary>no server specific settings, load at own risk.</details> |
| messagebox | replaces contact with a command dumping stuff in a channel |
| polling | polling via emoji utils |
| quotetools | <details><summary>Quote messages by messageID</summary>Gets messages by ID. Works across all the channels and servers the bot is in.</details> |
| relays | <details><summary>Relays messages across channels</summary>see `help Relays` for more info</details> |
| rolemanagement | <details><summary>Role Management tools</summary>React roles with requirements, selfroles with requirements, role based member search and more. A lot of this is still subject to large changes as needed.</details> |
| roomtools | Never run out of voice lobbies again |
| stickyroles | No role evasion |
| zalgosearch | <details><summary>Kill zalgo names</summary>Note: This will attempt to work everywhere right now, not config yet</details> |

## [ValeOfMushrooms](https://github.com/PaddoInWonderland/ValeOfMushrooms)

| Name | Description
| --- | --- | 
| customroles | Admins can add roles, users can engage or disengage roles. |
| grenzpolizei | Be a despotic dictator and keep tabs on every member on the server. |
| invoice | Add a role when a member enters voice channels |
| lastfm | Get currently playing and recently played tracks from Last.fm |
| openweather | Get the weather from OpenWeather. |
| tickets | A ticket system that works with channels |

## [palmtree5-cogs](https://github.com/palmtree5/palmtree5-cogs/tree/redv3-rewrites)

| Name | Description
| --- | --- | 
| banrole | Ban and unban by role |
| eventmaker | Event manager utility. Allows for creating and joining events and provides a notification at the start time |
| hpapi | <details><summary>Cog for getting info from the Hypixel API</summary>Gets data from the Hypixel API including player stats, guild info, and active boosters</details> |
| lockdown | <details><summary>Cog for locking down a server in the event of a raid</summary>Locks down a server using roles to affect users below the lockdown role</details> |
| mcsvr | Gets the status of a Minecraft Server (specifically version and player count) |
| messagepinner | Pins messages containing configured pin trigger text |
| reddit | Gets posts, user info, etc from Reddit's API |
| slowmode | Slow mode in Discord. Enforces a limit of one message per set time on non-exempt users |
| srrecords | Gets world records for the specified game from speedrun.com |
| tweets | Cog for getting public info from Twitter API |

## [aikaterna-cogs](https://github.com/aikaterna/aikaterna-cogs/tree/v3)

| Name | Description
| --- | --- | 
| away | Set and unset a user as being away. Originally by Paddo. |
| blurplefy | Blurplefy a user profile picture or image. |
| chatchart | Generate a pie chart from the last 5000 messages |
| dungeon | <details><summary>Specialized raid protection.</summary>Provides additional raid protection for servers utilizing a welcome/rules join channel.</details> |
| inspirobot | Fetch 'inspiring' messages. |
| partycrash | Posts existing server invites. |
| pingtime | It's ping... with latency. Shows all shards. |
| retrosign | [A port of Anismash's retrosign cog for v2](https://github.com/Anismash/Ani-Cogs/tree/master/retrosign) |
| rndstatus | <details><summary>Random bot statuses</summary>with an optional bot stats mode. Ported from Twentysix's v2 cog.</details> |
| seen | Check when the user was last active on a server. Originally made by Paddo. |
| wolfram | Query Wolfram Alpha for answers. |

## [Squid-Plugins](https://github.com/tekulvw/Squid-Plugins/tree/rewrite_cogs)

| Name | Description
| --- | --- | 
| hipchat_relay |  |
| logger |  |
| reactrole | Automatic roles from reactions. |
| tippr |  |

## [ZeCogsV3](https://github.com/ZeLarpMaster/ZeCogsV3)

| Name | Description
| --- | --- | 
| birthdays | Announce birthdays and give a role during people's birthdays |
| react_roles | Associate reactions on messages with a role |
| reminder | <details><summary>Allows users to remind themselves about anything they want</summary>Lets users tell the bot to remind them about anything they want. There is no limit to how many reminders one user asks for.</details> |

## [Trusty-cogs](https://github.com/TrustyJAID/Trusty-cogs/tree/V3)

| Name | Description
| --- | --- | 
| activity | Tracks activity on a server and kicks members not active in a while! Also sends an invite URL |
| addimage | Add image for the bot to directly upload similar to alias. |
| anime | Set a channel to show which anime is currently airing! |
| autorole | Automaticall apply roles when a user joins the server |
| backup | Backup all channel messages on a server. |
| badges | Create your own badge! |
| blockchain | Allows you to input a transaction from the blockchain and retrieve hidden information inside. |
| chatter | Talk to your bot and build a unique dataset for conversations! |
| cleverbot | Have your bot respond with cleverbot responses |
| compliment | Compliment people in a creative way |
| conversions | Conversions for BTC, currencies, precious metals, and stocks. |
| covfefe | Covfefeify any words! |
| decode | DNA and binary encoding/decoding of messages |
| dev | made the dev commands an importable cog using legacy sudo command |
| emojireact | React to messages containing any emojis! |
| faces | Japanese faces courtesy of the CIA |
| fun | The fun cog from Appu's Selfbot rewritten for redbot V3 including adding reactions and other "fun" commands. |
| gab | Checks if a user is on gab |
| halo | Gathers information from the Halo API and posts it on discord. |
| hockey | Gather hockey information from nhl.com and display in discord. |
| hue | A cog to control Philips Hue lights through discord. Not tested with bots outside the home network. |
| imagemaker | Show how you really feel. |
| imgflip | Recreation of Red v1 meme generator |
| insult | Insult people in a creative way |
| juche | Have the bot correct the current year to the Juche Calendar |
| mock | Mock the user who last posted! |
| modlogs | A more in-depth modlog cog for more information about users joining/leaving and messages edited/deleted. |
| notsobot | Work on converting some notsobot commands to redbot. Hopefully avoiding Image Magick. |
| pillconvert | a cog to upload any colour pill image. |
| qposts |  Gathers new Q posts from 8ch.net and posts them in discord. |
| reee | <details><summary>Posts various sized images based on specific triggered command lengths.</summary>May be customized manually for different images or by default express ones true rage.</details> |
| rekt | a command to see how rekt someone is. |
| runescape | a cog to grab Runescape 3 stats and profile information |
| serverstats | <details><summary>Get information about servers the bot is on.</summary>This cog provides a ton of useful development functions for gathering channel data and user data as well as providing a way to setup a channel to monitor which servers are adding the bot.</details> |
| serverwhitelist | Sets a whitelist for redbot to leave unapproved servers. |
| starboard | Create a starboard channel to save those amazing posts! |
| stickyroles | Keep user roles when they leave the server and re-join. Useful for muted roles. |
| tarot | Find your tarot reading, your life reading, or pull a random tarot card! Can also search for a card. |
| translate | <details><summary>Add flag emojis to messages to translate to that language or translate messages by command.</summary> (Uses Google Translate and may incur some fees)</details> |
| trump | Make your own Declaration signed by Trump. |
| trustyavatar | The cog that controls TrustyBot's changing Avatar image. It may be manually customized to ones liking. |
| trustybot | <details><summary>A collection of commands for Messing around with.</summary>Some functions may find their way to a more versatile cog eventually.</details>
| tweets | A modified version of Palm's twitter cog utilising twitter streams to setup a twitter channel to post user tweets. |
| weather | check the current weather in many cities around the world including in Kelvin. |
| welcome | Welcomes users to the server |

## [ax-cogs](https://github.com/Aioxas/ax-cogs/tree/V3)

| Name | Description
| --- | --- | 
| advgoogle | Retrieves results from Google |
| emote | Local emote summoning, has the ability to add, remove, or list emotes. Based on irdumb's sadface cog |
| geico | Online quote retrieval |
| horoscope | Zodiac and Chinese Horoscope and Fortune Cookie cog |
| loot |  |
| lootbox |  |
| points | Keep a tally of points |
| strawpoll | Create a strawpoll |
| trove |  |
| welcome | Welcomes new users to your server(s) |

## [Jumper-Plugins](https://github.com/Redjumpman/Jumper-Plugins/tree/V3)

| Name | Description
| --- | --- | 
| casino | Casino style mini games. Play up to 7 unique games and earn currency. |
| dicetable | Outputs multiple dice rolls into a table. |
| jisho | Translate English to Japanese and vice-versa |
| pokedex | View standard pokemon information, Movesets, TM learn-sets, search items, and pokemon locations. |
| raffle | Create reaction based raffles with timers that persist through restarts and shutdowns. |
| russianroulette | Play a game of Russian Roulette! |
| shop | Create, buy, trade, and redeem items. |

## [tmerc-cogs](https://github.com/tmercswims/tmerc-cogs/tree/v3)

| Name | Description
| --- | --- | 
| catfact | Gets a random cat fact. |
| lenny | ( ͡° ͜ʖ ͡°) |
| massdm | Send a direct message to all members of the specified Role. Personalize the message for each person. |
| nestedcommands | Experimental cog that allows you to use the output of one command as the input of another. |
| randimals | Get some random animal images. |
| streamrole | Assign a configurable role to anyone who is streaming. |
| welcome | Announces members joining, leaving, getting banned & getting unbanned, in a customizable text channel & with customizable messages. |

## [Laggrons-Dumb-Cogs](https://github.com/retke/Laggrons-Dumb-Cogs/tree/v3)

| Name | Description
| --- | --- | 
| instantcmd | Command and listener maker from a code snippet through Discord |
| roleinvite | <details><summary>Autorole based on the invite the user used.</summary>If the user joined using invite x, he will get a list of roles linked to invite x.</details> |
| say | Speak as the bot through multiple options. Allow file upload, rift in DM and specific destinations. |

## [hatredv3-cogs](https://github.com/hatred2k/hatredv3-cogs)

| Name | Description
| --- | --- | 
| fortnite | View fortnite stats |
| randomanimal | Post random dog and cat pictures. |
| screenshot | Screenshots a web page |
| urlshortener | Shorten and expand any url using goo.gl |

## [Wyn-RedV3Cogs](https://github.com/Wyn10/Wyn-RedV3Cogs)

| Name | Description
| --- | --- | 
| anisearch | A cog to search anime, manga, users and characters from the anilist API  |
| sysinfo | Uses psutil to show various system information for the machine running the bot |

## [PumCogs](https://github.com/PumPum7/PumCogs)

| Name | Description
| --- | --- | 
| emoji_steal | Steal/Upload custom emojis to your server using red bot. |
| giveaway | Create giveaways using Red Bot. |
| imageediting | Edits images using PIL |
| nicknamechanger | Checks nicknames and removes/changes special characters like ü or ◔ |

## [GrandeCogs-V3](https://github.com/HarukiGrande/GrandeCogs-V3)

| Name | Description
| --- | --- | 
| bash | Simple bash shell within Discord |
| freelancer | Freelancer Server Stats |
| nsfw | Posts NSFW Images From X Sites |
| opennic | OpenNIC Server Searching Tool |
| orly | Generate O Rly? Images |
| reddit | Reddit commands |
| scanport | Scan server ports |
| yugioh | YuGiOh Card Info & Prices |

## [Liante-Cogs](https://github.com/Liante-0216/Liante-Cogs)

| Name | Description
| --- | --- | 
| levels | A per-server leveling system with automatic roles. |

## [Colts-Cogs](https://github.com/coltoutram/Colts-Cogs)

| Name | Description
| --- | --- | 
| actionlogs | Action Logs, log message deletes, edits, user activity, bans and much more. |
| autorole | Automatically adds a role to users who join your server. |
| bancheck | Check if user is banned on https://bans.discordlist.net/ |
| massmove | Massmove users to another voice channel, use channel ID's from the voice channels. |
| penis | Detects users' penis size with maximum accuracy. |
| ping-time | Pings the server and shows the latency. |
| playskip | Plays and skips the current song. |
| speedtest | Runs a speedtest and prints the result, uses speedtest-cli. |
| sysinfo | Uses psutil to show various system information for the machine running the bot |

## [Tasty-Jaffa-cogs](https://gitlab.com/The_Tasty_Jaffa/Tasty-Jaffa-cogs/tree/v3/release)

| Name | Description
| --- | --- | 
| rolealert | Sends a custom message when someone gains a role |
| tempvoice | Creates voice channels that will be deleted once empty |

## [Tobo-Cogs](https://github.com/Tobotimus/Tobo-Cogs/tree/V3)

| Name | Description
| --- | --- | 
| docref | <details><summary>Search for references on documentation webpages.</summary>DocRef allows you to look up references on documentation webpages by their sphinx object names - this includes any documented python object! The documentation webpages must be added to the bot with a site name (of your own choice) and URL. The documentation webpages must be generated by sphinx (this includes almost every documentation page on ReadTheDocs).</details> |
| errorlogs | <details><summary>Log error tracebacks in text channels.</summary>ErrorLogs automatically outputs tracebacks of command errors in any text channel(s) you specify. It includes per-channel settings to determine whether global or server-wide errors should be posted.</details> |
| reactkarma | <details><summary>Like Reddit Karma, but with discord reactions!</summary>ReactKarma is a cog for counting upvotes and downvotes of everyone the bot sees. The karma leaderboard is global, however the cog can be effectively enabled and disabled per-server.</details> |
| register | <details><summary>Simplifies two SelfRole commands into one.</summary>Register adds a single command, which is effectively an alias for the commands `[p]selfrole` and `[p]selfrole remove`. The point is to have one command which does both adding and removing of selfroles, depending on whether or not the role is already applied to the user.</details> |
| sticky | <details><summary>Sticky messages for your channels!</summary>Sticky is a cog for sticking a message at the bottom of a channel. When a user sends a message in that channel, the bot will delete its old message and repost it, so it 'sticks' to the bottom.</details> |
| streamroles | <details><summary>Hoist users streaming on Twitch.</summary>StreamRoles is a cog for automatically assigning roles to users streaming on Twitch. The cog is also able to only assign a streaming role to users of a particular game. Specific users can also be blacklisted and whitelisted.\n\nDisclaimer: The first streamrole cog was made by tmerc, as some of you may know. This cog was written completely from the ground up by myself, and although I was unaware he had written a similar cog already, he should be given credit for coming up with the idea first.</details> |
| strikes | <details><summary>Strike misbehaving users.</summary>Strikes is a cog for helping moderation teams warn and keep track of misbehaving users. Strikes are filed with a reason and timestamp, and the cog is helpful for knowing how many times the user has misbehaved *recently*. ModLog integration is also available.</details> |
| updatered | <details><summary>A command to update Red!</summary>UpdateRed is a cog for updating your bot from within discord. When combined with the ability to restart the bot, updating Red becomes a easier than ever!\n\nYou can choose from multiple automatic versions, or specify a particular version you'd like to install.</details> |
| welcomecount | <details><summary>Customisable welcome messages.</summary>WelcomeCount is a cog for sending customisable and context-based welcome messages to new users. It's named after it's main feature - it counts how many members have joined each day, and this can be included in the welcome message.</details> |

**Comment by zephyrkul** [comment]
Forgot to note that I added another cog.

- rift: Allows cross-server communication through Red.

**Comment by skeith** [comment]
I have started the fire of v3 conversion and dev of my repo
https://github.com/skeith/MayuYukirin

**Comment by Fightergaming4** [comment]
here's mine. this is main and v1,  main has no files in it since I am making sub-branches for version updating.
main: https://github.com/Fightergaming4/fg4-cog
v1: https://github.com/Fightergaming4/fg4-cog/tree/v1
v2: COMING SOON

**Comment by yamikaitou** [comment]
@Fightergaming4 That is not how repos work, they already track version history. You should be putting all your cogs into 1 branch and then just updating them there. The way you are doing it now means that if anyone wants to get your update, they must remove your cog and repo and then re-add it.

**Comment by retke** [comment]
And the only cog you have is just sending default emojis, and a link to an unknown server. Cogs are supposed to bring unique things through the bot.

**Comment by Fightergaming4** [comment]
> 
> 
> @Fightergaming4 That is not how repos work, they already track version history. You should be putting all your cogs into 1 branch and then just updating them there. The way you are doing it now means that if anyone wants to get your update, they must remove your cog and repo and then re-add it.

I will go fix it.



> 
> 
> And the only cog you have is just sending default emojis, and a link to an unknown server. Cogs are supposed to bring unique things through the bot.

it is not an unknown server, it is red bot's cog support server.

**Comment by Fightergaming4** [comment]
updated cog link: https://github.com/Fightergaming4/fg4-cog

**Comment by zephyrkul** [comment]
Added a couple more cogs.
- clocks: Track projects with clocks.
- logsfrom: Log a specified channel to a markdown file.

The clocks one was a request for use with Blades in the Dark, a tabletop rpg we play on my server, so it may not have as much universal appeal as the rest of my amazing and wonderful cogs, but may as well pad out my repo when I write a cog that others might end up finding useful! 🛅

**Comment by Malarne** [comment]
https://github.com/Malarne/discord_cogs

- Boobs cog: update for v3 of oboobs cog by Mash
- Leveler cog: as name says, a leveler for v3, strings are only in french for now, feel free to make a PR to translate to english or add support for i18N (too lazy LUL)
- Roles cog: an old cog that i need to update, do not use that lol

**Comment by Kowlin** [comment]
Oh boy, I hope there aren't requirements on this, but ehh. I'm just gonna dump it here cause why now :P.

https://github.com/Kowlin/Sentinel My collection of cogs (which is small ATM, but who said small things are bad :smirk:)

 * Massmove, port from v2, mass move members over to another channel or the AFK channel
 * Freshmeat, a port from Irdumb's v2 alias to show the latest members in X hours.

**Comment by Purrhood** [comment]
sorry I deleted my other account ^
                                                      |

**Comment by bobloy** [comment]
@Purrhood your cogs need an `info.json` file each to be installed via downloader properly. Take a look at one of the other repos for an example.

Also, a description of what each of the cogs is would help

**Comment by Purrhood** [comment]
Thank you bobloy..

**Comment by purrhood** [comment]
Is it possible to remove my cog list? Thank you!

**Comment by palmtree5** [comment]
Closing in favor of https://cogboard.red/t/approved-repositories/210
