### ISSUE TITLE
Help me plz

### ISSUE THREAD

**Issue by stampysmith** [Cog-Creators/Red-DiscordBot#1399]
Red Discord bot active code 65001

**Comment by Kowlin** [comment]
You're not providing any error, information or other stuff that helps to explain your issue. Please explain the issue with the format that you've not used.

**Comment by tekulvw** [comment]
He can open another one, correctly, if he wants.

**Comment by stampysmith** [comment]
??

**Comment by pgaetani** [comment]
Provide the full error and a description of what you were doing in a new issue, "Red Discord bot active code 65001" says absolutely nothing.
