### ISSUE TITLE
Audio Error

### ISSUE THREAD

**Issue by Anismash** [Cog-Creators/Red-DiscordBot#140]
Newest Update with the bot (right before i wrote this) and everytime it should start a song, the bot audio module break and he won't leave with [prefix]stop the channel. The error message is this: http://pastebin.com/P5u9tSki

All the other commands still work but the bot can't leave or play anything in the channel.
PS.working with Ubuntu

**Comment by Kowlin** [comment]
Ensure that you also have discord.py updated.

**Comment by Anismash** [comment]
My bad.
Now it works. 
Thanks
