### ISSUE TITLE
[V3 Admin] [p]announce cancel command is not functioning normally.

### ISSUE THREAD

**Issue by endms3231** [Cog-Creators/Red-DiscordBot#1410]
### Type:

- Bug

### Brief description of the problem
first, [p]announce testing scarlet announcement
second, [p]announce cancel
third, "testing scarlet announcement" message was dosen't delete from set on channel.
### Expected behavior
the announcement message was removed.
### Actual behavior
"The current announcement has been cancelled." this message was seen but message was not deleted.
### Steps to reproduce

1. [p]announce testing scarlet announcement
2. [p]announce cancel
3. "testing scarlet announcement" message was dosen't delete from set on channel.
4. both Korean and English are the same phenomenon.

**Comment by tekulvw** [comment]
That's not a bug, it was never an intended feature.

**Comment by Second-Epsilon** [comment]
Uh...

**Comment by endms3231** [comment]
Isn't this a problem?

**Comment by tekulvw** [comment]
We're not changing the functionality.
