### ISSUE TITLE
[V3 Launcher] Unable to [6]Remove Instance on Windows

### ISSUE THREAD

**Issue by bobloy** [Cog-Creators/Red-DiscordBot#1411]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Unable to remove a v3 instance using red-launcher

### Expected behavior
Bot would be removed successfully

### Actual behavior
https://cdn.discordapp.com/attachments/387398816317440000/420967871678775306/unknown.png

### Steps to reproduce

1.  Create RED instance with default settings on windows
2.  Install any cogs _(maybe unneeded)_
3.  Use red-launcher to remove the instance

**Comment by tekulvw** [comment]
Fixed with #1412
