### ISSUE TITLE
[V3] [Help formatter] Field values exceeding limits

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1414]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem

Pagination inconsistently raising a 400 Error

### Expected behavior

Pagination should properly respect limits

### Actual behavior
[Traceback](https://gist.github.com/mikeshardmind/e6d3ed79d740b5251925aa0dc7449fad)
### Steps to reproduce
```
[10:46 AM] Sinbad: @Rachael Rosen help
[10:46 AM] BOTRachael Rosen: CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
[10:46 AM] BOTRachael Rosen: Error in command 'help'. Check your console or logs for details.
[10:46 AM] Sinbad: r, help
```

### Additional information

`r, ` is a prefix and the bot is also mentionable
red Version: 3.0.0b9
loaded cogs: admin, cleanup, mod
bot is running on python3.6.4
bot is run with the following flags:
`--dev --mentionable --no-prompt`

The first 2 embeds send fine when mentioned (showing 2 of 4)
The third and fourth do not send

When using the prefix, 3 of 3 embeds send.

More information available upon request if needed.

**Comment by tekulvw** [comment]
This should be fixed with #1375. Can you check and report back?

**Comment by mikeshardmind** [comment]
Seems to, though this is not in b9, so I guess this is fixed with release of b10

leaving this open so that it shows as known until then

**Comment by tekulvw** [comment]
Fixed in B10
