### ISSUE TITLE
[V3 Config] Duplicated temporary files

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1415]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem

When I checked my files from my cogs (under `Red-DiscordBot/cogs/CogName/`, there was something else with the expected `settings.json` file... 2945 files, that had the name `settings-<random int>.json.tmp`.

Most of the files were totally empty, others had half of the json (it stopped writing somewhere). I don't know how to do the error again but, it is cog specific and not random (if a cog has the glitch, the problem will occur, whatever machine that is). that may be a problem with the dict made but... there's still a working `settings.json` at the end, so it actually made the file

**Comment by tekulvw** [comment]
No repro, not actually a config issue. Feel free to reopen when you get more information.
