### ISSUE TITLE
[V3 Data management] We need a way to convert data from JSON to mongoDB, and revert

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1416]
### Type:

- [x] Suggestion
- [ ] Bug

### Brief description of the problem

Right now, we can't switch from JSON to mongoDB (or in the other way), if we do, we lose all data. Creating a data convertor wouldn't be really hard but that'll be really helpful (especially with those glitched JSONs #1415 )

**Comment by palmtree5** [comment]
Implemented in #1421
