### ISSUE TITLE
Requirements installation error

### ISSUE THREAD

**Issue by Ednaval** [Cog-Creators/Red-DiscordBot#1429]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem

When i enter either 1 or 2, i get an error whent donwloading the youtube part.

### Expected behavior

I guess it's suppose to download everything and install it

### Actual behavior

```
Main requirements:

1. Install basic + audio requirements (recommended)
2. Install basic requirements

ffmpeg (required for audio):
3. Install ffmpeg 32bit
4. Install ffmpeg 64bit (recommended on Windows 64bit)

0. Go back
> 1
Collecting pip (from -r requirements.txt (line 1))
  Using cached pip-9.0.1-py2.py3-none-any.whl
Collecting discord.py[voice] from git+git://github.com/Rapptz/discord.py.git#egg
=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning git://github.com/Rapptz/discord.py.git to c:\users\mizugu~1\appdata\lo
cal\temp\pip-build-kgv6mj_1\discord.py
Collecting youtube_dl (from -r requirements.txt (line 3))
  Downloading youtube_dl-2018.3.10-py2.py3-none-any.whl (1.7MB)

An error occurred and the requirements setup might not be completed. Consult the
 docs.

Press enter to continue.
```

### Steps to reproduce

1. Install Python 3.5 on Windows 7 Pro x64
2. Install Git for Windows
3. Run the launcher bat and select option for requirements.
4. Select 1 or 2.

**Comment by tekulvw** [comment]
Try running the `launcher.bat` with admin privileges

**Comment by Ednaval** [comment]
Already try that thanks, didn't do anything.
Right now, i'm uninstalling python to install it again and see if it makes a changement.

**Comment by Kowlin** [comment]
Closing this issue, if you still have this problem, feel free to drop into the [Discord server](https://discord.gg/red) or open a new issue.
