### ISSUE TITLE
[V3/Downloader] Downloading a repository does not display creator's installation message.

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#1433]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Downloading a repository does not display the creator's install message.
### Expected behavior
Install message is displayed after typing "I Agree", For example:
Thank you for installing JumperCogs. Report bugs Here ....
### Actual behavior
Feature is skipped.
### Steps to reproduce

1. Download a repository
2. Feel bad.
3. Cry to Will Tekulvw

**Comment by tekulvw** [comment]
Fixed with #1453
