### ISSUE TITLE
[V3] Optional Embed system

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1436]
### Type:
- [X] Suggestion
- [ ] Bug

Embeds don't play nice on Mobile, and they don't show up for anyone with link previews disabled. To stick all core features in embeds punishes mobile users with settings configured for conservative data usage.

Embeds on core commands whose functionality do not require link previews if not using an embed, should be displayable without the embed as well. (Notably, Steams shows picture of the stream from twitch, so this would be an example where not using an embed doesn't change things)

This would involve 3 additional settings in the bot config, possibly a flag in the CLI to start with embeds disabled (default enabled) and 3 commands in a command group for managing it, as well as restructuring the output flow of many core commands to conform to these settings. This would also likely involve injecting into context these settings and a property which would resolve to either true or false based on them and ctx.channel's type.

Settings: 
Global default: In the absence of a guild or user override, should embeds be used
Guild setting: Guild specific embed setting. This would apply in guild channels for anything other than the helpformatter.
User setting: DMs and help formatter would use this before falling back to the global default.

This also does not mean giving up formatting. As an example, Here is what the help could look like with YAML syntax highlighting
![screenshot from 2018-03-15 00-44-27](https://user-images.githubusercontent.com/22035876/37444793-0c0351da-27ea-11e8-9daa-a00d97fcf0d8.png)

Or the cogs:
!![screenshot from 2018-03-15 01-11-43](https://user-images.githubusercontent.com/22035876/37445337-de17e5ca-27ed-11e8-93c6-6e8f26cc8eef.png)
(first block is `py` (`css` gives a more green if desired), second is `ldif`)

**Comment by tekulvw** [comment]
Should we go ahead and create issues for each core cog and attach them to this epic?

**Comment by palmtree5** [comment]
We should go ahead and go through all the core stuff and make separate issues for each, listing out what in each is using embeds. I've done one issue for the entirety of `redbot.core` already though

**Comment by palmtree5** [comment]
Ok, all needed issues opened

**Comment by tekulvw** [comment]
Is audio the last thing on the list?

**Comment by mikeshardmind** [comment]
Possibly streams too if we're okay with streams falling back to a text only response (no stream preview) which would be reasonable to add.

**Comment by Tobotimus** [comment]
Closing this as I think our optional embed support is good now. Might be a command here or there which could use it, but streams and audio are best with embeds enforced, so I'm considering this epic done.
