### ISSUE TITLE
[V3 Config] Config throwing errors when used in an event handler

### ISSUE THREAD

**Issue by tmercswims** [Cog-Creators/Red-DiscordBot#1439]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
I am using Config inside an event handler defined within a cog. A short snip of the relevant code:
```py
async def on_member_update(self, before: discord.Member, after: discord.Member):
  guild = after.guild
  config = await self.config.guild(guild).all()
  # a bunch more code that does things like config['property']
```
When this handler is invoked, it successfully gets me the guild config dictionary, but it appears to be failing to destroy the object, or something of the sort. (Apologies, I'm not familiar enough with how Python deals with async stuff to know exactly what this means.)

```
[17/03/2018 09:07] ERROR events on_error 174: Exception in on_member_update
Traceback (most recent call last):
  File "/home/ubuntu/V3-Red-DiscordBot/lib/python3.5/site-packages/discord/client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "/home/ubuntu/V3-Red-DiscordBot/tmerc-cogs/streamrole/streamrole.py", line 262, in on_member_update
    )
  File "/home/ubuntu/V3-Red-DiscordBot/tmerc-cogs/streamrole/streamrole.py", line 202, in on_member_update
      )
AttributeError: __aexit__
```
It's worth mentioning that line 262 of the file is the last line of the `on_member_update` handler, which is a parenthesis closing a `log.warning()` call, and line 202 is the last line of the method _above_ the `on_member_update` handler, which is the closing parenthesis of a `ctx.send()` call.
It's also worth mentioning that I'm using the exact same call to config, `await self.config.guild(guild).all()`, in a normal command, and it's working fine there without issue.

Additionally, I attempted to use other config methods besides `.all()`, such as the normal `.<property>()` getters, and they resulted in the same error.

EDIT: Here is the whole file, in case it helps: https://github.com/tmercswims/tmerc-cogs/blob/v3/streamrole/streamrole.py#L204

**Comment by calebj** [comment]
The [`__aexit__`](https://docs.python.org/3/reference/datamodel.html#object.__aexit__) method is the equivalent to [`__exit__`](https://docs.python.org/3/reference/datamodel.html#object.__exit__) for asynchronous context managers. Something in your code is trying to use something as one, and somehow apparently enters a context (via `__aenter__`) without problems. I don't see any problems with your code.

I would suggest restarting the bot if you haven't tried it; sometimes cached code can cause odd glitches. @palmtree5 reports no errors when using the cog, which would support this theory.

**Comment by tmercswims** [comment]
Good point about the cached code. I had tried completely restarting the bot, but was still having the issue. So this time I shut it down, manually removed all the `__pycache__` directories, and then started it up again, and it's working fine now. Closing this ~
