### ISSUE TITLE
[Suggestion] Play local song once, no repeat.

### ISSUE THREAD

**Issue by kanahanazawa** [Cog-Creators/Red-DiscordBot#144]
i made a few aliases that come in and play one audio file using !local and it plays it like a playlist so it repeats. can there be a way to just play one file and stop similar to the airhorn?

**Comment by irdumbs** [comment]
like airhorn? #121 it's in a PR
if you want a song itself, that's another thing
although #121 could be used for that purpose i guess..

**Comment by kanahanazawa** [comment]
works great! thanks.

**Comment by irdumbs** [comment]
oh it works?!
please report any bugs/suggestions.
it haven't been accepted yet, so anything you find will help with the process

**Comment by kanahanazawa** [comment]
haha yeah it works. my friends are having fun with the sfx. it does just what i want it to do, play a file. ill let you know if any problems occur.
hope it gets accepted
