### ISSUE TITLE
[V3/Downloader] Add a key to specify a minimum Python version

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#1452]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [x] Suggestion
- [ ] Bug

Adding a key in the info.json file to specify the minimum python version required for installation. Something similar to the following key would be great:
`bot_version (list of integer) - Min version number of Red in the format (MAJOR, MINOR, PATCH)`

**Comment by tekulvw** [comment]
Fixed with #1455
