### ISSUE TITLE
[V3] Help messages are being cut off.

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#1454]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Help messages are being cut off by a few characters.
### Expected behavior
The message is displayed correctly.
### Actual behavior
They are cut off.
### Steps to reproduce
1. Run the bot with the dev flag.
2. Type `[p]help debug`
3. Feel sad.
4. Complain here.

Screen shot for the lazy
![Bug](https://gyazo.com/3732a5292734c659436f9d0c19576cea.png)

**Comment by tekulvw** [comment]
Fixed with #1456
