### ISSUE TITLE
[V3 Audio] Optional embed support discussion

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1464]
This is to be for discussion of implementing #1436 in `Audio`

Currently using embeds are:
```
event_manager: for track start and queue end notifications
[p]audioset settings
[p]audiostats
[p]now
[p]pause
[p]percent
[p]play
[p]prev
[p]queue
[p]search
_search_button
[p]seek
[p]volume
_embed_msg
```

**Comment by Tobotimus** [comment]
I've decided Audio doesn't need optional non-embed support, the cog has an intricately designed UI which presents information beautifully and effectively, even on Mobile I would suggest embeds would still look and perform better. It would also be pretty ironic for a user to disable embeds in the interest of saving cellular data whilst streaming audio on discord. This can be a cog where the exception is made for optional embed support in my eyes.

Marking this as a new status: "Sinking", meaning I'll close it soon if someone doesn't change my mind.

**Comment by Tobotimus** [comment]
Seems like a done deal to me

**Comment by hab33bi** [comment]
how can i edit redbot to change the ui of embeds i would like to edit the layout by adding the thumbnail and queue number to the output of the [p]play command but how ever many files i change i cannot change the output of [p]play, I change the file and then I close the bot and open it again! What files do i need to change to change the output of [p]play!

**Comment by aikaterna** [comment]
We don't really support editing, nor is this the issue to speak on about this. You can use [p]audioset thumbnail to add a thumbnail to audio displays, which is only available for YouTube tracks. If you have further audio questions, please join the Red support server.
