### ISSUE TITLE
[V3] Token Flag or Separate File

### ISSUE THREAD

**Issue by Kore-Development** [Cog-Creators/Red-DiscordBot#1466]
### Type:

- Suggestion

### Brief description of the suggestion
I would like the ability to set the token with a flag.
### What could it be useful for?
What someone could do is put the bot on GitHub. They would create a script that clones the repo, puts in the token and uses it. When they are finished using the bot the token would get removed and pushed to github. The reason why someone might do this is if they share the bot with friends. It would be easier to share configs, edited code, etc. without worrying about the token being shown to the public.
### What would I use it for?
The same as what it could be useful for.

**Comment by Kore-Development** [comment]
I would like the ability to put the token in a txt file instead of a flag. I would set the path (if configurable) to ../token.txt (up one folder then token.txt). It could also be if a flag specifies it then use the flag if it's not specified the use the file.

**Comment by Tobotimus** [comment]
I can understand the desire for a CLI flag - I'll self-assign that. However the token file doesn't make any sense to me - if you're writing a script anyway, why don't you read the file from that instead, and pass it in? 

As an alternative for now, you can set the `RED_TOKEN` env var to pass the token in.

**Comment by Tobotimus** [comment]
Added in #1872.
