### ISSUE TITLE
logging possible? my red-discord bot started dying frequently

### ISSUE THREAD

**Issue by bonesoul** [Cog-Creators/Red-DiscordBot#147]
couldn't see a way to start logging, is it possible?

**Comment by irdumbs** [comment]
@tekulvw do you mind publishing your logger?

**Comment by tekulvw** [comment]
If it's a bunch of errors in your command window/console/terminal justcopy and paste the traceback. If you think its important to how the bot connects to discords servers then you can enable debug mode in discordpy by [changing this line to say logging.DEBUG](https://github.com/Twentysix26/Red-DiscordBot/blob/develop/red.py#L400)

My logger just logs channel chats so it won't be much help.

**Comment by irdumbs** [comment]
you could start your startup .bat / .sh / .py with > console_log.txt
maybe?

**Comment by bonesoul** [comment]
tried that, doesn't log anything, even tried redirecting bot stdout and stderr to a file on ubuntu but no luck. i was using it for last few weeks all good but yesterday it started crashing frequently like every 5-10 minutes.

**Comment by irdumbs** [comment]
it works fine for me

``` bash
printf "\n+------\n------+\n+------\n+\n---------\n Starting red startup loop. ctrl+c ctrl+c to stop. should also !shutdown bot on discord.\n ---------\n+------\n------+\n+------\n+------\n" >>test_output.txt
while true
do
printf "\n+\n+\n+\n+\n--------- Starting red.py ---------\n+\n+\n+\n+\n" >>test_output.txt
python3 red.py >>test_output.txt 2>&1; echo $?
sleep 4
done
```

**Comment by Twentysix26** [comment]
I don't see how that wouldn't work on linux. Are you sure there is any error at all? Those sound like connection problems, which is pretty much the only thing that can cause the bot to crash

**Comment by bonesoul** [comment]
here is the last lines from the log before it crashes

```
Connected to:
2 servers
25 channels
198 users

10 active cogs with 78 commands

Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /root/vapistbot/cogs/streams.py:369> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_manager() running at /root/vapistbot/cogs/audio.py:608> wait_for=<Future pending cb=[Task._wakeup()]>>
```

**Comment by irdumbs** [comment]
lol that's not helpful at all
those errors tell us `The bot stopped`

**Comment by Twentysix26** [comment]
I think I've seen this happen before on disconnections... So, yeah, that's the reason. Most likely on your end

**Comment by franc-ist** [comment]
@Twentysix26 i always get those errors when force restarting my bot using [p]shutdown. looks like a connection cut off

**Comment by irdumbs** [comment]
!shutdown doesn't clean up everything. shouldn't worry about it unless the background tasks are messing with files

**Comment by tekulvw** [comment]
@raistlinthewiz is the bot dying and coming back up or is it freezing on crash?

**Comment by bonesoul** [comment]
the process crashes and gets killed.

**Comment by tekulvw** [comment]
@Twentysix26 the requested functionality got added in a351f2fc
