### ISSUE TITLE
[V3 Audio] Bump timeout connecting to Lavalink

### ISSUE THREAD

**Issue by TheWyn** [Cog-Creators/Red-DiscordBot#1476]
### Type:

- [ ] Suggestion
- [X] Bug

Lavalink server can take 20-35 seconds to start, bumping it to 50 seconds for good measure is recommended.  Pull https://github.com/Cog-Creators/Red-DiscordBot/pull/1474 made if needed.

**Comment by tekulvw** [comment]
Fixed with #1474
