### ISSUE TITLE
[V3] CLI prefix display

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1477]
### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
When using the `--prefix` flag, the bot's loaded message still displays the prefix(es) it had stored prior (in some cases, this could be none)
### Expected behavior
The new prefix(es) should be displayed
### Actual behavior
New prefix is usable, but not reflected in the CLI
### Steps to reproduce

1. launch the bot using the prefix flag and observe

**Comment by mikeshardmind** [comment]
Can confirm this applies to all CLI args that overwrite behavior of things in tmp_data in cli.py now, have not been working on a fix yet though

**Comment by tekulvw** [comment]
Fixed with #1770
