### ISSUE TITLE
[V3] Audio Resume/Pause Bug

### ISSUE THREAD

**Issue by Gtoyos** [Cog-Creators/Red-DiscordBot#1478]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
When you use the command `resume` it actually pauses the video and after if you use the command `pause` it resumes it.
### Expected behavior
When something is playing and you type `resume` it should say that there is nothing to resume, and when you type `pause` it resumes the current song.
### Actual behavior
Same as description.
### Steps to reproduce

1.  use command `play *insert song here*`
2. type `resume`
3. type `resume`
4. type `pause`
5. feel confused

Screenshot:
![weweew](https://user-images.githubusercontent.com/28682066/38123379-1a1eb340-33b1-11e8-82a5-2d82ce5462dd.PNG)

**Comment by aikaterna** [comment]
This is related to issue 20 on the Red-Lavalink repo.

**Comment by tekulvw** [comment]
This will be fixed in the next release of Red and Red-Lavalink
