### ISSUE TITLE
[Suggestion] Auto-assign members on join

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#148]
![image](https://cloud.githubusercontent.com/assets/15660809/14479713/bbdea09a-0164-11e6-99bb-c446e8ce1a34.png)

**Comment by tekulvw** [comment]
or they could just modify the @everyone permission in server settings

**Comment by irdumbs** [comment]
rainbow-ify everybody that comes innnnnnnnn \o/

**Comment by tekulvw** [comment]
![image](https://cloud.githubusercontent.com/assets/3731082/14944654/d455349c-0fc7-11e6-9426-c86b50c493a1.png)

Too specific for inclusion in the default bot, would be welcome in your welcome cog though ;)

**Comment by irdumbs** [comment]
fine fine
moved to an issue on the repo
