### ISSUE TITLE
[V3] Automatic man page for redbot command

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1480]
### Type:

- [x] Suggestion
- [ ] Bug

Since you have the `--help` flag which shows all flags for the `redbot` command, why not making a man page for that command, since a lot of users, as me, check man instead of `--help`. That can be automatically generated using `help2man`, which requires a `--help` flag and a `--version` flag (see #1479).
That can be probably made easily and included to the code, but before starting the PR, @tekulvw said it would be better to create an issue first so we can talk about that.

**Comment by mikeshardmind** [comment]
Generally man pages should be actual documentation, whereas `--help` should provide available arguments. 

I know help2man can be instructed to include more information in each section, but at that point why not just write [an] actual man page(s), or build them from relevant sections of the sphinx docs used for RTD?

**Comment by laggron42** [comment]
What are the sphinx docs for RTD 🤔 But yeah I agree, this could be better to write a different doc, just need to find the good tools.

**Comment by laggron42** [comment]
I'm writing the new man doc using [this guide](http://www.linuxhowtos.org/System/creatingman.htm), but, for the description part, should I take the one from the README of develop branch or write a new one?

**Comment by laggron42** [comment]
Alright, I made a quick man page following what we had for now with `--help`
```
Red - Discord Bot(1)                                                                                             Red - Discord Bot(1)

NAME
       Red - Discord Bot

SYNOPSIS
       redbot  INSTANCE_NAME [ --owner ID ] [ --co-owner [ ID [ ID ...  ] ] [ --p prefix ] [ --no-prompt ] [ --no-cogs ] [ --self-bot
       ] [ --not-bot ] [ --dry-run ] [ --debug ] [ --mentionnable ] [ --rpc ]

OPTIONS
       -h, --help
              Show this message.

       --V, --version
              Show Red's current version.

       --list-instances
              List all instances names.

        --owner OWNER
              ID of the owner. Set Red's owner ID.  Only who whosts Red should be owner, this has serious security implications.

        --co-owner [CO_OWNER [CO_OWNER ...]]
              ID of the bot's co-owners.  Only those who have access to the system should be  co-owner,  this  has  serious  security
              implications.

        -p, --prefix PREFIX
              Set Red's global prefix; can be multiple. Overrides the current global prefixes for this session.

       --no-prompt
              Disable console inputs. This will disable all console interactions. Useful when running as a sub-process.

       --no-cogs
              Starts Red with no loaded cogs but core.

       --self-bot
              Specifies if Red should log in as a selfbot.

       --not-bot
              Specifies if the token used belong to a user account instead of a bot one.

       --dry-run
              Makes  Red quit with exit code 0 before it starts logging to Discord. This should be used for testing the boot process.

       --debug
              Sets the loggers level at debug. This will also increase console outputs.

       --dev  This will load the Dev cog which includes the debug , eval , repl and mock commands.

       --mentionable
              Allows mentioning the bot as an alternative to the bot prefix.

       --rpc  Enables the built-in RPC server.  Please read the docsprior before enabling this!

LINKS
       Check out the source code at https://github.com/Cog-Creators/Red-DiscordBot/tree/V3/develop

       Check the docs at http://red-discordbot.readthedocs.io/

       Join our Discord server at https://discord.gg/red

Version 3.0.0b10                                 Made by Twentysix - Improved by many                            Red - Discord Bot(1)
```
https://gist.github.com/retke/3d567c7132da93c023fccd8fe7bbe3f4

**Comment by Kowlin** [comment]
Well. Rip me cleaning up the command arguments in ``--help``. It would be nice if they are synchronised.

**Comment by pgaetani** [comment]
You know, sphinx does have a way of building man pages:

http://www.sphinx-doc.org/en/master/man/sphinx-build.html

**Comment by tekulvw** [comment]
I don't think this is really necessary as the manpage wouldn't provide any more information than `--help`. There's also no supported way to install manpages with pip and there's zero windows support.

Read `--help` and RTD.
