### ISSUE TITLE
[V3] Audio Volume "No such player for that guild"

### ISSUE THREAD

**Issue by endms3231** [Cog-Creators/Red-DiscordBot#1482]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
if you type first time using audio module command "volume"(bot was not in voice channel)
"[p]volume" was fine, but "[p]volume 1" was not work very well
### Expected behavior
"Current Volume 1%"
### Actual behavior
"Error in command 'volume'. Check your console or logs for details."
### Steps to reproduce

1. bot was not in voice channel
2. using [p]volume 1~100
3. happening
4. 

details log

Traceback (most recent call last):
  File "c:\users\endms\envs\scarlet\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "c:\users\endms\envs\scarlet\lib\site-packages\redbot\cogs\audio\audio.py", line 710, in volume
    await lavalink.get_player(ctx.guild.id).set_volume(vol)
  File "c:\users\endms\envs\scarlet\lib\site-packages\lavalink\player_manager.py", line 306, in get_player
    raise KeyError("No such player for that guild.")
KeyError: 'No such player for that guild.'

**Comment by aikaterna** [comment]
This is fixed in #1473.

**Comment by endms3231** [comment]
okay, thanks!

**Comment by tekulvw** [comment]
Fixed with #1473
