### ISSUE TITLE
[V3] Cog path operations create duplicate entries

### ISSUE THREAD

**Issue by rngesus-wept** [Cog-Creators/Red-DiscordBot#1499]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
!addpath, !removepath, and !reorderpath do not behave as expected, creating duplicate entries.

### Steps to reproduce

1. Start a new Red instance and run `!paths`. This should yield the output in Discord
```
Install Path: /home/$USER/.local/share/Red-DiscordBot/cogs/CogManager/cogs

1. /home/$USER/.local/share/virtualenvs/$BOT_ENV/lib/python3.5/site-packages/redbot/cogs
```

2. `!addpath /tmp/test/path` (after making that path so that Red accepts it as an existing folder)
    * Expected: `!paths` gives the above output, plus `2. /tmp/test/path`
    * Actual: `!paths` gives
```
Install Path: /home/$USER/.local/share/Red-DiscordBot/cogs/CogManager/cogs

1. /tmp/test/path
2. /home/$USER/.local/share/virtualenvs/$BOT_ENV/lib/python3.5/site-packages/redbot/cogs
3. /home/$USER/.local/share/virtualenvs/$BOT_ENV/lib/python3.5/site-packages/redbot/cogs
```

3. `!removepath 3`
    * Expected: `!paths` gives the step 2 output but with the duplicate path removed.
    * Actual: `!paths` gives
```
Install Path: /home/$USER/.local/share/Red-DiscordBot/cogs/CogManager/cogs

1. /home/$USER/.local/share/virtualenvs/$BOT_ENV/lib/python3.5/site-packages/redbot/cogs
2. /tmp/test/path
3. /home/$USER/.local/share/virtualenvs/$BOT_ENV/lib/python3.5/site-packages/redbot/cogs
```

**Comment by tekulvw** [comment]
Fixed with #1501
