### ISSUE TITLE
Error Module not found in my site packages

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#150]
So I'm trying to create a cog for the bot called pokedex. I'm using the pokeapi with a wrapper. The problem is that when it attempts to load the cog it says No module named 'API'. API is one of the modules for the wrapper, and it is indeed in my site packages folder. The wrapper interacts fine with the api when I run tests outside of the bot and discord. Any insight on where I'm going wrong?

**Comment by irdumbs** [comment]
Why don't you hop on over to our discord server. You'll get quicker/better help there.

**Comment by tekulvw** [comment]
3rd party cog issue, if you want to try to get some help, head into the server and go to #coding
