### ISSUE TITLE
Login timer lists ms 

### ISSUE THREAD

**Issue by QuickNET-Tech** [Cog-Creators/Red-DiscordBot#1506]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
I may be wrong here, but I'm fairly certain the login time listed in the console window is incorrectly listing milliseconds (ms) instead of seconds (s)
### Expected behavior
If my assumption is correct, it should list the value with an s at the end like (4.95812s)
### Actual behavior
Time listed after logging into Discord is instead (4.95812ms)
### Steps to reproduce

1. Launch Red
2. Watch the console
3. Check the time it lists that it took to log into discord
4. This process usually takes 3-5 seconds for me but I always see the listing as ms

**Comment by QuickNET-Tech** [comment]
![unknown 1](https://user-images.githubusercontent.com/23668071/38449692-00786940-39d8-11e8-92b8-ccde08e4a771.png)
I noticed this the other day when Red took almost a minute to log in. Shared that it took almost a minute and someone pointed out that it said ms.

**Comment by Electromaster232** [comment]
@Kowlin 
You added the V3 tag to this, but it looks like in the screenshot posted above that QuickNET is referring to/using v2? I understand v2 is feature locked but this looks more like a bugfix to me.

**Comment by Kowlin** [comment]
All our development focus is on V3, V2 PR's are rarely merged.

**Comment by Tobotimus** [comment]
This isn't an issue in V3, as the login time isn't displayed

**Comment by Tobotimus** [comment]
This isn't going to be added, sorry, as V2 is feature locked.

Edit: Never mind me not thinking, as this is just a simple fix.

If you are able to, open a PR and we might merge it ;)
