### ISSUE TITLE
[Core] Error on Reload

### ISSUE THREAD

**Issue by Kio-td** [Cog-Creators/Red-DiscordBot#1515]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
The bot will crash upon reloading a loaded cog.
### Expected behavior
The cog reloads normally.
### Actual behavior
The bot prints ``Segmentation fault`` to console, and exits
### Steps to reproduce
1. get the latest version
2. reload.

If it at all helps, this is the code I use:
```python
import discord


class welcomer:

	def __init__(self, bot):
		self.bot = bot

	async def welcome(self, user):
		if user.guild.id == 412360553361833984:
			await self.bot.get_channel(415184652572164099).send("Oh! Hi, " + user.mention + "! Thanks for joining KPT. Check the link I sent you to verify. <3")

	async def goodbye(self, user):
		if user.guild.id == 412360553361833984:
			await self.bot.get_channel(415184652572164099).send("Awe, bye " + user.name + ".")

def setup(bot):
	bot.add_listener(welcomer(bot).welcome, "on_member_join")
	bot.add_listener(welcomer(bot).goodbye, "on_member_leave")
```

**Comment by Kio-td** [comment]
Okay, something new came up.

```
[09/04/2018 16:04] ERROR events on_command_error 198: Exception in command 'reload'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/core_commands.py", line 422, in _reload
    spec = await ctx.bot.cog_mgr.find_cog(c)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/cog_manager.py", line 271, in find_cog
    return await self._find_ext_cog(name)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/cog_manager.py", line 216, in _find_ext_cog
    for finder, module_name, _ in pkgutil.iter_modules(real_paths):
  File "/usr/lib/python3.6/pkgutil.py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "/usr/lib/python3.6/pkgutil.py", line 146, in _iter_file_finder_modules
    import inspect
  File "/usr/lib/python3.6/inspect.py", line 39, in <module>
    import importlib.machinery
  File "/usr/lib/python3.6/importlib/__init__.py", line 31, in <module>
    sys.modules['importlib._bootstrap'] = _bootstrap
AttributeError: module 'sys' has no attribute 'modules'
```

**Comment by mikeshardmind** [comment]
We really should be catching this in the load and reload logic, but it's an issue with your cog code. it is creating listeners, but never actually adding the cog.

**Comment by tekulvw** [comment]
A seg fault? This is looking like a broken python installation. Closing for now.

**Comment by Kio-td** [comment]
Would appreciate if this was reopened.
![image](https://user-images.githubusercontent.com/7786316/42729385-8211be24-87a4-11e8-8261-5439a9a9a38c.png)

**Comment by mikeshardmind** [comment]
I'm going to look into various potential causes on this. My prior response still stands, you should not expect setup to allow adding a listener which belongs to a cog, without also adding that cog. 

But that doesn't mean we can't prevent this from being an issue by raising an error and removing bad listeners. ED: the listeners actually function just fine.

**Comment by mikeshardmind** [comment]
1st With your code, I can't repro getting a segfault on reload.
2nd Load works because it appears to be valid unload doesn't work, as there was no cog added by that name to go find everything to remove.
