### ISSUE TITLE
[V3] C cogs maker ?

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1517]
### Type:

- [x] Suggestion
- [ ] Bug

I recently discover that it is possible to import things from C file to Python. Maybe that would be a good idea to work on a system that would allow C-made cogs. What do you think about that?

**Comment by mikeshardmind** [comment]
Not my call, but I dont think this is in scope. You could easily package Cython code as a pip dependency and add a cog as a pip import.

**Comment by Kowlin** [comment]
This seems a bit of our scope to do with Red, as said above a python package seems like the best solution

**Comment by Kowlin** [comment]
Closing since this issue is out of our scope.
