### ISSUE TITLE
[V3] Make test fixtures accessible in pip-installed package

### ISSUE THREAD

**Issue by rngesus-wept** [Cog-Creators/Red-DiscordBot#1521]
### Type:

- [X] Suggestion
- [ ] Bug

### Brief description of the problem
There are some nice test fixtures in `tests/conftest.py`, but no good way to import them for use with third party cogs. These tools should made available in the pip deployment for conscientious cog developers.

As an example, I tried copying that file to `site-packages/redbot/testing/conftest.py` and then having `from redbot.testing.conftest import *` in my cog repo's test file. The fixtures were then available as expected. Such a solution might be good enough, but it'd be better to find a way that doesn't involve `import *`. Perhaps it's unavoidable, with the way `pytest` wants to do namespace abuse for fixtures.

**Comment by tekulvw** [comment]
This will be coming in the next beta or two. For now I'm gonna stick it in Beta 15 to get some eyes on this.

**Comment by Tobotimus** [comment]
Now available with #1858 :smiley:
