### ISSUE TITLE
[V3 I18n] use named/positional args in multi-placed formats

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1526]
### Type:

- [x] Suggestion
- [ ] Bug

Basically, some languages may require reordering args, but at the moment we're not using named/positional args so it may not be clear to someone translating as to what is supposed to go in a given slot without source-diving

**Comment by mikeshardmind** [comment]
Adding to this: `pygettext` will NOT parse f-strings, so strings passed to `Translator` can be passed to f-strings, but you can't pass f-string to it.

**Comment by mikeshardmind** [comment]
Pretty sure this is handled well enough for current strings. Anywhere it isn't can be handled individually as noticed.
