### ISSUE TITLE
!sing !leave !sing (from different server)

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#153]
![image](https://cloud.githubusercontent.com/assets/15660809/14520270/e87e00ac-0266-11e6-9443-7cc528a47786.png)

!stop resolves the issue

**Comment by tekulvw** [comment]
Expected behavior

**Comment by irdumbs** [comment]
how is that expected behavior?

**Comment by tekulvw** [comment]
Oh oops, wasn't reading carefully enough

**Comment by tekulvw** [comment]
Encompassed by #185
