### ISSUE TITLE
Default SFX?

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#154]
Should there be defaults? What should they be?

Here are my choices:
- [ ] Airhorn
- [ ] Batman Transition
- [ ] Combo Breaker
- [ ] Deez Nuts
- [ ] Denied
- [ ] Hyper Combo
- [ ] Jeopardy
- [ ] Mario Kart
- [ ] Monster Combo
- [ ] NO
- [ ] Not Up in Here
- [ ] Punch
- [ ] Sad Violin
- [ ] Spooky Scary Skeletons
- [ ] Suspense
- [ ] Tadahh
- [ ] Triple Combo
- [ ] Ultra Combo
- [ ] What's his name?
- [ ] Wrong

[Defaults.zip](https://github.com/Twentysix26/Red-DiscordBot/files/218633/Defaults.zip)

Not in the zip:
- [ ] Heyayaya
- [ ] Just Do It
- [ ] Hu Waa Waa (Homer Simpson)

**Comment by franc-ist** [comment]
WHERE IS MY DEFAULT HEYAYAYA?

**Comment by jxtcman** [comment]
Is it okay to distribute these wrt. copyrights?

**Comment by irdumbs** [comment]
i have NOOOO idea.
do you recommend I take them down?
I was under the impression that <30 seconds was all good to distribute, but i don't know legal stuffs

**Comment by Kowlin** [comment]
SFX is a goner! So this is also a goner :3
