### ISSUE TITLE
[V3] Commands

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1546]
### Type:

- [ X] Suggestion
- [X ] Bug

### Brief description of the problem
Re-Add command enable/disable
 Also Warning cog doesn't allow moderators themselves to warn anyone.. 
![image](https://user-images.githubusercontent.com/10146271/38956541-c9421256-434f-11e8-8319-6af93a2a55dc.png)

**Comment by palmtree5** [comment]
the warn command doesn't work for mods because it's restricted to admins or users with the `ban_members` permission

**Comment by Ray-MRQ** [comment]
If it's not available to moderators then let there be an option for them to be enabled role specifically?

**Comment by mikeshardmind** [comment]
That will be available though permissions (#903) later on.
