### ISSUE TITLE
Hidden audio feature

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#155]
I suggest that the following feature be better documented so that users that don't know about it don't have to miss out.
# Song Mixing
1. Do any audio command. This will be your Track 1, so you may want to make sure it's something long or looping.  
   `!mix veorra`
2. Place the Track in the background  
   `!reload audio`
3. Add Track 2  
   `!local herbalflows`
4. Repeat.  
5. ...  
6. Profit?

don't forget.
`!alias add scratch resume`
`!alias add dip pause` <sub><sup>*I don't know DJ / audio mixing terms</sup></sub>

Have fun with the secret feature!

*disclaimer: I take no responsibility for any harm done to your computer / ears / lives / loved ones.

**Comment by Skordy** [comment]
Possibly the best feature of Red Bot. <3

**Comment by tekulvw** [comment]
Encompassed by #185
