### ISSUE TITLE
[V3] Version names out of order

### ISSUE THREAD

**Issue by bobloy** [Cog-Creators/Red-DiscordBot#1551]
### Type:

- [x] Suggestion
- [ ] Bug

### Brief description of the problem
Version `3.0.0b12` is alphabetically less than `3.0.0b9`
### Expected behavior
Latest version should be easily recognizable by 3rd party programs (PyCharm)
### Actual behavior
Latest version is placed behind most other version

![image](https://user-images.githubusercontent.com/955640/39012027-2cd00ada-43e1-11e8-8471-74ba4057e3dd.png)

Unsure if this is something that can be fixed

**Comment by mikeshardmind** [comment]
This is a bug with pycharm. The versioning here is [PEP440](https://www.python.org/dev/peps/pep-0440/) compliant

**Comment by tekulvw** [comment]
Issue with third party program, make a bug report with them.
