### ISSUE TITLE
[V3] Same link can be added multiple times on a playlist

### ISSUE THREAD

**Issue by pabloleban** [Cog-Creators/Red-DiscordBot#1556]
A quick scan over the playlist to check if a song is already there before appending a link would be great.

**Comment by tekulvw** [comment]
Also adding to #623. Should be much easier to implement than #1544

**Comment by rguan72** [comment]
Hello, I am new to this project. Is there any way I can help with this issue?

**Comment by Tobotimus** [comment]
Hey @rguan72 we'd love some help :) You're welcome to make a PR to resolve this issue, if you're new to that and would like some help, [CONTRIBUTING.md](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/.github/CONTRIBUTING.md) and maybe [this site](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) can help you. We're also happy to help in the #coding channel of our discord server at any time (https://discord.gg/red) :smiley:

**Comment by rguan72** [comment]
Ok, got it. Thanks!

**Comment by Tobotimus** [comment]
Resolved by #2071, thanks @rguan72 :smiley:
