### ISSUE TITLE
[V3] Failing to load Audio & Manager 

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1557]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [ X] Bug

### Brief description of the problem
Audio fails to load with lavalink installed. 
![image](https://user-images.githubusercontent.com/10146271/39063457-1a48e412-44c3-11e8-82c9-808123828fbb.png)

So far I am running this off a Venv python 3.6 b12 and getting that error, also, I was told "Manager isn't core" however I have that cog for some reason which wasn't on b11. 
![image](https://user-images.githubusercontent.com/10146271/39063567-659dc2d4-44c3-11e8-84da-1b08b01d2766.png)
![image](https://user-images.githubusercontent.com/10146271/39063577-743eedcc-44c3-11e8-8688-5ea48c3ff23d.png)
From the error I can tell it's a .manager problem so I can only assume the errors are related.

**Comment by bobloy** [comment]
Had user try the following command, it completed successfully (no 'wtf')

[p]eval
```
try:
    import redbot.cogs.audio.manager
except:
    print("wtf")
```
