### ISSUE TITLE
[Suggestion] a cleanup command that only deletes commands in the chat and Bot Relies.

### ISSUE THREAD

**Issue by The1stVoidRunner** [Cog-Creators/Red-DiscordBot#156]
Hi. i was wondering if someone could add a command that only deletes commands in the chat and Bot Relies.

**Comment by Twentysix26** [comment]
`[p]cleanup user @Yourbot <number>`

You can make an `[p]alias` out of that if you want

**Comment by irdumbs** [comment]
would be cool if you could cleanup based on regex though.
That'd let you clean up commands. just clean up msgs that start with a command prefix
