### ISSUE TITLE
[V3] Warning cog

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1562]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [x] Bug
- [ ] Suggestion

### Brief description of the problem
Warning cog doesn't let you warn anyone 
![image](https://user-images.githubusercontent.com/10146271/39098453-23346014-4663-11e8-8616-7dac8c0bec55.png)
 Note; when you're going to enable custom warn reasons it isn't obvious what to do to enable it.

Also; None of the ones below expect the ones crossed out works, appears in help menu, but doesn't appear as a command in [p]help warnaction or any other ones.
![capture](https://user-images.githubusercontent.com/10146271/39098534-3402aa6c-4664-11e8-88c7-e113b617eb7a.PNG)

**Comment by Bakersbakebread** [comment]
What can I do to recreate this issue? I can't seem too.

**Comment by mikeshardmind** [comment]
~~Can repro. Create one or more custom warning reasons to break warnings.~~ No longer able to repro, even on the same instance.

**Comment by palmtree5** [comment]
I can't repro the issue with `[p]warn` on my own bot

**Comment by palmtree5** [comment]
Closing as no repro. Note that a PR is coming to fix several other bugs found with this particular cog though
