### ISSUE TITLE
Could a Pi3B be able to run this?

### ISSUE THREAD

**Issue by vico93** [Cog-Creators/Red-DiscordBot#1570]
I ask this because some other similar bots (like GAwesomeBot and FredBoat) seems to doesn't run properly on pi due to requirements.
Did Red runs fine on Raspbery Pi (using raspbian as OS)?

**Comment by Tobotimus** [comment]
In short, yes.

Before opening an issue, please look for your answer in our [docs](https://twentysix26.github.io/Red-Docs/), which are linked from the front page of this repository. In just two clicks you will find a full installation guide for Raspbian.

In future, please direct support questions to the [official discord server](https://discord.gg/red), as we use GitHub issues for keeping track of the bot's development process.

**Comment by vico93** [comment]
Sorry, i didnt see the docs. Thanks for pointing me!
