### ISSUE TITLE
[V3 Cleanup] [p]cleanup bot doesn't delete the message of the command itself

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1572]
### Type:

- Bug

### Brief description of the problem
`[p]cleanup bot` should delete the message from which the command itself came, as is the nature of the command; to clean up bot commands and responses.

Also, if a large amount of messages are being deleted, the bot will ask the user to confirm if they want to delete that many messages. This prompt and the response should be deleted as well.

**Comment by palmtree5** [comment]
Done in #1602
