### ISSUE TITLE
Getting an error that says "unable to locate pip module"

### ISSUE THREAD

**Issue by EchoesNetwork** [Cog-Creators/Red-DiscordBot#1574]
Hi. So after downloading and running the command setup on the Red website, I've run into some an issue. I'm getting an error which says "Red cannot work without the pip module. Please make sure to install Python without unchecking any option during the setup." Not sure why this is happening, I've followed all the steps to install. But, when i run the final command (python3 launcher.py) that error pops up. Any help would be appreciated!

For reference, I'm running Ubuntu Artful (17.10).

**Comment by btkelley** [comment]
Well did you add python to the path? And get the right version? If so, go to the discord, there's more people there to help.

**Comment by Kowlin** [comment]
Apologies about the late reply, for the quickest source of support please join our Discord server over at https://discord.gg/red

Can you confirm that pip is installed and working on the system by running ``python3 -m pip --version``?

**Comment by Tobotimus** [comment]
Closing due to lack of response. Follow-up questions can be answered on the discord server, see Kowlin's response
