### ISSUE TITLE
[V3/Installation] discord.py Dependency is not updating on upgrade.

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#1576]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
The latest Discord.py rewrite isn't updated when using upgrade for Red install. 
### Expected behavior
Discord.py is upgraded
### Actual behavior
Discord.py is not upgraded.
### Steps to reproduce

1. Install  Red.
2. Wait for a breaking d.py change.
3. Wait for Red to conform to new change.
4. Update Red.
5. Watch your bot blow up.

### Workaround
`python -m pip install -U https://github.com/Rapptz/discord.py/tarball/rewrite#egg=discord.py` After upgrading Red.

**Comment by Tobotimus** [comment]
Unfortunately, this is simply pip behaviour. Use the `--force-reinstall` flag to ensure discord.py is properly upgraded if it needs to be.
