### ISSUE TITLE
[V3] Reason error

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1587]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
![image](https://user-images.githubusercontent.com/10146271/39540320-3a5e9352-4e3a-11e8-89b7-dee99e00eda7.png)
![image](https://user-images.githubusercontent.com/10146271/39540328-422de556-4e3a-11e8-8b68-2d66ba37ed88.png)
If the modlog says unknown it can't add the reason to it therefore not letting you modify it
### Steps to reproduce

1. Somehow get a "unknown" as moderator
2. Add a reason

**Comment by Tobotimus** [comment]
Not sure why this issue was closed, as it is still occuring

**Comment by Kowlin** [comment]
It was closed due to me mass closing issues, and overlooked this one. Sorry

**Comment by Tobotimus** [comment]
Fixed in #1604
