### ISSUE TITLE
[Cleanup] Respect pinned mesages

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1589]
Ohhh ye, we're adding more upon Cleanup's logic like it already wasn't hard enough! 😏 Cleanup should respect pinned messages when cleaning up in any setting used by not removing them when their detected in the list.

**Comment by skeith** [comment]
What if cleanup post a warning whether you want to delete pinned messages or not? and introduce a flag/subcommand to ignore pinned messages

**Comment by palmtree5** [comment]
Fixed in #1596
