### ISSUE TITLE
[V3 Backup] Improve files selected for backup

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1598]
Right now, everything (and I do mean everything) gets backed up.

* lavalink debug dumps
* log files
* pycache
* the entire git history of every cog installed through Downloader

While an option to intentionally do this could be nice, most people don't want or need more than their settings and the current state of the cogs.

For comparison:
```
tar xf original.tar.gz
find ./Red-DiscordBot/ -name "*.json" -o -name "*.py" -o -name "*.txt" -o -name ".yml" -o -name ".yaml" | tar czf trimmed.gz -T -
ls -l *.gz

-rw-rw---- 1 mike_shardmind mike_shardmind    48776 May  5 08:32 trimmed.gz
-rw-rw---- 1 mike_shardmind mike_shardmind 41527864 May  5 08:10 original.tar.gz
```
Now that approach would kill the Downloader cog (doesn't preserve enough about git), but there is a lot of stuff there which most likely does not need to be backed up.

**Comment by mikeshardmind** [comment]
Actually, the largest thing in the archive is the lavalink jar. Even just excluding things packaged in core red (keeping only things added) would likely help a lot.

**Comment by palmtree5** [comment]
see also #1666
