### ISSUE TITLE
[V3 Help] Extra features

### ISSUE THREAD

**Issue by Bakersbakebread** [Cog-Creators/Red-DiscordBot#1605]
This issue is created to discuss some extra features for help command :

- [X] helpset command (#1694)
- [x] allow users to add 'tagline' to suffix help command (#1705)
- [ ] default to DM on large message but set to channel toggle

**Comment by tekulvw** [comment]
The third feature can be accomplished by doing `!helpset maxpages 0` with the changes in #1694
