### ISSUE TITLE
[V3 Mod] Mute for channel categories

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1607]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command

#### Describe your requested feature

Instead of muting per channel, have an additional permission weather or not to mute catergorically, means less work for the bot and doesn't fill logs with per channel mutes/unmutes. All of this would be optional of course.

Edit; And then any channels that aren't muted via category it mutes per any channels left.

**Comment by mikeshardmind** [comment]
Replaced by #3270
