### ISSUE TITLE
Update raspbian install instructions

### ISSUE THREAD

**Issue by vico93** [Cog-Creators/Red-DiscordBot#1609]
Python 3.5 is available for raspbian via the package `python3` ([proof](https://www.reddit.com/r/raspberry_pi/comments/8hq4ij/what_version_of_of_python_comes_with_the_newest/dylqw4b/?context=3)). So no need to compile it from scratch anymore.

**Comment by palmtree5** [comment]
#1685 moves the docs to 3.6
