### ISSUE TITLE
[V3] Downloader / RepoManager / CogManager Doesn't handle branches well...

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1611]
1. Install a cog from a repo
2. Uninstall cog from that repo
3. Add a seperate branch from original repo
4. Install cog from that branch

Result:
Loaded cog is the original version from step 1

**Comment by tekulvw** [comment]
What happens if you restart the bot then load the new cog?

**Comment by tekulvw** [comment]
This is likely due to the bot not reloading modules internally when they're first loaded (that only happens with the reload command). #1691 may fix this.

**Comment by mikeshardmind** [comment]
#1691 should fix it as restarting the bot prior to load works as expected.

**Comment by mikeshardmind** [comment]
I can no longer reproduce this after #1691 was merged, closing.
