### ISSUE TITLE
[V3 Parser] --dry-run flag not handled 

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1612]
# Other bugs

#### What were you trying to do?

I was trying to run the bot with the `--dry-run` flag

#### What were you expecting to happen?

See the bot loading data, then stop before connecting to the gateway
```
  --dry-run             Makes Red quit with code 0 just before the login. This
                        is useful for testing the boot process.
```
#### What actually happened?

The bot connected to the gateway as usual, like if there weren't flags 

#### How can we reproduce this issue?

Just run any bot with the `--dry-run` and see if it change something

### Details

I searched for the flag in the source code to see if it was actually being used somewhere... No results.

*Nice issues templates btw*

**Comment by Kowlin** [comment]
Thinking of removing this feature since it was a port from v2 before we started using pytests to validate a working Red instance.

**Comment by Tobotimus** [comment]
I think it's fine to have this included, I don't see an exact use for it right now but you never know when it might come in handy.

**Comment by laggron42** [comment]
Thanks Toby
