### ISSUE TITLE
[V3 Userinfo] Guild join date storage?

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1614]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

The server join date from the userinfo command, from the General cog, shows what the API provides. However, left and join are usuals on servers nowadays, so the command shows the true join date, while he was already on the server before that. I wonder if it would be cool to store the first join date to show it later, even if the user left for a short (or not?) period.

*Everyone tells me that my PRs are useless, so I'm creating and issue first to discuss about that*

**Comment by Bakersbakebread** [comment]
I think it is a good idea, but as part of a cog. (Not core)

**Comment by bobloy** [comment]
Personally I've wanted this along with api join date, but I don't know if my usage is the general one

**Comment by laggron42** [comment]
@Bakersbakebread that would require a "clone" of the userinfo command

**Comment by pgaetani** [comment]
Wasn't saving user info some big problem with privacy a while ago? I feel like this would make more disclaimers necessary about what's being saved.

**Comment by laggron42** [comment]
Actually everyone is already making logs on messages for long while Discord said in its ToS it's forbidden. But that would be an interesting thing to add an option to "forget" someone, and that would be perfect for that section *that nobody respects atm* of the Discord Developers ToS : 

> 2.4 End User Data. “End User Data” means all data associated with the content within the functionality enabled by the API or SDK, including but not limited to message content, message metadata, voice data and voice metadata. You acknowledge and agree that Discord and its end users, as applicable, retain all worldwide right, title and interest in and to the End User Data. If you have access to End User Data through the API or the SDK, you shall ensure that your Applications do not collect, use and/or disclose End User Data except (a) as necessary to exercise your rights under this Agreement, (b) in accordance with Discord’s Privacy Policy. If you have access to End User Data through the SDK, you additionally agree to get express permission from the End Users.
You shall not sell, license or otherwise commercialize any End User Data. You may not use End User Data to target End Users for marketing or advertising purposes. You may not disclose End User Data to any ad network, data broker or other advertising or monetization related service.
You shall delete all End User Data upon Discord’s or the End User’s request and within seven (7) days following the End User’s termination of the End User’s account. You may only retain chat logs as necessary for the operation of your Applications. Discord’s offering of an API or SDK that allows you to reproduce or display End User message content is not an express or implied license to such content from Discord.
https://discordapp.com/developers/docs/legal

**Comment by Tobotimus** [comment]
From my perspective this feature can easily be provided by a 3rd party, and that can be implemented in many ways, it doesn't *necessarily* have to clone/replace the core userinfo command.

As for the privacy issues, I don't think storing this information is an issue, especially in comparison to the mod cog, which already logs name and nickname changes.

I simply think this feature is on the fence of being too niche to be core. However, I'm leaving this open and you're welcome to continue the discussion.

**Comment by laggron42** [comment]
How could a 3rd party cog modify other cogs?

**Comment by mikeshardmind** [comment]
easily...
You can (varying levels of difficulty, varying side effects):
Well behaved cogs will use `__unload` to restore any of the below

1. Import the cog class and override your own functions, remove the original cog and replace it on load

2. Remove commands and just replace them (Again, restore on unload)

3. Remove commands, replace them with static methods and manually assign their instance

4. Modify existing command objects directly by overriding their attributes 

That said any of these methods have risks of going terribly wrong if misused, or if used poorly or without consideration for how things interact, so you're on your own actually doing any of these.

**Comment by laggron42** [comment]
Okay, but what do you mean by "Well behaved cogs will use `__unload` to restore any of the below"? What should they do to restore that?

**Comment by mikeshardmind** [comment]
I'll give an example and leave the rest up to your imagination and ingenuity. I'm not looking to give a tutorial on messing with all of the internals of command objects here.

```py
def setup(bot):
    n = MessageBox(bot)
    # `_old_contact` is defined outside of the function and before it as `None`
    _old_contact = bot.get_command('contact')
    if _old_contact:
        bot.remove_command(_old_contact.name)
    bot.add_cog(n)
```

and the corresponding `__unload`:
```py
def __unload(self):
    if _old_contact:
        self.bot.add_command(_old_contact)
```

**Comment by laggron42** [comment]
Alright, thanks a lot!
