### ISSUE TITLE
[V3] Save the user that added a song to a playlist

### ISSUE THREAD

**Issue by pabloleban** [Cog-Creators/Red-DiscordBot#1615]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

When a song is added to a playlist, it should save somewhere the user that added that song.
So then when the command **!song** is used, we can see an "Added by: Twentysix". I think is quite simple to do this.

**Comment by pabloleban** [comment]
I never coded on python :(
Im more a JS guy but I would love to help on this project.

**Comment by Ray-MRQ** [comment]
pretty sure if you just do [p]queue it already says.

**Comment by pabloleban** [comment]
nope, it doesn't.

**Comment by pgaetani** [comment]
Yes it does.

<img width="461" alt="screen shot 2018-05-09 at 14 00 35" src="https://user-images.githubusercontent.com/7749471/39813624-75efd988-5391-11e8-8739-939d891cc1ca.png">

**Comment by pabloleban** [comment]
Is that a cog? Cause this is my case:
![image](https://user-images.githubusercontent.com/13904174/39814477-ddc35020-536a-11e8-8f48-008542cc4265.png)

**Comment by pabloleban** [comment]
and here when it's playing
![image](https://user-images.githubusercontent.com/13904174/39814514-0241faf0-536b-11e8-9611-954d3bb628ef.png)

**Comment by bobloy** [comment]
Doesn't look like you're running V3, or at least not the latest version. 
Please confirm that discord.py is 1.0 in your `!info` command, and your RED version is at least 3.0.0b11

**Comment by aikaterna** [comment]
Pablo has v2.

**Comment by Ray-MRQ** [comment]
what why has this issue got [V3] if the user himself doesn't have V3....

**Comment by Tobotimus** [comment]
Just a slight misunderstanding by the looks of things. Closing this since this feature is already implemented in V3.

Pablo, if you're interested in trying out V3, you can look at the README.rst on the V3/develop branch of this repository for getting started.

**Comment by pabloleban** [comment]
You were right.
