### ISSUE TITLE
[p]servers attempts to leave the wrong server [V3]

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#1616]
# Command bugs

#### Command name

servers

#### What cog is this command from?

Core

#### What were you expecting to happen?

Expected the value stated to be the actual value.

#### What actually happened?

If I chose the value 1, it'd send a message to leave the server which is after the ID 1.

#### How can we reproduce this issue?

[p]servers, select and ID and it'll attempt to leave a different server.

https://i.imgur.com/LRaktDD.png

**Comment by palmtree5** [comment]
Fixed in #1617
