### ISSUE TITLE
New Video to explain how to use Red-DiscordBot

### ISSUE THREAD

**Issue by Papy-Serra** [Cog-Creators/Red-DiscordBot#162]
Hi !
I'm french and i don't understand how to use Red-DiscordBot, so i install it on my VPS, no problem and i configure it, start it and now i have this:

![ss 2016-04-09 at 08 15 31](http://puu.sh/okK8P/b61f36612c.png)

And i don't know, how to set up the owner, i try `!set owner` (don't worry i choose `!` during the configuration), so i type `!set owner` but nothing happend, i mean no logs, i can't use any other commands, i tried `!play https://youtube.com/wathXXXXXX` but i juste have the link.

![ss 2016-04-09 at 08 15 32](http://puu.sh/okKCh/9cd06ad6b3.png)

So many i should to configure the text channel and the voice channel ?

I'm lost really.

Thanks you,
Regards,
Misteralex007

**Comment by franc-ist** [comment]
You've set up the bot as your own account. If `Misteralex007` is your bot account, login to your main account and retry the command. If not, create a new discord account for the bot, and delete `/data/red/settings.json` and restart the bot.

**Comment by Papy-Serra** [comment]
Ok thanks =)

**Comment by Papy-Serra** [comment]
Hi !
it's me again. Now i have a problem for playing a song with the bot

![ss 2016-04-09 at 08 15 31](http://puu.sh/oloqD/7551595cdb.png)

I downloaded the last version but no change.
And i want to know if it's work with soundcloud for instance ?

Thanks again,
Regards,
Misteralex007

**Comment by franc-ist** [comment]
@Misteralex007 did you do `pip3 install youtube_dl`?

**Comment by Papy-Serra** [comment]
yes i did it. I retried it and:

![ss 2016-04-09 at 08 15 31](http://puu.sh/olpdF/0983f38050.png)

But it doesn't work.

**Comment by Papy-Serra** [comment]
I tried with HTTPS and HTTP it doesn't work (with HTTP -> Invalid Link)

**Comment by franc-ist** [comment]
Join [this server](https://discord.gg/0k4npTwMvTrI2orL) and we'll get someone to help you out

**Comment by Papy-Serra** [comment]
Thank you so much for your help !
