### ISSUE TITLE
[V3 Streams] streamalert messages not tracked between restarts

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1620]
# Command bugs

#### Command name

`[p]streamalert twitch channel`

#### What cog is this command from?

`Streams`

#### What were you expecting to happen?

Stream alert messages should be tracked between reboots

#### What actually happened?

They're not tracked

#### How can we reproduce this issue?

1. Set up a stream alert
2. Wait for that channel to be live and the alert message to be posted
3. Restart the bot while the channel is live

**Comment by Tobotimus** [comment]
Fixed in #1630
