### ISSUE TITLE
[V3] Reload on cog update

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1625]
~~Reloading a cog after update does not reload anything the cog imported even if it changed in the update.~~ 
Edit: Or I'm too used to used to v2's behavior and occasionally revert to not updating manually.

Issue updated to reflect the real issue.

**Comment by tekulvw** [comment]
What is the real issue?

**Comment by Tobotimus** [comment]
In V2, updating cogs would prompt the user if they would like to reload those cogs. In V3, this feature is missing, and in my opinion it's necessary. I suspect lots of bot owners will be unaware just doing `cog update` won't actually load any changes on its own.

**Comment by palmtree5** [comment]
V2 also provided much more robust information about exactly what cogs were updated iirc

**Comment by tekulvw** [comment]
Tacking this on to #1683 and closing. Further discussion can happen there.
