### ISSUE TITLE
[V2] Audio voice

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#1643]
# Other bugs

#### What were you trying to do?

Trying to play music while bot is idle in a voice channel will eror out if that voice channel is full with the bot in the channel. 

#### What were you expecting to happen?

For the bot to keep playing.

#### What actually happened?

Bot errors out with "Your voice channel is full."

#### How can we reproduce this issue?
1. Create a voice channel with 2 slots.
2. Join voice channel and [p]play rickroll
3. After bot has joined and song has finished or you can do [p]stop try to
4. Try to play again while it is you and bot in the VC and channel is 2/2
5. Error

**Comment by tekulvw** [comment]
Not going to fix on V2 due to featurelock.

**Comment by Twentysix26** [comment]
Feature lock doesn't mean no bug fixes.
