### ISSUE TITLE
[V3] Mod | Mute

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1669]
# Other bugs

#### What were you trying to do?

Attempting to mute

#### What were you expecting to happen?

To mute/

#### What actually happened?

Unauthorised.

#### How can we reproduce this issue?

Assuming that the role has admin permission, in theory, mute permission should be given even if the moderator/admin role isn't present.

Attempt a mute with a test account that does not have the moderator/admin role but has the Administrator permission and try. 

Here's an example;
![image](https://user-images.githubusercontent.com/10146271/40142211-ee6fae10-594f-11e8-8831-09dc4cca7529.png)
Here's a user testing mute with that role.
![image](https://user-images.githubusercontent.com/10146271/40142272-1507c62a-5950-11e8-9bc8-28d08e5c5b03.png)
Now here's the user having the admin/mod role and then using mute.
![image](https://user-images.githubusercontent.com/10146271/40142328-3096026c-5950-11e8-87fa-bd50f5ff0625.png)
Note; the p!m is just an alias for mute server.

**Comment by Tobotimus** [comment]
I think all checks related to permissions should be resolved as true if the user has the Administrator permission. So this is more a logic error in the checks themselves.

**Comment by Tobotimus** [comment]
Fixed by #1711
