### ISSUE TITLE
tell people how to join 1st server?

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#167]
in console, explain how to get the bot to join it's 1st server,
both token and not

**Comment by irdumbs** [comment]
"Complete the initial setup as the bot requires (email, password, etc.), remember to sign into the bot’s account once and join your main server. This is the only time you will need to sign into the bot’s account."
in mac install docs. update docs to include token instructions?

**Comment by Kowlin** [comment]
Done in 5b764c41c35380dc5e97ea6391cbf0e73bf2b933
