### ISSUE TITLE
[V3] Audio: [p]play - The command does not work.

### ISSUE THREAD

**Issue by endms3231** [Cog-Creators/Red-DiscordBot#1680]
# Other bugs

#### What were you trying to do?

 i typed like that "[p]play always awake" to listening some music.

#### What were you expecting to happen?

 The searched song is playing.

#### What actually happened?

 Only the error log has occurred.

[log.txt](https://github.com/Cog-Creators/Red-DiscordBot/files/2019453/log.txt)

#### How can we reproduce this issue?

 Just you can see that log to using 3.0.0b13~4V redbot [p]play command...

I don't think it's just my problem.
The attached log was recorded on the win10, and i used the Virtual box, but Ubuntu also had an error.

**Comment by laggron42** [comment]
can you post the "error log"

**Comment by endms3231** [comment]
sure, i posted before 15 seconds.

**Comment by laggron42** [comment]
A restart should fix the issue

**Comment by endms3231** [comment]
still same result after restarting...

**Comment by skipfie** [comment]
leave the bot running for a bit for lavalink to initialize and open up ports. make sure the port 2333 is not blocked in firewalls

**Comment by endms3231** [comment]
firewall access that didn't show up until last days solved the problem...

and I don't know why but I had to use the command twice to load the audio
module.

one use of the command will eventually lead to error.


2018년 5월 28일 (월) 오후 2:45, skipfie <notifications@github.com>님이 작성:

**Comment by tekulvw** [comment]
Sounds like this is a firewall issue and is fixed.
