### ISSUE TITLE
Play command traceback on DM

### ISSUE THREAD

**Issue by Gtoyos** [Cog-Creators/Red-DiscordBot#1681]
# Command bugs

#### Command name

play

#### What cog is this command from?

audio

#### What were you expecting to happen?

The bot should tell me that that command isn't available on DM's

#### What actually happened?

Red threw a trace-back

#### How can we reproduce this issue?

DM Red using the command [$]play

**Comment by Gtoyos** [comment]
Most audio commands throw a trace-back if you invoke them on  Red's DM.
guild_only() should be used.

**Comment by Gtoyos** [comment]
Most audio commands throw a trace-back if you DM it.
guild_only() check should be used.

**Comment by tekulvw** [comment]
Fixed with #1682
