### ISSUE TITLE
I really need a custom cog

### ISSUE THREAD

**Issue by ddday** [Cog-Creators/Red-DiscordBot#169]
As the title states, I really need a custom cog, I would be willing to pay 5-10 dollars for it.

I really need this and would appreciate it if someone would at least reply.

Thank you for considering!

**Comment by franc-ist** [comment]
we can't help if you don't tell us what you want

**Comment by ddday** [comment]
I want a store based of the economy cog where a user would be able to say a command and a certain amount of points would be subtracted from the user's  economy bank balance and they would be given a tag.

**Comment by franc-ist** [comment]
#136

**Comment by Kowlin** [comment]
@ddday join the server and PM me, Lets have a little talk ;)

**Comment by irdumbs** [comment]
seriously? #136 
@Kowlin I recommend just making a PR to ~~red.py~~ (can and should be done in a separate cog) with this capability
#110

**Comment by Kowlin** [comment]
Somewhat working on it, development is a bit slow though.

**Comment by tekulvw** [comment]
Closing as not related to core bot development. Feel free to make a new post [here](https://github.com/Twentysix26/Red-Cogs)
