### ISSUE TITLE
[V3 Downloader/RepoManager] Hidden treated as disabled

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1690]
hidden no longer has it's v2 behavior: would be nice to have a `disabled` key to behave as the current hidden, and hidden get the v2 behavior back

Also, the minimum python version doesn't prevent cogs from being shown to people with lower python versions, just from installing which leads to fun and confusing user interactions.

**Comment by mikeshardmind** [comment]
So, it's come to my attention that I was mistaken about the key's current purpose. This is now a feature request, and I'll be updating the original with full details.

**Comment by tekulvw** [comment]
Fixed with #1828
