### ISSUE TITLE
[V3/Economy] Transfer sends completed message while having insufficient funds.

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#1697]
# Command bugs

#### Command name

`[prefix]bank transfer <user> <amount>`

#### What cog is this command from?

Economy

#### What were you expecting to happen?

Only the insufficient funds message should be displayed.

#### What actually happened?

![image](https://user-images.githubusercontent.com/18455011/40447093-73485d68-5e9f-11e8-9140-53c031ae9ba1.png)

#### How can we reproduce this issue?

Attempt to transfer funds that exceed your balance to another user.

**Comment by tekulvw** [comment]
Fixed in #1698
