### ISSUE TITLE
[V3 Audio] 'Not found' when attempting to use [p]play

### ISSUE THREAD

**Issue by tyhi** [Cog-Creators/Red-DiscordBot#1704]
# Command bugs

#### Command name

[p]audio [youtube-url/search]

#### What cog is this command from?

Core Audio

#### What were you expecting to happen?

The supplied url to be played/given search to have result.

#### What actually happened?

When command is ran, 'Nothing found' is returned. This is the result regardless if a search was given or a direct URL was.

#### How can we reproduce this issue?

I haven't been able to find another issue with this reported but even after reinstalling redbot this issue persists. I've also reloaded the audio cog multiple times. Nothing is outputted in the console so no "errors" are happening.

**Comment by aikaterna** [comment]
I'm curious if you're on Ubuntu 18.04 with Java 10. If so, this might be of some help for you: https://askubuntu.com/questions/971059/17-10-openjdk-and-oracle-jdk-8-and-9-the-trustanchors-parameter-must-be-non-empt/991636#991636

**Comment by tyhi** [comment]
That was indeed it. Thanks much.
