### ISSUE TITLE
add more supported audio extensions

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#171]
To help test, find all the occurences of .mp3 in audio.py  
![image](https://cloud.githubusercontent.com/assets/15660809/14598041/c5eefc46-0593-11e6-81a3-1f8b5c81667b.png)  
![image](https://cloud.githubusercontent.com/assets/15660809/14598052/cefced70-0593-11e6-8d3e-6ac963b7a43d.png)  
![image](https://cloud.githubusercontent.com/assets/15660809/14598060/da89631c-0593-11e6-903c-37d74b516582.png)  
Add other extensions, and start testing!  
There's probably a good reason why other extensions aren't supported. We'll either find out during testing or we'll get yelled at. Either way, we'll find the answer.

To test:  
- [x] m4a
- [ ] vcc

Approved:
- [ ] m4a
- [ ] vcc

**Comment by tekulvw** [comment]
Yeah, this was done in the rewrite
