### ISSUE TITLE
[V3] Fire an event on modlog case creation

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1716]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

This would add an event that gets fired when a modlog case is created. Some cog could then handle that in a function `on_modlog_case_create` or something like that to do something when a modlog case is created (for example, possibly notifying the affected user via DM when a case is created that they are the subject of)

Tagging @retke because this idea spawned out of the example I mentioned above

**Comment by laggron42** [comment]
Maybe it would be good to edit mod.py so it creates the modlog **before** performing the action, so the 3rd party cogs can do their things before losing access to the member.
