### ISSUE TITLE
[V3] Fusion between mod and warnings

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1718]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

The warnings cog allow to warn users with a well done system for selecting pre-made reasons and perform automatic mod actions with the points system. However, some problems exist with this cog:

- no interaction with modlog
- no DM being send to the warned member

These features are almost always there on most used bots (thinking about Dyno which has a cool automod system). 

Plus, the mod cog doesn't have a pre-made reason system nor it has automod. I'm thinking about merging those two cogs, so each can benefit of the other features (again, pre-made reasons, automod, modlog...). What do you think about that?

**Comment by mikeshardmind** [comment]
I think adding a "{user} recieved a warning" entry to the modlog would be plenty to fill this. Warnings can already issue messages to users through automated actions in the warning system, and it does interact with modlog if the warning results in a mod action being taken.

**Comment by palmtree5** [comment]
`Warnings` actually does register a case type with the mod log, but the warn command doesn't actually call it atm (that could probably change though). 

As for automod features, that's things like `[p]modset banmentionspam`, `[p]modset deleterepeats`, and the `Filter` cog (though it requires manually adding words to the filter) which already exist in core.

**Comment by tekulvw** [comment]
This issue is fixed with #2471
