### ISSUE TITLE
Bot stops playing when it encounters a song that has been removed from Youtube

### ISSUE THREAD

**Issue by joshstricklin** [Cog-Creators/Red-DiscordBot#1728]
If the playlist comes to a song that has been removed from Youtube, the bot will give me this error: I'm unable to play 'https://www.youtube.com/watch?v=QZXc39hT8t4' because of an error:
'[0;31mERROR:[0m unable to rename file: [Errno 2] No such file or directory: 'data/audio/cache/QZXc39hT8t4.part' -> 'data/audio/cache/QZXc39hT8t4''

And stop playing entirely. I have to restart the bot (and then the playlist) to get it to resume playing, and then it will quit playing entirely the next time it hits a removed song.

**Comment by Tobotimus** [comment]
Thanks for your issue, and sorry it took so long for a response.

We'd probably accept a PR for this despite V2 being very low priority right now. However considering we don't have one yet, this is unlikely to be fixed.
