### ISSUE TITLE
[V3] Listener for loaded cogs

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1738]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

A listener that would be triggered when a new cog is loaded would be great and bring a lot of possibilities to cog creators. Hope this can be added, never used asyncio so I can't do it myself.

**Comment by mikeshardmind** [comment]
Maybe I'm missing something here, but what exactly is the use case for dispatching this to cogs?

**Comment by laggron42** [comment]
Make events for command replacement, for example.

**Comment by mikeshardmind** [comment]
This would require both commands to be aware of replacement as a cog can't be loaded if it's commands can't be added, and both would likely want to replace each time it happened leading to loop endless loop conditions. It would be better to have this solved with dynamic command renaming on conflict.

**Comment by Tobotimus** [comment]
Dynamic command renaming is definitely something we've discussed and something I'd like to see as a feature in the future. However, I'm still interested in this request. @retke do you have an idea of which arguments should be passed to the event handler?

**Comment by laggron42** [comment]
The class object should be enough since you can get its name, its docstrings, its config object and all commands...

**Comment by The-Tasty-Jaffa** [comment]
I do think this will/can be a useful feature and could be used for more than just command replacement.

**Comment by Tobotimus** [comment]
This was added in #2149, use the event `on_cog_add`.
