### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by Papy-Serra** [Cog-Creators/Red-DiscordBot#174]
Hi !

I have a problem, i can't play a video/song from Youtube, because i have a problem with my hosting. I need to foce ipv4. So for that i need to add a parameter when Red-DiscordBot use youtube-dl.
I change the configuration file for youtube-dl and it's work but not wiht the Red-DiscordBot.

So could you help me to add a parameter -4 when Red-Discord call Youtube-dl.

Thanks,
Regards,
Misteralex007

**Comment by Twentysix26** [comment]
Solved
https://github.com/rg3/youtube-dl/issues/9244
