### ISSUE TITLE
[V3] Setup error with invalid token

### ISSUE THREAD

**Issue by Eslyium** [Cog-Creators/Red-DiscordBot#1765]
# Other bugs

#### What were you trying to do?
Reset token during setup when token is invalid

#### What were you expecting to happen?
Be able to reset the token and enter a new one

#### What actually happened?
sys:1: RuntimeWarning: coroutine 'Value._get' was never awaited and then kicks you out of setup.

![image](https://user-images.githubusercontent.com/18387809/40869498-32289df0-65ea-11e8-8384-f1ff9f7eab3a.png)

#### How can we reproduce this issue?
Ubuntu 16.04
redbot-setup and put an invalid token it will ask if you want to reset it, respond with y.

**Comment by tekulvw** [comment]
Fixed with #1771
