### ISSUE TITLE
[V3] Cogs missing from help list

### ISSUE THREAD

**Issue by Eslyium** [Cog-Creators/Red-DiscordBot#1768]
# Other bugs

#### What were you trying to do?

View cogs in help list

#### What were you expecting to happen?

See all cogs loaded in help

#### What actually happened?

Out of 19 loaded cogs (all the default that come with red) only 15 cogs were showing in the help list.
In this case I was missing CustomCom/Audio/Alias and couldnt find the other one.

#### How can we reproduce this issue?

Start a fresh bot, load all the default cogs and check the help command list.

**Comment by mikeshardmind** [comment]
Is this occuring on b15, b15post1 or post2, or off the development build? I cannot reproduce this issue locally.

**Comment by Eslyium** [comment]
This is off the Development build, Iv come to find out literally just now that if you do the help command in dms you get less pages given compared to outside dms

**Comment by Tobotimus** [comment]
This is intended behaviour - running `[p]help` in DM will hide any commands which can't be run in DM, and that includes the ones you mentioned were missing.

There may be some commands which are missing a `guild_only()` check when they should have one, in which case they will show up in the help message in DM, and can also be run in DM (most certainly resulting in an error). For these commands, please open a new issue :)
