### ISSUE TITLE
[V3 Modlog] Disallow the bot to post modlogs about itself

### ISSUE THREAD

**Issue by Eslyium** [Cog-Creators/Red-DiscordBot#1775]
# Other bugs

#### What were you trying to do?
Orignally used Warnings to kick it at a certain point limit, but doing a normal mod action (kick) does it.

#### What were you expecting to happen?
The bot to not do anything

#### What actually happened?
The bot didnt kick itself but made a Modlog post

![image](https://user-images.githubusercontent.com/18387809/40872229-bc740cdc-6618-11e8-860e-b96d02bbff72.png)

#### How can we reproduce this issue?
Try to kick the bot

**Comment by tekulvw** [comment]
Fixed with #1777
