### ISSUE TITLE
[V3] Remove "ctx.invoked_subcommand is None" boilerplate

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1785]
The vast majority of command groups send the help message when no subcommands are given - they do this with a statement like:
```py
if ctx.invoked_subcommand is None:
    await ctx.send_help()
```

This is really common and honestly, it's unnecessary boilerplate. It gets worse when we have sub-groups, with people often using `isinstance` checks to send help there. 

@mikeshardmind came up with the suggestion to add this to the `group()` decorator instead, but optionally disable it with a flag in case automatically sending help on no invoked subcommand wasn't desired.

We realised this would introduce a somewhat breaking change - all of a sudden, 3rd party cogs who hadn't removed the call to `ctx.send_help()` would be getting duplicate help being sent. For this reason, we've proposed a grace period where the flag will default to `False`, and will be set to `True` for beta 17.

**Comment by tekulvw** [comment]
Fixed with #1790
