### ISSUE TITLE
Online Radio support

### ISSUE THREAD

**Issue by hjri** [Cog-Creators/Red-DiscordBot#179]
like icecast/shoutcast?

**Comment by irdumbs** [comment]
had pandora info on my todo list
what are the popular radio solutions?

**Comment by hjri** [comment]
### Audio stream radio (which i had in question):
- I use **IceCast2** - http://icecast.org/ FOSS online radio.
- There's also **SHOUTcast**, which I think uses same protocol https://en.wikipedia.org/wiki/SHOUTcast
  (Actually, it's IceCast that uses shoutcast's protocol)

These are just an encoded audio stream broadcasted over (i think) RTMP. Basically it is a continuous stream of audio, kinda like FM radio. Content can be anything - you can hook up your microphone to it or set your music player to output it there.

### Modern streaming services I know:
- spotify
- google play music
- pandora
- ~~yandex music~~ (russian stuff)

These I think more like audio-on-demand. I only used google and yandex and both of them just loads separate song in a (locked) playlists.

**Comment by irdumbs** [comment]
so pandora doesn't have an official API, so any implementation will be unofficial. Not sure how Pandora will like that..
I love their selection and whole music genome thing though..

Does spotify come close to pandora's quality in that?

**Comment by franc-ist** [comment]
Spotify API wrapper: https://github.com/plamere/spotipy

@irdumbs

**Comment by irdumbs** [comment]
yeah... but I still want a solution that mimics pandora.
If someone is willing to work with me to mimic pandora's song selection without overstepping copyrights n such, please let me know.
we can probably get somewhat similar results from spotify, just have to recreate radio stations and limit repeats

**Comment by franc-ist** [comment]
hmm

**Comment by hjri** [comment]
maybe we should create separate issue for Icecast\Shoutcast support?

icecast\shoutcast support it pretty much transcoding continous audio stream from some internet source to discord.

pandora\spotify support seems to me is using some service-specific APIs and workarounds.

**Comment by irdumbs** [comment]
ah i didn't realize. naw, you can keep this as icecast\shoutcast

**Comment by orels1** [comment]
@hjri can you send me some examples of icecast-based stations to test against? I'm willing to dive into it a bit

**Comment by hjri** [comment]
@orels1 

Quick example - http://stream.gensokyoradio.net:8000/stream/1/

There's directories of public radio stations: 
Icecast: http://dir.xiph.org/
Shoutcast: http://www.shoutcast.com/

Usually radio stations\directories provide a playlist (pls\m3u\xspf) which contains only one item - URL to the radio like in quick example, so just take them out from there or just feed playlist to the bot if it supports it like that.

**Comment by irdumbs** [comment]
with the rewrite, that'll probably be a separate cog that communicates with the audio cog.

The way your describing it is similar to what I was thinking about with pandora/spotify.
perhaps we can roll them all up together if there's no copyright issues

**Comment by LGACode** [comment]
@irdumbs The first music streaming service that came to my mind that's similar to the Music Genome Project is Last.fm, and they have an official API.

http://www.last.fm/api

This would also allow users in a server to use a command to show what they are currently scrobbling or what they last scrobbled, and some minor stats with it. You would use a command to tell the bot what your Last.fm account name is so whenever you use other commands related to Last.fm, it associates your server nick with your Last.fm account.

Example: 

> [22:26:54] <CandleGlow> !np darkf
> [22:26:55] <Demonbot> Milo - sophistry and illusion ft. Nocando - cavalcade - Times Played: 5 - http://www.last.fm/music/Milo/_/sophistry+and+illusion+ft.+Nocando

**Comment by franc-ist** [comment]
@Codered999 there are already last fm cogs that have been developed

**Comment by irdumbs** [comment]
I think he's talking about using it to keep playing similar tracks based on your seeds/likes/dislikes like pandora does

**Comment by LGACode** [comment]
@irdumbs Exactly, they use advanced statistics based on scrobbles, and you can even fine tune the bot to utilize it's Decade vs Genre picker for even more similar tracks while still keeping things fresh.

**Comment by SapphicCode** [comment]
Google Play Music doesn't actually have an official API either, but [this](https://github.com/simon-weber/gmusicapi) looks like it might work.

**Comment by ccubed** [comment]
You can't actually play spotify music, because it's against the TOS. Online radio is much easier, ffmpeg can parse m3u's or direct streams.

**Comment by Twentysix26** [comment]
No plans for it in the near future.
