### ISSUE TITLE
[V3 i18n] Missing translations

### ISSUE THREAD

**Issue by WiNiW** [Cog-Creators/Red-DiscordBot#1791]
# Command bugs

#### Command name

play, queue and others from audio, stream

#### What cog is this command from?

audio, streams, others

#### What were you expecting to happen?

Find string for all commands/posts from all cog for translating

#### What actually happened?

Not every command or post has an translation

#### How can we reproduce this issue?

Check "cogs\audio\locales", "cogs\streams\locales", etc.

**Comment by Tobotimus** [comment]
We are working on improving translation coverage. I've just started a feature branch for people to help contribute to this until we have satisfactory coverage. I'm gonna close this now as it's a bit of a vague issue which isn't tracking anything specific, but thank you for your concern.
