### ISSUE TITLE
[V3 Fuzzy Help] Used with custom commands

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1796]
# Other bugs

#### What were you trying to do?

Use a custom command

#### What were you expecting to happen?

Print the text assigned to the custom command.

#### What actually happened?

The text was posted, with the fuzzy help message.

#### How can we reproduce this issue?

**This must be realised with a release containing the fuzzy help feature**

Create a custom command, call it, and the fuzzy help will show with the custom command.

**Comment by tekulvw** [comment]
This is already fixed with #1788
