### ISSUE TITLE
[V3 Menu] Listen before adding reactions

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1797]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

The menu tool provided by Red currently do the following steps when called:

1. Post the message
2. Add the reactions to the message
3. Start listening to the reactions
4. Do something when the message received a reaction.

This should be modified to work like that:

1. Post the message
2. **Start listening to the reactions**
3. **Add the reactions to the message**
4. Do something when the message received a reaction.

Currently, we have to wait for all of the reactions before clicking on something. This is quite annoying, especially with the `[p]search` command of Audio, which adds a lot of reactions. For example, if we already know that we want the number 2 result, we can't click on 2️⃣, we need to wait for all reactions before acting.

**Comment by Tobotimus** [comment]
I'll give this a go but I don't think I'll be able to make the order of execution so deterministic, but rather allow the event loop to give the impression that it happens in this order, using `create_task`

**Comment by tekulvw** [comment]
Fixed with #1808
