### ISSUE TITLE
[V2] "pm2 startup" error when setting up autorestarting on Linux

### ISSUE THREAD

**Issue by Kovaelin** [Cog-Creators/Red-DiscordBot#1798]
# Other bugs

#### What were you trying to do?

I was trying to setup autorestarting on Linux. I got up all the way up to `pm2 startup` before getting the final error message.

#### What were you expecting to happen?

I was expecting to get a command that I would need to issue before autorestarting would take effect.

#### What actually happened?

I was actually able to get pm2 running, however I am receiving this message when I try using `pm2 startup`

> [PM2] Init System found: systemd
Platform systemd
Template
[Unit]                                                                       
Description=PM2 process manager                                              
Documentation=https://pm2.keymetrics.io/                                     
After=network.target                                                         
>                                                                              
> [Service]                                                                    
Type=forking                                                                 
User=root                                                                    
LimitNOFILE=infinity                                                         
LimitNPROC=infinity                                                          
LimitCORE=infinity                                                           
Environment=PATH=/root/.nvm/versions/node/v10.1.0/bin:/bin:/usr/local/sbin:/u
sr/local/bin:/usr/sbin:/usr/bin                                              
Environment=PM2_HOME=/root/.pm2                                              
PIDFile=/root/.pm2/pm2.pid                                                   
>                                                                              
> ExecStart=/root/.nvm/versions/node/v10.1.0/lib/node_modules/pm2/bin/pm2 resur
rect                                                                         
ExecReload=/root/.nvm/versions/node/v10.1.0/lib/node_modules/pm2/bin/pm2 relo
ad all                                                                       
ExecStop=/root/.nvm/versions/node/v10.1.0/lib/node_modules/pm2/bin/pm2 kill  
>                                                                              
> [Install]                                                                    
WantedBy=multi-user.target                                                   
>                                                                              
> Target path
/etc/systemd/system/pm2-root.service                                         
Command list
[ 'systemctl enable pm2-root',
  'systemctl start pm2-root',
  'systemctl daemon-reload',
  'systemctl status pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
[PM2] Making script booting at startup...
[PM2] [-] Executing: systemctl enable pm2-root...
[PM2] [v] Command successfully executed.
[PM2] [-] Executing: systemctl start pm2-root...
Job for pm2-root.service failed because the service did not take the steps re
quired by its unit configuration.                                            
See "systemctl status pm2-root.service" and "journalctl -xe" for details.    
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-root failed, see error above.

#### How can we reproduce this issue?

I am not sure, but I believe it may have something to do with me unsuccessfully trying to do the systemd steps on this page: https://twentysix26.github.io/Red-Docs/red_guide_linux_autostart/

Doing the systemd steps before doing the pm2 steps, instead of only doing the pm2 steps, might have caused conflicts with the ".service".

I do not know how to go back and delete the bad "red.service" that might have been created or what to do with "systemctl status pm2-root.service" and "journalctl -xe".

Any help would be appreciated. Thanks

**Comment by Tobotimus** [comment]
Hi, sorry this took so long for a response. I'm unfortunately not an expert on the subject, but perhaps the helpful people in our Support Squad could give you a hand over in #support at https://discord.gg/red. Thanks!

**Comment by Kovaelin** [comment]
I eventually decided to start over and skip over the systemd part, but I'm not sure how to fix it if somebody else comes across the problem.
