### ISSUE TITLE
[V3 Audio] Remove status message

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1799]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

When a song is finished or stopped (with `[p]stop` or `[p]disconnect`), the status message (Listening to...) is staying. This should be removed automatically.

**Comment by Tobotimus** [comment]
Thanks for opening an issue :)

First of all, isn't this a bug report, not a feature request? Secondly, I can't reproduce this. The status messages are functioning fine for me. Here was one of my attempts at reproducing it:

In server 1:
 - `[p]play song1`
 - Bot sets its playing status as *Listening to song1*

In server 2:
 - `[p]play song2`
 - Bot sets playing status as *Listening to music in 2 servers*

In server 1:
 - `[p]stop`
 - Bot sets playing status to *Listening to song2*

In server 2:
 - `[p]disconnect`
 - Bot removes its status

**Comment by laggron42** [comment]
Yep, choose the wrong template, sorry. I can reproduce the issue by doing this:

- play and reload the cog
- stream with two servers at the same time (status tries to focus on both servers, this should just focus on one)
- disconnect from the channel (random)
- end queue (still random)
- type actions quickly (this is not a good behavior but there should be more checks anyway) 
- stop the stream (lavalink kill or crash, again put more checks or the status stays forever)

Most of that stays random tho, but could be fixed by more checks (like on unload)

**Comment by tekulvw** [comment]
I'm calling this PEBKAC, we can't handle every possible scenario and reloading the cog + killing the lavalink server is a good way to break things no matter what.

**Comment by laggron42** [comment]
Lavalink can break at any time from my experience, and this is simulating an error while a song is playing...
