### ISSUE TITLE
m3u files support?

### ISSUE THREAD

**Issue by hjri** [Cog-Creators/Red-DiscordBot#180]
or any playlist files support. symlinking audio files to a folder is tedious

**Comment by Kowlin** [comment]
m3u's aren't supported by ffmpeg, To make a playlist you'll need to copy the files into a folder under `data/audio/playlists`

**Comment by hjri** [comment]
that's tedious. can't bot itself read the m3u file?

**Comment by Kowlin** [comment]
No, there is no code for that in place.

**Comment by irdumbs** [comment]
how do you suggest we do it?
we can look into it but i have no idea what a m3u is :3

**Comment by hjri** [comment]
`.m3u` file is just a list of paths (relative to the file itself). there could be some metainformations written before each line.

https://en.wikipedia.org/wiki/M3U

There's also other playlist formats like `.pls`
These are pretty much the most common playlist format used by media players.

**Comment by hjri** [comment]
you could probably just import files listed in playlist into Bot's internal local playlist.

**Comment by hjri** [comment]
skipping over unsupported files or links of course if needed.

**Comment by irdumbs** [comment]
Referenced in #185
