### ISSUE TITLE
[V3 Help] Displaying the bot's mention as a prefix

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1801]
@Kowlin has given a good example of how this is currently displayed here:
![screenshot](https://media.discordapp.net/attachments/251782448629809152/453437266119884811/unknown.png?width=432&height=465)

Obviously this is ugly and undesired - I think in this circumstance the help formatter should detect that the prefix was a mention, and replace it with `@BotName` instead.

**Comment by tekulvw** [comment]
Fixed with #1823
