### ISSUE TITLE
[V3 Help] Cannot invoke in DM due to missing color

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1802]
# Command bugs

#### Command name

help

#### What cog is this command from?

None

#### What were you expecting to happen?

List all of the commands since it was invoked without any arguments

#### What actually happened?

Error because of unknown role color

#### How can we reproduce this issue?

Run the help command in DM.

![screen shot 2018-06-05 at 11 00 11](https://user-images.githubusercontent.com/23153234/40966078-ce782820-68af-11e8-92cc-310a06a79921.png)

**Comment by mikeshardmind** [comment]
This was already fixed in #1750
