### ISSUE TITLE
[V3 Audio] Lavalink status

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1811]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

I think that it would be great to have a command that shows lavalink status, so we could directly know if lavalink is running, on which ports... At least we could know why the bot is always returning "Not found" or that kind of things.

Also the command shouldn't be added under the audio cog, but without cog using `bot.add_command()` (so it will be shown in the "No category" section, but we can make it hidden). Why such a thing? Because the cog is directly linked to lavalink and sometimes, when it crash, the commands gets unloaded, so something independent from the audio cog would be great to know what's really going on!

**Comment by tyhi** [comment]
In regards to "Not found" #1704 which has to do with java certs.

**Comment by Drapersniper** [comment]
Red should nowdays be giving more detailed reason why something can't be played.

Not found would be a tricky one.

As part of the major rework of Red, `[p]node info` and `[p]node list` are commands which will display basic information about the nodes.

**Comment by Flame442** [comment]
In the past, perhaps the error messages were not as clear, however between `[p]audioset info`, the error messages, and the console and lavalink logs, I don't believe this information is as hard to find as it once was. For that reason I am going to close this issue, if there are any specific cases that are not clear still and need an update, feel free to make a new issue with up to date information.

**Comment by laggron42** [comment]
You forgot to actually close the issue
