### ISSUE TITLE
[V3 Downloader] [p]repo add does 3rd party check without arguments

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1819]
# Command bugs

#### Command name

[p]repo add

#### What cog is this command from?

Downloader

#### What were you expecting to happen?

The command should just show the help message, I shouldn't have to agree unless I'm actually adding a repository

#### What actually happened?

![screenshot of output](https://user-images.githubusercontent.com/7438501/41107128-fbc60250-6ab4-11e8-8a82-5f271a76b895.png)

**Comment by tekulvw** [comment]
Fixed with #1821
