### ISSUE TITLE
[V3 Help Formatter] Additional handling for arguments...

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1824]
# Feature request

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

putting `{prefix}`or `{botname}` in the docstrings should get formatted appropriately. We already do certain things to docstrings anyway, we can add a keyword format to them as well to add extra formatting niceness for user-facing help.

**Comment by Tobotimus** [comment]
Yep, totally agreed. What are people's thoughts on replacing `[p]` with the prefix as well?

**Comment by mikeshardmind** [comment]
I think filling with format is a more pythonic handling and makes more sense since this will only ever be developer facing, users will only see the end result.

Here's the full list of useful parameter's I would want to fill with

`{me}` this gets the bot user or member (based on context)
`{prefix}` the `clean_prefix` from helpformatter
`{author}` the author object

Additionally, I'd like to include access to
`{channel}` and `{guild}`

The question comes in on including these as the full objects or only providing representations of them. The latter is technically safer, but the first allows more flexibility of use, and anything unsafe could be done without any user interaction at all if someone loaded a malicious cog anyway.

**Comment by Tobotimus** [comment]
I support all of those propositions, but I also think `[p]` is worth replacing with `clean_prefix` since it's an existing habit amongst cog creators for referring to the prefix, and occurs throughout existing docstrings - it's an enhancement to the UX without cog creators having to make any changes.

I can't see any reason not to include the full objects in this case. As you've basically pointed out safety is a bit of a null factor in this conversation.

**Comment by mikeshardmind** [comment]
I think `[p]` is better used to represent that any prefix could be used, while actually inserting the current prefix is better if instructing on usage for a specific command. It's a subtle distinction, but I can think of at least a few ways this separation could be useful.

**Comment by Tobotimus** [comment]
Well I was going to just say we agree to disagree, but as it turns out the `[p]` in command help is already being replaced. The more you know!

**Comment by mikeshardmind** [comment]
this is better covered by changes being tracked in #2981
