### ISSUE TITLE
[V3] Audio: Multiple skips

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1845]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Skip more than one song, incredibly useful if you've got playlists with over 100 songs..

**Comment by Eslyium** [comment]
Now let me ask why would you want to skip more than one song? If its a playlist you put together just use the shuffle command to have the bot go around to different songs, I really don't see why this would be implemented.

**Comment by Ray-MRQ** [comment]
Okay, this my own playlist of over 330 songs. https://www.youtube.com/playlist?list=PLY1qMW_YV-SMFNl8qoU1daXpx15Kdl_hs 

Dislike shuffle due to having my better songs at the top, however, I've got some goods stuff at the bottom, skipping instead of shuffling guarantees my chances of getting that song I want, whereas shuffle may take a while.

An example tracks from 110 -120 I quite like, so instead of shuffling, skip to 110, and that's it.

**Comment by Eslyium** [comment]
You can use the bump command to push the songs you like up the list and then save it in that format.

**Comment by Ray-MRQ** [comment]
Can't save if the playlist gets updated every few days, as well as, bumping 10-20 songs is a bit much..

**Comment by Tobotimus** [comment]
Adding to #623 but this is going to be freezed whilst we ponder bigger issues, unless someone is willing to open a PR for it.
