### ISSUE TITLE
[V3] Request- Per server Cog disabling?

### ISSUE THREAD

**Issue by Kio-td** [Cog-Creators/Red-DiscordBot#1846]
I'm curious if there will be support to disable cogs per server in the future.

**Comment by mikeshardmind** [comment]
There already is with the permissions cog. 

```
[p]permissions addglobalrule deny SomeCog SomeGuildIdhere
```
For more details on this, see the [docs page on permissions](http://red-discordbot.readthedocs.io/en/v3-develop/cog_permissions.html)

**Comment by Kowlin** [comment]
Can confirm that this is done by doing the above. Also know that you can do ``permissions addglobaldefault deny SomeCog``. Closing this.
