### ISSUE TITLE
[Warnings] Feedback

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1851]
Alright... I've putted this off for long enough. Lets throw some feedback! I'm going into this as someone who has never tried out Warnings and going in blind.

### Verbose warnings
Lets start with the obvious elephant in the room. It doesn't actually send a warning to the warned user which in my opinion kinda beats the point of warning users. I've tried looking at it from many different angles on how this can be used on servers but verbose warnings is the only way I can see this being fitting in existing mod scenarios.

### Lists
The current method ``reasonlist`` and ``actionlist`` currently list their actions is a bit outdated to say the least. This could be updated to use the core reaction menus.

### Actions
The current method of creating actions is confusing: This is because the 2 help messages provided while making a action are confusing and long. They look near identical.

Also when you've created a action is delivers no verbose output besides a reaction which is easily missed under half the page of test and commands provided by both the user and bot in the same channel. Recommended fix for this would be to have the bot just output it normally instead of a reaction.

And finally on the subject of warnings. There is a requirement to set a 2nd command on a action. In some cases this is in-logical. Since as example I can have a kick set at the first command, but I cannot have a command that undoes the kick, since that's simply not possible.

### Other errors
Besides that Sentry *should* have collected errors for Warnings, if not I can go cause them again.

https://sentry.io/will-tekulve/bot-development/issues/566992026
https://sentry.io/will-tekulve/bot-development/issues/560365892

Further then this I really couldn't dive more into the functionality of Warnings due to the above issues.

**Comment by Tobotimus** [comment]
Status of this following #1867?

**Comment by Tobotimus** [comment]
Closing as I'm assuming this was resolved by #1867.
