### ISSUE TITLE
[V3 Config] Detect changes on backend, and only write when there are changes.

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1857]
- [ ] Cog
- [ ] Command
- [X] API functionality

Right now, config will always write when using a context manager, there's no need for this since we should be returning a copy of the data, not the original (see #1855 ). While this can be avoided in some cases by a design choice, there may also be cases where the code doesn't know if something needs to change in the mutable data until checking it. We should instead modify Config's handling of this to be more IO aware, and not make unneeded writes.

**Comment by Tobotimus** [comment]
Resolved by #1859
