### ISSUE TITLE
[Cleanup] Cleanup messages cleans up 1 to many messages

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1863]
# Command bugs

#### Command name

cleanup messages <amount>

#### What cog is this command from?

Cleanup

#### What were you expecting to happen?

We all know this, cleaning up the exact amount of messages provided in amount.

#### What actually happened?

``cleanup messages`` will clean up the messages + 1, as example if you cleanup 5 messages, it will cleanup 6 messages. Its unknown to me if this applies on messages with a warning on it when cleaning above 100 messages. 

#### How can we reproduce this issue?

Cleanup a number of messages.

**Comment by Tobotimus** [comment]
Resolved by #1864.
