### ISSUE TITLE
[V3 Downloader] bot_version info.json key not used

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1866]
# Other bugs

#### What were you trying to do?

Try putting the minimum required bot version in the info.json

#### What were you expecting to happen?

This version to be checked

#### What actually happened?

There is no check for it in the code

#### How can we reproduce this issue?

1. Put the `bot_version` key in the `info.json` with a value that should cause the cog to not install
2. Try installing that cog
3. Cog installed

**Comment by Tobotimus** [comment]
Needs more discussion on how we want to use this key. At the very minimum I think it should give a warning when `[p]cog update` installs the latest version of a cog which has a higher bot version than the one installed. It could also give the warning and hold back the installation, then the user would need to do `[p]cog update` again once they've updated their bot. Same suggestions apply with `[p]cog install`.

I'm gonna freeze this until more progress has been made on #1683, as I think there are other features there with higher priority.

**Comment by Jackenmen** [comment]
This was fixed with #2605, though it still doesn't check it with `[p]cog update`
