### ISSUE TITLE
Bad Audio Quality When Playing From Local Files...?

### ISSUE THREAD

**Issue by Yukinekos** [Cog-Creators/Red-DiscordBot#1870]
Hi.

Just like the title says; whenever I play anything from my local files with the red bot the quality just seems.. bad. All my music files are 320k and other bots (which don't play from local apart from 1) play in standard quality at least. Unlike red.

Is there anything I can do to fix this?

Thanks

**Comment by aikaterna** [comment]
The bot streams at 64k and it's also limited by the bitrate of your voice channel (max 96 unless you're on a partnered server, then it's 128).

**Comment by Yukinekos** [comment]
Oh... 64k is so low that's sad ;/

**Comment by Tobotimus** [comment]
V2 ain't gonna get this change sorry. Expect better quality overall in V3 audio, but local audio is a WIP feature there.
