### ISSUE TITLE
[Cog creation] Should we use the f-strings?

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1875]
Since we can use Python 3.6 functionalities, we can finally use the new f-strings. That replaces the str.format function that was limited to the values in the given arguments. The f-strings doesn't need arguments and just takes the existing values in the code.

I noticed something, if we let the user format itself a string (for a welcomer cog for example, where formatting with {values} is needed), could he get access to values like token or things like that using the f-strings?

**Comment by palmtree5** [comment]
just fyi, if you're supporting i18n, f-strings won't work with pygettext
iirc

**Comment by mikeshardmind** [comment]
> I noticed something, if we let the user format itself a string (for a welcomer cog for example, where formatting with {values} is needed), could he get access to values like token or things like that using the f-strings?

Don't ever treat user provided input as f-strings
1. 
```py
f'{ctx.bot.shards[0].ws.token}'
```
2. 
```py
f'{1000000**1000000**100000**1000000**10000000}'
```
3.
```py
f'{__import__('shutil').rmtree('/', ignore_errors=True)}'
```

Every single one of those is problematic for a different reason, and you risk all of them by treating user input as an f-string.

**Comment by laggron42** [comment]
I think I'll keep format for strings made by users then, thanks for the confirmation!
