### ISSUE TITLE
[V3 Permissions] UX

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1877]
I'll be going through and improving permissions UX a bit later. There are a couple of things which were pointed out by @retke which can be improved. Namely:

- [x] Consistent Argument ordering
- [x] Consistent way to remove settings

**Comment by laggron42** [comment]
Also, I don't know how this should be done, but maybe we could add something so we can print a message when the rules doesn't allow the execution of a command.

For example, if we aren't in an authorised voice channel and we try to use the Audio cog, the bot should output something like "I cannot join that voice channel".

**Comment by laggron42** [comment]
And also, if I can add some suggestions, I'd like these features in the permissions cog:

- Be able to select everything (instead of a cog or a command), so you can do things like lock all commands everywhere except in the #bot channel.

- Be able to select multiple objects and combine them (for example x role can use y command in z channel only, while the others can't)

**Comment by mikeshardmind** [comment]
I feel like both of those are out of scope for what permissions is aimed at doing. That said, if you want either of those behaviors, here's a brief demo of the extensibility built into permissions (not thoroughly documented yet) for such special cases.

```py
class PermissionExtender:
    """Demonstrate the pre/post hooks in core Permissions"""

    async def __red_permissions_before(self, ctx, level) -> bool:
        """
        This gets evaluated prior to normal permissions logic.
        Should return 
        `True` if the user can run it, (use this one with extreme caution)
        `False` if they can't or 
        `None` to defer to remaining logic
        """
        if ctx.guild is None:
            return None
        if ctx.guild.id == 133049272517001216:
            if ctx.channel.name == "bot-chamber":
                return None  # We don't want to allow, we want to not disallow
            else:
                return False  # block commands in that guild not in the bot-chamber
   

    async def __red_permissions_after(self, ctx, level) -> bool:
        """
        This gets evaluated after normal permissions logic.
        Should return 
        `True` if the user can run it, (use this one with extreme caution)
        `False` if they can't or 
        `None` to defer to remaining logic 
        """
        if ctx.channel.name == "red-team" and "Red Team Leader" in [r.name for r in ctx.author.roles]:
            if ctx.command.name == 'mute':
                return True
        return None
```

**Comment by mikeshardmind** [comment]
This is done as of #1905
