### ISSUE TITLE
[V3 commands] commands.parents

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1880]
Currently, both `[p]permissions canrun` as well as command fuzzy search assume all command objects our ours. The logic for command parents needs to be moved somewhere else, or we need to find a way to enforce using our classes, as neither of these work properly when interacting with 3rd party cogs not using our commands override.

**Comment by Tobotimus** [comment]
Enforcing the use of our command objects is gonna be the way to go here, just less headaches in general. Throwing an exception in `bot.add_command` is one way we could do it.

**Comment by Tobotimus** [comment]
Resolved by #1971.
