### ISSUE TITLE
[V3 Help] Restricted command groups display commands

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#1881]
#### Command name
Group commands that are core with checks for permissions, examples are [p]economyset, [p]cog, [p]repo

#### What cog is this command from?
Downloader and Economy

#### What were you expecting to happen?
Users that don't have permissions for these commands should not receive help when using the commands

#### What actually happened?
A user with no special permissions used [p]repo and the command group help appeared in chat, which shouldn't have been displayed for them. They aren't able to execute the group's subcommands that are shown, as expected.

#### How can we reproduce this issue?
Try !cog, !repo, or !economyset in Red's testing channel

**Comment by mikeshardmind** [comment]
Issue introduced in #1790 working on a fix.

**Comment by Tobotimus** [comment]
Resolved by #1882.
