### ISSUE TITLE
Blade & Soul Emojis

### ISSUE THREAD

**Issue by DemonRem** [Cog-Creators/Red-DiscordBot#1883]
wonder maybe it's possible to add blade & soul emojis , or how I can do it?,

I am sorry I have no clue in development

**Comment by Eslyium** [comment]
You can put the emojis in on your server by itself through Server Settings -> Emoji as long as you have the files for it. 

Other than doing that it would have to be in a cog made by you or someone else which you could request [here](https://cogboard.red/) under the bounties section.

**Comment by DemonRem** [comment]
@Eslyium 

Thank you very much
