### ISSUE TITLE
[V3]  Dev commands and discord.ext.commands

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1884]
Right now, debug/eval (and repl, maybe?) expose `discord.ext.commands` as `commands` Given that we subclass various things in this for our use in `redbot.core.commands`, shouldn't we be exposing our version? In either case, the other is still importable, but it seems our default should be to use our version.

**Comment by Tobotimus** [comment]
Resolved by #1944
