### ISSUE TITLE
[V3 Audio] Unable to create empty playlists

### ISSUE THREAD

**Issue by Crossedfall** [Cog-Creators/Red-DiscordBot#1887]
# Command bugs

#### Command name

`[p]playlist create <name>`

#### What cog is this command from?

Audio

#### What were you expecting to happen?

A empty playlist called <name> should be created

#### What actually happened?

Nothing

#### How can we reproduce this issue?

1. Create a brand new bot instance
2. Attempt to add a new playlist
3. Attempt to list or append tracks to the new playlist

Alt

1. Remove all existing playlists from a bot
2. Attempt to add a new playlist
3. Attempt to list or append tracks to the new playlists

_Attempting to append tracks results in,_ 
>No playlist with that name.

![gif](https://user-images.githubusercontent.com/26130695/41805024-d194427c-7666-11e8-9ce2-675bbfee8d57.gif)

#### Added information

Once you're affected by this bug you can seemingly only create playlists that are pre-loaded with music either through an `[p]eval` command or through `[p]playlist queue`. Tested this on old bots upgraded to the latest development, and, brand new instances created within entirely new hosting environments running the latest develop version.

![image](https://user-images.githubusercontent.com/26130695/41805313-5014bc84-766d-11e8-99b1-eab9845238f0.png)

#### Console `Debug` output

_**Creating empty playlist**_
`DEBUG json_io _save_json 30: Saving file /etc/redbot/<instance>/cogs/Audio/settings.json`

_**Appending music to an empty playlist using `[p]playlist append <name>`**_
`DEBUG json_io _save_json 30: Saving file /etc/redbot/<instance>/cogs/Audio/settings.json`

_**Resulting `settings.json` file**_
![image](https://user-images.githubusercontent.com/26130695/41804892-4277ef0a-7664-11e8-9297-324c21ab3972.png)

**Comment by Kowlin** [comment]
Cannot repro this on my instance.

**Comment by Tobotimus** [comment]
Resolved by #1889.
