### ISSUE TITLE
<p>cleanup messges

### ISSUE THREAD

**Issue by MrUnknownDE** [Cog-Creators/Red-DiscordBot#1893]
Hello,

I found a bug. The command `<p> cleanup messages` does not deal with an error in the console ...
I ask for help

Best regards
Johannes | MrUnknownDE

**Error in the Console:**
`[24/06/2018 11:01] ERROR red on_command_error 369: Exception in command 'cleanup messages'
Traceback (most recent call last):`
`  File "lib/discord/ext/commands/core.py", line 50, in wrapped`
`    ret = yield from coro(*args, **kwargs)`
`  File "/home/red/Red-DiscordBot/cogs/mod.py", line 865, in messages`
`    await self.mass_purge(to_delete)`
`  File "/home/red/Red-DiscordBot/cogs/mod.py", line 1286, in mass_purge`
`    await self.bot.delete_messages(messages[:100])`
`  File "lib/discord/client.py", line 1301, in delete_messages`
`    yield from self.http.delete_messages(channel.id, message_ids, guild_id)`
`  File "lib/discord/http.py", line 200, in request`
`    raise HTTPException(r, data)`
`discord.errors.HTTPException: BAD REQUEST (status code: 400): You can only bulk delete messages that are under 14 days old.`

**Comment by Tobotimus** [comment]
@MrUnknownDE Thanks for opening an issue.

Unfortunately, you cannot use `[p]cleanup` on messages more than 14 days old. That's a rule set by discord, not us. In V3, cleanup never tries to delete messages older that 14 days to prevent this error, but this is unlikely to be backported to V2, sorry. Closing
