### ISSUE TITLE
[V3] cog_data_path() returning wrong path

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#1894]
# Other bugs

#### What were you trying to do?

Grab the data path of a cog not installed in the default install path.

#### What were you expecting to happen?

The cog being able to grab the data directory content.

#### What actually happened?

`cog_data_path()` returned the default install path instead of the new install path, which made the cog error because it couldn't find the files it was looking for.

#### How can we reproduce this issue?

Change the install path for cogs to another directory then install RJM's Pokedex cog and try to search for an item with `[p]pokemon item`, the console will print out that it can't find the csv file because it's looking in the wrong place.

**Comment by Tobotimus** [comment]
You're misunderstanding the purpose of `cog_data_path` and confusing it with the cog install path. `cog_data_path` returns the path where local data is stored, which is set during `redbot-setup`. Passing a cog instance to the function will return the sub-directory corresponding with that cog. Cogs should never need to know (or use) the cog install path.

Your provided reproduction actually highlights an issue with the Pokedex cog, which could be better using the other helpers provided in `redbot.core.data_manager` to bundle and read CSV files.
