### ISSUE TITLE
[V3] error when trying to install

### ISSUE THREAD

**Issue by xenicle** [Cog-Creators/Red-DiscordBot#1897]
# Other bugs

When I'm trying to install Red-DiscordBot I get an error

#### What were you trying to do?

Trying to install red-discordbot

#### What were you expecting to happen?

red-discordbot was installed

#### What actually happened?

get this error message :

pip3 install -U --process-dependency-links red-discordbot[voice] --user

Collecting red-discordbot[voice]
Requirement not upgraded as not directly required: fuzzywuzzy[speedup]<=0.16.0 in ./.local/lib/python3.6/site-packages (from red-discordbot[voice]) (0.16.0)
Requirement not upgraded as not directly required: distro in ./.local/lib/python3.6/site-packages (from red-discordbot[voice]) (1.3.0)
Requirement not upgraded as not directly required: raven==6.5.0 in ./.local/lib/python3.6/site-packages (from red-discordbot[voice]) (6.5.0)
Requirement not upgraded as not directly required: appdirs==1.4.3 in ./.local/lib/python3.6/site-packages (from red-discordbot[voice]) (1.4.3)
Collecting discord.py>=1.0.0a0 (from red-discordbot[voice])
  Could not find a version that satisfies the requirement discord.py>=1.0.0a0 (from red-discordbot[voice]) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.16.10, 0.16.11, 0.16.12)
No matching distribution found for discord.py>=1.0.0a0 (from red-discordbot[voice])

#### How can we reproduce this issue?

pip3 install -U --process-dependency-links red-discordbot[voice] --user

**Comment by skeith** [comment]
Please head to the support channel on discord instead
