### ISSUE TITLE
[Suggestion] List of Aliases

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#190]
Hey, just like being able to see a list of custom commands, it would be awesome if you could view a list of aliases and what each one is an alias _for_.

**Comment by tekulvw** [comment]
Oh, [it's in there](https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/alias.py#L87) under `!aliaslist`. To find out what an alias does, simply use `!alias show <alias_name>`.

I'll make the change to go from `!aliaslist` to `!alias list` for clarity's sake.

**Comment by ghost** [comment]
Aha! Thanks @tekulvw. :heart: It doesn't show what they're an alias for, but all aliases should be self-explanatory anyway. :P

**Comment by irdumbs** [comment]
showing the actual alias within the list would be spam hell.
which is why `!customcommands` also doesn't do that
`!alias show <alias_name>` for aliases that aren't self explanatory ;)
