### ISSUE TITLE
Requirement Installation Error

### ISSUE THREAD

**Issue by camfsd** [Cog-Creators/Red-DiscordBot#1900]
# Other bugs

#### What were you trying to do?

Attempting to install basic requirements + audio requirements through launcher

#### What were you expecting to happen?

Installation without any errors

#### What actually happened?

Error at end of proccess:
`Command "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-c2vbjvkm\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-record-m_cjk74f\install-record.txt --single-version-externally-managed --compile --home=C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-target-wothfk4o" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-c2vbjvkm\PyNaCl\`

#### How can we reproduce this issue?

Not too certain what went wrong or how to reproduce.
- Installed Red-DiscordBot using the installation tutorial on the RedDocs page
- Installed Python WITH PATH
- Installed Git
- Ran Launcher
- Navigated to Install basic requirements + audio requirements
- Waited, then error at end of process.

Running: AWS instance, Windows10 64bit

**Comment by pgaetani** [comment]
`Python37-32`

Use python 3.5 please

**Comment by camfsd** [comment]
Same error.

**Comment by pgaetani** [comment]
Post a screenshot of the error you got with 3.5 please.

**Comment by camfsd** [comment]
[![Screenshot from Gyazo](https://gyazo.com/3f633c3f4008ea3bc3df7900fa47a06a/raw)](https://gyazo.com/3f633c3f4008ea3bc3df7900fa47a06a)

**Comment by laggron42** [comment]
Also you're not providing the full error. The error starts at the line "Traceback (most recent call)" (not in red). Please paste everything from there.

**Comment by pgaetani** [comment]
Look at the path in the error, you're still using 3.7, uninstall 3.7 completely and then install 3.5, afterwards, restart the instance.

**Comment by pozzzzy** [comment]
[![Screenshot from Gyazo](https://gyazo.com/dea559bbc82f6ab154546e84cd1cc04c/raw)](https://gyazo.com/dea559bbc82f6ab154546e84cd1cc04c)

**Comment by camfsd** [comment]
After rebooting instance twice:
[![Screenshot from Gyazo](https://gyazo.com/c55c367e8934a980abdeab8d92884182/raw)](https://gyazo.com/c55c367e8934a980abdeab8d92884182)

**Comment by camfsd** [comment]
Nevermind, Working. Thanks for the speedy help.
