### ISSUE TITLE
[V3 macOS] Issues when installing from pip

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1902]
# Other bugs

#### What were you trying to do?

I was trying to install Red on a fresh install of macOS (nothing installed, clear OS)

#### What were you expecting to happen?

Download Red and make it working.

#### What actually happened?

Lot of things happened with the installation step `pip install red-discordbot[voice]`.

1. discord.py not found. Had to install it manually with `pip install git+https://github.com/retke/discord.py@rewrite`
2. After installing discord.py and red-discordbot, version conflicts were raised.

```
Laggrons-MacBook-Pro:Documents laggron$ pip3 check
red-lavalink 0.1.0 has requirement websockets<5,>=3.0, but you have websockets 5.0.1.
discord-py 1.0.0a1477+g184c430 has requirement aiohttp<3.4.0,>=3.3.0, but you have aiohttp 2.2.5.
```

Even when I fetch the libraries, following the versions I have on my VPS, I still get version conflicts...

#### How can we reproduce this issue?

Try to install Red on a clean installation of macOS HighSierra. I don't know if this is specific to my computer, so I'll link the hardware and version informations.
![screen shot 2018-06-29 at 17 57 16](https://user-images.githubusercontent.com/23153234/42102358-f798e540-7bc5-11e8-8a7b-b059ceb56ff8.png)

**Comment by Tobotimus** [comment]
Not the computer but the way you're installing it. You're installing an incompatible version of discord.py before installing Red. Ours is currently pinned to revision `7eb918b19e3e60b56eb9039eb267f8f3477c5e17`, and can be installed with `pip install git+https://github.com/retke/discord.py@7eb918b19e3e60b56eb9039eb267f8f3477c5e17`.

Also, `pip install red-discordbot[voice]` is not the way we recommend installing Red. The correct way is outlined in the README.
