### ISSUE TITLE
[V3] Audio trivia

### ISSUE THREAD

**Issue by pabloleban** [Cog-Creators/Red-DiscordBot#1903]
# Feature request

Audio trivia support.
Like guessing the song, sound or whatever.

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

It should work the same way as the trivia system we have now.
But instead of text, it should play a YouTube video.

Some examples of the .txt sintaxis for trivias:

## Guessing the game:
``https://www.youtube.com/watch?v=FrceWR4XnVU `shovel knight``
``https://www.youtube.com/watch?v=Fn0khIn2wfc `super mario world``

## Guess the song (Only guitar track):
``https://www.youtube.com/watch?v=hfyE220BsD0`holiday``
``https://www.youtube.com/watch?v=Hh3U9iPKeXQ`sultans of swing``

## Guess the CSGO weapon:
``https://www.youtube.com/watch?v=DYWi8qdvWCk `AK47`AK-47``
``https://www.youtube.com/watch?v=DmuK9Wml88E `P90``

## Guess the LoL champion:
``https://www.youtube.com/watch?v=Hi1kUdreiWk`Jinx``
``https://www.youtube.com/watch?v=PNYHFluhOGI`Teemo``

There are a lot of possibilites and we have almost every tool to do this.

**Comment by aikaterna** [comment]
You may want to suggest this on the cogboard instead. https://cogboard.red

**Comment by pabloleban** [comment]
Done.
