### ISSUE TITLE
Text RPG Cog

### ISSUE THREAD

**Issue by ShahX** [Cog-Creators/Red-DiscordBot#191]
Looking for an immersive text RPG cog that has multiple options, items, bosses, mobs, checkpoints, and all the goodies a text RPG should have.

**Comment by irdumbs** [comment]
can you give an example of a few text rpgs

**Comment by ShahX** [comment]
https://github.com/Shymain/discordRPG 

well something like this, the creator for that RPG has dropped production so its offline and incomplete, but something like that is what I was thinking.

**Comment by franc-ist** [comment]
idlerpg

**Comment by orels1** [comment]
@ShahX 
That's a big project to work with.. I'm working on smth like that, but not as deep. My main goal is to make users able to fight and recieve exp based on chat activity. I will tell you if there will be any significant progress on that

**Comment by tekulvw** [comment]
Closing as not related to core bot development. Feel free to make another issue [here](https://github.com/Twentysix26/Red-Cogs)
