### ISSUE TITLE
[V3] Cleanup bot does not clean aliases

### ISSUE THREAD

**Issue by pabloleban** [Cog-Creators/Red-DiscordBot#1920]
# Command bugs

#### Command name

`[p]cleanup bot`

#### What cog is this command from?

Cleanup

#### What were you expecting to happen?

Cleans command messages (including aliases) and messages from the bot.

#### What actually happened?

It does not delete the alias commands.

#### How can we reproduce this issue?

Create an alias:
`[p]alias add rickroll play https://www.youtube.com/watch?v=dQw4w9WgXcQ`

Call alias:
`[p]rickroll`

Call cleanup:
`[p]cleanup bot 10`

`[p]rickroll` command never gets deleted.

**Comment by Kowlin** [comment]
Can confirm that this is a bug.

**Comment by pabloleban** [comment]
Note: If the `[p]cleanup bot 10` is called with an alias like `[p]cleanbot`, this alias command is deleted.

**Comment by rguan72** [comment]
I saw that this issue had no assignees. Just to double check, do you guys want someone to work on this?

**Comment by Tobotimus** [comment]
@rguan72 Sure, no one is working on it yet as far as I know :)

**Comment by Tobotimus** [comment]
Resolved by #2213.
