### ISSUE TITLE
[V3] Better handling of delete delay / CCs

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1921]
# Feature request

- [X] API functionality

### Details

So right now, things like custom commands get handled by delete delay by us actually parsing to see if it was a CC,
What if we had a red specific event which cogs could trigger when they are finished with a message which is handled through on_message as if it were a command for things like it? This would allow vastly simplifying how delete delay is handled and also allow handling of it for any 3rd party cogs with similar behavior

something like `on_custom_command(message, cog)` and `on_custom_command_error(message, cog, error)` for signatures.

**Comment by Tobotimus** [comment]
I'm going to freeze this for the moment as I don't see it as a high priority, however I'll give my 2 cents.

I wanted to implement a system to add aliases and CC's to the bot's registered commands, which would also simplify this issue, whilst opening up opportunities to solve others (e.g. conflicting command names). I simply haven't had the time to do it (yet). I'm not treating it as a high priority at this point, and I don't mind if it's done after V3's release.

Those events you've suggested would be fine though. I'm just apprehensive to implement them if we plan on going down the route I've explained above.

**Comment by mikeshardmind** [comment]
Closing this old issue, alias and cc both actually get handled as commands now, and we'll have other means for allowing other "not quite commands" to work this way
