### ISSUE TITLE
!cog info <repo_name>

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#193]
listing description of repo.

perhaps we could ask for an optional info.json in the repo instead of just pulling the description

**Comment by tekulvw** [comment]
Should also probably add `!cog uninstall <repo> <name>` while we're at it

**Comment by irdumbs** [comment]
Also could we provide a link back to their repo from the repo info? :)

**Comment by Kowlin** [comment]
Seems like a good idea to me

**Comment by Kowlin** [comment]
Done and added.
