### ISSUE TITLE
[V3] You can only append 600 songs from a YouTube playlist

### ISSUE THREAD

**Issue by pabloleban** [Cog-Creators/Red-DiscordBot#1933]
# Command bugs

#### Command name

`[p]playlist append <playlist> <link>`

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Append all the songs from a YouTube playlist to a red playlist.

#### What actually happened?

It appends the first 600 songs of the playlist

#### How can we reproduce this issue?

1. `[p]playlist create coolsongs`
2. `[p]playlist append coolsongs https://www.youtube.com/playlist?list=PLWwAypAcFRgKAIIFqBr9oy-ZYZnixa_Fj` (That link is a YouTube playlist with 5000 songs)
3. Bot says 
> 600 tracks appended to music.
4. `[p]playlist info coolsongs`
5. Bot says

> Playlist info for music:
> Author: Me
> Custom playlist.
> 600 track(s)

**Comment by shikhir-arora** [comment]
I believe this is a Lavalink -> Lavaplayer limitation but I haven't looked that closely.

**Comment by aikaterna** [comment]
Your application.yml in your audio data folder or in the Red python package location likely has a youtubePlaylistLoadLimit: of 600. We set that to 10000 in our defaults, which is where you'll need to change it if needed, in both files.

**Comment by Kowlin** [comment]
Closing due to issue resolved.

**Comment by pabloleban** [comment]
@Kowlin 
It was not resolved.

Both files mentioned by @aikaterna are in 10000.

However this issue is not that important. Keep it closed if you like.
