### ISSUE TITLE
[V3] Completely disable a command

### ISSUE THREAD

**Issue by chnaski** [Cog-Creators/Red-DiscordBot#1938]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ x] Command
- [ ] API functionality

#### Describe your requested feature
i know it's not something assumed, but i know a few people who run much larger servers like mine who use red in conjunction with other self hosted bots on the same prefix. as the owner, i'd like to be able to completely disable a command that is the same on both bots

**Comment by Tobotimus** [comment]
Resolved by #2099. Thanks for opening this issue for us!
