### ISSUE TITLE
[V3 Trivia] Users can mention `@here` and `@everyone` through a trivia session.

### ISSUE THREAD

**Issue by FixedThink** [Cog-Creators/Red-DiscordBot#1941]
# Command bugs

#### Command name

`[p]trivia` (found it with this one, but applies to other commands as well)

#### What cog is this command from?

Trivia (found it with this one, but applies to other commands as well)

#### What were you expecting to happen?

When a user answers a question correctly, either their username is mentioned, or their displayed name with mass mentioned escaped.

#### What actually happened?

The bot pings `@here` and `@everyone` when someone plays trivia, has one of those handles in their name, and answers a question correctly.

[Here is an image showing what happens.](https://i.imgur.com/KLsjnJk.png)

#### How can we reproduce this issue?

1.  Change your nickname to something containing `@here` or `@everyone`
2. Start a trivia session (e.g. `[p]trivia 2016`)
3. Answer a question correctly.

The line in question that causes the issue for trivia: https://github.com/Cog-Creators/Red-DiscordBot/blame/V3/develop/redbot/cogs/trivia/session.py#L194

And this commit (https://github.com/Cog-Creators/Red-DiscordBot/commit/b88b5a2601f56bda985729352d24842f087a8ade) shows that there might be more commands with this issue (although most are from `admin.py`.

**Comment by mikeshardmind** [comment]
*sigh* I'm inclined to say that people should just pair this with the filter commands and auto-rename people with `@here` or `@everyone` in their names. That said, I'll look into a suitable way to fix this as this will literally impact any command that just drops a user's display name into output.

**Comment by Tobotimus** [comment]
Resolved by #1942. Thanks for opening this issue @FixedThink!
