### ISSUE TITLE
[V3 Unload/Reload] edge cases in bot.unload_extension

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1943]
### The issue

Right now, `bot.unload_extension` will break unload and reload if any cogs exist on the bot where `Cog.__module__` is `None` 

While this is definitely an edge case, I think it is at least worth considering just filtering out any case where there isn't a module, and trust that in that case, the user of created that situation can handle any required cleanup.

### The use case

Adding a cog through eval to test a specific behavior temporarily, without creating an entire module for adding through standard means.

(yes, this is an extreme edge case, but it's how I've run into it, so even a "we won't support this" is a fine answer if that's the decision)

**Comment by Tobotimus** [comment]
Resolved by #1984.
