### ISSUE TITLE
[Raspbian] Installation instructions outdated (PIP ssl error)

### ISSUE THREAD

**Issue by SavvySloth** [Cog-Creators/Red-DiscordBot#1948]
# Other bugs

#### What were you trying to do?

Installing the bot on my raspberry Pi 3B running raspbian Lite

#### What were you expecting to happen?

A successful installation procces of PIP.

#### What actually happened?

Received error the following error code 

> pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pip
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip

#### How can we reproduce this issue?

Replace these two lines:
`wget https://bootstrap.pypa.io/get-pip.py`
`sudo python3 get-pip.py`
In both the installation script and in the manual installation instruction with:
`sudo apt-get install python3-pip`

**Comment by yamikaitou** [comment]
The docs for Raspbian are already known to be outdated and https://github.com/Twentysix26/Red-Docs/pull/129 is open to get them updated. See if your issue still occurs when you follow https://bobloy.github.io/Red-Docs/red_install_raspbian/. If it still errors out, update that issue with it so nothing is missed

**Comment by SavvySloth** [comment]
@yamikaitou Tried the script from the docs you linked for raspbian stretch but without success received the same error code. But with my own fix, I get an error about discord.py not being present but I am sure I installed discord.py. I am almost certain that it can't be something with the fact that I use Raspbian Stretch Lite right?

**Comment by yamikaitou** [comment]
There is no script to run for Stretch, only Jessie. Make sure you follow the instructions for your version.

**Comment by SavvySloth** [comment]
@yamikaitou There is a script in fact here: 
`sudo python3.5 get-pip.py`
that script gives the same following error:

> pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pip
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pip/
  Could not fetch URL https://www.piwheels.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='www.piwheels.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip

**Comment by yamikaitou** [comment]
That is an issue with your specific installation. Basically, your python was built without SSL enabled. We have seen people break python on their Raspbian install by following the Jessie guide when they have Stretch. If you have nothing on the install of importance, try a reformat and then follow the new guide and see if you still encounter the issue.

**Comment by SavvySloth** [comment]
@yamikaitou Sure, I'll give it a try

**Comment by SavvySloth** [comment]
Following the tutorial with a fresh flash of Raspbian Stretch Lite worked!
https://bobloy.github.io/Red-Docs/red_install_raspbian/.

**Comment by Swat1801** [comment]
# #
