### ISSUE TITLE
[Raspbian] Crash after closing Putty 

### ISSUE THREAD

**Issue by SavvySloth** [Cog-Creators/Red-DiscordBot#1949]
# Other bugs

#### What were you trying to do?

Closing Putty and keep the but running

#### What were you expecting to happen?

I expected the bot the stay online

#### What actually happened?

The bot instantly stopped replying to command and went offline after the discord time-out period

#### How can we reproduce this issue?

I have no idea can't find any logs must be looking in the wrong place and never had such a plugin before.

**Comment by flaree** [comment]
Follow the autorestart guide on the docs to keep the bot running when closing the session.

**Comment by SavvySloth** [comment]
Stupid of my following the wrong tutorial for the auto restart
