### ISSUE TITLE
Song commands not working on RaspberryPi 3B (ffmpeg installed)

### ISSUE THREAD

**Issue by SavvySloth** [Cog-Creators/Red-DiscordBot#1951]
# Other bugs

#### What were you trying to do?

I was trying to let the bot stream music.

#### What were you expecting to happen?

I was expecting to hear music coming from the bot.

#### What actually happened?

The bot gave the following error code
`Error in command 'play'. Check your console or logs for details.`

#### How can we reproduce this issue?

Release a fix for this issue

**Comment by Twentysix26** [comment]
Please issue the following commands:
`cd red-discordbot`
`sudo python3.5 -m pip install -r requirements.txt`
and let me know if it works or any error comes up

**Comment by sleepymanakete** [comment]
Hi, I have this problem on my RPI3 as well. I've done what was said above and now I get this error.
![image](https://user-images.githubusercontent.com/30272172/43048905-a6378a64-8dac-11e8-9e5f-d1136759dd15.png)

**Comment by Twentysix26** [comment]
@sleepymanakete  Was the requirements installation successful?
I don't have a Pi, if anyone has successfully installed Red on it and wants to review the current installation guide it would be appreciated.

**Comment by sleepymanakete** [comment]
Yes, it was. I followed the Ubuntu 16.04 guide for my Pi. The Raspbian guide took me days of googling errors before I got Red to work.

**Comment by sleepymanakete** [comment]
Update: Restarting the bot worked. However, if I make the volume anything but 100, music breaks.

**Comment by aikaterna** [comment]
Hi sleepymanakete, this issue was originally opened for Red v2 and ffmpeg, but it looks like you're running Lavalink which is Red v3 and a different issue. Could you please open a different issue or visit us on the Red server? There is another user who had some issues with getting audio to work on their pi for v3 and they needed to use a custom lavalink.jar to get it to work.

**Comment by sleepymanakete** [comment]
Hi, didn't know it was for V2; I'm sorry. qwq

**Comment by rikusen0335** [comment]
I had the same issue on Raspberry Pi3 B+, but I got a solution so I'll show you!

So from lancher, do `Install requirements` and next `Install basic + audio requirements` if you have installed requirements.
When finished install, then do `Update` and next `Update Red + requirements` to fix this issue.

**Comment by Tobotimus** [comment]
Gonna close this now. If you're still having issues, we can reopen it.
