### ISSUE TITLE
[V3] Addrole command errors on hierarchy issue

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1952]
Cleaner output for hierarchy issue with [p] addrole instead of giving error.
![image](https://user-images.githubusercontent.com/10146271/43022519-788fd718-8c5f-11e8-8979-95143db2c567.png)

**Comment by Tobotimus** [comment]
Hi, thanks for opening this issue! This should be a very simple fix. Self-assigning it now.

**Comment by Tobotimus** [comment]
Resolved by #1995.
