### ISSUE TITLE
[CI] Travis builds broken due to link checking

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1957]
Oracle/Java has blocked the Travis server from connecting to their site. This is resulting in every build failing whereby Travis is blocked from accessing the Java site.

**Temporary solution:**
I've disabled the enforcement of rules on Maintainers. **Handle with care.**

**Second temporary solution:**
Link checking is currently disabled (And the flag has been re-added to the command), this will ensure that builds will be able to run without interference.

**Proposed solution:**
Allow the build matrix to ignore the status of the Docs builds.
https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail

**Comment by Tobotimus** [comment]
Resolved by #1990.
