### ISSUE TITLE
[V3 Config] set_raw() replacing all key values

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#1964]
# Other bugs

#### What were you trying to do?

I was using set_raw() to update a value of a key.

#### What were you expecting to happen?

The value to updated to the new value, and for the rest of the key values to be unaffected.

#### What actually happened?

The value got set but the rest of the key values were removed from the key.

#### How can we reproduce this issue?

Create a dict in Config that contains more than one key value, then use set_raw() to set one of the values within the key, then grab and print the new dict.

**Comment by mikeshardmind** [comment]
Just to clarify here, do you mean that the default values provided through `register_default` are not included when you use `get_raw`, update the values, `set_raw`, and then later `get_raw` again, and if not, can you give a clear example of this happening?

**Comment by ghost** [comment]
Config registered the defaults, I printed them to make sure they were there, I then used set_raw() to change two of the values in a member's dict, then printed the whole member dict again and only those two values were in it.

**Comment by Tobotimus** [comment]
Likely to be fixed by #2018 (both the year, and the issue :wink:), so I'm gonna move this over to #1987.
