### ISSUE TITLE
[V3 Sentry] Let the cog creators access their cog's errors

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1966]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [ ] API functionality
- [x] Other

#### Describe your requested feature

Sentry is now used for logging errors of most Red instances, but only some core developers have access to it (Kowlin and orels1). I think we should make it so approved cog creators can access the errors from their cogs, so they can fix the errors quickly, and also have some statistics, like the number of instances using their cogs...

This could be done with a clear versionning system for repos (instead of being based on the latest commit, why not using the Github release system or give the version number in the `info.json` file?)

**Comment by tekulvw** [comment]
We don't track errors from 3rd party code and we have no way of giving people access to *just* their errors if we did. This will not be happening. If you want sentry logging, you'll have to add it to your own code.
