### ISSUE TITLE
[v3] centralized relational DB management

### ISSUE THREAD

**Issue by calebj** [Cog-Creators/Red-DiscordBot#1969]
# Feature request

#### Select the type of feature you are requesting:
- [x] Core (Config?)

#### Describe your requested feature
This isn't a request for a relational variant of Config, though that's certainly something I would like to see. Rather, I want a standard interface to getting database URLs (for networked DBs) or paths (sqlite), as well as a unique schema name or table name prefix. The cog itself would be responsible for interacting with the database using this information.

The scope of Red core in this request would be configuration/management of database URLs and credentials, checking that the server is running and the user has the appropriate permissions, and anything else that should occur before the cog can use it. *Maybe* backup/restore, too.

EDIT: enforcing schema versioning could be done through this interface as well, as a flat integer. SQLite supports a per-database user-defined value, but it's something you have to track manually for other databases.

**Comment by mikeshardmind** [comment]
I'd like to see this be a centralized store for more than just DBs, but anything which might benefit from centralized management, including (but not limited to) things like the tokens currently stored in the streams cog, but probably more as well.

**Comment by calebj** [comment]
True. Would some sort of bot-wide config with a well-established naming convention be a better solution? For example, keys named `db.postgres` or `token.twitch` in the bot-wide registry? The schema/table names would be up to the cog, and could simply reuse the Config ID.

**Comment by mikeshardmind** [comment]
This sort of centralized key store already exists now with the [api key framework](https://docs.discord.red/en/latest/framework_apikeys.html)

It would be reasonable to assume that using `postgres` as a service name (for example) was in reference to a DB, and that one of the keys to store here might be the connection string.
