### ISSUE TITLE
[V3 i18n] Guild-overides for localisations

### ISSUE THREAD

**Issue by TurnrDev** [Cog-Creators/Red-DiscordBot#1970]
It would be nice if I could change bot localisations per-server and per-user

*Edit by Tobotimus:* And per-channel? ;)

**Comment by Tobotimus** [comment]
Sorry I've already frozen this without a response.

This is really hard. It's not even really possible. This requires the translator to know which guild (or user, just guild herein) a string is being sent to, which is impossible unless a guild can be passed to the `_()` function. This is simply unrealistic. Firstly it defeats the purpose of the `_()` function being as visually unnoticeable as possible, secondly we simply don't have access to a guild object most of the time when `_()` is called. Thirdly, pygettext (a script we use to extract the strings, which is maintained by the Python core devs) would have to be modified to extract only the first argument from a `_()` call.

I can understand it's a very desirable feature. Unfortunately all I can recommend is running different bots for each locale.

**Comment by TurnrDev** [comment]
That's fair. I had a feeling it wouldn't be possible. Thank you for spending the time to get back to me :+1:

**Comment by Tobotimus** [comment]
@JayTurnr You might actually be in luck. Using [PEP 567](https://www.python.org/dev/peps/pep-0567) cvars, this is more possible than I previously thought :grin: However implementing it is going to be a lot of work, I'm not going to include this in 3.0.0's release milestone, but will reopen the issue and freeze it as a reminder that it should be done at some point.

**Comment by TurnrDev** [comment]
How's this going? I'd love to help in any way I can ☺️

**Comment by Drapersniper** [comment]
PR #3896 has been oppened to handle it.
