### ISSUE TITLE
[V3 Translator] Docstrings and f-strings not translated

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1977]
# Other bugs

#### What were you trying to do?

Use the i18n program on my cog and generate a valid `messages.pot` files

#### What were you expecting to happen?

Have a `message.pot` files which contains docstrings and all registered strings.

#### What actually happened?

- Docstrings were not in the `messages.pot` file
- Any message that had an f-string was ignored

```
laggrons-macbook-pro:~ laggron$ python3 Downloads/Python-3.6.6/Tools/i18n/pygettext.py -v -p Documents/Laggrons-Dumb-Cogs/say/locales/ Documents/Laggrons-Dumb-Cogs/say/*.py
Working on Documents/Laggrons-Dumb-Cogs/say/__init__.py
Working on Documents/Laggrons-Dumb-Cogs/say/say.py
*** Documents/Laggrons-Dumb-Cogs/say/say.py:160: Seen unexpected token "f"I am not allowed to send messages in {channel.mention}""
*** Documents/Laggrons-Dumb-Cogs/say/say.py:164: Seen unexpected token "f"I am not allowed to upload files in {channel.mention}""
*** Documents/Laggrons-Dumb-Cogs/say/say.py:234: Seen unexpected token "f"I will start sending you messages from {channel.mention}.\n""
*** Documents/Laggrons-Dumb-Cogs/say/say.py:296: Seen unexpected token "f"Version: {self.__version__}\n""
Working on Documents/Laggrons-Dumb-Cogs/say/sentry.py
```

#### How can we reproduce this issue?

Use the command `pygettext3 -v -p locales say.py` on my cog.

### Files

The cog: https://gist.github.com/retke/7e6f652a358975c29725970dc3ce07f5

The `messages.pot` file: https://gist.github.com/retke/ed4b7fcccba857afea9ac725f3a82565

**Comment by mikeshardmind** [comment]
f-strings don't work with pygettext, and cannot be automatically translated. (This isn't behavior which is going to change either due to how they work)

Doc strings you need to pass the correct args for (you can view how core red generates these or `pygettext -h`) for details there

**Comment by Tobotimus** [comment]
@mikeshardmind is correct, and I'm going to close this.

Clearly this is not red related, and the issue could be quickly resolved by simply asking in the discord server.
