### ISSUE TITLE
[V3 ModLog] Error in command "case"

### ISSUE THREAD

**Issue by sleepymanakete** [Cog-Creators/Red-DiscordBot#1978]
# Command bugs

#### Command name

[p]case

#### What cog is this command from?

ModLog

#### What were you expecting to happen?

To show me information about a case.

#### What actually happened?
I get this error:
![image](https://user-images.githubusercontent.com/30272172/43678766-a4a40388-97d6-11e8-90c7-d48ae2c54239.png)

#### How can we reproduce this issue?

1. Have a modlog with cases.
2. Do [p]case

**Comment by Tobotimus** [comment]
Hi, thanks for submitting this issue! Looks like a simple fix.

**Comment by Tobotimus** [comment]
Resolved by #1981
