### ISSUE TITLE
[V3/Streams] streamalert list command is missing a doc string.

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Red-DiscordBot#1997]
#### What were you trying to do?
call `[p]help` on streamalert list`

#### What were you expecting to happen?
Help message from the doc string would be displayed.

#### What actually happened?

No help message information was displayed, because the doc string was missing.

#### How can we reproduce this issue?
Call help on `[p]streamalert list` or see the missing short doc on `[p]help streamalert`

**Comment by Tobotimus** [comment]
Resolved by #2001.
