### ISSUE TITLE
[V3 Streams] Misleading error message

### ISSUE THREAD

**Issue by Twentysix26** [Cog-Creators/Red-DiscordBot#2003]
# Command bugs

#### Command name

`[p]streamalert twitch channel #name_of_a_discord_channel`

#### What cog is this command from?

Streams

#### What were you expecting to happen?

The bot telling me that I screwed up

#### What actually happened?

The bot told me that my Twitch token is invalid

#### How can we reproduce this issue?

1) Set a valid Twitch client ID
2) Issue `[p]streamalert twitch channel #name_of_a_discord_channel`

**Comment by Tobotimus** [comment]
Resolved by #2048.
