### ISSUE TITLE
cant find how to setup auto role

### ISSUE THREAD

**Issue by jaguard0** [Cog-Creators/Red-DiscordBot#2010]
# Command bugs

#### Command name

!help
#### What cog is this command from?

unkown

#### What were you expecting to happen?

i expected to see what i need to use for the autorole command but cant find anything related to it.

#### What actually happened?

it didnt show up at all

#### How can we reproduce this issue?

type !help i guess

**Comment by calebj** [comment]
Autorole is a third party cog. You need to install and load the cog before it'll show in help.

Edit: put the wrong name.

**Comment by Tobotimus** [comment]
Please use #support or #v3-support (depending on your version) in our discord server for further questions
