### ISSUE TITLE
list whitelisted / blacklisted users

### ISSUE THREAD

**Issue by irdumbs** [Cog-Creators/Red-DiscordBot#202]
for easier management

**Comment by ddday** [comment]
``@whitelist.command(name="show", pass_context=True)
    async def _whitelist_show(self, ctx):
        """Shows whitelisted users"""
        WhitelistedUsers = ''
        unknown = []
        WhiteList = fileIO("data/mod/whitelist.json", "load")
        if WhiteList == []:
            await self.bot.say("No one is whitelisted.")
        else:
            for i in WhiteList:
                member = str(discord.utils.get(self.bot.get_all_members(), id=str(i)))
                if member is not None: 
                    WhitelistedUsers += member + ', '
                elif member is None: 
                    unknown.append(i)
            WhitelistedUsers = WhitelistedUsers[:-2]
            await self.bot.say("The following users are whitelisted: " + WhitelistedUsers)` are whitelisted: " + WhitelistedUsers)``

`@blacklist.command(name="show", pass_context=True)
    async def _blacklist_show(self, ctx):
        """Shows current blacklisted users"""
        blckUsers = ''
        unknown = []
        blckList = fileIO("data/mod/blacklist.json", "load")
        if blckList == []:
            await self.bot.say("There are no blacklisted people.")
        else:
            for i in blckList:
                member = str(discord.utils.get(self.bot.get_all_members(), id=str(i)))
                if member is not None:
                    blckUsers += member + ', '
                elif member is None:
                    unknown.append(i)
            blckUsers = blckUsers[:-2] 
            await self.bot.say("The following users are blacklisted: " + blckUsers)
        if unknown != []: 
            await self.bot.say("There are users on the blacklist that could not be found on the servers. Would you like to delete them?")
            response = await self.bot.wait_for_message(author=ctx.message.author)
            response = response.content.lower().strip()
            if response == "yes" or response == "y":
                for i in unknown:
                    self.blacklist_list.remove(i)
                fileIO("data/mod/blacklist.json", "save", self.blacklist_list)
                await self.bot.say("Users have been removed from blacklist.")
            else:
                await self.bot.say("Alright, I'll leave them be.")`

**Comment by tekulvw** [comment]
Closing because functionality is in PR
