### ISSUE TITLE
[V3 Warnings] Warn doesn't create a modlog case

### ISSUE THREAD

**Issue by Mystard** [Cog-Creators/Red-DiscordBot#2022]
# Command bugs

#### Command name

warn

#### What cog is this command from?

warnings

#### What were you expecting to happen?

User to be warned via DM and a modlog case to be created.

#### What actually happened?

User gets warned via DMs but no modlog case is created.

#### How can we reproduce this issue?

1. Warn a user with `[p]warn <user> <reason>`
2. DM gets sent, no modlog case created

- - - - - - -

Running B19

**Comment by Jackenmen** [comment]
This can be closed as it was implemented here #2471
