### ISSUE TITLE
Installation of Requirements Failure: fatal: unable to connect to github.com

### ISSUE THREAD

**Issue by ashneverdawn** [Cog-Creators/Red-DiscordBot#2032]
# Command bugs

#### Command name

1. Install basic + audio requirements (recommended)

#### What cog is this command from?

Basic installation

#### What were you expecting to happen?

Successful installation of requirements.

#### What actually happened?

Installation of requirements failed.
Here is the console output: 

```
Collecting pip (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Collecting discord.py[voice] from git+git://github.com/Rapptz/discord.py.git#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning git://github.com/Rapptz/discord.py.git to /tmp/pip-install-ixo3rw1i/discord.py
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection timed out
github.com[1: 192.30.253.112]: errno=Connection timed out

Command "git clone -q git://github.com/Rapptz/discord.py.git /tmp/pip-install-ixo3rw1i/discord.py" failed with error code 128 in None

An error occurred and the requirements setup might not be completed. Consult the docs.

Press enter to continue.
```

#### How can we reproduce this issue?

1. Start with a fresh installation of Ubuntu Server 16.04 LTS (Xenial Xerus) on your server
2. Log in to your server as the root user 

> ssh root@server_ip_address

3. Create a new sudo user (replace username with the username you want)

> adduser username

> usermod -aG sudo username

4. Switch to the new user

> su - username

5. Follow exact steps outlined in the documentation for intallation:
https://twentysix26.github.io/Red-Docs/red_install_ubuntu/#updating-the-bot-requirements

6. Failure happens at "Updating the bot requirements" step

**Comment by Tobotimus** [comment]
@noxyal This looks like a connection issue between your server and GitHub. Try `ping github.com` from your server. If it shows your connection is OK, try installing again and if that fails, get back to us :)

**Comment by ashneverdawn** [comment]
@Tobotimus 
Thanks. I tried ping github.com, and there aren't any connection issues there. Besides, the previous installation step of cloning the bot worked flawlessly. I've setup another fresh server and installed again, but same issue.

I do notice something odd with the command that failed though:

`Command "git clone -q git://github.com/Rapptz/discord.py.git /tmp/pip-install-ixo3rw1i/discord.py" failed with error code 128 in None`

Shouldn't this be `https://` rather than `git://` ?

**Comment by Tobotimus** [comment]
@noxyal `git://` specifies the Git protocol for contacting remote URLs, it's unusual that it wouldn't work with git installed, especially on a distro like Xenial. However you can try this command to force git to use the HTTPS protocol whenever it sees a Git protocol on a GitHub URL:
```
git config --global url."https://github.com".insteadOf git://github.com
```

Edit:
I should have thought a bit harder - it isn't really unusual that this wouldn't work, due to firewalls. I'm guessing you have one on your system? The Git protocol requires access through port 9418.

**Comment by ashneverdawn** [comment]
I ended up going into the requirements.txt file and changing line 2 from
`git+git://github.com/Rapptz/discord.py.git#egg=discord.py[voice]`
to
`git+https://github.com/Rapptz/discord.py.git#egg=discord.py[voice]`
and it worked like a charm.

**Comment by Tobotimus** [comment]
No worries, it's likely to be the firewall issue I mentioned in my last comment. Closing this now that it's resolved.

**Comment by Svestis** [comment]
> I ended up going into the requirements.txt file and changing line 2 from `git+git://github.com/Rapptz/discord.py.git#egg=discord.py[voice]` to `git+https://github.com/Rapptz/discord.py.git#egg=discord.py[voice]` and it worked like a charm.

I was desperately trying to modify the nav bar (the home page reordering was working but not the nav bar) and that was an easy plug and play. Hopefully this will be integrated in the package, but thanks!
