### ISSUE TITLE
[V3] Be able to have global settings and data (not instance-specific)

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#2039]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Currently, the 3rd party cogs are always specific and depending to one single instance. The data is stored in the instance's files and cannot "interact" with other instances. An option to get a global data path would be great and reduce disk usage/memory usage/CPU usage for specific functions of some cogs.

Currently, `redbot.core.data_manager.cog_data_path()` returns something like this: `InstanceName/cogs/YourCog/`. Adding another function like `global_data_path` which would lead to `/usr/local/share/Red-DiscordBot/YourCog/` (on Linux) would be great for hosting something that use a lot of disk usage for example.

As an example, with that feature, the Audio cog could download Lavalink.jar in that global folder (I host 4 bots, only one Lavalink server but still 4 identic files) and make shared Lavalink server easier.

**Comment by mikeshardmind** [comment]
I think this is counterintuitive and goes against the idea of having separate instances with a user-chosen data path. Additionally, you can set your instances to use an external lavalink server and have none of the 4 own it, so that doesn't exactly speak to this being needed.

**Comment by Tobotimus** [comment]
I've slept on this and I think @retke has a point - some relatively large files which are only installation-dependent, not instance-dependent, are copied into the instance's data directory. However, I don't think the data manager is the place to deal with this, as the data manager is *specifically* for getting data and metadata for the current instance. Moreover, this use of the data manager could cause some concerning issues when the following situation occurs:
 - Two instances are running on the same system
 - Both instances have a 3rd party cog installed which utilises global data
 - The 3rd party cog in question is updated on one instance but not the other, possibly causing the cogs to conflict with each other on their treatment of the global data

It's important that different revisions of any cog can guarantee compatibility with any bundled data. This is why bundled data is *always* instance-dependent, along with any cog installations.

Now, as for the Lavalink.jar being copied, I think it is a different issue, and it still needs discussion. Personally, I think `red-lavalink` could bundle the Lavalink.jar, but I might be overseeing something in that design.

**Comment by Tobotimus** [comment]
Should probably open a new issue for the Lavalink.jar being copied, I will decide on a solution in the meantime.
