### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by despaceeto** [Cog-Creators/Red-DiscordBot#2040]
# Other bugs

#### What were you trying to do?
I was trying to run red bot

#### What were you expecting to happen?

for it to ask for a discord token
#### What actually happened?

Syntax error

#### How can we reproduce this issue?
1. download python latest version
2. do what you normally do with red bot
3 then press run red bot 
 outcomes invalid syntax: syntax error

**Comment by Tobotimus** [comment]
Hi, you're running Red with an incompatible python version. The compatibility is clearly stated in the [docs](https://twentysix26.github.io/Red-Docs/), just follow the guide for your operating system. Please ask further questions in the #support channel of our discord server: https://discord.gg/red
