### ISSUE TITLE
clear command erorr

### ISSUE THREAD

**Issue by turkhd** [Cog-Creators/Red-DiscordBot#2043]
# Command bugs

Command not working
#### Command name
chat clear

#### What cog is this command from?
conversation chat to delete posts

selftbot chat clear
#### What were you expecting to happen?
correction

I understood, sorry
#### What actually happened?
error giving

command erorr control panels look
#### How can we reproduce this issue?
rewrite pls

I understood, sorry

**Comment by Kowlin** [comment]
Closing this,

Red has no command named ``chat clear``,
We do not support selfbots, as they are against Discord's ToS

If you are opening a new issue, please ensure that its a core Red command. And we don't support selfbots anywhere. This includes this Github organization and the Discord server.

**Comment by turkhd** [comment]
Error in command 'cleanup messages'. Check your console or logs for details.

**Comment by turkhd** [comment]
Official server: https://discord.gg/red
Make sure to keep your bot updated. Select the 'Update' option from the launcher.
[23/08/2018 17:20] ERROR red on_command_error 369: Exception in command 'cleanup messages'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\Red-DiscordBot\cogs\mod.py", line 857, in messages
    async for message in self.bot.logs_from(channel, limit=number+1):
TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: generator

consol error

**Comment by Tobotimus** [comment]
@feyzullahduman147 You're using a modified version of the mod cog. Please don't modify cogs if you expect us to resolve issues.

**Comment by Twentysix26** [comment]
OP is using v2.

**Comment by turkhd** [comment]
new I downloaded

**Comment by Tobotimus** [comment]
You're right @Twentysix26, that's my bad, for some reason I didn't remember an `async for` line in the V2 mod cog. I stand corrected!

**Comment by Twentysix26** [comment]
@feyzullahduman147 Are you using a bot account for Red? You mentioned "selfbot" in your post.

**Comment by turkhd** [comment]
selfbot hm no account ?

**Comment by turkhd** [comment]
Red-DiscordBot my account no account record I have need I did not understand sorry

**Comment by Twentysix26** [comment]
Which version of Python are you using?

**Comment by turkhd** [comment]
Python 3.7.0 Twentysix26

**Comment by Twentysix26** [comment]
Try using [Python 3.5.4](https://www.python.org/downloads/release/python-354/) instead. Uninstall 3.7.0 first if you have no other use for it.

**Comment by turkhd** [comment]
immediately experience
