### ISSUE TITLE
mod cog error

### ISSUE THREAD

**Issue by turkhd** [Cog-Creators/Red-DiscordBot#2056]
# Other bugs

mod cog error
#### What were you trying to do?
cog setup

cogs mod setup erorr
#### What were you expecting to happen?
fix

#### What actually happened?
error

https://pastebin.com/yb241gyS
http://www.imgim.com/2747inciq7651858.png

Failed to load package mod. Check your console or logs for details.
#### How can we reproduce this issue?
you corrected

**Comment by turkhd** [comment]
@Tobotimus 
 help me pls

**Comment by Tobotimus** [comment]
@feyzullahduman147 Try reinstalling and restarting the bot

**Comment by Tobotimus** [comment]
@feyzullahduman147 For further questions please use the #v3-support channel of our discord server.
