### ISSUE TITLE
issues with install the discord bot

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#2057]
# Other bugs

#### What were you expecting to happen?
was inatall the bot but get this issue 

#### How can we reproduce this issue?
https://hastebin.com/uguzexiyot.sql

**Comment by Twentysix26** [comment]
Uninstall Python 3.6/3.7 and install Python 3.5 as told (and linked) in the installation guide.

**Comment by ghost** [comment]
Okay

**Comment by ghost** [comment]
@Twentysix26 Okay now it work now Thank you
