### ISSUE TITLE
swearing protection

### ISSUE THREAD

**Issue by turkhd** [Cog-Creators/Red-DiscordBot#2058]
# Feature request

antilink
antiswearing
antiadvertisement

#### Select the type of feature you are requesting:
antiswearing
antiadvertisement

- [ x] Cog
- [x ] Command
- [ ] API functionality

#### Describe your requested feature
on the server swearing you do not link sharing no special swearing config get

**Comment by flaree** [comment]
You can request custom cogs here: [https://cogboard.red](url)

**Comment by Tobotimus** [comment]
You can check out the filter cog for anti-swearing, antilink is already a 3rd party cog and it will stay that way, see #1398 for a list of 3rd party cogs.
