### ISSUE TITLE
autorole erorr

### ISSUE THREAD

**Issue by turkhd** [Cog-Creators/Red-DiscordBot#2070]
# Other bugs

#### What were you trying to do?
autorole setup

#### What were you expecting to happen?
fix

#### What actually happened?
erorr

https://pastebin.com/pbt2svh4
Error in command 'autorole add'. Check your console or logs for details.
#### How can we reproduce this issue?
you corrected

**Comment by laggron42** [comment]
This issue does not concern core Red. For this kind of problems, please post an issue on the cog's repo or in the [cog support discord server](https://discord.gg/GET4DVk).

**Comment by Tobotimus** [comment]
@retke is correct, closing.

**Comment by turkhd** [comment]
problem solved already @Tobotimus @retke
