### ISSUE TITLE
Pagify error...?

### ISSUE THREAD

**Issue by ParzivalWolfram** [Cog-Creators/Red-DiscordBot#2073]
# Command bugs

#### Command name

eval_os

#### What cog is this command from?

My own

#### What were you expecting to happen?

This command should execute commands on the host machine rather than in the bot itself. Owner only.

#### What actually happened?
```
Exception in command 'eval_os'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pi/Red-DiscordBot/cogs/owner.py", line 931, in eval_os
    for page in pagify(bytes(command_out)):
  File "/home/pi/Red-DiscordBot/cogs/utils/chat_formatting.py", line 39, in pagify
    num_mentions = text.count("@​here") + text.count("@​everyone")
TypeError: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: a bytes-like object is required, not 'str'
```

As seen in this traceback, this is an internal error in pagify, not my cog. 

Code:
@commands.command(pass_context=True)
@checks.is_owner()
```
async def eval_os(self, ctx, command=""):
	"""Runs a command on the system instead of in the bot."""
	message = ctx.message
	from subprocess import Popen, PIPE
	p = Popen([str(command)], stdout=PIPE, stderr=PIPE, stdin=PIPE)
	command_out, command_err = p.communicate()
	p.kill()
	destination = ctx.message.author
	await self.bot.send_message(destination, "stdout:")
	for page in pagify(bytes(command_out)):
		await self.bot.send_message(destination, box(page))
	await self.bot.send_message(destination, "stderr:")
	for page in pagify(bytes(command_err)):
		await self.bot.send_message(destination, box(page))
	await self.bot.send_message(destination, str("Exit code was " + str(p.returncode())))
```

#### How can we reproduce this issue?

Invoke this code in a command.

**Comment by Zephyrkul** [comment]
Pagify expects strings, not bytes. Since it's type-hinted to accept strings (`def pagify(text: str, ...`), it's assumed you'll fill that contract, so the error is on your end, not on pagify's.

**Comment by Tobotimus** [comment]
@zephyrkul is correct, pagify requires `str`. IIRC `Process.communicate` returns two `bytes` objects, so you will need to decode them before passing to pagify.

**Comment by ParzivalWolfram** [comment]
I would like to point out that the error says it EXPECTS a byte object over a string, not the other way around.

**Comment by Tobotimus** [comment]
@ParzivalWolfram I can see that, that error is coming from a subroutine in Python's standard library, not from the pagify function. Functions in python tend not to do type checks before continuing as that would add a tonne of verbosity. It's simply expected users will read documentation / type hints

**Comment by ParzivalWolfram** [comment]
```
Exception in command 'eval_os'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pi/Red-DiscordBot/cogs/owner.py", line 936, in eval_os
    await self.bot.send_message(destination, str("Exit code was " + str(p.returncode())))
TypeError: 'int' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'int' object is not callable
```
also, this. (byte objects are now strings)

I'm clearly not calling an int, so wtf?

**Comment by Tobotimus** [comment]
@ParzivalWolfram
```
  File "/home/pi/Red-DiscordBot/cogs/owner.py", line 936, in eval_os
    await self.bot.send_message(destination, str("Exit code was " + str(p.returncode())))
TypeError: 'int' object is not callable
```

That's your own code

p.returncode is an int, and you are in fact calling it.

**Comment by ParzivalWolfram** [comment]
@Tobotimus Yup. I'm not calling an int, so why is this happening? As I'm still using Red's functions and such, i'm still here.

**Comment by ParzivalWolfram** [comment]
actually, nvm, i'ma fucking idiot.

**Comment by Tobotimus** [comment]
p.returncode is actually part of the standard library, perhaps you should open an issue there? :P

Please either come to #coding or spend longer debugging your code. I know it's frustrating but blaming the tools should be your last resort.

**Comment by ParzivalWolfram** [comment]
The original issue was put here as I erroneously thought it was an issue in Red's code, not mine. While inaccurate, that was still the reason...
