### ISSUE TITLE
[V3 Maintaining] Internal documentation

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2074]
I feel like we're at the point where we have a lot of moving parts inside the bot. This isn't a bad thing, but as discord.py is not avoiding breaking changes yet, it may be a good idea to document which pieces of the bot/cogs rely on which portions of discord.py somewhere centralized, either in a wiki, or some other form.

**Comment by Tobotimus** [comment]
It's a sound proposal, unfortunately I personally don't have much time for it right now, will freeze it until stuff frees up.

**Comment by mikeshardmind** [comment]
Better suited for discussion on the proposals repo or in the monthly meetings in discord.
