### ISSUE TITLE
How to get entire command?

### ISSUE THREAD

**Issue by ParzivalWolfram** [Cog-Creators/Red-DiscordBot#2075]
I'm trying to make a cog, but people can enter commands with spaces in the keywords, so I'd like to take a command and have the entire remainder of the message put into a variable instead of just what's defined in the function. For example:

If someone sends the command `[p]search Generic String`, I need the variables set up as the following:
```
command == "Generic String"
```
however, when only defining a function with one variable for input, I end up with 
```
command == "Generic"
```
and the rest is dropped entirely.

How can I prevent Red from dropping the rest of the message when passing it to my function?

**Comment by Tobotimus** [comment]
Hi @ParzivalWolfram, hopefully [this](https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html#keyword-only-arguments) will help you. These docs are for the discord.py rewrite (V3 Red), but this section applies to async/V2 as well.

For questions like this, we prefer if you direct them at the #coding channel of our discord server: https://discord.gg/red, or the discord.py server: https://discord.gg/r3sSKJJ, especially considering this is more of a discord.py question than a Red one.
