### ISSUE TITLE
[V3] Warnings customreasons

### ISSUE THREAD

**Issue by coltoutram** [Cog-Creators/Red-DiscordBot#2078]
# Command Bugs

#### What were you trying to do?

Warn someone with a custom reason.

#### What were you expecting to happen?

After setting allowcustomreasons to true, warn someone with a custom reason.

#### What actually happened?

It said "That is not a registered reason!"

#### How can we reproduce this issue?

Load warnings, warningset allowcustomreasons true, warn someone with a custom reason.

**Comment by Tobotimus** [comment]
Duplicate of #2014
