### ISSUE TITLE
Bot doesn't play any audio

### ISSUE THREAD

**Issue by kokarn** [Cog-Creators/Red-DiscordBot#208]
It worked for a while but nowdays it doesn't play anything. 
Everything that get's thrown at it makes the bot join but nothing gets played.

If i check the log, after ~30s this pops up.

Both `git pull` and `sudo pip3 install --upgrade git+https://github.com/Rapptz/discord.py@async` ran and updated.

Anything I can do to help with the debug?

``` python
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 245, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 65, in on_message
    await bot.process_commands(message)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 608, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 380, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ubuntu/Red-DiscordBot/cogs/audio.py", line 75, in play
    if await self.check_voice(msg.author, msg):
  File "/home/ubuntu/Red-DiscordBot/cogs/audio.py", line 701, in check_voice
    await self.bot.join_voice_channel(author.voice_channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2396, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
```

**Comment by franc-ist** [comment]
Try changing the server location to somewhere closer to where the bot is located. It seems to be timing out before it can connect. Alternatively, get better internet. XD

**Comment by kokarn** [comment]
Hmm, that's interesting actually. I set it up on AWS but might switch to an european location then.

**Comment by kokarn** [comment]
Update, it's in Frankfurt and the Discord server is european as well

**Comment by irdumbs** [comment]
if you are logged into your bot's account via a discord app/browser, please close it.
You should not be logged into your bot's account.

Make sure you're also only running one instance of the bot and that it has permissions to join the voice channel.

If that doesn't help, shutdown your bot for ~20 minutes. If your bot still shows as offline a few minutes in, it may be the server not updating, possibly because your bot got rate limited?

Why don't you come into our discord server so we can help you troubleshoot.

**Comment by RealFriesi** [comment]
I have exactly the same problem. Have installed the bot today and it worked very well. After 2 hours I went back online and the bot has doesen´t play anything. There are no local files and YouTube videos played but he enters the voice channel.

**Comment by RealFriesi** [comment]
After the change of Discord server everything works again. Possibly an error of Discort Bot-Api?

**Comment by Kowlin** [comment]
the error is related to Discord.Py not being able to connect to a voice server, this is beyond our control.

**Comment by irdumbs** [comment]
@Friesinator come on into our discord server and we can more thoroughly help you troubleshoot

**Comment by OhlookitsSaad** [comment]
The bot does not even joins VC for me .

**Comment by tekulvw** [comment]
Please join the support server if you have any audio issues.
