### ISSUE TITLE
[V3 Audio] Allow bots to play youtube playlists

### ISSUE THREAD

**Issue by idcw0tdisism8** [Cog-Creators/Red-DiscordBot#2085]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Hello everyone,

I have a suggestion on the V3 Audio, and today I'll be talking to you about it.

So, this will be in the audio section of course, and the name of the command will be known as ytlist or ytplaylist.

The intended functionality for the command will be so users can play their playlists from youtube.

(If this was already suggested, I am sorry. This just popped up in my head.)

**Comment by zephyrkul** [comment]
The [p]play command already supports YouTube playlists in V3, and there's a [p]playlist command for making your own playlists in Red.

**Comment by idcw0tdisism8** [comment]
Ah, sorry. I just thought it'd be not there, yet.
