### ISSUE TITLE
Red wont launch for me

### ISSUE THREAD

**Issue by Toxici11i** [Cog-Creators/Red-DiscordBot#2090]
# Other bugs

#### What were you trying to do?
Trying to launch red

#### What were you expecting to happen?
For it to launch
#### What actually happened?
Spat out a fat error
----------------
Starting Red...
Traceback (most recent call last):
  File "red.py", line 12, in <module>
    from discord.ext import commands
  File "lib\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "lib\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "lib\discord\voice_client.py", line 43, in <module>
    import websockets
  File "lib\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "lib\websockets\client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "lib\websockets\protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "lib\websockets\compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax
Red has been terminated. Exit code: 1

#### How can we reproduce this issue?

Step 1)Cloning red with git
Step 2)Running it after installing dependencies
Step 3)Done

**Comment by Toxici11i** [comment]
New issue
----------
Re-ran the requirement install with audio support - came back with
-------------
Installing collected packages: pip, chardet, multidict, async-timeout, aiohttp, websockets, six, pycparser, cffi, PyNaCl, discord.py, youtube-dl, urllib3, certifi, idna, requests, imgurpython
  Running setup.py install for multidict ... done
  Running setup.py install for aiohttp ... done
  Running setup.py install for websockets ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for PyNaCl ... error
    Complete output from command C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-cfdjtv0a\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-1rduaq9n\install-record.txt --single-version-externally-managed --compile --home=C:\Users\user\AppData\Local\Temp\pip-target-rfa4tj5q:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\nacl
    copying src\nacl\encoding.py -> build\lib.win32-3.7\nacl
    copying src\nacl\exceptions.py -> build\lib.win32-3.7\nacl
    copying src\nacl\hash.py -> build\lib.win32-3.7\nacl
    copying src\nacl\public.py -> build\lib.win32-3.7\nacl
    copying src\nacl\secret.py -> build\lib.win32-3.7\nacl
    copying src\nacl\signing.py -> build\lib.win32-3.7\nacl
    copying src\nacl\utils.py -> build\lib.win32-3.7\nacl
    copying src\nacl\__init__.py -> build\lib.win32-3.7\nacl
    creating build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_box.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_hash.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_sign.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\randombytes.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\sodium_core.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\__init__.py -> build\lib.win32-3.7\nacl\bindings
    running build_clib
    error: [WinError 193] %1 is not a valid Win32 application
--------
At the end

**Comment by Twentysix26** [comment]
As the guide explains in bold letters Python 3.5.* is needed. Make sure you uninstall the current version you have first.
