### ISSUE TITLE
[V3 Mod] Timed mute

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#2103]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

An included timed mute for the mod cog is requested a lot currently, and would be a nice feature. I'm thinking about something like Dyno for the arguments, and would give something like this:

```
[p]mute guild @someone 30m my random reason
```

`30m` = 30 minutes
`2h` = 2 hours
`4d` = 4 days
...

Please give your feedback about this to know what would be the best, I'm planning to code this for the next beta (if there is one before RC)

**Comment by mikeshardmind** [comment]
If you'd like to do this, that would actually be wonderful. There was some discussion in discord about this earlier today actually, and the details for what was needed for this could be summed up as:

- All logic abstracted out of commands; Commands should just call the correct functions and schedule a corresponding the corresponding unmute.
- Unmute should be handled properly even in the case of bot uptime interruptions,
- Time handling should feel natural. (This can include added dependencies within reason, such as `humanize`)
- Logic should be easily modifiable to allow using a mute role at a later date. This should be accomplished naturally by breaking the logic out of the commands anyway.

If this is beyond what you would want to do, it will likely still be ready before RC1 as there are others interested in making this happen.

**Comment by Jamesp1989SL** [comment]
Why not go a step further and allow any command to be ran on a delay. Although maybe that wouldn't  warrant being core

**Comment by laggron42** [comment]
I'm having some difficulties with the libraries. I cannot find a good one for what I need:
- `datetime.datetime` have the good arguments and operations, but represents a date (year cannot be 0)
- `datetime.time` cannot be more than a day
- `datetime.timedelta` cannot represent years, months, hours, minuts

If you know any good libraries where you can set separately every unit, I'd like to know.

**Comment by mikeshardmind** [comment]
Not sure an extra lib is needed, it was just an option. Here's a recipe from some old code that should work fine.

```py
import re
from datetime import timedelta

TIME_RE = re.compile(r"((?P<days>\d+?)\s?(d(ays?)?))?\s?((?P<hours>\d+?)\s?(hours?|hrs|hr?))?\s?((?P<minutes>\d+?)\s?(minutes?|mins?|m))?\s?((?P<seconds>\d+?)\s?(seconds?|secs?|s))?\s?", re.I)

def parse_timedelta(some_input: str) -> timedelta:
    matches = TIME_RE.match(some_input)
    params = {k: int(v) for k, v in matches.groupdict().items() if None not in (k, v)}
    return timedelta(**params)
```

This could be made more robust with something such as pyparsing, but is likely overkill here.

**Comment by mikeshardmind** [comment]
replaced by #3270
