### ISSUE TITLE
[V3] Escape markdown properly on Custom Command list

### ISSUE THREAD

**Issue by skeith** [Cog-Creators/Red-DiscordBot#2104]
# Command bugs

Yes I found bug

#### Command name

`cc list`

#### What cog is this command from?

customcom

#### What were you expecting to happen?

It list the cc beautifully 

#### What actually happened?

![image](https://user-images.githubusercontent.com/340284/45192128-1cdf8e00-b279-11e8-8897-00b07ef90135.png)

#### How can we reproduce this issue?

Just have several custom commands with code block / inline code block markdown

**Comment by Tobotimus** [comment]
Not exactly a duplicate but resolving #1841 would fix this, so I'm gonna close this in favour of that. Thanks for reporting though

**Comment by Tobotimus** [comment]
Turns out #1841 was not a way of fixing this. Re-opening.

**Comment by Tobotimus** [comment]
Resolved by #2215.
