### ISSUE TITLE
[V3 Cog] Rndstatus (Edited)

### ISSUE THREAD

**Issue by Jqd0n** [Cog-Creators/Red-DiscordBot#2107]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

 So rndstatus botstats on v3, of course. But with a twist, if @aikaterna or someone can possibly do this. Make it so you can have a rndstatus text and everything else. For example:

With my friend. | [p]help | 4826 users | 497162 servers

Just a cog edit request, I think it'd be nice so what you have set can work on the botstats anywhere you want it. (Separate command in the v3 cog or a new cog, idc personally.)

**Comment by Jqd0n** [comment]
Upvotes appreciated.

**Comment by laggron42** [comment]
This issue does not concern the core bot. Please move this to the [cog board](https://cogboard.red) or to someone's 3rd party repository.
