### ISSUE TITLE
Addcom not working or responding at all. Is this happening to anyone else or did I set up the bot incorrectly?

### ISSUE THREAD

**Issue by foreverballoon** [Cog-Creators/Red-DiscordBot#2109]
# Command bugs

#### Command name

!addcom

#### What cog is this command from?

Commands

#### What were you expecting to happen?

Being able to add some sort of custom command that would show the command author's role, or some other variable like with {discord.Role}.

#### What actually happened?

Using !addcom does absolutely nothing. Searching for a few hours on why this isn't working didn't pull up anything. Using help brought me this message:

> !command
> 
> Disables/enables commands
> 
> With no subcommands returns the disabled commands list
> 
> Commands:
>   disable Disables commands/subcommands
>   enable  Enables commands/subcommands
> 
> Type !command command for more info on a command.
> You can also type !command category for more info on a category.

However, enabling and disabling the commands, copying and pasting the example commands from the redbot red_guide_command_args list also does nothing. The bot will not respond to anything involving !addcom, though it does respond to !alias just fine. Alias will not allow me to call upon a user's role or anything in depth, so it isn't what I'm looking for. Is this a bug, a server error, or am I missing something? I've read several times over all of the instructions and help commands and even the example commands don't work --they are ignored as if they have wrong syntax. It doesn't make any sense for them to be example commands if they're the incorrect syntax, so that can't be the issue.

#### How can we reproduce this issue?

1. I typed !addcom desiredcommandname desiredmessageortag
2. I then typed !desiredcommandname to receive no response
3. I then tried !command enable desiredcommandname yet I only get the same command help window that does not help, enable anything, or make the !desiredcommandname do anything when typed.

Alternate method

1. I typed !addcom whereami? You're in channel {channel.name}! from the examples
2. I then typed !whereami? and the bot will not respond. (But will respond to aliases, and example aliases like !alias add NO flip and !NO as if nothing is wrong.)

**Comment by flaree** [comment]
The command is [p]customcom or just [p]cc for short

**Comment by Twentysix26** [comment]
Were you previously running an old version or have you read about [p]addcom somewhere? I'm asking in case there is some out of date documentation
edit: Found and fixed it
