### ISSUE TITLE
[V3 Config] Adding some Python magic functions to Group and/or Value

### ISSUE THREAD

**Issue by DeltaSigma130** [Cog-Creators/Red-DiscordBot#2112]
# Feature request

I would like to see an additional Python magic method added to at least the Group class.  The one with the most benefit would be `__eq__`.  I would except this would be True if the identifiers within the Group/Value equaled each other.  For completeness, driver, and force_registration could be checked, but default checking would be problematic due to possible depth issues.

**Comment by Jqd0n** [comment]
Yeah, I would too.

**Comment by mikeshardmind** [comment]
I don't think this is quite intuitive to have that be that equality here, and I also don't think there is a well-defined equality here given the async nature of access to the actual values. I'm curious what use-case you see this being useful given that you get config values by identifier already, this would seem to be an unneeded method.

**Comment by Tobotimus** [comment]
I'm with @mikeshardmind that if you would like to equate things like `Group` objects based on identifiers, simply equate `Group.identifiers`. This is more explicit.

**Comment by DeltaSigma130** [comment]
This is not an equality of the stored value itself.  It is simply a comparison of the objects themselves.  I am writing an extension library to Config that auto-generates Discord commands and Config objects in an ArgParse style.  I have the option of multiple commands modifying the same config, so I needed to check that the object is the same.  

I fully admit that it is a fringe use case, and I can see that there could be ambiguity or confusion.  I'll withdraw the request.

**Comment by mikeshardmind** [comment]
Less fringe than you might think, though I agree with @Tobotimus 's earlier statement that if you need that equality, just check the equality of the identifiers attribute.
