### ISSUE TITLE
Error when executing sudo pip3.5 install git+https://github.com/Rapptz/discord.py@async

### ISSUE THREAD

**Issue by JakeyPrime** [Cog-Creators/Red-DiscordBot#212]
Every time I try the command above, I get this error:
`Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pi                                                                                                                                                             p-build-08a51o4p/PyNaCl/setup.py';exec(compile(getattr(tokenize, 'open', open)(_                                                                                                                                                             _file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp                                                                                                                                                             /pip-c6sei5q8-record/install-record.txt --single-version-externally-managed --co                                                                                                                                                             mpile" failed with error code 1 in /tmp/pip-build-08a51o4p/PyNaCl/`

Screenshot of it happening:
http://puu.sh/oAAc6/00c41a7892.png

**Comment by irdumbs** [comment]
[5:17 PM] BOTSaltBot: sudo apt-get install python3.5-dev build-essential libssl-dev libffi-dev
[5:17 PM] BOTSaltBot: sudo yum groupinstall "Development Tools"
[5:17 PM] BOTSaltBot: sudo yum install libffi-devel libssl-devel

not from me, from SaltBot

**Comment by orels1** [comment]
You're on windows, I suppose?
try running `pip install pynacl` separately and tell if it gives the same error

**Comment by tekulvw** [comment]
Feel free to post back if you're still having issues, closing because no response and the commands you need have been posted.
