### ISSUE TITLE
[CustomCommands] Cooldown for custom commands

### ISSUE THREAD

**Issue by Zalatis** [Cog-Creators/Red-DiscordBot#2120]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

In customcog cog add the possibility to mention a cooldown for the custom command 

`[p]customcom add commandyouwant Hello World -t 3600`

3600 = time in seconds

**Comment by Tobotimus** [comment]
Hi! I think we could probably include this in 3.1. I see in your example you've included unix-style arg parsing, unfortunately we don't really support that in core at the moment. I would instead suggest a new command:
```
[p]customcom setcooldown <command> <seconds>
```
This prevents polluting `[p]customcom add`'s arguments but is still straightforward to use.

**Comment by Zalatis** [comment]
Nice thank you :)

**Comment by Zephyrkul** [comment]
Sounds fun and I'm bored. I'll look into it.

**Comment by Zephyrkul** [comment]
I wasn't sure what type of cooldown you were referring to (per user, per channel, overall?), so I just put all three in.

**Comment by Zalatis** [comment]
Really nice , any possibility to adapt the develop branch with this too ? 🥉 
(not only V3 then :c)

**Comment by Zephyrkul** [comment]
I don't plan to, sorry. That branch (V2) is feature-frozen; bugfixes and minor enhancements only.

**Comment by Zalatis** [comment]
Oh okay :(
Np going to sleep have a good day :)

**Comment by Zephyrkul** [comment]
Sure thing. If you want to consider upgrading to V3 at any point feel free to ask questions about it in the [official server.](https://discord.gg/red)

**Comment by Kowlin** [comment]
Merged in #2124
