### ISSUE TITLE
[V3] bot-wide settings for automated mod actions

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2125]
# Feature request

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

One last thing I'd like to see added prior to RC1 (because this is a 3rd party intended for use tool), which has been discussed partially in discord before

Per guild settings for automated mod action immunity. Any cog having such actions should use the settings there, and a `bot.is_automated_action_immune(member_or_context)` should work for cogs to check this.

I'll have a PR for this soon if it's something others think should be in core, but I find this a better solution than tying it to mod roles (which grant other things) or needing each individual cog which has such settings to need to be configured separately.

**Comment by Tobotimus** [comment]
Resolved by #2129 :tada:
