### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by StaffiiVR** [Cog-Creators/Red-DiscordBot#214]
Cant figure out how to change it when its already set D:

**Comment by StaffiiVR** [comment]
and also how do i change commands cuz i want to change [p]cleanup messages [number]
to [p]clear [number]

**Comment by franc-ist** [comment]
`[p]set prefix`, where `[p]` is your prefix

**Comment by franc-ist** [comment]
to change the commands, edit the code. we wont help you if it goes wrong

**Comment by StaffiiVR** [comment]
okey thx i just wanted to change to clear but its fine :+1:

**Comment by irdumbs** [comment]
you can add an alias. `[p]alias add clear cleanup messages`
