### ISSUE TITLE
Get potential context when loading a cog

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#2147]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Sometimes, cogs needs interaction with the one who loaded it for the first time (for initial setup or this kind of things). However, for now, we can only DM the bot owner for this since we don't know where the cog was loaded (and sometimes, co-owners load it, so the owner dunno what's happening and the co-owner don't see the cog getting loaded).
Appending a potential context (can be `None` if it was loaded on start) to the setup function's arguments would be great for these cogs who needs initial setup!

**Comment by mikeshardmind** [comment]
I'm not sure this is appropriate to add, as with RPC support in bot, it's possible the first load happens without a context as well, so encouraging cog devs to rely on something like this is not advisable.

I'd suggest informing your users with your install message that the cog requires setup and hiding commands which require setup being done using checks until then.

**Comment by Tobotimus** [comment]
I'm with Mike here, could you explain what is achieved by this over the install message? The install message can easily direct the user to a setup command. I can't think of a reason why a cog would need a setup for every time it's loaded rather than when it's installed

**Comment by laggron42** [comment]
I use Sentry logging in my cogs, but the users must accept or not if they want their errors to be reported. Currently, the bot sends a DM to the owner and waits for its answer, but some users told me it would be better if this was done in the context channel because they're co-owners (that only happens for the first load).

**Comment by mikeshardmind** [comment]
This can still be prompted for in an install message, which would automatically be in the context channel.

**Comment by laggron42** [comment]
Alright, thanks for the suggestions.
