### ISSUE TITLE
Failed to load: cogs.audio

### ISSUE THREAD

**Issue by StaffiiVR** [Cog-Creators/Red-DiscordBot#215]
So i just downloaded everything that said was needed, but i cant figure whats causing the error :cry: 

![image](https://cloud.githubusercontent.com/assets/15522514/14936354/40a4ec42-0eeb-11e6-9000-542bc25b9b31.png)
![image](https://cloud.githubusercontent.com/assets/15522514/14936356/4c895778-0eeb-11e6-9bd8-c7002b6bb30d.png)

**Comment by franc-ist** [comment]
join the support server

**Comment by StaffiiVR** [comment]
link?

**Comment by franc-ist** [comment]
its everywhere on the docs
