### ISSUE TITLE
Google Sheets: Read and Write Data

### ISSUE THREAD

**Issue by MostHated** [Cog-Creators/Red-DiscordBot#2150]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [X] API functionality

#### Describe your requested feature

I was wondering if its possible to allow the bot to read and write data to and from a Google Sheet document so that say, specific information could be tied to a user and saved to Google Sheets as a database and could then be referenced as needed for a lookup. The top row of each column would be the header name and each row would be an entry. 

Example would be, a user messages the bot and sends them a pieve of information, such as an ID number or something, the bot checks against an API or other Google Sheet to see if the data being checked is valid, if so it makes an entry in a separate Google Sheet as seen below, it then assigns that user in Discord to a specific group based on the verification and saves that to the Google Sheet for future reference in case the user leaves or something, so when they come back the bot knows that person already verified and maintain their access to X group, so they can access X channel.

```
DiscordName | IsUserVerified | DateOfVerification 
@1234Bob    | Yes            | 2018-09-24
@2345Mark   | Yes            | 2018-09-25

```

**Comment by Tobotimus** [comment]
Hi @MostHated, not mentioning the difficulties with using the OAuth2 Google Sheets API with Red, this feature is simply too niche to be core. You might find someone willing to create it over at the [cog board](https://cogboard.red), however, as it could make a good 3rd party cog.
