### ISSUE TITLE
Looking for a way to edit [p]help

### ISSUE THREAD

**Issue by Alchameth** [Cog-Creators/Red-DiscordBot#2153]
I am making this new issue because I want to remove the embedded message and provide a link that shows the commands in details; in short i want to change the [p]help command to my needs. Is there any way to do that?

26 mentioned an external cog where I have to do "bot.remove_command("help")" but i dont know what that cog is

**Comment by Tobotimus** [comment]
Hi @Alchameth we'd prefer if you took this discussion to Discord, you may ask in the #coding channel in https://discord.gg/red. Thanks :smiley:
