### ISSUE TITLE
Moderation cog problem 

### ISSUE THREAD

**Issue by Lowiee** [Cog-Creators/Red-DiscordBot#2154]
So today I used the clean up command and noticed it wasn’t working so I was like eh probably deleted something fix it later then I notice pretty late at night, that all the moderation commands are broken I tried reinstalling didn’t work, think the moderation part needs to be recoded!

**Comment by Twentysix26** [comment]
Is the bot responding at all? I would also check for any message in the console after you issue a cleanup.  
Avoid reinstalling for random issues... Unless you modified the code (and in that case it's outside the scope of these issues) that is always the last resort and rarely solves anything.

**Comment by Lowiee** [comment]
Let me get the error some how gimme a minute

**Comment by Lowiee** [comment]
Every moderation command is broken

**Comment by Lowiee** [comment]
It randomly out of no where stopped working which is ood because I never made any modification on that day.

**Comment by Twentysix26** [comment]
"broken" doesn't tell much, we cannot help without details.  
If it doesn't respond at all check if the cog is loaded with `[p]cogs`

**Comment by Lowiee** [comment]
I’ll explain the issue properly, I woke up and tried to clear some messages then it wouldn’t work I didn’t make a modification before that, so I don’t know why it isn’t working, I try to load and it fails other cogs work on load https://imgur.com/a/3Ai1o78

**Comment by Twentysix26** [comment]
1. Turn off the bot
2. Delete the file `data/mod/past_names.json`, it's corrupted
3. Turn on the bot
4. `[p]load mod`

**Comment by Lowiee** [comment]
^-^ fixed thank you, issue resolved
