### ISSUE TITLE
[V3 Mod] Tempban doesn't remove the user from settings on unban

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#2160]
# Command bugs

#### Command name

tempban

#### What cog is this command from?

Mod

#### What were you expecting to happen?

When the user is unbanned and then permanently banned, they remain permanently banned.

#### What actually happened?

The user is unbanned by the bot on the next loop due to their previous tempban having expired.

#### How can we reproduce this issue?

1. Tempban a user.
2. User is unbanned and rejoins.
3. User is permanently banned. Another tempban overrides the settings, so an extended tempban sidesteps the issue.
4. User is unbanned by the bot when the unban task loop runs again.

**Comment by netflixandbill** [comment]
I can try to find the logs or other debug info from when this was happening to give some more insight on this. thanks for writing this up too.

**Comment by Tobotimus** [comment]
@netflixandbill Thanks for offering but there's no need, this issue is resolved by #2161 :smiley:
