### ISSUE TITLE
Make aliaslist actually list aliases instead of spamming the chat.

### ISSUE THREAD

**Issue by agtr** [Cog-Creators/Red-DiscordBot#219]
![fulllength](https://cloud.githubusercontent.com/assets/12876103/14938390/dc6a887c-0f21-11e6-9757-f08921b3cf75.PNG)

**Comment by franc-ist** [comment]
#187

**Comment by tekulvw** [comment]
I'm confused as to what you're actually asking.

If you're asking to show what each alias is, that can be done with `!alias
show <name>`. If you're asking to show what each alias is NEXT to the name
in the list, that's likely something I'm not going to implement. Like you
said, we're trying to avoid spamming the chat and having it show what the
alias is in `!alias list` is gonna wreak havoc especially if you have long
aliases.
On Apr 30, 2016 4:27 PM, "Francis Taylor" notifications@github.com wrote:

#187 https://github.com/Twentysix26/Red-DiscordBot/issues/187

**Comment by irdumbs** [comment]
!customcommands sends them in a PM,
maybe !aliaslist could do that as well?

**Comment by ddday** [comment]
`  @commands.command(pass_context=True, no_pm=True)
    async def aliaslist(self, ctx):
        server = ctx.message.server
        if server.id in self.aliases:
            message = "```Alias list:\n"
            for alias in sorted(self.aliases[server.id]):
                if len(message) + len(alias) + 3 > 2000:
                    await self.bot.say(message)
                    message = "```\n"
                message += "\t{}\n".format(alias)
            if len(message) > 4:
                message += "```"
                await self.bot.say(message)`


To 


`    @commands.command(pass_context=True, no_pm=True)
    async def aliaslist(self, ctx):
        server = ctx.message.server
        if server.id in self.aliases:
            message = "```Alias list:\n"
            for alias in sorted(self.aliases[server.id]):
                if len(message) + len(alias) + 3 > 2000:
                    await self.bot.say(message)
                    message = "```\n"
                message += "\t{}\n".format(alias)
            if len(message) > 4:
                message += "```"
                await self.bot.whisper(message)`

**Comment by tekulvw** [comment]
#195 7e4c41f
