### ISSUE TITLE
Change the LOGIN_TYPE

### ISSUE THREAD

**Issue by patrickblackjr** [Cog-Creators/Red-DiscordBot#220]
Is there a list of `LOGIN_TYPE`s from the /data/red/settings.json:
![discord-bot-question](https://cloud.githubusercontent.com/assets/13282318/14938689/5564d3a8-0ef1-11e6-82ae-120707ae548b.png)

I want to use Discord's official API somewhat and I want that fancy little `BOT` tag that comes after the name if you use their API so I was wondering if there was a way to change that and use the information provided when you create a bot user on discord. 

Thanks,
Patrick

**Comment by Redjumpman** [comment]
If you have an account that you have converted/created to make a bot account using discords Oauth, then you will need to go to that page and receive the bot token. If you delete you settings.JSON you and run red.py it will prompt you to enter either your email or bot token. This will allow you to have the tag. Also take a look at this https://twentysix26.github.io/Red-Docs/red_guide_bot_accounts/ for more information on this subject.

**Comment by tekulvw** [comment]
Or you could run `!set token <token>` in DM and the bot will switch itself.
You'll just need to restart it to see it gain the BOT tag.

**Comment by irdumbs** [comment]
still think there should be a built-in command to switch between the 2 😉

**Comment by patrickblackjr** [comment]
Worked like a charm.

/close
