### ISSUE TITLE
[Downloader] Cogs don't get unloaded after uninstalling.

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2216]
# Other bugs

#### What were you trying to do?

When uninstalling a cog from downloader the cog does not get unloaded.

#### What were you expecting to happen?

The cog being deleted **&** unloaded.

#### What actually happened?

The cog only got deleted, The cog stayed active and in memory.

#### How can we reproduce this issue?

``cog uninstall <3rd party cog>``
Check that the cog is still loaded in memory
``cogs``

**Comment by Tobotimus** [comment]
Resolved by #2243.
