### ISSUE TITLE
!addplaylist 

### ISSUE THREAD

**Issue by llAntonio1ll** [Cog-Creators/Red-DiscordBot#223]
When I try to add a track by doing !addplaylist Rap https://www.youtube.com/watch?v=tzJyWmDWpqY
I get Something went wrong. Either the link was incorrect or I was unable to retrieve the page. I even tried putting rap lowercase and got the same error. Am I doing something wrong, or is this an issue please respond.
![bot_issue](https://cloud.githubusercontent.com/assets/19142997/14946211/5f0baa96-0fe4-11e6-8fda-93bd15bfdca4.png)

**Comment by JaL-P** [comment]
At the moment you can not add single songs to a playlist.

[p]addplaylist will only accept YouTube or Soundcloud Playlists. If you was wanting to add a single song then you would have to add it into the txt file (Red-DiscordBot/data/audio/playlist/<PlaylistName>)

**Comment by llAntonio1ll** [comment]
@JLBP ok but what is the format.

**Comment by franc-ist** [comment]
The format is a youtube playlist link [https://www.youtube.com/playlist?list=](https://www.youtube.com/playlist?list=)

**Comment by tekulvw** [comment]
Agreeing with ^. You must use a youtube playlist link with `!addplaylist`. Feel free to come to #support if you have any more questions.
