### ISSUE TITLE
[3.1] Mute improvements

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2231]
~~@zephyrkul and I are both working on various improvements (note, not bugfixes) to mute which will not be ready for the initial stable release of V3~~

Here's a to-do list for this:

[ ] Temp muting (see #2140)
[ ] Role based server mute options (not on by default)
[ ] Preventing mute dodging (leave-rejoin server) 

[ ] additional QoL changes from #2179

**Comment by BurritoWrapped** [comment]
I would like to see this be added to Red.  I see this partially done in #2179

**Comment by mikeshardmind** [comment]
It's on the planned list. (see the tags) However, with several people busy with other things, and with the current development focus on the 3.0.0 release, this will not be finished until after that.

**Comment by DiscordLiz** [comment]
This is getting to be extremely large. Would it be possible to have the mute functions split into another extension entirely?

**Comment by mikeshardmind** [comment]
:+1: from me on that assuming it would be in 3.2, not 3.1 (or after, assuming the planned documentation changes to not include cogs in breaking guarantees).
