### ISSUE TITLE
[Downloader/Converter] _ is not Defined

### ISSUE THREAD

**Issue by Aioxas** [Cog-Creators/Red-DiscordBot#2236]
# Command bugs

#### Command name

cog uninstall

#### What cog is this command from?

Downloader & Converters.py

#### What were you expecting to happen?

Normal error saying "cog is not installed

#### What actually happened?

error saying _ is not defined

#### How can we reproduce this issue?

[p]cog uninstall OwO

**Comment by Tobotimus** [comment]
Resolved by #2239.
