### ISSUE TITLE
[Downloader] KeyError Prefix

### ISSUE THREAD

**Issue by Aioxas** [Cog-Creators/Red-DiscordBot#2237]
# Command bugs

#### Command name

cog uninstall

#### What cog is this command from?

Downloader

#### What were you expecting to happen?

Tell me that the cog is installed but can no longer be located for uninstallation.

#### What actually happened?

KeyError: prefix

#### How can we reproduce this issue?

1. Install any 3rd-party cog
2. Remove files manually for said cog in CogManager/cogs
3. Attempt [p]cog uninstall <cog name of 3rdparty cog>
4. Receive error that error wasn't able to display (Check Console Log for Details)

**Comment by Tobotimus** [comment]
Resolved by #2238.
