### ISSUE TITLE
[V3 config] Create voice_channels etc for config

### ISSUE THREAD

**Issue by The-Tasty-Jaffa** [Cog-Creators/Red-DiscordBot#2248]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

I'm suggesting renaming the current `Config.channels` to `Config.text_channels` because it is more clear. Also changing the name allows for clear use of other defaults such as Voice channels and categories.

By allowing the existence of `Config.voice_channels` and `Config.category_channels` would allow cog creators to have a different way of using config.

An example of where this would be incredibly useful would be in my Tempvoice cog, pswd cog or any other cog that stores data about voice/category channels.

**Comment by mikeshardmind** [comment]
Just an FYI, `Config.channel` does already support anything which has an id attribute castable to both a  str and int (I might even be abusing this behavior of it in some places...)

While I do support this improvement as you may want different registered defaults for different channel types, you can use a sentinel value in your defaults to signify this until this is handled.

**Comment by The-Tasty-Jaffa** [comment]
> Just an FYI, `Config.channel` does already support anything which has an id attribute castable to str. (I might even be abusing this behavior of it in some places...)
> 
> While I do support this improvement as you may want different registered defaults for different channel types, you can use a sentinel value in your defaults to signify this until this is handled.

I don't see any information about this in the docs... just the one line which says > `Config.channel() which takes discord.TextChannel`

**Comment by mikeshardmind** [comment]
I'm aware the docs don't elaborate on this fully, which is why for now I'm informing you the actual behavior used. There's no checking for type done there, it just grabs the id, and makes it a str as a key in a config identifier sequence. I've also edited it should be castable to an int as well.

If you'd like to PR that it accepts any `discord.abc.GuildChannel` instead, this could easily be accepted, otherwise, someone else will get to it when they can. (While the type could be wider, it would be better not to promote this usage, and add new methods for custom objects later)

**Comment by Tobotimus** [comment]
I agree with your sentiment, and there are quite a few things we've been thinking about changing in config. For now these will be on hold until we have a final release for 3.0 and have made some more progress on 3.1. Thanks :)

**Comment by mikeshardmind** [comment]
I think rather than implement this as breaking, we should retain the old behavior as there may be settings which are not channel type specific and have no need of the specificity as a result, while adding a group for each channel type.

**Comment by mikeshardmind** [comment]
*sigh* after getting around to looking into this a bit more, I noticed a "fun" detail in config.

```

    GLOBAL = "GLOBAL"
    GUILD = "GUILD"
    CHANNEL = "TEXTCHANNEL"
    ROLE = "ROLE"
    USER = "USER"
    MEMBER = "MEMBER"
```

This can still be non breaking by changing it to say...

```

    GLOBAL = "GLOBAL"
    GUILD = "GUILD"
    CHANNEL = "TEXTCHANNEL"  # do not change this without writing a migration.
    TEXT_CHANNEL = "ACTUALTEXTCHANNEL"
    ...
```
But it's a little ugly. Still worth supporting IMO, and possibly create a cleanup for this at the next version we push with actual breakage.

**Comment by mikeshardmind** [comment]
Actually, because of how global scopes work (*curses at getattr*), this isn't non-breaking no matter what. Slate this for 3.2

**Comment by Tobotimus** [comment]
I think the minimum breakage (what @mikeshardmind is saying) is that new scopes mean more functions on the Config objects, which would cause problems for cog creators who use a Global key which has the same name as the new function.

If we did it like this:
- `Config.channel` which uses the `ConfigCategory.CHANNEL = "TEXTCHANNEL"` category,
- `Config.text_channel` which uses the `ConfigCategory.TEXT_CHANNEL = "ACTUALTEXTCHANNEL"` category, and
- `Config.voice_channel` which uses the `ConfigCategory.VOICE_CHANNEL = "VOICECHANNEL"` category

It's ugly, but it's unlikely to bother many cog devs. Perhaps we could look into migrating "TEXTCHANNEL" to "CHANNEL" silently to mitigate the ugliness.

*Edit:* I forgot about category channels but you get the picture ;)

**Comment by mikeshardmind** [comment]
I think I'd prefer deprecating global key use to prevent this sort of issue from being reoccuring (Named custom groups with 0 identifiers will work identically well) or changing how global keys are accessed `config.get_global` or something else like that.

But yes, that would be the breakage.

**Comment by mikeshardmind** [comment]
closing this, it's rehashed in the config2 discussion better than here.
