### ISSUE TITLE
[V3 Help] Help filtering bug.

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2249]
# Other bugs

#### What were you trying to do?

Using permissions, default deny a Cog, reallow a command from it to some scope.

#### What were you expecting to happen?

Help should show that cog in scopes where there is at least 1 usable command from it.

#### What actually happened?

Help can be invoked for the command, command works, but the cog help is not shown.

#### How can we reproduce this issue?

 - Using permissions, default deny a Cog, reallow a command from it to some scope.
 - Invoke help for the cog

### Note:
Reporting this for @Kowlin as he seems to have gotten distracted, behavior was first observed in Fortnite server.

**Comment by Tobotimus** [comment]
Resolved by #2339.
