### ISSUE TITLE
AttributeError: '<class '__main__.Bot'>' object has no attribute 'bot'

### ISSUE THREAD

**Issue by Lonomox** [Cog-Creators/Red-DiscordBot#2253]
Hello everyone,

I have the following issue with my bot:

When I try to use the command: !bank than the bot is giving out the following:

```
!bank
Bank operations
Commands:
  balance  Shows balance of user.
  register Registers an account at the Twentysix bank
  reset    Deletes all server's bank accounts
  set      Sets credits of user's bank account. See help for more operations
  transfer Transfer credits to other users
Type !bank command for more info on a command.
You can also type !bank category for more info on a category.
```
```
Error in command 'bank'. Check your console or logs for details.
```
My self-hosted bot is running on a Linux Debian 8 server. This is the error who is occurring in my console:

```
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/WhatsMyName/cogs/economy.py", line 305, in _bank
    await send_cmd_help(ctx)
  File "whatsmyname.py", line 132, in send_cmd_help
    await self.bot.say("I've just sent you a PM!"
  File "lib/discord/client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Bot'>' object has no attribute 'bot'
```

I don't know how to fix the issues, who are occurring above.

**Comment by bobloy** [comment]
Did you rename a file to `whatsmyname.py` ?

**Comment by Lonomox** [comment]
> Did you rename a file to `whatsmyname.py` ?

I just made a copy of "red.py" and simply edited it 🙂 I didn't change any of the code, just named everything from "Red" to "WhatsMyName".

EDIT: I only renamed everything who isn't important to start up

**Comment by Tobotimus** [comment]
This error doesn't occur without the modifications you've made. We cannot help you if you edit the code, please revert your changes if you would like to fix it.

**Comment by Lonomox** [comment]
I've just looked through the "whatsmyname.py" and I just changed following:

line 27: `description = "WhatsMyName - A Discord bot made with <3 by TivogGaming"`

and

line 297: `print("WhatsMyName - Discord Bot")`

**Comment by Lonomox** [comment]
Okay, nvm. Got it self ;)

**Comment by Twentysix26** [comment]
We do not deal with issues caused by modifications of the original code. Open a new issue if you encounter a problem that's reproducible on a default installation.
We would also appreciate if you'd keep the credits of the original authors and do not claim to have made the bot yourself.
