### ISSUE TITLE
[V3 Filter] syntax change on [p]filter add/remove and [p]filter channel add/remove

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#2254]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

I'm suggesting changing the syntax of the commands mentioned in the title to have a param called `is_sentence`. This param is optional (see https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html#typing-optional), defaulting to `False` if not specified

Running the commands to add multiple individual words at once would have no visible change (i.e. it'd still be something like `[p]filter add word1 word2 word3`. Adding/removing sentences would change to `[p]filter add/remove yes This is a sentence` instead of `[p]filter add/remove "This is a sentence"` and then having to reconstruct the sentence without the quotes

**Comment by Jackenmen** [comment]
The behavior of filter commands has changed since (see #3925) and I feel this is no longer needed. I'm going to close this but if you don't agree, feel free to reopen with a comment.
