### ISSUE TITLE
[V3 Downloader] Non-portable downloader issues. (sigh)

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2260]
CENTOS 7's latest version of git available in default repositories is `1.8.3.1` which does not have the `-C` option. This means on one of our OSs listed as supported, several downloader functions will error.

Docs need updating, or we need to handle certain things differently

Problematic lines in red code below:

https://github.com/Cog-Creators/Red-DiscordBot/blob/8bba860f85d0c1c9ff65caab4efd27152099116c/redbot/cogs/downloader/repo_manager.py#L28-L34

Reference of available options in the oldest version of git we should expect on a supported OS: https://book.git-scm.com/docs/git/1.8.3.1

**Comment by mikeshardmind** [comment]
the most portable way of handling this would likely involve invoking from that path, rather than using `-C`,  though we could use the `--git-dir` option instead (which is not equivalent in behavior, so this would need testing)

**Comment by Tobotimus** [comment]
We're already requiring the use of IUS for installing Python, we just need to change the requirement from `git` to `git2u`

**Comment by Tobotimus** [comment]
Resolved by #2309.
