### ISSUE TITLE
Filter Regex v3

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [Cog-Creators/Red-DiscordBot#2261]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x ] Command
- [ ] API functionality

#### Describe your requested feature
The ability to use regex in [p]filter so if "hell" is added for example, it won't delete Hello.
<!--
Feel free to describe in as much detail as you wish.
To make Filter not delete everything that has the filtered word in.

If you are requesting a cog to be included in core: 
    - Describe the functionality in as much detail as possible
    - Include the command structure, if possible
    - Please note that unless it's something that should be core functionality,
      we reserve the right to reject your suggestion and point you to our cog 
      board to request it for a third-party cog
      
If you are requesting a command:
    - Include what cog it should be in and a name for the command
Filter
    - Describe the intended functionality for the command
To not censor all words that have a filtered word inside it.
    - Note any restrictions on who can use the command or where it can be used
Mod, admin, server owner and bot owner.

**Comment by calebj** [comment]
It's trivial to arrange a denial of service using Python's built-in backtracking regex engine, so full support for regex isn't a good idea for core. Automata-based engines such as RE2 and Hyperscan don't have this problem, but impose additional binary dependencies.

*Almost* equivalent functionality can be achieved by the following:
```py
WORD_SPLIT = re.compile(r'[^\w]')
...
msg_words = set(map(str.lower, WORD_SPLIT.split(content)))
should_delete = msg_words.intersection(filtered_words)
```

**Comment by Tobotimus** [comment]
#2292 is a more specific description of the issue we are resolving here, since we are not planning on supporting regex as requested here. So, I'm closing this in favour of #2292.
