### ISSUE TITLE
[Modlog API] Allow lookup via UserID

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2266]
# Feature request
#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Allow the modlog API to look up cases by userID, this can help with various cases whereby a cog creator wants to look back at the past history of a member in a guild. Such as having automated tools decide then next action for the member.

**Comment by DiscordLiz** [comment]
I'm going to do this unless someone else was already working on it. I don't know if there's a better place to discuss who is doing something.

**Comment by Tobotimus** [comment]
@DiscordLiz This is the best place to ask :smiley: As far as I know, no one is currently working on this. So we'd be grateful if you're willing to try it out!
