### ISSUE TITLE
[Filter] [V3] Removes words not added to the filter.

### ISSUE THREAD

**Issue by GamerGirl1995** [Cog-Creators/Red-DiscordBot#2292]
# Other bugs

#### What were you trying to do?

we added certain words to the filter to be filtered on the discord server.
and we want the words that consist of the bad word to remain on the channel.

#### What were you expecting to happen?

for the word consisting of the bad. so not being the bad word.
For example: ass is on the filter but if someone then types assist or assistant it should leave those words in the channel, because they are not bad words.

#### What actually happened?

Someone mentioned that he needs assistance with a specific problem and the bot removed the word assistance because it has the word ass in it that is indeed on the filter

the word has been added with: !filter add ass

#### How can we reproduce this issue?

1. add a word to the the filter by typing for example: !filter add ass
2. type a word that has the filtered word in it like: assistant
3. The bot will remove the word assistant, event though the word itself isn't filtered but the word ass is.

I hope i did this reporting right, i've made an account with github just to report this issue.
Thanks for the great bot!

**Comment by Ianardo-DiCaprio** [comment]
I pretty sure there was a PR that added this recently so I'm sure this will be available in a update in the near future.

**Comment by Kowlin** [comment]
Pending PR: https://github.com/Cog-Creators/Red-DiscordBot/pull/2262
