### ISSUE TITLE
git 

### ISSUE THREAD

**Issue by Shio17** [Cog-Creators/Red-DiscordBot#2293]
Red launcher said 
  Error [WinError 2] 지정된 파일을 찾을 수 없습니다 while executing command git clone -q 
Cannot find command 'git' - do you have 'git' installed and in your PATH?
this
how can i solve this?

**Comment by GamerGirl1995** [comment]
by installing git.

https://git-scm.com/downloads

**Comment by Shio17** [comment]
i download it but i have that error

**Comment by bobloy** [comment]
Please use the docs to install Red and don't skip any steps.
https://twentysix26.github.io/Red-Docs/red_install_windows/

If you have any further errors, join our discord and ask in the #support channel
https://discord.gg/red

**Comment by GamerGirl1995** [comment]
@bobloy that install doc is wrong though, because current Red bot does require Python 3.6.6 to run.
in that install doc it says to not install Python 3.6 or higher, but it is required now.

@zetablack you need to install python 3.6.6

**Comment by yamikaitou** [comment]
@gamergirl1995 Wrong, Red v3 requires 3.6.6. Red v2 still uses 3.5.4 on Windows.

**Comment by Shio17** [comment]
so should i download python 3..6.6?

**Comment by yamikaitou** [comment]
No, please follow the guide you were linked to

**Comment by GamerGirl1995** [comment]
better question would be are you trying to use V3 or V2 @zetablack 
if V3 then yes you need to install 3.6.6. python version.

**Comment by Kowlin** [comment]
Gonna close this. For support with installing Red please [join the discord server](https://discord.gg/red).
