### ISSUE TITLE
[CustomCom] CC list markdown does not properly escape.

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2295]
The CC list does not properly escape markdown causing the bellow issue. 

![image](https://user-images.githubusercontent.com/10947836/48375198-77f18f00-e6c7-11e8-8a3c-1481266bd43c.png)

**Comment by Tobotimus** [comment]
I'm confused as to why the `>>epicstaff` command is not being placed on a new line, and it's also missing one of its right angle-brackets in the prefix. Maybe it has something to do with the content of the `>>creator` command?

**Comment by Kowlin** [comment]
It seems that Discord is inserting the new line into the URL, seeing as the [Hex character 0A](http://www.columbia.edu/kermit/ascii.html) is a line feed.

**Comment by Tobotimus** [comment]
Resolved by #2350.
