### ISSUE TITLE
Default "Entertainment" trivia list contains incorrect facts about Beethoven

### ISSUE THREAD

**Issue by Sonicwave** [Cog-Creators/Red-DiscordBot#2298]
The Entertainment trivia list contains two facts about Beethoven that are incorrect ([link](https://github.com/Cog-Creators/Red-DiscordBot/blob/develop/data/trivia/entertainment.txt) for reference):
>Which of Beethoven's symphonies was the legendary "Incomplete"?`The 9th Symphony`9th`9 (line 187)

>How many symphonies did Beethoven complete?`Eight`8 (line 297)

Wikipedia however states that Beethoven finished 9 symphonies and the 10th was the one that was unfinished. This is also stated at the question at line 504, "_What composer was working on his 10th symphony at the time of his death?`Ludwig van Beethoven`Beethoven_".

There are also several questions that I believe have multiple correct answers that are not mentioned:
> What is the term used for 'slowly' in music?`Lento (line 539)

"Adagio" is also used to describe "slowness in music".

> He wrote the operas "The Magic Flute" and "The Marriage of Figaro"?`Wolfgang Amadeus Mozart

This question should also accept "Mozart" as an answer instead of just "Wolfgang Amadeus Mozart". The grammar is also awkward; it might be better phrased as "Who composed the operas ....?"

> What composer was working on his 10th symphony at the time of his death?`Ludwig van Beethoven`Beethoven

Gustav Mahler also had an incomplete 10th symphony.

**Comment by mikeshardmind** [comment]
This was resolved in #2823
