### ISSUE TITLE
Could not find a version that satisfies the requirement youtube-dl

### ISSUE THREAD

**Issue by Reden1039** [Cog-Creators/Red-DiscordBot#2300]
# Command bugs

#### Command name

Could not find a version that satisfies the requirement youtube-dl (from -r requirements.txt (line 3)) (from versions: )

#### What cog is this command from?

Install basic + audio requirements (recommended)

#### What were you expecting to happen?

Install basic + audio requirements

#### What actually happened?

Error appeared saying:
Collecting youtube-dl (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement youtube-dl (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for youtube-dl (from -r requirements.txt (line 3))
An error occurred and the requirements setup might not be completed. Consult the docs.

#### How can we reproduce this issue?

1. Follow steps on website to download and setup Red
2. Run Red
3. Install Requirements
I don't know why this is happening. I'm a beginner. Any help?

**Comment by Tobotimus** [comment]
Hi, I'm sorry you had this issue, and sorry for the slow response. It looks like a bit of an anomaly. Please ensure the system you are installing Red on is connected to the internet. If you're still experiencing this issue, please let us know in the #support channel of our discord server: https://discord.gg/red. Thanks!
