### ISSUE TITLE
[V3 Cleanup] "Cleanup user" does not clean up the command itself

### ISSUE THREAD

**Issue by Aryss** [Cog-Creators/Red-DiscordBot#2307]
# Command bugs

#### Command name

Cleanup user

#### What cog is this command from?

cleanup

#### What were you expecting to happen?

Bot deletes the command after it completes the task, as it was with with cleanup command in v2

#### What actually happened?

Bot removed the messages by the specified user, but the left command intact

#### How can we reproduce this issue?

1. Send some messages by user @A
2. Use the following command: !cleanup user @A 2
3. messages will be removed, but the command will stay

**Comment by Tobotimus** [comment]
Thanks for this report @Aryss! This has been resolved by #2310.
