### ISSUE TITLE
Add ability to view other Urban Dictionary definitions

### ISSUE THREAD

**Issue by LGACode** [Cog-Creators/Red-DiscordBot#231]
I used the command `!urban kek` and got the first definition, so logically I wanted to see if it would give me the second definition. I tried using `!urban kek 2` but this only returns

> Your search terms gave no results

Please add the ability to view more definitions.

**Comment by Kowlin** [comment]
Currently made some time for this, working to make this.

**Comment by Kowlin** [comment]
PR #293 is done and awaiting approval.
