### ISSUE TITLE
Docs for setting up a Mong database

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#2312]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [ ] API functionality
- [x] Other

#### Describe your requested feature

Red supports Mongo databases, but there are literally no docs for setting up one, and the users have to search on google to create one (I did this, and it's complicated to know what we need to create, where to find the IP and the port...).

It would be great to write a simple doc for installing MongoDB, using their console, creating a user and its database and set that up with their Red instance before the first release! Would also be cool to have a section on how to migrate existing data between JSON and MongoDB, but #2251 needs to be fixed first.

**Comment by mikeshardmind** [comment]
Closing, we've removed mongo as an option.
