### ISSUE TITLE
[V3 Permissions] Rule precedence bug.

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2313]
Applying a default to a Cog as well as to a command within a Cog (Default deny cog, allow command) does not allow the command. 

With current intended precedence, this should allow the command. 

Initially reported by <@203619925179236352> (Céli28), confirmed by me and <@218773382617890828> (TrustyJAID)

**Comment by mikeshardmind** [comment]
This appears to just be default rules not playing well. Defaults (for cogs) are not be overridden by other rules which apply in the current context, and additionally, defaults can lock owners out of commands. This might indicate an exception being raised and suppressed silently breaking the expected behavior here based on the intended flow, but I won't have a chance to take a closer look into this until later.

**Comment by celi28** [comment]
Looks related to #2249

**Comment by Tobotimus** [comment]
Thanks for reporting, will look into this and #2249 when I get the chance.

**Comment by mikeshardmind** [comment]
I'm not sure it's related to 2249. 2249 being a UX issue that could possibly be caused by this leads me to think that solving this first and seeing if 2249 disappears with it is the best course of action for prioritizing fixes, then fixing that as a separate fix if this is not the case.

**Comment by mikeshardmind** [comment]
After a bunch of testing... Neither I, Toby, or Kowlin have been able to reproduce this anymore on V3/release/3.0.0. I'm closing this, but if anyone can still reproduce it on an up to date bot, please still comment.

**Comment by mikeshardmind** [comment]
Whoo boy, we have a reproduce now.

Thanks? Soulrfit <@142006827155062784>

<details><summary>yaml content collapsed in here.</summary><p>

Guild acl:
```yaml
COG:
  Admin:
    default: false
    334061410915057664: true
    411874257522393098: true
  Alias:
    default: false
    334061410915057664: true
    411874257522393098: true
  Audio:
    default: false
    334061410915057664: true
    411874257522393098: true
  Cleanup:
    default: false
    334061410915057664: true
    411874257522393098: true
  Core:
    default: false
    334061410915057664: true
    411874257522393098: true
  ErrorLogs:
    default: false
    334061410915057664: true
    411874257522393098: true
  General:
    default: false
    334061410915057664: true
    411874257522393098: true
  Mod:
    default: false
    334061410915057664: true
    411874257522393098: true
  ModLog:
    default: false
    334061410915057664: true
    411874257522393098: true
  NoEpic:
    default: false
    334061410915057664: true
    411874257522393098: true
  Reports:
    464137944815501312: true
  RoleManagement:
    default: false
    334061410915057664: true
    411874257522393098: true
  Spoopy:
    411874257522393098: true
  Streams:
    default: false
    334061410915057664: true
    411874257522393098: true
  SysInfo:
    default: false
    334061410915057664: true
    411874257522393098: true
COMMAND:
  cleanup:
    default: false
    411874257522393098: true
    334061410915057664: true
    415935589368594432: false
    441001661532602378: false
    362235556937334795: false
  customcom:
    default: false
    411874257522393098: true
    334061410915057664: true
  customcom list:
    362235742648532992: false
    362236197860409344: false
    362236325425971201: false
    440978693125439489: true
    520130928169975838: false
  genname:
    374987880592048128: false
  help:
    default: false
    334061410915057664: true
    411874257522393098: true
    440978693125439489: true
  info:
    default: true
  massrole search:
    411874257522393098: true
  now:
    440978693125439489: true
  pause:
    440978693125439489: true
  play:
    440978693125439489: true
  prev:
    440978693125439489: true
  search:
    440978693125439489: true
  skip:
    440978693125439489: true
  spoopy:
    411874257522393098: true
  spoopy check:
    441001661532602378: true
    441002581704310784: true
  stop:
    440978693125439489: true
  uinfo:
    334061410915057664: false
  voiceban:
    411874257522393098: true
```

There is no global acl set.


</p></details>

**Comment by Tobotimus** [comment]
Ah I misunderstood what the bug was when I last investigated this issue. I thought the bug was that default cog rules were taking precedence over actual model-based rules for commands. I now realise it's for default deny cog, default allow command.

This will also be the case for default deny supercommand, default allow subcommand.

I can see why this is occurring - the reason subcommand rules are able to take precedence over cog/supercommand rules is because when a rule is set, the parent's rules are modified too. This is not the case for default rules, and in fact they essentially follow the same process that was used before the permissions rewrite. However, I don't think it will be hard to incorporate them into the new technique.
