### ISSUE TITLE
git clone fail

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#2321]
# Other bugs

 No

#### What were you trying to do?

Install the requirements for red
#### What were you expecting to happen?

 For it to successfully install

#### What actually happened?

It failed with the error code

#### How can we reproduce this issue?

i really don't know
![image](https://user-images.githubusercontent.com/45539554/49419940-22088800-f757-11e8-879a-bb2b3400ceb7.png)

**Comment by yamikaitou** [comment]
https://discordapp.com/channels/133049272517001216/133049553984159745/516762468387782686

Or if you'd rather not join Discord to see it, 

close launcher
open git bash
run `git config --global url."https://".insteadOf git://`
then try installing reqs again

**Comment by ghost** [comment]
Thanks, I got the Bot ready and it's working smoothly
