### ISSUE TITLE
"empty" youtube link hungs bot

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#2322]
# Command bugs

#### Command name

`play` / `queue` 

#### What cog is this command from?

`audio`

#### What were you expecting to happen?

Say that link is incorrect or do nothing

#### What actually happened?

Bot hung

#### How can we reproduce this issue?

1. Use develop branch of bot
2. Exec cmd `queue https://www.youtube.com/watch`

**Comment by aikaterna** [comment]
I can't repro this on any of my v3 bots, the bot responds with "Nothing found" when you use the play command with this url, and the queue command doesn't work with urls either. Did you use a different command than just "queue https://www.youtube.com/watch" ?

**Comment by fixator10** [comment]
> I can't repro this on any of my v3 bots, the bot responds with "Nothing found" when you use the play command with this url, and the queue command doesn't work with urls either. Did you use a different command than just "queue https://www.youtube.com/watch" ?

This is on develop (async discord.py branch), not on v3 (rewrite)

**Comment by Tobotimus** [comment]
V2 is past its EOL, sorry, this is unlikely to be fixed.
