### ISSUE TITLE
[V3] Bundled data is not properly nuked, old data files stick around

### ISSUE THREAD

**Issue by luna-system** [Cog-Creators/Red-DiscordBot#2329]
#### What were you trying to do?

Remove files from the bundled data

#### What were you expecting to happen?

The files removed from the repo would be removed from bundled data/cog data folders on update

#### What actually happened?

The new files are in place, but so are the old files.

#### How can we reproduce this issue?

Set up a data folder, put 1.jpg 2.jpg and 3.jpg in there. Load the cog via github, push a commit that deletes 2.jpg, then update the cog. You'll have all three files still available to your data path.

```
high 冬(winter) energyToday at 11:18 PM
<<weeed set backgroundImage list

RedbotNGBOTToday at 11:18 PM
backgrounds: ['CrlxLkzUEAEzEan.jpg', 'CrlxLk4UkAAww6Z.jpg', 'forest3.jpg', 'beach-paradise-beach-desktop.jpg', 'backround.jpg.cf8567d9efb8925809436a2c1f01e8b0.jpg', 'CrlxLk1VYAAQdzi.jpg', 'backround2.jpg.6f994a20cc67e6a0058a6bed9cb7c123.jpg', 'forest1.jpg', 'glitchscene3.jpg', 'forest2.jpg', 'glitchscene.jpg', 'glitchscene2.jpg', 'backround3.jpg.5fa80a45458028f986e20c096082e888.jpg']
```

![unknown](https://user-images.githubusercontent.com/183767/49847135-9917cf00-fd9c-11e8-9dce-e2ae1ab9425e.png)

**Comment by Tobotimus** [comment]
Resolved by #2342. Note that #2342 has more significant changes than just fixing the issue in `load_bundled_data`. Please see the notes on the PR for details.
