### ISSUE TITLE
Bot won't move into voice channel

### ISSUE THREAD

**Issue by AdmiralTeitoku** [Cog-Creators/Red-DiscordBot#233]
How do I get the bot to move into the voice channel?

**Comment by franc-ist** [comment]
@AdmiralTeitoku can we have a bit more information than this? Also, see:

```
1. Have you done EVERYTHING on this page? https://twentysix26.github.io/Red-Docs/red_win_requirements/  
2. Are you in an audio channel?  
3. Does your bot join the channel?  
4. Does your bot have permissions to join the channel?  
5. Does your bot have permission to speak in the channel?  
6. Does your cmd give an error message?  
7. What happens when you do !help Audio?  
8. Does the cmd give an error message now?  
9. Have you tried !reload Audio?  
10. Have you tried restarting the bot?  
11. Are you sure you're not logged into the bot's account?
12. Are you sure you did EVERYTHING in requirements?
```

**Comment by AdmiralTeitoku** [comment]
1. Yes
2. Yes
3. No
   4.Yes
   5.Yes
   6.No
   7.No command called "Audio" found.
   8 No
   9.Yes
   10.Yes
   11.Yes
   12Yes

**Comment by franc-ist** [comment]
@AdmiralTeitoku join the [support server](https://discord.gg/0k4npTwMvTs5xhYo) and we'll be glad to help you out.

**Comment by Twentysix26** [comment]
Permanent invite: [Removed]  

**PLEASE NOTE:  
This is Red-DiscordBot, not Dynobot, not Fredboat, or whatever you searched to end up on this issue. I have removed the above link because people kept flowing into our server expecting help for other bots.  
If you are not using Red, look elsewhere.  
If you are, the link is in a variety of places, like the docs.**

**Comment by 83Spyder** [comment]
Just started having this issue as well after updating discord.py.

**Comment by Kowlin** [comment]
Run the following command as usual @83Spyder 
`pip3 install --upgrade git+https://github.com/Rapptz/discord.py@5fa715c35033c4fd5438649a03f4d2835e7a7f06`

**Comment by tekulvw** [comment]
Closing as I'm assuming he made it into the server
