### ISSUE TITLE
Repo add seems to fail on servers but not through PM

### ISSUE THREAD

**Issue by suedeyoung** [Cog-Creators/Red-DiscordBot#2332]
# Command bugs

Error in command 'cog repo add'. Check your console or logs for details. 

#### Command name

!cog repo add 26-cogs https://github.com/Twentysix26/26-Cogs

#### What cog is this command from?

26-cogs

#### What were you expecting to happen?

I would think that it would install the module since I'm the owner of the bot. I'm not entirely sure why it couldn't install from the command in a discord server but could over PM

#### What actually happened?

While it works through PM it fails over installing over the only server that it has installed. I'm not sure if that is by design or not so wanted to make this to make sure. Errors when it happens (it's all one but I couldn't figure out how to add in the new line to help separate it): 

`Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]`

`[14/12/2018 04:47] ERROR red on_command_error 369: Exception in command 'cog repo add'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/discordred/Red-DiscordBot/cogs/downloader.py", line 97, in _repo_add
    self.update_repo(repo_name)
  File "/home/discordred/Red-DiscordBot/cogs/downloader.py", line 676, in update_repo
    raise UpdateError(name, *e.args) from None
cogs.downloader.UpdateError: ('26-cogs', 'Error resetting to origin/') ` 

#### How can we reproduce this issue?

This is a pretty new bot with only one other cog installed currently, was attempting to install the insult cog from the 26-cogs repo.

Run `!cog repo add 26-cogs https://github.com/Twentysix26/26-Cogs` from a server that the bot is listed in and note the error, then run the command to the bot over PM.

**Comment by yamikaitou** [comment]
Update git to 2.x

If it is giving that message when used in a server, then it will also be failing for the same reason when used in DM. Odd that it appears to be working even though it isn't

**Comment by suedeyoung** [comment]
Yeah, I was thinking that it might have something that I did until a roommate was able to replicate it as well. Let me upgrade to git 2.x and see what happens. I'll update shortly

**Comment by Twentysix26** [comment]
I can't check now but I don't remember any specific behavior for DMs only, it should fail for both. Perhaps we should mention on the Linux guide(s) about the minimum git version

**Comment by suedeyoung** [comment]
Yeah, I didn't see anything different in the coding for DM to the server but in DMs, it reported as installed without the errors so I'm not sure, I'm still learning as I go! 

It does seem that Centos is behind on the git version on its default system repo (spun up a new VM on our OpenStack and it tried to install 1.8) so I'll have to create another repo for yum once I get home from work in a few hours. 

With this, a note in the guide probably would be a good idea just in case. I didn't notice anything else weird though until I ran into this but just to be safe.

**Comment by yamikaitou** [comment]
If you were following the guide, you should have already installed the IUS repo, so try installing git2u

**Comment by suedeyoung** [comment]
I forgot to update this here! 

So I did have that repo installed but it still did the system provided git for some reason. I went into yum shell and just did a reinstall of the package and it installed the version 2.x now and I was able to confirm that the bot is able to work now through server messages and install. 

Thanks guys!
