### ISSUE TITLE
is_automod_immune raises error on webhook messages

### ISSUE THREAD

**Issue by TrustyJAID** [Cog-Creators/Red-DiscordBot#2336]
# Other bugs

#### What were you trying to do?

Checking `is_automod_immune` inside `on_message` with a webhook message update.

#### What were you expecting to happen?

`is_automod_immune` would return True or False depending on who sent the message.

#### What actually happened?

`is_automod_immune` raised AttributeError: 'User' object has no attribute 'roles' after a webhook message was sent.

#### How can we reproduce this issue?

Check `is_automod_immune` on incoming webhook messages.

**Comment by mikeshardmind** [comment]
This is very easily remedied, the question is should webhooks be considered automod immune though? My 2c is yes since they require manage_server to set up.

**Comment by mikeshardmind** [comment]
I'm going through our other methods which take a message, context, or author to ensure they don't run into the same issue, PR in a moment with them being considered immune from moderation actions, behavior on that can be changed if desired.

**Comment by Tobotimus** [comment]
Resolved by #2337.
