### ISSUE TITLE
[Multiserver audio.py] Changing an Audio server setting removes the other audio server settings

### ISSUE THREAD

**Issue by MattiSony** [Cog-Creators/Red-DiscordBot#234]
When changing the volume or vote setting it removes the other audio settings for the server.

If I do `[p]audioset volume 30` it changes the volume correctly but removes the other settings for the server:

``` json
"SERVERS" : {
        "81753183336009728" : {
            "volume" : 30
}
```

When it should look like this:

``` json
"SERVERS" : {
        "81753183336009728" : {
            "QUEUE_MODE" : true,
            "VOLUME" : 30,
            "VOTE_THRESHOLD" : 50
}
```

Also,(this is not related with the stuff above :P)  everyone is able to use `[p]skip` and  `[p]stop` without the bot starting a vote for it.

**Comment by Twentysix26** [comment]
Fixed in https://github.com/Twentysix26/Red-DiscordBot/commit/4661d9f766c4514a34aae0e1d5bacd66e9de60c3
Will close after merge in cog-changes
Thanks for reporting

**Comment by tekulvw** [comment]
Merged
