### ISSUE TITLE
red-discordbot 3.0.0rc2 has requirement idna==2.7, but you'll have idna 2.8 which is incompatible.

### ISSUE THREAD

**Issue by owocado** [Cog-Creators/Red-DiscordBot#2353]
# Other bugs

#### What were you trying to do?

I was scrolling through my journalctl logs for redbot, and I see this often in my journalctl logs:
```
Dec 29 05:11:40 zeno redbot[24413]: red-discordbot 3.0.0rc2 has requirement idna==2.7, but you'll have idna 2.8 which is incompatible.
Dec 29 05:11:54 zeno redbot[24413]: red-discordbot 3.0.0rc2 has requirement idna==2.7, but you'll have idna 2.8 which is incompatible.
```

Are these log entries safe to avoid? And if not, how do we fix this?

**Comment by Tobotimus** [comment]
To fix the issue (and the vast majority of issues with dependencies) I would recommend doing a reinstall into a fresh virtual environment, you can read about those in the docs. This will not touch your instances or their data.

For that specific dependency (idna), it's unlikely having a slightly more up-to-date version of it will cause problems, but for other dependencies it's a different story, so I would still recommend reinstalling whenever you see that come up. If it always comes up after installing a specific cog, I recommend contacting the cog author.
