### ISSUE TITLE
Asks for protobuf>=3.0.0, which is installed and run errors

### ISSUE THREAD

**Issue by mattiasghodsian** [Cog-Creators/Red-DiscordBot#2355]
I can't figure out how to get Red to run. I followed the GUIDE and still no success.

Python 3.5.4
Pip 18.1
Git 2.20.1
Protobuf 3.0.0

![Installing requiremnts](https://i.imgur.com/fp4pi7s.png)

![Start Red](https://i.imgur.com/qhH62Qh.png)

#### What were you trying to do?

Run RedBot on Windows 10

#### What actually happened?

- Asking for protobuf to be installed when it is.
- Running RedBot returns errors

**Comment by yamikaitou** [comment]
You have Python 3.7 installed, you will either need to uninstall it or create your own batch files that use your 3.5.4 install instead. If you need further support, we recommend joining us on Discord at discord.gg/red
