### ISSUE TITLE
No Audio, 0:00 

### ISSUE THREAD

**Issue by kamixd1337** [Cog-Creators/Red-DiscordBot#2359]
# Other bugs

#### What were you trying to do?

 I was trying to play a song 

#### What were you expecting to happen?

the song to play

#### What actually happened?

the bot joined but it didn't play anything and it was stuck on 0:00

#### How can we reproduce this issue?

I wish I knew. I'm using centos 7, python 3.6.7 and the java that was on the installation page. I found out that it works for root but not on the user I created for the bot

**Comment by Eslyium** [comment]
Have you checked to see which user owns the files? If it isn't the user your using that owns the files you may have to take ownership of them.

**Comment by kamixd1337** [comment]
python and java was installed on root, bot was all installed on user. I removed everything redbot related and reinstalled too. same problem

**Comment by Tobotimus** [comment]
Hi, sorry to hear you had trouble with Audio. Please join the [support server](https://discord.gg/red) and we'll be happy to work through the issue with you.
