### ISSUE TITLE
[Feature Request] Stop music when nobody is in the channel

### ISSUE THREAD

**Issue by idcw0tdisism8** [Cog-Creators/Red-DiscordBot#2360]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

 Okay, so. Everyone knows @aikaterna's bot Cat and any bot would still play music in a channel when nobody is there. This might already be a feature (don't know) but I'd like to have an api functionality to stop the music and have the bot leave the channel when nobody is in the voice channel.

**Comment by aikaterna** [comment]
Use [p]audioset emptydisconnect.

**Comment by idcw0tdisism8** [comment]
Ah, okay.

Just was a random idea I was thinking of.

(like everything is already taken)
