### ISSUE TITLE
[V3 Feature Request] Have setting to use a @mention instead of userid

### ISSUE THREAD

**Issue by idcw0tdisism8** [Cog-Creators/Red-DiscordBot#2361]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

 I was wondering if you guys could implement this into v3 where we could use a user @mention instead of userid, because it's easier to do it on mobile when mods use the bot, etc.

**Comment by Twentysix26** [comment]
Use mentions *where*? In any command? Because that's always been a thing. Any user converter accepts names, nicknames, mentions and user IDs

**Comment by idcw0tdisism8** [comment]
It's not working when I use [p]warn @mention

It just has me do user IDs

**Comment by idcw0tdisism8** [comment]
nevermind, idk why it didn't let me do it before it works now
