### ISSUE TITLE
Add a docs to show people how to 24/7 host their bot for Google Cloud

### ISSUE THREAD

**Issue by Jadon8134** [Cog-Creators/Red-DiscordBot#2368]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [ ] API functionality
- [x] Other

#### Describe your requested feature

 I believe there should be docs for using the Google Cloud 24/7 host, as I got recommended to it to 24/7 host my bot and it goes to a Linux setup and I understand NONE of that Linux stuff, so I'm thinking we should have docs for this.

**Comment by Jadon8134** [comment]
For people who actually know how to do this stuff, don't be redirecting me to a damn thread unless your being 100% sure of it.

**Comment by Kowlin** [comment]
Google Cloud is covered under our Linux installation documentation for both v2 and v3. As a general guidance we have in Red. We will not hold someone's hand while installing Red. If you do not understand these instructions I strongly recommend a public bot that **isn't** self-hosted.

As a side note, being friendly in an issue goes a lot further then being passive aggressive.
