### ISSUE TITLE
[V3 Permissions] Permission hooks don't set state

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2374]
Permission hooks forcibly allowing a command don't set the permission state to allowed, meaning it's impossible to detect that normal behavior was overridden in this case. 

As already shown in voice checks for mod cog, having access to the intended state is important.

It might be worth adding to the enum for allowed/denied by hook (denied by hook too for anyone logging check failures)

**Comment by Tobotimus** [comment]
Resolved by #2375.
