### ISSUE TITLE
[Filter] Log channel for filtered messages

### ISSUE THREAD

**Issue by entchen66** [Cog-Creators/Red-DiscordBot#2377]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

It would be nice to add to the Filter Cog a function, that allow to set a log Channel, where messages will be posted, wich are filtered out by the filterlist.

**Comment by Tobotimus** [comment]
Closing as per discussion in #2443.
