### ISSUE TITLE
Guild blacklisting cog

### ISSUE THREAD

**Issue by manwhodoesbots** [Cog-Creators/Red-DiscordBot#2378]
Hello, I was looking for a guild blacklisting cog and could not find one could anyone give me one? Thanks (v3)

**Comment by aikaterna** [comment]
https://github.com/mikeshardmind/SinbadCogs/tree/v3/guildblacklist

Please visit https://cogboard.red/t/approved-repositories/210 for a v3 cogs list until cogs.red is completed for v3.

**Comment by Tobotimus** [comment]
Also, please use our discord server to ask questions like this in the future.
