### ISSUE TITLE
Warning in chat when track exceeds audio length / automatic skip?

### ISSUE THREAD

**Issue by lumpycustard** [Cog-Creators/Red-DiscordBot#238]
I've got two suggestions that relate to each other. The first is a simple reply from Red advising that a queued song is too long.

![example](http://i.imgur.com/39iBz9a.jpg)

Users will repeatedly queue the same track over and over thinking that the bot isn't working because it responds with "Playing requested link...", but in fact the song isn't being played because it exceeds max length (in my case 10 minutes).

The second suggestion is for the bot to automatically skip a long song and try the next youtube result. For instance, if i type in "[p]play epic sax guy", the first result in youtube is a 10 hour remix, whereas the second link is a 4 minute video. Rather than manually searching youtube myself and locating the proper link, i think it would be good if the bot would skip the first result for exceeding maxlength, and trying the second or third most popular results instead.

The second suggestion isn't quite as important, but would be cool.

Thanks.

**Comment by tekulvw** [comment]
We'd need to store a response text channel/ID

**Comment by tekulvw** [comment]
For now we're gonna be satisfied with a console notification, added in a recent PR. Will revisit later.
