### ISSUE TITLE
[Request] Show ms when using [p]ping cog

### ISSUE THREAD

**Issue by manwhodoesbots** [Cog-Creators/Red-DiscordBot#2386]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

 Cog for ms when using [p]ping

**Comment by PredaaA** [comment]
[Aikaterna's pingtime](https://github.com/aikaterna/aikaterna-cogs/tree/v3/pingtime) cog do that.

Check [here](https://cogboard.red/t/approved-repositories/210) for a list of v3 approved cogs
