### ISSUE TITLE
[Cog] Promotion/demotion cog w/logging

### ISSUE THREAD

**Issue by manwhodoesbots** [Cog-Creators/Red-DiscordBot#2388]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

If someone could make a cog where you do [p]promote @user#0001 [rank] and [p]demote @user#0001 [rank] that'd be great, I'm looking for that. Thank you!

**Comment by aikaterna** [comment]
Please visit the cogboard site at https://cogboard.red for new cog requests. Also, please use our discord server to ask questions like this in the future as we've asked you to do so previously.
