### ISSUE TITLE
Allow redbot-setup to be run in headless mode

### ISSUE THREAD

**Issue by LGACode** [Cog-Creators/Red-DiscordBot#2396]
See https://cogboard.red/t/allow-headless-setup-command/250

Necessary for Docker deployment of v3, otherwise an [Expect script](https://forums.docker.com/t/dockerfile-how-to-answer-install-question-from-application/5240) needs to be written to answer the GUI questions for redbot-setup.

**Comment by LGACode** [comment]
Chat log discussing redbot-setup headless mode with Twentysix: https://pastebin.com/CAC99tpn

**Comment by evan-sm** [comment]
It’s been 3 days since me trying to dockerize redbot. 
Been trying to attach config.json and settings.json, but still get errors.
Run it as “redbot —no-instance” etc

How do I skip “First run configuration master” ?

**Comment by mikeshardmind** [comment]
If you'd like to PR a change required for this, by all means, do so. In the meantime, each open PR for an official docker image (competing methods to handle it) is copying a preconfigured config.json into the image as this use case really isn't applicable to the majority of our users outside of docker currently. I'd recommend you do the same if you can't wait for a solution to be reviewed and up to our standards as an official image.

Refer to #2273 (current frontrunner) and #2163 (a possible alternative) for more details on this.

**Comment by LGACode** [comment]
@wMw9 I have successfully built a container for v3 without headless mode using Expect scripts to answer the interactive install menus. With this method you can create Red containers without filling out and mounting a config.json and settings.json. You can send me a message on Discord **LGA Code#0001** if you want more info.

**Comment by Tobotimus** [comment]
i'm interested in doing this - I've been thinking about changing the way we store each instance's metadata and settings. I think it'd be beneficial for users and developers alike to have a standardized, documented config file in YAML format, one for each instance, which describes things like data path, storage backend details, and maybe some other stuff too. This'd also mean the `redbot` script could be run with a `--config-file <path_to_file>` argument in place of an instance name. The `redbot-setup` script would just generate one of these config files and place it in the usual config directory.
