### ISSUE TITLE
[Mod] Uncaught hackban exception

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2397]
Below follows an uncaught exception to hackban.

![image](https://user-images.githubusercontent.com/10947836/51933846-8a47b300-2402-11e9-8d36-c4e3fa59a032.png)

**Comment by Twentysix26** [comment]
That's fixed with #2164 which is not on pypi yet

**Comment by Kowlin** [comment]
Fixed in #2164
