### ISSUE TITLE
[audio] ffmpeg/avconv thread hangs

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#240]
For some reason the ffpmeg/avconv thread seems to be hanging and stopping the bot from fully dying. Almost always the last log entry is someone searching for a saved playlist but it never loads or gets queued.

**Comment by Kowlin** [comment]
Adding this here to avoid duplicates.

`[s16le @ 00000238cb10e080] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2216 >= 2191`
from #273

**Comment by tekulvw** [comment]
Nothing new to report, closing
