### ISSUE TITLE
[Warnings] [p]warnings dose not allow user mention

### ISSUE THREAD

**Issue by CGDoctor8** [Cog-Creators/Red-DiscordBot#2403]
# Command bugs

[p]warnings
[p]unwarn

#### What cog is this command from?

Warnings

#### What were you expecting to happen?

[p]warnings and [p]unwarn would allow user mention to see past warnings

#### What actually happened?

it only accepts user ID

#### How can we reproduce this issue?

Warn a user then check there warnings 
EX:
$warn @CGDoctor8 Spam
$warnings @CGDoctro8
The following error will be given
`Converting to "int" failed for parameter "userid".`

**Comment by Kowlin** [comment]
Can be most likely resolved with an ``typing.Optional``.
