### ISSUE TITLE
[Help] No help without a docstring

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#2415]
# Other bugs

#### What were you trying to do?

`[p]help <command>`
alternatively, `[p]<command>` with missing required arguments.

#### What were you expecting to happen?

The help embed to show.

#### What actually happened?

Nothing, if the docstring for the command doesn't exist or is empty.

#### How can we reproduce this issue?

```py
class Test(commands.Cog):
    @commands.command()
    async def test(self, ctx, *, required):
        pass
```
`[p]help test` or `[p]test`
No response.

---

```py
class Test(commands.Cog):
    @commands.command()
    async def test(self, ctx, *, required):
        """"""
        # empty docstring
        pass
```
`[p]help test` or `[p]test`
No response.

---

```py
class Test(commands.Cog):
    @commands.command()
    async def test(self, ctx, *, required):
        """
        """
        pass
```
`[p]help test` or `[p]test`
Help embed shows, but with a random line:
[![Screenshot from Gyazo](https://gyazo.com/fa66849952897d686e4c88980318be46/raw)](https://gyazo.com/fa66849952897d686e4c88980318be46)

---

```py
class Test(commands.Cog):
    @commands.command()
    async def test(self, ctx, *, required):
        """this is a docstring"""
        pass
```
`[p]help test` or `[p]test`
Help embed shows normally.

**Comment by mikeshardmind** [comment]
This is still an issue currently. While it can be rectified, I'm of the opinion it isn't useful to special case help for this, and is more useful to our users to require a docstring in commands. 

While I'm not completely made up on this, I don't think empty docstrings should be considered a feature.

A suitable fix would be to enforce this at command add (next to enforcing our subclassed commands) or if we end up special casing this, swapping an empty docstring for `"\u200b"` in embeds, and `""` in code blocks

**Comment by Tobotimus** [comment]
Eh, I think a command with no docstring should still show help, just with the signature and no description. It shouldn't be difficult, I see no reason to ban them
