### ISSUE TITLE
Shared Libraries do not get reloaded during cog update/reload

### ISSUE THREAD

**Issue by sepdotgg** [Cog-Creators/Red-DiscordBot#2419]
# Other bugs

#### What were you trying to do?

Updating a repository which contains a shared library. The shared library contained code changes. When asked whether to reload the cogs from the repo, selected "Yes".

#### What were you expecting to happen?
I was expecting the `Downloader/lib/cog_shared` module to be reloaded as well.

#### What actually happened?

The library files are copied correctly, but the shared library/cog_shared module is not reloaded. The bot needs to be fully restarted in order to pick up changes in shared libraries. This causes  issues if the cogs rely on that updated code until the bot is restarted.

#### How can we reproduce this issue?

1. Repo containing a shared library.
2. Push a change to the shared library.
3. Run a cog update.
4. Select "Yes" when asked whether to reload the cogs.

**EXPECTED:** Libraries in the repo also get reloaded.
**ACTUAL:** Libs are not updated. Bot needs to be restarted in order to reload the shared libs.

**Comment by mikeshardmind** [comment]
Shared libs are marked for deprecation in 3.2, removal in 3.3 due to not having a satisfying answer to this and many other issues they lead to.
