### ISSUE TITLE
Better management of RPC servers

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#2423]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

I'm planning to use the websockets server provided with Red but I found a potential issue, similar to the Lavalink issues.
If a user has multiple instances on his server (which is encouraged with the new launcher), he gets issues with ports, since only one program can use a specific port.
The issue is frequent with Lavalink but can be easily fixed by using the `[p]llset external` setting of the Audio cog, then using one instance's Lavalink server or even running his own server. However, if a cog requires the RPC server, there is no option to prevent the issue of multiple servers on one port.

Possible fixes could be:
- allowing to set his own port for RPC with flags or commands
- running only one RPC server for the whole redbot program, all instances will then connect to that server

I need to be sure that RPC can run on multiple instances before even considering the usage of this in my cogs.

**Comment by mikeshardmind** [comment]
fixed in #2429
