### ISSUE TITLE
Deprecation and removal of Sentry

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2430]
After reviewing and talking about the current status of Sentry I feel that its time to drop the Sentry in favor of our own API that tracks install data such as Python version and Red version.

Reasons on removing Sentry:
 * It generates a huge load on bots with high server or member counts.
 * The results that Sentry gathers are not much of value to us.
 * Not all core members have access to Sentry.
 * We can get more accurate results on bugs with a monthly survey or GitHub issues.
 * Sentry currently leaks errors of 3rd party cogs into our feed.
 * The current library we use is deprecated and porting over to the new library won't easily resolve the current issues we have.

Reasons for our own API:
 * We can more accurately track the information we care about, Such as our install base and Red versions in circulation.
 * Examples of stuff we can track: Cogs loaded, cogs installed, Red version, Python version, OS version

**Comment by mikeshardmind** [comment]
:+1: from me on this.

I don't think we are getting actionable data from Sentry (even if some of what we get *is* useful). More often than not, major issues end up in a support channel, an issue on github, or disclosed personally in cases where we have a relationship with the impacted server.

I dont know that we need to hook any new analytics or logging in, this is opt in as it is, so maybe just a monthly reminder (with an opt out on reminder) that we have surveys (which would need to be in place first) for red hosters.

**Comment by mikeshardmind** [comment]
addendum to above, maybe an extra cog we offer (but dont include in installs) that generates a plaintext report for us to minimize the work hosters need to do to help us, + get us the data in a uniform manner.
