### ISSUE TITLE
[Mod] Set default days of messages to delete for [p]ban

### ISSUE THREAD

**Issue by BurritoWrapped** [Cog-Creators/Red-DiscordBot#2441]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

- Ability to set the default days of messages purged when using the ban command.  This would be able to replicate what Dyno does with regards to banning.

**Comment by Zephyrkul** [comment]
The ban command allows you to specify how many days worth of messages you want to delete along with the ban. See `[p]help ban` (replace `[p]` with your prefix) for details.

**Comment by BurritoWrapped** [comment]
What I’m looking for is a feature to set the default days of messages to delete.

**Comment by Zephyrkul** [comment]
While not a direct solution, #2455 would allow you to set an alias for banning with a specific number of days.

**Comment by Jackenmen** [comment]
Added in #2930
