### ISSUE TITLE
[Streams] Filter out re-runs for Twitch

### ISSUE THREAD

**Issue by crunchprank** [Cog-Creators/Red-DiscordBot#2444]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

I would like to see the feature added to filter out Twitch re-runs when using the `streams` cog that comes with the core Red bot. I run into the issue where everyone in a Discord channel gets mentioned that the streamer is going live, though no indication is given that it is a re-run.

It would be great to see either:

a) The ability to exclude re-runs.
b) A message in the channel announcement specifying that the stream is a re-run and not a live broadcast.

**Comment by EgonSpengler** [comment]
Just leaving a comment to call dibs on this feature, as it's halfway fixed ;)

PR soon!

**Comment by tekulvw** [comment]
Fixed with #2620
