### ISSUE TITLE
[Help] Display default permissions/checks/rules in help

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#2451]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Basically, when running `[p]help <command or cog>`, information from `@checks` should be displayed so it's easy to tell who might have access to a command within seconds in Discord.

Below are a few examples from another bot I've used. You can see that there is a "Requires" section that specifies any required permissions to run a command.

![killbot](https://xnaas.info/img/ColdAggressiveAnchovy.png)

![setnick](https://xnaas.info/img/FearfulOrchidCollardlizard.png)

![deaf](https://xnaas.info/img/HurtfulClumsyBlueshark.png)

The above examples would be fairly obvious even without the "Requires," but you get the idea.

Something like the above added to Red so that if you ran, for instance, `[p]help setstream` you'd know what permissions it looks for by default.

The current situation requires checking code on github or having a dummy user to run `[p]help` with and just guessing and it makes knowing where to even start with the Permissions cog a bit difficult.

**Comment by mikeshardmind** [comment]
I'd prefer a new command to browse default requirements rather than to inject it into the help and it either be inaccurate after modification or overly information dense.

**Comment by ghost** [comment]
That route would be fine, as well. Anything would be an improvement over the way the system currently works.

[NadekoBot](https://nadekobot.me) handles displaying of permissions pretty ok, imo:

![permissions](https://xnaas.info/img/TrustySharpSpringpeeper.png)

The above, again, just being an example. Not trying to say _how_ Red should handle it, just offering some feedback/suggestions. 👍 

Edit: And I definitely think there needs to be a way to see what permissions are required by an `@check` without needing to open open the codebase.

**Comment by Jackenmen** [comment]
This might be possible to do more easily with 3rd-party help formatter after the stuff around that gets done. 

Also image links seem to be dead, so posting this image that at least partially shows what example way of showing permissions was proposed here:
![image](https://user-images.githubusercontent.com/6032823/72562887-bfb40d80-38ac-11ea-8e1e-44c274067ce2.png)

> And I definitely think there needs to be a way to see what permissions are required by an @​check without needing to open open the codebase.

That actually could be quite useful as a separate command, though due to freedom in our permission system, it would not be possible to make such command fully accurate.

**Comment by mikeshardmind** [comment]
I'm freezing this one for many of the reasons already stated by @jack1142 

It's a rather low priority, and we will have other ways to customize this behavior which may work better customized on an individual bot basis. 

As a seperate command, there's actually something I have in my devtools cog which I may look to add to core in some fashion later on for helping explore who can run what where.

**Comment by oodvg** [comment]
2 years later...
