### ISSUE TITLE
Audio playback still busted?

### ISSUE THREAD

**Issue by ParzivalWolfram** [Cog-Creators/Red-DiscordBot#2485]
I have that one bug where audio plays for half a second and then... nothing. Is this still not fixed or is it some other issue?

Reproduced on multiple machines with latest version of vanilla Red, no extra cogs, on Linux and Windows, with FFMPEG and that other one i can't remember the name of right now.

(Should this be on discord.py's repo?)

**Comment by ParzivalWolfram** [comment]
Just updated, problem still persists.

**Comment by Tobotimus** [comment]
I'm not sure on the status of this issue, but I'm afraid V2 is past its EOL and it's quite unlikely to receive any new bugfixes. You're welcome to fork it and fix it yourself if you'd like, you're unlikely to get conflicts with the base repo any more :)

**Comment by ParzivalWolfram** [comment]
I'm on v3, but okay.

**Comment by Jackenmen** [comment]
Our Audio cog in V3 doesn't use FFMPEG. If you have some problems with audio in V3, use #support channel on Red's discord server: https://discord.gg/red

**Comment by Tobotimus** [comment]
Yeah sorry I assumed you were on V2 because you mentioned FFMPEG. Anyway, I agree with Jack, this issue would best be resolved in support :)
