### ISSUE TITLE
Audio Playback - Youtube-DL is completely broken

### ISSUE THREAD

**Issue by ZackRuybal** [Cog-Creators/Red-DiscordBot#2497]
# Command bugs

#### Command name

play

#### What cog is this command from?

audio

#### What were you expecting to happen?

For it not to error

#### What actually happened?

I tried to play some music, and unfortunately it didn't work.

~play never gonna give you up

```ERROR: Signature extraction failed: Traceback (most recent call last):
  File "lib/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
    elif not re.match(r'https?://', player_url):
  File "lib/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function
    'Downloading %s player %s' % (player_type, player_id)
  File "lib/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js
    r'.sig||(?P<sig>[a-zA-Z0-9$]+)(',
  File "lib/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.'
```

#### How can we reproduce this issue?

1. Try to play anything
2. See that the bot joins
3. Read chat to see the error appear

**Comment by yamikaitou** [comment]
Try updating the bot requirements through the launcher

**Comment by ZackRuybal** [comment]
> 
> 
> Try updating the bot requirements through the launcher

Tried that, yeah. Still errors

**Comment by yamikaitou** [comment]
If your youtube-dl is up-to-date and you restarted your bot after updating the requirements, then you just have to wait for them to push an update to fix it. There is nothing we can do to resolve that error message

**Comment by ZackRuybal** [comment]
> 
> 
> If your youtube-dl is up-to-date and you restarted your bot after updating the requirements, then you just have to wait for them to push an update to fix it. There is nothing we can do to resolve that error message

So, as a slight update, the ~yt command works just fine. And, it's magically mended itself. So uh, yeah it can and should be closed.
