### ISSUE TITLE
Feature for the stream alert

### ISSUE THREAD

**Issue by callumcosta2402** [Cog-Creators/Red-DiscordBot#2514]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x ] Command
- [ ] API functionality

#### Describe your requested feature

Hi it would be great with the stream-alert feature if there was a command allowing you to add custom alert titles to the bot so instead of @here, {user} is live! you could add your own custom message to follow the TAG.

**Comment by EgonSpengler** [comment]
Fixed with #2600
