### ISSUE TITLE
Play + Bump Combo Command

### ISSUE THREAD

**Issue by LopezNathan** [Cog-Creators/Red-DiscordBot#2522]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

A combination command of play and bump into one. This allows you to easily add a song to the top of the queue without having to run both `play song` and `bump queue#`.

I accomplished this with a hacky method by copying `play` and utilizing the existing `bump` method.

```
            current_queue_count = len(player.queue)
            bump_index = len(player.queue) - 1
            bump_song = player.queue[bump_index]
            player.queue.insert(0, bump_song)
            removed = player.queue.pop(current_queue_count)
```

This can be seen in the latest commit of my fork : https://github.com/LopezNathan/Red-DiscordBot/commit/6f4206be601f842a0253be8b4d1a434d1af9be55

I can submit a PR with this change, although I feel someone can produce a much cleaner method to accomplish this.

**Comment by mikeshardmind** [comment]
resolved in #3244
