### ISSUE TITLE
[V3 Downloader] Update repo without cogs, update single cog

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2527]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog

- [x] Command

- [ ] API functionality

#### Describe your requested feature

I would want to see `[p]repo update` command which would update repo without updating any cog. This could be useful when new cog is released in repo and you would want to install it without updating other cogs.

From what I've seen to make this change without breaking `[p]cog update` it would be required to know status of the installed cogs (if they are up-to-date) as currently updating cog is based on checking if the repo is up-to-date and if it isn't downloader updates all cogs from that repo. 

Once we know the status of the installed cogs, it probably wouldn't be hard to add functionality to update individual cogs without updating other from the repo, so I thought I add this to the issue as well.

**Comment by Zephyrkul** [comment]
Both of these features already exist with V3.
1) Update repos without updating cogs:
Simply use `[p]cog update` and when it asks you if you want to reload, react with ❎.

2) Update only specified cog
`[p]cog update [cog_name]`

**Comment by Jackenmen** [comment]
1. But in reality cogs are updated and just not reloaded, which means that in next reload or restart of a bot, new version will be used, so it doesn't work as I suggested above.

2. This doesn't update one cog, it updates every cog from the repo this cog is in.

**Comment by mikeshardmind** [comment]
I'd love to see this as part of the core behavior, including pinning cogs to specific versions, but it's not here right now. The underlying behavior of this is also why when an author updates a single cog, every installed and loaded cog shows as updated.

**Comment by Jackenmen** [comment]
Yeah, pinning cogs would go well with these changes too, true. I was wondering, how it should be handled, to make those changes possible. Everything should probably be based on commit ids as by this we could:
- install cog from specific commit
- pin cogs to its current state/commit (maybe also option to upgrade and then pin?)
- upgrade cog to particular commit (which needs to be newer than the one it's currently on)
- obviously upgrade individual cogs
- show cogs that can be updated (this would require using `git diff`, which might not be good performance-wise though, there's also `git diff-index`, which should faster option, but I'm not git expert, so there might still be some better option)

Commit ids for each cog should be kept in conf's `installed` variable as we will need to operate on it in some of those functionalities.
I'm interested in helping with this, I'm not sure, if I'll be able to write all of this on my own, but I surely wanted to write my ideas on what could be implemented as it might be useful for someone else too.

And if someone thinks that something from what I said should be handled differently, it would be better to know that too :D
