### ISSUE TITLE
Enable (or give an option to) warning when a command can't be used in DMs

### ISSUE THREAD

**Issue by ajwsert** [Cog-Creators/Red-DiscordBot#2529]
# Feature request

Bring back the `That command is not available in DMs` message for commands not allowed/available for DMs.

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

For v2, when a command is not allowed/available for DMs were issued in there, the bot would respond with `That command is not available in DMs`, the same doesn't happen with v3.
When migrating to v3 I got myself puzzled by that lack of response and I started assuming the cog was broken, later then I learned the lack of said message is by design to avoid annoyances. I can understand such annoyances in guild/server channels but could we get it back for DMs? Or at least some setting to enable such thing?

**Comment by GamerGirl1995** [comment]
I would love to see that back too

**Comment by Jackenmen** [comment]
This has been fixed by #3057
