### ISSUE TITLE
!song is broken in the last update

### ISSUE THREAD

**Issue by mendess** [Cog-Creators/Red-DiscordBot#253]
http://prntscr.com/b3opqr Queued a playlist and used !song 

http://prntscr.com/b3os65 `!p == !queue` queue a soundcloud link and used `!song`. Same error

http://prntscr.com/b3ot7h this appeared randomly during the play of the song above but since some of it is in portuguese I'm guessing it's a problem on my end (roughly translates to: _your connection timed out_)

http://prntscr.com/b3otgi `!p == !queue` queue a Youtube link and used `!song`. Same error

http://prntscr.com/b3ov9h `!stop`ed and then queued up a YT link.

http://prntscr.com/b3ovxp this appeared randomly during the play of the song above but I guess it just cloudflare being a dick.

[red_log.txt](https://github.com/Twentysix26/Red-DiscordBot/files/264026/red_log.txt)

**Comment by tekulvw** [comment]
Should be fixed with 55531ad

**Comment by Kowlin** [comment]
Fixed and inactive issue.
