### ISSUE TITLE
[Filter] better way to set up Filter and see whats filter's are set

### ISSUE THREAD

**Issue by entchen66** [Cog-Creators/Red-DiscordBot#2537]
# Feature request

Change some stuff in the Filter Cog. More infos below.

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Here are some points, that can be improved:

*Filter adding for a channel should be possible out of any other channel.
*Improve the visability of the filter list.
*list all words with one command that are set up in diferent channel.

**Comment by mikeshardmind** [comment]
This can't really be added as requested. I remember the discussion about this in discord, but am having an issue finding it. The problem comes in where `filter list` as a command then just dumps everything banned into the channel that content doesn't belong in
