### ISSUE TITLE
[Filter] channel words didn't sho up

### ISSUE THREAD

**Issue by entchen66** [Cog-Creators/Red-DiscordBot#2538]
# Other bugs

#### What were you trying to do?

After adding a word to the channel Filter by [p]filter channel add "list of words" the filter word didn't show up in the Filter list.

#### What were you expecting to happen?

Words should be in the list orded by server filter words and channel filter words.

#### What actually happened?

Channel filter word didn't show up. Maybe cant set anymore, see Screenshot.

![grafik](https://user-images.githubusercontent.com/1564726/55288705-bf995e80-53bb-11e9-9fad-f16d77b95824.png)

#### How can we reproduce this issue?

See screenshot.

**Comment by Jan200101** [comment]
seems to be an error in translation

**Comment by Kowlin** [comment]
Error was in the translation, removed the offending translation and updated it. Will be fixed in the next translation release.
