### ISSUE TITLE
Cleanup Between addition

### ISSUE THREAD

**Issue by SharkyTheKing** [Cog-Creators/Red-DiscordBot#2544]
# Feature request

Cleanup between messageID1 messageID2

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature
Adding onto the Cleanup Cog from Core. The ability to cleanup messages that are between two messagsIDs, will be a reliable way to know what message you're deleting rather than trying to just guess with the other commands.

**Comment by NeuroAssassin** [comment]
Wrote a PR to address this issue in #2617.
