### ISSUE TITLE
[p]mute server fails when missing some perms

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#2549]
# Command bugs

#### Command name

`mute server`

#### What cog is this command from?

`Mod`

#### What were you expecting to happen?

Skip channel with missing permissions

#### What actually happened?

Mute process stopped on channel with missing permissions

#### How can we reproduce this issue?

1. Deny `Manage Permissions` or `Read Messages` permission for bot in some channel
2. Mute someone via `mute server`
3. Mute will work only in some channels, instead of all, thats bot has access to.

Insufficient permissions in 1 channel:
![Failed Mute Audit Log](https://Moeka.is-a-good-waifu.com/9dZsMmY.png)
Bot has permissions in all channels:
![Mute Audit Log with Bot's Full Access](https://Moeka.is-a-good-waifu.com/dFBVgk4.png)

**Comment by bobloy** [comment]
This should be resolved due to `mute server` no longer existing

**Comment by Jackenmen** [comment]
Indeed, it should be resolved.
