### ISSUE TITLE
[Docs] Sudo is not installed in minimal installation of Debian

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2564]
It might be worth adding to install guide of Debian, that `sudo` might be missing, if you have minimal installation of Debian on your server and maybe tell how to do install `sudo` or point to some info about it?

Some reference to possible solution: https://unix.stackexchange.com/a/425664

**Comment by tekulvw** [comment]
I don't think it's up to us to provide this information. It's a basic requirement of running minimal Debian and have to deal with this. Worst case a user can just `su` and login as root to install pre-reqs.

**Comment by Tobotimus** [comment]
I'm with Will on this one, it's not our job to premeditate such peculiar environments in our guides. Besides, if the user sees `-bash: sudo: command not found` that should give them enough info to google the solution independently.
