### ISSUE TITLE
[p]ban requires days parameter

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#2582]
# Command bugs

#### Command name

`ban`

#### What cog is this command from?

`mod`

#### What were you expecting to happen?

Ban with reason provided

#### What actually happened?

`Converting to "int" failed for parameter "days".`

#### How can we reproduce this issue?

Use `[p]ban` command with first arg as first word of reason, as stated in help, in example: `[p]ban @Wumpus#0000 Test reason for ban`

![Command help and ban invocation](https://Moeka.is-a-good-waifu.com/8eAXLBA.png)

**Comment by Flame442** [comment]
Right now, you need to specify `days` in order to provide a reason.
This could probably be fixed with `typing.Optional`, it's a question of if it should be fixed or if this is intended behavior.

**Comment by fixator10** [comment]
By docstring for command seems like not intended behavior.

**Comment by tekulvw** [comment]
Fixed with #2602
