### ISSUE TITLE
Audio cogs not loading

### ISSUE THREAD

**Issue by SweggyMelonPie** [Cog-Creators/Red-DiscordBot#259]
I have 9 active cogs with 59 commands wich audio is missing. Tried !load Audio but didn't worked. Don't know if that's the problem but I've tried to installed youtube.dl and this pops up. http://imgur.com/vQ0F6Ms

**Comment by ddday** [comment]
Try asking in the official server, there's generally a better response time there.
https://discord.gg/0k4npTwMvTrXh5va
