### ISSUE TITLE
SSL Error: Windows Server

### ISSUE THREAD

**Issue by deadmanproxy** [Cog-Creators/Red-DiscordBot#260]
whenever I want to add a stream of hitbox, nothing happens.

syntax I used: !streamalert hitbox "channelname"

**Comment by MattiSony** [comment]
Working fine for me, you're not supposed to have quotes around the name.

**Comment by deadmanproxy** [comment]
I'm not writing the channel name in quotes. It was just for clarification. I already asked the support in the Discord channel but they couldn't help me either. For some it's working, for some it's not. It has worked for me for weeks and suddenly stopped. I already did an update and a restart but nothing helped. The console says that the channel is not avaliable or that it has to be a channel name, nickname etc. The Channel exists so far.

**Comment by irdumbs** [comment]
if you could post the errors, that'd help us.

**Comment by deadmanproxy** [comment]
I will post the errors here as soon as I am home!

**Comment by deadmanproxy** [comment]
![discord error](https://cloud.githubusercontent.com/assets/8581756/15353296/b3907dd8-1ce8-11e6-8717-4e279e77cbae.png)

**Comment by deadmanproxy** [comment]
the channel "deadmanproxy" (without quotes) exists but the console keeps telling me this.

**Comment by Twentysix26** [comment]
That error has nothing to do with your hitbox channel.

**Comment by deadmanproxy** [comment]
what else could it be then? Should I consider a complete re-installation?

**Comment by tekulvw** [comment]
Well if we could see the error...notice how the first line of that picture says "During handling of the above error..."? We need the original error, not the error that happened because of the error.

**Comment by deadmanproxy** [comment]
![discord error](https://cloud.githubusercontent.com/assets/8581756/15450263/fd3f926e-1f97-11e6-9a11-2acb7eb7b497.png)

**Comment by deadmanproxy** [comment]
Error solved! Bot is running on WinServer. All I had was to open my stream (hitbox channel) in IE and now the bot works! Thx for ur support!

**Comment by Kowlin** [comment]
Error seems to be related too that Python fails to retrieve the SSL cert by its self. Mostly due to the firewall settings of Windows server.
