### ISSUE TITLE
WorldFlags Trivia, flag of Mauritania labelled as New Zealand

### ISSUE THREAD

**Issue by BlackCowThrower** [Cog-Creators/Red-DiscordBot#261]
During the trivia the flag of Mauritania (https://i.imgur.com/1o8hBla.png) is falsely labelled as the New Zealand flag (https://i.imgur.com/WElCUGn.png)
This is all, I know its not really an issue, but if you are annoying and pernickety like me then its just another thing:)
Hardly a complex fix, but thanks anyway

**Comment by Kowlin** [comment]
Fixed in https://github.com/Twentysix26/Red-DiscordBot/pull/267. Awaiting acceptation of PR
