### ISSUE TITLE
Update timer for Youtube Playlists

### ISSUE THREAD

**Issue by jonyroda97** [Cog-Creators/Red-DiscordBot#263]
The Youtube Playlists should have a timer that for time to time they look if the playlist have more videos and then update the playlist with them

Edit: in the right order of course :smiley:

**Comment by jonyroda97** [comment]
@

**Comment by jonyroda97** [comment]
wrong button :neutral_face:

**Comment by tekulvw** [comment]
Oh boy, this is so low on the totem pole of things to do for audio that I'm gonna close it for now. You can just add the playlist again and it should overwrite the old one.

**Comment by jonyroda97** [comment]
Yes I'm adding it again from week to week.
It's just an idea to make the bot a little more automatic.

EDIT: Shouldn't it be opened till it's done?

**Comment by tekulvw** [comment]
This really isn't something that's super important to add to audio...however you could probably accomplish what you want with my scheduler cog, squid repo

**Comment by jonyroda97** [comment]
OH... That would done the thing :smiley:

It's not about the importance but just for you to know that it's a thing that would be good to add and so you don't forget it.
Label it "Low Priority" or something.
