### ISSUE TITLE
resume command should rejoin voice channel

### ISSUE THREAD

**Issue by zinefer** [Cog-Creators/Red-DiscordBot#264]
The resume command appears to throw a `Not voice connected in this server.` instead of reconnecting to the voice channel.

**Comment by Kowlin** [comment]
This won't work because the bot will not have a song dedicated to said server. Thus the resume command will not be used.

**Comment by irdumbs** [comment]
I'm assuming you had some playlist going, you `!pause`d it, waiting for > 5 minutes, the bot left the voice channel, then you tried to `!resume`
correct?

**Comment by tekulvw** [comment]
Closing because of lack of communication
