### ISSUE TITLE
Fedora support

### ISSUE THREAD

**Issue by Thodoris1999** [Cog-Creators/Red-DiscordBot#2648]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Can you guys support Fedora Linux?

Thanks

**Comment by yamikaitou** [comment]
Fedora is already supported (as is almost all Linux distros). If you have an issue installing it from our guides, hop into our Discord server and ask in #support

**Comment by Jackenmen** [comment]
While there's no Fedora guide in docs for stable version, you can use guide for CentOS instead. That section already got renamed to indicate it's also for Fedora, in develop branch, it's just not showing in docs for stable version.

**Comment by Thodoris1999** [comment]
Ok, I'll try it later! I will remove this issue when I get it to work.

**Comment by Thodoris1999** [comment]
On your docs I went straight to the instructions for fedora. I saw yum and thought I Red is not maintained on dnf because fedora no longer supports yum.

Had I just seen what the dependencies are and installed them myself, I would have not been confused. It works now, it was a misunderstanding on my part.

I will close the issue now.

**Comment by Jan200101** [comment]
its worth mentioning that since the release of dnf yum has been a symlink to dnf
