### ISSUE TITLE
[Streams] Specifically YouTube Alerts

### ISSUE THREAD

**Issue by Menteroth** [Cog-Creators/Red-DiscordBot#2655]
#### What were you trying to do?

Add YouTube channels for alerts. Added three of them which is the current list at the moment. One of the channels is never used. Just added for testing.

#### What were you expecting to happen?

For the bot to alert when channel goes live with a nice embed.

#### What actually happened?

The alerts appear totally random several times a day and all at once, even if channels aren't or have never been live. https://i.imgur.com/aMSrtUK.png

#### How can we reproduce this issue?

1. Add channel(s) to alert.
2. Reload `streams` cog and see the same issue as when waiting for an alert.

#### Sidenote

I also get this sometimes when trying to add channels or using `[p]youtube <channel>`.
"Something went wrong whilst trying to contact the stream service's API."

Similar issue: #2466

**Comment by Jackenmen** [comment]
Since the time issue was made, there have been a few changes to the way we update streaming status for YouTube channels and this should no longer happen. Let me know if that's not true.
