### ISSUE TITLE
[Docs] Java 8 cask for Mac installs does not exist any more

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#2662]
# Other bugs

#### What were you trying to do?

Helping an install in support. Mac user was going through the docs and installing Java 8 via brew per our instructions.

#### What were you expecting to happen?

For Java 8 to be installed.

#### What actually happened?

The java8 cask has been deleted due to Oracle's licensing changes from April of 2019.

#### How can we reproduce this issue?

Try to run `brew cask install java8` on a Mac.

**Comment by Kowlin** [comment]
Fixed in #2663
