### ISSUE TITLE
[RFC] Core red API bot.send_to_owner

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2665]
We have more and more specific information which we want to get to owners, and with team users, and co-owners, we need a better way than just fetching the owner and trying to send.

I'm proposing a new method on the bot, `send_to_owner`. This will behave *like* `discord.abc.Messagable` with the args it takes, except it will do the following:

- Send to the owner and co-owner, owner only if the owner does not have a discrim of `#0000` (Currently, team users and webhooks are the only things with that as a discrim, users can't have it)
- Send to a configured channel(s)

Additionally, this would come with settings to opt out of DMs specifically from this for people who choose to only have these message in a configured channel.

### Things in the bot (currently) which should use this on initial implementation if added:

- contact
- update notifications

**Comment by Kowlin** [comment]
I agree with this, especially with the use of Discord Developer teams.
