### ISSUE TITLE
[Help command] Future plans 

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2667]
The help redesign in #2628 is not the end of our improvements to help.

There are some default behavior changes in it. While the defaults have changed, there should still a setting added for showing that commands exist or not

Additionally, there are some other planned improvements:

- [x] Exposing a setting for using a menu, rather than paginating output.
- [ ] Adding help attribute use for cog developers, notably: (with more to consider)
  - [ ] Allowing them to set a max page size for their cog/groups lower than the bot
  - [x] (Get cog creator input for other potential useful opts)
- [ ] An API for registering additional 3rd party formatters with the bot and a setting for which formatter to use.  
- [x] Delete delay settings
  - Consider this as a per guild or per channel, not global?
  - Exclude DMs?
- [ ] Guild specific Settings
- [ ] Better whitespace handling
- [ ] Longer Timeout default + customization of timeout

**Comment by aikaterna** [comment]
For the menu style help, could a longer timeout for buttons be considered? In talking with Preda, Kenny, and Trusty it seems that all of us have gotten messages from our bot users at some point asking for longer timeouts on the menu reactions.
