### ISSUE TITLE
!play doesn't work on Linux

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#268]
Stopped working out of sudden. Works fine on Windows, but not on Ubuntu.
Bot joins channel fine when I run a !play command, but doesn't start playing anything. Even using !skip makes the bot say it's not playing anything. Here are a few errors I'm getting.

`[20/05/2016 18:56] ERROR audio _join_voice_channel 488:
Traceback (most recent call last):
  File "/root/Red-DiscordBot/cogs/audio.py", line 486, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2576, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Ignoring exception in on_message
Traceback (most recent call last):
  File "/root/Red-DiscordBot/cogs/audio.py", line 486, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2576, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 244, in _run_event
    yield from getattr(self, event)(_args, *_kwargs)
  File "red.py", line 71, in on_message
    await bot.process_commands(message)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 611, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 384, in invoke
    yield from injected(_ctx.args, *_ctx.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 47, in wrapped
    ret = yield from coro(_args, *_kwargs)
  File "/root/Red-DiscordBot/cogs/audio.py", line 1096, in play
    await self._join_voice_channel(voice_channel)
  File "/root/Red-DiscordBot/cogs/audio.py", line 489, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel")
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel
Task was destroyed but it is pending!
task: <Task pending coro=<_run_event() done, defined at /usr/local/lib/python3.5/dist-packages/discord/client.py:241> wait_for=<Future pending cb=[Task._wakeup()]>>`

**Comment by jaw3l** [comment]
I have the same issue, bot is responding all commands  but I don't get any kind of output (like error etc.). Using last version of red and discord.py

**Comment by Kowlin** [comment]
Ensure that you have ffmpeg installed, To find out on how to do it. Check out the following guide.
https://twentysix26.github.io/Red-Docs/red_install_linux/#repositories
https://twentysix26.github.io/Red-Docs/red_install_linux/#ffmpeg

**Comment by JonasBonno** [comment]
I am also having problems with playing YouTube. I have tried new install on Ubuntu and Alpine. Same result. I am sure that ffmpeg is installed. All commands work except not working with YouTube. Playlist not working ether. Bot joins channel but never starts playing. No error outputs. Anyone found the problem?

**Comment by franc-ist** [comment]
Is opus installed? A mistake in the docs meant that is was removed accidentally from the linux guide @JonasBonno

**Comment by JonasBonno** [comment]
How do I install opus - apt-get install opus or is it a option/module for ffmpeg? @FishyFing

**Comment by franc-ist** [comment]
`sudo apt-get install libopus-dev -y`

**Comment by JonasBonno** [comment]
It is already install. I am running it inside a alpine docker container. See code here: https://github.com/JonasBonno/dockerfiles/blob/master/discordbot/1.4

Do you have any ideas? @FishyFing

**Comment by franc-ist** [comment]
What version is your python. Also, join the [support server](https://discord.gg/0k4npTwMvTpv9wrh)

**Comment by JonasBonno** [comment]
Version: 3.5.1 
I have joined your support server.

@FishyFing

**Comment by ghost** [comment]
Installing libopus fixed the issue for me. Thanks.

**Comment by JonasBonno** [comment]
Version: 3.5.1 
I have joined your support server. There we found my issue. Thanks :)

My issue was that I have a firewall and I only allowed common ports. 
When I opened up for e.g. all ports to frankfurt306.discord.gg and london366.discord.gg, then my bot was able to play.

@FishyFing

**Comment by Kowlin** [comment]
@JonasBonno keep in mind that the server the bot will connect on will change a huge amount of times. This is due to that you don't have a dedicated server assigned. Keep this in mind while doing your firewall.

(Closing this issue. The issue creator has fixed his problem. If you have another problem feel free to open another issue.)
