### ISSUE TITLE
Different filter behaviour

### ISSUE THREAD

**Issue by DevilXD** [Cog-Creators/Red-DiscordBot#2687]
# Other bugs - Filter cog

The v3 version of filter used `p in content` to check if a filtered word is contained within a message. In v3.1, a `\b{re.escape(w)}\b` regex pattern is used for this instead.

This means that in the old filter behavior, for example, adding `tard` as a filtered word would cause messages with both `tard` and `retard` inside them to be filtered. In the new version, because of the `\b` tokens inclusion, `retard` is no longer filtered.

This change of behavior wasn't stated anywhere. The doc string for the `[p]filter` command says: "Add or remove **words** from server filter.", implying that only whole words should be added and filtered, and not only parts of the words, which further implies that this was a bug fix then?

Was this intended? If so, could there be a mention about this behavioral change stated somewhere? I didn't expect it to change.

**Comment by mikeshardmind** [comment]
This was an intentional fix. See #2262 and #2292

If the prior behavior is important to you, please make a feature request for a separate command to configure string in message things in filter as well.
