### ISSUE TITLE
Change permissions from manage_server to administrator

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#269]
The Administrator permission is usually a higher up one then the manage_server one. And it also gives us a nice little disposable permission for newer commands that can have big impact on a server.

![](http://i.imgur.com/ygaovr8.png)

**Comment by Redjumpman** [comment]
+1 This is a good idea.

**Comment by franc-ist** [comment]
+1

**Comment by ddday** [comment]
Why +1 when you can give a thumbs up?

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/11dddc4e4021d54cdf5f22a5f6c8e662ce7ea6c3
