### ISSUE TITLE
CustomCommand on_message listener error

### ISSUE THREAD

**Issue by DevilXD** [Cog-Creators/Red-DiscordBot#2697]
# Other bugs

The CustomCommands cog throws an error into the console if a message processed in the `on_message` listener happens to start with a prefix and a space following right after.

#### How can we reproduce this issue?

1. Have CC loaded
2. `[p]cc add simple bugtest This command is for bug testing only!`
3. `[p] test` (notice the space after the prefix)

Haven't tested if this is still the case without any CC added. Traceback: https://i.imgur.com/SQdk8ot.png

Python 3.7.1, Red 3.1.1, D.py 1.0.1

**Comment by mikeshardmind** [comment]
fixed in #2739
