### ISSUE TITLE
[Audio] Child folders within playlist folder

### ISSUE THREAD

**Issue by Dommage** [Cog-Creators/Red-DiscordBot#270]
is there a way to have the bot to play local playlist even if there's folder inside.

Actually if I copy a folder to Red-DiscordBot/data/audio/localtracks it won't work if there's folder inside the folder

Thanks

**Comment by Kowlin** [comment]
As a example, your `bot/data/audio/localtracks` folder should look like this. If the bot cant find the folder. Try reloading audio or restarting the bot.

![](http://i.imgur.com/wenlsgu.png)

**Comment by jonyroda97** [comment]
I think that it would be useful what @Dommage says.
For example: have a folder per type of music and in there per band

**Comment by Dommage** [comment]
I mean if you put a folder inside one of those...

**Comment by Kowlin** [comment]
Currently there is no way to do that.

**Comment by tekulvw** [comment]
it'd be as simple as using walk() instead of listdir() iirc, thoughts @Twentysix26 ?

**Comment by tekulvw** [comment]
Moving to #623
