### ISSUE TITLE
Complete bot translation

### ISSUE THREAD

**Issue by lucasvperini** [Cog-Creators/Red-DiscordBot#2703]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

Hey!

It's possible to translate 100% of the bot messages? Or i can download the repo and compile it again? If so, how do i compile?

Thanks!

**Comment by aikaterna** [comment]
You can contribute at https://crowdin.com/project/red-discordbot if you are fluent in another language. Translations are automatically added to the bot as we release new versions.

**Comment by lucasvperini** [comment]
There's a way to translate/edit messages style on the source then compile it?

Thanks.

**Comment by Jackenmen** [comment]
I would suggest doing everything on crowdin and wait for next release of redbot, which will include everything you added there.
However, if you don't want to wait, you can download all language files in zip file from crowdin and paste `cogs` and `core` folders into folder one level higher than what's shown on Core Path, when you run `[p]paths` command (`[p]` is your prefix).

So for example, if your `[p]paths` output is:
```
Install Path: /home/ubuntu/red-data/cogs/CogManager/cogs
Core Path: /home/ubuntu/red-venv/lib/python3.7/site-packages/redbot/cogs
```
You should copy `cogs` and `core` folders from downloaded language archive into `/home/ubuntu/red-venv/lib/python3.7/site-packages/redbot` folder (if system ask you if you want to replace files, you should agree to replace all files)

If you will need more help I suggest you to ask on #support channel on our discord server: https://discord.gg/red

**Comment by lucasvperini** [comment]
Any news on this?

**Comment by Jackenmen** [comment]
What news do you want exactly? o.O

**Comment by Kowlin** [comment]
There isn't any news on this. Our translations are updated per release from Crowdin to GitHub. I highly encourage you to translate on Crowdin if you want to help out with the translation effort.

**Comment by lucasvperini** [comment]
I guess i wasn't very clear... Sorry.
I want to customize every part of the bot, title, every messages, etc..
I can do it and compile the source on my own? Or something like that?

**Comment by mikeshardmind** [comment]
We don't generally support this. If you want to contribute a translation, you can see the above portions. For changing every message outside of translation, there are no plans to support this. Many of red's messages are important, including information on how things work. If you have found any messages unclear, feel free to suggest an improvement to them.
