### ISSUE TITLE
Modset deletedelay on, wildcard after prefix?

### ISSUE THREAD

**Issue by itsnaeng** [Cog-Creators/Red-DiscordBot#2705]
# Other bugs

#### What were you trying to do?

Normally type to others but if you happen to have your [p] in the beginning of the sentence, the bot thinks it's a command.

ex, `[p]... why did you do this?` (This will actually auto-delete the entire line? even though it's not a command)
ex, ``[p] ... why did you do this?` (The bot doesn't seem to remove it since it has a space)

#### What were you expecting to happen?

Not to delete the message when sent to the channel.

#### What actually happened?

If you have the prefix in the front and did multiple of dots, or people tend to troll with like `[p]fakecommand` it'll just auto-delete the message + they tend to spam the log chanels with it.

#### How can we reproduce this issue?

`[p]anythingwithoutaspace`

**Comment by mikeshardmind** [comment]
I can't replicate this behavior with core cogs on 3.1.1, 3.02, or the current dev build. 

If you have the output of `[p]info` and `[p]cogs` I can take another look, but this doesn't appear to be caused by modset deletedelay.

**Comment by itsnaeng** [comment]
This was done on the Red v3.0.2, with Python 3.6.8.
There's no additional cogs used just the core bot itself with non-existence commands on Red.

Should I make a test server for you Mike?

**Comment by mikeshardmind** [comment]
After double checking in a fresh environment( for each), I was able to replicate this on 3.0.2 I could not replicate this on 3.1.1 or on the current development build.

**Comment by itsnaeng** [comment]
Will there be a hotfix for this, unless it's not a bug.

**Comment by mikeshardmind** [comment]
I haven't heard any support from other devs on having another backport to 3.0.x (Myself included).

The recommended course of action would be the update to latest, or if that's not feasible for you right now, to disable the delete delay until such time as it is.
