### ISSUE TITLE
[HelpFormatter] menus blocking settings preview

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#2712]
# Other bugs

#### What were you trying to do?

View current `[p]set` settings

#### What were you expecting to happen?

`[p]set` shows help for `[p]set` and current bot's settings

#### What actually happened?

`[p]set` shows only help for ~15 seconds or until helpmenu is closed manually, then shows current settings

#### How can we reproduce this issue?

1. Enable `[p]helpset usemenus`
2. Use `[p]set` cmd or `[p]modset`

![gif](https://Moeka.is-a-good-waifu.com/8Uj5YPf.gif)

**Comment by mikeshardmind** [comment]
The reason this happens is pretty obvious...

I see a few options here.

1. Don't change the help behavior further, just send the settings first.
    - This has a downside that people need to consistently do this.
    - It's a change in output formatting from what people are used to
2. Detatch the menu into a task in the help formatter itself.
    - We could in theory end up with different ordering each time.
        - Could probably circumvent the above by detatching and sleeping a 10th of a second, but this isn't great.
        - EDIT: a better solution (here) would be manually send the first page, then use the menu in a task.
    - This changes the API of the help formatter again, as currently it wont return until finished.
        - EDIT: I'm okay with this change, given the return type is always None, and can still be assumed to mean "help has been sent" 
    - (EDIT:) This is my current preference
3. Detatch the menu into a task in the few groups which use it this way
    - This is my personal pick (Edit: Was)
    - The "having to do it yourself" part is already implied by using `autohelp=False` for these.
    - Does add some extra work for 3rd party devs emulating the design. 
        - This would mean we have a how to reference in core code though
4. Stop sending the settings when used like this and add view commands for settings.
    - Clear behavior without design concerns
    - Does add another command
