### ISSUE TITLE
[Core] Set colour returns wrong link.

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2715]
# Command bugs

#### Command name

``help set colour``

#### What cog is this command from?

Core

``Set colour`` returns an outdated help link that doesn't exist anymore.

![](https://cdn.discordapp.com/attachments/387398816317440000/580167443788595200/unknown.png)

This should either link to our own documentation whereby we can reasonably ensure compatibility to ensure that this never happens again, or link to the new Discord.py documentation.

**Comment by retnikt** [comment]
this should be closed, no?
