### ISSUE TITLE
[Streams] Rerun feature broke Mixer

### ISSUE THREAD

**Issue by yamikaitou** [Cog-Creators/Red-DiscordBot#2724]
# Command bugs

#### Command name

Mixer Stream Alerts

#### What cog is this command from?

streams

#### What were you expecting to happen?

Automated posting of live streamers

#### What actually happened?

Nothing

#### How can we reproduce this issue?

Add a Mixer user who is live and wait for the zero messages to appear. But, if you remove `, is_rerun` on Line 548 of streams.py, it works as expected. It seems like #2620 did not account for other streaming platforms.

This likely also occurs with other platforms, I only diagnosed Mixer

**Comment by mikeshardmind** [comment]
This should be fixed with #2679 + #2699 , and should be included as part of 3.1.2

**Comment by yamikaitou** [comment]
It is not, `check_online` is only called when someone manually checks if a stream is online, not when using streamalert to automatically post live streamers, that uses `check_streams`

**Comment by palmtree5** [comment]
That feature is being removed in #2433 anyway because of the migration over to the "new" Twitch API which doesn't show anything regarding reruns
