### ISSUE TITLE
Filtering issue

### ISSUE THREAD

**Issue by GamerGirl1995** [Cog-Creators/Red-DiscordBot#2740]
#### What were you trying to do?

Someone changed his name to Night and it filtered the name because the word Nig is on the filter list. so basically it shouldn't filter the persons name because it was Night and not Nig.

Now this issue is solved in the filtering system when it comes to proper chat in a channel, where someone can say for example assistance but not ass when ass is on the filter list. but assistance consisting the word ass is possible. (like i stated that works correctly)

however if you do the same for nicknames (!filter names) it will filter the name if a word consists of the word that is in the filter list. so Nig is filtered and night is not. however changing the name to Night will filter that name because Nig is in Night.

Hope that made sense.

#### What were you expecting to happen?

For nickname Night not be filtered because that actual word is not on the filter list.

#### What actually happened?

The word night got filtered because the word Nig which is part of Night is on the filter list.

#### How can we reproduce this issue?

1. !filter add Nig
2. !filter names (to enable the filtering names option)
3. Try to change your name to Night
4. See how the bot changes your name because nig is on the list and part of the word night.

**Comment by GamerGirl1995** [comment]
any idea how to fix this? as its a rather big issue on the company discord.

**Comment by mikeshardmind** [comment]
I'd suggest turning off name filtering until it's fixed. It will be fixed when someone has the time to fix it.
