### ISSUE TITLE
[Permissions] Possible inheritance issue leading to ignoring of @checks

### ISSUE THREAD

**Issue by MeatyChunks** [Cog-Creators/Red-DiscordBot#2742]
This seems to have been introduced with 3.1.

Steps to reproduce:

- Install a cog (I used adventure)
- Load permissions and adventure
- `[p]permissions setdefaultserverrule deny Adventure` (capital A so it denies the whole cog)
- `[p]permissions addserverrule allow Adventure #channel`
- Normal users are now able to use commands that include admin `@checks`, adventureset in my case.

It doesn't seem like this is intended behaviour. I'm sure permissions respected checks from file previously. With this behaviour I'd have to go through and allow each command of the cog manually, leaving out the Admin commands.

here is my ACL output for the server showing it's set to a channel ID, just to be safe:
```yaml
COG:
  Adventure:
    default: false
    567319948146245642: true
```

**Comment by mikeshardmind** [comment]
This isn't a bug, this is the behavior of permissions. You just allowed the entire cog to anyone using it in that channel. See https://red-discordbot.readthedocs.io/en/stable/cog_permissions.html for more info.
