### ISSUE TITLE
[Help] UseMenus server specific/toggle for DM's

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [Cog-Creators/Red-DiscordBot#2744]
# Feature request
- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature
Is there any chance the help menus could be toggled per-server and for DM's, so help could be menu's in one server, but normal in another, and then have an option for if it's sent to DM's a toggle for if it shows all pages or if it shows as a menu.

**Comment by Ianardo-DiCaprio** [comment]
Or if it would be easier to allow make it so help uses menus, but can still be toggled to go to DM's instead of posting it to the server.

**Comment by mikeshardmind** [comment]
I'll look into some further customization here, but this is unlikely to happen in the short term. I'd like to support a few more options on this, but there are a few internal changes we should work on before this to make this as smooth as possible.

If included, it will likely be in version 3.2 or higher. This would happen at or around the same time as some other planned additions for help aimed more towards creators having customization options as well.

**Comment by Ianardo-DiCaprio** [comment]
Basically, when this is done, I'd like to be able to toggle help to:

1. Be able to toggle help on/off on servers (when off, still show help for when you do a command without the arguments or do `[p]help <command>` and if it's off, and you just do `[p]help` it get sent to DM's).

2. Be able to toggle help menu's on/off on servers.

3. Be able to toggle help menu's on/off in DM's.



Currently if you use a command without arguments, that for instance sends 2 different help embeds, with max pages 0 and menus off it sends one on server and 1 to DM's which I find annoying.

**Comment by mikeshardmind** [comment]
Replaced by #2667
