### ISSUE TITLE
[Audio] Appending tracks to playlist requires connecting to vc

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2772]
# Command bugs

#### Command name

`[p]playlist append <playlist_name> <url>`

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Append tracks without having to connect to voice channel

#### What actually happened?

Message "Connect to a voice channel first."

#### How can we reproduce this issue?

Run command from "command name" section without being in voice channel.

**Comment by Jackenmen** [comment]
Looks like the same problem applies to youtube playlists

**Comment by aikaterna** [comment]
To generate Track objects, audio must have a valid Lavalink player. Players are only able to be generated when connected to a voice channel. This is intended and there is not a way to append tracks without being connected to a voice channel.
