### ISSUE TITLE
ModuleNotFoundError: discord.utils due to polluted environment

### ISSUE THREAD

**Issue by adamjorr** [Cog-Creators/Red-DiscordBot#2773]
# Other bugs

I've fixed the issue for myself but posting this here if anyone experiences a similar problem. Tagging @mikeshardmind since he commented on a PR comment I made earlier #2769 

After updating Red yesterday, somehow my installation broke and the bot couldn't launch.

Apparently there is a "discord" package installable from pip in addition to "discord.py". Both were installed on my system for some reason and I suspect this was causing conflicts with finding the right modules. This probably would've been mitigated with a virtual environment in the first place.
Uninstalling `discord` and installing `discord.py==1.0.1` fixed it.

#### What were you trying to do?

Update + run red

#### What were you expecting to happen?

launcher to launch

#### What actually happened?

ModuleNotFoundError

```
Jun 16 00:17:11 horace redbot[14943]: Traceback (most recent call last):
Jun 16 00:17:11 horace redbot[14943]:   File "/home/redbot/.local/bin/redbot", line 6, in <module>
Jun 16 00:17:11 horace redbot[14943]:     from redbot.__main__ import main
Jun 16 00:17:11 horace redbot[14943]:   File "/home/redbot/.local/lib/python3.7/site-packages/redbot/__main__.py", line 13, in <module>
Jun 16 00:17:11 horace redbot[14943]:     from redbot.core.bot import Red, ExitCodes
Jun 16 00:17:11 horace redbot[14943]:   File "/home/redbot/.local/lib/python3.7/site-packages/redbot/core/__init__.py", line 6, in <module>
Jun 16 00:17:11 horace redbot[14943]:     from .config import Config
Jun 16 00:17:11 horace redbot[14943]:   File "/home/redbot/.local/lib/python3.7/site-packages/redbot/core/config.py", line 9, in <module>
Jun 16 00:17:11 horace redbot[14943]:     from .data_manager import cog_data_path, core_data_path
Jun 16 00:17:11 horace redbot[14943]:   File "/home/redbot/.local/lib/python3.7/site-packages/redbot/core/data_manager.py", line 10, in <module>
Jun 16 00:17:11 horace redbot[14943]:     from discord.utils import deprecated
Jun 16 00:17:11 horace redbot[14943]: ModuleNotFoundError: No module named 'discord.utils'
```

#### How can we reproduce this issue?

unsure, pollute your environment

**Comment by Rapptz** [comment]
Sorry, I know this issue was closed but I wanted to mention something.

I own both the `discord` and `discord.py` packages on PyPI. The `discord` package doesn't have version meta data so it can't be reliably used in e.g. requirement specifications. It just installs the latest `discord.py` package, which I believe was written to be `>=1.0.1`.

**Comment by Tobotimus** [comment]
Thanks @Rapptz, yeah I'm pretty sure @adamjorr having the `discord` package installed is a red herring. The `no module named discord.utils` issue arose when we stopped vendoring discord.py and started listing it as a dependency. Something to do with pip requiring users to do  `--force-reinstall`, just one of those weird pip bugs.

**Comment by adamjorr** [comment]
That explains it, thanks for confirming I'm not crazy :rofl:
