### ISSUE TITLE
Spotify Support

### ISSUE THREAD

**Issue by LennoxP90** [Cog-Creators/Red-DiscordBot#278]
Not necessarily an issue but it would be great for spotify integration Thanks, keep up the good work

**Comment by ddday** [comment]
spotify is a closed module. Therefore if you don't want the developers to be imprisoned then it won't be integrated any time soon.

**Comment by Kowlin** [comment]
Closing this. (From what I can gather) The Spotify API does not support playing music.

**Comment by irdumbs** [comment]
this issue didn't say anything about 'playing music'

even if we assume that it is, it's still very possible to play music from info given by spotify.
reopening?

**Comment by Kowlin** [comment]
You know ffmpeg doesn't support downloading from external sources. Without help that is. But I think this is also against the ToS from Spotify. We're opening a whole bunch of legal issues is we try this...

**Comment by Kowlin** [comment]
In some way already. But there are API end points to gather playlists and so on.

**Comment by tekulvw** [comment]
It's a major legal issue, Danny already had this discussion. Closing and keeping closed.
