### ISSUE TITLE
[Core] Adding Team support

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2781]
Discord has recently added support to pull the team members via the endpoint ``GET discordapp.com/api/v7/oauth/applications/@me``. (see sample output below) I'm interested in adding this behavior into Red but I'm now sure on how ever I want to go at it. So far I've come up with 2 possible ideas to allow team support.

1. We directly add in all team members to the ``co_owners`` field within Red at boot up, or
2. Once the bot has the ``--team`` flag enabled, we will then add in the team members to the ``co_owners`` field. This will ensure that there is an explicit opt-in for team support.

Beyond the first issue of adding in new co-owners to teams. We'd also need to update the ``info`` command to reflect that its being hosted on a team. Which we can now do. Such as listing the "Instance owned by" field as "Team Red-DiscordBot"

EDIT: Forgot JSON sample >.<

```json
{
    "description": "",
    "name": "Lars",
    "team": {
        "owner_user_id": "142006827155062784",
        "members": [
            {
                "membership_state": 2,
                "team_id": "532230556675604482",
                "user": {
                    "username": "Tense",
                    "discriminator": "6198",
                    "id": "96742984233525248",
                    "avatar": "780c330743cc20ec14458383e9af037e"
                },
                "permissions": [
                    "*"
                ]
            },
            {
                "membership_state": 2,
                "team_id": "532230556675604482",
                "user": {
                    "username": "Kowlin",
                    "discriminator": "2536",
                    "id": "57287406247743488",
                    "avatar": "a_a3b9a3de2c74bfb0cb138e99c9b08a89"
                },
                "permissions": [
                    "*"
                ]
            },
            {
                "membership_state": 2,
                "team_id": "532230556675604482",
                "user": {
                    "username": "Flak",
                    "discriminator": "0001",
                    "id": "167354221190971392",
                    "avatar": "06834be37c453d1dd08cccd22fbae411"
                },
                "permissions": [
                    "*"
                ]
            },
            {
                "membership_state": 2,
                "team_id": "532230556675604482",
                "user": {
                    "username": "Soulrift",
                    "discriminator": "0001",
                    "id": "142006827155062784",
                    "avatar": "a_42055826f952fd72e62aacf7d53d54e9"
                },
                "permissions": [
                    "*"
                ]
            }
        ],
        "id": "532230556675604482",
        "name": "Fortnite Moderators",
        "icon": "799e3fdc1c6df26fd321d181129e5648"
    },
    "bot_require_code_grant": false,
    "summary": "",
    "verify_key": "a601f0b5001042125f06ccdaa99f5cfb16163dbe09a98ee8aec512c0a489048c",
    "owner": {
        "username": "team532230556675604482",
        "discriminator": "0000",
        "flags": 1024,
        "id": "532230556675604482",
        "avatar": null
    },
    "bot_public": false,
    "id": "575017721797017644",
    "icon": null
}```

**Comment by Zephyrkul** [comment]
I'd assume d.py would figure out team support upstream, and things like the bot's is_owner coro would be updated to reflect this new feature. We should see how d.py handles this, since it could mess up ratelimits and the like if we access the API directly, and since it's likely to include team support in methods our bot class inherits or calls.

**Comment by Rapptz** [comment]
Support for teams will probably not be backported to 1.2.x (since it requires adding new attributes). It'll probably be in 1.3. 

I was thinking of adding it in a patch bump so it'll be in the 1.2.3 version that is currently blocking #2769 but since it murks up the versioning scheme I decided against.

**Comment by mikeshardmind** [comment]
I'm fine with waiting on full support for it to be added upstream. Our current team users should already be using the coowner flag for now, so we don't lose anything to wait.

**Comment by LGACode** [comment]
Is this the proper place to also report that !info does not correctly display Teams as the owner? It shows the Team ID instead of the actual Team name:

![image](https://user-images.githubusercontent.com/6125912/72123887-05f2f500-3320-11ea-9c39-0dfff3a48d94.png)

**Comment by mikeshardmind** [comment]
Yep, thanks for the info, we'll be looking into handling this when we add team support too.
