### ISSUE TITLE
[Config] Cache is set to new object even if object isn't JSON serializable

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2793]
# Other bugs

#### What were you trying to do?

Set object that isn't JSON serializable.
```py
config.someval.set({231, 321})
```

#### What were you expecting to happen?

Get exception about non-serializable object and Config's cache to stay intact.

#### What actually happened?

Config's cache got updated with a non-serializable object.

#### How can we reproduce this issue?

Assuming `config` contains `Config` instance, use this:
```py
try:
    await config.someval.set({231, 321})
except TypeError as e:
    print(str(e))
    print("yeah, we all know it's not JSON serializable, shut up")
print(await config.someval())
```

You should get this printed:
```py
Object of type set is not JSON serializable
yeah, we all know, it's not JSON serializable, shut up
{321, 231}
```

**Comment by Tobotimus** [comment]
I think our fix for this (and a bunch of other cache coherency issues in the JSON driver) will be to simply do `json.loads(json.dumps(value))` on every value which is set, before inserting it into the cache.
