### ISSUE TITLE
[Core] Fuzzy command search - commands show up multiple times if they have aliases

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2797]
# Other bugs

#### What were you trying to do?

Misspell a command with aliases (as in, coded aliases, not the ones from alias cog) with fuzzy command search enabled.

#### What were you expecting to happen?

Fuzzy command search to show proper command once.

#### What actually happened?

Fuzzy command search showed the proper command twice.

#### How can we reproduce this issue?

Use these commands with fuzzy command search enabled (misspell in second command intended)
```
[p]load general
[p]stopwatdc
```
Get this embed as a response:
![image](https://user-images.githubusercontent.com/6032823/60015441-d29e9080-9683-11e9-8573-9b5bc8f456ff.png)

**Comment by Tobotimus** [comment]
Ha, a #2450 regression? Or maybe it was never fixed :eyes:

**Comment by mikeshardmind** [comment]
wasnt ever fixed. the fact that help's fuzzy search was deduplicated was merely a side effect of how commands are filtered there, the normal on none found doesnt have that

**Comment by Tobotimus** [comment]
Anyway, this should be a pretty easy fix. I'll try get it done now
