### ISSUE TITLE
[Warnings] Option to disable DMing warns, option to warn in guild channel

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2800]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

I want to request 2 things in this issue, first is an option to disable sending warnings in DM to warned user and second is option to warn a user (i.e. ping them) in set guild channel and/or just warn that user in channel where the `[p]warn` command was issued.

**Comment by DevilXD** [comment]
> option to warn a user (i.e. ping them) in set guild channel and/or just warn that user in channel where the [p]warn command was issued.

Could you please clarify on this part? It's kinda hard to understand what the feature should be from this description.

Is it a channel where all warnings should be going to? If so, the warnings cog adds a modlog type you can enable to log those into the modlog channel already.

**Comment by Jackenmen** [comment]
But modlog is generally private, it doesn't "ping" and you can't have multiple modlog channels, I just want the bot to say it warned a user in the channel where the `[p]warn` command was issued OR in a set channel. To be more specific, it should do `ctx.send(f"{user.mention} was warned for spamming")` (or `channel.send` if it's set)

**Comment by DevilXD** [comment]
Right, so separate channel which can be made public. Gotcha.
