### ISSUE TITLE
[Informational & RFC] 3.2 Plans

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#2804]
We've had some internal talks about some of this, but the following is currently on my radar for the next minor version. There's not as much here as some might think, but as we're looking at a faster development cycle, the minor version really do signify when we have one or more changes which can't feasibly be added without a breaking change.

* There's some breaking changes planned for config to add things to it for safety and ease of use.
  - While these are breaking, we're on the very very low end of breaking here, more details to come, this may not impact most users

* Restructuring our docs, marking things we don't want to make guarantees about as private, and adding a page laying out in detail the commitments we intend on what is considered breaking. (requires some code restructure, but this one is mostly policy and docs for going forward)

  - By removing some things from our guarantees based on what we intend for cog dev use, we are empowered to change other things more flexibly to still prioritize users in future upgrades while informing devs what will and wont be supported.

* Modlog redesign

  - Needs to happen in a minor version, let's do it here.

* Killing `redbot-launcher`

* Make less mocked objects needed for efficient config usage (see below)

There will almost certainly be other things should they be ready in the same time window, but 3.2 doesn't need to be as drawn out. It just needs to provide the changes allowing a 3.2.x

As always, if there are other breakages to consider with a good reason for them, it's worth discussing, and this is even the time when it would be relevant.

**Comment by palmtree5** [comment]
I'm gonna throw #2433 in as a 3.2 target as at this point, while its primary focus was a new feature, it's actually turned into a bit of an overhaul that would probably be better suited for a minor release as opposed to a micro

**Comment by mikeshardmind** [comment]
addition to the list, killing `redbot-launcher` in favor of more non interactive opts and commands in discord

**Comment by mikeshardmind** [comment]
Looking to allow some more direct access in config without needing to mock objects in 3.2 as well (something like, but not necessarily identical to the below signature)
```py
def member(self, member: Optional[discord.Member]=..., guild_id=None, member_id=None) -> Group:
```
