### ISSUE TITLE
[Downloader] Cog update issue.

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [Cog-Creators/Red-DiscordBot#2828]
# Command bugs

#### Command name

cog update <cogname>

#### What cog is this command from?

Downloader

#### What were you expecting to happen?

For it to update the cog given.

#### What actually happened?

It said the cog given was already up to date even though I know it wasn't.
Doing `[p]cog update` without saying a cog name updated the cogs it was previously saying was already up to date.

#### How can we reproduce this issue?

Try to update 1 cog that has updates.

**Comment by mikeshardmind** [comment]
I can't seem to repriduce this issue. If you have any more specific details which may help in identifying the issue, I can look into this more.

**Comment by Ianardo-DiCaprio** [comment]
I have an unedited red that is up to date with the V3/develop branch.
With the --dev flag.

I added a random cog that I made so I could edit it to update it to test, but while doing that I've found that although they don't have changes, it still says that it updated successfully. Where as others says that they're already up to date.
