### ISSUE TITLE
Aliases can be used anywhere

### ISSUE THREAD

**Issue by franc-ist** [Cog-Creators/Red-DiscordBot#283]
If a channel is ignored, an alias can still be used by non-mods.

**Comment by tekulvw** [comment]
Discord.py issue, I've tried numerous times to get Danny to fix this

**Comment by Twentysix26** [comment]
About what aliases are we talking about? alias.py ones? How is this a discord.py issue?

**Comment by tekulvw** [comment]
Yeah, alias.py, customcom, and emotes all suffer from this. Within discordpy there is no way to stop it from dispatching on_message events which is what those three operate on

**Comment by Twentysix26** [comment]
I see this as a non-issue.
https://github.com/Twentysix26/Red-DiscordBot/blob/77bed58c455dd0565ec44654c890e01fc4e98d11/red.py#L71
This is how we ignore channels, servers and users for every other command, what's keeping us from doing the same in alias.py?

**Comment by tekulvw** [comment]
Because it shouldn't be up to cogs to respect ignores, if you do then issues like this happen.

**Comment by Twentysix26** [comment]
I get what you mean but it's just how the command extension is designed. It makes sense for it to work as it does now. As I see it, there's really nothing for the author to "fix", it's working as intended.

Back to the original issue, it will be trivial to add the checks in alias. Already done the same in custom commands.

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/65c7cdb8eefd45a95df94244469e1e7dd9d14b1f
