### ISSUE TITLE
Ability for reaction menu to be interacted with by everyone and not just command author

### ISSUE THREAD

**Issue by CSmither** [Cog-Creators/Red-DiscordBot#2835]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

Currently, reaction menus can only be interacted with by the original command author. It would be useful to allow the option of everyone being able to interact with reaction menus.

I think this is just an extension of the menu predicates and another menu class (similar to the existing one) calling the new predicates.

I had a go at duplicating the menu class and changing the predicate that it calls, but not luck so far as my python is a little rusty.

Has this been explored already? Is there another way to do this that exists already?

**Comment by Flame442** [comment]
I'm not sure if menus that let anyone move them are ever a good idea. It will just create confusion and conflict from different people trying to move it. Most commands are only supposed to be interacted with by the invoker anyway. Can you give an example of when this functionality would be useful?

**Comment by Tobotimus** [comment]
It'll be supported by #2809. In the example I put in the docs for that PR, I used a reactrole menu which let anyone react to it.

**Comment by CSmither** [comment]
So what I was trying to do is to have a voting system. So a single page with options and reactions to record votes. So I override the default controls and just have the options and a finish vote reaction. 
I know this is possible using the library you use and I have kinda got it working using that. But using red's util menus would be far neater.

**Comment by CSmither** [comment]
Having quickly read through the docs in #2809 I think this covers this use case. 
Will follow that MR and try it out when it is merged.

Thanks
