### ISSUE TITLE
[I18n] Add Traditional Chinese Translation

### ISSUE THREAD

**Issue by ibmibmibm** [Cog-Creators/Red-DiscordBot#2838]
# Feature request

Add Traditional Chinese Translation

#### Select the type of feature you are requesting:

- [x] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

There is only Simplified Chinese on [crowdin](https://crowdin.com/project/red-discordbot), and it will helps me and my friends a lot if there is a Traditional Chinese section!
I've joined this project on crowdin, and I can help translating into Traditional Chinese.

**Comment by Tobotimus** [comment]
Just added it, go nuts :smile: Thanks!
