### ISSUE TITLE
Notify channel when song changes?

### ISSUE THREAD

**Issue by 19lmyers** [Cog-Creators/Red-DiscordBot#284]
This is somewhat related to the queue list feature.

I was wondering if the bot could announce in a channel when it begins playing a queued song, because I'm not always sure if the song has changed.

**Comment by irdumbs** [comment]
we may make it a toggleable option

**Comment by DevScyu** [comment]
You mean something like this: https://github.com/Twentysix26/Red-DiscordBot/pull/325

**Comment by tekulvw** [comment]
Moving to #623
