### ISSUE TITLE
Trying to play a playlist and this appears.

### ISSUE THREAD

**Issue by Mikethe3rd** [Cog-Creators/Red-DiscordBot#285]
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Mike\Desktop\Red-Bot\Red-DiscordBot\cogs\audio.py:1562> exception=ClientException('ffmpeg/avconv was not found in your PATH environment variable',)>
Traceback (most recent call last):
  File "C:\Users\censored\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 371, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 950, in **init**
    restore_signals, start_new_session)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\censored\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\censored\Desktop\Red-Bot\Red-DiscordBot\cogs\audio.py", line 1589, in queue_manager
    song = await self._play(sid, url)
  File "C:\Users\censored\Desktop\Red-Bot\Red-DiscordBot\cogs\audio.py", line 658, in _play
    local=local)
  File "C:\Users\censored\Desktop\Red-Bot\Red-DiscordBot\cogs\audio.py", line 341, in _create_ffmpeg_player
    song_filename, use_avconv=use_avconv, options=options)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 374, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable

Using windows 10.

**Comment by tekulvw** [comment]
Read the docs

**Comment by franc-ist** [comment]
Read this fully: https://twentysix26.github.io/Red-Docs/red_win_requirements/

**Comment by Mikethe3rd** [comment]
Yes I did I got everything I can screenshot you that I have the path available in my path environment variable and got the files etc etc.

**Comment by tekulvw** [comment]
Go ahead and screenshot, because you don't have ffpmeg or avconv in your path

**Comment by Mikethe3rd** [comment]
http://imgur.com/a/xwqUV

**Comment by tekulvw** [comment]
How do you run the bot?

**Comment by Mikethe3rd** [comment]
Clicking on the startred.bat, typing in chat !playlist mix playlistname
then it starts spamming the error after a bit.

**Comment by Mikethe3rd** [comment]
I just upgraded red bot after a long time of not using it, should I just try restarting pc / reinstalling?

**Comment by tekulvw** [comment]
Yeah try restarting

**Comment by Mikethe3rd** [comment]
Done, still no sign of life ;-;

**Comment by Mikethe3rd** [comment]
will try doing a fresh install I suppose

**Comment by Mikethe3rd** [comment]
Yeah I think I know what was the issue, my red bot wasn't with a bot tag or a bot account at all.

**Comment by Mikethe3rd** [comment]
1. Done, still no sign of life ;-;
   2.will try doing a fresh install I suppose
2. Yeah I think I know what was the issue, my red bot wasn't with a bot tag or a bot account at all.
   4.: Jk, error still appears somehow, no matter what playlist I play either, did everything I could, I'm lost, my ffmpeg does get detected when I type ffmpeg -version etc.

new edit: it appears It's fixed, I needed avconv too? for some reason I thought its either ffmpeg or avconv not both

**Comment by ddday** [comment]
You don't need both it's either @Mikethe3rd

**Comment by irdumbs** [comment]
you probably typed `!audioset player` at some point and set avconv as your audio player.
Being you didn't have avconv installed, it complained about not finding it.

**Comment by Mikethe3rd** [comment]
Weird because I removed the entire folder, unless it saves things in another way

**Comment by tekulvw** [comment]
So...I'm guessing this got fixed?

**Comment by Mikethe3rd** [comment]
Guess yes
