### ISSUE TITLE
[i18n] Should we keep novelty languages?

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#2850]
I'm copying this issue over from this [discussion](https://crowdin.com/project/red-discordbot/discussions/8/0/home) on Crowdin.

Languages like LOLCAT and Pirate English are a novelty, I understand some people like that and I have no problem with it.

But looking forward it would simplify some things for us devs to only support official languages with recognisable language codes. By "official languages" I'm really referring to those supported by various libraries we aim to use, in particular the ones listed [here](https://www.unicode.org/cldr/charts/latest/summary/root.html).

Of course, if no one is interested in translating these languages, that's all the more reason to remove them. But if anyone objects, please post here and we'll keep it in mind.

### Technical reasons for consideration
Looking forward we hope to enhance our i18n features by integrating [`babel`](http://babel.pocoo.org/en/latest/) into the framework. However, babel doesn't recognise these novelty languages, because it relies on CLDR (linked above). Keeping these languages means defaulting to en-US whenever we're using babel features, but this might lead to some confusing behaviour with utils that return a Babel locale, because if you pass in something like `lol-US`, you'll get `en-US` back.

**Comment by mikeshardmind** [comment]
+1 from me on removing the novelty lang support. There's almost nothing translated in them, even only including strings that existed from the inception of crowdin support, and the benefits are pretty clear.

**Comment by Tobotimus** [comment]
Also in case it wasn't clear, if we do decide to remove these languages from core support, this also means any .po files provided with cogs which don't use a CLDR-recognised language-TERRITORY code will be ignored.

**Comment by mikeshardmind** [comment]
As there's been no negatives on this and the only novelty languages we had had no meaningful translations, Its safe to say we aren't keeping the novelty langs.
