### ISSUE TITLE
[Audio] Prefer Topic Channel

### ISSUE THREAD

**Issue by AHIRAISSHY** [Cog-Creators/Red-DiscordBot#2856]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
-  Command
- [ ] API functionality

#### Describe your requested feature

[Audio Setting] if you use the spotify link and it's looking up a song from youtube prefer from that topic channel for an 

Example link for the topic track: https://www.youtube.com/watch?v=tEXYfT_G0W0

and if that topic track doesn't exist just look it up normally

Command Name: ```[p]audioset topictracks```

**Comment by aikaterna** [comment]
https://discordapp.com/channels/133049272517001216/133049878837329920/587635412831436820 is where I originally answered you when you asked for this in the Red Discord server. I will not be adding this feature as it is expensive API-wise to try to search through all of the possible track responses until a topic track is returned. Considering new YouTube Data API V3 keys are being given out with rather low initial numbers right now, this is not a feature that will work well within audio.

**Comment by AHIRAISSHY** [comment]
Welp oof
