### ISSUE TITLE
Suggestion: Add localization support.

### ISSUE THREAD

**Issue by Yandols** [Cog-Creators/Red-DiscordBot#286]
Probably on a low priority feature suggestion: Add localization support of some sort. 
So that end-users won't need to modify red's core files in order to change the language to theirs or a even a few simple messages. Instead they just need to modify a language file in `/data/` or something.

**Comment by Twentysix26** [comment]
That's been suggested before. While great in theory, it would be a real pain to implement at this point. It's something that would need massive changes. Not feasible.
