### ISSUE TITLE
[Alias] Add information about support of parameters in help

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2862]
As in title, there's currently no place where user can get help on alias parameters, I propose either just adding explanation on that in help command or possibly just putting link to docs (which would need to be created first) on that.

Only examples of usage are in #2455

**Comment by mikeshardmind** [comment]
This won't be rushed into 3.1.3 The syntax and supported types may change between now and 3.2 as alias has at minumum a partial redesign planned.

Will keep this issue up to date with those plans so that if the redesign is after 3.2 we ensure a doc update in the mean time
