### ISSUE TITLE
The removal of !sfx and functionally to !queue? Curious.

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#287]
Maybe it's my ineptness, but when I updated the bot, the sfx folder still exists but the !sfx command is no longer existent.

!queue also no longer displays the song queue, instead just has the bot leave a message about how to use the !queue command.

**Comment by ddday** [comment]
The audio module has been recently re-written. The sfx command was removed but will likely come back as a 3rd party cog. 

As to queue I have no idea.

**Comment by tekulvw** [comment]
Duplicate of #257 and sfx is gone in rewrite, look for a 3rd party cog in the future
