### ISSUE TITLE
[Modlog] Adding a reason fails for any new case after the update

### ISSUE THREAD

**Issue by DevilXD** [Cog-Creators/Red-DiscordBot#2874]
# Command bugs

#### Command name

`[p]reason`

#### What cog is this command from?

`ModLog`

#### What were you expecting to happen?

A reason gets added to a case.

#### What actually happened?

The bot says the case doesn't exist.

#### How can we reproduce this issue?

`[p]reason <case_id> Test reason` for any `case_id` of a case that was created after updating to the latest stable (3.1.3).
`redbot.core.modlog.to_json` missing a key in the output dict is most likely to be the cause here.

**Comment by Tobotimus** [comment]
Resolved by #2877.
