### ISSUE TITLE
[Audio] `[p]audioset settings` reports Jar build incorrectly

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#2880]
`[p]audioset settings` is currently reporting the current Red version as the Jar build instead of the Lavalink version. We should probably add something to the manager to make it store the version of the currently used Lavalink jar, or perhaps we can get the version through the REST API?

**Comment by Drapersniper** [comment]
This can be closed, As on #2904 we no longer report the JAR version, this is due to the difficulty of obtaining the version on external lavalink (specifically in different machines)
