### ISSUE TITLE
[Context] Context Based formatting API

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#2883]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

An API to facility sending messages based on the context the command in called in (Mobile vs Web/Client) With would allow devs to check this API and send a message formatted to the platform the user is in

Say Smaller code blocks  to avoid ugly folding  on mobiles.

Don't think we would do the formatting as there too many variables this should be up to the cog devs.

This api would be something like `Context.embed_colour()`

**Comment by mikeshardmind** [comment]
We're starting to get a lot of options showing up here. It may be worth changing the way this works, with something like `ctx.ux_options()` which would return `types.SimpleNamespace` filled with the options for the context. (or a custom class with helper function as well if we have a reason to)

**Comment by DevilXD** [comment]
Isn't this information accessible via `ctx.author.mobile_status`, `ctx.author.desktop_status` and `ctx.member.web_status` ?

https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.mobile_status

**Comment by mikeshardmind** [comment]
Closing this one for now. We'd have to maintain a rather complex amount of logic for this to be any better than letting the cog developer use their best judgment based on available info.

A prime example of where this could go wrong is if audio attempted to use this.
