### ISSUE TITLE
[Tunnel] Allow to use proxy_url for attachments in files_from_attach

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2885]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

`Tunnel.files_from_attach` function could be extended to allow the use of cached attachments, which would make it more useful when the message is deleted but the images are still available under proxy_url.

Would also be nice if it could skip files that aren't images and therefore aren't cached instead of throwing exception because of the single file when all the others were images.

**Comment by mikeshardmind** [comment]
While im not completely against supporting the proxy url, I'm not at all in favor of intentionally circumventing message deletion in core utils. The core bot should be generally safe.to use without major privacy law concerns.

**Comment by mikeshardmind** [comment]
added in #2887
