### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by BizarreDuck** [Cog-Creators/Red-DiscordBot#2886]
```
Traceback (most recent call last):
  File "red.py", line 12, in <module>
    from discord.ext import commands
  File "lib\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "lib\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "lib\discord\voice_client.py", line 43, in <module>
    import websockets
  File "lib\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "lib\websockets\client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "lib\websockets\protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "lib\websockets\compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax
```
Using the old version of Red, I had it before on another computer but that one broke, then transferred the files to new computer. Tried to re-open Red, updated, reinstalled requirments, tried to repair + reset (both .data and to factory settings), then deleted the folder (after it still didnt work) and redownloaded Red. The error for that Red was something to do with red.py, I didnt copy + paste it
Followed the instructions here to redownload (https://twentysix26.github.io/Red-Docs/red_install_windows/), Python 3.5.4 (32 bit) and the Git that was recommended there. I downloaded "basic requirments" (no audio requirments, option 2) and option 3 for audio (ffmpeg 32bit (i have no idea what bit my computer is, the files seemed to be repeating 32 so i tried that)), and it comes up with that error ^^ 
Dunno whats wrong.

**Comment by Jackenmen** [comment]
You most likely also have other Python version installed on your computer and Red used that one instead of the correct one.
If you need support, you should ask on Red's server:
https://discord.gg/red

**Comment by Tobotimus** [comment]
Yeah you're running Red V2 with Python 3.7. As Jack said, best ask in the support server :smiley:
