### ISSUE TITLE
Can't make tempbans permanent

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#2898]
# Command bugs

#### Command name

tempban

#### What cog is this command from?

Mod

#### What were you expecting to happen?

To be able to make the tempban permanent later on

#### What actually happened?

Unbanning, hackbanning, or any combination did not remove the user from the tempban list

#### How can we reproduce this issue?

Tempban a user
Unban them
Hackban them
After tempban expires, the user is unbanned despite being unbanned and hackbanned.

**Comment by mikeshardmind** [comment]
This can be resolved by making hackban also clear a pending unban/unban entry
