### ISSUE TITLE
[Warnings] Permissions for `[p]warnings` command can't be modified

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2900]
# Command bugs

#### Command name

`[p]warnings`

#### What cog is this command from?

Warnings

#### What were you expecting to happen?

Permissions cog to be able to change required permissions for `[p]warnings` command - in this case, allow mods to use it.

#### What actually happened?

The command still couldn't be used by mods. Reason for this is that we use a `is_admin_or_superior` function inside the command instead of using a check. This was done like this to allow users to check their own warnings without any permissions, but because of this, there's no way to use the command for people without admin role, even when changing the required permissions with Permissions cog. I never had to check if args is given within a check before, so I'm not sure if it's possible to do using `commands.check`, but IMO Permissions cog should allow to change required permissions for this command.

#### How can we reproduce this issue?

`[p]permissions addserverrule allow warnings Mods`

**Comment by mikeshardmind** [comment]
My comment from the recent duplicate applies here:

> Red's permission model would require these two separate behaviors to be split into separate commands. A command anyone could run by default to view their own warnings, and a command which used a normal permissions override-able check (at the same admin default level) to view others.

To further clarify, `permissions` doesn't support variable allow/deny based on the intent of the command. It can't know, only restrict or unrestrict the command.

**Comment by Dav-Git** [comment]
The general idea was that server admins especially on bigger servers can entrust a specific role with the ability to check a users warnings and proceed with different disciplinary actions as a result of the outcome of the warnings check.

Whether that would be done in a seperate command or not doesn't really matter, but I think the option should be there, especially since every other aspect of the warnings cog is controllable using permissions.

**Comment by Dav-Git** [comment]
Since the PR working on this issue got closed I'm not sure if the In progress status still applies.
