### ISSUE TITLE
No special case for 2-tuple humanize_list

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#2906]
# Other bugs

#### What were you trying to do?

use humanize_list with a 2-item list

#### What were you expecting to happen?

returns "*x* and *y*"

#### What actually happened?

returns "*x*, and *y*"
note the comma here

#### How can we reproduce this issue?

use humanize_list on a 2-tuple

**Comment by mikeshardmind** [comment]
This should likely use http://babel.pocoo.org/en/latest/api/lists.html#babel.lists.format_list as we transition to using babel for some i18n things.
