### ISSUE TITLE
[Trivia] Typo in starwars trivia

### ISSUE THREAD

**Issue by ZeLarpMaster** [Cog-Creators/Red-DiscordBot#2909]
# Command bugs

#### Command name

`[p]trivia`

#### What cog is this command from?

`trivia`

#### What were you expecting to happen?

Trivia to not have typos

#### What actually happened?

Trivia had a typo

#### How can we reproduce this issue?

Play `starwars` trivia

**Comment by Flame442** [comment]
Can you please specify the typo?

**Comment by ZeLarpMaster** [comment]
Feel free to ignore this, I just needed an issue so I could make a changelog entry for #2903

**Comment by mikeshardmind** [comment]
for future ref, standalone PRs are fine and you can use the PR # as well.

**Comment by ZeLarpMaster** [comment]
Can you add that to [contributing.md](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/.github/CONTRIBUTING.md#47-using-towncrier)?

**Comment by mikeshardmind** [comment]
:+1: Will do (I thought I had, it was not intentional that this was not already present there)

**Comment by mikeshardmind** [comment]
fixed in #2903
