### ISSUE TITLE
[Setup] Don't use working directory for storing setup logs

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2917]
Currently `redbot-setup` command creates a folder named "red_setup_logs" in working directory and I think this behaviour is too invasive and unexpected. I am not entirely sure where the setup logs should be stored instead, possibly in appdirs location, but touching working directory without any information about it just isn't a good way to do it.

**Comment by Drapersniper** [comment]
We could use the OS temp folders to store these logs, however this would cause them to be be wiped after a reboot

**Comment by mikeshardmind** [comment]
I'm perfectly fine with redbot-setup not logging to disk
