### ISSUE TITLE
[Bank] Bank transfer logic at max balance

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#2923]
# Command bugs

#### Command name

bank transfer

#### What cog is this command from?

bank

#### What were you expecting to happen?

For a user to keep their credits after a failed transfer attempt.

#### What actually happened?

The transfer amount disappeared into the void.

#### How can we reproduce this issue?

Users A and B both have 60% of max balance amount in their bank. User A gives User B 50% of the max balance amount via the bank transfer command. User B would now at 110% of max balance and the bot replies "User B's balance cannot rise above 9,223,372,036,854,775,807 credits."  However, User A will now be at 10% of max balance instead of the expected 60% of max. The transfer amount is being deducted from User A's balance when it shouldn't have been.

**Comment by Flame442** [comment]
Fixed by #2925
