### ISSUE TITLE
Downloader updating repos

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#2927]
# Command bugs

#### Command name

cog update

#### What cog is this command from?

Downloader

#### What were you expecting to happen?

For the cog to load and not another version to load. 

#### What actually happened?

Got replaced with a unloaded not installed cog.

#### How can we reproduce this issue?

1. Install nsfw from Preda-Cogs as an example.
2. Load nsfw cog. 
3. Add another repo that contains a cog named nsfw but do not install.
4. cog update with the new repo added when you update something.
5. Reload nsfw or restart your bot and notice that your bot has started using the new nsfw cog and not your old one.

**Comment by Jackenmen** [comment]
After additional tests on Discord, we figured out that the `nsfw` cog was in fact marked as installed under several repo names (some no longer existent, which also made us aware of other issue). So to address this issue, we should not allow installing another cog going by the name that another installed cog already uses.
About the other issue we found - `[p]cog uninstall` is useless after repo is removed as `Installable` class checks for repo availability and if it can't find the repo anymore, it changes `repo_name` to "MISSING_REPO" string even though that repo name is necessary for other operations like that `[p]cog uninstall` command
