### ISSUE TITLE
[Downloader] Issue with deleted repo/branch.

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [Cog-Creators/Red-DiscordBot#2936]
# Command bugs

#### Command name

Cog update

#### What cog is this command from?

Downloader/RepoManager

#### What were you expecting to happen?

For all cogs to update

#### What actually happened?

Got a command invoke error.

#### How can we reproduce this issue?

Have a repo added, where the repo or branch no longer exists.

I feel like this should be handled better, and pass that repo and carry on updating, instead of erroring out the whole command.

**Comment by Flame442** [comment]
Fixed by #3080
