### ISSUE TITLE
[Menus] Feature request.

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [Cog-Creators/Red-DiscordBot#2937]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Not sure if it's possible, but I think having the ability to delete the command message when the click the red cross emoji on menus would be a cool and useful feature to have.

**Comment by Drapersniper** [comment]
iirc this will be the default behaviour in #2809

**Comment by Tobotimus** [comment]
Deleting the "command message"... I think this is too niche to be worth supporting in the default menu. After #2809 it will be pretty easy for you to subclass the menu to achieve what you want, however.

**Comment by mikeshardmind** [comment]
This is already possible if you provide your own action for that emoji rather than using the default controls.
