### ISSUE TITLE
Modset deletedelay behavior, 3.1.5

### ISSUE THREAD

**Issue by itsnaeng** [Cog-Creators/Red-DiscordBot#2942]
# Other bugs
This bug happens with the modset's deletedelay feature enabled, I have submitted about this on a previous version which was 3.0.2 on python 3.6.8 @ [#2705](https://github.com/Cog-Creators/Red-DiscordBot/issues/2705) 

#### What were you trying to do?

Just normally chat with friends in a public server, though some users happen t use the prefix [p] in front of their messages and it just deletes.

#### What were you expecting to happen?

Ignored message as it's not a command

#### What actually happened?

The bot seems to registers any messages with the prefix as a command, so it just deletes any messagess as `[p]whateverMessage is this`

#### How can we reproduce this issue?

Red's Version: 3.1.5
Python Version: 3.7.3

1. enable `[p]modset delaydelete X`
2. type whatever message with the prefix in the front `[p]whateverhere`
3. auto deleted?

Example screenshots:
https://i.shikashi.me/BYX0o
https://i.shikashi.me/ewyny

Note: I have tried this with cogs unloaded and loaded. (Looks like a core behavior)

**Comment by Vexed01** [comment]
I can reproduce this behaviour. Red 3.1.5, Python 3.7.4 and d.py 1.2.3.

Video: https://vexed.uk.to/294f4
