### ISSUE TITLE
[Setup] `redbot-setup delete` should allow to keep Red's data within database

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2962]
# Feature request

#### Describe your requested feature

Deleting instance from Red shouldn't require deleting Red's data from database - especially that it doesn't require that for JSON backend.

**Comment by Madhav-byte-debug** [comment]
I mean you could alway take a backup

**Comment by Jackenmen** [comment]
@Madhav-byte-debug please don't necromance old issues for absolutely no reason.
