### ISSUE TITLE
extension titleRequest does not have a setup function

### ISSUE THREAD

**Issue by GauldothHD** [Cog-Creators/Red-DiscordBot#2979]
# Command bugs

#### Command name

!load _"cogname"_

#### What cog is this command from?

Custom cog created by manual: 
https://red-discordbot.readthedocs.io/en/latest/guide_cog_creation.html#getting-started

#### What were you expecting to happen?

I'd like to see "I can do stuff"

#### What actually happened?

_Got an error in Terminal:_

Traceback (most recent call last):                                                 n load_extension
  File "d:\programs\python 3.7.4\lib\site-packages\redbot\core\core_commands.py", l")ine 106, in _load                                                                  on
    await bot.load_extension(spec)
  File "d:\programs\python 3.7.4\lib\site-packages\redbot\core\bot.py", line 296, in load_extension
    raise discord.ClientException(f"extension {name} does not have a setup function")
discord.errors.ClientException: extension titleRequest does not have a setup function

#### How can we reproduce this issue?
**__init__.py**
from .titleRequest import TitleRequest

def setup(bot):
    bot.add_cog(TitleRequest())

**titleRequest.py**
from redbot.core import commands

class TitleRequest(commands.Cog):
    """My custom cog"""

    @commands.command()
    async def mycom(self, ctx):
        """This does stuff!"""
        # Your code will go here
        await ctx.send("I can do stuff!")

**Comment by GauldothHD** [comment]
Can you please give me a hint on what am I doing wrong?

**Comment by kennnyshiwa** [comment]
sounds like your folder structure is probably wrong should look something like this. For more help you should join the discord as we can help you easier there with coding your own cog

```
.
└── folder_with_cogs
    └── mycog
        ├──__init__.py
        └── mycog.py

**Comment by mikeshardmind** [comment]
Without a bit more info, it's a bit difficult to be able to say. The above suggestion about folder structure is a good place to check.

Red attempts to import a module, then looks for a function named `setup` in that module.

If Red says the function isn't there, it isn't, but this can be caused by multiple things.

We have a dedicated channel in the discord server for help with writing cogs if you are still having issues after this.

**Comment by GauldothHD** [comment]
I found the solution which isn't really a user error.

Apparently the folder structure should look like this if you want to add a new cog and run it:
.
└── folder_with_cogs
    └── mycog
        └── mycog
             ├──__init__.py
             └── mycog.py

While my [p]paths has output like this: "..folder_with_cogs\mycog\"
This is a BUG.

**Comment by Drapersniper** [comment]
`..folder_with_cogs` should be the folder you add with `[p]addpath` and not `folder_with_cogs\mycog`
