### ISSUE TITLE
Bot sends two messages instead of one

### ISSUE THREAD

**Issue by robsgh** [Cog-Creators/Red-DiscordBot#299]
Whenever a command is used that requires output from the bot, it will always send two messages instead of one.  This just recently started happening after the latest pull.  Also when looking at the output from the server, it complains saying "ERROR: unable to rename file: [Errno 2] No such file or directory: 'data/audio/cache/ZPBLpzWd_p4.part' -> 'data/audio/cache/ZPBLpzWd_p4'"

**Comment by tekulvw** [comment]
You sure you're not running two instances of the bot?

**Comment by robsgh** [comment]
Gosh, I feel stupid.  I forgot that a long time ago I tried to make Red a service.  Thank you.

**Comment by tekulvw** [comment]
Not a problem :)
