### ISSUE TITLE
Selfhosting on Heroku

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#3001]
Would Like To See It Be Able To Use It With Heroku Hopefully That You Could Make Run On Heroku Would Be Helpful And Quite Nice To Be Able To Run It On Heroku

**Comment by mikeshardmind** [comment]
Heroku support is a semi-frequent request, but it's something we've consistently decided against supporting. While this could change, it's unlikely to do so.

_Red can work on Heroku_, but there are caveats to that.

  1. Red's notion of dependency handling for 3rd party cogs doesn't play well with Heroku's environment.
  2. Red doesn't currently have a completely non-interactive setup. (This one is planned)
  3. Heroku isn't a great idea for stateful, long running applications

If you handle point 2 and can accept the instability related to point 3 then Red will work with only minimal hiccups around 3rd party cogs, but you're on your own.
