### ISSUE TITLE
[Docs] Auto-restart guide doesn't mention venvs - add info about `ExecStart`

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3005]
Basically I think there should be something in auto-restart docs that would be similar to the command we use in #support:
![image](https://user-images.githubusercontent.com/6032823/65280653-26106580-db31-11e9-83b6-56aa3d32d41e.png)

**Comment by Dezyox** [comment]
Agree. The actual documentation is good, but not user friendly on this point if we change the instance path.
