### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#3006]
Would Like To Be Able To Change "Red V3" in the help cmd to something that i would to change it to

**Comment by Flame442** [comment]
That is part of the credits for the bot. Removing references to Red is against the terms of the licence.

**Comment by Jackenmen** [comment]
Would Like You To Respect The Work All Contributors Did And Not Request Removing Credits

**Comment by mikeshardmind** [comment]
If you don't like that the bot has a small, non-intrusive note in the help and info indicating what bot it is, you're welcome to use anything else.

**Comment by ghost** [comment]
> That is part of the credits for the bot. Removing references to Red is against the terms of the licence.

how could it breaking licence when there is no licence :/

**Comment by Flame442** [comment]
https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/LICENSE

**Comment by ghost** [comment]
is says permission: modification ✅ so i can mod bits in the code

**Comment by Flame442** [comment]
From the license:

 5. Conveying Modified Source Versions.

  You may convey a work based on the Program, or the modifications to
produce it from the Program, in the form of source code under the
terms of section 4, provided that you also meet all of these conditions:    

    a) The work must carry prominent notices stating that you modified
    it, and giving a relevant date.

    b) The work must carry prominent notices stating that it is
    released under this License and any conditions added under section
    7.  This requirement modifies the requirement in section 4 to
    "keep intact all notices".

    c) You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.  This License gives no
    permission to license the work in any other way, but it does not
    invalidate such permission if you have separately received it.

    d) If the work has interactive user interfaces, each must display
    Appropriate Legal Notices; however, if the Program has interactive
    interfaces that do not display Appropriate Legal Notices, your
    work need not make them do so.

**Comment by mikeshardmind** [comment]
This is no longer appropriate discussion for the issue tracker.

I would strongly suggest you speak to an actual lawyer before attempting to interpret a small line as "I can do whatever I want with this", the GNU GPL v3 license is very legally dense, and nobody here is your lawyer.
