### ISSUE TITLE
Using !set avatar causes error

### ISSUE THREAD

**Issue by franciscusconstantus** [Cog-Creators/Red-DiscordBot#302]
![image](https://cloud.githubusercontent.com/assets/16739295/16043805/bdb25296-3241-11e6-8c93-411bb8e30227.png)

![image](https://cloud.githubusercontent.com/assets/16739295/16043429/e82721fc-323f-11e6-93ee-69086d11dac5.png)

**Comment by franciscusconstantus** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/f6383c2dfd4c392cb0f280905acb4abe2ec34a0e

Thanks

**Comment by tekulvw** [comment]
Are you running XP? O.O

**Comment by franciscusconstantus** [comment]
C:\Users\ would already give away I aint running XP.
