### ISSUE TITLE
Bold part of docstrings do not have [p] replaced with used prefix

### ISSUE THREAD

**Issue by Vexed01** [Cog-Creators/Red-DiscordBot#3039]
# Other bugs

#### What were you trying to do?

Have `[p]` in the bold part of a docstring be replaced for the used prefix.

#### What were you expecting to happen?

The `[p]` to be replaced with the used prefix.

#### What actually happened?

The `[p]` stayed as `[p]`.

#### How can we reproduce this issue?

1 Create a docstring that uses `[p]` in the bold (first line, before the double newline) part
2 load/reload the cog
3 Run `[p]help <command>`
4 See that `[p]` is not replaced with the used prefix

#### Other Details

![image](https://user-images.githubusercontent.com/51716387/66422036-da9afa00-ea00-11e9-9884-6db79c916705.png)
In this image, the docstring is
```py
"""from [p]paths.

[p]
"""
```
This was found in relation with #3038

**Comment by mikeshardmind** [comment]
This will be fixed in the handling of #2981

**Comment by mikeshardmind** [comment]
resolved in #3339
