### ISSUE TITLE
imgur search Posts Three Images into Chat

### ISSUE THREAD

**Issue by bryonadams** [Cog-Creators/Red-DiscordBot#3044]
When using the built in imgur search functions, it pulls three image search results from imgur/reddit and posts all three to Discord. When I looked at the code it looks like there's a slice that tells it to post all three. Is this intentional behavior? When the search succeeds on all three that's a huge wall of image posted to Discord chat as a single post. I can edit the slice to only use the first but I figured I'd ask here first in case this is a bug/error or if I'll need to edit this. Just seems like an insane default or I'm just doing something wrong on my end.

Slice in question (same code is used for each type of image search it looks like):

```
for r in results[:3]:
  msg += r["gifv"] if "gifv" in r else r["link"]
  msg += "\n"
```

Thanks!

**Comment by Jackenmen** [comment]
I think we should allow the user to decide how many images they want to get, the more sane default would surely be one image but I think allowing up to max of 5 images to be returned will work great here.

So for example:
- `[p]imgur search dog`
  should return one image of a dog
- `[p]imgur search 1 dog`
  should return one image of a dog
- `[p]imgur search 3 dog`
  should return three images of a dog
- `[p]imgur search 5 dog`
  should return five images of a dog
- `[p]imgur search 0 dog`
  should fail
- `[p]imgur search 6 dog`
  should fail

This can be achieved using `typing.Optional`:
```py
async def imgur_search(self, ctx, amount: Optional[int] = 1, *, term: str):
```
