### ISSUE TITLE
[Set] Stream

### ISSUE THREAD

**Issue by Menteroth** [Cog-Creators/Red-DiscordBot#3046]
# Feature request
To be able to set channel being streamed as any platform, like YouTube and Mixer, not only Twitch.

#### Select the type of feature you are requesting:
- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature
Set bot as streaming with YouTube, Mixer or Twitch. So when someone clicks "watch" it opens the respective platform/channel set.

If you are requesting a command:
Cog: Core
[p]set stream [platform] [channel] [stream_title]

**Comment by Jackenmen** [comment]
Discord doesn't support other platforms than Twitch in Streaming status

**Comment by Drapersniper** [comment]
AFAIK,  Discord hasn't added YouTube and Mixer rich presences,  so this is not really doable until rich presences for those services are avaliable and can be used by a bot

**Comment by Menteroth** [comment]
Oh okay. I thought one could add streaming presence and enter URL within the code.
Well then. Thanks for the quick replies.
