### ISSUE TITLE
[Audio] Bot's status isn't cleared on auto-disconnect

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3050]
# Other bugs

Bot's status isn't cleared on auto-disconnect. It was already happening before Draper's PR came in.

#### How can we reproduce this issue?

1. `[p]audioset emptydisconnect 10`
2. `[p]play audio url`
3. Leave channel and wait 10 seconds for the bot to leave it as well.
4. Status still shows up.

**Comment by Drapersniper** [comment]
@jack1142 just to check, have you toggle `[p]audioset status` ? I assume so but just wanted to check.

Having a skim through the code and `_status_check()` is only called when status is set to True.

It then runs on `LavalinkEvents.TRACK_START`, `LavalinkEvents.TRACK_END` and `LavalinkEvents.QUEUE_END`

Auto disconnect should trigger a `QUEUE_END` so without doing any testing it seems that the only reason why this wouldn't reset the status is if the status was disabled after the track started playing.

**Comment by Jackenmen** [comment]
@Drapersniper yes I do have `[p]audioset status` set to true, I forgot to put it in reproduction steps.
