### ISSUE TITLE
[Core] Add indicator that someone is using dev version

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3056]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

I don't really know what to choose here, but I guess API functionality fits it the most as once that's done, every place with version will have it updated.

#### Describe your requested feature

I think it would be cool to have an indicator that someone is using dev version of Red. **Ideally** I'm thinking of something similar to how mypy handles it:
Stable release:
```
$ mypy --version
mypy 0.730
```
Dev version:
```
$ mypy --version
mypy 0.740+dev.0e41cce53548c260a419a80a813760457508624e
```

But I know that this is a lot of work for something like this so I think it would be more than enough to just have `+dev` suffix added when someone uses dev version.
That would limit additional work to just adding another version bump commit with `+dev` suffix right after every regular release.

**Comment by Jackenmen** [comment]
This is at least partially solved - we now bump our version to `.dev1` after each release. Still no commit in the version (i.e. `3.2.3.dev1+0e41cce53548c260a419a80a813760457508624e`) or number of commits since release (i.e. `3.2.3.dev1+5`) but it's still a very big improvement for support squad.

**Comment by mikeshardmind** [comment]
I'm going to consider the current version as solving this "well enough" for now. Maybe we should also be bumping dev versions more, but I'll hold off on advocating for that at all for a while longer.
