### ISSUE TITLE
[Core] Add option to disable DM notifications about outdated instance

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3074]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [x] API functionality
(eeeeh, nothing really fits)

#### Describe your requested feature

I would like an option to disable update notification that you get in DM on bot startup when you're using outdated bot version.

**Comment by mikeshardmind** [comment]
:thinking: I'm inclined to deny this one. We already have a means to move these notifications to another channel rather than a DM, is there a reason we want to support users staying on outdated versions long term?

**Comment by Drapersniper** [comment]
Agree, if we give users so continuous warning that they are out of date  we will risk insintivising users to stay on outdated version.

At best in my optinion we could set defered notifications (say one per week)

**Comment by Jackenmen** [comment]
I changed my mind, I don't want that lol (nor would I want to support more people using old version because they don't know there's new one)
