### ISSUE TITLE
audio not playing, error from audio cog

### ISSUE THREAD

**Issue by anewhomegw2** [Cog-Creators/Red-DiscordBot#3076]
# Command bugs
Error when using _play url   - get vox error connecting to discord over the last 2 days.
All package updates have been applied, including one today and PIP updated.

#### Command name
_play 

#### What cog is this command from?
Audio

#### What were you expecting to happen?
Beautiful Tunes to play from Youtube

#### What actually happened?
[21/10/2019 19:01] ERROR red on_command_error 388: Exception in command 'play'
Traceback (most recent call last):
  File "C:\gw2bots\Red-DiscordBot\Red-DiscordBot\cogs\audio.py", line 715, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "C:\Users\dan\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 410, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\gw2bots\Red-DiscordBot\Red-DiscordBot\cogs\audio.py", line 1525, in play
    await self._join_voice_channel(voice_channel)
  File "C:\gw2bots\Red-DiscordBot\Red-DiscordBot\cogs\audio.py", line 719, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel,"
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel, please try again in 10 minutes.

#### How can we reproduce this issue?
Update to latest - try to play using _play url - where a URL link is a YouTube link ?

**Comment by yamikaitou** [comment]
v2 Audio is broken because of recent changes by Discord that required a Library update. discord.py is not planning on updating the async branch with the fix (which is what v2 uses). You will need to install v3 to continue using Audio. If you need further support, feel free to join us on Discord

**Comment by Jackenmen** [comment]
You may need the docs for V3 that contain all installation guides for it, so here they are: https://docs.discord.red/en/stable/
You should be able to simply follow the guide for your operating system to install V3 but if you encounter any issues you can ask on Red's Discord server like Yami said: https://discord.gg/red

**Comment by anewhomegw2** [comment]
Thank you all - I'll give it a go, see if I can get it operational.
