### ISSUE TITLE
YouTube Streaming API uses up 10.000 requests in a few hours + not properly working

### ISSUE THREAD

**Issue by Skyridr** [Cog-Creators/Red-DiscordBot#3095]
# Other bugs

#### What were you trying to do?

Setting up the stream youtube API so RED using `[p]set api youtube api_key,keyhere` in a private channel.

#### What were you expecting to happen?

For RED to properly show whenever a user is live in a designated channel. 

#### What actually happened?

RED appears to be using 10.00 requests in matter of hours every single day. 

![image](https://user-images.githubusercontent.com/6794064/68072764-5b8fac00-fd89-11e9-90f7-4a84988d3b5d.png)

I believe whenever the API daily quota is being reset, the bot shows up that the user is live!

![image](https://user-images.githubusercontent.com/6794064/68072778-8548d300-fd89-11e9-8e0d-26d75f61cf83.png)

While the stream ended 10 hours ago. I'm not sure why it's using up so many requests while I used/entered the API key in a private channel.

Also applies sometimes when the API is working fine (still in its quota). YouTuber was live, and I was forced to re-add the streamers channel for it to mention it to be live as per example:

![image](https://user-images.githubusercontent.com/6794064/68073334-461d8080-fd8f-11e9-8399-244e4596f69c.png)

The most top reply from the bot is from the RSS cog which shows the live notification.

Makes me think atm that the live stream mention function is somewhat in its alpha stage.

#### How can we reproduce this issue?

Thus far I used 2 keys total, all maxed out in a few hours. Am I the only one who is having this issue?

**Comment by Drapersniper** [comment]
For for clarity, for anyone else reading this.

10,000 quota is not a lot at all, using the search/list end points that is only 100 calls

Also the youtube api key is shared with the audio cog so if any of your users are playing Spotify albums or playlists it will use some quota too

**Comment by Skyridr** [comment]
I'm not using the audio cog though. So why would it make so many requests for a single YouTube live monitor? I'm not monitoring anyone else, only one person.

**Comment by Drapersniper** [comment]
As it is it check every 1 minure

**Comment by Drapersniper** [comment]
But to clarify I'm aware there is planned changed to the stream cog to help this, however no ETA, and this the quota issue is a limitation by the YouTube Data API,  you could try to apply for an increased quota.

In regards to the bug where the live stats is being shows at the incorrect times i'll let someone more familiar with the streams cog answer that

**Comment by Skyridr** [comment]
Which in total are 1,440 requests in total per day ^^. 

As for the live not properly showing, also applies sometimes when the API is working fine (still in its quota). YouTuber was live, and I was forced to re-add the streamers channel for it to mention it to be live as per example:

![image](https://user-images.githubusercontent.com/6794064/68073334-461d8080-fd8f-11e9-8399-244e4596f69c.png)

The most top reply from the bot is from the RSS cog which shows the live notification.

Makes me think atm that the live stream mention function is somewhat in its alpha stage.

**Comment by Drapersniper** [comment]
> Which in total are 1,440 requests in total per day ^^.

and that translates to 144, 000 quota /channel/day

**Comment by Jackenmen** [comment]
Fixed in #3237
