### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by zubairfazal** [Cog-Creators/Red-DiscordBot#3096]
# Feature request

#### Select the type of feature you are requesting:

- [ ] API functionality

#### Describe your requested feature

I would love to sharding implemented.

**Comment by Drapersniper** [comment]
If you mean bot sharding, it already is.

If you mean something else please try to be more detailed

**Comment by Vexed01** [comment]
Your bot will automatically shard when sharding is needed. You can't force it to shard yourself.

**Comment by Flame442** [comment]
Red will automatically shard when it reaches a large number of guilds. Red tends to start sharding at about 1000 guilds.
