### ISSUE TITLE
Redbot --no-prompt and --no-instance flags do not work in Docker

### ISSUE THREAD

**Issue by LGACode** [Cog-Creators/Red-DiscordBot#3097]
# Other bugs

#### What were you trying to do?

Create a Docker container for Red v3

#### What were you expecting to happen?

Allow Docker to run `redbot` command without entering the CLI setup, passing all necessary info via flags.

#### What actually happened?

The error "You need to configure the bot instance using `redbot-setup` prior to running the bot." appears when running the named instance for the first time, regardless of what flags are used.

#### How can we reproduce this issue?

1. Create a Dockerfile to build Red v3. Include an Expect script to answer the CLI questions when running `redbot-setup`.
2. Attempt to run the new Redbot named instance created in step 1 during the Docker image build process. Docker will always respond with the error "You need to configure the bot instance using `redbot-setup` prior to running the bot."

View the below conversation on Red - Discord Bot Discord server for full context:
Beginning - https://discordapp.com/channels/133049272517001216/387398816317440000/640548950247735299
End - https://discordapp.com/channels/133049272517001216/387398816317440000/640565405261234197

**Comment by Kowlin** [comment]
At the moment a workaround is to create (or simply copy and edit and existing) ``config.json`` and place that in the docker container's ``~/.config/Red-DiscordBot`` folder (Make it if it doesn't exist), this will circumvent the need to use the setup cli for making an new instance. I had an working example on my main desktop which I cannot access ATM, will update it here with an working docker experiment that I had.

**Comment by Kowlin** [comment]
As promised the docker files that I had some success with: https://gist.github.com/Kowlin/64c848df14c68e5d2c0439ffac922480

Edit: Also this isn't technically a bug as the setup is functioning as expected. Red ATM isn't really suited for docker deployment without some external help. See my first comment.

**Comment by LGACode** [comment]
This issue appears to have been resolved in later versions of Red. Not sure which version specifically resolved this.
