### ISSUE TITLE
Permissions cog can be denied losing access to the cog entierly

### ISSUE THREAD

**Issue by kennnyshiwa** [Cog-Creators/Red-DiscordBot#3107]
# Command bugs

#### Command name

permissions setdefaultserverrule

#### What cog is this command from?

permissions

#### What were you expecting to happen?

when trying to do ``[p]permissions setdefaultserverrule deny Permissions`` for it to say it can't disbale access to the permissions command/cog similar to how ``[p]command`` can't be disabled

#### What actually happened?

The cog was denied and unable to be allowed back

#### How can we reproduce this issue?

1. ``[p]permissions setdefaultserverrule deny Permissions``
2. try and use any permissions commands

**Comment by Kowlin** [comment]
Its worth noting that owners will keep access to the entire suite of commands regardless if their blocked or not, so I'm hesitant on calling this a bug.

**Comment by palmtree5** [comment]
Inclined to agree with @Kowlin on this

**Comment by mikeshardmind** [comment]
This is a bug, but it's also a low priority to handle since it requires willfully locking yourself out. We can prevent a guild owner from locking themselves out without allowing this to bypass global permission settings.
