### ISSUE TITLE
[Audio] Play breaks on disabled lavalink services

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#3113]
# Command bugs

#### Command name

play

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Either default back to the "Nothing found" message, or let me know lavalink didn't respond to the query.

#### What actually happened?

after some amount of time, 

```
Nov 11 16:08:37 scw-555b42 redbot[5451]:   File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 1005, in __aenter__
Nov 11 16:08:37 scw-555b42 redbot[5451]:     self._resp = await self._coro
Nov 11 16:08:37 scw-555b42 redbot[5451]:   File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 497, in _request
Nov 11 16:08:37 scw-555b42 redbot[5451]:     await resp.start(conn)
Nov 11 16:08:37 scw-555b42 redbot[5451]:   File "/usr/local/lib/python3.7/dist-packages/aiohttp/client_reqrep.py", line 844, in start
Nov 11 16:08:37 scw-555b42 redbot[5451]:     message, payload = await self._protocol.read()  # type: ignore  # noqa
Nov 11 16:08:37 scw-555b42 redbot[5451]:   File "/usr/local/lib/python3.7/dist-packages/aiohttp/streams.py", line 588, in read
Nov 11 16:08:37 scw-555b42 redbot[5451]:     await self._waiter
Nov 11 16:08:37 scw-555b42 redbot[5451]: aiohttp.client_exceptions.ServerDisconnectedError: None
```

#### How can we reproduce this issue?

set youtube to `false` in lavalink's application.yml (Was testing the viability of this with changes to youtubes ToS pending for December)

**Comment by Drapersniper** [comment]
I'll get a fix up for this some point this week.

**Comment by mikeshardmind** [comment]
Upon closer inspection, this appears to have already been fixed in dev, issue here was me testing with the wrong instance. Nothing to see here.
