### ISSUE TITLE
Emit events when a shared API token is changed

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#3134]
# Feature request
#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature
Should emit the name of the service which was updated. This will allow cogs to cache the values and only update when if they change.

**Comment by Zephyrkul** [comment]
Doesn't config already use a cache? Also, would it be worth expanding the event scope to consider config changes overall?

**Comment by mikeshardmind** [comment]
Config doesn't cache for DB backends. This is one of the only places 3rd party code might be caching a setting in nonobvious way (such as a single aiohttp client session) and should receive an indication to update
