### ISSUE TITLE
[Audio] Help of `[p]audioset emptydisconnect` should mention precedence of `[p]audioset dc`

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3140]
Help of `[p]audioset dc` already does that, I think it might be good to also say that in help of `[p]audioset emptydisconnect`

**Comment by Drapersniper** [comment]
Can be assigned to me and i'll get it done .. for once i'll det a 1 line PR done 🏆 (No guarantee though this may end up in a 5k PR)
