### ISSUE TITLE
Allow More Than One Owner

### ISSUE THREAD

**Issue by LGACode** [Cog-Creators/Red-DiscordBot#3156]
# Feature request

Please allow more than one owner for a bot. This is especially useful for companies using Red as a team.

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [ ] API functionality

**Comment by Kowlin** [comment]
Co-owners can be assigned with the ``--co-owners`` flag when launching Red, checkout ``redbot --help`` for more information on that. Team support is pending development (under #2781) while we wait for Discord.py to add in team support.

**Comment by Vexed01** [comment]
More info about the `--co-owner` flag, from SaltBot's response to the `>coowner` custom command in [discord.gg/red](https://discord.gg/red):

![image](https://user-images.githubusercontent.com/51716387/69670239-5de4dd80-108b-11ea-8121-a2999463bfb9.png)

**Comment by mikeshardmind** [comment]
Further note: our team support when added will require users to specify they want the support. There may be a difference with "I trust you having access to the token for the purposes of the server's future" and "I trust you running code on the machine this is hosted on"

**Comment by LGACode** [comment]
This is exactly what I was looking for, thank you. Excited to see what the teams feature will bring.
