### ISSUE TITLE
Some form of audio error I've never seen before.

### ISSUE THREAD

**Issue by GostOmega** [Cog-Creators/Red-DiscordBot#316]
![console_error2](https://cloud.githubusercontent.com/assets/18472043/16218325/5dc7c43e-374a-11e6-8152-31e2d87b34ec.png)

Can someone please educate me on how this came to be? Someone called for a playlist that consisted of 3 songs, and the audio stopped (or so I've been told) when the playlist reached the end of the final song. At this time console looked fine because I check it ever 30 minutes or so, but a few hours later, the console was spamming this error (bot still online but a bit laggy at responding). What is weird to me is that no one did any audio commands during those few hours.

If anything I find it a little bit funny and curious on how this happened and why it didn't spam earlier.  I stopped the bot from playing the audio, that seemed to stop the spamming. Restarted console and now I'm here.

P.S. I blacked out the directories that are private, sorry.  :(

**Comment by irdumbs** [comment]
what was the link to the playlist you used?
or if it was local / edited, what 3 songs?

**Comment by GostOmega** [comment]
One of my girlfriend's playlist called "[Cute songs](https://www.youtube.com/playlist?list=PLD2P7U9UgAZT-pWkA6UmIprRcH7YrKxb9)"
She's half Japanese so she likes to listen to this music, and so do her friends on her Discord server.
It's her server, I'm just the guy who keeps the bot running and everything organized lol.

**Comment by Kowlin** [comment]
For the developer side, things to note from this that it seems to occur from a SSL error especially a "EOF occurred in violation of protocol". I will see what I can do.

**Comment by tekulvw** [comment]
It just seems like it was a one off thing (assuming this doesn't happen every single time?)

**Comment by GostOmega** [comment]
@tekulvw Ya just the one time. I mentioned above I was just curious on what this meant, or if it's something to worry over.

**Comment by Kowlin** [comment]
I think we can write it off as a one time occurrence. But regardless I'm still interested on what is triggering this.

**Comment by tekulvw** [comment]
In all honesty probably just internet shitting out, gonna close for now
