### ISSUE TITLE
[Downloader][RepoManager] Track failing repos in context of RepoManager

### ISSUE THREAD

**Issue by wereii** [Cog-Creators/Red-DiscordBot#3162]
- [x] cog change

## Influences:
- Downloader & RepoManager
**All of this is based on current downloader changes as seen in #3080**

### Context
- As of now, if repository update fails with UpdateError (`git pull` failed, [code](https://github.com/Cog-Creators/Red-DiscordBot/blob/a47d758c4dc6d688490992d8c0b46f51807dc30b/redbot/cogs/downloader/repo_manager.py#L1160)) the failed repo's name is added into `failed` collection and then the collection is additionally returned (this is a change introduced in #3080, eg. `return ret, failed`).
- Because of this change to the "backend" of downloader's updating commands, all methods that are currently handling any repo updating (methods behind `[p]repo update` or most of methods from `[p]cog`) have to propagate the collection of `failing` repos out up to `message` context - so the called commands can successfully report that some of the ["repos have failed to update" ](https://github.com/wereii/Red-DiscordBot/blob/a47d758c4dc6d688490992d8c0b46f51807dc30b/redbot/cogs/downloader/downloader.py#L1242).
- Basically main point behind this is: even if one or multiple fail to update, everything else continues (if it has to) and the failing status is reported to user.

### What
- Moving the whole `failing` collection into context of RepoManager instead of carrying and propagating it around (`return (ret, failing)`)
- the main idea is that [`RepoManager.update_repos`](https://github.com/wereii/Red-DiscordBot/blob/a47d758c4dc6d688490992d8c0b46f51807dc30b/redbot/cogs/downloader/repo_manager.py#L1130) (and [`RepoManager.update_repo`](https://github.com/wereii/Red-DiscordBot/blob/a47d758c4dc6d688490992d8c0b46f51807dc30b/redbot/cogs/downloader/repo_manager.py#L1112) too) would (instead of carrying the collection locally) move the failed Repo objects into context of RepoManager: `RepoManager.failing: set()` but **as well remove the repo if it's already in there** but didn't error this time (examples: github is momentarily down, someone deleted branch and then reverted it), basically _keep track_ of repos that failed last time update was ran (on them)
- *Important notice:* the methods `update_repo/s` would still return failed repo/s as normally (for example in `update_repo: -> return (repo, (old, new))` but their old/new commits would stay the same, eg. "there is nothing to update" which most of the time means calling methods would skip these repos: "nothing to do with this one"
- meths under `[p]repo delete` would obviously have to check and remove the repo from the context too

### Why
- Mainly to avoid carrying around the `failing` collection thru out multiple methods, up back into `message ctx` where it's main purpose is to be formatted and sent as "warning" message to user, this is most significant in [`Downloader._cog_update_logic`](https://github.com/wereii/Red-DiscordBot/blob/a47d758c4dc6d688490992d8c0b46f51807dc30b/redbot/cogs/downloader/downloader.py#L770).
- Like this, for example the `_cog_update_logic` would do it's work (updating repos, getting new cogs, ...) as it should and just additionally, at the end, check the `self._repo_manager.failed` and if it's not blank, inform user about some repos [`failing`](url)

### Possible problems
- (raised by @jack1142 in Discord) concurrency - if two updating commands are running at the same time, magic happens (updating commands should `lock`, or anything updating-wise under it)

**Comment by Drapersniper** [comment]
Are you going to clear the context once the command is done running? Don’t think we should cache the failing repos for follow up commands

**Comment by wereii** [comment]
>Don’t think we should cache the failing repos

I think this is a wrong view on this, If the following commands don't **directly** access failed repos, their behavior won't change because this is considered only in `repo updates`.

Example behavior is:
- command A: calls update on all repos, two failed, let's call them X and Y, they are added into `.failing`, command A finished it's work, checks `.failing`, formats and warns user repo X and Y failed to update
- command B: calls update on some repos, one of them is X, all the selected repos, even X will try to get updated, X now doesn't fail, so the updating method checks if X is in the `.failing` and removes, command finishes work and checks `.failing` and warns user that now only `Y` is failing

**Comment by Drapersniper** [comment]
When would the failing repos be cleared ? Because as a cog creator what happens if I fix what was causing it to fail and it’s cached ?

**Comment by wereii** [comment]
> When would the failing repos be cleared ? Because as a cog creator what happens if I fix what was causing it to fail and it’s cached ?

All repos are still checked when update is called on them; if the repo failed before and it does not fail now it's removed from `.failing`

The important principle behind `.failing` is the `command finishes work and checks .failing and warns user`. So instead of carrying it around in every function, you can update whatever you want, and at the end just check & warn.

EDIT: if you do a diff on `downloader._cog_update_logic` before any failing repos logic and after, it had to be shuffled a lot to support the "once finished send warning some repos failed", the "once finished" (or "at the end") means, that with avoiding code duplication, the function has to always end in one point, so the typical design `if: return if: return` (instead of `if: else:`) had to be changed.

**Comment by mikeshardmind** [comment]
I don't think it's appropriate as an instance variable here. It's info from the result of a specific method call which other calls need, not info which belongs to the repo manager. I know that may sound like a pedantic difference on the surface given how the repo manager class is used in the bot as a single instance driven by commands, but I believe in the principle of least surprise. It makes it easier to work with code which you aren't personally familiar with and therefore makes it easier for other people to also work on the code later on.

**Comment by wereii** [comment]
@mikeshardmind That's definitely a point.

My view was that, the way these fails are handled right now, the `failed` collection is only needed in the command's method (or within `ctx`), any underlying utility method that calls update on repos now has to carry it even it doesn't really care about them.
I might even say that the content of `failed` is not dependent on `.repo_update/s` caller's context, there are no params, the update mechanism is always the same, if the repo is broken the result is the same among all commands calling repo updates. 

That's my last words, I will be closing this in a few days if there is nothing else.
