### ISSUE TITLE
Send DM on join

### ISSUE THREAD

**Issue by josiec09** [Cog-Creators/Red-DiscordBot#3170]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [x] API functionality

#### Describe your requested feature

Would like to be able to send a custom welcome message as a DM to members when they join. Mee6 bot for an example.

**Comment by kennnyshiwa** [comment]
there are 3rd party cogs that are able to do this such as trustys welcome cog, all of which can be found at https://cogboard.red/t/approved-repositories/210

**Comment by Flame442** [comment]
This is better suited to be a cog, rather than a feature of the core bot. You can search for or request a cog on our cogboard (linked above).
