### ISSUE TITLE
Anyone know how to fix this?

### ISSUE THREAD

**Issue by AsuraSushi** [Cog-Creators/Red-DiscordBot#318]
Been working just fine and recently a lot of songs give me this error:

http://puu.sh/pHtjn/6117bff60c.png

I'm just not good with this kind of stuff.

**Comment by Specro** [comment]
Try updating youtube-dl: 
`pip3.5 install --upgrade youtube_dl`

**Comment by Kowlin** [comment]
Can confirm that this works, updating youtube_DL will resolve this issue. There was a breaking in the YouTube API.

**Comment by rustty** [comment]
Got it to work again. Used this:
`pip install --upgrade youtube_dl`

**Comment by tekulvw** [comment]
YTDL Issue
