### ISSUE TITLE
[Permissions] More ways to set rules

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#3181]
# Feature request

Negations, neutrals, and more.

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

It's not uncommon for someone to want to restrict command or cog to a specific channel, without wanting to unlimit it in that channel. Currently, permissions can only do this by denying to each other channel manually.

The ideal solution is to add an ordered rules mode which allows expressions (such as `not channel`)

This mode *would* likely be restricted to being managed by yaml for core commands due to the interactive complexity otherwise.

The configuration would be exposed for 3rd party plugins to make it easy for 3rd paties to create rule installers which dont need to act as a permission hook to function.

**Comment by DevilXD** [comment]
Would this special mode support the ability to set the `who_or_what` to something like `mod` or `admin` that'd allow to restrict a command to either the Mod or Admin role set in the config? as far as I'm aware this isn't possible right now, and it'd be useful to "downgrade" certain commands from their `admin_or_permissions` status to `mod_or_permissions` globally, without having to add this overwrite for each mod role on each server.

This would also make it much easier to do changes later on, like changing the mod role (would have to rebind all overwrites to the new role too).
