### ISSUE TITLE
How do I fix this error?

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#319]
http://prntscr.com/bllh95

**Comment by franc-ist** [comment]
Update discord.py `pip3 install --upgrade git+https://github.com/Rapptz/discord.py@async`

**Comment by ghost** [comment]
I have done that, I do that every time I start it.

**Comment by franc-ist** [comment]
@rustty if you did it, you wouldn't get the error

**Comment by Sevenn83** [comment]
Your youtube-dl binary is up to date ?

(same problem here #318)

**Comment by Kowlin** [comment]
Cross-post from #318 

Can confirm that this works, updating youtube_DL will resolve this issue. There was a breaking in the YouTube API.

**Comment by ghost** [comment]
fixed. Used this:
`pip3.5 install --upgrade youtube_dl`
