### ISSUE TITLE
[aiohttp] issues in py38

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3196]
re: https://github.com/aio-libs/aiohttp/issues/3644

On Python3.8 theres an issue with aiohttp 3.5.4 which is the version bundled with red currently. didn' take time to look into the full affect of it but theres been at least 1 report of a used using RPC and Py38 and hitting the afore mentioned bug

**Comment by mikeshardmind** [comment]
closing with #3288
