### ISSUE TITLE
Add maxheight to [p]helpset

### ISSUE THREAD

**Issue by LGACode** [Cog-Creators/Red-DiscordBot#3197]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

Please add a new command `maxheight` in `[p]helpset` to control the maximum height of help page embeds. I think this would be much more useful than `pagecharlimit`.

**Comment by Drapersniper** [comment]
That’s not something that the bot can control.

All we can limit is content per page but I can make a Very tall embed with only a new characters

**Comment by Flame442** [comment]
Although we can technically track how many newlines are used, the width of a users screen could make an embed taller than expected. There isn't any way to effectively limit the height of an embed.

**Comment by mikeshardmind** [comment]
I'm going to close this one for now. We can revisit it as an idea if discord ever lets bots provide a full oEmbed object with more control over it as a result.
