### ISSUE TITLE
Development deps

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3198]
# Other bugs

#### What were you trying to do?

Install Red development environment.

#### What were you expecting to happen?

The install to not error.

#### What actually happened?

ERROR: tox 3.14.2 has requirement importlib-metadata<2,>=1.1.0; python_version < "3.8", but you'll have importlib-metadata 0.19 which is incompatible.

#### How can we reproduce this issue?
Tested on python version 3.7.3

1. Clone Redbot
2. Do make.bat newenv

**Comment by Jackenmen** [comment]
Fixed in #3288
