### ISSUE TITLE
Audioset vote

### ISSUE THREAD

**Issue by Mikethe3rd** [Cog-Creators/Red-DiscordBot#321]
it doesn't do any effect, no matter to what I change it.

**Comment by irdumbs** [comment]
it has not been implemented yet since the change to new audio. it will be reimplemented.

**Comment by Mikethe3rd** [comment]
Okay thanks, any ETA? I assume a few weeks atm qq

**Comment by irdumbs** [comment]
no ETA but that sounds about right. (at least for it being written, not approved)

**Comment by Mikethe3rd** [comment]
Damn alright then, if possible I kind of want to keep this thread open so you can notify me when it works again.

**Comment by calebj** [comment]
Implemented in #340

**Comment by tekulvw** [comment]
#340 should be merged soon, closing
