### ISSUE TITLE
Show Server IDs in servers Core Command

### ISSUE THREAD

**Issue by LGACode** [Cog-Creators/Red-DiscordBot#3224]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature
Please show Server IDs when using the `servers` command. This would be useful to help report malicious servers that adds your bot without permission.

![image](https://user-images.githubusercontent.com/6125912/71493821-4d955f00-27ff-11ea-84b8-f628f5d9eedc.png)

**Comment by Stonedestroyer** [comment]
I will be taking this on if @Bakersbakebread wasn't on it as I saw your closed PR.

**Comment by Bakersbakebread** [comment]
Feel free. 😊
