### ISSUE TITLE
[Informational][Audio] Audio refactorization for 3.3/3.4

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3226]
## Goals

1. Simply audio to make maintenance easier
2. Expose a large part of the audio functionality through public APIs
3. Reduce duplicated code
4. Improve performance

## Steps

- [x] Separate Audio file into multiple parts
- [ ] Make version guaranteed Public APIs that the Audio cog makes a use of
- [ ] Enforce Lavalink.jar for the public API on a non standard port that can be overwritten by an external API
- [x] Improve Audios namespace
- [x] Type hint audio fully 

### Public API planned functionality 

1. Enqueue tracks
2. Insert track on 0 index
3. Skip Tracks
4. Stop playback
5. Change volume 
6. Expose YouTube and Spotify APIs
7. Expose Local and Global cache entries
8. Pause playback
9. Shuffle Tracks

Note: The plan to ensure the API uses all the existing audio Restrictions 
 such as DJ Role and restricted keywords and vote system.

**Comment by mikeshardmind** [comment]
Note: As the required changes would either be additions to the parts of the bot we do guarantee or modifications/removals of parts not covered under a versioning guarantee, these changes can be made whenever deemed ready, The version here could very well be 3.2.1 should they be ready and reviewed at that point, however unlikely that may be given the scope of the changes intended.
