### ISSUE TITLE
Giving up after 0 retries

### ISSUE THREAD

**Issue by Lash-L** [Cog-Creators/Red-DiscordBot#323]
My bot will completely stop working when some commands are used. But sometimes the commands will work. For example, I just tried !version, !modset, and !help. and the console just said "ERROR:Giving up after 0 retries" 3 times and stopped playing music completely. The boy has stopped working quite a bit. Any fixes?

**Comment by Kowlin** [comment]
Mind posting your full log in here?

**Comment by Lash-L** [comment]
http://pastebin.com/tu0Y1JqM

**Comment by Kowlin** [comment]
Updating your Discord.py with the following command should resolve the problem `pip3 install -U git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice]`

**Comment by Lash-L** [comment]
I tried that and actually it stopped working completely. I just reinstalled it and it's working without an issue now.
