### ISSUE TITLE
[Trivia] `[p]trivia stop` isn't Permissions-friendly

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3233]
https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/cogs/trivia/trivia.py#L237-L243

**Comment by Flame442** [comment]
Could just use a custom check

**Comment by mikeshardmind** [comment]
For anyone looking to fix this with a custom check:

you'll want to implement the check using : `redbot.core.commands.permissions_check` (see [here](https://github.com/Cog-Creators/Red-DiscordBot/blob/e776b5ca1a3ac14ac2573826510cdfe4dbde382e/redbot/core/commands/requires.py#L617))

**Comment by Flame442** [comment]
We might want to comb through the bot and look for these, users are running in to similar issues with other commands such as `[p]bank set`.
