### ISSUE TITLE
3.2 wrapup tasks

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#3243]
The following all need to be done at the end of the 3.2 release cycle prior to either a release candidate or a release. I'm noting it here so it does not get lost.

[X] Review modules to ensure nothing which should be private and exempt from versioning guarantees was missed
[ ] ~~Add `from __future__ import annotations` to all non-cli code (this will error on bad version matches, and we want to warn the user gracefully they have an incompatible python version)~~
[ ] Review dependency versions and consider bumps situationally, excluding black (see below)
[X] Consider a Lavalink Jar bump for 3.1.9 to give people more time to transition to 3.2 with cog developers handling the breaking changes (considered, not happening)
[ ] Update black and do a formatting pass (we want a new behavior, but this should be *last* code change since it has the potential to conflict with all the things)

**Comment by mikeshardmind** [comment]
Related: #3196, #3198

**Comment by mikeshardmind** [comment]
Also related: #2802 (handled)

**Comment by Drapersniper** [comment]
Add a change log to #3279 that `[p]playlist download` will now compress playlists larger than the server attachment limit and attempt to send that.

**Comment by mikeshardmind** [comment]
Changelog handled.
