### ISSUE TITLE
Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by brad342** [Cog-Creators/Red-DiscordBot#326]
I'm a noob at this, so please bear with me. I have the Bot setup in discord and everything, but whenever I type !play [link] I get a message saying; Signature extraction failed: Traceback (most recent call last):
the message also says to update youtube.dl but i have NO CLUE how to do that! answers much appreciated!

**Comment by Twentysix26** [comment]
Command prompt:
`pip3 install --upgrade youtube_dl`

**Comment by brad342** [comment]
THANK YOU so much :)
