### ISSUE TITLE
Aliases do not work for custom commands

### ISSUE THREAD

**Issue by mvanalphen** [Cog-Creators/Red-DiscordBot#327]
It does not seem to be possible to set up an alias for custom commands. For instance (and to reproduce):

`!addcom example This is an example.`
`!alias add test example`
`!test`

This should add an alias for the custom command !example, namely !test. However, when using !test nothing actually happens. There's no errors in the Red log file either.

While debugging it turns out that everything works well in the check_aliases function (it works the same way it does for a regular bot command), but process_commands does not seem to execute the custom command.

I've only been able to confirm this on my server - if there's a workaround I'm happy to use it!

For the record, I'm running the bot on Ubuntu 15.10.

**Comment by GostOmega** [comment]
Check your `\data\alias\aliases.json` and `\data\customcom\commands.json` and check for misspelling maybe? I did my own test on my girlfriend's server and it worked for me, same example you provided. Assuming you're not using an outdated version of discord.py and/or Red Bot.

**Comment by mvanalphen** [comment]
I checked both, and ran them through a json validator. It works fine for regular commands, but not for custom commands. I last pulled yesterday, so I should be on the most recent version of the develop branch.

If I remember correctly, setting aliases for custom commands did work when I ran the bot locally on Windows. After I moved it to a VPS on Ubuntu it no longer worked. Could that be the cause?

**Comment by tekulvw** [comment]
This happens because both aliases and custom commands listen to the `on_message` event and I chose not to dispatch a new, fake message object each time an alias was used. If I do, it will cause other cogs to believe it to be real and introduce exceptions when they try to act on it. Slightly modifying this process to allow custom commands to work may be something we look into in the near future.

**Comment by mvanalphen** [comment]
Excellent, thank you for the clarification!
