### ISSUE TITLE
Advanced Aliases

### ISSUE THREAD

**Issue by JedMoody** [Cog-Creators/Red-DiscordBot#328]
I'm having trouble adding extended aliases to Redbot.

Using the alias command or other, how can I create an alias for example that plays a local playlist, shuffles that playlist and then skips the first song?
So the bot will put in commands '!local all', '!shuffle' and then '!skip' all in succession.

I saw on the alias wiki there was something about 'create_task' but I'm not sure how to work that or input it at all, mentioning there are currently no examples.

Any help would be greatly appreciated!

**Comment by tekulvw** [comment]
Currently there is no way to "nest" commands in aliases like you are suggesting, though it is something we may look into in the future.
