### ISSUE TITLE
Cannot answer to roll

### ISSUE THREAD

**Issue by Sinnoma** [Cog-Creators/Red-DiscordBot#3284]
# Command bugs

#### Command name

`roll`.

#### What cog is this command from?

From : `General`.

#### What were you expecting to happen?

The command should answer the number.

#### What actually happened?

The command return an error message. `Command raised an exception: HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.`

#### How can we reproduce this issue?

You can use this command : 

`.roll 99990123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789`

The bot CAN answer to this, it just need to remove the author mention and the 2 🎲

**Comment by mikeshardmind** [comment]
I'm inclined to say we cap roll to a reasonable number rather than special case long output.

**Comment by Flame442** [comment]
I think that setting an upper limit on the size of a dice roll is a better solution for this than attempting to change the output after the fact.

**Comment by Stonedestroyer** [comment]
I will take this on.

**Comment by Drapersniper** [comment]
2**64 -1 is a Known number to work, I think setting a max cap to this is an acceptable amount ...
