### ISSUE TITLE
[Core] Information about out-of-date version shows if newer version is release candidate

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3287]
# Other bugs

I actually haven't encountered it, but by looking at the code, it looks like out-of-date notification is gonna be sent on alpha/beta/release candidate releases too.

**Comment by mikeshardmind** [comment]
It might. Depends on if the response from pypi includes these. We can do a simple filter just in case.

**Comment by Stonedestroyer** [comment]
Can confirm it happens on dev.

`Your Red instance is out of date! 3.1.9 is the current version, however you are using 3.1.8!`

**Comment by Jackenmen** [comment]
This is not what I meant, @Stonedestroyer, this issue is about alpha/beta/rc releases on PyPI triggering out-of-date message, yours however is about missing version bump in V3/develop branch.

**Comment by Jackenmen** [comment]
PyPI doesn't return info about pre-releases in `data["info"]` so this issue is actually invalid.
