### ISSUE TITLE
Playing from Youtube Error

### ISSUE THREAD

**Issue by infrasparker** [Cog-Creators/Red-DiscordBot#329]
# ***If you are experiencing issues with Audio, please read***
*This issue has been resolved. New issues with Audio are tracked in #4505. If you need additional help, please feel free to join our support server at https://discord.gg/red*

---

Redbot throws an error every time I attempt to !play using youtube search options.
For instance, when I type:
!play retro funky sundance
in the discord chat, I see

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Infrasparker\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Infrasparker\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Infrasparker\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\Infrasparker\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Infrasparker\Documents\Red-DiscordBot\cogs\audio.py:1750> exception=AttributeError("'NoneType' object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "C:\Users\Infrasparker\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Infrasparker\Documents\Red-DiscordBot\cogs\audio.py", line 1781, in queue_manager
    song = await self._play(sid, url)
  File "C:\Users\Infrasparker\Documents\Red-DiscordBot\cogs\audio.py", line 730, in _play
    song = await self._guarantee_downloaded(server, url)
  File "C:\Users\Infrasparker\Documents\Red-DiscordBot\cogs\audio.py", line 542, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "C:\Users\Infrasparker\Documents\Red-DiscordBot\cogs\audio.py", line 206, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'

In the console.
I don't really know where to start reading the error message, but since I know red is working for others can anyone help me? Thanks.

EDIT: Missposted. Already found solution to this issue.

**Comment by Twentysix26** [comment]
I guess you fixed this with  
`pip3 install --upgrade youtube_dl`

**Comment by infrasparker** [comment]
Yeah, exactly. Sorry for the spam[?] thread.

**Comment by graysonspop4444** [comment]
please help i know absolutely nothing about bots and when i plug that command into the terminal for my mac it does nothing

**Comment by palmtree5** [comment]
If the bot's running, commands should be entered inside discord

**Comment by Rekiamer** [comment]
how do I enter the command in the bot? or in the discord
have the same problem

**Comment by palmtree5** [comment]
You should just be able to install requirements via the launcher @Rekiamer

**Comment by redsmok04** [comment]
wq

**Comment by redsmok04** [comment]
i have this error ModuleNotFoundError: No module named 'youtube_dl'

**Comment by bobloy** [comment]
Ask your question in the discord instead of commenting on a year old Issue
https://discord.gg/red

**Comment by xxtensazenxx** [comment]
if you join the discord they'll just say its out of scope and not help you. Most unhelpful dev's I've seen in a while
