### ISSUE TITLE
[Trivia] Trivia answer matching too permissive

### ISSUE THREAD

**Issue by EricChiz** [Cog-Creators/Red-DiscordBot#331]
All trivia answers will match within a line instead of only the whole line. This works the majority of the time, but also results in things like "chair" matching an answer of "air".

**Comment by Twentysix26** [comment]
I guess I could restrict it a bit and check the individual words against the correct answer

**Comment by CRASNY** [comment]
`if answer in message.content.lower():` to `if answer == message.content.lower():` seems simple enough.
