### ISSUE TITLE
[DEV] Dependancy requirements mismatch

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3329]
# Other bugs

#### What were you trying to do?

Install Red-Bot from dev and run `make newenv` from the red folder and then launch the bot using redbot-setup. 

#### What were you expecting to happen?

The bot setup to launch. 

#### What actually happened?

Package entry mismatch error. 

```
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (aiohttp 3.6.2 (c:\users\stonedestroyer\onedrive\coding\Red-DiscordBot\.venv\lib\site-packages), Requirement.parse('aiohttp<3.6.0,>=3.3.0'), {'discord.py'})

```

#### How can we reproduce this issue?

1. Install Red from Github. 
2. Use `make newenv`
3. Do redbot-setup, do not use python -m redbot-setup.

**Comment by mikeshardmind** [comment]
We won't be directly fixing this.

Right now, we have a version mismatch which will be resolved *eventually* on dependencies where we tested to ensure it was fine.

Setuptools's entrypoints don't handle this well with editable installs.

For now, you can use `python -m redbot.setup` with editable installs for development.

**Comment by mikeshardmind** [comment]
Leaving this open; While we won't be directly fixing it, let's hold closing this until it is resolved.
