### ISSUE TITLE
[Docs] `deadsnakes` only supports Ubuntu LTS releases

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3330]
We should point to pyenv install for non-LTS Ubuntu releases

**Comment by mikeshardmind** [comment]
Do we want to include docs for non-LTS releases? Right now, we only have docs for LTS releases and I don't neccessarily see an issue with that.

**Comment by mikeshardmind** [comment]
Oh, we removed the specification there that those docs were for 16.04/18.04 ...
