### ISSUE TITLE
Localtracks will not show symlinked folders in Red 3.2.2 on Ubuntu 18.04

### ISSUE THREAD

**Issue by crovaxon** [Cog-Creators/Red-DiscordBot#3332]
# Command bugs

#### Command name

local play

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Listing all the folders and tracks that are in localtracks.

#### What actually happened?

Symlinked folders were not showing up in the bot reply. Only local folders and files and symlinks of files show up.

#### How can we reproduce this issue?

1. Create a symlink to a folder containing music in localtracks:
`ln -s path/to/local/music/folder path/to/reds/localtracks/`
2. Initiate playing of local music in redbot:
`[p]local play`
3. Red will list folders and tracks for you to choose from. I observed that any local folders and files show up as well as symlinked files but the symlinked folder will not show up in the selection.

#### Additional context
This happens with Red 3.2.2, on Ubuntu 18.04 64 Bit. It has been working as expected prior to updating, which was Red 3.1.8.

**Comment by Drapersniper** [comment]
Can be assigned to me, will work on it in the next few days .... also fuck localtracks
