### ISSUE TITLE
Local playlist doesnt repeat?

### ISSUE THREAD

**Issue by lifegrain** [Cog-Creators/Red-DiscordBot#334]
all my local playlist doesnt want to repeat,i tried checking !repeat to see if it is toggled on
it says it is toggled on,also in console the bot does seem to try to repeat the playlist but failed
it just keeps showing this line in red text

data/audio/localtracks: No such file or directory

exactly that

**Comment by tekulvw** [comment]
Damn, missed this a while back...but at last it was fixed in a8cf519b
