### ISSUE TITLE
Audio not finding YouTube tracks

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#3341]
# Command bugs

#### Command name

Play
#### What cog is this command from?

Audio
#### What were you expecting to happen?

Audio cog to find and play the track.

#### What actually happened?

The bot returned cannot find anything.

#### How can we reproduce this issue?

I just installed the new version on Debian 9.4 VPS, I was testing and the play and playlist commands are not finding tracks

**Comment by Flame442** [comment]
Do you have the specific command you used? This isn't a very descriptive issue...

**Comment by ghost** [comment]
+play https://youtu.be/TCw0_tCrlhs
It keeps giving me Nothing found loading information from YouTube track failed

**Comment by Drapersniper** [comment]
![image](https://user-images.githubusercontent.com/27962761/72209864-40d56400-34ab-11ea-988f-e0e410e639ac.png)
IT seems to be working if you need further support join the support server this issue is not something to do with the code and can be closed.

**Comment by Flame442** [comment]
Server can be found [here.](https://discord.gg/red)
