### ISSUE TITLE
[Audio] Playlist copy message is incomplete

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#3344]
# Command bugs

#### Command name

[p]playlist copy name --from-scope Guild --to-scope Global
[p]playlist copy name --from-scope User --to-scope Global

#### What cog is this command from?

Audio

#### What were you expecting to happen?

For the resulting message to be complete.

#### What actually happened?

While using these commands the resulting message said

**Playlist Copied**
Playlist playlistname (637357548558876691) copied from guildname to the (665660417133248534).

This message should have the scope included and should have read:

**Playlist Copied**
Playlist playlistname (637357548558876691) copied from guildname to the Global scope (665660417133248534).

or "copied from guildname to Global" is fine as well.

#### How can we reproduce this issue?

Use playlist copy with moving the playlist to the global scope and look at the user facing message after the command completes. I have tried this with other scopes and they seem to be unaffected.

**Comment by Drapersniper** [comment]
Fixed by #3347
