### ISSUE TITLE
[Audio] Local track format in error message

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#3345]
# Other bugs

#### What were you trying to do?

Load a playlist with saved local tracks that were not present on the host.

#### What were you expecting to happen?

For the user facing message to be formatted properly for describing the local track.

#### What actually happened?

The item is formatted like it is an internet-based track.

Track Error
Something broke when playing the track.
[www.nevergetoveryou](localtracks//Music/Simon & Milo/Saturday Night/32 - www.nevergetoveryou.mp3)

#### How can we reproduce this issue?

Load in a localtracks track that will break in some way, or that isn't present on the host.

**Comment by Drapersniper** [comment]
![image](https://user-images.githubusercontent.com/27962761/72211163-9b2bf000-34be-11ea-8a20-fe4a9de4118a.png)
For context ...

**Comment by Drapersniper** [comment]
Fixed by #3348
