### ISSUE TITLE
(Audio cog) Bot no longer auto disconnects when notify is turned on.

### ISSUE THREAD

**Issue by ionite34** [Cog-Creators/Red-DiscordBot#3349]
# Other bugs - Audio Cog

Problem with core audio. When notify is turned on (audioset notify), bot will no longer disconnect when queue ends, even with auto disconnect setting on. Auto disconnect works after notify is turned off.

**Comment by Drapersniper** [comment]
![image](https://user-images.githubusercontent.com/27962761/72222291-ef84ad80-355a-11ea-8ba1-ab756058e8a1.png)
Not reproducible, care do provide me with more details of when and how this happens what commands you are using etc ... please join the support server at https://discordapp.com/invite/red and We can look at it in more detail... for now this issue can be closed as there is no issues with the code

**Comment by Drapersniper** [comment]
re... okay this was a misunderstanding on my part pinpointed the but and fixed already
