### ISSUE TITLE
[Commands] `ctx.tick()` - add optional message to send when bot can't react

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3359]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Change function definition of `ctx.tick()` to:
```py
async def tick(self, message: Optional[str] = None) -> bool:
```
So that we can set an optional message that will be sent if bot is unable to send the reaction. We could also make it possible through `ctx.react_quietly()` as well

**Comment by Drapersniper** [comment]
+1 on this.

**Comment by Kowlin** [comment]
I think this makes a fine small improvement to do.
