### ISSUE TITLE
Improve answer detection with Trivia

### ISSUE THREAD

**Issue by Brayzure** [Cog-Creators/Red-DiscordBot#336]
An issue that I've noticed is that, due to the small delay between when a message is sent and when it's actually received, a user that _appears_ to have sent the correct answer first does not actually get credit for it. I'm aware of why this happens, but it's hugely aggravating for many users that the credit for many questions simply goes to the fastest typist.

I suggest changing how answers are detected. Instead of taking the first valid answer, detection of a valid answer starts a very short (1 second or less), hidden timer during which any other user that submits the correct response _also_ receives credit. This would mitigate some of the issues with a user having higher than average latency, as well as appearing to be more fair.

**Comment by Twentysix26** [comment]
To be honest, I'm not even sure if what you're describing is an actual issue.

> that the credit for many questions simply goes to the fastest typist.

This is exactly how it's supposed to be. Sure it sucks for those with latency but there's not much I can technically do. That's a problem on their end.

**Comment by tekulvw** [comment]
Agreed, closing
