### ISSUE TITLE
[p]yt does not work most if not all of the time

### ISSUE THREAD

**Issue by notsaeegavas** [Cog-Creators/Red-DiscordBot#338]
When I try to use [p]yt and search something like, [p]yt rap god, nothing happens, but when I do, [p]play https://www.youtube.com/watch?v=XbGs_qK2PQA or something for the same song, it works. Can I get this to be fixed as I don't want to search it in youtube first and then copy the link just so I can play it in my discord server?

**Comment by tekulvw** [comment]
Likely just network error, closing
