### ISSUE TITLE
[p]shutdown and [p]restart stall on clean up

### ISSUE THREAD

**Issue by EcoSGPI** [Cog-Creators/Red-DiscordBot#3419]
# Command bugs

#### Command name

[p]shutdown and [p]restart

#### What cog is this command from?

Core

#### What were you expecting to happen?

Bot to shutdown or restart (with correct batch file, adjusted and verified in #support on main Red server)

#### What actually happened?

```
[2020-01-19 13:12:05] [INFO] red.main: Shutting down with exit code: ExitCodes.RESTART
[2020-01-19 13:12:05] [INFO] red.main: Please wait, cleaning up a bit more
````

That never finishes and closes/restarts/shuts down just sits with that message

#### How can we reproduce this issue?

Isolated issue it would seem, was told to create issue by support staff 

EcoS.GPI#0545
![bot resart](https://user-images.githubusercontent.com/37411547/72686067-86eb8280-3abe-11ea-9190-33cae493a580.png)

**Comment by mikeshardmind** [comment]
Need a bit more info, could we get the output of debuginfo and which cogs you have loaded?

**Comment by EcoSGPI** [comment]
```
Debug Info for Red
Red version
3.2.3
Python version
3.8.1 (32bit)
Discord.py version
1.2.5
Pip version
19.3.1
System arch
AMD64
User
Crystal
OS version
Windows 10 (version 10.0.18362)
Python executable
c:\users\crystal\appdata\local\programs\python\python38-32\python.exe
```

```
47 loaded:
account, admin, adventure, adventurealert, alias, application, autorole, away, backup, bank, banmessage, cah, cleanup, customcom, downloader, economy, economyraffle, editor, embedmaker, extendedmodlog, filter, forwarding, gallery, general, infochannel, leveler, mod, modlog, nolinks, permissions, raffle, reactpoll, reddit, relays, reports, retrigger, rift, rolemanagement, scheduler, serverstats, shop, starboard, sticky, tbs, tweets, warnsystem, welcome


5 unloaded:
audio, image, streams, trivia, warnings
```

**Comment by Jackenmen** [comment]
Can you replicate this when running Red with `--no-cogs` flag?

**Comment by EcoSGPI** [comment]
That allowed it to shutdown/restart properly and I was able to figure out it was the `tweets` cog by trusty causing the issue, I will take the problem to him, thank you!
