### ISSUE TITLE
[Core] Bot naming in set commands. 

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3428]
Currently we have the ability to be able to change the name under help using [p]set description due to licenseinfo command being added. 

There is some commands under set that uses Red when it refers to the bot but the newly added description command uses bot. Question is if the doc string for set and all subcommands that use Red should be changed to follow bot description for uniform naming or just be renamed to bot. 
![Screenshot_20200121-172727](https://user-images.githubusercontent.com/1307729/72823344-d7f0a780-3c73-11ea-9d02-834af8a1469a.jpg)

**Comment by Flame442** [comment]
If the `[botname]` replacement that was supposed to be added by #3063 is ever added in another PR, we could consider using that in these places.

**Comment by mikeshardmind** [comment]
That replacement was enabled as part of #3339 

+1 from me on these strings being updated with the exception of where "Red" refers to the project and the sing command, where it refers to the character the bot is named after.
