### ISSUE TITLE
[Audio] Lazy Scopes

### ISSUE THREAD

**Issue by NIXC** [Cog-Creators/Red-DiscordBot#3431]
# Feature request
#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Allow lazy searching scopes in audio. Its difficult to use global playlists right now because every command requires --scope global, even if there is no other playlist except the global one. There are other situations as well where it would be simpler to use if it just found the playlist you wanted instead of reporting it doesn't exist (in the current scope).

**Comment by Drapersniper** [comment]
resolved by #3430
