### ISSUE TITLE
[Docs] Installing Python on Mac

### ISSUE THREAD

**Issue by Sinnoma** [Cog-Creators/Red-DiscordBot#3436]
# Other bugs

#### What were you trying to do?

Tried to install to install Python 3.8 on Mac.

#### What were you expecting to happen?

2 things :
 - The argument `--with-brewed-openssl` could be recognized
 - Homebrew could install Python 3.8

#### What actually happened?

The argument `--with-brewed-openssl` isn't necessary anymore as I saw on [the following issue](https://github.com/Homebrew/homebrew-core/issues/8974)

Using the given command will also install Python 3.7 and not the 3.8 one, and need to be remplaced by the command : `brew install python@3.8`, according to Red 3.2.

#### How can we reproduce this issue?

Install Python as said on the documentation.

**Comment by aikaterna** [comment]
FWIW I can confirm that the `--with-brewed-openssl` is not needed and it looks like homebrew offers 3.8.1 as the Python 3.8 install.

**Comment by Sinnoma** [comment]
Also noticed
`brew tap caskroom/versions` has to be switched to `brew tap homebrew/cask-versions`

Using `brew cask install homebrew/cask-versions/adoptopenjdk11` :
`Error: Cask 'adoptopenjdk11' is unavailable: '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/adoptopenjdk11.rb' does not exist.`

I think that a full rewrite of this part of the doc is needed. Probably I can do this if I have time.
