### ISSUE TITLE
Use codeblocks in [p]local (folder|play)

### ISSUE THREAD

**Issue by ltukezl** [Cog-Creators/Red-DiscordBot#3466]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

to keep long paths more intact I'm suggesting for using code blocks when displaying the names of folders or files.

Current menu doesn't display long\path\names properly by truncating or making ugly annonations when escape characters are found (windows).

**Comment by Drapersniper** [comment]
Can you provide a screenshot of what you mean  by making ugly annonations
