### ISSUE TITLE
[Docs] Typo in Embed Helpers

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#3468]
# Other bugs

https://red-discordbot.readthedocs.io/en/stable/framework_utils.html#module-redbot.core.utils.embed

`redbot.core.utils.embed.randomize_color` says there is an alias called ``randomize_color`` though it should say ``randomize_colour``.

**Comment by yamikaitou** [comment]
That is RTD doing what it does. `randomize_colour` is the function in the code and `randomize_color` is the alias. If anything, the note about the alias could be removed from the docstring so it doesn't appear like that on RTD

**Comment by Dav-Git** [comment]
What's the preferred angle of attack on this? I can open a PR to remove the alias notice (which I don't think is the right choice) or try to figure out if I can get ``randomize_color`` to display a different string in the docs and open a PR thereafter,

**Comment by Drapersniper** [comment]
https://red-discordbot.readthedocs.io/en/stable/framework_utils.html#redbot.core.utils.embed.randomize_color

Update this to say 
> Gives the provided embed a random color. There is an alias for this called randomize_colour

imo is enough either is an allias for the other
