### ISSUE TITLE
[Audio] API tutorials should be made to work in DMs

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#3471]
# Command bugs

#### Command name

`[p]audioset` api commands, there may be others in core but I forget what all else use api keys if any

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Dump the tutorial on setting API keys

#### What actually happened?

> That command is not available in DMs.

Since API keys should be set in DMs, this is a bit problematic since users either have to constantly switch between DMs and a guild channel or they end up just using the commands in a guild, which can be a security concern.

#### How can we reproduce this issue?

Use any of the audioset api commands in DMs

**Comment by Drapersniper** [comment]
Blocked by #3459

**Comment by Drapersniper** [comment]
Fixed by #3459

**Comment by Drapersniper** [comment]
This has been fixed in the feature branch
