### ISSUE TITLE
[Mod] Hackban stopped working.

### ISSUE THREAD

**Issue by GamerGirl1995** [Cog-Creators/Red-DiscordBot#3476]
#### Command name

Hackban

#### What cog is this command from?

Mod

#### What were you expecting to happen?

For it to work and ban someone that isn't on the server any longer.

#### What actually happened?

Nothing. it didn't work, and Red decided to throw an error in the Console instead.
This error: http://prntscr.com/quxb5i (screenshot link)

#### How can we reproduce this issue?

1. Find someone that isn't on the server to hackban.
2. Type [p]hackban UserID reason
3. Red will return an error.

**Comment by Jackenmen** [comment]
Will be fixed by #3475

**Comment by Jackenmen** [comment]
@GamerGirl1995 also, as temporal workaround you can explicitly pass amount of days to the hackban command like this:
```
[p]hackban UserID 0 reason
```
Where 0 is number of days worth of messages to remove (can be between 0 and 7)

**Comment by GamerGirl1995** [comment]
> @GamerGirl1995 also, as temporal workaround you can explicitly pass amount of days to the hackban command like this:
> 
> ```
> [p]hackban UserID 0 reason
> ```
> 
> Where 0 is number of days worth of messages to remove (can be between 0 and 7)

Thank you for that. i appreciate that.
