### ISSUE TITLE
-play fails to play a video

### ISSUE THREAD

**Issue by 19lmyers** [Cog-Creators/Red-DiscordBot#348]
Multiple times I get an error like this.  I try to -play a video and the console results in:

```
ERROR: giving up after 0 retries
data/audio/cache\0TmoYBcLul8: No such file or directory
```

Other videos work fine, and it doesn't seem to have any relation to the video's length...

**Comment by palmtree5** [comment]
Odd, I'm able to play that video just fine via the play command.

**Comment by 19lmyers** [comment]
This error has a habit of disappearing after restarting the bot or updating the python module youtube_dl, but it always comes back.

**Comment by Eslyium** [comment]
Whens the last time you updated the bot? This was an issue that should have been FIXED I remember correctly.

**Comment by 19lmyers** [comment]
Redownloaded it the day I made this issue.

**Comment by tekulvw** [comment]
Which video?

**Comment by palmtree5** [comment]
@tekulvw I assume [this](https://www.youtube.com/watch?v=0TmoYBcLul8) based on the second line of the error message in the OP

**Comment by tekulvw** [comment]
God I'm blind, thanks dude. @19lmyers I can't replicate the issue so the best I can give you is to make sure that the youtube_dl_options in your audio.py file looks exactly like this:

``` py
youtube_dl_options = {
    'source_address': "0.0.0.0",
    'format': 'bestaudio/best',
    'extractaudio': True,
    'audioformat': "mp3",
    'outtmpl': '%(id)s',
    'noplaylist': True,
    'nocheckcertificate': True,
    'ignoreerrors': True,
    'quiet': True,
    'no_warnings': True,
    'outtmpl': "data/audio/cache/%(id)s",
    'default_search': 'auto'
}
```

**Comment by 19lmyers** [comment]
It didn't have the source_address line. I added it and will report back if
it happens again.
