### ISSUE TITLE
[Audio] Disconnect while others are listening

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#3485]
# Command bugs

#### Command name

[p]disconnect

#### What cog is this command from?

Audio

#### What were you expecting to happen?

For the bot to disconnect.

#### What actually happened?

The bot said "There are other people listening to music." as if DJ mode or voteskip was activated.

#### How can we reproduce this issue?

Join a channel
Have a friend join the channel (not a privledged user on the bot)
Play a song.
Have the friend try to use [p]disconnect

**Comment by Drapersniper** [comment]
This should have the same behaviour as stop, if DC or stop are run while DJ mode is not enforcde the non priviledge user should be able to stop the player

**Comment by Drapersniper** [comment]
Handled by #3502

**Comment by Drapersniper** [comment]
This has been merged into the feature branch
