### ISSUE TITLE
Incorrect response to [p]set prefix (without arguments)

### ISSUE THREAD

**Issue by SapphicCode** [Cog-Creators/Red-DiscordBot#349]
When you run [p]set prefix without any arguments, the bot responds with
`Example: setprefix [ ! ^` (note the missing space)

I _would've_ made a PR, but GitHub doesn't let you have multiple forks for some reason.

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/4b453ef22fd792e42b3d4530ccfc0726a73f79f6
