### ISSUE TITLE
[RFC] Discussion for Audio fixes to go into 3.3.3

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3494]
https://github.com/Cog-Creators/Red-DiscordBot/issues/3485
https://github.com/Cog-Creators/Red-DiscordBot/issues/3471
https://github.com/Cog-Creators/Red-DiscordBot/issues/3467
https://github.com/Cog-Creators/Red-DiscordBot/issues/3492
https://github.com/Cog-Creators/Red-DiscordBot/issues/3389
https://github.com/Cog-Creators/Red-DiscordBot/issues/3353

The issues above are known issues with Audio 1.1.1 (Red 3.3.0)

There is also an issue with Playlist when you dont provide a scope when creating playlists which doesn't have an open issue for it.

Since Audio is currently in a frozen state I'm not keen on working on these HOWEVER users are important sooo they get to suggest which of these should go in Red 3.3.1

The following i will not consider for 3.3.1 unless you can give me a very strong valid point as to why they should and can't wait for the refactor:
https://github.com/Cog-Creators/Red-DiscordBot/issues/3467
https://github.com/Cog-Creators/Red-DiscordBot/issues/3492

If I missed anything this is your chance to propose it/raise it.

**Comment by mikeshardmind** [comment]
Pushing this to 3.3.2 based on a brief discussion of what is and can be ready in discord.

**Comment by mikeshardmind** [comment]
Note: 3.3.2 should be considered for these, but we're looking to do a 3.3.1 very soon with currently available improvements and fixes.

**Comment by mikeshardmind** [comment]
Pushing to 3.3.3 as there still hasn't been a discussion on these.
