### ISSUE TITLE
Songs sometimes play faster then they should

### ISSUE THREAD

**Issue by Removed-5an** [Cog-Creators/Red-DiscordBot#350]
I have been experimenting with the bot and it's been functioning great for me. However for songs I notice they tend to play faster than they should for a brief moment and then go back to the regular playback speed.

Any idea what the issue might be?

**Comment by Eslyium** [comment]
Pretty sure this is normal, If you haven't updated the bot in a while try updating it.

**Comment by Removed-5an** [comment]
Running the latest version, haven't had this issue with other music bots using youtube-dl. This tends to happen towards the beginning and end of a track. Might be some kind of caching issue?

**Comment by Eslyium** [comment]
if your hosting it off your home computer it could be due to the network

**Comment by Removed-5an** [comment]
Hosting it on a low latency high badwith network, so that's not it.
There's an option to switch player however:

player    Toggles between Ffmpeg and Avconv

I think it runs on ffmpeg by default, can't really run with avconv as it's missing an executable in my PATH, but would switching players help or is it not worth the change?

Also would modifying the cachemax help?
There's no recommended size, what's the default? should I increase it?

**Comment by Eslyium** [comment]
It depends on how long of videos your wanting people to play.

**Comment by Removed-5an** [comment]
Anything between 5 minutes and 4 hours. What's the default cachemax?

**Comment by tekulvw** [comment]
It's not a caching error per-se. The audio file itself (mp3) is fully downloaded prior to the bot playing it. However, the bot still re-encodes data on the fly each time the song is played and your lag is either coming from that or it's possibly on the Discord network side
