### ISSUE TITLE
`[p]local search` isn't matching tracks

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3501]
As the title says ... draper fucking fix this shit

**Comment by Drapersniper** [comment]
GFDI ... local tracks are a useless piece of functionality can we kill the inbread shity faced broken asweuifh

https://discordapp.com/channels/133049272517001216/133251234164375552/674193199962521600
Folders with some special characters can't be inspected??????

**Comment by Drapersniper** [comment]
This should already be fixed in the Feature branch, leaving this note here for whoever is going to continue working on it

**Comment by Jackenmen** [comment]
![image](https://user-images.githubusercontent.com/6032823/82903245-fa1b6e80-9f60-11ea-8f44-98b6c80c8df2.png)

**Comment by Drapersniper** [comment]
if its broken, blame it on Jacks i18n
