### ISSUE TITLE
[Audio] inadequate playlist update with local cache enabled

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#3506]
# Other bugs

#### What were you trying to do?

Update local playlist from remote (youtube)

#### What were you expecting to happen?

Update playlist with adding new songs, removal of nonexistent in remote playlist

#### What actually happened?

Random songs was removed, when they are still available on remote playlist.

#### How can we reproduce this issue?

1. use Audio with disabled local cache
2. `playlist save` remote playlist ([i.e.](https://www.youtube.com/playlist?list=PLP08gCf9c_7OITwu6VfPSMkwUsg0RGMDq))
3. enable local cache
4. `playlist update` saved playlist
5. random songs get removed

**Comment by Drapersniper** [comment]
Can't get this to reproduce 
![image](https://user-images.githubusercontent.com/27962761/74087133-65f4cc80-4a81-11ea-97ba-d10b653d17bb.png)

I've added some logic to skip the cache when using `playlist update` which should ensure the update is done properly going forward but, if you have any more details on this one im all ears

**Comment by Drapersniper** [comment]
This is not an a bug per say...

Lavalink is returning different tracks every time, this also happens with the cache disabled.
