### ISSUE TITLE
[Fuzzy] Fuzzy searching doesn't replace special [help strings]

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#3507]
# Other bugs

#### What were you trying to do?

use a slightly wrong command, e.g. `[p]Invite`

#### What were you expecting to happen?

Suggest help-like formatted commands, e.g.
![Screenshot](https://cdn.discordapp.com/attachments/492050319241379871/674346100668235776/unknown.png)

#### What actually happened?

[botname] isn't replaced.
![Screenshot](https://cdn.discordapp.com/attachments/492050319241379871/674346467904847883/unknown.png)

#### How can we reproduce this issue?

Use a slightly wrong command for a command whose docstring includes `[botname]`

**Comment by Flame442** [comment]
Note that all help replacements are not being replaced in fuzzy search, `[p]` is included.
