### ISSUE TITLE
[p]unban fails when using a mention

### ISSUE THREAD

**Issue by newgreenshoot** [Cog-Creators/Red-DiscordBot#3523]
# Command bugs

#### Command name

[p]unban

#### What cog is this command from?

Mod

#### What were you expecting to happen?

After banning a user, I expected to be able to unban them with a mention, e.g. `.unban @user#1234`

#### What actually happened?

It produces `Converting to "int" failed for parameter "user_id".`

#### How can we reproduce this issue?

Ban a user, then try to use the "unban" command to unban them while using a mention (instead of their user ID, which works fine).

The mentions already do contain the user ID, in the form of something like `<@123456789>`, so I assume the bug is related to the special characters at either end not being properly stripped out before it's converted to an integer.

**Comment by Drapersniper** [comment]
This is intentional, the user is banned you won’t be able to mention him after he is no longer in the cache, if you look at the unban command you should see that you are supposed to use a user id and it doesn’t accept other arguments
