### ISSUE TITLE
Loop argument DeprecationWarning spamming in logs

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#3526]
This is spamming multiple times a second in my log: 
![image](https://user-images.githubusercontent.com/18037011/74084141-8432dc00-4a31-11ea-89d3-a5e792ebb497.png)

Debug info: 
![image](https://user-images.githubusercontent.com/18037011/74084143-8c8b1700-4a31-11ea-8267-18842aae5a39.png)
![image](https://user-images.githubusercontent.com/18037011/74084144-8eed7100-4a31-11ea-95aa-99ede7379a04.png)

**Comment by Drapersniper** [comment]
![image](https://user-images.githubusercontent.com/27962761/74084160-266bb780-4a64-11ea-9129-aa4fb1d35b75.png)

**Comment by mikeshardmind** [comment]
Nothing in Red should be causing this. There were a few scarcely used places of it before, but in 3.3.1 all of those have already been rectified (see #3509)

The full uncropped deprecation warning should display a file and line number on which this is occuring.

**Comment by RheingoldRiver** [comment]
Ok updating websockets worked, it was version 6 not 8.1. Is there a requirements file that could be updated to require the more recent version? I did the install on a new digital ocean droplet so I wouldn't be surprised if this came up for other people also. Either way, thanks for the answer!
