### ISSUE TITLE
[Core]Per guild prefix

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#3540]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

It would be awesome for bots that get used on multiple guilds to be able to set a "local prefix" that only triggers commands in the guild where it has been set. Maybe there could also be an option to disable global prefixes so that each guild can choose their own set of prefixes.

Example:
Guild A:
``[p]set prefix local !``
``!ping``
-->Pong.

Guild B:
``!ping``
--> No reply

**Comment by PredaaA** [comment]
It already exists under `[p]set serverprefix` command.

**Comment by Jackenmen** [comment]
As Preda said, it's already available under `[p]set serverprefix`.
