### ISSUE TITLE
[Audio] Config schema 2 migration incorrectly recorded as upgraded to _SCHEMA_VERSION = 3

### ISSUE THREAD

**Issue by synrg** [Cog-Creators/Red-DiscordBot#3552]
When the config schema 2 upgrade happens, at the end, it is recorded as upgraded to _SCHEMA_VERSION (currently 3). This is premature, as the schema 3 upgrade has not happened yet. It should be recorded as upgraded only to schema 2 here.

https://github.com/Cog-Creators/Red-DiscordBot/blob/86549248699d1bcd5294b57805d49b1fb3d1a660/redbot/cogs/audio/audio.py#L268

**Comment by Drapersniper** [comment]
Im nearly certain this has been fixed on the feactor, but please whoever is reviewing it do double check
