### ISSUE TITLE
[Core] [p]set game command should return the new status text and not just a "Set" message.

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#3556]
# Enhancement

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

The ``[p]set game``, ``[p]set watching`` and ``[p]set listening`` commands currently just return a generic "Set" message. I think adding what text is now displayed as status in the confirmation message, would look better and feel more polished than just having a "set" message.

I can PR this if it's something that you guys would want to implement but maybe you have a reason for not doing it?

**Comment by Flame442** [comment]
It seems like the maximum game length is 128 characters, so enforcing that as an upper limit would solve the issue of overly long games breaking the response message AND fix unintended behavior where it accepts the game but the game isn't actually set.
