### ISSUE TITLE
[Core] cog disable and enable

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3569]
# Feature request

#### Select the type of feature you are requesting:

- [X] Cog
- [X] Command
- [X] API functionality

#### Describe your requested feature

Allow users to disable and enable cogs per server and also globally if they wish (I know unload but it's not the same) cause this keeps the cog loaded.

**Comment by mikeshardmind** [comment]
This seems like more trouble than it's worth.

1. This won't disable events.
2. We won't make this disable events.
3. ``unload`` exists.
4. permissions rules can be set for a server disabling it
5. permissions hooks and cog checks can both be used (depending on if your code or not) to disable in some guilds, without requiring dangerous uses of permissions allow rules.

**Comment by Stonedestroyer** [comment]
In that case is there a better alternative to how I would deny a cog globally and allow it in one server without resorting to bot checks or permission hooks.

Main issue is if I use permission rules I can allow each command but then if I allow the mod commands that have permission checks and also includes admin that would give every user in that server the right to use it.

**Comment by mikeshardmind** [comment]
#3181 (whenever someone works on it) will be the way to do that in core.

**Comment by Jackenmen** [comment]
This won't be implemented as `[p]cog disable/enable` and #3658 (originally #3181) is the alternative that is gonna allow to do this when (and if) someone takes it.

I'm gonna close this as #3658 is gonna be the way for solving the given problem in Core.

Let me know if there's anything else that was missed in the discussion here.
