### ISSUE TITLE
[p]cleanup messages stopped working.

### ISSUE THREAD

**Issue by Fabian-Evolved** [Cog-Creators/Red-DiscordBot#3574]
# Command bugs

#### Command name

cleanup messages

#### What cog is this command from?

cleanup cog

#### What were you expecting to happen?

for that command to remove the messages

#### What actually happened?

it didn't but instead said this on the console:
http://prntscr.com/r49v3r (screenshot link)

- http://prntscr.com/r49wgh (this screenshot shows log from [p]traceback command)

#### How can we reproduce this issue?

1. say a couple lines.
2. type [p]cleanup messages 5   (if you made 5 test lines otherwise use number of test lines you did)
3. see bot not removing messages.

**Comment by PredaaA** [comment]
Discord is currently having issues a lot of bots are getting that exact same error.

**Comment by Kowlin** [comment]
Gonna close this since this seemed to be a global Discord error.
