### ISSUE TITLE
Option to disable [p]contact

### ISSUE THREAD

**Issue by YeahImRose** [Cog-Creators/Red-DiscordBot#359]
Over time, I've seen a very large amount of people complain about not being able to disable the `contact` command. The only problem I could foresee is that some people may not know how to disable it if they aren't told how.

If anyone has any suggestions on how disabling it should work, please comment with your idea.

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/bf063f55fc70ef4ec02879dbac19c48691cc7365
