### ISSUE TITLE
[Core] Licenseinfo always enforceable

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3611]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [X] API functionality

#### Describe your requested feature

[p]licenseinfo can not be used if a user if blacklist or whitelist is in effect from mod cog.
A user should be able to always access licenseinfo even if they are blacklisted due to the license terms. 

It seems [p]ignore server/channel licenseinfo still responds so that command works.

It should also be ensured third-party cogs can not bypass licenseinfo if this is now possible. I have some cogs in mind that may be able to achieve this. 
-->

By request of @Drapersniper to create this issue.

**Comment by mikeshardmind** [comment]
I'm somewhat astounded here. I don't think that the bot should respond in channels it has been told to ignore. This doesn't seem like a matter of ensuring the license is available, everywhere the bot can interact, it still is. It's a command which controls where the bot interacts.

**Comment by Stonedestroyer** [comment]
> I'm somewhat astounded here. I don't think that the bot should respond in channels it has been told to ignore. This doesn't seem like a matter of ensuring the license is available, everywhere the bot can interact, it still is. It's a command which controls where the bot interacts.

The bot currently responds to licenseinfo while [p]ignore has been used but does not to [p]blacklist so that behavior is already in the bot.

**Comment by mikeshardmind** [comment]
The fact that the idea is to make the bot respond to people ot shouldn't, rather than fix that shows where the priorities are now.

Blacklist is a type of command for removing abusers, ignore is a command for restricting locations. Neither of these have any reason to be considered as interrupting the ability to obtain the license as it is still available to people who can interact with the bot, where they can interact with it.

**Comment by Drapersniper** [comment]
This is here for public visibility, there are current internal discussions and further consulting of a laywer in to clarify the ramifications of either action.

So the final decision here hasn't been chosen.

**Comment by Twentysix26** [comment]
@mikeshardmind First and final warning: I'm not tolerating further jabs or offhanded remarks about the current state of things (or better, about how you perceive them to be), no matter how valuable the input you're providing is. To make it clear, I'm fully in agreement with your opinion on the proposed functionality. For the moment I'm closing the issue as the majority seem to disagree about the need for this.
