### ISSUE TITLE
Permissions cog doesn't allow users command permissions

### ISSUE THREAD

**Issue by Boii1** [Cog-Creators/Red-DiscordBot#3647]
# Command bugs

Permissions updates the YAML file when manually uploading a YAML via Discord message but doesn't seem to update when using some of the commands to set it. Even if you manually specify the server ID, channel ID or user ID said persons cannot use the command.

#### Command name

[p]permissions *

#### What cog is this command from?

Permissions

#### What were you expecting to happen?

It would allow people I had chosen to do [p]reload for when the bot hangs and refuses to play audio.

#### What actually happened?

Upon any type of command I had instanced it would not allow the user to use the said command afterword at all. I was the only one capable of using the command.

#### How can we reproduce this issue?

Just attempt any of the commands either global or server and try to give someone permission to a command such as reload / "reload audio" or similar.

**Comment by Jackenmen** [comment]
Reload command is owner-only and permissions for those commands can't be overridden.

**Comment by Jackenmen** [comment]
Closing this as we don't currently plan to allow owners to give permissions to owner-only commands through Permissions cog.
