### ISSUE TITLE
[Feature] Streams | Additional Option

### ISSUE THREAD

**Issue by Menteroth** [Cog-Creators/Red-DiscordBot#3654]
# Feature request

#### Select the type of feature you are requesting:
- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature
Command: `streamset`
Option: `game`
Syntax: `streamset game <game>`
Function: To set specific game(s) to only alert when a streamer is playing a game from that list.

Useful for servers that are for a specific game.
This might be a bit off topic, but still connected, but maybe be able to seperate specific game(s) alerts from general alerts. So as above I mentioned a Discord for a specific game where you can have alerts for `<game>` in one channel and then be able to have another channel for regular alerts where anything is played. I hope this wasn't too confusing.

**Comment by Jackenmen** [comment]
Is #2356 what you want?

**Comment by Menteroth** [comment]
Seems like something similar yeah.

**Comment by Jackenmen** [comment]
Closing in favor of #2356
