### ISSUE TITLE
Error in command 'slot' - KeyError: 'SLOT_TIME'

### ISSUE THREAD

**Issue by TakVap** [Cog-Creators/Red-DiscordBot#369]
After latest pull update, !slot command works once per user then displays the above message.

[06/09/2016 22:07] ERROR red on_command_error 88: Exception in command 'slot'Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(_args, *_kwargs)
  File "C:\Users\user\Documents\Red-DiscordBot\cogs\economy.py", line 384, in slot
    if abs(self.slot_register[author.id] - int(time.perf_counter()))  >= self.settings[server.id]["SLOT_TIME"]:
KeyError: 'SLOT_TIME'

**Comment by Kowlin** [comment]
I've tried this out on my machines, and I cannot replicate this bug.

**Comment by TakVap** [comment]
Odd, as soon as I use the latest economy.py (6 days ago) I can replicate the error. If I use an economy.py from a few months back it works perfectly fine.

![takbotslot](https://cloud.githubusercontent.com/assets/4213609/18363616/bd3ffaa2-7602-11e6-9d6a-3b272aef9dac.png)

**Comment by Kowlin** [comment]
Hmm okay, I've just tried the slot time, could you try setting the slot time with the following command? `economyset slottime <time in seconds>`, worst case scenario you need to dig into the json in `data/economy/settings.json`

**Comment by TakVap** [comment]
That did the trick, thanks - I'd never used the slottime settings before (nor had I ever had a reason to) so migrating an old configuration to a new / fresh bot installation caused this issue.

"SLOT_TIME" : 5" was indeed missing from the economy/settings.json and that makes sense.

Most appreciated!
