### ISSUE TITLE
Add a core command to check if red is outdated 

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3693]
This is a bit niche since the bot dms the owners on a restart, however for long running bots it would be a good way to check without restarting

**Comment by Kowlin** [comment]
An on demand command would not be suitable here in my opinion, I'd rather be polling pypi for the latest version once per 12 hours or an day or so, as the command could be very easily forgotten.

**Comment by Jackenmen** [comment]
We already have command for checking if Red is outdated - `[p]info` offers that information:
![image](https://user-images.githubusercontent.com/6032823/77630081-cb761d00-6f4a-11ea-9b97-daa1923fb136.png)
