### ISSUE TITLE
local command of audio cog does not work

### ISSUE THREAD

**Issue by Lemmmma** [Cog-Creators/Red-DiscordBot#3713]
# Command bugs

#### Command name

local

#### What cog is this command from?

Audio

#### What were you expecting to happen?

I would be able to play music from my computer as mp3 files

#### What actually happened?

The bot gave following output:
```
Invalid Environment
No localtracks folder.
```
Also, in the data folder, there is indeed no localtracks folder.

In the red.log file there is an error:
`[ERROR] red.audio: 'No such player for that guild.'`
[red.log](https://github.com/Cog-Creators/Red-DiscordBot/files/4405891/red.log)

[spring.log](https://github.com/Cog-Creators/Red-DiscordBot/files/4405893/spring.log)

#### How can we reproduce this issue?

install and start according to this site: https://red-discordbot.readthedocs.io/en/stable/install_windows.html
add audio cog: `[p]load audio`
`[p]local folder` or `[p]local play` or `[p]local search`

(Also, a more detailed documentation of the basic cogs would be nice. If that already exists, I couldn't find it.)

**Comment by Drapersniper** [comment]
Please join the support server, as from your issue the cog seems to be working as intended however it seems like your setup may be incorrect 

https://discord.gg/red

**Comment by Lemmmma** [comment]
> Please join the support server, as from your issue the cog seems to be working as intended however it seems like your setup may be incorrect
> 
> https://discord.gg/red

Thanks for the quick answer. I will take a look at that.

**Comment by Lemmmma** [comment]
You were right. I wasn't aware you had to set the localtracks folder. Thanks again!
