### ISSUE TITLE
No tracks playing because of inappropriate content

### ISSUE THREAD

**Issue by chka17** [Cog-Creators/Red-DiscordBot#3729]
Bot gives me a response "Track Error. This video may be inappropriate for some users." really often. Is there any way of allowing Red to run all the tracks, including ones that "may be inappropriate for some users"?

**Comment by Drapersniper** [comment]
Please head over to the support server (https://discord.gg/red) for further support, this is not an issue with the cog of Red and it's dependencies

**Comment by aikaterna** [comment]
For people reading this issue in the future, age restricted tracks are not currently able to be played on our audio backend. We will need to wait for the maintainers/contributors of Lavaplayer to resolve this before they can be played.
