### ISSUE TITLE
V3 - cant reopen Redbot?

### ISSUE THREAD

**Issue by BizarreDuck** [Cog-Creators/Red-DiscordBot#3748]
This might be a dumb question and its not even an issue- I didn't know where else to put this, I'm so sorry- but I closed Redbot V3 and I don't know how to reopen it.
In the folder that the bot created, there's no where to launch it again like there was for Redbot V2... how do I open it's command prompt again?
http://prntscr.com/rxybbi 

Thanks :,)

**Comment by hatred2k** [comment]
You don’t open anything. You run ``**redbot <instance name>**`` in the console.

**Comment by Flame442** [comment]
If you need more help using red, feel free to drop in our support server at https://discord.gg/red.
