### ISSUE TITLE
[Admin] Manage role by reactions

### ISSUE THREAD

**Issue by simonbarre** [Cog-Creators/Red-DiscordBot#3755]
# Feature request

I hope this request is not already ask, and it's the good place to post.

I search how to configure the bot to set role at users when they clik on an reaction.

#### Select the type of feature you are requesting:

- [x] Cog
- [x] Command
- [ ] API functionality

**Comment by yamikaitou** [comment]
This already exists as a 3rd Party Cog. A key feature of Red is that it can be expanded with additional cogs. Not every feature people use suits the core bot. I'd suggest giving our [Getting Started](https://red-discordbot.readthedocs.io/en/stable/getting_started.html) page a read.

For this specific feature, Sinbad has it but as he is no longer supporting his cogs, [Trusty has a fork](https://github.com/TrustyJAID/SinbadCogs) of it that he is planning on maintaining
