### ISSUE TITLE
Add a way to remove the avatar

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3756]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

There should a be a way to remove the avatar (`await bot.user.edit(avatar=None)`) through the bot. I think adding a subcommand like `[p]set avatar clear` (alias `remove`?) would be okay.

**Comment by Kowlin** [comment]
Ye I'd feel that the best way to approach that would be a sub command
