### ISSUE TITLE
[Converting] JSON

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3779]
When converting back to JSON from any backend it seems that current data is not exported back if I had originally went from JSON and have existing data as files. I have tested this with Redis and have not tried PostgreSQL but have no reason to doubt it would be different.

**Comment by Drapersniper** [comment]
Welp nope this one is totally my fault on redis 😓

**Comment by Stonedestroyer** [comment]
I didn't just create issue for a PR disregard.
![image](https://user-images.githubusercontent.com/1307729/79972073-a7e4ba80-8495-11ea-9334-0b3eb0daee4e.png)
