### ISSUE TITLE
[p]cleanup user, text are not deleting the correct number of messages

### ISSUE THREAD

**Issue by Twentysix26** [Cog-Creators/Red-DiscordBot#378]
This happens when there are message in between what it has to be deleted

In general, the messy code of the cleanup functions could use some love. It would probably be better to refactor them

**Comment by YeahImRose** [comment]
After doing some test, I think that using `purge_from` just makes things more difficult for fixing this issue. If anything, using `discord.utils.find`/`discord.utils.get` and `delete_message`/`delete_messages` may work. I'll do some more testing and post progress here.

**Comment by Twentysix26** [comment]
Fixed in https://github.com/Twentysix26/Red-DiscordBot/commit/327420904819996c83c7e215e6b8ddbaba9593ae
