### ISSUE TITLE
Banmention options

### ISSUE THREAD

**Issue by SharkyTheKing** [Cog-Creators/Red-DiscordBot#3786]
# Feature request
#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

`modset banmentionspam` Instead of having this purely set to ban only, it would be nice to have options to have the bot warn / kick / softban / ban. Having different options rather than having just a pure straight ban for mentions.

Yes, this can be achieved by making a cog or using a third party, though if mentions is already a core function, why not add options and customization to it.

**Comment by SharkyTheKing** [comment]
Since no one's commented regarding this, once I find enough time I'll be taking up on this issue and doing a PR. If anyone has recommendation on how I should do it, please feel free to let me know so I can get a plan going ahead! Thanks.

**Comment by Jackenmen** [comment]
I don't have a particular idea on how it should be done, but I think that adding such feature makes sense 👍

**Comment by SharkyTheKing** [comment]
Was merged with https://github.com/Cog-Creators/Red-DiscordBot/commit/73a34eacd6bf1b7089e7ed33c311845d0f1f2f97. Yay!
