### ISSUE TITLE
Status messages no longer persist

### ISSUE THREAD

**Issue by SapphicCode** [Cog-Creators/Red-DiscordBot#380]
When setting a status message with `[p]set status`, these messages no longer persist after a reboot.

**Comment by franc-ist** [comment]
Adding to this, statuses will also clear themselves randomly, even without a reboot. Could be a problem with rndstatus, but this was unloaded at the time.

**Comment by Kowlin** [comment]
We never save the status, what you're seeing is the old status before a reboot. So long the bot doesn't properly log out the status remains as it was until its forced to log out.
