### ISSUE TITLE
Per-server localising

### ISSUE THREAD

**Issue by DannyB5544** [Cog-Creators/Red-DiscordBot#3801]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature
So, in a bit of ye olde necroposting, I thought I'd bring back up the issue of Per-server languages. Currently we have bot-wide language setting and regional format setting, but a per-server option might be useful for larger bots that may not strictly be in English only servers.

Found it referenced in PR https://github.com/Cog-Creators/Red-DiscordBot/pull/2246, and also in issue https://github.com/Cog-Creators/Red-DiscordBot/issues/1970

**Comment by Jackenmen** [comment]
There's no need to make another issue if one is already there (which you even referenced in the issue description).
