### ISSUE TITLE
[Audio] - Lavalink fails after a period of time

### ISSUE THREAD

**Issue by jenke15** [Cog-Creators/Red-DiscordBot#3812]
# Other bugs

#### What were you trying to do?

I am using autoplay with autopause enabled and let the bot/music just run without any further commands.

#### What were you expecting to happen?

I expect music to be played continuously. 

#### What actually happened?

It plays music for 1-3 hours then randomly fails. 
In Red's log I find: 
`[2020-04-29 20:51:14] [ERROR] red.audio: Exception raised in Audio's emptypause_timer.
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 8086, in disconnect_timer
    await lavalink.get_player(sid).pause()
  File "/root/redenv/lib/python3.8/site-packages/lavalink/lavalink.py", line 110, in get_player
    node_ = node.get_node(guild_id)
  File "/root/redenv/lib/python3.8/site-packages/lavalink/node.py", line 389, in get_node
    raise IndexError("No nodes found.")
IndexError: No nodes found.`
In the audio log (spring.log) the entries stop, meaning the last written entry to the file is:
`2020-04-29 20:50:19.281  INFO 4351 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "pause", "guildId": "[removedGuildID]", "pause": true}`

A restart is required to resolve. It is important to note that the java process is still running. I am running Lavalink through Red (not separate). If I run [p]autoplay I will receive:
`Connection to Lavalink has not yet been established.`

#### How can we reproduce this issue?

1. Start bot
2. Enable autoplay, autopause
3. Add list of songs to default playlist
4. Summon bot to channel, then issue [p]autoplay
5. Wait 1-3 hours
6. After 1-3 hours, music will stop, but bot will remain in the channel

**Comment by Drapersniper** [comment]
Hey Issues with lavalink aren't something that short be in the repo. If you need help join the support server and further debugging can be done to help you with your issue.

https://discord.gg/red/. 

This is most likely a websockets issue but until some testing can be done won't know for sure.

**Comment by jenke15** [comment]
@Drapersniper Sorry about that... I've posted it a few times in the discord and never really got any replies on this specific subject. If you're around tomorrow, I'd be happy to share whatever you needed. I believe it's a websocket issue too - is there a default timeout maybe?

**Comment by Drapersniper** [comment]
What's your name on discord?

**Comment by jenke15** [comment]
Thank you Draper for speaking with me. I know you said this is out of Red’s hands. Just in case anyone else experiences this, just turn off auto pause, that fixes it. Music will be playing all the time, yes, but, it resolves the issue until this can be fixed!

**Comment by Drapersniper** [comment]
Erm this isn't caused by auto pause.

**Comment by jenke15** [comment]
Okay then, ongoing issue.

**Comment by pordini** [comment]
I've seen this same issue, it happened when other people were giving commands, while I was away. I couldn't find any useful logs so far, but ever since I disabled the stop and disconnect commands haven't seen it occur. That's not to say this is a solution or workaround, I just haven't seen it since.

If there is info I could provide, let me know.

**Comment by Drapersniper** [comment]
For issues with the bot please ask in https://discord.gg/red.

GH issues are not meant for debugging and support, not to mention that Lavalink is a service the bot uses and not directly coded in this repo.

**Comment by Jackenmen** [comment]
Support questions belong to Red's discord server.

**Comment by smariyah** [comment]
Saya juga pernah mengalami tidak ada suara. 
Apakah ini berasal dari discord ataukah stream twitch?

**Comment by Jackenmen** [comment]
As I said in the comment above, support questions belong to Red's discord server, here's invite link:
https://discord.gg/red

Also, please use English to communicate both on our GitHub and Red's discord server.

**Comment by smariyah** [comment]
@jack1142 ok
Sorry, my lang english not good

**Comment by m0rth4r0** [comment]
I have the same issue with exactly the same settings. Have you managed to find a better way than stop the "autopause"?

**Comment by Flame442** [comment]
As has been said *multiple times* in this issue, please direct support questions to [the Red support server](https://discord.gg/red). This issue is closed and 2 years old, there is no reason to continue conversation here.
