### ISSUE TITLE
[Admin] Serverlock doesn't function.

### ISSUE THREAD

**Issue by Robert606** [Cog-Creators/Red-DiscordBot#3814]
# Command bugs

#### Command name

!serverlock

#### What cog is this command from?

[Admin] Cog

#### What were you expecting to happen?

For people not being able to invite the bot into their server, when the serverlock feature is enabled.

#### What actually happened?

People where able to invite the bot into their server. even when the serverlock feature states it was serverlocked.

#### How can we reproduce this issue?

1. have the bot in 1 server, and use !serverlock so that it says: "The bot is now serverlocked."
2. Do !invite and the bot will DM you the invite link. follow that link and invite the bot into your server.
3. It will still join said server. Even though it shouldn't.

On my instance which is btw the latest version of Red 3.3.7 - it joins a server from someone that has done that, even though i have the bot serverlocked. i even disabled the Invite command. which prevents most of it, however some people have the invite link saved in their DM's and use that instead the bot. which serverlock normally would prevent, but now doesn't.

Hope this report helps people.

**Comment by Jackenmen** [comment]
@Robert606 should be fixed in next non-hotfix release, however I suggest to just untick the "Public Bot" checkbox in bot application's settings:
![image](https://user-images.githubusercontent.com/6032823/80723496-fe3ea280-8b00-11ea-9d60-2702a5c540c0.png)

**Comment by Robert606** [comment]
Thank you @jack1142 for the quick response. I will do that.
