### ISSUE TITLE
Help isn't translatable - pot files for strings aren't created

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3818]
Only thing from `help.py` that gets added to `.po` files is help docstring for `[p]help`.

**Comment by Jackenmen** [comment]
Reason for this is us using `T_` instead of `_` which prevent `gettext` from picking those strings.

There's also another problem with using Translator inside f-string, e.g. `f"{_('Syntax')}"` won't get picked after changing from `T_`, this is a bigger issue that we would need to fix in redgettext (and probably avoid such usage until then) if we want to have it supported.

**Comment by Dav-Git** [comment]
Can't we just switch ``T_`` for ``_`` and change the f-strings to use ``.format()`` ?

**Comment by Jackenmen** [comment]
We can, the f-string issue will probably not be fixed any time soon (even though I do have code for `pygettext` that could probably just be applied to `redgettext`, but I am not so sure about its quality) and the `T_` could just be added to keywords supported by `redgettext`, although I am not sure why `T_` was used over `_` here.
