### ISSUE TITLE
[Audio] [p]local search does not return any matches

### ISSUE THREAD

**Issue by SieBRUM** [Cog-Creators/Red-DiscordBot#3821]
# Command bugs

The `local search` command does not seem to return any matches

#### Command name

`local search`

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Expect some search results.
Current setup
![image](https://user-images.githubusercontent.com/14212955/80955769-16176e80-8e00-11ea-9ee7-094721da2088.png)

#### What actually happened?
![image](https://user-images.githubusercontent.com/14212955/80955806-262f4e00-8e00-11ea-8831-9493695c5f9a.png)
![image](https://user-images.githubusercontent.com/14212955/80955822-347d6a00-8e00-11ea-9342-24b27df41ecb.png)

#### How can we reproduce this issue?
![image](https://user-images.githubusercontent.com/14212955/80955950-81f9d700-8e00-11ea-8fbb-fc861de74812.png)

Execute the search command

**Comment by Drapersniper** [comment]
Handled by #3459

**Comment by Kowlin** [comment]
Handled by #3459
