### ISSUE TITLE
Help command issue with / at at start of bot nickname

### ISSUE THREAD

**Issue by MzLiv** [Cog-Creators/Red-DiscordBot#3825]
# Other bugs

#### What were you trying to do?

Run the help command.

#### What were you expecting to happen?

DM with list of commands

#### What actually happened?

Error in command 'help'. Check your console or logs for details.
Log attached

#### How can we reproduce this issue?

Nickname bot starting with \
Potentially also use \ as bot prefix

#### Potential issue:
https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/core/commands/context.py#L261
No input validation

[message.txt](https://github.com/Cog-Creators/Red-DiscordBot/files/4588155/message.txt)

**Comment by Drapersniper** [comment]
> Error in command 'help'. Check your console or logs for details.

IT would be nice if in the future you just post the traceback instead of a file thats forced to download.

can you show the output of `[p]cogs` also go to the support server so that we can do some debugging https://discord.gg/red
