### ISSUE TITLE
How to allow other people on the server to queue up songs and summon bot

### ISSUE THREAD

**Issue by hasnainb237** [Cog-Creators/Red-DiscordBot#384]
For some reason I cannot find the command to give permission to others in the server to either queue up songs or summon the bot. How do I do this? It will only respond to me.

**Comment by Twentysix26** [comment]
You might have whitelisted yourself.
`[p]whitelist clear`

**Comment by hasnainb237** [comment]
it turns out the [p] symbol that I used is something different from what my friends have on their keyboard cuz im on desktop and their on mobile. how do i change my [p]?

**Comment by Twentysix26** [comment]
See `[p]help set prefix`

**Comment by hasnainb237** [comment]
aight i got it thanks
