### ISSUE TITLE
audioset maxlength command not working

### ISSUE THREAD

**Issue by AlexGauthier** [Cog-Creators/Red-DiscordBot#385]
Hi,

I'm trying to modify the maximum length of my bot and the command is not producing the expected behavior. 
The console doesn't show any form of bug/error thrown in the process.

I might be doing something wrong, but here is what my command looks like to try to put the maxlength limit up to two hours, ! being my [p] : !audioset maxlength 7200.

Let me know if there is anything wrong with how I'm trying to use the command!

Thanks for your time and amazing bot!

**Comment by palmtree5** [comment]
That should've worked. Are you set as the owner?

**Comment by Removed-5an** [comment]
@AlexGauthier Don't forget to do !reload audio
