### ISSUE TITLE
Make selfrole case insensitive

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#3853]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

In Admin cog, could selfrole be made case insensitive? In the event that a server has two separate roles that are both allowed in selfrole, it could print a warning about the situation every time a role is added or removed via selfrole.

**Comment by Drapersniper** [comment]
I think it is more appropriate to be explicit here when performind moredation actions ( giving a role) to members. but this is just my personal opinion.

**Comment by RheingoldRiver** [comment]
my users are unable to figure out how to assign themselves roles because it's case-sensitive. I realize how ridiculous that sounds, but it's a huge usability problem in my server. I suppose I could just make all role names lowercase, but that makes my server look lazy/sloppily set-up, and it's supposed to be an official support server.

Maybe case sensitivity could be toggled?

**Comment by Jackenmen** [comment]
I think this wouldn't be a bad idea, assuming only `[p]selfrole add/remove` would be affected and you would still have to use proper casing when adding/removing role from available selfroles with `[p]selfroleset`. Once role is added with `[p]selfroleset`, its ID is saved in config so users would have the proper role assigned no matter the casing that they used.

I'm marking this as "Needs discussion" until another org member gives their opinion

**Comment by Dav-Git** [comment]
If I may chip in, what happens if the role "James" and "james" are both set to self-assignable and a user runs ``[p]selfrole add james``

**Comment by RheingoldRiver** [comment]
In that case I would add james and print a warning along with the confirmation - "Added role `james`. Please note that the role[s] `James`[, and JameS] is[are] also available. You may use `^selfrole remove` and `^selfrole add` if needed." or something along those lines

If there are multiple casings available and you try to assign one that doesn't match any of them, it could either error or guess and print a similar warning. I think this is enough of an edge case (and already a terrible practice haha) that it's not a big tradeoff to somewhat sacrifice ease of use in this case.

**Comment by Dav-Git** [comment]
In that case I would say it would be best to check role.name.lower() and don't allow 2 roles with a similar name with just different casing to be made self-assignable at the same time.

**Comment by RheingoldRiver** [comment]
ah yeah, that probably makes more sense

**Comment by Flame442** [comment]
> don't allow 2 roles with a similar name with just different casing to be made self-assignable at the same time.

I'm not sure *quite* how that would work since role names can be changed...
You can technically break this right now if you have two roles with the exact same (case sensitive) name. It will only allow you to assign one of them, saying the role was already assigned if you have one of the two. You *are* able to use the ID, but must users won't know to do that.

**Comment by Drapersniper** [comment]
We could ... do a menu picker for when a prompt matches multiple roles, in the realworld chances are that this won't be the case much, but outside of straight up saying "unable to give you role, currently multiple roles share this name"  can't think of anything else we could do

**Comment by RheingoldRiver** [comment]
well it could give you the role you exact-matched if you did, and if not then say "sorry unable to determine"

If `James` and `james` exist ->

* selfrole James -> you get James
* selfrole james -> you get james
* selfrole JaMeS -> error
