### ISSUE TITLE
[Audio] [p]play YouTube WebM inconsistant error

### ISSUE THREAD

**Issue by SieBRUM** [Cog-Creators/Red-DiscordBot#3885]
# Command bugs
[p]play <link> returns an error, but using the [p]play with a search query does not. Please make this consistant.
In this image, the bot says WebM is not supported
![image](https://user-images.githubusercontent.com/14212955/83300538-7d0a2680-a1f8-11ea-9637-986446022565.png)

In this image, the bot starts playing the video.
![image](https://user-images.githubusercontent.com/14212955/83300955-2b15d080-a1f9-11ea-8ab3-d0087f5e119d.png)

They both use the same link! 
![image](https://user-images.githubusercontent.com/14212955/83300777-e9852580-a1f8-11ea-85f1-9e99bcb86c2b.png)

#### Command name
`[p]play`

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Either block both or accept both. Maybe check if the livestream is not live anymore and if so, just play it like a normal video.

#### What actually happened?

Both have different results

#### How can we reproduce this issue?

`[p]play https://www.youtube.com/watch?v=FLM2U9bAlgU` returns error
`[p]play rooler` does not

### Version
Currently running the newest build
![image](https://user-images.githubusercontent.com/14212955/83301751-741a5480-a1fa-11ea-8a54-a8df9ceda9cc.png)

**Comment by Drapersniper** [comment]
Okay, before I dismiss this I would like to ask you a few questions. Go to the main server and ping me me in there @Draper#6666

https://discord.gg/red

**Comment by SieBRUM** [comment]
Update, had a chat with Drapersniper. Seems to be a deeper issue in the backend. He will hunt for the poor bastard that has to fix the issue.

**Comment by aikaterna** [comment]
Hi, sorry this took a while but this was being determined in our audio backend and not through code that we write/control ourselves. This will be working for you now with Red 3.4.2 (to be released soon(tm)), but playing the direct link will display a long track time (`106751991167:07:12:56`). I'm going to be closing this as the playback portion will be functional with our Red 3.4.2 update and the audio backend that's included with that version, but I am keeping that long track time in mind and will also work with others on getting that resolved at some point as well.

Edit: This should be fully resolved with Red 3.4.3 and the 1132 build of our Lavalink.jar.
