### ISSUE TITLE
!trivia responds in private chat

### ISSUE THREAD

**Issue by Krappa322** [Cog-Creators/Red-DiscordBot#390]
Title says it all. !trivia responds with all possible trivia in private chat instead of in the channel where it is used.

**Comment by palmtree5** [comment]
I believe that is intended.

Output from `!help trivia`:

```
!trivia [list_name]

Start a trivia session with the specified list

trivia stop - Ends the current session
trivia - Shows trivia lists
```

If you want to start a trivia session, I'd recommend doing `!trivia` followed by the name of a list (which is what's being sent via PM.

**Comment by calebj** [comment]
Because there can be a large number of question sets, the list is sent via direct message instead of spamming the regular channel.
