### ISSUE TITLE
Posting general info about the bot on ping

### ISSUE THREAD

**Issue by Motzumoto** [Cog-Creators/Red-DiscordBot#3912]
Command- So for instance someone pings the bot to figure out what it does, it should reply with some general info like;

Prefix,
help command
Some general info about the bot, maybe uptime, how many servers its in, how many commands, maybe the support server (requires a setup obviously), some general information like that.

it would really help out new people figuring out what the bot is, what it does, and how to use it.

**Comment by Drapersniper** [comment]
Theres been some internal discussing about exposing the bot prefix via a single blank mention of the bot.

However a lot of what you mentioned is avaliable in 
`[p]info` and `[p]serverinfo` 

why do you feel this information should be duplicated into `[p]ping` or are you suggesting to depricate the info/server info commands?

**Comment by PredaaA** [comment]
I think they means when mentionning the bot, not in `[p]ping` command.

**Comment by Dav-Git** [comment]
This issue stems from a quick talk on the cog support server. They are essentially looking for what we already discussed in ~~burndown~~ feature ideas.
 Reference discussion: https://discord.com/channels/133049272517001216/133049878837329920/714570353124311090

**Comment by Drapersniper** [comment]
tl:dr i suggested i may aswell stop being lazy and implement it ... stand-by for PR

**Comment by Drapersniper** [comment]
Closing this in favour of the following comment. 
https://github.com/Cog-Creators/Red-DiscordBot/pull/3914#issuecomment-649858300
