### ISSUE TITLE
Make subcommands interactive

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#3928]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

When we type a command who includes subcommands, the bot sends the help menu of the subcommands, with another message saying `What section do you want to go into?` (A setting (`[p]helpset interactivesubcommand`) must be turned on, default to off)
If the user returns a correct subcommand, if the subcommand gives other subcommands, then the bot asks again, else the bot forgets everything.

If the subcommand is a command and don't require to parse any parameters (Like a channel), the bot will run the command, else, the bot will send the help menu of the command.
I mostly think it's useful for cog like Leveler from Fixator who have a lot of subcommands and can be very annoying to copy/paste every time

Some discussion has been already made on the feature-ideas channel: https://discordapp.com/channels/133049272517001216/133049878837329920/718858765193183242

It needs deeper discussion, suggestions, ideas, critics, and more since it can be a lot of problems, but useful for users.

**Comment by NeuroAssassin** [comment]
To reiterate what was said on discord, so that its here as well, one thing that I believe would need to be discussed is how it would interact with commands that perform an action without subcommands.

**Comment by madebylydia** [comment]
Closing as this is probably never gonna be added and as Neuro said, a hard thing to implement.
