### ISSUE TITLE
Empty Voice Channel?

### ISSUE THREAD

**Issue by lbarnett83** [Cog-Creators/Red-DiscordBot#393]
I'd implement this myself, but I don't really know python all that well.  I feel like it'd be good if the bot periodically checked the voice channel it's playing in, and if no users are present for a present amount of time, stop playing and leave the channel.  Just a thought :)

**Comment by palmtree5** [comment]
It already does this after 300 seconds

**Comment by lbarnett83** [comment]
Even it is playing music to an empty channel. Because my bot continued for well over an hour without disconnecting

**Comment by palmtree5** [comment]
Oh, I see what you're getting at. Yeah, I think the auto-disconnect only fires if the bot isn't playing audio

**Comment by Kowlin** [comment]
That is correct @palmtree5. Auto-disconnect only triggers when the bot is inactive.

**Comment by palmtree5** [comment]
FYI, mirrored this as a suggestion in the suggestions channel in Discord

**Comment by tekulvw** [comment]
Fixed with #456
