### ISSUE TITLE
[Audio] Spotify enqueue playlist not working

### ISSUE THREAD

**Issue by Xanawatt** [Cog-Creators/Red-DiscordBot#3930]
# Command bugs

#### Command name

[p]play https://open.spotify.com/playlist/37i9dQZF1DX5KpP2LN299J?si=Pcr9ifiAT_eROKUXOsxWyw

#### What cog is this command from?

Audio

#### What were you expecting to happen?

The songs in the playlist to be added to the queue.

#### What actually happened?

After getting tracks 62/62, the playlist enqueue fails with the error:
`Invalid Environment
Nothing found.
The YouTube API key may be invalid or you may be rate limited on YouTube's search service.
Check the YouTube API key again and follow the instructions at [p]audioset youtubeapi.`

#### How can we reproduce this issue?

[p]play https://open.spotify.com/playlist/37i9dQZF1DX5KpP2LN299J?si=Pcr9ifiAT_eROKUXOsxWyw

I thought that this was an error with my api key's but upon looking at the google console, it appears all the requests are going through, but at 100% failure rate. Sorry if this doesn't belong here, just trying to fix it.

**Comment by Jackenmen** [comment]
If you need help using Red, you should ask on our support server at [discord.gg/red](https://discord.gg/red). The info posted here most likely doesn't mean that it's an actual bug with the cog, but to know that for sure, we would need more information. I suggest to start by asking in the support server linked above where people experienced with Red problems can try to help you and *if needed*, redirect you here :)

I'm leaving this open for now and if you get further with this - either by solving it or getting more debug info about this, please send an update here.

**Comment by Drapersniper** [comment]
![22E9EC05-8920-423B-8318-E299106D1EC3](https://user-images.githubusercontent.com/27962761/83962794-3a9bb600-a898-11ea-9981-cf53ecf2b54e.png)


For clarity purpose Xanawatt project had no daily quota. This issue can now be closed.
