### ISSUE TITLE
[Trivia] When a trivia game results in a tie, bot picks a random user between the 2 tied players for the payout

### ISSUE THREAD

**Issue by owocado** [Cog-Creators/Red-DiscordBot#3931]
# Command bugs

#### Command name

It doesn't have a command name, because this happens when the trivia ends in a tie.

#### What cog is this command from?

Trivia

#### What were you expecting to happen?

I was expecting the bot to announce that "This trivia session has ended in a tie." Or something like that.

#### What actually happened?

The bot randomly picks a winner between the two winners for the economy payout and "Congratulations, ..... for coming first" announcement. 

#### How can we reproduce this issue?

First set the payout multiplier to your desired value other than the default 0 value with `[p]triviaset payout <value>` command. 
Start and play the trivia with someone else or a group of people. Play in such a way that all participating players ends up winning equal score. When trivia ends, the bot picks a random winner from the players who have tied with equal score for the payout and for "Congratulations, ..... for coming first" message.

**Comment by Jackenmen** [comment]
You're right that this shouldn't happen but the question here is - what should we do when there's a tie? Should we give the full payout to everyone in a tie, split it or should we not give payout at all?

**Comment by Vexed01** [comment]
I think that a split is best as this means the winners don't "miss out" and get nothing and the total paid per trivia remains constant. If not this one, I would lean towards all users getting the full payout.

**Comment by owocado** [comment]
In my opinion, we should give full payout to everyone resulted in a tie, because they all have technically won the game in a sense, so it is fair to pay full payout to each of them, but I can understand if others might have conflicting opinions on this. Splitting the payout would be kind of a cheap move/decision. Not paying at all would be honestly unfair.

Edit: after further consideration and careful thinking, splitting the payout sounds fair.

**Comment by Drapersniper** [comment]
Im personally in favour of splitting the payout, a lot of server/bot owner care about their economy and splitting the payout would be the most balanced way to fix this issue.

**Comment by Jackenmen** [comment]
I tend to agree with splitting the payout too so unless someone else wants to voice their opinion, I'm gonna mark it as accepted in about 18 hours with splitting the payout as the solution that should be implemented.

**Comment by yamikaitou** [comment]
+1 for splitting the payout between the winners

**Comment by NeuroAssassin** [comment]
I think splitting up the payouts is a good idea as well

**Comment by leblancg** [comment]
Hi, I am interested in taking on this issue! Is it currently only possible to reach a tie case if the trivia game reaches the response timeout? Or is it possible for more than one user to win a trivia question and score a point?

**Comment by Flame442** [comment]
I believe a tie can also occur when the bot runs out of questions before the point limit.

**Comment by Flame442** [comment]
Implemented by #4649
