### ISSUE TITLE
Remove the extras from Red's splash screen (or only show postgres)

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3936]
The extras shown in our splash screen are useless - Voice is always True since 3.0.0, Docs and Tests extras are irrelevant when running Red (they are only needed to run the external tools for development like sphinx or pytest):
![image](https://user-images.githubusercontent.com/6032823/83971322-26c57380-a8db-11ea-811a-018038d2c5b9.png)

I say we either should just get rid of that or only put Postgres extra in there (and more extras in future if we would have more)
Also, if we were to go with the latter it could somehow be made clearer what the ticks in that box mean.

**Comment by Drapersniper** [comment]
Kowlin is working on that screen to implement Rich, so could be a good time to nuke everything to oblivion, and just keep stuff the extra drivers (postgres, redis)

**Comment by Jackenmen** [comment]
> to implement Rich

To implement what?

**Comment by Drapersniper** [comment]
Redoing that screen using https://github.com/willmcgugan/rich

**Comment by Jackenmen** [comment]
@Kowlin sure likes to play with cool stuff 😏 thanks for clarifying

**Comment by NeuroAssassin** [comment]
> @Kowlin sure likes to play with cool stuff 😏 thanks for clarifying

I'm working on it as well with Kowlin.

**Comment by goettner** [comment]
Is this issue still relevant? If so, I'd be happy to take a look at it.

**Comment by Kowlin** [comment]
@goettner this is currently handled in #4577.
