### ISSUE TITLE
[Audio] Twitch.tv links are no longer functional

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3937]
This issue is solely for the purpose of visibility.

No need to comment saying you are seeing, as this is not something that Red can fix and is something that needs to be fixed upstream

Lavalink server returns : `Server responded with an error.`

**Comment by aikaterna** [comment]
This was resolved with the Lavalink.jar that is currently in use on Red 3.4.0 (https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.3.1_1069)
