### ISSUE TITLE
[Drivers] Add the best driver ever

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3939]
After some discussion I realise red is lacking a portable driver that's available to all users natively, that users have full control over.

As such I will be implemented a discord message based driver.

As fast as the api allows you so if it's slow blame discord, no longer will I/Os be an issue.

Uses 0 storage space, store everything in discord servers.

Super secure, only people you give permission too will be able to see it using discord flawless permission system.

Easily delete any unwanted data by using discord amazing search function and delete functions.

Are you nosey? Pin up to 50 entries for each access.

As part of Red V3.3.-9 this new driver will be available so get ready for it.

**Comment by Stonedestroyer** [comment]
I think if add this driver we should have each category be a cog and then each scope it's own channel. But maybe it's better if each cog is it's own server? That does add problem for bots above 20 servers that can't create guilds. 

But one category per cog and then one channel per scope could work. Also if we utilize discord edit messages thing we could make some very advanced stuff with changelog and rollback.

**Comment by Jackenmen** [comment]
I know we haven't discussed this but like Trump (just with *slightly* less powah) I'm vetoing this or in other words... 
NO! 
![bdd](https://user-images.githubusercontent.com/6032823/83997138-01c61480-a95e-11ea-92fc-20f0b59f5877.jpg)
