### ISSUE TITLE
[Downloader] Add embed version of `findcog`

### ISSUE THREAD

**Issue by Vexed01** [Cog-Creators/Red-DiscordBot#3944]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

An embed version of `[p]findcog`.

#### Aditional details

I'll do this at some point soonish, which likely will involve removing the function `format_findcog_info` ([L1317-1358](https://github.com/Cog-Creators/Red-DiscordBot/blob/f59e77002b33677b078a427b72acd5beb1598d24/redbot/cogs/downloader/downloader.py#L1317-1358)). If anyone has anything to add before I delve into downloader for the first time, speak now!
Draper also said I should look at L1346 and 1347 whilst in this area of the code:
```py
made_by = "26 & co."
repo_url = "https://github.com/Cog-Creators/Red-DiscordBot"

**Comment by Jackenmen** [comment]
> An embed version of `[p]findcog`.

I don't see the need *personally*, but if it won't look terrible and the command will still be available when embeds are disabled, I guess I don't really mind. Hopefully it also won't take a lot more space than the non-embed version :P

> Draper also said I should look at L1346 and 1347 whilst in this area of the code

@Drapersniper what do you want to change about it?

**Comment by Drapersniper** [comment]
> > An embed version of `[p]findcog`.
> 
> I don't see the need _personally_, but if it won't look terrible and the command will still be available when embeds are disabled, I guess I don't really mind. Hopefully it also won't take a lot more space than the non-embed version :P
> 
> > Draper also said I should look at L1346 and 1347 whilst in this area of the code
> 
> @Drapersniper what do you want to change about it?

 I would like to see core cogs keeping this while local cogs say local for the repo and n/a for author

**Comment by Vexed01** [comment]
I'm thinking of something like this:
![This is the link to the image. You're looking at this is <#450749498231357450> aren't you? Well, either click me or open the comment on GH to see the image. Soz :/](http://i.vex.my.to/vYf1yd)
Yes, I know the branch name looks a bit out of place but most repos have v3 as the default branch so this isn't a big issue, in my opinion.

In terms of lines jack, it shouldn't be more than +10/20 or so as I'm taking out a function's docstring. Edit: Well actually you probably mean space in discord...
Or if you mean space in discord then look ^ - making them inline means its about the same if there's no repo branch

**Comment by Jackenmen** [comment]
> Or if you mean space in discord then look ^ - making them inline means its about the same if there's no repo branch

yeah, that's what I meant, the amount of lines of code doesn't really matter unless you make it unnecessarily long 😄 

> I would like to see core cogs keeping this while local cogs say local for the repo and n/a for author

Yeah, that's fine, try not to forget about it, since this issue is focused on different thing :)

Probably the way to go about it would be checking cog's `__module__` for `redbot.cogs.`
