### ISSUE TITLE
[Downloader] `repo incorrectsubcommand` causes bot to type

### ISSUE THREAD

**Issue by Vexed01** [Cog-Creators/Red-DiscordBot#3948]
# Command bugs

#### Command name

`[p]repo/cog/pipinstall*` (without any subcommands)

#### What cog is this command from?

Downloader

#### What were you expecting to happen?

The bot to not start typing.

#### What actually happened?

The bot started typing.

#### How can we reproduce this issue?

1. Run `[p]cog` or `[p]repo` without any subcommands

#### Aditional info

*`[p]pipinstall` only types for under a second, whilst the others type for a few seconds.

I haven't tested this on downloader's hidden commands.

I had a quick look for any "stray" `ctx.typing`s and it appears there aren't any unless I cannot use Ctrl + F (which is likely).

**Comment by Jackenmen** [comment]
I'm rather sure it's about this:
https://github.com/Cog-Creators/Red-DiscordBot/blob/4335b3b2d420689127aae560a80cb20d9b05af05/redbot/cogs/downloader/downloader.py#L69-L70

I can't check it myself, but shouldn't the bot stop typing as soon as it sends the help message? Cause if it does, I don't see what's wrong with this.

**Comment by Vexed01** [comment]
It stops typing after the help message on `[p]pipinstall`, but not with `cog` or `repo`. This behaviour for `cog` and `repo` also happens with subcommands when the help message is displayed.
![http://i.vex.my.to/7vO7ht](http://i.vex.my.to/7vO7ht)
