### ISSUE TITLE
loop function missing?

### ISSUE THREAD

**Issue by LogFan** [Cog-Creators/Red-DiscordBot#395]
Hi, the doc write about a [p]loop function but it doesn't seem to be implemented. I just looked at the code, and it doesn't look like complicated to do this.

Does "audio_player" and "voice_client" have an doc anywhere? Maybe one of this has the good function :)

**Comment by Twentysix26** [comment]
Like stated, the command list in the docs is purely indicative and not kept up to date  
`[p]audioset loop` is the current command.
