### ISSUE TITLE
[Core] User embed settings does nothing

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#3953]
# Other bugs

#### What were you trying to do?

Disable embeds for myself

#### What were you expecting to happen?

Commands that supports `[p]embedset` show plain text message, when user's embeds is disabled (i.e. `[p]help`)

#### What actually happened?

Messages are still embedded

#### How can we reproduce this issue?

1. Setup latest develop version
2. Use `[p]embedset user False` to disable embeds for yourself
3. Try `[p]help`, it will be embedded

**Comment by Jackenmen** [comment]
This is intended and the help docstring for this is just outdated. PRs that remove the information about special-casing help are welcome.
