### ISSUE TITLE
Uploading Images with Red

### ISSUE THREAD

**Issue by VioletRDB** [Cog-Creators/Red-DiscordBot#397]
Because of the custom emoji update being /less/ than ideal in sizes, people on my server have been asking me for an emote cog. I have pretty much everything, but I don't know how to have Red directly upload an image to the text chat. Is it possible, or is there a workaround that I'm not seeing? I've been looking around for a few hours, but I couldn't find anything helpful.

**Comment by Twentysix26** [comment]
I'm not sure what you're asking exactly. You can't make such a feature with normal commands, you'll have to code it yourself.  
Docs of discord.py: http://discordpy.readthedocs.org/en/latest/

**Comment by skeith** [comment]
Axios has emote cog

https://github.com/Aioxas/ax-cogs/tree/master/emote
