### ISSUE TITLE
Red is spamming postgres with an invalid query 

### ISSUE THREAD

**Issue by Ryonez** [Cog-Creators/Red-DiscordBot#3983]
# Other bugs

#### What were you trying to do?

Was looking at my database logs for another issue.

#### What were you expecting to happen?

To find something related to my other issue.

#### What actually happened?

I found this:
![image](https://user-images.githubusercontent.com/16157130/85005638-32534d00-b1ad-11ea-8220-0ac0844f3e08.png)

#### How can we reproduce this issue?

I honestly have no clue, I'm hoping you guys know what's happening here.

**Comment by Drapersniper** [comment]
All I see is Red trying to get a value that doesnt exist, which makes it use the default set by cogs.

**Comment by Ryonez** [comment]
Why is this ending up in my database logs then?

**Comment by Drapersniper** [comment]
Because a query is being made for the value?

**Comment by Ryonez** [comment]
I guess this is a case where I'm just surprised because I've never seen a database log to the docker logs for query errors so far.

Can this be fixed on red's side? Something like if value not found then create default? Because I'd like to use the logs, and having them spammed with the same query from something else is a little harder to sort through.

**Comment by Drapersniper** [comment]
Postgres data is not cached within red.

So everytime a valueis queried, and it doesnt exist in the database the error is raised which signals that the default value in memory should be used.

There doesn't really seem to be anything broken here as we need to know when a value doesnt exist to use the default.

**Comment by Ryonez** [comment]
Hmm, maybe there's a way to tweak the verbosity on Postgres's side then.

**Comment by Ryonez** [comment]
Oh, thank you very much!

I must confesses I'd put this out of mind long ago >.<
