### ISSUE TITLE
Red terminates without logical cause

### ISSUE THREAD

**Issue by ADAMPOKE111** [Cog-Creators/Red-DiscordBot#399]
Red crashes for seemingly no reason. The output in the console I get is this:

```
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at /home/bot/Red-DiscordBot/cogs/audio.py:1952> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at /home/bot/Red-DiscordBot/cogs/audio.py:1841> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at /home/bot/Red-DiscordBot/cogs/audio.py:1956> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /home/bot/Red-DiscordBot/cogs/streams.py:404> wait_for=<Future pending cb=[Task._wakeup()]>>Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_manager() running at /home/bot/Red-DiscordBot/cogs/audio.py:1799> wait_for=<Future pending cb=[Task._wakeup()]>>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe171c92940>
```

I am running the latest version of Red.

**Comment by Twentysix26** [comment]
Need complete traceback. If that's all there is it might be your connection

**Comment by ADAMPOKE111** [comment]
There's no more faults/outputs/errors in the console apart from this. What issue with my connection might it be? Packet loss?

**Comment by Twentysix26** [comment]
I cannot know from that. Does it happen that often?

**Comment by ADAMPOKE111** [comment]
It happens at least once a day. I have to keep restarting it over and over.

**Comment by Twentysix26** [comment]
Even without these issues it's very recommended that you use an autorestart solution, as described here
https://twentysix26.github.io/Red-Docs/red_guide_linux_autostart/
This will assure that the bot restarts and comes back online if your connection goes down or Discord has problems. Pick the right one for your system.  
This shoud solve your problem.
