### ISSUE TITLE
[Help] Add current settings to `[p]helpset` cmd

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#4013]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Add current settings display (as in `[p]modset`/`[p]set`) for `[p]helpset` command

**Comment by mikeshardmind** [comment]
I would seriously prefer if there was an additional command to list settings rather than spit the settings out on a group that would otherwise only send help, especially with the behavior of help being opened up more to 3rd party customization.

**Comment by mikeshardmind** [comment]
If it goes the separate settings command route, I'd be happy to PR the changes I'm currently testing [here](https://github.com/mikeshardmind/Red-DiscordBot/commit/d2150323ce09d7b3a09033b2e3b9e0162e08333c) after #4011 as the way this is handled is somewhat dependent on those changes.

**Comment by Jackenmen** [comment]
I prefer a separate command too. While it is somewhat convenient to see the settings when you use the group command, it can imo also be annoying.
