### ISSUE TITLE
Failing to find video/song with the parameters given

### ISSUE THREAD

**Issue by LogicPlague** [Cog-Creators/Red-DiscordBot#4029]
# Command bugs

#### Command name

[p]play

#### What cog is this command from?

audio

#### What were you expecting to happen?

I was expecting the bot to find the song and play it.

#### What actually happened?

It didn't find the song to play it and replied with "Nothing found." in chat.

#### How can we reproduce this issue?

1. Type [p]play [song name]
2. Press enter
3. The bot will most likely respond with "Nothing found."

#### Other info.

The bot may even error if there is a video/song on YouTube with the exact name. However, if you use the URL instead of the name, the bot will most likely find and play it.

[p] = stands for bots prefix
[song name] = stands for the name of song or video used.

**Comment by flaree** [comment]
Hey, you'll be able to get greater help if you head to the support server over @ https://discord.gg/red

**Comment by aikaterna** [comment]
Also this is relevant here: https://github.com/Cog-Creators/Red-DiscordBot/issues/3943#issuecomment-644940587
