### ISSUE TITLE
RED throws up errors when reaching the end of a local playlist

### ISSUE THREAD

**Issue by link1021l** [Cog-Creators/Red-DiscordBot#405]
As the title says, if you reach the end of a local playlist using actual .MP3 files, RED will not loop around and instead will throw up the "data/audio/localtracks: No such file or directory" error over and over again every second until you start another playlist (using !stop causes RED to say she isn't playing anything)

**Comment by Eslyium** [comment]
Error code please?

**Comment by link1021l** [comment]
As I said in the post, it simply says "data/audio/localtracks: No such file or directory" over and over.

**Comment by link1021l** [comment]
Is there another error code I should be looking for?

**Comment by Twentysix26** [comment]
No, I was able to reproduce it

**Comment by tekulvw** [comment]
#441 should fix this
