### ISSUE TITLE
[Help] Let the user define how many time the reaction must disappear 

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#4074]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

Some of my users were complaining about how many time reactions disappear, thing that I understand since help command can be big depending the settings and cogs loaded.
It would be nice if the owner can set up this option.

**Comment by Drapersniper** [comment]
It will be less of an issue when #4062 is merged as that will set the timeout to 3 minutes rather than 30 seconds.

but an option to customize help timeout would be nice indeed.

**Comment by mikeshardmind** [comment]
As discussed elsewhere with @Drapersniper , I'm aware of an issue with adding this setting currently that's intertwined with some other things that need further exploration before being put in the public eye.
