### ISSUE TITLE
[i18n] Crowdin pulls norweigan as no-NO but babel sets as nb-NO

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#4080]
# Other bugs

#### What were you trying to do?

Crowdin pulls in Norwegian `po` files as `no-NO.po` however Babel's `Locale.parse` parses `no-NO` as `nb-NO`.

#### What were you expecting to happen?

Norwegian translations to work.

#### What actually happened?

They didn't render.

#### How can we reproduce this issue?

1. `[p]set locale no-NO`
2. `[p]set showsettings`

---

Babel's `Locale.parse()` is the issue:
```py
from babel import Locale as BabelLocale
return BabelLocale.parse("no-NO", sep="-")
```

↑ returns `nb-NO`, Crowdin pulls in the files as no-NO thus translations don't work.

**Comment by Jackenmen** [comment]
From quick eval, `po` files with these names don't have a match in Babel:
```
no-NO: this locale is called `nb-NO` in Babel
debugging: this locale doesn't exist in Babel
en-PT: this locale doesn't exist in Babel
lol-US: this locale doesn't exist in Babel
sr-SP: this locale doesn't exist in Babel
```

The relevant eval:
```py
from pathlib import Path

import babel
import redbot

root = Path(redbot.__file__).parent
po_filenames = set()
for path in root.glob("**/locales/*.po"):
    po_filenames.add(path.stem)
for name in po_filenames:
    try:
        locale = babel.Locale.parse(name, "-")
    except babel.UnknownLocaleError:
        print(f"{name}: this locale doesn't exist in Babel")
    else:
        result = f"{locale.language}-{locale.territory}"
        if result != name:
            print(f"{name}: this locale is called `{result}` in Babel")
```

I'm not entirely sure what's the right way to solve this, but I'm guessing it probably makes most sense to update the relevant language code(s) on Crowdin. I'm guessing `debugging` locale should be special-cased although I'm not sure what is its purpose.

There's also a `lol-US` locale in our po files for some reason...

**Comment by Kowlin** [comment]
I'm honestly surprised about the existence of lol-US within Crowdin, will take a look at it on Crowdin's side when I get the chance.

**Comment by Kowlin** [comment]
So after looking into the case of ``no-NO`` and ``nb-NO``, it appears that according to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (from my understanding) Norwegian has [2 distinct styles of writing](https://en.wikipedia.org/wiki/Norwegian_language#Bokm%C3%A5l_and_Nynorsk). However! Crowdin offers not only the Riksmål and Bokmål dialects, but also a generic Norwegian one. So what Crowdin is doing here is technically correct, but not not in the eyes of Babel.

**Comment by Kowlin** [comment]
I've replaced Crowdin's generic ``no-NO`` with ``nb-NO`` as recommended by Norwegian speakers them self. This will be reflected on the next Crowdin push I'm gonna do in a second, and in the next version of Red.
