### ISSUE TITLE
[Mute] Add ``[p]mute all`` to combine voice and text mute

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#4083]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

Cog : Mutes (after #3634) / Mod (pre #3634)
Command: ``[p]mute all`` / ``[p]unmute all``
Function: Applies a guild mute. Additionally mutes in all voicechannels though.

Instead of this issue staying open #3597 can be amended.

**Comment by Jackenmen** [comment]
`[p]mute server` (now called just `[p]mute`) has been changed to mute all channels, not just text channels so this is technically resolved.
