### ISSUE TITLE
[General] [p]urban command doesn't support a weird string of characters

### ISSUE THREAD

**Issue by SapphicCode** [Cog-Creators/Red-DiscordBot#409]
It returns [this error](http://i.imgur.com/8fgmE6M.png), even though it's actually [a definition on Urban Dictionary](https://www.urbandictionary.com/define.php?term=FL%C3%9CGG%C3%85%D3%98NK%D0%B1%E2%82%AC%C4%8CHI%C5%92%C3%9F%C3%98L%C4%AE%C3%8AN).

**Comment by Kowlin** [comment]
This will be easily resolved with `urilib` encoding feature. See the Google.py code for a example of URL encoding (cugh clever bot)

**Comment by vjFaLk** [comment]
Weirdly, http://api.urbandictionary.com/v0/define?term=FLÜGGÅӘNKб€ČHIŒßØLĮÊN respoinds with sounds, but no definitions.
