### ISSUE TITLE
Look through emojis used in Red to see if some don't need variation selector

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4106]
#4105 handles emojis in chat formatting, but all other places in Red still need to be checked. 

Info copied from Sinbad's PR:
  - Ensures consistent rendering across devices
  - See:  https://unicode.org/Public/emoji/12.1/emoji-variation-sequences.txt

**Comment by flaree** [comment]
left/right arrow in DEFAULT_CONTROLS also needs the selector
