### ISSUE TITLE
Silent 'cog update' errors

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#411]
It is possible for errors to occur because of a failed `git stash`. The entire repo folder inside of data/downloader _should_ be removed and re-cloned each time `cog update` is called imo.

**Comment by Kowlin** [comment]
I agree with this. But what we should take in consideration is that there is a ratelimit on cloning from Github. I personally don't know what it was. But I'm sure it exists

**Comment by tekulvw** [comment]
It doesn't, actually. There was this big official github blog post a while back about some company using gh as a cdn, which is totally okay they were just big enough that it was causing some server issues.

As an alternative we may want to `git reset --hard` instead of re-cloning.

**Comment by Twentysix26** [comment]
How does git stash even fail? Is this in case the user doesn't have git name/email set?

**Comment by tekulvw** [comment]
Either that or files magically get changed and can't be re-stashed. Honestly I don't know, but I know it's happened on my vps more than once

**Comment by Kowlin** [comment]
Then I'm wrong on that fact. But I recall adding a token to Composer

**Comment by tekulvw** [comment]
Will be fixed with #450

**Comment by Kowlin** [comment]
Closing due to #450 being merged.
