### ISSUE TITLE
[Downloader] Shows cogs that are not installed as installed.

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#4117]
# Other bugs

#### What were you trying to do?

Trying to see what cogs I have installed.

#### What were you expecting to happen?

The bot to show me all my INSTALLED loaded and unloaded cogs

#### What actually happened?

"unloaded" field shows cogs that aren't even installed. Trying to uninstall the cogs shown fails.

#### How can we reproduce this issue?

I don't know to be honest.

![Screenshot_20200726-123959.jpg](https://user-images.githubusercontent.com/57032623/88477065-73691a80-cf2c-11ea-8c8f-cae4d1b1b0f2.jpg)

**Comment by Dav-Git** [comment]
As an addition, it also shows loaded cogs as unloaded. ![Screenshot_20200726-124625.jpg](https://user-images.githubusercontent.com/57032623/88477191-70225e80-cf2d-11ea-87b5-147a50b22856.jpg)![Screenshot_20200726-124645.jpg](https://user-images.githubusercontent.com/57032623/88477195-71ec2200-cf2d-11ea-9168-dbacf83e4b3c.jpg)

System logs are clear except for the traceback shown

**Comment by Jackenmen** [comment]
`[p]cogs` just shows all cog packages that are in any cog path (`[p]paths`), any package inside some cog path can be in practicality called "installed".
But if these "not installed" cog packages are in `<datapath>/cogs/CogManager/cogs` path, and you aren't the one who put them there manually, maybe it is a bug with Downloader, but unless you can reproduce it, there's not much we can really do about it.
As for showing loaded cogs as unloaded, the cog **package** (called extension in d.py terminology) called "dev" is not loaded, there just already exists a different cog (not cog package) with name "Dev" (which most likely is the one loaded by `--dev` flag) and that's what `dev` cog package tries to add and fails.

**Comment by Dav-Git** [comment]
You're right on dev. Completely forgot I was running with --dev. The cogs shown are not in any cog path. I double-checked before opening the issue. I didn't do anything for this to happen. It just appeared like this overnight and a restart doesn't fix the issue either

**Comment by Jackenmen** [comment]
> The cogs shown are not in any cog path.

I am doubting a bit that this is true - one of your cog paths appears to be `/home/discbot/git-stuff/Trusty-cogs` (see the traceback that you sent of trying to load `dev` cog package) and I am taking an educated guess that it contains all these "not installed" cogs.

**Comment by Dav-Git** [comment]
Yes you are right. I forgot that I had overwritten the path command... Big mistake on my end. This is a non-issue afterall.
