### ISSUE TITLE
[BUG] Serverlock does not serverlock.

### ISSUE THREAD

**Issue by ltzmax** [Cog-Creators/Red-DiscordBot#4123]
### Command name

!serverlock

#### Did you find a bug with a command?

Yes

#### What cog is this command from?

Admin

#### What were you expecting to happen?

the command to replay "The bot is now serverlocked."

#### What actually happened?

Nothing.

#### How can we reproduce this issue?

1.have the bot in 1 server, and use !serverlock.
2.try on a different bot that is not dev.

i'm not actually sure if its a bug.. but it does not response or actually serverlock the bot. i have tried on all my 3 servers and it yet doesnt response or do any serverlock... (iknow you can turn off the public settings in the developer portal.)

my bot is on latest dev verison.

**Comment by Flame442** [comment]
A few things could be wrong here
1. You are not considered the bot owner. You can check who the bot owner is considered by using `[p]info`.
2. The admin cog is not loaded. You can try loading it with `[p]load admin`.
3. Some kind of permission issue preventing the bot from reading/sending messages in all of your servers (unlikely).

I can't reproduce this issue, so if you need more help figuring this out, come to #support in https://discord.gg/red.
