### ISSUE TITLE
Move commands for changing Bank and ModLog API settings to `[p]set`

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4128]
To be specific:
- `[p]modlogset` from `modlog` cog should be moved to `[p]set modlog`
- `[p]bankset` from `bank` cog should be moved to `[p]set bank` (as part of this, `bank` cog would be removed)
- `[p]economyset registeramount` from `economy` cog should be moved to `[p]set bank registeramount`
- (this is a maybe) `[p]bank reset` and `[p]bank prune` should be made part of `[p]set bank`

IMO, they shouldn't be part of any cog since they allow to change settings of a core API, same as `[p]autoimmune`, `[p]whitelist`, or `[p]embedset` that also allow users to change API settings.

Relevant discussion can be found in: #4067 

This is currently planned for 3.5.0 release as it's going to break people's usage of permissions.

**Comment by Dav-Git** [comment]
Whoever takes this should see #4067 for prior discussions
