### ISSUE TITLE
Local playlists don't play in order

### ISSUE THREAD

**Issue by inklesspen** [Cog-Creators/Red-DiscordBot#413]
I have a local playlist consisting of an audio drama. Each file is named with a leading zero-prefixed number: `01, 02, ..., 10, 11, etc`. However, playing a local playlist did not start with `01` as I would have expected.

**Comment by tekulvw** [comment]
#441 should fix this

**Comment by Twentysix26** [comment]
Solved in https://github.com/Twentysix26/Red-DiscordBot/pull/441
