### ISSUE TITLE
[Mute] Voicemute doesn't work if user is server muted.

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#4139]
# Command bugs

#### Command name

``[p]mute voice``

#### What cog is this command from?

Mute

#### What were you expecting to happen?

User to be unable to speak in or join (not sure which one it was) in a voicechannel.

#### What actually happened?

Bot said: "That user can't send messages in this channel."

#### How can we reproduce this issue?

```[p]mute server @User```
Wait for confirmation message
```[p]mute voice @User```

**Comment by mavaddat** [comment]
Is this a bug? Isn't it [supposed to say this](https://github.com/Cog-Creators/Red-DiscordBot/blob/6cef336417551909ee47039579c4110609ad64fe/redbot/cogs/mod/mutes.py#L13) when the user is already muted?

**Comment by Dav-Git** [comment]
> Is this a bug? Isn't it [supposed to say this](https://github.com/Cog-Creators/Red-DiscordBot/blob/6cef336417551909ee47039579c4110609ad64fe/redbot/cogs/mod/mutes.py#L13) when the user is already muted? 

The user is not actually muted in voice channels

**Comment by mavaddat** [comment]
> The user is not actually muted in voice channels

So then there is also a bug that `server mute` does not actually mute the user?

**Comment by Dav-Git** [comment]
> > The user is not actually muted in voice channels
> 
> So then there is also a bug that `server mute` does not actually mute the user?

That is the bug I am speaking about in the issue description.... It only mutes the user in **text**channels

**Comment by Dav-Git** [comment]
Closed due to being irrelevant after #3634
