### ISSUE TITLE
[Core] Expand TimeDeltaConverter to accept month and year as valid timedeltas or edit other means of reading human readable time

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#4140]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

The commands.TimeDeltaConverter currently only supports inputs of up to ``x weeks``, however it would be very useful (especially for usecases like tempban) if it would also accept ``x months`` or ``x years``.

**Comment by mikeshardmind** [comment]
I would rather this not be part of the timedelta converter and part of a broader human time handling being added instead. The units supported right now all have fixed lengths, whereas months and years have to be calculated relative to current date and time for correctness.

**Comment by Dav-Git** [comment]
Title updated to maybe reflect this?
