### ISSUE TITLE
[redbot-setup] Cannot exit

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#4145]
# Other bugs

#### What were you trying to do?

I got asked to prompt a token, and tried exiting.

#### What were you expecting to happen?

Leave.

#### What actually happened?

I cannot exit when doing Ctrl+C, and using a wrong token don't let me go too.

#### How can we reproduce this issue?

- Create an instance.
- Start the instance.
- When asking for the token, try exiting.

**Comment by Dav-Git** [comment]
I can't reproduce this. Ctrl+C worked fine for me on Ubuntu 20.04 LTS and Windows 10 in powershell (didn't test cmd)

**Comment by madebylydia** [comment]
My machine is also using on Ubuntu 20.04... 🤔
![image](https://user-images.githubusercontent.com/61093863/89108395-5fe01700-d438-11ea-834f-22b6a3d45d3e.png)

**Comment by yamikaitou** [comment]
Confirmed when using ssh within Windows terminal

**Comment by yamikaitou** [comment]
![image](https://user-images.githubusercontent.com/833969/89108527-32c74080-d407-11ea-8175-f78a014458cb.png)
I found a workaround, not ideal but it semi worked (it prompts me to reset the token when I next run it)

**Comment by Vexed01** [comment]
This does appear to be an issue with SSH. I can reproduce in PuTTY as well as OpenSSH in Windows Terminal, but not directly on the machine.

**Comment by mikeshardmind** [comment]
Sounds like these specific ssh clients aren't passing keyboard interrupt through to the remote. This isn't an issue with Red and works locally.

**Comment by madebylydia** [comment]
*Hey, anyone?*
While this is a SSH client issue and not related to Red, I still think it's an issue to get "forced" to give a valid token.
I think that 'redbot-setup' should give up if we give more than 3 invalid tokens.
