### ISSUE TITLE
Question to all Contributors.

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#4171]
If your name is in this list https://github.com/Cog-Creators/Red-DiscordBot/graphs/contributors

Could you please reply to this issue with your discord name so that we can look into getting you the contributor role in the discord server?

**Comment by maxbooiii** [comment]
MAX#0002

**Comment by Dav-Git** [comment]
Dav#6998 (already have it tho)

**Comment by douglas-cpp** [comment]
Douglas#6849

**Comment by thisisjvgrace** [comment]
឵឵❤#0055 (user id: 306810730055729152)

**Comment by PythonTryHard** [comment]
Hitori Tori#5630 (if we're still open)
