### ISSUE TITLE
Error in user data statement about username history

### ISSUE THREAD

**Issue by PredaaA** [Cog-Creators/Red-DiscordBot#4177]
[Here](https://docs.discord.red/en/latest/red_core_data_statement.html#what-data-red-collects) and most specifically at this "In particular the bot will keep track of a short history of usernames/nicknames which actions refer to your Discord account **(such as creating a playlist)**".

By creating a playlist it is just storing user ID. See [redbot/cogs/audio/apis/playlist_interface.py#L83](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/cogs/audio/apis/playlist_interface.py#L83).

**Comment by Jackenmen** [comment]
It's an issue with lack of commas I think - it should be sth like "[...] the bot will keep track of a short history of usernames/nicknames, which actions refer to your Discord account [...]"

**Comment by mikeshardmind** [comment]
As the person who wrote that, yes it's just a lack of clarity as to what each part refers to. Commas would be one way to address this, though not necessarily the clearest. The bot will store nicks/usernames in various places and this should be considered separately from the creation of playlists, which was just an example of actions taken by an account that might trigger certain storage.
