### ISSUE TITLE
[Permissions] DM notification for command in DM

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#4178]
# Command bugs

#### Command name

`permissions acl getglobal`

#### What cog is this command from?

`Permissions`

#### What were you expecting to happen?

Get YAML without notification about DM

#### What actually happened?

Got YAML file and `I've just sent the file to you via DM.` message in DM

#### How can we reproduce this issue?

Execute `[p]permissions acl getglobal` in DM

**Comment by douglascdev** [comment]
I've reproduced this myself and the issue makes sense, there's no need for the bot to tell you the file will be sent via DM if you're already DMing the bot for it.
 Can I make a PR to fix this?

**Comment by Jackenmen** [comment]
@douglas-cpp Of course, feel free to take it :)

**Comment by Jackenmen** [comment]
I went ahead and assigned you, but don't feel obliged to work on it, if you were to change your mind :)
(comment saying so would be appreciated in that case though)
