### ISSUE TITLE
Add Taxed threshholds to the bank API

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#4190]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

-- Allow Bank managers to set tax brackets to be applied on Deposit/transfer

**Comment by palmtree5** [comment]
Soo, with this: what happens to the credits taken for taxes? Should they just disappear? Should they go in a pool to somehow be redistributed? Something else?

**Comment by Drapersniper** [comment]
To sumarize the discussion from discord:

1- I believe we should have both options, which is toggable by the BAND admin *bot owner if global, server admins if server based)
2- I believe if the toggle is set to stockpile this stockpiled value should be retriavable via the bank api (for redistribution)
