### ISSUE TITLE
[Announce] No Error Message

### ISSUE THREAD

**Issue by Jacob-1999** [Cog-Creators/Red-DiscordBot#4196]
# Command bugs

- [x] Bug
- [x] Enhancement
- [ ] Feature

#### Command name

[p]announce

#### What cog is this command from?

Admin

#### What were you expecting to happen?

Error message when no channel was setup to receive announcements

#### What actually happened?

The `The announcement has begun.` message sends regardless if no channel was set to receive announcements.

#### How can we reproduce this issue?

1. Clear your announce channel from all servers your bot is in if you had any set.
2. Use the announce command as normal
3. Observe

**Comment by douglascdev** [comment]
I'm up for solving this, by sending an error message when there is no announcement channel set. Let me know if this is a desired change and I'll make a PR.

**Comment by Jacob-1999** [comment]
I would say its desired because for anyone that uses the announce command and messes up (hard to do but a scenario), would like to know what the error is instead of normal execution.

**Comment by Dav-Git** [comment]
@douglas-cpp you still up to doing this?

**Comment by douglascdev** [comment]
@Dav-Git sure, on it, just thought I should get approval from someone at the org before working on issues without a PR's welcome/accepted tag

**Comment by Jackenmen** [comment]
@douglas-cpp I went ahead and assigned you based on the interest here and in Red server, but don't feel obliged to work on it, if you were to change your mind :)
Let me know if you would want me to unassign you.
