### ISSUE TITLE
Possibly add a blacklist for servers?

### ISSUE THREAD

**Issue by ncodex2** [Cog-Creators/Red-DiscordBot#421]
This is more a suggestion than a issue, maybe possibly a cog or a command that makes the bot owners blacklist a certain server so they can't re-invite the bot?

**Comment by Kowlin** [comment]
interesting concept. I'll look into it, either as a main cog or as a addon for one of the existing core cogs

**Comment by Aioxas** [comment]
Someone was playing around with that. Something about "If x server has less than 100 members, make the bot leave.", I guess this can be further expanded with something along the lines of adding the server id to a blacklist, if it's added to said server, it will automatically leave or something.

**Comment by calebj** [comment]
You can't do what you want directly (a "reverse ban"), but Squid's admin cog does something similar. There's a setting to "lock" the server list. All it does is leave the server right after it's added by someone if the "lock" is enabled.

**Comment by tekulvw** [comment]
I do like the concept of this, I think we may be on the path to including admin in red core for V3 so I'll tag this accordingly.

**Comment by mikeshardmind** [comment]
I'm open to PRing my

[guildblacklist](https://github.com/mikeshardmind/SinbadCogs/tree/v3/guildblacklist) and 
[guildwhitelist](https://github.com/mikeshardmind/SinbadCogs/tree/v3/guildwhitelist)
as core cogs if this functionality is still desired.

In their current form, they can whitelist or blacklist by either owner or guild id. A little rough around the edges and not up to feature parity with the v2 cogs yet, but they could be cleaned up and PR's in if this is still something to be included in v3

**Comment by tekulvw** [comment]
We're gonna satisfy this by having `serverlock` in V3 from the admin cog and having the exact functionality you're looking for available in 3rd party cogs.
