### ISSUE TITLE
My Bot Wont Start.....

### ISSUE THREAD

**Issue by SumRed** [Cog-Creators/Red-DiscordBot#426]
My bot will not start I'm pretty sure I do everything right when I click runbot. This problem comes up http://imgur.com/a/UbCUP not sure what to do not good with this kinda stuff.

Thanks for the help in advance

**Comment by Twentysix26** [comment]
That's not Red.

**Comment by Pandentia** [comment]
Links that might help you out:
https://github.com/SexualRhinoceros/MusicBot
https://discord.gg/0iqN3da4zqpJpuY0
