### ISSUE TITLE
update.bat doesn't work if the server service (LanmanServer) isnt running.

### ISSUE THREAD

**Issue by CyberKiller** [Cog-Creators/Red-DiscordBot#428]
This is because the command `NET SESSION >nul 2>&1` returns an error that the server service isn't running regardless of whether or not the script has admin privileges: 

```
The Server service is not started.

More help is available by typing NET HELPMSG 2114
```

See the answer called "**More Issues**" at the following url: [http://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights](http://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights)
Maybe use one of the two alternatives to check for admin rights in that answer instead.

**Comment by Twentysix26** [comment]
That service is on by default on all Windows OS since XP. Any reason why you disabled it?

**Comment by CyberKiller** [comment]
I disabled it for security reasons and because I don't use it. I suppose very few people would have it disabled though.

**Comment by skeith** [comment]
There is an alternative for this without coding any admin checks on the bat file, which is converting the bat to a small EXE which add/ask admin privilege (http://www.f2ko.de/en/b2e.php) - need testing

**Comment by CyberKiller** [comment]
I also made my own workaround which is a little AutoIt script that I have posted below if anyone else wants to use it:

```
#RequireAdmin

#include <FileConstants.au3>

Opt("MustDeclareVars", 1)

Local Const $sFile = @ScriptDir & "\update.bat", $sTmpFile = @ScriptDir & "\TEMPupdate.bat"
Local $hFile = FileOpen($sFile, $FO_READ)
Local $s = FileRead($hFile)
FileClose($hFile)
$s = StringReplace($s, "net session >nul 2>&1", "fsutil dirty query %systemdrive% >nul")
$hFile = FileOpen($sTmpFile, $FO_OVERWRITE)
FileWrite($hFile, $s)
FileClose($hFile)
ShellExecuteWait($sTmpFile)
FileDelete($sTmpFile)
```

The #RequireAdmin statement makes the script elevate it's self to admin (you still get the UAC prompt), then it reads update.bat into a string, replaces the offending line with an alternative one and writes the string to a temp .bat file, ShellExecutes it and deletes the temp file after the update script has finished.

**Comment by Twentysix26** [comment]
`update.bat` has been replaced by the launcher
