### ISSUE TITLE
[Request] Delete initiating command.

### ISSUE THREAD

**Issue by xdtrammell** [Cog-Creators/Red-DiscordBot#431]
Hi I just recently got the bot setup and I love it. The old bot I was using for music had an option to delete the command the initiated it after few seconds. I am ocd about having commands in the text chat and have to keep deleting them manually.  If you could add this feature It would be amazing. [The old bot I was using ](https://github.com/Just-Some-Bots/MusicBot) would keep its self contained to about one line for music.

**Comment by tekulvw** [comment]
Implemented in #445
