### ISSUE TITLE
Ability to lock bot commands to a channel

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#4361]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

The ability to lock all commands to a single channel from a guild owner perspective. This can be frustrating for servers with large guilds.

An alternative may be the ability to use greedy in the ignore channel function.

**Comment by TurnrDev** [comment]
This, yes please

**Comment by Jackenmen** [comment]
Full allow/blocklist-like behavior for ignoring would IMO be the ideal solution, but it requires increasing the complexity of it a fair bit, so providing a middle-ground like #4458 for the time-being might not be a bad idea. I would appreciate more feedback here.
