### ISSUE TITLE
Stop getting a DM when using dev

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#4365]
# Feature request

#### Select the type of feature you are requesting:

- [X] Core

#### Describe your requested feature

Every time I use a development version of Red, I'm receiving a DM message telling me to update Red to the latest version. I would like the bot to stop DMing me when I use dev.

**Comment by Drapersniper** [comment]
I'm not in favour of this. If the dev build is out of date it should inform users

**Comment by flaree** [comment]
He's using the 3.4.0 dev so he is behind on the current dev release

**Comment by Dav-Git** [comment]
I think Predator means if using 3.4.1dev you still get the DM that 3.4 is current version

**Comment by Dav-Git** [comment]
Lol autocorrect

**Comment by madebylydia** [comment]
run.

**Comment by Drapersniper** [comment]
I'm on 3.4.1.dev1 and I don't get notification at all. Since that's newer than 3.4.0
