### ISSUE TITLE
Pagify - escape param ignores page_length

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Red-DiscordBot#438]
implications: possible msgs over 2000

**Comment by Chovin** [comment]
^ fixes this issue but now msgs with a bunch of @ here @ everyone will chew into the page length quite a bit

**Comment by Kowlin** [comment]
Technically fixed? or can we wait for #543?

**Comment by Chovin** [comment]
not fixed, the problem was just moved the other direction. wait for #543

**Comment by Tobotimus** [comment]
This has been fixed for V3, are there plans to implement for V2?

**Comment by tekulvw** [comment]
Stale
