### ISSUE TITLE
Red does not escape Markdown in name/nickname when adding into [p]help's embed

### ISSUE THREAD

**Issue by PythonTryHard** [Cog-Creators/Red-DiscordBot#4380]
# Command bugs

#### Command name
`[p]help`

#### What cog is this command from?

Core

#### What were you expecting to happen?

`[p]help` fully escapes semi-valid Markdown markers in bot's displayed name when put into embed, ie.

:::::::::::::::::::: Embed ::::::::::::::::::::
**servers** Lists and allows \`Bot Name to leave servers.
**set** Changes \`Bot Name's settings.
:::::::::::::::::::: Embed ::::::::::::::::::::

and so on.

#### What actually happened?
![image](https://user-images.githubusercontent.com/31789326/91642883-24496480-ea59-11ea-9d98-a9b16a7fe1d2.png)

#### How can we reproduce this issue?
1. From anywhere that you can call `[p]help`, set Red's nickname to contain half of Markdown formatter (\`, \*, \*\*,\*\*\*). Red will not print out any error message. In my case I set to "\`Bot Name"
2. Call `[p]help`. 

Bug found on version 3.4.0, installed from PyPi with `pip install Red-DiscordBot`

**Comment by Jackenmen** [comment]
Adding escaping for bot name will break the non-embed version of help. We also can't feasibly escape only when embed version is supposed to be sent as the method giving help text can be overridden by cog creators and if we would add something like `is_embed` kwarg, we would break help for every cog that was overriding that method.
We might make some plans for this later, but I'll be freezing this for now as I don't think we'll be able to change this in near future.

**Comment by Flame442** [comment]
Due to Jack's comments above, and the fact that the name has to be deliberately set to have formatting characters that would break help, this is not something that we are currently looking to fix.
