### ISSUE TITLE
Allow command processing on_message_edit

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#4401]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

This is a widely attempted action across all bots on discord, currently a 3rd party cog can be used to achieve this behaviour but I think it would fit in core if we allowed it to respect a toggle that should be on by default (to allow it to reach as many users as possible)

**Comment by TurnrDev** [comment]
Sounds good, my only concern is checking that that message has already successfully triggered a command, and if it has, what should be done in that situation.

**Comment by Zephyrkul** [comment]
If it's already available as a 3rd party cog, why the sudden need to make it core?

**Comment by Drapersniper** [comment]
> imo highly used stuff could have a spot in core to be readily accessible. Definitely improves the UX of the bot overall

As Flare stated in #tesinting, and I couldn't reiterate this, imo anything that makes devs and users life easier can and should be added to core, the amount of users that attempt doing this already, by making this into a core functionality it expands the number of users this functionality is availiable to, hence the comment about making it on by default.

@TurnrDev it would just process the new command, unless we would want it parse it and ignore messages that already processed a command, but i personally see no need for this. if i run `[p]help` then edit to `[p]info` i personally dont see an issue with it running both commands.

**Comment by TurnrDev** [comment]
Any issues I have are with management comnands, but since you'd need a privileged role anyway + management actions would appear in the ModLog, I guess it's not the worst thing in the world.
