### ISSUE TITLE
version and changelog support for info.json

### ISSUE THREAD

**Issue by TurnrDev** [Cog-Creators/Red-DiscordBot#4407]
# Feature request

Add a `version` key to `info.json` which can be returned by commands such as `[p]cog info`.

Add a `changelog` key to `info.json` which can be returned by a new command `[p]cog changelog` - possibly default to `CHANGELOG.md` if no changelog key found.

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [x] API functionality

#### Describe your requested feature

I find it just a little perplexing that you can't verify you're on the latest version of a cog via `[p]cog info` - I know that `[p]cog update` will tell you, but if the cog maintainer announced an update but forgot to actually push to Master (for example), you can't guarantee you're on the right version.

Changelog would be handy so see changes to cogs without leaving Discord, thus helping you decide if you want to update.

**Comment by Dav-Git** [comment]
This does exist in a way by injecting a version number into the cog's help entry but I guess an info.json key would be manageable more easily

**Comment by Jackenmen** [comment]
I would suggest posting in #1683 instead. The changelog idea isn't new, but the concrete ideas you put here could be useful when doing #1683

**Comment by Jackenmen** [comment]
Since you added the comment about this idea in #1683, I'm gonna close this issue.
