### ISSUE TITLE
[Warnings] Remove warnchannel

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#4410]
# Feature request

#### Select the type of feature you are requesting:
Deletion of warnchannel functionality

- [x] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

The warnings cog has a functionality called waarnchannel which allows it to send warnings to a predefined channel. Maybe I'm missing something here but it seems a little pointless to me, considering that a modlog case is already being created and sent to the modlog? If this feature is redundant we could just drop it entirely no?

The functionality of sending the warning to ctx is something worth keeping probably but the warnchannel itself seems redundant.

**Comment by Jackenmen** [comment]
Read the issue description and comments in #2800 for the intended use case.
