### ISSUE TITLE
Allow `[p]ban` to hackban and rename `[p]hackban` to `[p]massban`

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4419]
# Enhancement request

#### Select the target of enhancement you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

`[p]ban` should allow to ban users that aren't in the server (when user mention/user id was used of course as we can't otherwise ban them).
`[p]hackban` should be renamed to `[p]massban` or `[p]multiban`. The command should still allow only user mentions and IDs to avoid ambiguity.

**Comment by Jackenmen** [comment]
To add, `[p]hackban` alias should probably stay for some time.

**Comment by Drapersniper** [comment]
Errrmmm why are we calling it mass ban? Why not just allow the ban command to be greedy and accept multiplier inputs, for the end user the end actions is a ban, if we are merging them we should only send a ban modlog and do so via the ban command no need for a separate command

**Comment by Jackenmen** [comment]
We're making it a separate command because having the argument be greedy is gonna be a confusing behavior when we support passing usernames and nicknames.

**Comment by Drapersniper** [comment]
So we aren't merging ban and hackban anymore ? But instead just renaming hackban to massban ? (Note this is still not clear to users that this allows (and is required) to ban people outside of the server)

**Comment by Zephyrkul** [comment]
Ban will ban/hackban a single person as needed.
Massban will ban/hackban multiple people as needed.

The functionality of both are being merged. The argument parsing is being split between banning one person (`[p]ban`) and banning multiple people (`[p]massban`). This is all explained in the opening post.

> `[p]ban` should **allow to ban users that aren't in the server** (when user mention/user id was used of course as we can't otherwise ban them).
> `[p]hackban` should be renamed to `[p]massban` or `[p]multiban`. The command should still allow only user mentions and IDs to avoid ambiguity.

**Comment by Drapersniper** [comment]
Ah awesome thanks a whole bunch xD I know it's hard to believe but I can read, I was talking about a the general user feedback that ban and hackban should be merged that happened in advance coding, but I appreciate your effort at trying to be useful.

**Comment by Zephyrkul** [comment]
I was merely answering your question:
> So we aren't merging ban and hackban anymore ? But instead just renaming hackban to massban ?
