### ISSUE TITLE
Bot randomly disconnects every minute or so.

### ISSUE THREAD

**Issue by ncodex2** [Cog-Creators/Red-DiscordBot#443]
Here's the log: https://swirlyhost.com/7b8a9a18eaf18d49f4b4.png
After this the bot restarted, this happens several times.
I'm assuming this happens because of audio.
A user is saying this https://swirlyhost.com/7005d5fc73f9945b945f.png

**Comment by ncodex2** [comment]
The uptime command doesn't log this restart which is weird.

**Comment by ncodex2** [comment]
Happened again https://swirlyhost.com/3b728b2680f97c16df1c.png

**Comment by tekulvw** [comment]
Okay...what are you doing that causes this?

**Comment by ncodex2** [comment]
Particularly nothing, when a few servers start playing audio, the bot seems to restart. Some user said that this might be because of a private video in a playlist, i'm not sure though.

**Comment by skeith** [comment]
can you give example of a private video link and a playlist link that includes private video? so I can test this

**Comment by ncodex2** [comment]
Still happening. Bot keeps disconnecting every minute or so.
I'm unable to provide that playlist as the user left and is unwilling to co-operate.

**Comment by ncodex2** [comment]
Basically this is happening now, doesn't seem to have anything to do with audio. https://swirlyhost.com/e161ed213ae348175a9a.png
and it keeps giving those "Riley is now online" messages every minute or so as the bot reconnects.
Stats & uptime don't record this.
@skeith

**Comment by skeith** [comment]
@nikolaaa4 can you post the latest traceback for the audio problem from data/red/red.log to a hastebin link? Please include the timestamp line above the traceback

**Comment by ncodex2** [comment]
I unloaded the audio cog so i don't think it's that @skeith

**Comment by skeith** [comment]
Well then, just post the traceback including timestamp line when the problem occurred

**Comment by ncodex2** [comment]
It seems to be caused by a cog, i'm doing investigation and i will report once i find the cog responsible for this.

**Comment by ncodex2** [comment]
Seems to be a problem with the Redjumpman's heist cog. I opened a github report there.
