### ISSUE TITLE
Add an clean_prefixes arg for get_prefixes

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#4436]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

Actually, using get_prefixes() will return all prefixes without being cleaned.

An argument which would be called `clean_prefixes`, default to False, will clean prefixes before returning the list.

**Comment by Dav-Git** [comment]
Where would you want to use this? The only applicable case I can see would be when showing current prefixes to the user where you can already ``ctx.clean_prefix`` no?

**Comment by madebylydia** [comment]
Prada's MartTools has a command "prefix" where it return all prefixes.
May be also useful for when I ping the bot with no command so it can return an explicative message with every prefixes but cleaned.
