### ISSUE TITLE
Add ability to disable cogs from cogs itself

### ISSUE THREAD

**Issue by fixator10** [Cog-Creators/Red-DiscordBot#4444]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [X] API functionality

#### Describe your requested feature

Add an function to disabled cog from itself.
Aka `[p]command disablecog`, but in code.

Or make `bot._disabled_cog_cache.disable_cog_in_guild` public method

**Comment by Drapersniper** [comment]
🤔  what would the purpose be? like what use cases are there for it.

**Comment by fixator10** [comment]
In my case, that's needed for converting old cog's "disable" feature to red's core
https://github.com/fixator10/Fixator10-Cogs/blob/cc75931b512345815b089f051e1a7f9d63033385/leveler/leveler.py#L95

**Comment by Jackenmen** [comment]
Why not just refer people to the `[p]command disablecog` command?

**Comment by Flame442** [comment]
Due to a lack of activity and the only use case I can see being to convert old disables to this system (which has probably long since stopped being an issue), I am closing this.
