### ISSUE TITLE
ADD music from radio stations support .mp3 urls

### ISSUE THREAD

**Issue by dontknowanything23** [Cog-Creators/Red-DiscordBot#4448]
# Feature request

Please add the support for Radio Live Streams wirth .mp3 or .m3u urls.

Tanks!

#### Select the type of feature you are requesting:

- [x] Cog
- [ ] Command
- [ ] API functionality

**Comment by PredaaA** [comment]
Hello, this is already supported.
You may need to use `[p]audioset restrict` to disable commercial links only though.

**Comment by Jackenmen** [comment]
If you have any further issues, ask on our support server at https://discord.gg/red
