### ISSUE TITLE
 [Request] Publish RSS from a RSS link

### ISSUE THREAD

**Issue by Kcchouette** [Cog-Creators/Red-DiscordBot#447]
Hello

Thank you for your bot. Is there a way to add a command to push the RSS news from a RSS link on discord?

I think adding/deleting the rss link should be for mod/admin and deletion too. But the bot should be able to check every 1 min if RSS is not up to date? And publish the link if a update of the new article?

Thanks in advance!

**Comment by Kowlin** [comment]
Hi there, RSS exists as a 3rd party cog, you can install it by following the command on the [following page](https://twentysix26.github.io/Red-Docs/red_cog_approved_repos/) (Repository Squid-Plugins) after that you can run `cog install squid-plugins rss`. Hope this helps, if this doesn't you can always join the support server.

**Comment by Kcchouette** [comment]
@Kowlin thank you for your help. And how do you restrict `[p]rss add` or others things like that?

**Comment by Kowlin** [comment]
You can use the `permission` cog from the same repository.

**Comment by Kcchouette** [comment]
I'm closing this issue. Thank you for your help!
