### ISSUE TITLE
[Mod] Mention spam accounting for roles

### ISSUE THREAD

**Issue by SharkyTheKing** [Cog-Creators/Red-DiscordBot#4471]
# Feature request

After finalizing https://github.com/Cog-Creators/Red-DiscordBot/pull/4359 (allowing for duplicate mentions). A small discussion was brought up (I forgot with whom), to possibly make something that would / could account for role mentions as well. 

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

This could either be it's own count system (separate from total user mentions. So user mentions could be set to 7, while role mentions could be set to 3), or it would take both user mentions and role mentions into the same context. (each would account for 7 in this example). 

I wanted to make this issue to gather feedback, I am more than willing to work on this myself, though, I want to make 100% sure that this is something worth working on, getting proper feedback on how to set this up and how it should action.

The reason why I believe this should be something for Core Mod is because while it can 100% be used as a third party cog, I figured this would give us and any user who uses core mod better advantages and control over antimentionspam we offer.

**Comment by Bakersbakebread** [comment]
I don't see any reason to not include role mentions in anti-mention-spam filtering, it seems like a perfect addition.

It would be neat if it could be exclusive, as well as inclusive with member mentions - for maximum flexibility.

**Comment by SharkyTheKing** [comment]
Realized how long ago this was, I'll start working on this starting this week.
