### ISSUE TITLE
[Core] Inconsistent Value With Different Responses

### ISSUE THREAD

**Issue by Jacob-1999** [Cog-Creators/Red-DiscordBot#4478]
# Command bugs

#### Command name

`!inviteset public yes`

#### What cog is this command from?

Core

#### What were you expecting to happen?

Enabling the ability for users to invite the bot into their server.

#### What actually happened?

Running the command twice with the same value given will toggle it on/off
![image](https://i.imgur.com/57451YE.png)

#### How can we reproduce this issue?

1. Run the command
2. Run the command again

**Comment by Flame442** [comment]
For reference, this bool param is a **confirm** value, much like `[p]bankset toggleglobal`.
Here is the output when run with no param (or explicit false):
![image](https://user-images.githubusercontent.com/34169552/95633302-60f37d00-0a55-11eb-9042-f1504386af37.png)
