### ISSUE TITLE
Suggestion: Relicense Red from GPL V3 to AGPL.

### ISSUE THREAD

**Issue by Sandvich** [Cog-Creators/Red-DiscordBot#4496]
Hi,

I came across Red today because of a different bot, [Aiura](https://top.gg/bot/438959507389808641), which claims to be a fork of Red. Unfortunately their website is currently under construction, so there is no detailed information there.
The reason I'm opening this PR is because, as far as I can tell, they seem to have no source available. Now, this is *not* a GPL violation... But that's because this project is licensed under the generic GPL and not the Affero GPL ([AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html)).

Is this intentional? Because it seems to me that forking a popular discord bot and then refusing to release the code is a violation of the spirit of the GPL, even if not the license. And running it SaaS-style sidesteps the GPL entirely, but not the AGPL. So maybe this was simply a misunderstanding on the part of the creators of Red?

I think it would be better to switch it to AGPL for future releases, and relicense past releases where buy-in is viable to collect.

**Comment by Drapersniper** [comment]
GPL Is indeed the intended license which the team has decided to go for.
As long a users are respecting the GPL license they are free to do what they wish.

Also worth mentioning it's very unlikely that we will be relicensing Red, now or in the future.

**Comment by Sandvich** [comment]
Okay, fair enough. If no change is needed, that's fair enough. I just wanted to bring it up in case :)

**Comment by Kowlin** [comment]
I'm not gonna close this as of now. This does bring up some interesting situations that weren't thought about when adopting the licence all the way back at the projects creation and at the very least I want to dig into what our team thinks about this.

**Comment by Kowlin** [comment]
At the moment we've decided to not change the licence. However thanks for the suggestion, it lead to some interesting talking points.
