### ISSUE TITLE
[Mod] Toggable nickname/username saving.

### ISSUE THREAD

**Issue by SharkyTheKing** [Cog-Creators/Red-DiscordBot#4514]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [x] API functionality

#### Describe your requested feature
I know this was brought up before the Data API configurations were talked about (data retention and so). There was a PR that was started on regarding this, though it was closed for reasons I forget.

I wanted to bring this back up in an issue to gather feedback on having a command to toggle the bot saving nicknames and usernames in the Mod cog, currently there is no such thing and it's saving people's nickname changes.

I'd also like to purpose a command that lets possibly server owner or just bot-owner permission to wipe the complete list of names / usernames if they use the command.

One thing I'd like to spark up a conversation on is the possibility of having servers opt-in on nickname saves if the bot-owner allows for it. Giving the ability to toggle it on per server and toggle it on as a whole.

If the bot owner disables it, no matter what it's disabled. Though if it's enabled and a owner wants to record that for their server, they can opt into it.

* Sorry for spelling / grammar, it's nearly 3 am and I'm tired.

**Comment by Bakersbakebread** [comment]
Nicknames would most likely fall under, in terms of GDPR, what is considered legitimate interests.

Article 61f says:
> “processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require protection of personal data, in particular where the data subject is a child.”

This can be broken down into a three-part test:
1) **Purpose test**: are you pursuing a legitimate interest?
2) **Necessity test**: is the processing necessary for that purpose?
3) **Balancing test**: do the individual’s interests override the legitimate interest?

One would argue that saving nicknames is necessary for prevention of bad names, offensive names or restrictions per guild rules. 

The best method of using this information legitimately is to do exactly what you mentioned, opt-in. This should be the default for all servers/global and those who wish to use the feature should knowingly enable it.

I'd love to see this feature implemented, I see no negatives.

**Comment by Twentysix26** [comment]
+1
They would be good improvements from a technical standpoint too as username / nickname tracking utilizes a considerable amount of disk space on big bots. And if it's opt in writes would also be reduced a lot.
