### ISSUE TITLE
Installation fails on Python 3.9.x (dependency and documentation clarity issue)

### ISSUE THREAD

**Issue by Nytelife26** [Cog-Creators/Red-DiscordBot#4526]
# Other bugs

#### What were you trying to do?
Install the bot on a version of Python the documentation said should be fine (3.9.x, Windows 64-bit)

#### What were you expecting to happen?
I was expecting the bot to install properly, as the documentation says it should

#### What actually happened?
The installation failed at building the wheel for the package `apsw-wheels` and the process exited. Upon reviewing their site and GitHub, it is apparent the latest version they support is 3.8.x.

#### How can we reproduce this issue?
1. Try installing the bot on a version later than 3.8.x

#### How can we fix this issue?
Clarify the documentation to say that 3.9.x is not yet supported to save users the headache of having to try all this and find out for themselves. No disrespect, just a helpful pointer. Many thanks and good work on the bot, and I acknowledge this isn't entirely your fault, but it should probably be clarified as the documentation says 3.8.1 or later should work which implies 3.9.x should too.

**Comment by Flame442** [comment]
We are aware 3.9 is not supported. From the windows install docs:
![image](https://user-images.githubusercontent.com/34169552/97049176-3cb19900-1549-11eb-8d2d-a1bed1a80225.png)

**Comment by Flame442** [comment]
Actually, that's from the dev docs, the stable docs do not have that part. It will be added to stable when v3.4.1 is released. Sorry for the confusion.

**Comment by Flame442** [comment]
(Already handled by #4480)
