### ISSUE TITLE
"[p]muteset makerole" can error out and fail if ratelimited

### ISSUE THREAD

**Issue by newgreenshoot** [Cog-Creators/Red-DiscordBot#4530]
# Command bugs

#### Command name

`[p]muteset makerole`

#### What cog is this command from?

Mutes

#### What were you expecting to happen?

The command to successfully create a new role with overrides configured for a server's channels and categories

#### What actually happened?

It causes an exception, leaving a partially-configured role and posting an error in chat. The traceback ends with `discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 429 Too Many Requests (error code: 0): You are being rate limited.`

#### How can we reproduce this issue?

1. Start with a server that has no mute role configured, and a considerably large number of channels.
2. Run `[p]muteset makerole [role]`
3. If Discord ratelimits Red while it's applying overrides, the command will error out leaving the role only partially configured.

**Comment by Drapersniper** [comment]
Please provide the full traceback as it can help debugging the issue. Seeing just the last line isn't very helpful .

**Comment by newgreenshoot** [comment]
My bad, does this work?:
```
redbot[50180]: [2020-10-26 04:09:45] [ERROR] red: Exception in command 'muteset makerole'
redbot[50180]: Traceback (most recent call last):
redbot[50180]:   File "/home/redbeta/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
redbot[50180]:     ret = await coro(*args, **kwargs)
redbot[50180]:   File "/home/redbeta/.local/lib/python3.8/site-packages/redbot/cogs/mutes/mutes.py", line 697, in make_mute_role
redbot[50180]:     errors = await asyncio.gather(*tasks)
redbot[50180]:   File "/home/redbeta/.local/lib/python3.8/site-packages/redbot/cogs/mutes/mutes.py", line 729, in _set_mute_role_overwrites
redbot[50180]:     await channel.set_permissions(role, overwrite=overs, reason=_("Mute role setup"))
redbot[50180]:   File "/home/redbeta/.local/lib/python3.8/site-packages/discord/abc.py", line 658, in set_permissions
redbot[50180]:     await http.edit_channel_permissions(self.id, target.id, allow.value, deny.value, perm_type, reason=reason)
redbot[50180]:   File "/home/redbeta/.local/lib/python3.8/site-packages/discord/http.py", line 258, in request
redbot[50180]:     raise HTTPException(r, data)
redbot[50180]: discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being rate limited.
```

**Comment by Drapersniper** [comment]
```py

for channel in ctx.guild.channels:
    tasks.append(self._set_mute_role_overwrites(role, channel))
errors = await asyncio.gather(*tasks)

```
Seems to be the source of the problem, I would assume the command is being run on a server with many channels (@chloecormier  can you confirm how many channels are in the server?)

**Comment by newgreenshoot** [comment]
Right, the server I can reproduce this in has 209 text channels and 19 voice channels... yeah, I know it's excessive.

**Comment by Jackenmen** [comment]
Whatever we decide to do, we should remember to do it for all the usage of `gather` we have in Mutes.

**Comment by kolegge3** [comment]
@chloecormier only bug is that u are alive tf2c paaedo male in wig 
![Uploading ezgif-4-53ffca5be9.gif…]()
