### ISSUE TITLE
massban not banning ids

### ISSUE THREAD

**Issue by phenom4n4n** [Cog-Creators/Red-DiscordBot#4555]
# Command bugs

I found a bug.

#### Command name

massban

#### What cog is this command from?

Mod

#### What were you expecting to happen?

The mass ban to ban all 3 members I pinged.

#### What actually happened?

2 members were banned, but on one I got the following error:
https://cdn.discordapp.com/attachments/133251234164375552/770791292468068362/unknown.png
![image](https://user-images.githubusercontent.com/34169552/97373353-38a8b280-188c-11eb-8df6-d49593b7a88f.png)

#### How can we reproduce this issue?

1. attempt to massban a member by pinging them
2. it doesn't work
From my experience it only happens when trying to massban this id: `651931638409986049`
https://cdn.discordapp.com/attachments/133251234164375552/770792689323081738/unknown.png
![image](https://user-images.githubusercontent.com/34169552/97373361-3e05fd00-188c-11eb-88fc-59339bef0038.png)

**Comment by Jackenmen** [comment]
Thanks for the report! This will be fixed in Red 3.4.2.
