### ISSUE TITLE
`[p]triviaset custom upload` should make the filename lowercase

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4570]
# Command bugs

#### Command name

`[p]triviaset custom upload`

#### What cog is this command from?

Trivia

#### What were you expecting to happen?

I expected the command to add a list in a way that allows me to actually use it.

#### What actually happened?

The command added the list using its original filename casing that includes uppercase letters. `[p]trivia` command turns all the passed categories lowercase, so this makes the added custom trivia list unusable.

#### How can we reproduce this issue?

1. Run `[p]triviaset custom upload` with a file that has uppercase letters in it.
2. Try starting trivia using `[p]trivia` command with the original filename (without extension).
3. See the error message.

---

This can be fixed by automatically making the filename lowercase within the `[p]triviaset custom upload` command.

**Comment by timjwkim** [comment]
Hi! I'm new and want to contribute to this project. Is this an issue I could pick up and work on?

**Comment by Drapersniper** [comment]
Sure thing, any issues with PR welcome label you can pickup without checking with us and we will happily review it when you are done

**Comment by KianBral** [comment]
To clarify:

Should the files "test.yaml", "TEST.yaml", "Test.yaml", and "tESt.yaml" all overwrite the name "test" or should they all be distinct names?

**Comment by Jackenmen** [comment]
You should just ensure that the filename is lowercase when checking if the file already exists and later make sure it saves under that lowercase name if the file doesn't exist or the user agreed to overwrite it.
All that code is already there and it should just be a matter of turning the filename lowercase in the proper place(s).

Edit: that means that the variable with `TEST` string would be turned into `test` and after that, the function would continue with the checks.
