### ISSUE TITLE
Trivia should have some validation checks for the trivia files

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4571]
We should be checking the validity of the trivia list in `[p]trivia` command and `[p]triviaset custom upload` command. I don't know how much checks we need (could use schema verification, although that can result in poor errors sometimes), but our format looks like this (written in a form of a dictionary):
```py
# AUTHOR and CONFIG are special keys that are optional
{
    "AUTHOR": "some string",  # type: str
    "CONFIG": {
        # all keys in here are optional
        "max_score": 123,  # type: int
        "timeout": 123.0,  # type: float
        "delay": 123.0,  # type: float
        "bot_plays": False,  # type: bool
        "reveal_answer": False,  # type: bool
        "payout_multiplier": 123.0,  # type: float
    },
    "question 1 (string)": [
        # list of answers; can be a combination of any of the types below
        "answer 1",  # type: str
        123,  # type: int (gets implicitly converted by Trivia)
        True,  # type: bool (gets implicitly converted by Trivia;
               # this one can be a source of issues,
               # but it probably needs to remain to avoid breakage,
               # at least until next minor version)
        1.69,  # type: float (gets implicitly converted by Trivia;
               # this one can be a source of issues,
               # but it probably needs to remain to avoid breakage,
               # at least until next minor version)
    ],
}
```

As an example, this is one of the errors that can currently occur when starting the trivia with an invalid format, that happens to be valid YAML.
```
Exception in command 'trivia'
Traceback (most recent call last):
  File "/Users/choure/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/choure/redenv/lib/python3.8/site-packages/redbot/cogs/trivia/trivia.py", line 320, in trivia
    trivia_dict.update(dict_)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by leblancg** [comment]
Hi there, I am new to this project and I am interested in taking on this issue. My thinking is that JSON schema validation has a good chance of solving this. What are your concerns?

**Comment by Stonedestroyer** [comment]
> Hi there, I am new to this project and I am interested in taking on this issue. My thinking is that JSON schema validation has a good chance of solving this. What are your concerns?

The issue with json is that yaml was picked cause of user accessibility to be able to create them without any programming experience. Changing to json would make the gap to creating trivia's much harder as we don't have a way to interactively create them.

**Comment by leblancg** [comment]
My bad, I didn't mean changing from YAML to JSON I just meant that after parsing the YAML we could use a JSON schema validator such as this one (https://github.com/Julian/jsonschema) to verify that the YAML follows the desired format.

**Comment by leblancg** [comment]
I've found that some trivia lists (ex. hockey.yaml:1353) has a float listed as one of the answers. Should this be acceptable too?

**Comment by Jackenmen** [comment]
@leblancg It's the same situation as with `bool` type - it should be allowed (at least for now) as disallowing it would be a breaking change since it may break existing trivia lists (such as the hockey one).

I updated the issue, good catch!
