### ISSUE TITLE
[Audio] Repeat fails on local playlists.

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#459]
Repeat fails to repeat the playlist when the playlist is a local one.

**Comment by resathegreat** [comment]
is this already been fixed ? because i can't seems to repeat my local playlist

Edit: Nevermind, i got it, need to start the redstartloop one. Delete my comment if you deemed necessary

**Comment by Kowlin** [comment]
Yes, its been fixed in a older commit roughly a week before this issue was made.
