### ISSUE TITLE
Connection to Lavalink has failed

### ISSUE THREAD

**Issue by dash74** [Cog-Creators/Red-DiscordBot#4605]
# Other bugs

#### What were you trying to do?

Attempting to play music

#### What were you expecting to happen?

I was expecting it to start playing the music I selected

#### What actually happened?

I received and error Connection to Lavalink has failed.

#### How can we reproduce this issue?

Fresh install of Ubuntu 20.04
Standard install of Red-DiscordBot
Loading audio cog
attempting to play music

[latest.log](https://github.com/Cog-Creators/Red-DiscordBot/files/5541204/latest.log)

**Comment by Drapersniper** [comment]
Please go over to our support server so you can get support, the invite is https://discord.gg/red.

We will need further info to debug this. Closing it for the time being as it is likely due to user error or #4601

**Comment by Drapersniper** [comment]
Yup my bad... the log file isn't rendering for me on mobile, duplicated bug to #4601
