### ISSUE TITLE
[Core] Cleanup `[p]set` command

### ISSUE THREAD

**Issue by NeuroAssassin** [Cog-Creators/Red-DiscordBot#4612]
As we all know, the `[p]set` command is a disaster at the moment and needs a cleanup.  Making this issue for my initial plan while also opening feedback so this can get discussed.  Here's a few highlights:

- New group command `[p]set user` combining
  - `[p]set avatar`
  - `[p]set nickname`
  - `[p]set username`
- Make `[p]set activity` combining
  - `[p]set status`
  - `[p]set listening`
  - `[p]set playing`
  - `[p]set streaming`
  - `[p]set watching`
  - `[p]set competing`
- New group command `[p]set roles` combining
  - `[p]set addadminrole`
  - `[p]set addmodrole`
  - `[p]set removeadminrole`
  - `[p]set removemodrole`
- New group command `[p]set i18n` combining
  - `[p]set globallocale`
  - `[p]set globalregionalformat`
  - `[p]set locale`
  - `[p]set regionalformat`
- New group command `[p]set ux` (name needs improvement) combining
  - `[p]set color`
  - `[p]set custominfo`
  - `[p]set description`
  - `[p]set usebotcolor`
- Possible group command (need name) combining:
  - `[p]set fuzzy`
  - `[p]set serverfuzzy`
  - `[p]set prefix`
  - `[p]set serverprefix`

If you'd like to say anything about these, please comment below.

**Comment by Kowlin** [comment]
It may now be a good time to also introduce an change that I had planned prior with guild scoped i18n and that's setting "serverprefix" as "prefix" and "prefix as "globalprefix". Basically let guilds be more important then the global scheme

**Comment by Drapersniper** [comment]
I would argue that although i18n is industry standard, its not user friendly.
Going from that a lot of the command could be renamed once added to a group for example:

New group command `[p]set roles` combining
- `[p]set addadminrole`
- `[p]set addmodrole`
- `[p]set removeadminrole`
- `[p]set removemodrole`

Could become
- `[p]set role addadmin`
- `[p]set role addmod`
- `[p]set role removeadmin`
- `[p]set role removemod`

This could be applied to several of the groups mentioned above.


I would argue that the following would likely be better:
New group command `[p]set bot` combining
- `[p]set bot avatar`
- `[p]set bot nickname`
- `[p]set bot username`
- `[p]set bot color`
- `[p]set bot custominfo`
- `[p]set bot description`
- `[p]set bot usecolor`

**Comment by madebylydia** [comment]
I love this suggestion! However I would rather see `[p]set i18n` as `[p]set locale`, or at least making it an alias. This way sound more human.

**Comment by ltzmax** [comment]
Love the idea, but also, i dont feel like `[p]set serverprefix` and `[p]set prefix` should be group commands, they'd be better off not being it, is what i feel is best with it.
