### ISSUE TITLE
Message about scheduled stream is sent for past schedules that never happened

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4626]
# Other bugs

#### What were you trying to do?

I started the bot after updating to the latest development version.

#### What were you expecting to happen?

Nothing?

#### What actually happened?

I got a message for a stream that was scheduled in the past but never happened:
![image](https://user-images.githubusercontent.com/6032823/99650029-3386ef80-2a55-11eb-8f23-81ee4190d50c.png)

#### How can we reproduce this issue?

1. Add a youtube channel with `[p]streamalert youtube kubakuczys9`
2. Observe.

Currently, `1.` needs to be done *before* updating to the latest development version due to #4625.

**Comment by laggron42** [comment]
Gonna work on a fix myself for that one

**Comment by Jackenmen** [comment]
Fixed by #4631
