### ISSUE TITLE
Cleanup self inconsistent with other commands in the cog

### ISSUE THREAD

**Issue by npc203** [Cog-Creators/Red-DiscordBot#4639]
# Command bugs

An inconsistency with a command (self) on the cleanup cog

#### Command name

[p]cleanup self

#### What cog is this command from?

It is from the cleanup cog.

#### What were you expecting to happen?

I expected the command to delete my message which  invoked the command, like any other command in the cog

#### What actually happened?

It didn't delete the invoked command.

#### How can we reproduce this issue?

Have some bot messages 
cleanup self 1

**Comment by Jackenmen** [comment]
IMO the command message should get removed (if the bot has permissions to do so) as I don't see any reason for this command to differ from the rest of the commands in the Cleanup cog and I can't really think why you would want the command message to stay when you're already purging messages.

As an example, `[p]cleanup user` (which similarly to `[p]cleanup self`, removes messages made by *one specific user*) removes the command message as well.

The implementation shouldn't be too tricky as `[p]cleanup self`'s code is already checking whether the bot has mass purge permission so we only really need to ensure that the command message gets added to the list of purged messages when we have that perm.
