### ISSUE TITLE
No gitlab repo support in downloader.

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#464]
I suggest that the built in downloader cog should allow gitlab repos as normaly if you add a gitlab repo it does `Error in command 'cog list' - ValueError: max() arg is an empty sequence`

**Comment by Jan200101** [comment]
should work if gitlab works with git.
Can you link a example repo ?

**Comment by Kowlin** [comment]
We support Git on every repository, from GitHub to BitBucket and so on. There is a problem with your downloader, I recommend you delete the `data/downloader` folder while the bot is off.

**Comment by calebj** [comment]
There is no reason the downloader won't work with gitlab or any other git host, unless your repo isn't structured correctly. Please post a link to the repo you're having issues with.

**Comment by palmtree5** [comment]
I've tested downloader with both bitbucket and gitlab and both work. @jakesden please link the repo

**Comment by ghost** [comment]
https://gitlab.com/jakesden/Jake-Cogs

**Comment by ghost** [comment]
Thanks for the quick response!

**Comment by palmtree5** [comment]
I get a 404 on that. If it's private, that would be why it doesn't work

**Comment by Jan200101** [comment]
^

**Comment by Kowlin** [comment]
The git repo is a private one. And the bot does not support authorisation, this means that the repo has to be public.

**Comment by ghost** [comment]
made it global still has same error

**Comment by tekulvw** [comment]
what link are you trying to use?

**Comment by ghost** [comment]
posted above

**Comment by ghost** [comment]
does it need to be a link to the .git or not?

**Comment by tekulvw** [comment]
Yes, do you have any files on there?

**Comment by ghost** [comment]
yes did you see? its a mirrored version of https://gitlab.com/jakesden/Jake-Cogs
but m trying to switch to gitlab brb

**Comment by tekulvw** [comment]
You just gave me the same link, there are no files on there and no clone URL, unlike https://gitlab.com/gitlab-com/www-gitlab-com for example

**Comment by palmtree5** [comment]
https://github.com/jakesden/Jake-Cogs vs https://gitlab.com/jakesden/Jake-Cogs

The gitlab repo appears to be empty to me

**Comment by ghost** [comment]
https://gitlab.com/jakesden/Jake-Cogs/tree/master
and the other link i misposted was the one im migrating over to gitlab https://github.com/jakesden/Jake-Cogs/

**Comment by palmtree5** [comment]
that gitlab link you just posted 404s. Can you see the files in that repo?

**Comment by ghost** [comment]
i can and it is global

**Comment by tekulvw** [comment]
Okay well, this is entirely your issue to fix. The bot does not care if the repo is on github or bitbucket or gitlab, you just need a valid, public, clone-able URL. I'm closing this.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/15571690/20222918/0f93398c-a82f-11e6-95de-6c039e2c083f.png)

**Comment by Jan200101** [comment]
cloning on gitlab needs gitlab login details.
I would switch to github as gitlab seems like a mess to manage but its your choice at the end

**Comment by ghost** [comment]
"The project can be cloned without any authentication."

**Comment by Jan200101** [comment]
![image](https://cloud.githubusercontent.com/assets/15076013/20223013/d67f42ea-a837-11e6-92f7-b0f4e6018b41.png)

**Comment by Kowlin** [comment]
And that is clearly not the case, this is a issue with GitLab. To confirm this I'm currently going to setup my own Git server back on again.

**Comment by Jan200101** [comment]
and here the same with your repo
![image](https://cloud.githubusercontent.com/assets/15076013/20223046/fe15ed2c-a837-11e6-818f-f9e49d8ab5be.png)

This denies that gitlab does not want login details so it will not work with the downloader cog

**Comment by palmtree5** [comment]
http://i.imgur.com/M7dzsiT.png
