### ISSUE TITLE
Please add method to use in discord

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#4643]
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [x] Command
- [x] API functionality

**Comment by Drapersniper** [comment]
Ehhh ... It appears you forgot to add some detail to your request.

Is there anything you wish to ask for if not I will be closing this feature request.

**Comment by Drapersniper** [comment]
In the future I ask you that you do the following:

1. User the templates provided.
2. Fill the templates accurately.
3. Provide detail for issues you open.

I will be closing this issue as invalid since there was no actionable information provided and you have no replied to my question.
