### ISSUE TITLE
Please Add Method How to Use in discord

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#4645]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature
Please Add How The bot can be use in discord so it can work

**Comment by aikaterna** [comment]
Every install of Red is going to be different because people can add different plugins to it. If you want to see how your bot can work, use its help command and it will tell you all of the commands it has and a short description of what it does.
