### ISSUE TITLE
[Core] Add Enabling of Globally Disabled Cogs/Commands Per Server Functionality

### ISSUE THREAD

**Issue by Jacob-1999** [Cog-Creators/Red-DiscordBot#4651]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

Have the ability as a bot owner to choose to enable certain commands for a server while keeping them globally disabled.

This functionality would allow bot owners to globally disable cog/commands across all servers said bot is in but at the same time allowing bot owners to enable the same cog/commands for a server or two. An example of this would be `[p]command disable global ping`/`[p]command enable server ping`. This would apply to cogs as well.

**Comment by Flame442** [comment]
You can currently achieve something similar to this with `[p]permissions setdefaultglobalrule`. The only downsides to this approach are that *any* server can choose to re-enable it, not just servers the bot owner chooses, and that re-enabling it takes care, as just blanket `allow`ing will override any checks the cog has.

Despite these downsides, we are not currently interested in expanding the functionality of `[p]command` to add this feature.
