### ISSUE TITLE
Alias ignores newlines in last argument

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#4652]
# Command bugs

#### Command name

alias

#### What cog is this command from?

Alias

#### What were you expecting to happen?

Newlines are respected

#### What actually happened?

Newlines get ignored

#### How can we reproduce this issue?

Create an alias for a command that takes a custom text block, and call it with a new line. The new lines will all be ignored.

For example, one cog we use is this one: https://github.com/TsubakiBotPad/misc-cogs/tree/master/msgutils

We create an alias `^alias add ee editmsg <channelid>` and then call it with 

```
^ee <msgid> some custom text that
spans more than one line
```

We'd expect the bot to edit the custom text to:

```
some custom text that
spans more than one line
```

but instead the message text is edited to:

```
some custom text that spans more than one line
```

This behavior can be reproduced with any command though, just find one that takes a custom text block that can reasonably span multiple lines and create an alias for it, then call the command with the alias as shown.

**Comment by Flame442** [comment]
I believe this is a duplicate of #2704, it might be better to comment on that issue instead of creating a new one.

**Comment by RheingoldRiver** [comment]
Ah thanks, I searched and didn't find anything, I guess because I searched for newline as one word
