### ISSUE TITLE
Arch Linux instructions no longer work as Arch ships with Python 3.9

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4655]
Arch Linux uses bleeding edge technology so its python package already uses Python 3.9 that is currently not compatible with Red.
We could tell people to install the `python38` package from AUR (https://aur.archlinux.org/packages/python38) however, I don't think it's our job to tell Arch users *how* they can do it since Arch is meant to be a system for knowledgeable users and aside from the manual, recommended way, there are also plenty of tools that make it a bit easier for the user but are not endorsed by Arch Linux.

**Comment by palmtree5** [comment]
Arch users should still be able to use pyenv I would think

**Comment by Jackenmen** [comment]
Indeed, they should be able to use it. I was going off Arch's wiki on what they suggest to do to get older Python versions, but telling people to use pyenv is also an option and it does simplify the documentation maintenance.

I like it 😄

**Comment by TheWyn** [comment]
I commented this to Draper yesterday, fixed by forking red and removing the 3.9 check..other then deprecated warnings haven't found any bugs.
