### ISSUE TITLE
Help categories

### ISSUE THREAD

**Issue by npc203** [Cog-Creators/Red-DiscordBot#4665]
# Feature request

As an end user with lots of 3rd party cogs, the help section pagifies to 17 pages for me. Its a mess for ppl to get commands as of now. And hence I suggest to opt for cog categories. 

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

One such way of doing it is
Bot owners can add an optional category using set or something
common categories are grouped together and will be displayed as
[p]help [category name]
ungrouped categories will be bunched into its own category

So that it is less cluttered and free to navigate as well as get commands
This could as well as be a togglable optional feature

I'm not really sure of the implementation nor think that the way I mentioned above is a good idea either,
But even looking at big red bots as in martine, mewtwo,pikachu have them and it kinda helps to get commands faster.

What's yall take on this?

**Comment by Dav-Git** [comment]
I'm not sure I 100% what you are suggesting but there is already a way to get commands by cog by running ``[p]help <CogName>`` or to have it navigatable with reactions via the ``[p]helpset usemenus`` setting.

Are you suggesting further categorization or is that what you wanted?

**Comment by bobloy** [comment]
Here's a concept for how to do this.

- Add `helpset category` base command 
    - `add <category name>` 
    - `delete <category name>`
    - `addto <category> <Cog_or_command>`
    - `remove <category> <Cog_or_command>`
    - `rename <category> <category name>`

- Add `help categories` to get these categories
- Add `helpset togglecategories` to toggle categories for raw `help`, defaulted to off.

`help categories` would then first get all the commands a user has access to like normal in the given context (`walk_commands` I believe). Then it would reformat using the categories as the top level data grouping, with unconfigured Cogs/commands going to a default category like `Uncategorized`.

Looking something like:

- `<Category Name1>`
    - `<Cog Name1>`
        - `<command1>`
        - `<command2>`
    - `<Cog Name2>`
        - `<command3>`
- `<Category Name2>`
    - `<Cog Name1>`
        - `<command4>`
    - `<Cog Name 3>`
        - `<command5>`


Problem:
The difficult part with this I imagine would be how to store the Cog/command info. My best guess would be restricting this to only work on cogs that have registered `configs` and using that provided `id` along with the Cog/Class + command names. Alternatively, it could be very relaxed and work only on Cog/command name strings, which has the difficulty of same-name cogs/commands and if they're swapped. A third option would be some new method of identifying cogs that creators would have to opt-in for.

Honestly though, I believe I don't know enough to even attempt this myself. I'd consider this a fairly difficult feature request unless someone could share a reasonable way to solve the above problem.

**Comment by Drapersniper** [comment]
I don't feel like it the time/complexity/benefit ratio of this feature request makes sense.

Currently people are able to create help formatters, and this would work perfectly with a custom formatter, as such I don't think it's worthwhile to be added to core.

That said I'm not shutting it down just speaking my mind and if folks feels the time/effort spend on this  and complexity added by it will be worth for the minority of the user base that will end up using this won't stop them.

**Comment by ltzmax** [comment]
It helps to create your own help formatter if you needed to get the commands faster or want it less messed up for yourself.. You do have coding channel in the discord to ask if you needed help with something you're unsure about while making your help formatter on how you wanted it.

`[p]help <category/Cogname>` also already exist. It says below your help menu already as well.

**Comment by npc203** [comment]
Closing this for now. Based on the discussions, it would rather be easier to code for the bots using the help formatter api.
