### ISSUE TITLE
Names with Backslash Shows Incorrect Output

### ISSUE THREAD

**Issue by Menteroth** [Cog-Creators/Red-DiscordBot#4666]
# Command bugs

#### Command name

`bank balance`

#### What cog is this command from?

Economy

#### What were you expecting to happen?

Show their name as is.

#### What actually happened?

Skips the `\`.

#### How can we reproduce this issue?

Use this name and use command.  `CR1|\/|S0|\| D3\/1|_`

![image](https://user-images.githubusercontent.com/24851042/101889121-53ff2100-3b9f-11eb-8e11-7ea384adefd4.png)

**Comment by Drapersniper** [comment]
That's just how discord renders singular backslashes.  I'm not sure if it's worth escaping this ( it will need to be done basically everywhere) just to show the backlash

**Comment by Menteroth** [comment]
Ah okay. Yeah, no biggie really. Thanks.

**Comment by Kowlin** [comment]
This is infact Discord being Discord.
