### ISSUE TITLE
Include the ability to log filter hits

### ISSUE THREAD

**Issue by Danstr5544** [Cog-Creators/Red-DiscordBot#4676]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

We have a `filterban` casetype, so **within a similar vein** I was wondering if we could get a `filterhit` command - it would allow us to **mark a channel to act as a log** for when someone uses a blacklisted phrase - loosely related, also record it as a modlog case?

**Comment by SharkyTheKing** [comment]
100% for this. I built a 3rd party cog for personal use to do this because I liked seeing who's repeatedly getting filtered out or a way to make sure the filter is working properly and not catching false positives.

Would love to see this done for core filter.

**Comment by Jackenmen** [comment]
+1
While it is easy to make a cog listening for the filter's message delete event, I don't see a reason why it shouldn't just be a part of Filter.

**Comment by ltzmax** [comment]
+1
i would 100% love this.
