### ISSUE TITLE
[Mod] add so it shows you're on mobile in userinfo

### ISSUE THREAD

**Issue by ltzmax** [Cog-Creators/Red-DiscordBot#4696]
# Feature request

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

currently userinfo does not show that an user is on mobile but shows as "online" instead. 

i did try to make it myself as well but it does not look any good for me when formatting wasn't easy enough to make it look good.
https://i.imgur.com/VNlQEMF.png

**Comment by Flame442** [comment]
Users have 3 different "onlines", one on desktop (the client), one on web (the website, and also the api for bots), and one on mobile (the app). These three statuses can have different states, so you could be "away" on desktop but "online" on mobile. Right now, `userinfo` shows the "top" status (ie the one you see when you look at the user through the client).

I don't have a strong opinion on adding a mobile indicator of some kind, however I don't think it is a good idea to replace the icon entirely with a phone emoji as that is somewhat ambiguous.

~~To see more information on the different types of statuses, check out my cog `onlinestats`~~

**Comment by ltzmax** [comment]
> Users have 3 different "onlines", one on desktop (the client), one on web (the website, and also the api for bots), and one on mobile (the app). These three statuses can have different states, so you could be "away" on desktop but "online" on mobile. Right now, `userinfo` shows the "top" status (ie the one you see when you look at the user through the client).
> 
> I don't have a strong opinion on adding a mobile indicator of some kind, however I don't think it is a good idea to replace the icon entirely with a phone emoji as that is somewhat ambiguous.
> 
> ~~To see more information on the different types of statuses, check out my cog `onlinestats`~~

Well the mobile emoji doesn't look good anyway without making it look good.. that's why I made this issue so we maybe could get something like that in core without using an 3d party cog. But it's understandable if it's not possible to have.

**Comment by ltzmax** [comment]
And about your cog, I'll take a look at it and see more what you mean.
