### ISSUE TITLE
My pm2 is not working 

### ISSUE THREAD

**Issue by SDS1234** [Cog-Creators/Red-DiscordBot#4708]
Hello,
I followed your instructions and decided to use the pm2 method. It does not work for me to use this. This is my start command: pm2 start redbot --name "Redbot UFO" --interpreter "/root/.pyenv/shims/python" --interpreter-args "-O" -- UFO --no-prompt

I hope you can help me 

with kind regards 
SDS

**Comment by aikaterna** [comment]
Keep your issue in support where it belongs.

**Comment by SDS1234** [comment]
My question has not been answered

**Comment by palmtree5** [comment]
Support questions belong in the support channel in [our Discord server](https://discord.gg/red)
