### ISSUE TITLE
Improve help of `[p]tempban` (possibly add example usage?)

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4712]
# Command bugs

It is not obvious how `[p]tempban` should be used due to how argument parsing is configured for `duration` and `days` arguments with avoiding one eating the other in mind.
I think adding an explanation for the argument format and some examples of usage could really help with this.

#### Command name

`[p]tempban`

#### What cog is this command from?

Mod

**Comment by ltzmax** [comment]
Would you also be down to improve all ban commands and kick command with examples of how to use?

I wanna look into doing this one, but also wanna wait incase someone else wanna try to do their first pr.

**Comment by Jackenmen** [comment]
> Would you also be down to improve all ban commands and kick command with examples of how to use?

Sure! Having examples in more commands seems like a nice improvement.

> I wanna look into doing this one, but also wanna wait incase someone else wanna try to do their first pr.

If you want to do it, don't worry about that, there's always something else new contributors can take on, we have a looot of documentation that isn't all that good anyway :)

**Comment by ltzmax** [comment]
> If you want to do it, don't worry about that, there's always something else new contributors can take on, we have a looot of documentation that isn't all that good anyway :)

Okay, sounds good. I'll do it tonight. :)
