### ISSUE TITLE
Copy info about the bands from help of `[p]eq set` to help of `[p]eq`?

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4716]
I think that would make it a bit more obvious, especially when you consider that the ℹ️ emoji shows you the help of `[p]eq`, not the help of `[p]eq set`.
Alternatively, we could have `[p]eq explain` or something, but it's probably not worth adding another command in the group.

What do you think?

**Comment by Drapersniper** [comment]
Sounds good to me until EQ is rewritten. Anyone is free to open a PR for the copy pasta, no need to add a new command

**Comment by ltzmax** [comment]
i'll like to be assigned to this pr, i'll do this one.
