### ISSUE TITLE
Add white/blacklist check to canrun command

### ISSUE THREAD

**Issue by privacywhen** [Cog-Creators/Red-DiscordBot#4717]
# Feature request

#### Select the type of feature you are requesting:

- [X] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature
Change "canrun" functionality to check allow/ignorelists before reporting result. Perhaps include what specific setting prevents their use of the command.

Example Command: [p]permissions canrun  BobTheBuilder warn
Example Result: "That user has the permissions to run the command, however, is prevented by localblocklist."

When trying to debug issues around the a users ability to run a command with "canrun", it only reports if the users has the permissions. This led to an situation where the user had the correct permissions so "canrun" reported as "allowed", however, this did not account for them being excluded by the allowlist/ignorelist. This resulted in the user not being able to run the command, despite "canrun" claiming they could.

**Comment by flaree** [comment]
I think if this was added then it should be seperate from permissions as it would now includes stuff from outside of it

**Comment by Jackenmen** [comment]
This will be possible as part of `[p]diagnoseissues` command which is meant to help diagnose what command checks are making the command fail to run. I'm currently working on this.

**Comment by Jackenmen** [comment]
Fixed by #5243
