### ISSUE TITLE
[Audio] Make autodisconnect on empty channel optional

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#473]
(mostly making this as a note for myself)

There are users that normally just let the bot continuously play music so they can jump in and out of the voice channels as they please and never need to restart a playlist.

**Comment by palmtree5** [comment]
Gonna throw my two cents in here: why not just make the time configurable, probably having 0 be the value that means the bot won't leave the voice channel?

**Comment by jonyroda97** [comment]
the command <code>[p]pause</code> can't even be used... the bot gets of the channel and if you are playing a playlist you have to play it again from the start...

**Comment by tekulvw** [comment]
Fix with #479 

@palmtree5 that's something we can revisit in another PR

@jonyroda97 you're saying that right now if you use `pause` the bot will automatically disconnect?

**Comment by tekulvw** [comment]
@jonyroda97 Yeah that bug snuck in there, will be fixed with that PR

**Comment by Twentysix26** [comment]
Added in #497
