### ISSUE TITLE
[Cleanup] let cleanup show in channel how many messages it deleted for a short while

### ISSUE THREAD

**Issue by owocado** [Cog-Creators/Red-DiscordBot#4732]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [ ] API functionality
- [x] Cog UX improvement

#### Describe your requested feature

EDIT: I'm suggesting this feature as a toggle. 

Currently, messages deleted through cleanup commands gets deleted silently and how many messages it deleted gets logged to console/bot logs. However, in many instances it would be useful if bot displayed how many messages it actually deleted in said channel for a short while (5 seconds or less) before auto-vanishing, so as to inform the person who executed said cleanup command. Below GIF can demonstrate what I'm trying to say:

![unn2zSDxKu](https://user-images.githubusercontent.com/24418520/104428927-0cf3b980-55ab-11eb-957f-faa217436a08.gif)

This could be helpful in many instances, where, people who are managing a discord server as trial mod or helpers with just manage messages perms and don't have access to neither audit logs nor bot's console logs , OR to mods and admins who don't have to keep checking audit logs after using cleanup commands to see how many messages bot actually deleted in said channel, etc etc. It saves time, even by little amount and also makes the cleanup process transparent for them by showing deleted messages count. I also personally believe it improves user experience too in context of using cleanup cog. Just my 26 cents.

**Comment by npc203** [comment]
+1 from me.
This has already been brought up here https://canary.discord.com/channels/133049272517001216/133049878837329920/775417296277602324, but was rejected outrightly.

Would like this to be implemented as a toggle-able feature

**Comment by Jackenmen** [comment]
Hmm, having it show for *few* seconds IMO wouldn't be a bad idea, I'm guessing some would still like it to be togglable though.
+0.5 from me, I want more people to share their thoughts on this

**Comment by Kreusada** [comment]
Yeah also +0.5 from me. It's not a feature I'd be desperate for, but if there could be a toggle for this then I'm down for it.

**Comment by owocado** [comment]
Yeah I meant to suggest this as a toggle. Somehow I missed that part to include in OP.

**Comment by ltzmax** [comment]
+1 from me for this. A toggle settings for it wouldn't be bad to let it show for some seconds.

**Comment by Dav-Git** [comment]
+1 having feedback on what just happened is always good. If it annoys someone, they can just turn it off.

**Comment by madebylydia** [comment]
+0.4...
I am doubtful on using a togglable settings for such a tiny thing, to me, it should be either, we show how many messages were deleted and then self-destruct the message, or simply stay shut, the Org should decide of what decision to do. But otherwise, I'm good with the suggestion.
A parameter could be used in the commands, probably to True by default, I don't see any problem in making it the default option.
