### ISSUE TITLE
Add so you can ignore multiple channels

### ISSUE THREAD

**Issue by ltzmax** [Cog-Creators/Red-DiscordBot#4736]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Right now as you see, you cannot ignore multiple channels at once, but you can with `[p]ignore server`, i dont really want to ignore a full server but spefic channels, and it takes so much if you wanna ignore example 30 channels and have 5 or 10 channels unignored.

![FPtUglt](https://user-images.githubusercontent.com/63972751/104840261-57847700-58c6-11eb-877d-d4636faec43f.png)

**Comment by TrustyJAID** [comment]
Just wanted to add to this you can currently ignore channel categories to ignore all channels within that category which may help with your problem.

**Comment by ltzmax** [comment]
> Just wanted to add to this you can currently ignore channel categories to ignore all channels within that category which may help with your problem.

Ah didn't know you could do that. Thanks.
