### ISSUE TITLE
A Feature For global Equalizer presets.

### ISSUE THREAD

**Issue by SnooPee508** [Cog-Creators/Red-DiscordBot#4737]
# Feature request

#### Select the type of feature you are requesting:

- [x] Command

### Hello! I have an awesome Idea! Is it possible in equalizer that bot owners can create global equalizer presets? So that adding filters like Bassboost, treble etc. If it is possible then we don't need to add separate filters command. This can come in handy :)

**Comment by Drapersniper** [comment]
Comment on #2940
