### ISSUE TITLE
Immortal Souls

### ISSUE THREAD

**Issue by Lexl6799** [Cog-Creators/Red-DiscordBot#4751]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [ x] API functionality

**Comment by ghost** [comment]
Someone label this good first issue please

**Comment by Flame442** [comment]
> Immortal Souls is a melodic death metal band from Kokkola, Finland, formed in 1991. They released a split album and their debut on Little Rose Productions in the late 1990s and early 2000s. In 2002 Immortal Souls signed with Dutch label Fear Dark which released their second and third album as well as a compilation.

I'm not quite sure what this has to do with red or its API functionality, so I am going to close this issue. Feel free to make another one with more detail if you have an actual feature request, or join [our discord](https://discord.gg/red) if you just want to chat.

**Comment by ghost** [comment]
Aww, you ruined it!
