### ISSUE TITLE
[Downloader] Some commands don't follow embed format

### ISSUE THREAD

**Issue by Jacob-1999** [Cog-Creators/Red-DiscordBot#4764]
# Command Bugs

#### Command names

`[p]cog info <repo> <cog>` & `[p]repo info <repo>`

#### What cog are these commands from?
Downloader

#### What were you expecting to happen?

Command outputs should follow same embed format as the rest.

#### What actually happens?

They use code blocks instead of the embed like the rest of the commands do.

#### How can we reproduce this issue?

1. Enable Guild or Channel embed via `[p]embedset`
2. Run the commands

**Comment by Jackenmen** [comment]
Personally, I'm not too sold on putting the output of these commands in an embed, though I guess it would be a bit more consistent with the `[p]findcog` or `[p]cog listpinned` commands. I would appreciate feedback from more people here before proceeding.
