### ISSUE TITLE
Aliases for some commands which have optional arguments fail to operate normally

### ISSUE THREAD

**Issue by Kreusada** [Cog-Creators/Red-DiscordBot#4766]
#### Command name

Aliases for _some_ commands which require optional arguments.

#### What cog is this command from?

Alias, but also the cog from which the command of the alias is from. Currently, it seems to be the case especially with `Downloader`.

#### What were you expecting to happen?

For the aliases for `pipinstall` and `load` to return the help menu, as no arguments were given.

#### What actually happened?

For `load`, the redbot would start typing but there would be no result.
For `pipinstall`, the redbot would start typing and then send "Libraries installed", although no arguments were given.

These are two examples I've discovered, but there may be more.

#### How can we reproduce this issue?

Create an alias for `pipinstall`, and/or `load`.
Use these aliases without any arguments.

**Comment by Kreusada** [comment]
++ Aliases for reload, and unload have the same behavior as above, too

**Comment by Flame442** [comment]
https://github.com/Cog-Creators/Red-DiscordBot/blob/aad34f2b08df8954d669c9b12caa09c936181918/redbot/cogs/alias/alias.py#L186-L188

When there are no args, there is a trailing space after the command. This causes commands like `load` which take an arbitrary (but non-zero) number of values to glitch out. Running `.strip()` on the mocked message should fix this issue.
