### ISSUE TITLE
[bug] im getting a error from mod log when i run the bot.

### ISSUE THREAD

**Issue by kpopdev** [Cog-Creators/Red-DiscordBot#4773]
# Other bugs

when i run the bot i get this error 
[14:25:52] WARNING  Fix this using the hidden command: `modlogset fixcasetypes` in Discord: Got       [red.core.modlog]
                    outdated key in casetype: audit_type

#### What were you trying to do?

everytime i run the bot i get this error 
[14:25:52] WARNING  Fix this using the hidden command: `modlogset fixcasetypes` in Discord: Got       [red.core.modlog]
                    outdated key in casetype: audit_type

#### What were you expecting to happen?

i dont want this error show when i run my bot also i think it slow down the bot too from running.

#### What actually happened?

[14:25:52] WARNING  Fix this using the hidden command: `modlogset fixcasetypes` in Discord: Got       [red.core.modlog]
                    outdated key in casetype: audit_type

#### How can we reproduce this issue?
"%userprofile%\redenv\Scripts\activate.bat"
redbot <your instance name>

**Comment by Jackenmen** [comment]
@mina9999 Have you tried running the command that was given to you in the warning?

**Comment by kpopdev** [comment]
> 
> 
> @mina9999 Have you tried running the command that was given to you in the warning?

no bc i dont even use the mod logs.

**Comment by Jackenmen** [comment]
Well, the warning already explains what you need to do to fix it. Since you're saying you don't use mod logs, you will additionally need to load the modlog cog first. Running these commands should fix this issue:
```
[p]load modlog
[p]modlogset fixcasetypes
[p]unload modlog
```

Note: Replace `[p]` with your bot's prefix.

**Comment by kpopdev** [comment]
> 
> 
> Well, the warning already explains what you need to do to fix it. Since you're saying you don't use mod logs, you will additionally need to load the modlog cog first. Running these commands should fix this issue:
> 
> ```
> [p]load modlog
> [p]modlogset fixcasetypes
> [p]unload modlog
> ```
> 
> Note: Replace `[p]` with your bot's prefix.

tysm for the help
