### ISSUE TITLE
[ModLog] Add a setting to add onto cases with [p]reason

### ISSUE THREAD

**Issue by Jacob-1999** [Cog-Creators/Red-DiscordBot#4776]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [ ] Command
- [x] API functionality

#### Describe your requested feature

A toggle-able setting to switch between changing the original reason of a case and adding onto a case, like additional notes. If someone has a long reason, it could make it easier instead of typing or copying the long reason, especially if you're on mobile and need to add additional details.

**Comment by Dav-Git** [comment]
Maybe not as a toggle-setting, but as a seperate command `[p]addnote` I see this being pretty useful for more complex modlog cases.

**Comment by Jacob-1999** [comment]
Toggle would be better because you're either overriding the existing reason or you're adding onto an existing case. I believe it's simple enough to have just that.

I've expressed this plenty of times in my time being in Red; I'm no code expert. It's quite possible that _code wise_, it's easier to do a command rather than a toggle for an API functionality.

**Comment by Dav-Git** [comment]
Oh, I think I misunderstood you here. I thought you were talking about a setting that would change the default behaviour of `[p]reason`but you meant something like `[p]reason add [whatever]`.

**Comment by Jacob-1999** [comment]
When I originally wrote this suggestion, I had in mind a toggleable setting to switch functionalities but looking into it now, it seems more simple to go with `[p]addnote <case> <text>` to add onto. 

Now that I think about it while typing this up, going with the `[p]addnote` command, something would need to be thought up on `[p]reason <case>` command. Maybe additionally to `[p]addnote <case>` you can have a `[p]editnote <case> text` so you can edit your owned note. 

The more I think about this, the more complex it's becoming.

**Comment by Flame442** [comment]
Perhaps something akin to `[p]appendreason` would be better, which modifies the reason in place by *appending* the text instead of *replacing* the text, while also not being an entirely separate "note" that needs special handling. Then, `[p]reason` could be used to override the entire block as normal.

**Comment by Dav-Git** [comment]
I agree with flame here. However the maximum field length of an embed could be problematic when embeds are requested for modlog messages.

At the same time limiting the entire reason to the embed field max length doesn't really leave a lot of room for expansion at times.

The usefulness of the command would therefore be rather limited to appending very small quantities of text.

**Comment by Jacob-1999** [comment]
I agree with Flame as well. Also, Discord increased the character limit for embeds a while ago when they increased the character limit for Nitro users. I believe with the current limit mentioned in this document is sufficient for appending. For each new appending message to a case, it can be a new field. https://discord.com/developers/docs/resources/channel#embed-limits

**Comment by Jacob-1999** [comment]
I'll be closing this issue in light of [JoJo's advancedlog cog](https://github.com/Just-Jojo/JojoCogs/blob/master/advancedlog/info.json) that has similar features as I've described initially and in the past.
