### ISSUE TITLE
[bug] when you run redbot on so many shards the python.exe wont split or Multithreaded dosnt work.

### ISSUE THREAD

**Issue by kpopdev** [Cog-Creators/Red-DiscordBot#4787]
**What Red version are you using?**

3.4.6.dev1

**What were you trying to do?**

i just run my bot from "%userprofile%\redenv\Scripts\activate.bat" and checked the active process.

**What did you expect to happen?**

if the shards are 4 it should be 4 active python.exe on running process so it made the bot faster.

**What actually happened?**

my bot is in 4500 servers and when i run my bot and check running process only 1 python.exe is running. with 30% of using my cpu. https://cdn.discordapp.com/attachments/657638377042214980/806802362299318282/unknown.png 

**How can we reproduce this error?**

1. the bot should be in more than 3k servers.
2. then run the bot. and check the running process.
3. as you can see only 1 python.exe is using %30 of cpu https://cdn.discordapp.com/attachments/657638377042214980/806802362299318282/unknown.png

**Comment by Drapersniper** [comment]
That's not how the sharding works. Red is not a multi-process program.

**Comment by PredaaA** [comment]
This is all working as intended. First, (in your case which is Red bot, using discord.py) a shard is a separate connection to Discord, on your bot process, and not an separate process.
Red makes use of [discord.py AutoShardedClient](https://discordpy.readthedocs.io/en/latest/api.html#discord.AutoShardedClient), which after ~2k guilds will start sharding the bot automatically (number of shards are depending of what Discord's gateway returns, [see that link](https://discord.com/developers/docs/topics/gateway#get-gateway-bot)).

Now that said, yes a discord.py bot like any bot can run in multiple processes, with x shards per process. But that's out of the scope of Red's support.

**Comment by Kowlin** [comment]
Im afraid that Preda's comment above me is correct. There are ways to handle that sort of stuff by having a shard instance manager, it's own program to handle additional bot instances. However, none have been written for Red and that sadly is a extremely low priority for me due the lack of overall use it would receive.
