### ISSUE TITLE
`SetParser` converter (`[p]bank set` command) should have meaningful error message

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4789]
**What component of Red (cog, command, API) would you like to see improvements on?**

`[p]bank set` command

**Describe the enhancement you're suggesting.**

Currently using invalid input with `[p]bank set` gives an error that doesn't tell you what's wrong:
![image](https://user-images.githubusercontent.com/6032823/107106044-e7647380-6829-11eb-8590-41a8f665e7dc.png)

We should add some meaningful error messages to the converter used there.

**Comment by rijusougata13** [comment]
can you assign me ? i want to work on this.

**Comment by Jackenmen** [comment]
@rijusougata13 done. If you need any more guidance on this, feel free to ask in here or on [our discord server](https://discord.gg/red).

And just in case you change your mind about working on this, just let us know and someone will unassign you.

**Comment by rijusougata13** [comment]
yeah sure if change my mind i will let you know..

**Comment by rijusougata13** [comment]
@jack1142  hey i was trying to make changes in some files .But it seems it has no effect on that bot..can you guide me how to update the bot after i make any changes..

**Comment by NeuroAssassin** [comment]
I would recommend taking a look at our CONTRIBUTING.md for steps on how to set up the bot in a developer environment (https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/CONTRIBUTING.md).  If you have any other questions, feel free to join the discord server Jack linked above, which will allow us to help you a bit more easily in a back-and-forth context.

**Comment by rijusougata13** [comment]
![Screenshot from 2021-02-10 19-25-19](https://user-images.githubusercontent.com/52108435/107519352-30c01480-6bd6-11eb-8446-c100f99b6da4.png)

it will give a meaningfull error message to user if argument is not valid. @NeuroAssassin  @jack1142 please take a look if it is correct or not .
