### ISSUE TITLE
[bug] the mod cog/core made bot super slow with making large setting files.

### ISSUE THREAD

**Issue by kpopdev** [Cog-Creators/Red-DiscordBot#4798]
**What Red version are you using?**

3.4.5

**What were you trying to do?**

my bot were super slow my bot is in 4k servers and i unloaded the mod cog like [p]unload mod. then my bot is fast again. i checked whats going on with Process Monitor software and i saw the redbot in mod settings is making so many large files.( i think its bc it check the users changing their name and it save it to the settings or idk for real.)

**What did you expect to happen?**

it shouldnt bug the bot or slow down the bot like this. it use so much cpu too.

**What actually happened?**

please look at screenshot that i send
bot keep writing large files in settings = https://cdn.discordapp.com/attachments/760365719660527627/808880223063375882/unknown.png 
and here  : https://cdn.discordapp.com/attachments/760365719660527627/808880819481215016/unknown.png 

**How can we reproduce this error?**

1. load the mod cog/core
2. it keep making large files.

**Comment by Flame442** [comment]
There is an open issue suggesting a setting to disable name/nickname tracking, #4514. If you would like a setting such as that one, I recommend you add a comment to that issue.
