### ISSUE TITLE
Bot starts playing random tracks after my local music files stop playing

### ISSUE THREAD

**Issue by kristiyanTopchiyski** [Cog-Creators/Red-DiscordBot#4802]
Hello, I want to ask how can I disable the search and the playing of youtube/spotify and other external music on the bot, I want to show only local files and the bot to be able to find only local files, because it randomly starts playing different songs after my queue ends

**Comment by Drapersniper** [comment]
GitHub issues are for issues, if you have a question please use our discord support server.

https://discord.gg/red
