### ISSUE TITLE
Cog update returns error when an update has occurred

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#481]
Using the current downloader, the bot outputs this message after a repo has been updated:

Downloading updated cogs, please wait... done. 
Updated cogs: aikaterna/test.(edited)
Error in command 'cog update' - AttributeError: 'NoneType' object has no attribute 'count'

```
[19/11/2016 17:24] ERROR red on_command_error 233: Exception in command 'cog update'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\d
iscord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\downloader.py", line 261, in update
    for page in pagify(note, delims=['\n'], shorten_by=shorten_by):
  File "C:\Red-DiscordBot\cogs\utils\chat_formatting.py", line 39, in pagify
    num_mentions = text.count("@here") + text.count("@everyone")
AttributeError: 'NoneType' object has no attribute 'count'
```

**Comment by Jan200101** [comment]
version of red and discordpy ?

**Comment by aikaterna** [comment]
3 hours ago
5acf2f - [Owner] Pagify [p]cogs (#482)

Discord.py 0.14.3, latest update with Embed

**Comment by Kowlin** [comment]
I've been looking into this, but cannot find the cause yet. What you can do is go clean with your downloader by deleting ``data/downloader``. This will resolve the issue, but will result in the lose of the downloader data like repositories.

**Comment by tekulvw** [comment]
It's this method: https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/downloader.py#L524

When `bool(log)` is `False` `format_patch` will return `None` instead of a string, which is expected. Someone just needs to add an `else: return ""` to the end of that if statement.

**Comment by tekulvw** [comment]
Or perhaps add an `if note is None: continue` statement right before this loop: https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/downloader.py#L261
