### ISSUE TITLE
Audio cog should have option to play from any URL

### ISSUE THREAD

**Issue by anderson2927** [Cog-Creators/Red-DiscordBot#4812]
**What component of Red (cog, command, API) would you like to see improvements on?**

Audio cog

**Describe the enhancement you're suggesting.**

Currently, the audio cog can only play from a whitelist of domains and URLs. It should at least be an enable/disable option to allow us to [p]play from ANY URL. We could also allow functionality to expand the whitelist. Again, if this is too complex, then simply allow us to disable the URL whitelist, because in RedBot V2 this was a standard feature that has been abruptly removed for specific use cases that do not apply to every Discord server. Thank you!

**Comment by Jackenmen** [comment]
@GlenAnderson if I understand what you're asking correctly, that is already possible with `[p]audioset restrict` command (`[p]` is your prefix).

**Comment by anderson2927** [comment]
> @GlenAnderson if I understand what you're asking correctly, that is already possible with `[p]audioset restrict` command (`[p]` is your prefix).

Thank you, so sorry.
