### ISSUE TITLE
[Mod] A Noting system for Mods

### ISSUE THREAD

**Issue by Jacob-1999** [Cog-Creators/Red-DiscordBot#4842]
**Type of feature request**

Command

**Description of the feature you're suggesting**

The functionality of this command would be designed to allow server moderators to attach notes to users such that it'll create a NOTE case that is sent to the modlog channel along with being able to view the case with `[p]casesfor` or maybe with a subcommand. The note would not be sent to the user via DM and is designed to only be for moderator purpose. 

`[p]note add <user> <reason>` → Adds a note to the specified user.

`[p]note list <user>` → Gets a list of the notes made for the specific user.

`[p]note del <case_id>` → This subcommand would essentially remove the note case from modlog as well from `[p]casesfor` OR from the subcommand `[p]note list`. 

`[p]note edit <case_id> <reason>` → Same functionality as `[p]reason <case_id> <reason>`.

**Comment by RheingoldRiver** [comment]
We have a (third-party, unafilliated) cog that supports this that you could install and/or fork called `baduser` - <https://github.com/TsubakiBotPad/misc-cogs/blob/master/baduser/baduser.py>

It's pretty inhouse but it supports adding both strikes & notes. Strikes come with the extra effect that you'll get pings when striked users do things like leave/rejoin the server. Notes are just neutral. You can print strikes & notes independently.

You can also configure positive, neutral, and negative roles, which will ping you in the configured channel when they get added to a user, this way you can track that no one accidentally adds influential roles to someone via misclick or whatever. (This requires intents.)

Again if you install without forking keep in mind this is both third-party & inhouse for our server, and we make changes to it as we need so if that sounds undesirable, just fork and pull from upstream occasionally only if you want to.

**Comment by Dav-Git** [comment]
Bobloy also has `flags` in his approved repo https://github.com/bobloy/Fox-V3

**Comment by Kowlin** [comment]
At the moment we aren't interested in adding this into the core bot.
