### ISSUE TITLE
[Mutes] Mute error shows incorrect text

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#4847]
When muting a user fails, the message for unmuting is shown instead.

![image](https://user-images.githubusercontent.com/57032623/108998410-ca88c680-7698-11eb-9f2c-f641376b6d37.jpeg)

**Comment by Jackenmen** [comment]
#4850 was meant to fix this, but looking at the full message here, it appears that the "That user cannot be muted" reason still needs fixing so I'm keeping this open.
