### ISSUE TITLE
[Streams] Errors in Console

### ISSUE THREAD

**Issue by Menteroth** [Cog-Creators/Red-DiscordBot#4873]
I guess this occurs everytime it checks for online streams because it happens every 5 minutes.
Plus some "can't connect to Twitch API" errors sometimes.

https://pastebin.com/H2BqMVva

**Comment by Jackenmen** [comment]
Most of the logs here are related to network issues ("getaddrinfo failed"), however there is this in logs that is an actual issue:
```py
c:\__\coding\redenv\lib\site-packages\redbot\cogs\streams\streams.py:737 in check_streams
                        embed, is_schedule = await stream.is_online()
c:\__\coding\redenv\lib\site-packages\redbot\cogs\streams\streamtypes.py:182 in is_online
            return await self.make_embed(data)
c:\__\coding\redenv\lib\site-packages\redbot\cogs\streams\streamtypes.py:186 in make_embed
        vid_data = data["items"][0]
```
However, it looks like we're already tracking it in #4695 so I'm going to close this one. Thanks for reporting.
