### ISSUE TITLE
[Suggestion] Warning Function within the Mod Cog w/ Working Code

### ISSUE THREAD

**Issue by NekoTony** [Cog-Creators/Red-DiscordBot#488]
http://hastebin.com/igoloyudew.rb

That right there is the mod cog with a warning function. Users can set the max amount of warning points people can use before it bans. It works just like kick/ban where it sends the message to the mod-logs. I suggest updating the descriptions for the warn command and modset points command. Basically, you can assign warning points to a user, indicating they are doing something wrong, and if they reach the max amount of warning points they would be ban from that server permanently. It's something i came up in such little time and was hoping you could look into it, edit anything you don't like and possibly add it to the mod cog since it could benefit a lot of people and could be use as a warning system for people acting up. So...what do you say?

**Comment by NekoTony** [comment]
Alittle update: http://hastebin.com/lolomawoto.rb

Allows you to remove warning points

**Comment by Kowlin** [comment]
We thank you for the time you spend creating this, but it would be better if you used a GitHub PR system. This allows us to compare it against the current code, and will make a easier review system in general.

**Comment by NekoTony** [comment]
o

**Comment by Kowlin** [comment]
Was added in #490 closing.
