### ISSUE TITLE
[Downloader] Reply to original message for expensive coms

### ISSUE THREAD

**Issue by Vexed01** [Cog-Creators/Red-DiscordBot#4884]
### What component of Red (cog, command, API) would you like to see improvements on?

Downloader 

### Describe the enhancement you're suggesting.

I think that for the expensive commands in Downloader where the bot is typing (eg install/update/uninstall), it should then reply (without mention) to the invoke command.

I feel this would be a good fit with what replies are intended for, especially on slower hosting devices/big deps.

Possibly something for a downloader rewrite, but otherwise I would be happy to get assigned to this.

**Comment by Jackenmen** [comment]
Justification from Vexed (2021-03-18 - [message link](https://discord.com/channels/133049272517001216/718148684629540905/822145724258844742)):
> What I was thinking about was if it takes ages, pretty niche but ages ago on a slower machine it took half a day so a random message was a bit of a surprise when I'd forgotten I did it
> and I wouldn't like a ping myself

**Comment by Jackenmen** [comment]
I'm not really convinced this is something that should be added to Downloader, if there comes up a new reason for doing this, it might be reconsidered but for now, I'm going to close this.
