### ISSUE TITLE
Streams Cog - Multi Channel with "Regex" support

### ISSUE THREAD

**Issue by AlphaOmega2020** [Cog-Creators/Red-DiscordBot#4895]
### What component of Red (cog, command, API) would you like to see improvements on?

Streams

### Describe the enhancement you're suggesting.

Hi, would it be possible to add multi channel options to "streams" cog? What i mean by this is, if a stream has a specific word or words in its title it is posted in a specific channel, the same for another set of words are posted in a separate channel and if nothing matches then it goes to the default channel? 

No matched word = does not post OR posts to channel 0 
Matched word "stream" = posts to channel 1
Matched word "twitch" = posts to channel 2

**Comment by davidhu99** [comment]
Hi, is this wanted?

**Comment by Animal-UK** [comment]
> Hi, is this wanted?

yes

**Comment by AlphaOmega2020** [comment]
Yes

**Comment by AlphaOmega2020** [comment]
@davidhu99 could you do this?

**Comment by Drapersniper** [comment]
Regex support is unlikely to be added, that being said "Regex like:" support may be supported.

Also I'm nearly certain that @davidhu99 was asking if the Org members whished for him to work on this, due to it being untriaged the current direction here is not clear.

There was a brief discussion about it on the official discord server.

**Comment by AlphaOmega2020** [comment]
> Regex support is unlikely to be added, that being said "Regex like:" support may be supported.
> 
> Also I'm nearly certain that @davidhu99 was asking if the Org members whished for him to work on this, due to it being untriaged the current direction here is not clear.
> 
> There was a brief discussion about it on the official discord server.

ah, I see thank you.

Yes Regex "like" is fine. I hope this can be implemented! it would be a massive hit with large multi channel servers.

**Comment by Jackenmen** [comment]
I believe this feature is too niche though I'm not a very big user of Streams cog. @palmtree5 what do you think about this?

**Comment by BTNGaming** [comment]
This should be added xD I've been looking for something like this for so damn long, so when someone has a specific word or phrase in their title, it would announce that they are streaming... I run an RP server on FiveM so I'd like to NOT advertise other RP servers in my discord via streams

**Comment by danutzzzzz** [comment]
> This should be added xD I've been looking for something like this for so damn long, so when someone has a specific word or phrase in their title, it would announce that they are streaming... I run an RP server on FiveM so I'd like to NOT advertise other RP servers in my discord via streams

Ditto

**Comment by Kowlin** [comment]
This isn't gonna be something we will be adding in core I'm afraid. I agree with Jack here that this feature is too niche to be of value for the majority of Red end users.
