### ISSUE TITLE
[Warnings] Raw namedtuple output in [p]warnings

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Red-DiscordBot#4900]
### What Red version are you using?

3.4.7

### Cog name

Warnings

### Command name

warnings

### What did you expect to happen?

Have the member name properly show

### What actually happened?

Because `user` is treated as a member object, if it is a named tuple (when a user id is used for a member no longer in the server) it prints out that named tuple instead of the member name.

`Warnings for Member(id=00000000000, guild=<Guild id=00000000 name='Server' shard_id=0 chunked=True member_count=0>)`

https://github.com/Cog-Creators/Red-DiscordBot/blob/d26335b01b892e346e52cfd3bfcb86706647a76c/redbot/cogs/warnings/warnings.py#L529
https://github.com/Cog-Creators/Red-DiscordBot/blob/d26335b01b892e346e52cfd3bfcb86706647a76c/redbot/cogs/warnings/warnings.py#L555

### How can we reproduce this error?

1. Warn a user
2. Have that user leave the server
3. Run `[p]warnings <uid>` on that user

**Comment by Obi-Wan3** [comment]
Would displaying the user's `Username#Disc`(from a `self.bot.fetch_user()`) be acceptable? I am interested in taking this issue.

**Comment by Flame442** [comment]
I'm not sure we want to use a `fetch_user` call due to rate limits, I was thinking either a fallback `"Unknown User"` or use their id.
