### ISSUE TITLE
Dispatch listener when deleting services

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#4916]
### What component of Red (cog, command, API) would you like to see improvements on?

Shared API Keys

### Describe the enhancement you're suggesting.

I have a cog that was previously fetching the shared API keys when running a command, I fixed this by making a little cache, so on, I made a listener in my cog to detect changes if the API key of the service I'm using is being touched, so if the API key is edited, my cog will then call again the shared API.

The problem here is that if the user delete the service, my cog will NOT get any updates, so it'll still use the cache I made, that is a problem since I want my cog to know if the key is updated, or deleted.

My proposal is to either add this to the actual `on_red_api_tokens_update` or create a new listener. (`on_red_api_service_delete`)

**Comment by Jackenmen** [comment]
The lack of dispatch on shared API token removal was unintended, so I've just made a PR dispatching the update on removal.

**Comment by madebylydia** [comment]
Perfect, thank you.
