### ISSUE TITLE
Audio module is broken. YouTube got update.

### ISSUE THREAD

**Issue by REALMWTH** [Cog-Creators/Red-DiscordBot#4929]
### What Red version are you using?

3.4.7

### Cog name

Audio

### Command name

play

### What did you expect to happen?

To work :D

### What actually happened?

It doesn't work because of YouTube update

### How can we reproduce this error?

1.start play command
2.???
3.doesn't work

Here is what was updated within YouTube: https://github.com/jagrosh/MusicBot/issues/658
You guys need to update LavaPlayer

**Comment by aikaterna** [comment]
There are a few things at play here where it's not as simple as "update Lavaplayer".

First of all, take a look at https://github.com/Cog-Creators/Red-DiscordBot/issues/4505 where we have gathered all of the current issues.

Secondly, we have a prerelease jar at https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.3.2.3_1211 in case you are an advanced user and want to try our application of fixes, which was just published *yesterday* as all these problems are currently evolving issues.

Lastly, Lavaplayer 1.3.74 doesn't seem to address one of the issues, which is the PLAYER_JS_URL error mentioned in our pinned issue. We can't update to something that isn't working. 1.3.74 was also published this morning, not even hours ago, and there will need to be more changes. Be patient while I test and work on fixes with the Lavaplayer team.

**Comment by REALMWTH** [comment]
@aikaterna thank you very much for letting me know! I've indeed had PLAYER_JS_URL error reported by LavaLink yesterday and thought that it was fixed. Will wait patiently till it's fixed ;)
Until then, I've temporary unloaded audio module

**Comment by aikaterna** [comment]
Will be resolved by https://github.com/Cog-Creators/Red-DiscordBot/pull/4932
