### ISSUE TITLE
Error in downloader string formatting

### ISSUE THREAD

**Issue by JKohlman** [Cog-Creators/Red-DiscordBot#4963]
### What Red version are you using?

3.4.9

### Cog name

Downloader

### Command name

`cog install <repo> <cog that doesn't exist>`

### What did you expect to happen?

The error message should display the repository's name

### What actually happened?

Error message displays `Couldn't find this cog in {repo.name}:`

### How can we reproduce this error?

1. Run `[p]repo add <repo> <url>` to add a repo
2. Run `[p]cog install <repo> <cog that doesn't exist>` to attempt to install a non-existent cog
3. Observe result

From my first impressions this seems to be an issue with this line: https://github.com/Cog-Creators/Red-DiscordBot/blob/0eaa0f494cc6abc9a42cf7dfcab5bc426428ac1d/redbot/cogs/downloader/downloader.py#L1422-L1426

**Comment by Kreusada** [comment]
This has been patched via #4954

**Comment by Kowlin** [comment]
Thanks for the report! However this has already been fixed in #4954, and is scheduled to be included in the next release.
