### ISSUE TITLE
Picarto streams are not working (API changes)

### ISSUE THREAD

**Issue by Cloufish** [Cog-Creators/Red-DiscordBot#4969]
### What Red version are you using?

3.4.0

### Cog name

Streams

### Command name

!picarto Unnoen

### What did you expect to happen?

I expected the output of whether Unnoen (The user) is live or not

### What actually happened?

I got the message "That channel doesn't seem to exist."

### How can we reproduce this error?

1. Simply execute this command on a discord

![image](https://user-images.githubusercontent.com/32965886/114037815-9ac90300-9881-11eb-9a2b-04cdb15a6098.png)
![image](https://user-images.githubusercontent.com/32965886/114037886-ac120f80-9881-11eb-8d61-5df2f42a5432.png)

The solution to this problem is probably updating API interaction.

**Comment by Drapersniper** [comment]
Have you tried to reproduce it on the latest version of Red? (3.4.9)

**Comment by PredaaA** [comment]
Can confirm that it happens on latest version too.

**Comment by Kowlin** [comment]
Today i saw a small conversation on Discord that the Api has changed, (Not sure if we even used an API for the service) I'm willing to guess that it's related to that and will look into it in a bit.

**Comment by Cloufish** [comment]
> Have you tried to reproduce it on the latest version of Red? (3.4.9)

I was installing it today (Linux user). So I thought I'm on the newest version. **How to update the RedDiscord-Bot if its python module's not being the latest version?**, but (3.4.0)

**Comment by bobloy** [comment]
> > Have you tried to reproduce it on the latest version of Red? (3.4.9)
> 
> I was installing it today (Linux user). So I thought I'm on the newest version. **How to update the RedDiscord-Bot if its python module's not being the latest version?**, but (3.4.0)

If you're on 3.4.0, you probably are using the wrong version of python. Re-read the docs, or come join the discord to receive support. https://discord.gg/red

**Comment by cens0r3d** [comment]
this seems to be again a issue, api updated ?
