### ISSUE TITLE
Documentation for cog reinstallreqs

### ISSUE THREAD

**Issue by Technetium1** [Cog-Creators/Red-DiscordBot#4974]
### What component of Red (cog, command, API) would you like to see improvements on?

Downloader

### Describe the enhancement you're suggesting.

`[p]cog reinstallreqs` works as it was intended to in https://github.com/Cog-Creators/Red-DiscordBot/issues/3167 / https://github.com/Cog-Creators/Red-DiscordBot/pull/3274, however this behavior is not documented in the help command, only in the manual. https://docs.discord.red/_/downloads/en/latest/pdf/

**Comment by Jackenmen** [comment]
This command is purposefully not documented - it is a hidden command that Red will ask you to run when it detects the change in the environment.
