### ISSUE TITLE
bot.user does not contain all information it should

### ISSUE THREAD

**Issue by Jan200101** [Cog-Creators/Red-DiscordBot#498]
to be exact bot.user is missing

>nick
>permissions_in
>roles
>self_deaf
>self_mute
>server
>server_permissions
>session_id
>status
>top_role
>voice
>voice_channel
>mute
>color'
>colour
>created_at
>deaf
>default_avatar
>default_avatar_url
>discriminator
>display_name
>game
>id
>is_afk
>joined_at
>_copy
>_update_voice_state
> _ slotnames _ (double underscore, github has weird formatting)

a way of getting past this right now is server.get_member(bot.user.id) which will result in the full information being presented

**Comment by Jan200101** [comment]
server.me exists

**Comment by tekulvw** [comment]
This isn't missing anything. `bot.user` is an instance of `discord.User` which is server-independent (and why it has none of those attributes). You are looking for `server.me`
