### ISSUE TITLE
Broken Issue Templates

### ISSUE THREAD

**Issue by nfitzen** [Cog-Creators/Red-DiscordBot#5006]
You can see I'm not using an issue template for this very reason.

The reported error (based on <https://github.com/Cog-Creators/Red-DiscordBot/blob/7434a7c8e2d547767ad3eac169fcc942f8423df8/.github/ISSUE_TEMPLATE/feature_request.yml> and the other issue templates) seems to be:

- `title` must be a type of String.
- `assignees` must be a type of String or Array.

**Comment by Kowlin** [comment]
Thanks for the heads up, seems we got hit by a breaking change that wasn't announced.
