### ISSUE TITLE
[Core/Admin] Bot can leave all guilds while serverlocked

### ISSUE THREAD

**Issue by yamikaitou** [Cog-Creators/Red-DiscordBot#5008]
### What Red version are you using?

3.4.9

### Cog name

Core

### Command name

leave

### What did you expect to happen?

While the bot is serverlocked, the bot should not be able to leave the final server it is in

### What actually happened?

The bot left the server and is now lost in the abyss

### How can we reproduce this error?

1. Create new Bot
2. Join 1 server
3. Load Admin
4. Enable serverlock
5. Leave the server
6. Cry as you just lost your bot

### Anything else?

[x ] :D

**Comment by Jackenmen** [comment]
Making `[p]leave` check admin cog's config is a no go here (and it wouldn't solve the problem if the user kicked the bot) so as I see it, we have two ways to solve this:
- allow the bot to join a server *if* it's in no other guild
- don't allow the bot to join a server but show a warning in logs with information on how the user can surpass the server lock (which is running the bot with `--no-cogs` flag,)

It's important to say that this is an uncommon scenario and so I don't think we need to give some *amazing* solution and these are already quite good ones.

// side "what the heck": *why do we not have `--exclude-cogs` flag!?*
