### ISSUE TITLE
SponsorBlock API added to music bot

### ISSUE THREAD

**Issue by SaiCode-DEV** [Cog-Creators/Red-DiscordBot#5033]
### Type of feature request

Other

### Description of the feature you're suggesting

On more and more youtube songs unnessesary scenes come at the end of the songs (which arent music) Sponsorblock API just lets you skip those parts automatically. Can you please implement this as a feature?

**Comment by Drapersniper** [comment]
Sorry but I'll interject here and say no.

Putting aside the nightmare that it would be handling this on tracks that have multiple skips.

This is something I find morally wrong if you aren't paying to consume the content.

**Comment by flaree** [comment]
> Sorry but I'll interject here and say no.
> 
> Putting aside the nightmare that it would be handling this on tracks that have multiple skips.
> 
> This is something I find morally wrong if you aren't paying to consume the content.

not to mention the already included lyrics command can essentially do this given that most won't have intros etc.

**Comment by aikaterna** [comment]
It's also a request that's more suited for the audio backend we use vs. anything in Red itself. Feel free to request this in Lavaplayer, but it's highly unlikely we will be able to do anything regarding this ourselves.
