### ISSUE TITLE
Migrating from JSON database to PostgreSQL

### ISSUE THREAD

**Issue by cofob** [Cog-Creators/Red-DiscordBot#5047]
### What component of Red (cog, command, API) would you like to see improvements on?

Database

### Describe the enhancement you're suggesting.

Can I migrate from a existing JSON storage to PostgreSQL without data loss?

**Comment by Jackenmen** [comment]
If you need help using Red, you should ask on our support server at [discord.gg/red](https://discord.gg/red).
