### ISSUE TITLE
[Audio] everyone can playlist remove anything

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Red-DiscordBot#505]
no author checks, no permission checks

**Comment by Chovin** [comment]
except global playlists, there's that 👍

**Comment by Chovin** [comment]
fixed here apparently -> 1942f15576effbcb3ea35263254c4b25bad9faca
has anyone actually tested it? I know I haven't :3

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/1942f15576effbcb3ea35263254c4b25bad9faca
