### ISSUE TITLE
Use a different exit code for configuration errors

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#5069]
### What component of Red (cog, command, API) would you like to see improvements on?

Bot Core

### Describe the enhancement you're suggesting.

It might be worth using different exit code(s) (different from 1 that is) when Red has stopped due to an error that will certainly not be fixed just by a restart:
- missing intents
- no owner set (related to #4926)
- no token/prefix set when running with `--no-prompt`
- invalid token
- incorrect cli arguments passed (this is already mostly done by argparse)

This should also come with an update to auto-restart guides so that these different exit codes prevent continuous auto-restarting.

### Anything else?

The part with auto-restart guides might not be achievable on Mac - it doesn't seem that launchd can differentiate based on exit codes whether it should restart or not (it seems to only be able to differentiate between zero and non-zero), perhaps a special compatibility mode flag could be added?

If we want to get suggested by some source on the numbers to use for the exit codes, we can look [here](https://km.kkrach.de/p_exit_and_error_codes/) and [here](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Exit%20Codes) though it doesn't really seem like there's that much conventions for this and we can just come up with our own exit code numbers.

**Comment by palmtree5** [comment]
Regarding Mac: [the man page for launchd.plist](https://www.manpagez.com/man/5/launchd.plist/) seems to indicate that we would not be able to differentiate based on exit codes whether to restart or not. We can definitely look at Linux though, it should definitely be possible with systemd. I would also need to make changes to #4081 as well which would require some investigation of NSSM's docs to figure out if it's possible

EDIT: Quick look at NSSM's docs makes it seem to be possible on Windows...........with registry edits.........

**Comment by Jackenmen** [comment]
> Quick look at NSSM's docs makes it seem to be possible on Windows...........with registry edits.........

It should be possible to just use:
```
nssm set redbot AppExit 2 Exit
```
in addition to already ran commands.
