### ISSUE TITLE
Cleverbot Broken.

### ISSUE THREAD

**Issue by emorrisn** [Cog-Creators/Red-DiscordBot#509]
I could be wrong in the fact that its just my internet however cleverbot doesnt seem to work. The error is: `    parsed = self._parse(resp.text)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\cleverbot\cleverbot.py", line 156, in _parse
    if parsed[0][1] == 'DENIED':
IndexError: list index out of range`
Hope you can fix! ~Ethan

**Comment by emorrisn** [comment]
My name (in discord) is: F U R Y™#1730

**Comment by Twentysix26** [comment]
Most recent version of the cleverbot cog works. Update it or if that fails install it again. Also, wrong repository to open this issue in.

**Comment by emorrisn** [comment]
k sorry, thanks. I also did update but that doesnt seem to fix it
