### ISSUE TITLE
Limit Server Prefix length

### ISSUE THREAD

**Issue by yamikaitou** [Cog-Creators/Red-DiscordBot#5091]
### Type of feature request

Other

### Description of the feature you're suggesting

Impose a length limit on server prefix (and possible raise a warning on a global prefix)

**Comment by laggron42** [comment]
Should this be a hard coded limit or customizable one? And what should be the default value here then?

**Comment by phenom4n4n** [comment]
Based on some discussion in the server it was generally agreed that a reasonable value would be above 20 and maybe around 32 which is the username limit, I suggest that this should be hard coded as having it customizable seems like a trivial and niche feature.
