### ISSUE TITLE
Backing red up guide

### ISSUE THREAD

**Issue by Apoo711** [Cog-Creators/Red-DiscordBot#5110]
### Type of feature request

Other

### Description of the feature you're suggesting

I was reading through support and saw somebody say "I don’t think the backup guide is even on red docs" and I thought it might be a good idea to a page in the docs which would show users the back up commands, if its a good idea, I'm willing to make it.

**Comment by Drapersniper** [comment]
Yeah it's a good idea, right now there's an old frozen issue about it. https://github.com/Cog-Creators/Red-DiscordBot/issues/3421

It's pending the work on downloader.

**Comment by Apoo711** [comment]
I have made a template, which probably needs a lot of improvement, I've sent in the advanced-coding channel so people can review it.

**Comment by Jackenmen** [comment]
As mentioned above, duplicate of #3421
