### ISSUE TITLE
Impose limits on cleanup message command

### ISSUE THREAD

**Issue by Slurpcy** [Cog-Creators/Red-DiscordBot#5113]
### Type of feature request

Other

### Description of the feature you're suggesting

This is regarding the command ``[p]cleanup messages <amnt>`` as u know people could enter **any amnt** they wish and this could cause the bot to be rate limited , i would recommend **imposing a strict limit on how many messages can be deleted per cmd.** as that would be really helpful

### Anything else?

no that would be it.

**Comment by aikaterna** [comment]
Cleanup can only do cleanup for the past 14 days' worth of messages based on the limitation via the Discord API. You can't get rate limited through this action, but you will see the bot taking some time to cleanup large amounts of messages because it has to request it in chunks of 100 messages.

**Comment by aikaterna** [comment]
We may think about limiting this in the future, but with the confirmation for deletion over 100 messages and the fact that we're limited on how many messages we can delete anyway, and there are not really "bad" ratelimits being applied here (the calls for deletion and the time to fetch and delete are handled appropriately by the underlying library), I am closing this.
