### ISSUE TITLE
`[p]warn` accepts non-positive int points values

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Red-DiscordBot#5119]
### What Red version are you using?

3.4.9

### Cog name

Warnings

### Command name

warn

### What did you expect to happen?

An error when trying to run `[p]warn` with a negative or 0 number of points for a custom reason.

### What actually happened?

It blindly accepts the passed points.

### How can we reproduce this error?

1. Enable custom reasons
2. `[p]warn <user> -1 test`
3. `[p]warnings <user>`

**Comment by ghost** [comment]
Would like to work on this issue! Any help regarding this would be much appreciated.

**Comment by Flame442** [comment]
Sorry, a PR was already made for this issue (they just forgot to link it).

**Comment by ghost** [comment]
Ah alright, no problemo!
