### ISSUE TITLE
[Audio] More music providers

### ISSUE THREAD

**Issue by andrewbanonis** [Cog-Creators/Red-DiscordBot#5136]
### Type of feature request

API functionality, Command, Other

### Description of the feature you're suggesting

In addition to the two audio API's used, I would love for their to be an integration with Amazon Music and TIDAL. I have a few friends that use Amazon Music and they would like to be able to use direct links from there so they can play playlists. Personally, I use TIDAL, so being able to use playlists that I have in TIDAL would also be awesome! I know that there playlist converters out there, but that's a few extra steps to take which I really don't want to have to do, nor do my friends want to do it. I also think many other people would especially like to use Amazon Music links.

**Comment by andrewbanonis** [comment]
Also, I did some Google searching, it seems like that there is no official direct API from Amazon for Amazon Music, but it may be possible using an external tool, still doing some research on that. And as far as TIDAL goes, there does seem to be an API, but I'm not too sure how it works.

**Comment by Kowlin** [comment]
First of all thank you for the suggestion, however with audio services we very much operate on the side of caution. This is due the fact that most if not all are paid services either directly or indirectly. As for your suggestion, I'm gonna leave it open. However working this out may proof difficult.

**Comment by andrewbanonis** [comment]
Gotcha, didn't know that. Would still love to see it possibly sometime in the future :)

**Comment by aikaterna** [comment]
You would need to request support for these from the parent projects for the audio backend, Lavaplayer specifically. I'm closing this because I don't see that happening any time soon.
