### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by lincolnthedev** [Cog-Creators/Red-DiscordBot#5139]
### Type of feature request

Other

### Description of the feature you're suggesting

I found a PIP package for Discord.py slash commands, but I'm not great at Python, so wanted to see if anyone could look into it. Here's some info on it: [https://pypi.org/project/discord-py-slash-command/](https://pypi.org/project/discord-py-slash-command/). Also, just want to say thank you for this amazing project!

### Anything else?

As for the implementation, probably as a separate cog that comes with core called "slashcmds" and the following commands to go with that cog:

- **[p]addcog <COG NAME>** Add all of a cog's commands as slash commands
- **[p]addcmd <COMMAND NAME>** Add a single command as a slash command
- **[p]addcmds <COMMAND NAME...>** Add multiple commands as slash commands

**Comment by flaree** [comment]
We do not support the slash commands feature as our underlying library (discord.py) has yet to add support for them. Once it supports it, we will explore what features within Core will benefit from it, if anything. Cog Authors can either wait for Red to update our d.py version (once it supports it) or use an extension package to implement it in their cogs. The old version of this CC that contained a list of reasons why you shouldn't expect it any time soon can be found by running ?whynoslashold in #testing on the support server https://discord.gg/red


This is taken from our cc in the server.

**Comment by lincolnthedev** [comment]
This is a library that works on top of Discord.py

**Comment by flaree** [comment]
Until core discord.oy supports it (which won't be until 2.0), it won't be added into core Red. A lot of those libraries badly monkeypatch stuff. Creators are free to use them in their own cogs on the other hand.

**Comment by Jackenmen** [comment]
> As for the implementation, probably as a separate cog that comes with core called "slashcmds" and the following commands to go with that cog:
> 
> * **[p]addcog ** Add all of a cog's commands as slash commands
> * **[p]addcmd ** Add a single command as a slash command
> * **[p]addcmds ** Add multiple commands as slash commands

This is simply not possible, commands created with discord.py's commands extension cannot be directly translated to slash command due to various reasons like the custom converters, greedy parameters, and probably more.

As for the `discord-py-slash-command` library, we are not interested in using any 3rd-party discord.py libraries for slash commands or buttons. When discord.py supports them, then we'll consider looking into doing something with slash commands (though as said above, it won't be what you suggested) but until then, slash commands are a no-go in Core Red.

**Comment by PixPMusic** [comment]
This has been implemented upstream:

https://github.com/Rapptz/discord.py/issues/6149 - https://github.com/Rapptz/discord.py/tree/master/discord/app_commands
