### ISSUE TITLE
Allow balances to go into the negatives

### ISSUE THREAD

**Issue by Apoo711** [Cog-Creators/Red-DiscordBot#5151]
### Type of feature request

API functionality, Cog

### Description of the feature you're suggesting

I was using Flare's Unbelievaboat cog and i commited a crime through it, i had 0 balance before and and after i ran the command i lost an another 227 but my balance still remained on 0.

**Comment by Jackenmen** [comment]
Many cogs rely on the bank not allowing the balance to go below 0 and, for example, by catching exceptions they ensure that the user can afford the action before proceeding. Arguably, one could make a new keyword argument that needs to be explicitly set to True in cases where you do want to allow the balance to go into debt (so when you're trying to buy something, you're declined but if you are forced to pay something, you go into debt) but it still has a high potential of affecting many cogs and you haven't yet given many reasons for why you think this is a good idea. So, if you want to seriously consider this feature, I would suggest coming up with some concrete reasons, potential solutions, and in general, your view on how this could/should be done.

**Comment by Jackenmen** [comment]
You should also try to show us reasons why this cannot be solved with a 3rd-party cog and therefore would benefit from Core supporting it directly.

Here's one example of a 3rd-party cog that could be made to serve similar purpose:
> would be better suited as a third party cog to calculate the debt accrued anyways and force the user to pay into that to not accrue more debt within some time frame otherwise they lose all their bank balance could even be setup as a loan system so people can take out a loan and then have to pay it back within some time frame. That way it would work with Yami's cogs since it relies on cores bank never going below zero
>
> Originally posted by TrustyJAID in [message](https://discord.com/channels/133049272517001216/133081046869737472/855605881310674964)

**Comment by Jackenmen** [comment]
There have been no further responses here and the general consensus seems to be against adding this so it's time to close this.
