### ISSUE TITLE
Expose `[p]inviteset` Functionality (for Cogs)

### ISSUE THREAD

**Issue by Obi-Wan3** [Cog-Creators/Red-DiscordBot#5152]
### Type of feature request

API functionality

### Description of the feature you're suggesting

Currently, there is no supported method for third-party cogs to utilize the bot's settings for `[p]inviteset` in order to generate invite links with the same permissions and scopes as `[p]invite`. It would be great if either the settings/config info or the [link-generation function](https://github.com/Cog-Creators/Red-DiscordBot/blob/52f96e043bb43de9d5bb12d6c9dfdb34fb1cbf4d/redbot/core/core_commands.py#L372) were exposed for cogs to utilize.

### Anything else?

An example where this would be useful is in my [BotAccess](https://github.com/Obi-Wan3/OB13-Cogs/blob/400d75b932b0a1a508ed63943fdff082ee2b42a7/botaccess/botaccess.py#L195) cog, where server supporters are granted the ability to invite the bot to a limited number of their own servers. However, without this endpoint, either the generated invite link would be the "default" or `[p]inviteset` would need to be re-implemented.

**Comment by ltzmax** [comment]
This would be a good thing to have a public method for.

I also have a cog that try to use [p]inviteset to generate invite permission scope, so this is something I do find very useful for.

**Comment by Stonedestroyer** [comment]
Do you just want the current invite URL or some invite util that you can use to generate invite links by passing it permissions etc?

**Comment by TheDiscordHistorian** [comment]
> Do you just want the current invite URL or some invite util that you can use to generate invite links by passing it permissions etc?

The current one set in core, there's already an util in `discord.utils` iirc to generate invite links

**Comment by madebylydia** [comment]
In my opinion, it would be a nice addition to have both, for example, having one function that return what Red usually generate (What you did) and another function for an URL invite builder, as you suggested, which reminds me of this: https://docs.adonisjs.com/guides/routing#url-generation.
As I can tell, it would allow to:
1. Set scopes, under the form of a `tuple`, optional, default to `('bots',)`
2. Set permissions, under the form of an `int`, optional, default to `0`
3. Set guild ID, under the form of an `int` or a `discord.Guild` object, optional
4. Set `disable_guild_select`, under the form of a `bool`, optional, default to `False`

Reference: https://discord.com/developers/docs/topics/oauth2#bot-authorization-flow-bot-auth-parameters
