### ISSUE TITLE
Shorter Youtube Clips do not play completely, cutting off shortly before their endings

### ISSUE THREAD

**Issue by mag2352** [Cog-Creators/Red-DiscordBot#5158]
### What Red version are you using?

3.4.12

### Cog name

Audio

### Command name

play

### What did you expect to happen?

Any shorter youtube video, using this as an example, https://www.youtube.com/watch?v=BU0X7gsuEFI, the bot will stop playing the video at the end of the word "can", which is not the end of the video.

### What actually happened?

Playing this same video on the actual YouTube website, or using jagrosh's MusicBot will play the video to its entirety. This issue has been present for many versions of the bot, I have just decided to make an post about it now.

### How can we reproduce this error?

1. Enable automatic disconnect with [p]audioset dc (for example: !audioset dc).
2. Play any short music video, in this case, https://www.youtube.com/watch?v=BU0X7gsuEFI
3. Listen, and you can hear the video end earlier than expected.

### Anything else?

This issue isn't honestly a big problem, just wanted to notify other users about it.

**Comment by aikaterna** [comment]
Hey, I'm having trouble reproing this, tried it on three different hosts so far with various Red bots I have and it's played all the way through on every one. Also tried it with other python Lavalink libraries on other bots, and even tried it with Jagrosh's music bot on a Windows host (where I also tested a Red) and it was the same outcome. A couple folks in the Red server tried it on their bots too and it played all the way through to the word "stop" at the end of the video. Do you have an exceptionally slow device you're running your Red on or any sort of other spec information you could provide?

**Comment by mag2352** [comment]
Hmmm... it probably is my setup. I'll set it up again from scratch. I don't think its a slow device, it has a i7 7700 on Ubuntu LTS.

**Comment by mag2352** [comment]
Yup, reinstalling fixes the issue, that is embarrassing. Thanks for the help and confirmation.

**Comment by mag2352** [comment]
Okay, I figured out why it's happening. When auto disconnect is enabled ([p]audioset dc), that is what causes the issue. That is what is needed for me to replicate it.

**Comment by Jackenmen** [comment]
I can reproduce the issue. Thanks for looking into this further.
