### ISSUE TITLE
[Suggestion] Selective Cog Updates

### ISSUE THREAD

**Issue by Kyrislian** [Cog-Creators/Red-DiscordBot#516]
Just a suggestion for the Downloader Cog. Would be really nice to have the ability to pick which cogs to be updated and which to leave be, as sometimes some have been further customized for particular Red instances ^^

**Comment by Chovin** [comment]
I second this for security reasons.
being able to see what can be updated and choose which to update is pretty important if you're pulling from the repos of a bunch of new faces

**Comment by Kowlin** [comment]
This is a issue, not sure how I can test this.

**Comment by Twentysix26** [comment]
@Kowlin It's in the downloader, which is already merged
