### ISSUE TITLE
[Audio] Lavalink not handling voice updates/resumes on channel change appropriately

### ISSUE THREAD

**Issue by ImPrithibi** [Cog-Creators/Red-DiscordBot#5170]
### What component of Red (cog, command, API) would you like to see improvements on?

Audio

### Describe the enhancement you're suggesting.

After you queue a track into the bot and have it playing in one Voice channel, If you move the bot to another voice channel while the bot is playing, It seems like the Music keeps playing but the user isn't able to hear it. 

### Anything else?

If there are any questions or such, Please contact me

**Comment by aikaterna** [comment]
Make sure your Red is up to date, there's conditions in some of the newest Red-Lavalink commits that force resuming when channels are changed. FWIW I can't repro this as moving my bot to another channel makes audio resume playing shortly after the move as there was code written to detect this and do so.

**Comment by aikaterna** [comment]
Well, looks like we got a couple bots to do this but it seems to be intermittent. It may be farther up the chain in Lavalink itself as there have been a lot of folks asking about resumes and the like in the support channels for that, or it could have to do with the Discord client itself as I've seen similar things in the past. Could also be in our handling in the lib we use to connect to the Lavalink API/jar file. So I'll do some poking around regarding this, but no promises. A disconnect from the voice channel and reconnect to the voice channel on the bot's side will fix playback in the meantime.

**Comment by Technetium1** [comment]
I've run into this many times in the last few months. The solution was to move the bot back where it came from, then `[p]summon` to the next channel. It's occasionally given a Lavalink traceback; which will get posted here next time I see it.

**Comment by aikaterna** [comment]
This is related to https://github.com/freyacodes/Lavalink/pull/546 and we won't have much to do for it until it's fixed in the parent project.

**Comment by kpopdev** [comment]
i also sometimes when i do [p]audioset restart or change the lavalink server it will spamming my log [INFO] red.Audio.WS.Audio: Voice websocket reconnected to channel 891983638101639178 in guild: 760364973423067198 | Reason: Error code 4006 & Not playing. 
its all the same log but spamming.

**Comment by aikaterna** [comment]
This will be resolved by using our newest jar build at https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.4.0_1275. Note that you will also need to use the Red-Lavalink update at https://github.com/Cog-Creators/Red-Lavalink/pull/103 as well. Conversely, in case you don't want to try things manually, wait for Red to support these changes and then update Red on a new release.
