### ISSUE TITLE
[Mod] rename doesn’t respect user hierarchy 

### ISSUE THREAD

**Issue by phenom4n4n** [Cog-Creators/Red-DiscordBot#5187]
### What Red version are you using?

3.4.12

### Cog name

Mod

### Command name

rename

### What did you expect to happen?

The bot would respond, telling the user that  they cannot edit the names of members higher than them.

### What actually happened?

The user was able to edit the name of a member higher than them.

### How can we reproduce this error?

1. Place the bot’s role above 2 users in a server.
2. Have one user have a role higher than the other.
3. Give the user that is lower manage nickname perms.
4. Have user that is lower run `[p]nickme` on the user that is higher, allowing the lower user to bypass Discord hierarchy and edit that user’s nickname.

**Comment by qenu** [comment]
As red responses, 
> I do not have permission to rename that member. They may be higher than or equal to me in the role hierarchy.

I don't think the original design for red was to acknowledge and compare the role hierarchy between ctx.author and user, but instead it compares redbots' role to users' role

although if you want to make it that way its pretty simple, just swap ctx.me to ctx.author in names.py#L41 , and change up the response to match outcome L54

[something like this](https://github.com/qenu/Red-DiscordBot/blob/563cd805fd66b8d1359e9e9a233048268cfff085/redbot/cogs/mod/names.py)

**Comment by Flame442** [comment]
qenu, the current handling you are referring to is there to prevent API errors from the bot attempting to rename a member who is higher or equal to the bot user in the hierarchy. That check needs to remain.

What phen is referring to is the fact that the bot does not check if the *invoker* is higher than the member in the hierarchy, as that invoker would not normally be able to change the member's nickname, and probably should not be able to by default using `[p]rename`. This should probably be bundled in the `[p]modset hierarchy` setting, disallowing users from renaming members higher or equal in the hierarchy UNLESS that setting states the hierarchy should be ignored.

**Comment by qenu** [comment]
I see I have misunderstood what he meant,
Seeing that theres' a built-in hierarchy check function, I've went ahead on adding it
#5211
