### ISSUE TITLE
Support showing sphinx-style parameter-specific help texts in converter errors

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#5192]
### What component of Red (cog, command, API) would you like to see improvements on?

Converter errors

### Describe the enhancement you're suggesting.

I was thinking about ways to augment the display of error messages for converter errors with custom help text from the user, and I thought of leveraging Sphinx-style docstring help.

For example, suppose the full docstring is:

```
Specify a channel in which to configure the imagelimit, and a limit. The bot will then delete excessive images posted in the channel.

@param channel: The channel that you want to set up the automod imagelimit in
@param limit: The maximum number of images a user can send before the bot starts deleting
```

Provided help text if the user omits or sends an invalid limit:

```
<converter error message>
Additional info:
> `limit`: The maximum number of images a user can send before the bot starts deleting
```

Crucially, the parameter-specific help text will also NOT show in the normal help menu for the command, so we have some automatic progressive disclosure avenues available only as the user messes up. Further links can also be placed in the error messages linking to external wikis or other help resources, allowing frustrated users to get the help they need, without clogging up help menus with over-descriptive parameter explanations.

Opting out of the more verbose converter messages would be as simple as not writing Sphinx-style help texts for all of the parameters.

And this method would have the added benefit of integrating with writethedocs if people wanted to publish their cogs' docs on readthedocs.

### Anything else?

Related to:
* #5174 
* #5182

**Comment by Flame442** [comment]
While we may opt to use sphinx-style parameter syntax for something in the future, this is not what we would want to use it for. You may want to consider using slash commands once 3.5 comes out, as those support parameter specific descriptions.
