### ISSUE TITLE
[Filter] Scan text files for matches

### ISSUE THREAD

**Issue by MeatyChunks** [Cog-Creators/Red-DiscordBot#5193]
### What component of Red (cog, command, API) would you like to see improvements on?

API

### Describe the enhancement you're suggesting.

With Discord's new file preview, it's possible to bypass the filter by sending a text file which will be automatically embedded. If the attachment content type is text, this could also be scanned by the filter. There could also be a `[p]filterset` command to enable/disable this if needs be.

**Comment by Kowlin** [comment]
This feels out of scope for filter sadly enough. As this is more then just a simple grab the file and look what's inside it. There are a lot of nuances that need to be considered, such as file size of the ``txt``, ensuring its a valid ``txt`` and not some incorrectly labeled file. And I also have some concerns with security regarding this. The way Discord handles showing  ``txt``s is by letting the client pick them up and attempting to show them in an secure environment, we cannot easily replicate this. And to me it feels like there are too many downsides for this to succeed in a good way.
