### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by MeaslystormNetwork** [Cog-Creators/Red-DiscordBot#5197]
### What Red version are you using?

3.4.5

### What were you trying to do?

Tried To Follow Installation Guide Using Python. python -m pip install -U Red-DiscordBot
This Command Here. 

### What did you expect to happen?

To Completly Install Redbot.

### What actually happened?

https://ibb.co/Nr0kz8y.png This happened while doing the install command...

### How can we reproduce this error?

1.python -m pip install -U Red-DiscordBot - Install in python
2. install
3. install
... install

### Anything else?

Yeah please fix it! Or tell me what im doing wrong. Thanks

**Comment by aikaterna** [comment]
Please join our support server at https://discord.com/invite/red and head to the support channel so we can assist you.
