### ISSUE TITLE
Allow selfroleset multiple params

### ISSUE THREAD

**Issue by relma2** [Cog-Creators/Red-DiscordBot#5237]
### What component of Red (cog, command, API) would you like to see improvements on?

Core/Admin

### Describe the enhancement you're suggesting.

So currently `selfroleset add` does not do multiple parameters.

Like I did this, expecting the roles "she", "he", and "they" to become self settable, but this happened: 
![image](https://user-images.githubusercontent.com/9358770/131557269-2ab5665b-98bb-416c-8bc5-d9f8e16d7497.png)

So it turns out i have to do the roles individually

### Anything else?

I think this would be a pretty useful enhancement tbh

**Comment by Kreusada** [comment]
Any chance I could be assigned to this one?
