### ISSUE TITLE
Audio cog crashed shortly after installation

### ISSUE THREAD

**Issue by dhoskins97** [Cog-Creators/Red-DiscordBot#5239]
### What Red version are you using?

3.4.12

### What were you trying to do?

Was trying to use Audio cog to listen to music. Queued 3 songs to test functionality (installed last night)

### What did you expect to happen?

I expected the bot to play the tracks I queued

### What actually happened?

The bot played most of the first song without an issue, then stopped and threw this error in Discord:

![image](https://user-images.githubusercontent.com/50965130/131587475-0fe52f5c-00c1-4473-a1f2-fe727eb13895.png)

The redbot instance gave the following output:

[18:04:10] CRITICAL Caught unhandled exception in event loop:                                                [red.main]
                    Task was destroyed but it is pending!
Exception ignored in: <coroutine object as_completed.<locals>._wait_for_one at 0x0000028BBBA1AB40>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\tasks.py", line 615, in _wait_for_one
    f = await done.get()
  File "C:\Python38\lib\asyncio\queues.py", line 165, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
           CRITICAL Caught unhandled exception in event loop:                                                [red.main]
                    Task was destroyed but it is pending!

### How can we reproduce this error?

1. Queue a few tracks on Audio cog.
Not certain, I don't know if this is purely environmental or if I bungled installation.

### Anything else?

After the initial crash described above, when I restart the bot I receive the following output:
(Forgive me if this is an obvious issue, I've not worked with discord bots before now and I'm stumped on this one.)

[18:06:24] INFO     Loading packages...                                                                           [red]
           INFO     Loaded packages: audio                                                                        [red]
           INFO     Connected to Discord. Getting ready...                                                        [red]

______         _           ______ _                       _  ______       _
| ___ \       | |          |  _  (_)                     | | | ___ \     | |
| |_/ /___  __| |  ______  | | | |_ ___  ___ ___  _ __ __| | | |_/ / ___ | |_
|    // _ \/ _` | |______| | | | | / __|/ __/ _ \| '__/ _` | | ___ \/ _ \| __|
| |\ \  __/ (_| |          | |/ /| \__ \ (_| (_) | | | (_| | | |_/ / (_) | |_
\_| \_\___|\__,_|          |___/ |_|___/\___\___/|_|  \__,_| \____/ \___/ \__|

┌─────────── Baccai ────────────┐ ┌─────────────────────┐
│  Prefixes           │ r       │ │  Shards       │ 1   │
│  Language           │ en-US   │ │  Servers      │ 3   │
│  Red version        │ 3.4.12  │ │  Unique Users │ 70  │
│  Discord.py version │ 1.7.3   │ └─────────────────────┘
│  Storage type       │ JSON    │
└───────────────────────────────┘
Loaded 3 cogs with 64 commands

Invite URL: https://discord.com/oauth2/authorize?client_id=882088681278693406&scope=bot
[18:06:27] ERROR    Audio failed to start up, please report this issue.              [red.cogs.Audio.cog.Tasks.startup]
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:969 in _wrap_create_connection                         │
│ >  969                 return await self._loop.create_connection(*args, **kwargs)  # type:                          │
│        ignore  # noqa                                                                                               │
│ C:\Python38\lib\asyncio\base_events.py:1050 in create_connection                                                    │
│ > 1050         transport, protocol = await self._create_connection_transport(                                       │
│ C:\Python38\lib\asyncio\base_events.py:1080 in _create_connection_transport                                         │
│ > 1080             await waiter                                                                                     │
│ C:\Python38\lib\asyncio\sslproto.py:529 in data_received                                                            │
│ > 529             ssldata, appdata = self._sslpipe.feed_ssldata(data)                                               │
│ C:\Python38\lib\asyncio\sslproto.py:189 in feed_ssldata                                                             │
│ > 189                 self._sslobj.do_handshake()                                                                   │
│ C:\Python38\lib\ssl.py:944 in do_handshake                                                                          │
│ >  944         self._sslobj.do_handshake()                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

The above exception was the direct cause of the following exception:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\dakot\redenv\lib\site-packages\redbot\cogs\audio\core\tasks\startup.py:57 in initialize                    │
│ >  57             await self._build_bundled_playlist()                                                              │
│ C:\Users\dakot\redenv\lib\site-packages\redbot\cogs\audio\core\utilities\playlists.py:713 in                        │
│ _build_bundled_playlist                                                                                             │
│ > 713         web_version, tracks = await self._get_bundled_playlist_tracks()                                       │
│ C:\Users\dakot\redenv\lib\site-packages\redbot\cogs\audio\core\utilities\playlists.py:690 in                        │
│ _get_bundled_playlist_tracks                                                                                        │
│ > 690             async with session.get(                                                                           │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\client.py:1117 in __aenter__                                        │
│ > 1117         self._resp = await self._coro                                                                        │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\client.py:520 in _request                                           │
│ >  520                             conn = await self._connector.connect(                                            │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:535 in connect                                         │
│ >  535                 proto = await self._create_connection(req, traces, timeout)                                  │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:892 in _create_connection                              │
│ >  892             _, proto = await self._create_direct_connection(req, traces, timeout)                            │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:1051 in _create_direct_connection                      │
│ > 1051             raise last_exc                                                                                   │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:1020 in _create_direct_connection                      │
│ > 1020                 transp, proto = await self._wrap_create_connection(                                          │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:973 in _wrap_create_connection                         │
│ >  973             raise ClientConnectorSSLError(req.connection_key, exc) from exc                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ClientConnectorSSLError: Cannot connect to host gist.githubusercontent.com:443 ssl:default [[SSL: WRONG_VERSION_NUMBER]
wrong version number (_ssl.c:1131)]
[18:06:28] ERROR    Task-270 raised an Exception                                         [red.cogs.Audio.task.callback]
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:969 in _wrap_create_connection                         │
│ >  969                 return await self._loop.create_connection(*args, **kwargs)  # type:                          │
│        ignore  # noqa                                                                                               │
│ C:\Python38\lib\asyncio\base_events.py:1050 in create_connection                                                    │
│ > 1050         transport, protocol = await self._create_connection_transport(                                       │
│ C:\Python38\lib\asyncio\base_events.py:1080 in _create_connection_transport                                         │
│ > 1080             await waiter                                                                                     │
│ C:\Python38\lib\asyncio\sslproto.py:529 in data_received                                                            │
│ > 529             ssldata, appdata = self._sslpipe.feed_ssldata(data)                                               │
│ C:\Python38\lib\asyncio\sslproto.py:189 in feed_ssldata                                                             │
│ > 189                 self._sslobj.do_handshake()                                                                   │
│ C:\Python38\lib\ssl.py:944 in do_handshake                                                                          │
│ >  944         self._sslobj.do_handshake()                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

The above exception was the direct cause of the following exception:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\dakot\redenv\lib\site-packages\redbot\cogs\audio\core\tasks\startup.py:65 in initialize                    │
│ >  65             raise err                                                                                         │
│ C:\Users\dakot\redenv\lib\site-packages\redbot\cogs\audio\core\tasks\startup.py:57 in initialize                    │
│ >  57             await self._build_bundled_playlist()                                                              │
│ C:\Users\dakot\redenv\lib\site-packages\redbot\cogs\audio\core\utilities\playlists.py:713 in                        │
│ _build_bundled_playlist                                                                                             │
│ > 713         web_version, tracks = await self._get_bundled_playlist_tracks()                                       │
│ C:\Users\dakot\redenv\lib\site-packages\redbot\cogs\audio\core\utilities\playlists.py:690 in                        │
│ _get_bundled_playlist_tracks                                                                                        │
│ > 690             async with session.get(                                                                           │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\client.py:1117 in __aenter__                                        │
│ > 1117         self._resp = await self._coro                                                                        │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\client.py:520 in _request                                           │
│ >  520                             conn = await self._connector.connect(                                            │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:535 in connect                                         │
│ >  535                 proto = await self._create_connection(req, traces, timeout)                                  │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:892 in _create_connection                              │
│ >  892             _, proto = await self._create_direct_connection(req, traces, timeout)                            │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:1051 in _create_direct_connection                      │
│ > 1051             raise last_exc                                                                                   │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:1020 in _create_direct_connection                      │
│ > 1020                 transp, proto = await self._wrap_create_connection(                                          │
│ C:\Users\dakot\redenv\lib\site-packages\aiohttp\connector.py:973 in _wrap_create_connection                         │
│ >  973             raise ClientConnectorSSLError(req.connection_key, exc) from exc                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ClientConnectorSSLError: Cannot connect to host gist.githubusercontent.com:443 ssl:default [[SSL: WRONG_VERSION_NUMBER]
wrong version number (_ssl.c:1131)]

**Comment by Jackenmen** [comment]
If you need help using Red, you should ask on our support server at [discord.gg/red](https://discord.gg/red).
