### ISSUE TITLE
!mute server command works for anyone. Regardless of permission.

### ISSUE THREAD

**Issue by JakeyPrime** [Cog-Creators/Red-DiscordBot#524]
When admin and modrole have been set, the !mute command works fine, and only mods and admins can use it. But the !mute server command can be used by anyone. Found out the hard way.

**Comment by palmtree5** [comment]
Confirming that anyone can use !mute server. It doesn't make sense as to why though

**Comment by JakeyPrime** [comment]
I just looked into the code to see why, and I can't find anything. Albeit, I'm not the best with Python, but I can't see anything.

**Comment by tekulvw** [comment]
I have no idea either, looking into it right now

**Comment by tekulvw** [comment]
Okay we do have an answer, someone's gonna put a patch together momentarily

**Comment by JakeyPrime** [comment]
Thanks guys, amazing work.

**Comment by tekulvw** [comment]
And done, fixed with the above referenced merge.
