### ISSUE TITLE
Audio lag spikes and play faster after them

### ISSUE THREAD

**Issue by MineJOT1** [Cog-Creators/Red-DiscordBot#5309]
Audio lag spikes occur when playing from youtube with the audio cog.
I tested with two windows machines. I have 400m down 40m up internet.

**Comment by aikaterna** [comment]
Audio on Discord is sent through UDP, so if there are any drops in connection you will get "lag" as the packets aren't re-sent. The speed of your internet is not really important unless you are on dialup or something similar.

Laggy audio is most likely a problem with the connection between the host machine of your bot to the Discord server (or Discord is wonking out), try these:

1. Wait
2. Try restarting your bot
3. Check to make sure it's not just a bad quality song (try a different song)
4. Try a different server region
5. Try hosting your bot elsewhere
6. Try using the Discord web client and not the desktop client
7. Have others listen to your bot while it's playing - if not everyone is experiencing the issue, it's a Discord client issue. 

If you have further questions or need more help, join the official support server at discord.gg/red.
