### ISSUE TITLE
Removing an instance with nonexistant PostgreSQL database fails

### ISSUE THREAD

**Issue by leetfin** [Cog-Creators/Red-DiscordBot#5312]
### What Red version are you using?

3.4.13

### What were you trying to do?

Delete an instance with a nonexistent PostgreSQL database.

### What did you expect to happen?

The instance to be deleted.

### What actually happened?

A really long error message, and the instance did not get deleted.

### How can we reproduce this error?

1. Run redbot-setup <name>
2. Choose PostgreSQL
3. Input settings to a server that doesn't exist
4. Try to delete the instance

### Anything else?

[Discord support message where issue was found.](https://discord.com/channels/133049272517001216/387398816317440000/886422097692332052)

**Comment by Jackenmen** [comment]
This is up for grabs, to fix this, the driver should only be initialized and teardown *if* the user actually asks to delete the db data. The relevant code can be seen here:
https://github.com/Cog-Creators/Red-DiscordBot/blob/eeed082542515350260b7f66f38cb5e8f74d1dd9/redbot/setup.py#L267-L283

It might also be worth showing a better error message on failure too, though we don't have uniform errors between different drivers which might be a bit of a problem here (catching *all* exceptions is a no go unless we do not hide the traceback). I would say that this is not necessary to address this issue and we can just deal with that in farther future.

**Comment by leetfin** [comment]
is all that's needed here another `if delete_data is True:`?
