### ISSUE TITLE
occasional track error 

### ISSUE THREAD

**Issue by Ae3NerdGod** [Cog-Creators/Red-DiscordBot#5318]
every once in a while a track fails to play for no reason, if i go back to the track it will play, but the first try fails. anyway we could get a setting for retrys? also, i have no idea where these errors get logged. journalctl - u red@<instance name> doesnt show any errors, so i dont even know why the tracks are failing to play

**Comment by aikaterna** [comment]
First of all, make sure that your bot is up to date as the audio backend was recently updated. You can check if there's an update for you by looking at your bot's `info` command. If this happens after your bot is fully up to date, we're going to need the Lavalink logs from you, which are in your bot's datapath under the logs folder in the Audio folder. Please join the support server at discord.gg/red with those logs so we can help you if you still need help.
