### ISSUE TITLE
Audio failed to start up

### ISSUE THREAD

**Issue by jeikeuu** [Cog-Creators/Red-DiscordBot#5327]
### What Red version are you using?

3.4.5

### Cog name

Audio

### Command name

Startup

### What did you expect to happen?

The bot and cog to start like normal

### What actually happened?

![error](https://user-images.githubusercontent.com/91136004/134179749-42f4caf1-8d28-45ac-a762-d40c2a5fa7fd.png)

### How can we reproduce this error?

1.start the bot
2.
3.
...
start the bot

### Anything else?

Was using the bot perfectly fine until I had to update my graphics drivers and restart my PC

**Comment by Flame442** [comment]
Did you actually check your red version, or copy the hint? You can check it in `[p]info`. If that *is* your red version, you are very out of date and should update your bot.

**Comment by wtreible** [comment]
Also happened to me. Randomly went to restart today and get this same exact error.

**Comment by Ryan5453** [comment]
@wtreible @jeikeuu Are either of you running your bot at home? In the [red server](https://discord.gg/red) a user seemed to be able to fix this issue by restarting their router, so you could possibly try that and see if it fixes this.

**Comment by jeikeuu** [comment]
@aleclol You da best
