### ISSUE TITLE
Can `^userinfo` say if a user was banned?

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#5346]
### What component of Red (cog, command, API) would you like to see improvements on?

Command

### Describe the enhancement you're suggesting.

If I `^userinfo` someone and they're not in the server, currently it just says "Member xxxxxxxx not found." no matter what. But, if that user has a ban recorded on the server, could it say "Member xxxxxxxxxxxx is banned." ?

**Comment by madebylydia** [comment]
I am personally not in favor for that.
If I do not want my members to know I banned a member, (In others words my modlog channel is private) then I think they shouldn't be able to know through the `userinfo` command.
While it may be possible, the bot would require the Ban Members permission, and that's unlikely admins would put this permission for this particular functionality if they don't use the bot for moderation purposes.
And I'm not for it as I think it break a bit privacy of the banned user. And staff's discretion.

**Comment by RheingoldRiver** [comment]
Hmm, those are good points. Maybe this could be done only when it's executed by a mod (or someone with ban users permission) in a channel that @ everyone lacks permissions to view? (and when the bot has the permission to view the banned user list of course)

We typically use `^userinfo` in mod-only bot spam channels for the most part and it would be pretty useful to see if a user is banned or not.

**Comment by Apoo711** [comment]
I believe userinfo is designed to be this way, userinfo gets info about a user in the server and not globally. I could be wrong though, this is just what I understood.

**Comment by ltzmax** [comment]
It's not too bad idea but I don't think it's possible lock that to ban permission. There's plenty servers out there that doesn't use bots for moderating servers and don't see that as useful feature.

All though there is a modnote cog that might be a little to help. Even if it's not what you look for.

**Comment by RheingoldRiver** [comment]
What if, in addition to the permission gate, this was toggleable in `modset` ?

e.g. `^modset userinfoshowbans`

**Comment by madebylydia** [comment]
I am not in favor of a toggleable for this command, it become much more complicated than it should be to me. It's meant to be easy to use and only show informations of an user that is present in the server.
Maybe my point of view is a bit too "out of place" as I never had to deal with this kind of context (Having to check an userinfo of someone I banned).

**Comment by RheingoldRiver** [comment]
For us, we use our bot on a network of related servers, and it's pretty often that a user will be banned on one of them but not all. We are wondering who the user is, so we ^userinfo them on another, "oh they're not a member here" and then we have to check "ok well are they banned or just not a member" and it's a pretty big hassle. It would help a lot if the command just said, "oh actually the user is just banned here."

I'm not sure what the best compromise would be between maintaining privacy for servers that want nothing to do with displaying bans here & displaying this info, but I suspect a lot of servers are closer to our use case with this command, so I'm just making some suggestions of possible ways to enable that, while defaulting to the status quo.

**Comment by Apoo711** [comment]
I'd suggest looking into sbansync by twentysix. https://github.com/Twentysix26/x26-Cogs

**Comment by aikaterna** [comment]
You could fork Red and add it yourself to your own instance, or make a 3rd party cog for it. I'm not particularly fond of this suggestion for core either. Lots of folks on the Red server have their own implementation of userinfo, when they want to add things to it for their own preferences.

**Comment by Flame442** [comment]
Since the conversation in this issue appears to be resolved, I'm closing it now.
