### ISSUE TITLE
Russian translation issue

### ISSUE THREAD

**Issue by nukdokplex** [Cog-Creators/Red-DiscordBot#5363]
### What Red version are you using?

3.4.14

### Cog name

Core

### Command name

repo add

### What did you expect to happen?

No translation for substring "I agree" or bot's reaction to the translated message, in Russian it is "Я согласен".

### What actually happened?

![image](https://user-images.githubusercontent.com/25458915/135725711-53e0d1c9-426a-4cec-89e2-dbb6b637cfe4.png)

### How can we reproduce this error?

1. Set i18n settings to Russian language
2. Add any repo by command "[p] repo add"

**Comment by ghost** [comment]
There are many prompts like this that cause issues when translated (such as "yes", and "no") and it's up to the translator to notice it, i didn't know it was possible to avoid (i think still is in some cases like "True" and "False" or audio playlist scopes) and thus never reported, it's nice to see a major i18n issue get solved even if gradually.

**Comment by Jackenmen** [comment]
This can generally be easily resolved in regular string, but it is not as easy to handle with docstrings (see also #3919 and the discussion in the associated PR)

**Comment by Kowlin** [comment]
This particular string also has been handled on the Crowdin side last week and is ready to be introduced on the next release.
