### ISSUE TITLE
Unable to start Red

### ISSUE THREAD

**Issue by ss1gohan13** [Cog-Creators/Red-DiscordBot#5368]
**What Red version are you using?**

(newest)
Docker container - https://github.com/PhasecoreX/docker-red-discordbot

**What did you expect to happen?**
After updating the docker container, I expected the container to restart. 

**What actually happened?**

Received an error:
`/app/start-redbot.sh: 39: /app/functions/configure-redbot.sh: redbot: Permission denied`

**How can we reproduce this error?**

Starting the container again

Anything else?

Using unRaid and docker to run/manage my containers.

**Comment by Wayrion** [comment]
Docker isn't supported, If you have any more queries please feel free to ask in red's support server (discord.gg/red)

**Comment by Jackenmen** [comment]
Docker is not officially supported by Red. The container that you're mentioning is 3rd-party and as such, you should get support [there](https://discord.gg/QzdPp2b), not here.
