### ISSUE TITLE
update.bat doesn't work with python 3.6

### ISSUE THREAD

**Issue by rreyv** [Cog-Creators/Red-DiscordBot#544]
It quits with 'requested python version (3.5) not installed.
Changing to update.bat to search for 3.6 instead works though.

**Comment by Kowlin** [comment]
We currently don't support Python 3.6 *(As it just released roughly 16 hours ago from writing this post)* So please note that there are already some issues regarding 3.6 on the bot. One of them being not being able to set the owner from the console. And we're looking into fixing them (Mostly after Christmas)

**Comment by rreyv** [comment]
Thanks for the ridiculously quick response! Have a good Christmas. I'll use
3.5 in the meantime.

**Comment by Kowlin** [comment]
*Poof* update.bat is gone! Python 3.6 should be supported now. The new launcher will update and run Red from now on.

**Comment by rreyv** [comment]
Gracias
