### ISSUE TITLE
Use CamelCase in the [p]findcog command.

### ISSUE THREAD

**Issue by Honkertonken** [Cog-Creators/Red-DiscordBot#5443]
### Type of feature request

Cog, Command

### Description of the feature you're suggesting

In the `[p]findcog` command, all the cogs installed using downloader don't use CamelCase under the Cog Name field.

**Comment by Flame442** [comment]
Currently, the `Cog Name` field uses the `name` info.json key if the cog is installed via downloader, and the class name otherwise. It should probably be made consistent, and making it the class name would make it easier to find help for a cog from a command. Unless there is some reason to show the `name` field that I'm not thinking of, this should be an acceptable change.

**Comment by madebylydia** [comment]
Instead of replacing the cog name (#5519), putting the class's name between parentheses next to the cog's name could do the trick?

**Comment by Jackenmen** [comment]
I don't agree with this change, I consider package name (the name that is currently shown for Downloader-installed cogs in `[p]findcog`) to be more useful - *every* command in Downloader, as well as `[p]load/unload/reload` commands requires *this* name as an argument, not the class name. If anything, we should instead try to figure out a package name for the other cases, not use the class name for Downloader-installed cogs.
I'm not sure that such a package name could always be fully accurate but it's IMO more useful to have it this way.
Another option would be to just put both cog package name and class name into `[p]findcog`. The output of the command is getting somewhat long so perhaps doing it in parentheses as @Predeactor said would be preferable over adding another field.

**Comment by Honkertonken** [comment]
fair, so something like this should do the trick. https://rick-roll.click-if-you-da.re/5jYP8g0Za.png , made the changes required.

**Comment by Jackenmen** [comment]
Resolved by #5772
