### ISSUE TITLE
Readme file. Korean translation.

### ISSUE THREAD

**Issue by sangpyeong** [Cog-Creators/Red-DiscordBot#5445]
I want to contribute to this project by translating the readme file description into Korean, is it possible?

**Comment by WreckRox** [comment]
The readme file, to my knowledge, is not translated into any languages. You can check the [Crowdin](https://translate.discord.red/) for Red to see where you can help translate Red.

**Comment by Kowlin** [comment]
Hey there,

Thank you for your interest in translating the README.md, however we do not accept translations for that. If you're still interested in translating, we suggest you do so on https://translate.discord.red .
