### ISSUE TITLE
Config *_from_id(s) methods not typechecking.

### ISSUE THREAD

**Issue by i-am-zaidali** [Cog-Creators/Red-DiscordBot#5459]
### What Red version are you using?

3.4.14

### What were you trying to do?

Trying to access a guild's data from config using the `Config.guild_from_id()` method but accidentally passed in a guild object instead of its id.

### What did you expect to happen?

An error or exception to raise that indicated that my passed value wasn't of type int.

### What actually happened?

The `Config.guild_from_id()` method took the guild object and casted it to a string which turned into the guild's name and upon bot restart, errors were raised about it not being of base 10 for int casting when using the `Config.all_guilds()` method in a cog's initialization

### How can we reproduce this error?

1. Use the `Config.guild_from_id()` method but instead of an integer id, pass a proper guild object.
2. Restart the bot and call the `Config.all_guilds()` method in a cog.

### Anything else?

I'll be happy to push a pr fix for this if needed

**Comment by Flame442** [comment]
Though generally we expect inputs to be the correct type without explicit checking, since in this case it has the potential to easily break a config file, I'd say there probably should be some explicit type checking. Feel free to PR a fix if you feel comfortable doing so.
