### ISSUE TITLE
Update required packages when 3rd party cog is updated

### ISSUE THREAD

**Issue by i-am-zaidali** [Cog-Creators/Red-DiscordBot#5469]
### What component of Red (cog, command, API) would you like to see improvements on?

Downloader

### Describe the enhancement you're suggesting.

When updating a cog through the `[p]cog update` command, the bot should try and update the required packages from the info.json too. This often results in errors if an update to the cog requires a newer version of the required package and its not updated.

**Comment by Jackenmen** [comment]
Cog update does update the requirements. Due to how Python works, the updated requirement won't be used until you restart Red.

**Comment by i-am-zaidali** [comment]
Oh. I didn't know that. Thanks
