### ISSUE TITLE
[Feature Request] Webstream play

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#548]
Ability for the audio cog to listen to a webstream.

**Comment by skeith** [comment]
You know, your suggestion is TOO broad. YouTube is a webstream. Soundcloud too is a webstream. Both supported

**Comment by ghost** [comment]
To a constant webstream such as listen.moe/stream for example. Is this specific enough?

**Comment by Conobi** [comment]
Yep. What you want is an icecast/shoutcast support, and i really would love to get something like this.

**Comment by tekulvw** [comment]
Moving to #623
