### ISSUE TITLE
[Core] Add a function that allows, with more options than Predicates, to request confirmation from a user in the form of feedback/messages

### ISSUE THREAD

**Issue by AAA3A-AAA3A** [Cog-Creators/Red-DiscordBot#5539]
### Type of feature request

API functionality

### Description of the feature you're suggesting

Hello,
I have coded a function to add to the core that adds many options to Predicates.
It is a function that can be invoked by any cog in the redbot or core. It allows you to ask the user for confirmation with reactions or yes/no messages. Compared to Predicates, the developer can include everything in one function: the text to be sent, the embed to be sent, the file to be sent, the time until the end, the message sent at the end of the timeout, if the function should use reactions or ask for yes/no, a possible message that will be used instead of sending a new one, if it is the function that sets the reactions or if the invoking code already does so, if the message must be deleted at the end, the reactions to be used (a list of 2 to be provided), if the owners of the bot can also use the reactions/messages, a list of members authorised to reply too.
The only falcutative argument is `ctx` and the rest will be set automatically by the function.
I don't know where to put it in the core. Any ideas? Predicates perhaps?
Thanks in advance for your answers.

### Anything else?

async def ConfirmationAsk(
        ctx,
        text: Optional[str]=None,
        embed: Optional[discord.Embed]=None,
        file: Optional[discord.File]=None,
        timeout: Optional[int]=60,
        timeout_message: Optional[str]="Timed out, please try again",
        use_reactions: Optional[bool]=True,
        message: Optional[discord.Message]=None,
        put_reactions: Optional[bool]=True,
        delete_message: Optional[bool]=True,
        reactions: Optional[Iterable[_ReactableEmoji]]=["✅", "❌"],
        check_owner: Optional[bool]=True,
        members_authored: Optional[Iterable[discord.Member]]=[]):

![image](https://user-images.githubusercontent.com/89632044/148996805-2839dfb7-75e4-4ece-b983-283c9754674f.png)

**Comment by Flame442** [comment]
This is not something we are interested in adding into core. The features this would support are already supported by the existing Predicate system in a more configurable manor, while being easier to work with and understand.
