### ISSUE TITLE
Cannot change bot's name using "redbot --edit"

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#5545]
### What Red version are you using?

3.4.16

### What were you trying to do?

I was trying to edit one of my instance using `redbot <Name> --edit`. In the process, I wanted to edit the bot's name too, but when answered "Yes", the command make you return to the terminal.
See the included GIF.

![Code_htfcdRR4U3](https://user-images.githubusercontent.com/61093863/150001426-2d5c44b3-0c2c-478f-a2a1-00b95fc86fd7.gif)

### What did you expect to happen?

Being able to change's the bot name.

### What actually happened?

The command exited.

### How can we reproduce this error?

1. Use `redbot <name> --edit`
2. Skip questions and say "yes" for changing the instance's name.

### Anything else?

The others questions work just fine, this questions seems to be the only issue in here.

**Comment by Jackenmen** [comment]
This will be fixed by #5540.
