### ISSUE TITLE
Social Media Command

### ISSUE THREAD

**Issue by jliby** [Cog-Creators/Red-DiscordBot#5558]
### Type of feature request

Cog, Command

### Description of the feature you're suggesting

I am curious to know if I can add a cogg that will manage the social media for a particular server. I am thinking of a discord bot that will return the social media account of a specified user.

**Comment by Kowlin** [comment]
Hey there, these issues are only for issues related to Red's code and its internal systems. If you require support regarding Red you're welcome to join [our Discord server](https://discord.gg/red). Also I suggest you check out the [cog index](https://index.discord.red/) to see if someone has already created something similar as you requested.
