### ISSUE TITLE
Add support for asynchronous `Cog.cog_unload`

### ISSUE THREAD

**Issue by phenom4n4n** [Cog-Creators/Red-DiscordBot#5560]
### What component of Red (cog, command, API) would you like to see improvements on?

Cog

### Describe the enhancement you're suggesting.

Currently, the `Cog.cog_unload` method is synchronous. If a cog has asynchronous cleanup to do, it must create a task to do so. Creating a task does not guarantee the execution or completion before other shutdown tasks take place, such as Config driver teardown. It would be nice to be able to guarantee the completion and support of asynchronous code in the `Cog.cog_unload` method.

Since this requires modification of the discord.py library, this enhancement is targeted for 3.5. If there are concerns over such a change breaking existing `cog_unload` definitions, it could support asynchronous and synchronous calls by "maybe awaiting" it. However, many breaking changes are expected in the 3.5 release, so I don't think this is a major concern.

### Anything else?

Just as the setup function of an extension has a 30-second timeout, a timeout should also be implemented for an asynchronous `Cog.cog_unload` function, as it is meant to be an infallible finalizer.

**Comment by Flame442** [comment]
`teardown` (the extension removal equivalent to `setup`) is now async in dpy 2.0. Does this suffice to solve this issue for you?
<https://discordpy.readthedocs.io/en/latest/ext/commands/extensions.html?highlight=setup#id2>

**Comment by phenom4n4n** [comment]
Yeah, in 2.0 Cog.cog m_unload can be a coroutine now.
