### ISSUE TITLE
Scheduled youtube streams that existed before using "[p]streamalert youtube" do not get tracked or notified about

### ISSUE THREAD

**Issue by Nogooduser** [Cog-Creators/Red-DiscordBot#5562]
### What Red version are you using?

3.4.16

### Cog name

Streams

### Command name

streamalert youtube

### What did you expect to happen?

All livestreams in the youtube channels added by the command should be properly tracked and alerts should be sent out.

### What actually happened?

After using ``[p]streamalert youtube <channel>`` on multiple youtube channels, I discovered that any scheduled streams those channels had *prior* to me running that command did not get tracked, so no notifications were sent when those streams went live either.

### How can we reproduce this error?

1. Schedule a youtube stream on a channel
2. Run ``[p]streamalert youtube <channel>`` to track the channel
3. Begin streaming that scheduled stream

The bot won't send out any kind of notification.

### Anything else?

There is nothing in the logs indicating an error is occurring. The bot just simply doesn't seem to be tracking anything that exists before the command is run.

**Comment by Jevon64** [comment]
Currently looking into this with matcha19! Has this been addressed in any recent changes?

**Comment by Jevon64** [comment]
Can you provide us with more details about this bug? What system and os are you using? Were you able to reproduce this bug multiple times? I have tried it several times on my system (Windows 11) and was not able to produce the error.

**Comment by Mister-42** [comment]
Can you check it the channel was still monitored? If not, it might be related to #5343

**Comment by NOUR277272** [comment]
It is fixed now, but thanks for trying.
