### ISSUE TITLE
RPC decorator for adding rpc handlers

### ISSUE THREAD

**Issue by npc203** [Cog-Creators/Red-DiscordBot#5575]
### What component of Red (cog, command, API) would you like to see improvements on?

RPC

### Describe the enhancement you're suggesting.

RPC methods are registered manually as of now when a cog is loaded. I'd like propose a decorator similar to `commands` in dpy, to add RPC methods when a cog is loaded. Something on the lines of `@rpc_method` which would register the method.

![image](https://user-images.githubusercontent.com/50765275/154030499-cca3f70d-83c7-4670-8c4b-f701f07928c9.png)

Just a quality of life feature.

### Anything else?

One way I could see this done is, adding an attribute to the function which is wrapped.
```py
def rpc_method(func):
    """
    Decorator for RPC methods
    """
    func.rpc_method = True
    return func
```

then whenever a cog is loaded, one could loop around the methods perhaps?
somwhere on the lines of
```python
for name, method in inspect.getmembers(cog, predicate=inspect.ismethod):
            if getattr(method, "rpc_method", None) is True:
                self.bot.register_rpc_handler(method)
```

**Comment by Jackenmen** [comment]
RPC is effectively frozen until we decide on a different solution to replace it with so we're not interested in adding new functionality to it. We may reconsider this feature once we decide on and move to a new solution.
