### ISSUE TITLE
Formatting utils escapes if nested

### ISSUE THREAD

**Issue by PredaaA** [Cog-Creators/Red-DiscordBot#5581]
### What Red version are you using?

dev

### What were you trying to do?

Just running help.

### What did you expect to happen?

No escaping.

### What actually happened?

Text being escaped while it should not. Seems to be related off #5435.
![image](https://user-images.githubusercontent.com/46051820/154867635-d214fa16-0a01-437e-a9ff-21999c33b639.png)
![image](https://user-images.githubusercontent.com/46051820/154867637-5a5fc412-7797-471f-8829-2f6d7bfcc2da.png)

### How can we reproduce this error?

Run any command that uses the formatters edited in the said PR.

**Comment by Flame442** [comment]
Nesting two formatters (IE `bold(underline(text))`) causes the inner one to be "undone" by the outer one's automatic escaping of any formatting characters. #5435 replaced many literal `**__{text}__**`s with these formatter functions, which broke the formatting.

This issue only affects dev right now, however it should be fixed before the next release.
