### ISSUE TITLE
Please get in touch with me

### ISSUE THREAD

**Issue by Sparkzzzzzz** [Cog-Creators/Red-DiscordBot#5595]
Hi there Aikaterna (and the red community), I wanted to let you know that I really need red's help at this point and this is the only way to contact you, I was foolish and got banned from the support server for dm advertising about 5 months ago and all my alts (another dumb mistake) were also banned. Therefore I plead you to give me a second chance and help me improve.

Yours truly,
Sparkz.

**Comment by Jackenmen** [comment]
The Red server now accepts ban appeals:
https://forms.gle/E8STnt3Xpb1YeAuP6
![image](https://user-images.githubusercontent.com/6032823/155893240-2a80dc76-1086-4986-a005-9e2e28d14fe8.png)

**Comment by Sparkzzzzzz** [comment]
I know but I submitted 5 appeals over time but no help

**Comment by Hridaan965** [comment]
Also can you paste the link here? ill give it another shot

**Comment by Sparkzzzzzz** [comment]
> The Red server now accepts ban appeals: https://forms.gle/E8STnt3Xpb1YeAuP6 ![image](https://user-images.githubusercontent.com/6032823/155893240-2a80dc76-1086-4986-a005-9e2e28d14fe8.png)

can you send the link? ill give it another shot

**Comment by Jackenmen** [comment]
> I know but I submitted 5 appeals over time but no help

Well, this issue is certainly not helping your case ;)

> Also can you paste the link here? ill give it another shot

I've already sent it above but sure:
https://forms.gle/E8STnt3Xpb1YeAuP6

**Comment by Twentysix26** [comment]
We review all ban appeals. If you didn't get a response it simply means that your appeal was rejected. Sending more ban appeals will not get you unbanned.
