### ISSUE TITLE
Confirmation in the [p]pipinstall command.

### ISSUE THREAD

**Issue by Honkertonken** [Cog-Creators/Red-DiscordBot#5614]
### What component of Red (cog, command, API) would you like to see improvements on?

Downloader Cog.

### Describe the enhancement you're suggesting.

Having a confirmation on the ```pipinstall``` should be handy as to avoid typos and stuff. 
As mentioned in the docstring improper usage can potentially brick your bot. 

Something like this should do the trick.
![image](https://user-images.githubusercontent.com/6032823/158007096-b730e5e2-dc99-4b6c-96ab-c43ed8dda58f.png)

**Comment by Flame442** [comment]
We are not interested in this change at this time.

As `[p]pipinstall` is an owner only command, the owner could do similar things using `pip` in console, which also does not have protections. The kinds of mistakes a quick check like this would catch are typos, which would **not** break the bot as they would most likely be invalid libs. The only way to actually break the bot with this command would be to change the version of an existing lib that red depends on, however this change would not prevent that as that requires entering specific lib names.
