### ISSUE TITLE
Make `traceback` prompt if you want it to print all pages, if there's more than say 5

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#5621]
### What component of Red (cog, command, API) would you like to see improvements on?

^traceback

### Describe the enhancement you're suggesting.

Occasionally an error will have *egregiously* long text, and using `^traceback` currently is not gated in the number of messages it sends. Adding a confirmation if you want it to print, in the case that an error message is *truly* gigantic would be nice. (Recently I restarted my bot because it was printing the entire source code of a wiki page that had failed to save; I don't even know how many pages it would have been, but it just would not stop.)

### Anything else?

As a bonus, the page count could be configurable, but really I'm just looking for something covering truly outlandish edge cases here, so a quick fix hard-coding even like 15 or 20 would be fine by me.

**Comment by Flame442** [comment]
To solve this issue, I would suggest using `send_interactive` rather than `send` in the `[p]traceback` command.
