### ISSUE TITLE
Make CommandInvokeError error message customisable

### ISSUE THREAD

**Issue by PredaaA** [Cog-Creators/Red-DiscordBot#5622]
### What component of Red (cog, command, API) would you like to see improvements on?

Core

### Describe the enhancement you're suggesting.

Currently when a command errors out, it sends the following message to all users:
![image](https://user-images.githubusercontent.com/46051820/158693825-4aa8dd83-2e6f-4e4b-a368-663849bd5a52.png)

However "Check your console or logs for details." for end users doesn't make much sense, just for the bot owner(s) though it makes sense.
My suggestion would be to make this message customisable, like we do on disabled commands. And by default let that message.
Maybe some templating to send the command name, and "Check your console or logs for details." if the command invoker was the owner too.

**Comment by matcha19** [comment]
I'll be looking into implementing this feature with @jevon64. Please let me know if you would like anything else to be considered! 😃

**Comment by Flame442** [comment]
@matcha19
I would recommend against working on this particular issue at this time. This is a feature request which has not yet been accepted as something we are interested in pursuing. In particular, there are multiple considerations we would need to make before a PR could be made (what should the command name be? in what cog should it be located, or should it be in core? what specific customization should be allowed by this command?)

If you are looking for issues to help out with, any labeled with `PRs Welcome` are your best bet, though `Accepted` ones are generally also OK to work on assuming someone else has not already started work. Anything with `Needs Triage` has not been looked over by us yet, and given that our focus is currently on preparing the bot for 3.5, most likely will not be looked at in the near future.

**Comment by matcha19** [comment]
@Flame442 
Ah sounds good! We'll look at PR Welcome issues in the meantime. Thanks for letting us know.

**Comment by lakai** [comment]
Is it possible to have a setting for it to not spit out any error message at all?  It really serves no purpose for the end user.

**Comment by Jackenmen** [comment]
I think it makes no sense to not send any message at all, it's bad UX. User should always be getting some response and at the last resort (unexpected exception) it should be the error about an issue with the command.
