### ISSUE TITLE
[Cleanupset] add ability to change the global default

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#5645]
### Type of feature request

Cog

### Description of the feature you're suggesting

We have a relatively large network of related servers, and all of us preferred the default when it didn't notify, if there was an owner-restricted command to change the global default that would be awesome. Most individual server owners don't know about `cleanupset` so it's hard for us to get it disabled on every server in the network.

**Comment by Flame442** [comment]
Most command settings that can be changed per-server do not have the option to set a global default. If this were to be changed, it would need to be changed across the entire bot. We are not currently interested in adding a default just to this setting.
