### ISSUE TITLE
[Launcher] Says requirements arent installed but starts anyways

### ISSUE THREAD

**Issue by Jan200101** [Cog-Creators/Red-DiscordBot#566]
![image](https://cloud.githubusercontent.com/assets/15076013/21741932/3f49680e-d4e4-11e6-9b98-7c8a33f536c4.png)

Also I had the requirements installed and could run red without the launcher, but the launcher wanted me to redownload them over itself

**Comment by tekulvw** [comment]
do we not `try/except` on attempting to load reqs? @Twentysix26

**Comment by Twentysix26** [comment]
Couldn't reproduce this at the time and no one had this issue yet.
