### ISSUE TITLE
[Heroku] Heroku Hosting Docs

### ISSUE THREAD

**Issue by BurritoWrapped** [Cog-Creators/Red-DiscordBot#567]
Hi,
Can someone create documentation on how to host w/ heroku?

**Comment by tekulvw** [comment]
iirc Heroku doesn't allow you to store data that persists across application starts and because we have yet to move away from pure json file storage I don't know if this is possible yet

**Comment by Kowlin** [comment]
This is something I'm actively playing with. But everything boils down to the database drivers. Without those I don't think Heroku is something we can achieve

**Comment by Twentysix26** [comment]
This belongs in Red-Docs
