### ISSUE TITLE
Add command for syncing app commands

### ISSUE THREAD

**Issue by Luc1412** [Cog-Creators/Red-DiscordBot#5672]
### Type of feature request

Command

#### Cog: 
Downloder or Admin

#### Description
A command to sync the bots application commands as it’s the preferred way to sync commands. 
This command should include a guild id option for syncing a specific guilds app commands 

#### Restrictions
This command should have the same permissions as loading/unloading cogs

**Comment by Drapersniper** [comment]
> This command should have the same permissions as loading/unloading cogs

What about the use case where you'd like to allow a server owner/admin to enable/disable slash on their servers?

**Comment by Rapptz** [comment]
> What about the use case where you'd like to allow a server owner/admin to enable/disable slash on their servers?

That should be accomplished using the Discord native feature dubbed permissions v2 which will come out soon.
