### ISSUE TITLE
translate 3rd party cogs 

### ISSUE THREAD

**Issue by Zaphkeil** [Cog-Creators/Red-DiscordBot#5689]
### Type of feature request

Other

### Description of the feature you're suggesting

How do I translate 3rd party cogs

**Comment by Flame442** [comment]
For core, [translate red here.](https://translate.discord.red/)
For 3rd party cogs, you need to contact the cog creator, as the cog has to be modified in order to support translations.
In the future, questions regarding red can be asked in the [support server.](https://discord.gg/red)
