### ISSUE TITLE
"WinError 5 Access denied" on Windows

### ISSUE THREAD

**Issue by KrisDLuna** [Cog-Creators/Red-DiscordBot#569]
* Affects probably any Windows OS with UAC
* Running in Admin mode doesn't help

After the latest update, Python runs into this error when installing required libs.

> Successfully installed aiohttp-1.0.5 async-timeout-1.1.0 chardet-2.3.0 discord.py-0.16.0 imgurpython-1.1.7 multidict-2.1.4 pip-9.0.1 requests-2.12.4 websockets-3.2 youtube-dl-2017.1.8
> Exception:
> Traceback (most recent call last):
>   File "C:\Users\Joebob6778\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "C:\Users\Joebob6778\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\commands\install.py", line 423, in run
>     shutil.rmtree(target_item_dir)
>   File "C:\Users\Joebob6778\AppData\Local\Programs\Python\Python35-32\lib\shutil.py", line 488, in rmtree
>     return _rmtree_unsafe(path, onerror)
>   File "C:\Users\Joebob6778\AppData\Local\Programs\Python\Python35-32\lib\shutil.py", line 383, in _rmtree_unsafe
>     onerror(os.unlink, fullname, sys.exc_info())
>   File "C:\Users\Joebob6778\AppData\Local\Programs\Python\Python35-32\lib\shutil.py", line 381, in _rmtree_unsafe
>     os.unlink(fullname)
> PermissionError: [WinError 5] Access is denied: 'C:\Jason\Red-DiscordBot\lib\aiohttp\_websocket.cp35-win32.pyd'

So I'm assuming 'aiohttp_websocket.cp35-win32.pyd' is locked to read-only.

I was able to bypass this by editing the init.py for aiohttp though, adding this:

> import errno, os, stat, shutil
> 
> def handleRemoveReadonly(func, path, exc):
>   excvalue = exc[1]
>   if func in (os.rmdir, os.remove) and excvalue.errno == errno.EACCES:
>       os.chmod(path, stat.S_IRWXU| stat.S_IRWXG| stat.S_IRWXO)
>       func(path)
>   else:
>       raise
> 
> shutil.rmtree(filename, ignore_errors=False, onerror=handleRemoveReadonly)

Then using the Launcher to reinstall requirements (basic + audio).
So for anyone looking for a quickfix, just do what I did.
The init.py will be back to normal after reinstalling.

**Comment by palmtree5** [comment]
So I just tested and I'm not getting this error message that you got

**Comment by KrisDLuna** [comment]
Problem won't reproduce if you're already on latest version.
My 'Red-DiscordBot' installation path was in a separate drive (D:\Red-DiscordBot) too. Example shown above was from another affected user.

Other than these 2 factors... can't really think of anything else. I know I'm not the only one who has this issue though.

**Comment by Twentysix26** [comment]
Pip sets the `lib` folder read-only by default. It seems that unchecking the option and making it apply to all the files that it contains fixes the issue. Leaving this open since this is just a workaround
