### ISSUE TITLE
cannot import name '_early_init' from 'redbot'

### ISSUE THREAD

**Issue by Rprloekwirt** [Cog-Creators/Red-DiscordBot#5699]
### What Red version are you using?

3.4.5

### What were you trying to do?

Running or entering redbot-setup.

### What did you expect to happen?

I expected the bot to start up. 

### What actually happened?

![Uploading aergerga.jpg…]()

### How can we reproduce this error?

1. source ~/redenv2/bin/activate
2. redbot <instance_name>

### Anything else?

I've tried looking up the documentation or google for this error and found nothing. 

Any help is appreciated :D

**Comment by Flame442** [comment]
The current latest version of the bot is 3.4.16, so the first thing I would suggest is updating your bot. If you need more help, the proper place to ask is in [our support server](https://discord.gg/red), so feel free to ask for further support there!
