### ISSUE TITLE
Discord Invite not working

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#571]
that what it is.. SS: http://prntscr.com/dtygjl

**Comment by Jan200101** [comment]
My guess is you are talking about the red discord server so here is a temp link until it gets fixed
https://discord.gg/8NUzpKJ

**Comment by ghost** [comment]
yeah, but I can't join, the same issue... Recheck?

**Comment by Jan200101** [comment]
welp then you are probably banned or similar

**Comment by Kowlin** [comment]
Tl;dr: your banned from the server.

**Comment by ghost** [comment]
lol, just need the local thing working, but normal installation just gives http://prntscr.com/dtyjqf intresting, that nobody responses in the discord, when i talk about it, leave then try to rejoin, banned, now on gh that fast response..

**Comment by Jan200101** [comment]
you should have had patience and there is probably a reason for the ban.

**Comment by Twentysix26** [comment]
I have banned you after you left. Your attitude is not welcome. Have a nice day.
