### ISSUE TITLE
RedBot cant find any YouTube links with just "text"

### ISSUE THREAD

**Issue by GlennIgen** [Cog-Creators/Red-DiscordBot#5710]
### What Red version are you using?

3.4.16

### Cog name

Audio

### Command name

play and search

### What did you expect to happen?

When using the `[prefix]play` or `[prefix]search` command, RedBot should play or search for a Youtube link.

### What actually happened?

When using the `[prefix]play` or `[prefix]search` command, RedBot throws "Nothing Found."

### How can we reproduce this error?

1. Use command `[prefix] play SOME_TEXT`
2. Use command `[prefix] search SOME_TEXT`
3. Use command `[prefix] play SOME_URL`

### Anything else?

If you use `[prefix]play {URL}` it works just fine.

I have looked at "freyacodes/lavalink", and it looks like it's an issue for all users?
Im not sure if it is relatable: https://github.com/freyacodes/Lavalink/issues/660

**Comment by aikaterna** [comment]
The issue you linked on the Lavalink repo is relevant, and points to https://github.com/Walkyst/lavaplayer-fork/pull/50 where the fix has been PRed but still needs to be tested by the appropriate people, merged into lavaplayer, and then Lavalink needs to use it.

**Comment by GlennIgen** [comment]
> The issue you linked on the Lavalink repo is relevant, and points to [Walkyst/lavaplayer-fork#50](https://github.com/Walkyst/lavaplayer-fork/pull/50) where the fix has been PRed but still needs to be tested by the appropriate people, merged into lavaplayer, and then Lavalink needs to use it.

Allright I see, so for now, we will just need to wait and see right?
Thank you :)

**Comment by aikaterna** [comment]
Yes, everyone will need to wait until Red can use this new fix.

**Comment by GlennIgen** [comment]
Allright, thanks again. :)

**Comment by aikaterna** [comment]
I'm going to reopen this so we can keep this issue tracked and refer to it when there's a fix. Thank you for reporting it though.
