### ISSUE TITLE
Dota cog the docs don't lead to anything

### ISSUE THREAD

**Issue by whatisgh** [Cog-Creators/Red-DiscordBot#573]
The docs at https://twentysix26.github.io/Red-Docs/red_cog_dota/
didn't help since the +cog install command doesn't work, it need some repo thing, it gives me `+cog install <repo_name> <cog>`

**Comment by orels1** [comment]
Hey there @whatisgh 
You can install it with these commands:

```
+cog repo add orels1 https://github.com/orels1/ORELS-Cogs
```
```
+cog install orels1 dota
```

That should get you covered. For future support on Dota cog, you can go [here](https://discord.gg/PuStXks) in the #support_orels-cogs channel

**Comment by whatisgh** [comment]
oops i guess http://prntscr.com/dub2f6

**Comment by whatisgh** [comment]
wait should the repo be orels1 not orels in 2nd cmd?

**Comment by whatisgh** [comment]
yep, that worked http://prntscr.com/dub308
