### ISSUE TITLE
Not able to set game

### ISSUE THREAD

**Issue by sethwv** [Cog-Creators/Red-DiscordBot#577]
When I attempt to use the command `set game` it gives the following error message `Error in command 'set game' - AttributeError: '<class '__main__.Bot'>' object has no attribute 'change_presence'`

**Comment by Kowlin** [comment]
Update both your bot and the requirements, either by the launcher or by update.bat. (in case of windows)

**Comment by sethwv** [comment]
The launcher meaning pi.sh?

**Comment by Kowlin** [comment]
Run the following commands in the bot folder,
``git stash``
``git pull``
``sudo pip3 install -U -r requirements.txt``

**Comment by sethwv** [comment]
Thanks!
