### ISSUE TITLE
"That command is not available in DMs.", what does this means?

### ISSUE THREAD

**Issue by HighwayStar54** [Cog-Creators/Red-DiscordBot#578]
I tried to play a song using `!play voodoo chile` but I got this in return: `That command is not available in DMs.`.
How can I get my blt playing songs? How do I fix this?

**Comment by Chovin** [comment]
![image](https://cloud.githubusercontent.com/assets/17536161/21961656/328fc0ae-db5b-11e6-8e5b-89565dff7c3f.png)
DM stands for Direct Message
You cannot issue that command to the bot through one.
Go to a server you both share, join a voice channel, and issue the command from a text channel there
for further questions, please go to our [support server](https://discord.gg/0k4npTwMvTpv9wrh)
