### ISSUE TITLE
Allow discord.ClientUser or discord.BaseUser for Config.user

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#5790]
### What component of Red (cog, command, API) would you like to see improvements on?

API: [Config](https://cs.github.com/Cog-Creators/Red-DiscordBot/blob/ae80e62a1359b4f9f4ef1fd4290bd8a383f4b74c/redbot/core/config.py#L593)

### Describe the enhancement you're suggesting.

Currently, the method [`Config.user`](https://cs.github.com/Cog-Creators/Red-DiscordBot/blob/ae80e62a1359b4f9f4ef1fd4290bd8a383f4b74c/redbot/core/config.py#L1090)'s typehint only allow [`discord.User`](https://github.com/Rapptz/discord.py/blob/v1.7.3/discord/user.py#L679), but it may be common for certain developers to use Red's user instance when calling [`Config.user`](https://cs.github.com/Cog-Creators/Red-DiscordBot/blob/ae80e62a1359b4f9f4ef1fd4290bd8a383f4b74c/redbot/core/config.py#L1090), it is my case, but doing `self.bot.user` (Where `self.bot` is a [`redbot.bot.Red`](https://github.com/Cog-Creators/Red-DiscordBot/blob/ae80e62a1359b4f9f4ef1fd4290bd8a383f4b74c/redbot/core/bot.py#L86) instance) will return a [`discord.ClientUser`](https://github.com/Rapptz/discord.py/blob/v1.7.3/discord/user.py#L279), which does not inherit from [`discord.User`](https://github.com/Rapptz/discord.py/blob/v1.7.3/discord/user.py#L679).

Here is my proposal:
1. Change the `user`'s typehint of `Config.user` to: `discord.BaseUser` (Which is both implemented by `discord.User` and `discord.ClientUser`, and that [contains the user's ID](https://github.com/Rapptz/discord.py/blob/462ba84809f43349296c44cbe6468f631a00edab/discord/user.py#L87))
2. Change the `user`'s typehint of `Config.user` to: `typing.Union[discord.User, discord.ClientUser]`

Both solution shouldn't introduce any breaking changes. I can drop a PR ASAP if you are okay with such modification.

### Anything else?

Here is a live action of the issue:
![image](https://user-images.githubusercontent.com/61093863/176991967-b08fe887-b8b8-4ee8-9043-e1da22f6383d.png)

Alternative: Adding `# type: ignore` at the end of the affected line

**Comment by Jackenmen** [comment]
The type hint is `discord.abc.User` so it accepts all user types. The docstring uses discord.User so that could be fixed.

The screenshotted error is about you trying to pass a variable that might be None, not because of you trying to pass ClientUser.

**Comment by madebylydia** [comment]
My bad on that one, I just paid too much attention to the docstring and VSC... Damn me.
![image](https://user-images.githubusercontent.com/61093863/177005924-bf15d69e-823f-4b6e-b3e4-e6e8b2d95628.png)
I'll correct the docstring at least... Sorry for the wrong infos 😰
