### ISSUE TITLE
Add a `--unload-cog [UNLOAD_COGS...]` cli flag 

### ISSUE THREAD

**Issue by japandotorg** [Cog-Creators/Red-DiscordBot#5796]
### Type of feature request

Other

### Description of the feature you're suggesting

Adds a way to unload a cog when starting red using the cli - `--unload-cog [UNLOAD_COGS...]`
Kinda similar to `--load-cogs [LOAD_COGS...]` but does the opposite, instead of loading the cogs, it unloads the specified cog.

### Anything else?

So I was having some issues lately with a third party cog which was not letting my bot start and was crashing it on boot, and it was impossible to unload that single cog before starting up the bot, and it's hard to remember what cogs I have loaded at times, and using the `--no-cogs` flag just starts the bot without any cog being loaded on start. It'll be really convenient to have a cli option to unload one or more cogs at boot if some cog is causing the bot to not boot up or similar issue to what I've faced in the past.

**Comment by AAA3A-AAA3A** [comment]
Hello @japandotorg ,
The PR that implements the idea you proposed in this issue (#5802) has been merged a few hours ago. This new feature will be in Red 3.5 when this version is released.
Thanks for the idea that made me a Red contributor with my first merged PR!
AAA3A

**Comment by Jackenmen** [comment]
Oh yeah, this is resolved by #5802 now, didn't realize that an auto-close keyword wasn't used in that PR's description.

**Comment by japandotorg** [comment]
> Hello @japandotorg ,
> The PR that implements the idea you proposed in this issue (#5802) has been merged a few hours ago. This new feature will be in Red 3.5 when this version is released.
> Thanks for the idea that made me a Red contributor with my first merged PR!
> AAA3A

😄 Tysm for the contribution and also because I kinda needed this PR to happen. 💖
