### ISSUE TITLE
Add optional timer to `[p]audioset dc`

### ISSUE THREAD

**Issue by w-biggs** [Cog-Creators/Red-DiscordBot#5801]
### What component of Red (cog, command, API) would you like to see improvements on?

Audio

### Describe the enhancement you're suggesting.

`[p]audioset emptydisconnect` has a timer setting, but a timer setting for plain old `[p]audioset dc` would be very useful as well to add a buffer before the bot disconnects post-queue. It can be a bit jarring for the bot to leave immediately after the queue ends.

**Comment by Flame442** [comment]
Duplicate of #5350.
