### ISSUE TITLE
[Audio] RLL mishandling of connection state

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#5804]
### What Red version are you using?

3.4.17

### Cog name

Audio

### Command name

llset external or llset wsport (automatically toggles external)

### What did you expect to happen?

I expected the bot to toggle audio to external Lavalink connections without issues.

### What actually happened?

The bot started heartbeating after a period of nonresponsiveness to commands after using [p]llset external.

### How can we reproduce this error?

1) have a Red that has an internally managed Lavalink server (default)
2) be using Red-Lavalink 0.9.3
3) let the bot start up all the way, load the Lavalink process, and then connect to it
4) use [p]llset external
5) try [p]ping, it will be blocked, and there will eventually be heartbeat messages

### Anything else?

I am making a PR to RLL to try to address this but I am not sure if my approach will be correct or if it's the best approach for this issue. In short, the node closing is overlapping with the connection attempt to the external server. It might be better to harden the _multi_try_connect or the connection function path and change the situation where a node tries a reconnect on a closed/shutdown node, and not prompt reconnecting in the first place in that case.

**Comment by aikaterna** [comment]
Resolved by https://github.com/Cog-Creators/Red-Lavalink/pull/131

**Comment by Jackenmen** [comment]
This has been fixed in Red 3.4.18.
