### ISSUE TITLE
[Core] Add a possible way to remove multiple paths with `[p]removepath`.

### ISSUE THREAD

**Issue by ltzmax** [Cog-Creators/Red-DiscordBot#5820]
### Type of feature request

Command

### Description of the feature you're suggesting

Currently you can only remove one path with `[p]removepath`, it would be great if you could remove multiple ones at once instead of having to redo the command multiple times, Let me add a small example here, if someone has 10 paths and wants to remove 5 of them, They might want them all at once. So a possible way would be great there.

### Anything else?

No.

**Comment by Kreusada** [comment]
Whilst I'm not exactly opposed to this idea, I don't think removing paths is a frequent practice. If there are a few paths that wish to be removed, it wouldn't cause harm to re-use the command until all the necessary paths have been removed. Considering the use of the command to this extent isn't common, it questions whether the change would actually be necessary. I guess it wouldn't hurt to implement a fitting change though.

**Comment by madebylydia** [comment]
@Flame442 Can you assign me to this issue? I'll take it :)
