### ISSUE TITLE
Permissions error on lib directory.

### ISSUE THREAD

**Issue by nanotoast** [Cog-Creators/Red-DiscordBot#583]
I'm trying to install dependencies and running in to a permissions error.  It seems the script (or pip) is setting permissions on the /Red-DiscordBot/lib directory to 0200:
```
redbot@toastnation:~/Red-DiscordBot$ stat lib/
  File: 'lib/'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d	Inode: 1931276     Links: 22
Access: (0200/d-w-------)  Uid: ( 1007/  redbot)   Gid: ( 1007/  redbot)
```
I've manually set permissions to the lib directory for read/write access, and it will revert back to 0200 as soon as I run option 1.

This seems to be the same or a similar error as referenced in issue #569, but I'm running the latest version and it's still erroring.

Running on Linux Ubuntu 16.04
Full log of error during requirements install:
[http://pastebin.com/GYGPydYh](http://pastebin.com/GYGPydYh)

**Comment by Twentysix26** [comment]
[Should be ok now](https://github.com/Twentysix26/Red-DiscordBot/commit/7eabe70db54c3bf99889f04bca205d388e0d755b). Try to update Red (restart the launcher afterwards) and try the requirements installation again.
