### ISSUE TITLE
Use GZip/Brotli compression for writes on the JSON driver

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#5835]
### What component of Red (cog, command, API) would you like to see improvements on?

Config

### Describe the enhancement you're suggesting.

We will have access to Brotli with Red 3.5, and GZip is part of the stdlib; currently, the biggest drawback of JSON is its write performance - We already introduced, https://github.com/Cog-Creators/Red-DiscordBot/pull/2921, which significantly reduces the JSON file size.

The next enhancement in this area can be done by compressing these files - The `_load_data` method is only called once per Config initialization, meaning we would only decompress the data once per file and on every write OP.

There will be some overhead added by compressing the data on every write, but on local testing, this was negligible.

The benefit of the compression here is further reducing the file sizes, which should both increase disk longevity and improved write performance.

It will make manual editing of these files even more difficult. However, manually editing these files is not supported (and can be done via an online decompressor or locally.)

File which will require changes:
https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/core/drivers/json.py

# Brotli
Local testing reduced the file sizes by  more than 300%

```diff
...
+ import brotli

...
    def _load_data(self):
        if self.cog_name not in _driver_counts:
            _driver_counts[self.cog_name] = 0
        _driver_counts[self.cog_name] += 1

        _finalizers.append(weakref.finalize(self, finalize_driver, self.cog_name))

        if self.data is not None:
            return

        try:
-            with self.data_path.open("r", encoding="utf-8") as fs:
-                self.data = json.load(fs)
+            with self.data_path.open("rb", encoding="utf-8") as fs:
+                self.data = json.loads(brotli.decompress(fs.read()))
        except FileNotFoundError:
            self.data = {}
-            with self.data_path.open("w", encoding="utf-8") as fs:
-                json.dump(self.data, fs)
+            with self.data_path.open("wb", encoding="utf-8") as fs:
+                fs.write(brotli.compress(json.dumps(data).encode("utf-8")))

...

def _save_json(path: Path, data: Dict[str, Any]) -> None:
    filename = path.stem
    tmp_file = "{}-{}.tmp".format(filename, uuid4().fields[0])
    tmp_path = path.parent / tmp_file
-    with tmp_path.open(encoding="utf-8", mode="w") as fs:
-        json.dump(data, fs)
+    with tmp_path.open(encoding="utf-8", mode="bw") as fs:
+        fs.write(brotli.compress(json.dumps(data).encode("utf-8")))
        fs.flush()  # This does get closed on context exit, ...
        os.fsync(fs.fileno())  # but that needs to happen prior to this line

    tmp_path.replace(path)

    try:
        flag = os.O_DIRECTORY  # pylint: disable=no-member
    except AttributeError:
        pass
    else:
        fd = os.open(path.parent, flag)
        try:
            os.fsync(fd)
        finally:
            os.close(fd)
...
```
# GZip

Local testing reduced the file sizes by about 300%

```diff
...
+ import gzip
...

    def _load_data(self):
        if self.cog_name not in _driver_counts:
            _driver_counts[self.cog_name] = 0
        _driver_counts[self.cog_name] += 1

        _finalizers.append(weakref.finalize(self, finalize_driver, self.cog_name))

        if self.data is not None:
            return

        try:
-            with self.data_path.open("r", encoding="utf-8") as fs:
-                self.data = json.load(fs)
+            with self.data_path.open("rb", encoding="utf-8") as fs:
+                self.data = json.loads(gzip.decompress(fs.read()))
        except FileNotFoundError:
            self.data = {}
-            with self.data_path.open("w", encoding="utf-8") as fs:
-                json.dump(self.data, fs)
+            with self.data_path.open("wb", encoding="utf-8") as fs:
+                with gzip.GzipFile(fileobj=bio, mode="wb", compresslevel=9) as gfile:
+                    json.dump(self.data, gfile)

...

def _save_json(path: Path, data: Dict[str, Any]) -> None:
    filename = path.stem
    tmp_file = "{}-{}.tmp".format(filename, uuid4().fields[0])
    tmp_path = path.parent / tmp_file
-    with tmp_path.open(encoding="utf-8", mode="w") as fs:
-        json.dump(data, fs)
+    with tmp_path.open(encoding="utf-8", mode="wb") as fs:
+        with gzip.GzipFile(fileobj=bio, mode="wb", compresslevel=9) as gfile:
+            json.dump(data, gfile)
        fs.flush()  # This does get closed on context exit, ...
        os.fsync(fs.fileno())  # but that needs to happen prior to this line

    tmp_path.replace(path)

    try:
        flag = os.O_DIRECTORY  # pylint: disable=no-member
    except AttributeError:
        pass
    else:
        fd = os.open(path.parent, flag)
        try:
            os.fsync(fd)
        finally:
            os.close(fd)
...
```

**Comment by Drapersniper** [comment]
Note to @jack1142  from @kowlin 
- Look into async GZip/Brotli to reduce the potential load for the compressing/decompressing

Edit: There is a lot of context missing from this, the goal behind looking into an async decompression system is due the fact that if we can reduce the amount of time we take to load stuff into RAM. The less time we will deal with blocking heartbeats on the higher end of load times. And if we can make the decompression asynchronous this will mean that we possible end up with a **vastly** lower timer where we block heartbeats.  ~~Kowlin

**Comment by aikaterna** [comment]
While I can definitely appreciate this issue being opened, (I'm one of the people that would directly benefit from this as one of my bot's core data files is approximately 45mb) we voted to shelve this one for now. Even though this is being closed it doesn't mean it won't be considered in the future... but it won't be considered for work at this moment. Some folks were interested in seeing this implemented as a non-default option for the JSON driver so that a bot owner could turn it on if they are in the "very large" bot range, like hundreds of thousands of users with nicknames being tracked or something of that nature.
