### ISSUE TITLE
Cleanup command doesn't work in Voice Channel attached Text Channels

### ISSUE THREAD

**Issue by RMednis** [Cog-Creators/Red-DiscordBot#5858]
### What Red version are you using?

3.4.18

### Cog name

Cleanup

### Command name

cleanup

### What did you expect to happen?

Messages in a text channel attached to a voice channel to be deleted.

### What actually happened?

Messages remained, running `cleanup after <messageid>` throws an error with an exception:

```python 
Exception in command 'cleanup after'
Traceback (most recent call last):
  File "/home/user/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/user/redenv/lib/python3.9/site-packages/redbot/cogs/cleanup/cleanup.py", line 328, in after
    after = await channel.fetch_message(message_id)
AttributeError: 'VoiceChannel' object has no attribute 'fetch_message'
```

### How can we reproduce this error?

Do the following steps:
1. Create a voice channel
2. Select `Open Chat` in the ui
3. Type a message
4. Try to clean up the channel

### Anything else?

This seems to affect all the cleanup related commands. Even the regular .cleanup command doesn't return a help response.

The exception is only visible when running `cleanup after` however.

**Comment by Flame442** [comment]
The bot as a whole currently does not support text in voice channels or threads, as the current version of dpy used by the bot does not support these features. These will be supported in 3.5.
