### ISSUE TITLE
Audio Cog

### ISSUE THREAD

**Issue by hzumbru1** [Cog-Creators/Red-DiscordBot#586]
Whenever I run the bot 11/12 cogs are running. The audio cog will not run. Any suggestions?

**Comment by Twentysix26** [comment]
[Load it](https://twentysix26.github.io/Red-Docs/red_getting_started/)

**Comment by hzumbru1** [comment]
How would I go about that?

**Comment by Twentysix26** [comment]
By clicking on my previous message 👍

**Comment by hzumbru1** [comment]
Thank you so much! I did not see that the first time reading over. Greta bot btw!

**Comment by Twentysix26** [comment]
Thanks, no problem
