### ISSUE TITLE
Hybrid Commands fail to assign to guild only

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#5877]
Currently we have this weird issue of Hybrid commands failing to bind to a guild when ``guild_ids`` is passed in the Decorator of a hybrid command.

**Comment by TrustyJAID** [comment]
After doing some more looking it appears this is intended upstream. HybridGroups parse the guild_ids kwarg but HybridCommands themselves do not and require the decorator if it's a standalone command.
