### ISSUE TITLE
Internal Lavalink jar shutdown unexpectedly

### ISSUE THREAD

**Issue by Johnnycyan** [Cog-Creators/Red-DiscordBot#5882]
### What Red version are you using?

3.4.18

### What were you trying to do?

Load audio cog

### What did you expect to happen?

The audio cog to load and start Lavalink server

### What actually happened?

The lavalink server crashes and constantly loops trying to restart again
[hs_err_pid46396.log](https://github.com/Cog-Creators/Red-DiscordBot/files/9795862/hs_err_pid46396.log)

### How can we reproduce this error?

Pretty sure it's a system issue but not sure how. It was working in the past but all of a sudden stopped working.

**Comment by aikaterna** [comment]
Hi there, can you join us on the Discord support server at discord.gg/red ? I'd like to walk you through trying some alternative things and seeing if they help your situation. Please feel free to ping aikaterna the Discord user when you get there.

**Comment by aikaterna** [comment]
We spoke in the support channel and apparently this isn't happening any more. I suspect Red could benefit from some of the udpqueue updates that are present in later Lavalink versions, but without this being a repeating issue it's hard to test. Closing this for now.
