### ISSUE TITLE
Cleverbot error fix missing an underscore?

### ISSUE THREAD

**Issue by pewbaldpew** [Cog-Creators/Red-DiscordBot#589]
https://gyazo.com/251a5e334f059ff42d0257f0c25a3379 - taken from someone in support.

Someone was confused by this and I'm sure other people would be too.

https://gyazo.com/52521fc0643fce510333c100ea04f1b4

**Comment by Twentysix26** [comment]
The underscore is there if you copy and paste. It doesn't show on discord, the css for code lines cuts it out. Anyway, wrong repo
