### ISSUE TITLE
Add some way to recover when someone forgets what they set their server prefix to

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#5891]
### What component of Red (cog, command, API) would you like to see improvements on?

Core

### Describe the enhancement you're suggesting.

Currently, it's possible to "lock yourself out" in a server if you set a server prefix and forget it. Global prefixes won't work, in best case the bot owner has enabled `--mentionable` and you can use mention prefix in the server but if the bot owner did not do that then you don't really have any good way of finding out what the prefix is, setting it to something else or resetting it. To alleviate this problem, at least one of those things needs to be possible.

Potential options are:
- adding `[guild]` parameter to `[p]set showsettings` command which could be used in DMs to get server's settings (including server prefix) without knowing the server prefix
- adding a new command for reseting server prefix from DMs (e.g. `[p]set serverprefix reset <guild>`)
- adding (or changing existing) command for setting server prefix from DMs

**Comment by leetfin** [comment]
Huh, I always thought mentionable commands were on by default. Maybe make a recovery command that's always mentionable similar to how licenseinfo will be under #5865?

**Comment by Flame442** [comment]
We've decided to go with:
- Modify `[p]set showsettings` to accept an **optional** `[guild]` parameter.
- Modify `[p]set serverprefix` to have a **`typing.Optional`** `[guild]` parameter _before_ the prefix(es).

**Comment by AntonioNarra** [comment]
Hi. I plan on working on this.

**Comment by AntonioNarra** [comment]
> We've decided to go with:
> 
> * Modify `[p]set showsettings` to accept an **optional** `[guild]` parameter.
> * Modify `[p]set serverprefix` to have a **`typing.Optional`** `[guild]` parameter _before_ the prefix(es).

`[p]set serverprefix`  is currently a guild only command. Should this be changed so that it works in both guilds and DMs?

**Comment by Jackenmen** [comment]
Yes.
