### ISSUE TITLE
https://lmgtfy.app is broken, which breaks lmgtfy command use

### ISSUE THREAD

**Issue by ase1590** [Cog-Creators/Red-DiscordBot#5908]
### What Red version are you using?

3.4.18

### Cog name

General

### Command name

lmgtfy

### What did you expect to happen?

The site to work

### What actually happened?

https://lmgtfy.app seems to be dead.

any attempts to fill in info in the site, then pull actual results yields a blank webpage, with what appears to be an update to CSP killing the site, as it seems to be entirely unmaintained. This makes it no longer useful to hit repetitive questions with the lmgtfy command in Red, as the site itself is now broken due to browser content security policy in Chrome based browsers. The site has been in this state for what seems to be months now, and is unlikely to be fixed. 

### How can we reproduce this error?

1. go to https://lmgtfy.app
2. try to pull any google results from it
3. site comes up blank

**Comment by Flame442** [comment]
Site appears to be working fine for me, may have been a brief blip or could be that it's blocked in your region. Can you double check if it's still down for you right now?

Edit: Read the issue closer, it's the *search contents* that don't work. Missed that part. Yep, seems like this is an issue.

**Comment by Flame442** [comment]
Seems like `https://letmegooglethat.com/?q=` may be a valid replacement for this?

**Comment by ase1590** [comment]
That one works for me!
I'm not picky on what the replacement should be, but thought I should point out the original site had died and is unmaintained :)

**Comment by japandotorg** [comment]
`https://letmegooglethat.com/?q=` site seems to be working for me as well, looks like a perfect replacement.

**Comment by Ryan5453** [comment]
lmgtfy.app continues to work if you additionally provide the `s` parameter with the value `g`

Example: `https://lmgtfy.app/?q=Red-DiscordBot` does not work
Example: `https://lmgtfy.app/?q=Red-DiscordBot&s=g` does work

**Comment by Jackenmen** [comment]
> lmgtfy.app continues to work if you additionally provide the `s` parameter with the value `g`

Let's go with that then.

**Comment by ase1590** [comment]
I'd like to add on here that the site is basically unreachable now, as the SSL cert expired some time back and due to HSTS, one can no longer connect to the site, rendering it effectively dead.

**Comment by Flame442** [comment]
#6255 is the original place that problem was brought up, which was recently superseded by #6268 so we could have an in-house solution that won't break like the others. That fix that will be included in the next release.
