### ISSUE TITLE
[suggestion] adding build support for git repos of python modules

### ISSUE THREAD

**Issue by Jan200101** [Cog-Creators/Red-DiscordBot#595]
title should give all the info you need

a module repo affected by this is https://github.com/Holiverh/python-valve as it doesnt have a up to date pip (because its not made my the author)

**Comment by Jan200101** [comment]
Right now its throwing this Error when adding a git+[github link] to the requirements field
http://i.imgur.com/PyaOALu.jpg

**Comment by Jan200101** [comment]
Traceback
http://i.imgur.com/p4J61NB.jpg

**Comment by tekulvw** [comment]
Should be fixed with #786 probably won't be implemented in V2

**Comment by Kowlin** [comment]
Fixed with #786 (v3), not implemented in v2.
