### ISSUE TITLE
Error in documentation example

### ISSUE THREAD

**Issue by grievertime** [Cog-Creators/Red-DiscordBot#5966]
### What Red version are you using?

3.4.5

### What were you trying to do?

run the example under "Basic Usage" at [https://docs.discord.red/en/stable/framework_modlog.html](https://docs.discord.red/en/stable/framework_modlog.html)

### What did you expect to happen?

Run the example

### What actually happened?

Error enabling the COG due to missing "checks"

### How can we reproduce this error?

ND

### Anything else?

the first import should be `from redbot.core import commands, modlog, checks
` instead of `from redbot.core import commands, modlog
`

**Comment by Kreusada** [comment]
This has been fixed in #5463

**Comment by Flame442** [comment]
Just to point it out, the latest version of Red is 3.4.18. You should probably follow [these instructions](https://docs.discord.red/en/stable/update_red.html) and update your bot to that version.
