### ISSUE TITLE
Cannot run on Debian 8.

### ISSUE THREAD

**Issue by itsacorn** [Cog-Creators/Red-DiscordBot#597]
Hi, i cannot run Red on Debian 8. I runned the install script, it ran without errors, but now, when i do run python3 red.py it says:

discordbot@shutteddown:~/Red-DiscordBot$ python3 red.py
  File "red.py", line 79
    async def send_message(self, *args, **kwargs):
            ^
SyntaxError: invalid syntax
discordbot@shutteddown:~/Red-DiscordBot$

Dont tell me to get python3.5, as python3 is the latest on Debian and it automatically installs 3.5 even though it doesnt mention it in the name.

**Comment by Twentysix26** [comment]
You're not running python3.5

**Comment by itsacorn** [comment]
The installer ran without errors, when i tried with Python3.2, it said it didnt have 3.5, but when i ran python3 it shown no errors, so it must be 3.5

**Comment by Twentysix26** [comment]
Running `python3 --version` will tell you otherwise

**Comment by itsacorn** [comment]
3.4.2. how do i install 3.5 on debian?

**Comment by NekoTony** [comment]
Google

**Comment by Twentysix26** [comment]
I'm not sure myself. I didn't make the guide and never installed on Debian. You should be able to find some resources on how to do it

**Comment by Jan200101** [comment]
debian doesnt have it so add it from another Linux distro and make Frankendebian or build it from source

**Comment by itsacorn** [comment]
How do i install Discord.py?

**Comment by Twentysix26** [comment]
Use the launcher

**Comment by itsacorn** [comment]
I fixed it and it runs. I set ? as my prefix, but it doesnt show anything when i enter ?help in my group. I added the bot

**Comment by itsacorn** [comment]
Oh i seen it it sends in private message. Can i change that?

**Comment by Twentysix26** [comment]
No, it sends excessively long help messages in DM to keep public chats clean.

**Comment by itsacorn** [comment]
Is it possible to add a custom Playing... subtitle to the bot?

**Comment by Twentysix26** [comment]
`[p]set`  
For further questions feel free to join our [server](https://discord.gg/0k4npTwMvTpv9wrh)
