### ISSUE TITLE
Remove the colors in Installed Cogs list

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#6003]
### What component of Red (cog, command, API) would you like to see improvements on?

cog list

### Describe the enhancement you're suggesting.

To me, it is very confusing that "Installed" is red and "Uninstalled" is green. I would suggest removing the syntax highlighting from this menu altogether.

Example screenshot:

![image](https://user-images.githubusercontent.com/18037011/227386917-1170b7ca-0c5c-4a2a-8895-f6969c8c7d4b.png)

This implies to me that the things in red are things that I do not have available to me. But, maybe I'm calling up this list to see "what's installed and ready to use" as opposed to "what's ready to be installed." In that case, the color-coding is completely backwards.

In fact, even when I am pulling this cog up because I want to install something, I get confused, because to me green should be "already installed and good to go."

### Anything else?

1. This suggestion applies to every similar interface where the diff color coding is used but the POV could be considered in either direction, "what's available to use" or "what's available to install" when the command is called
2. There is a typo in this command (Available cog: -> Available cogs)

**Comment by Flame442** [comment]
> There is a typo in this command (Available cog: -> Available cogs)

There is only 1 cog in that section, hence "cog" not "cogs". It has dynamic plurality.

**Comment by RheingoldRiver** [comment]
Ah, makes sense

**Comment by rramboer** [comment]
No styling:
![image](https://user-images.githubusercontent.com/73763472/232599819-ce48da43-00a3-43a7-899d-cf6f727cf0ca.png)

'fix':
![image](https://user-images.githubusercontent.com/73763472/232599875-b7d729a2-4836-407f-b961-49ef28f853bc.png)

'yaml':
![image](https://user-images.githubusercontent.com/73763472/232599940-78fdc687-6372-467d-ba73-fd4d85c78dd8.png)

'markdown':
![image](https://user-images.githubusercontent.com/73763472/232600535-1dc5df64-bc58-449b-8ae0-dcb7bcdc33c9.png)

**Comment by RheingoldRiver** [comment]
Markdown does look pretty nice. But if you feel strongly another way, my opinion on this isn't that important. I mostly just wanted a change from diff.

Thanks a lot for making this change!!

**Comment by rramboer** [comment]
I changed it to markdown

**Comment by Drapersniper** [comment]
I think Yaml provides a good contrast between package name and cog description, as well as a diff colour for the +- symbols which was the goal of the diff code block here

**Comment by hollowstrawberry** [comment]
I do like yaml in this case

**Comment by Jackenmen** [comment]
I'd go with Markdown, YAML is more likely to get problematic with some cog descriptions and it's IMO a bit too colorful. We might want to change the style of this entirely in the future but for now I'd like something that doesn't look as jarring as the `diff` style.

@rramboer are you still interested in making a PR for this? It seems that your PR got closed after you removed your fork.

**Comment by rramboer** [comment]
I can make a PR. Give me 48 hours to get back home.
