### ISSUE TITLE
Systemd tutorial could be using user services instead of requiring root permissions

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#6009]
### What component of Red (cog, command, API) would you like to see improvements on?

Docs

### Describe the enhancement you're suggesting.

Just a simple thought, right now Red can be installed without root permissions on most systems, except for the fact that the `systemd` tutorial uses system services (located in `/etc/systemd/system`).

It is possible to make this work without sudo by installing the files in `$HOME/.config/systemd/user` instead, and then using `systemctl/journalctl --user`. These are referred as user services, as opposed to system services.

You can read more about these in [the ArchWiki](https://wiki.archlinux.org/title/systemd/User).

### Anything else?

If you're ok with the change I can PR this, it's nothing too complicated. I just prefer to open an issue first and discuss about it, see if this is wanted.

**Comment by palmtree5** [comment]
I'm inclined to agree with something Jack said in Discord related to this:

> enable-linger requires root permissions
> And without it, user service isn't really good for this use case

`enable-linger` being the thing that would allow Red to continue to run even without an active session

even right now, the bot is being run as whatever user is specified when the unit file is written. Theoretically, this could be root if someone were to specify that, but we strongly discourage actually running  the bot as root anyway. It could be that we update the docs in some way to create a dedicated user for running the Red service (again, taking from something Jack mentioned in Discord)
