### ISSUE TITLE
[Suggestion] Trivia leaderboard

### ISSUE THREAD

**Issue by CRASNY** [Cog-Creators/Red-DiscordBot#601]
Thought this would be pretty cool and encourage more participation. Just some way to permanently log who on the server has the most trivia victories.

**Comment by MiniJennJenn** [comment]
Would have to consider how many people are in the game. What if one person just keeps playing one person trivia games and winning. 

Also maybe times won per trivia list... idk

**Comment by Tobotimus** [comment]
Implemented for V3 in #915
