### ISSUE TITLE
Have to use /play multiple time before song plays

### ISSUE THREAD

**Issue by Tomberryy** [Cog-Creators/Red-DiscordBot#6034]
### What Red version are you using?

3.4.18

### Cog name

Audio

### Command name

play

### What did you expect to happen?

A song playing

### What actually happened?

After trying multiple times, the song finally play but goes through multiple attempts with track error

### How can we reproduce this error?

No idea

### Anything else?

![untitled](https://user-images.githubusercontent.com/85990187/233127105-225b67f3-5d15-403a-8482-a38679fea45f.png)

Here's a screenshot of the behaviour

Happy to provide more info :)

Thanks in advance

**Comment by aikaterna** [comment]
Known issue, will most likely be fixed with the next release. Thanks for reporting it.

**Comment by jdkang** [comment]
FWIW also seeing this issue on `3.6.18`
