### ISSUE TITLE
Error updating repo branches

### ISSUE THREAD

**Issue by Aioxas** [Cog-Creators/Red-DiscordBot#604]
As name says, doing cog update on a repo branch (a develop branch for example) causes:

1. UpdateError due to not being able to do fast-forwarding. Console error is:
    Fatal: Not possible to fast-forward, aborting
    - This is caused when master or main tree has a newer commit than the one the branch originated. Aka (Branch is one commit behind master, n commits ahead of master)
    - Shown in discord as "Error polling updates"
2. Doing git reset --hard origin/HEAD moves the branch all the way back to the original commit when the branch split off from master.
     - This causes the cog update to do all the commits (and thus if new cogs were added or deleted, it shows them again and again)

**Comment by tekulvw** [comment]
This is because you added local commits that weren't a part of the remote repo branch, not because commits were added to master on the remote

**Comment by Aioxas** [comment]
Local commits that weren't part of the remote repo branch? How so? The n commits ahead of master works without an issue, it's when it gets behind master that it goes wacky. Maybe I am wrong, but if you can explain all the better.

At the time that the branch was created, there were no newer commits in master (in github). 

So in order to fix that, you say I should rebase it every time? I am just curious.

**Comment by Jan200101** [comment]
Probably edited a cog that was in /data/downloader and commited it, but never pushed or doesnt have push rights

**Comment by Aioxas** [comment]
Not the case, Sentry. No cogs from that repo have been edited.

**Comment by Twentysix26** [comment]
This should've been fixed by #675
