### ISSUE TITLE
Exception on not found Youtube-Video

### ISSUE THREAD

**Issue by Nama** [Cog-Creators/Red-DiscordBot#606]
Hi,
I am on commit #605 with updated requirements. I am running on arch Linux with Python 3.6.
Audio playback is working, but I noticed two malfunctions with the commands `play` and `yt`.

`play ocremix chemixtrixx` is working like intended.
`play chemixtrixx` says in the channel "Searching..." and nothing happens.
**Console output**
```
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at /home/kirika/scripts/red/cogs/audio.py:1994> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "/home/kirika/scripts/red/cogs/audio.py", line 2052, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "/home/kirika/scripts/red/cogs/audio.py", line 476, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: chemixtrixx: YouTube said: This video does not exist.
```
Well, if a video is not found, it should be posted to the channel. But seems, that there is an error in the code.
Anyway, if you search with your browser on Youtube for "chemixtrixx" there are dozens of results...

**Comment by palmtree5** [comment]
Hmm, I get a completely different error when doing `play chemixtrixx` (`NoneType has no attribute duration`)

**Comment by kev946** [comment]
Try updating your youtube-dl package `pip3 install youtube-dl --upgrade`

**Comment by Nama** [comment]
I updated the requirements again (youtube_dl-2017.2.14) and now I get the exact same exception @palmtree5 gets.

**Comment by Kowlin** [comment]
This is a general error for when the file cannot be downloaded. Please try another song. But to get back on topic. The YouTubeDL error is fixed.

**Comment by Nama** [comment]
Well I guess the "not found" bug might be unrelated to Red but to youtube-dl, since [this link](https://www.youtube.com/results?search_query=chemixtrixx) is a thing.

I just updated Red and the requirements.
Let's say, a video really couldn't be found, Red should respond on the channel to the command. Instead, only exceptions occur.
Output of `play chemixtrixx`:
```
ERROR: chemixtrixx: YouTube said: This video does not exist.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at /home/kirika/scripts/red/cogs/audio.py:2004> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "/home/kirika/scripts/red/cogs/audio.py", line 2062, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "/home/kirika/scripts/red/cogs/audio.py", line 478, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
```
Output of `play kjghsdfohuwetgljknasdf`
```
ERROR: [youtube] No video results
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at /home/kirika/scripts/red/cogs/audio.py:2004> exception=AttributeError("'NoneType' object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "/home/kirika/scripts/red/cogs/audio.py", line 2037, in queue_manager
    song = await self._play(sid, url)
  File "/home/kirika/scripts/red/cogs/audio.py", line 806, in _play
    song = await self._guarantee_downloaded(server, url)
  File "/home/kirika/scripts/red/cogs/audio.py", line 602, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "/home/kirika/scripts/red/cogs/audio.py", line 252, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'
```
youtube-dl really seems broken with some results, telling Red that [the video](https://www.youtube.com/results?search_query=chemixtrixx) doesn't exist and Red doesn't seem to handle "not found" response from youtube-dl

**Comment by tekulvw** [comment]
This is either the result of an outdated youtubedl or another one of those #609 things.
