### ISSUE TITLE
Bot does not add songs in a youtube playlist to queue that have been added since first time playlist was requested

### ISSUE THREAD

**Issue by the-Astra** [Cog-Creators/Red-DiscordBot#6096]
### What Red version are you using?

3.4.19

### Cog name

Audio

### Command name

play

### What did you expect to happen?

The entire playlist to be added to the bot's queue.

### What actually happened?

Only videos in the playlist that were present upon first time requesting are added to the queue. Any videos added past that time are not added.

### How can we reproduce this error?

1. Request a youtube playlist to the queue
2. Add some new videos/songs to the playlist
3. Request the playlist again. The number queued will be the same as first request

### Anything else?

Adding onto this (though it could probably qualify as its own issue), songs have been skipping at random more and more frequently for unknown reason. The ones that are being skipped are still public and hosted on youtube.

**Comment by aikaterna** [comment]
Make sure your Red bot is updated to 3.4.19, for the last issue you mentioned about skipping songs. I don't believe Red 3.4.5 would be working anymore, the version you claim to be running in this issue.

When it comes to your playlist, if it's a playlist link on an outside service that you are passing to play, the cache has cached that playlist link being the specific songs. You can wipe your cache or set it to remember 0 days of links, in your audioset settings.

**Comment by the-Astra** [comment]
Ah that was a mistake on my end, Red bot is fully up to date on 3.4.19, I thought the suggested fill in was up to date
