### ISSUE TITLE
[Request] Guide to putting RedBot on a cloud server.

### ISSUE THREAD

**Issue by Drakmon** [Cog-Creators/Red-DiscordBot#610]
Is there any way to have the bot on a cloud based server so that it doesn't have to run off my pc. I have done a bit of research into a few products such as amazon or heroku but i was curious if this is even possible & if it is if anyone has a guide?

**Comment by Kowlin** [comment]
Red will work on any VPS or other service that runs a classical headless server, (think of Ubuntu, CentOS, Debian, ETC) Red will also work on services such as Heroku and Cloud9. However we do not provide documentation for these services yet.

**Comment by Aareon** [comment]
I use [DigitalOcean](https://www.digitalocean.com/) to host my bot. Check it out.

**Comment by Twentysix26** [comment]
You can use the existing guides for that. The only research you have to do on your own is how to connect to a VPS.

**Comment by pardeepsingh12365** [comment]
How to host red on heroku please tell me

**Comment by Stylite** [comment]
You can not host red on heroku, Use a vps from this list https://gist.github.com/Twentysix26/cb4401c6e507782aa6698e9e470243ed

**Comment by SwinsorOfficial** [comment]
Does Red work on Heroku or not?

**Comment by laggron42** [comment]
@SwinsorOfficial 
![screen shot 2018-04-11 at 18 37 26](https://user-images.githubusercontent.com/23153234/38630524-74e33c46-3db7-11e8-9589-0e6dc296caa3.png)

**Comment by pgaetani** [comment]
Look at the response right above your question, Swinsor, actually read issues before asking things like that, maybe your question is already answered.
