### ISSUE TITLE
Option to classify reason in moderation actions as required 

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#6105]
### What component of Red (cog, command, API) would you like to see improvements on?

Mod

### Describe the enhancement you're suggesting.

An option to classify the reason arg as required. I believe this would be a beneficial option to add to the modularity of Red.

### Anything else?

Reason being, we are trying to move to Red for all moderation uses and being able to require a reason would be nice to ensure its properly logged and not require to use the reason command afterwards.

**Comment by WGrav01** [comment]
I'll work on this

**Comment by kevin1015wang** [comment]
Hi, I'd love to work on the feature to add an option to require reasons for moderation actions!

**Comment by aikaterna** [comment]
Feel free. We don't assign non-members to specific issues.
