### ISSUE TITLE
[suggestion] colored launcher

### ISSUE THREAD

**Issue by Jan200101** [Cog-Creators/Red-DiscordBot#612]
Colorama could be used for it. I implented a example in [here](https://github.com/Jan200101/Red-DiscordBot/blob/2d105674d296aa071248df5600746b7b75ab8146/launcher.py).
Then install it with the requirements

**Comment by Jan200101** [comment]
Example
http://i.imgur.com/WsbH5GQ.jpg

**Comment by Aareon** [comment]
Even a [ouput.py](https://github.com/Aareon/J-Discord/blob/master/utils/output.py) utility would work for something like this. Simply instantiate the class [like so](https://github.com/Aareon/J-Discord/blob/master/bot.py#L10) and call.

**Comment by Jan200101** [comment]
Colorama is bugged right now and randomly bugs on py 3.6 and vanilla command prompt.

**Comment by tekulvw** [comment]
Still bugged, we may revisit this when we can get hte current issues resolved but this isn't on the radar anytime soon.
