### ISSUE TITLE
[Mutes] NoneType error for guild

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#6140]
### What Red version are you using?

3.5.1

### What were you trying to do?

Started bot up, noticed errors in logs from Mutes.

### What did you expect to happen?

No errors to occur.

### What actually happened?

The below error started being spammed
```py
[ERROR] red.cogs.mutes: An unexpected error occurred in the unmute task
Traceback (most recent call last):
May 10 18:32:24 deimos python[116489]:   File "/home/flare/redenv/lib/python3.11/site-packages/redbot/cogs/mutes/mutes.py", line 274, in _clean_tasks
May 10 18:32:24 deimos python[116489]:     r = task.result()
May 10 18:32:24 deimos python[116489]:         ^^^^^^^^^^^^^
May 10 18:32:24 deimos python[116489]:   File "/home/flare/redenv/lib/python3.11/site-packages/redbot/cogs/mutes/mutes.py", line 489, in _auto_channel_unmute_user
May 10 18:32:24 deimos python[116489]:     member = channel.guild.get_member(data["member"])
May 10 18:32:24 deimos python[116489]:              ^^^^^^^^^^^^^
May 10 18:32:24 deimos python[116489]: AttributeError: 'NoneType' object has no attribute 'guild'
```

### How can we reproduce this error?

Unsure of exact steps, seems to be coming from the unmute event that is ran.

**Comment by sravan1946** [comment]
I *think* this is related to #6139 and fixed in that

**Comment by flaree** [comment]
That is related to vendored menus, this is mutes

**Comment by sravan1946** [comment]
Yea my bad.

**Comment by Jackenmen** [comment]
Oh cool, us *actually* logging errors is already revealing issues with Mutes! Thanks for the report :)
