### ISSUE TITLE
[Docs] Brew formulae missing for Java install for Mac

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#6192]
### What Red version are you using?

3.5.2

### What were you trying to do?

Reviewing #6190 and installing Java 17 on a Mac via the method listed, `brew install --cask temurin17`, and also the `brew install --cask temurin11` listed on our current docs.

### What did you expect to happen?

I expected Temurin's Java 17 or 11 to be installed.

### What actually happened?

The formulae are missing and `temurin` points to Java 20.

```
aikaterna@Mac-mini ~ % brew install --cask temurin17
==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: Cask 'temurin17' is unavailable: No Cask with this name exists.
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Searching for similarly named casks...
==> Casks
temurin

To install temurin, run:
  brew install --cask temurin
```

### How can we reproduce this error?

1. Have a Mac with an up to date copy of brew.
2. Use `brew install --cask temurin11` or `brew install --cask temurin17`

### Anything else?

There are formulae for `openjdk@11` and `openjdk@17` that can be installed without the `-cask` flag, but they from Oracle.

**Comment by yamikaitou** [comment]
If you run `brew tap homebrew/cask-versions` first, you can then install `temurin11` or `temurin17` successfully.

Found it on the install guide at adoptium.net/installation

**Comment by yamikaitou** [comment]
Strangely enough, this is already documented in the docs... so no action needed?

**Comment by Jackenmen** [comment]
Looking at our docs containing `brew tap homebrew/cask-versions`, I assume there is no action needed here.
