### ISSUE TITLE
Alphabetically sort installed cogs in `[p]cog list`

### ISSUE THREAD

**Issue by sravan1946** [Cog-Creators/Red-DiscordBot#6214]
### What component of Red (cog, command, API) would you like to see improvements on?

cog list

### Describe the enhancement you're suggesting.

The cogs in the Installed session is not sorted alphabetically.
![image](https://github.com/Cog-Creators/Red-DiscordBot/assets/57430307/c9b5a753-26e3-489d-95cc-f66a79dd94a7)

It would look better if that session is also sorted alphabetically like in the available cogs session

**Comment by Jackenmen** [comment]
Huh, I have never noticed this, sorting would definitely make sense here.
