### ISSUE TITLE
Nothing happens when using [p]cog update

### ISSUE THREAD

**Issue by Micru0** [Cog-Creators/Red-DiscordBot#6218]
### What Red version are you using?

Newest

### Cog name

Admin

### Command name

Cog

### What did you expect to happen?

I expected it to update cogs since the bot is shutting down every 2 songs.

### What actually happened?

Literally nothing happens 

### How can we reproduce this error?

1.cog update
2.nothing happens 
3.
...

**Comment by japandotorg** [comment]
Are you sure you have downloader loaded? `[p]load downloader`, also it's recommended to join the [support server](https://discord.gg/red) for such queries/issues.

**Comment by Micru0** [comment]
> 



> 

Yeah it worked after that thanks man!
