### ISSUE TITLE
Pillow Not Detected.

### ISSUE THREAD

**Issue by utf-4096** [Cog-Creators/Red-DiscordBot#624]
Hi ! I got a new issue with red, every cog that needs pillow is not detected anymore and says that i need to install pillow, even if it is already installed, updates did'nt fixed it, so now, i ask on GitHub. How can we fix this ? Let me know !

**Comment by skeith** [comment]
Screenshot of said error please

**Comment by utf-4096** [comment]
![error](https://cloud.githubusercontent.com/assets/25370216/23067689/bc037248-f520-11e6-81e1-0b157e6dee70.PNG)

**Comment by skeith** [comment]
Can you tell us, what module is that and screenshot the console / cmd window for the error too

Also, please screenshot the result of these command (run from console/cmd)
Linux : `pip3.5 freeze`
Windows : `py.exe -3 -m pip freeze`

**Comment by NekoTony** [comment]
try running it 👀

**Comment by utf-4096** [comment]
I am gonna to try

**Comment by DracoZ12** [comment]
![image](https://cloud.githubusercontent.com/assets/25370216/23067782/25028716-f521-11e6-936d-5082a3472340.png)

**Comment by utf-4096** [comment]
Modules : Drawing, leveler and emotes. All of those use pillow.

**Comment by skeith** [comment]
~~you forgot to answer my other question, what module is that?~~

also, please try replying in one single comment

**Comment by NekoTony** [comment]
yukrin got ya cover, I'm out


btw cute avatar

**Comment by skeith** [comment]
@DracoZ12 do you by any chance have more than one python version installed?

**Comment by NekoTony** [comment]
do u have more then one python installed?

**Comment by utf-4096** [comment]
I only have Python 3.5 installed

**Comment by skeith** [comment]
@DracoZ12 can you go over the Red Discord support channel, so we can troubleshoot you faster?

**Comment by utf-4096** [comment]
ok
