### ISSUE TITLE
[streams] Use of deprecated helix/users/follows endpoint

### ISSUE THREAD

**Issue by wohali** [Cog-Creators/Red-DiscordBot#6246]
### What Red version are you using?

3.5.4

### Cog name

Streams

### Command name

twitchstream

### What did you expect to happen?

Use of current API endpoint

### What actually happened?

Just received an email from Twitch:

> Hello,
>
> We are reaching out as we have identified that your application(s) below have made requests to the deprecated "helix/users/follows" Twitch API endpoint in the past month and may be affected by the scheduled shutdown if further action is not taken.
> 
> (my Red bot)
> 
> This “Get Users Follows” Twitch API endpoint was deprecated in February 2023 and replaced by “[Get Channel Followers](https://dev.twitch.tv/docs/api/reference/#get-channel-followers)” and “[Get Followed Channels](https://dev.twitch.tv/docs/api/reference/#get-followed-channels).”  To continue receiving follow count, receiving follower information, or checking for a follow, please make sure your application is updated to use the new API URLs and that your authentication flow includes the new scopes if required.

### How can we reproduce this error?

1. Follow a Twitch stream
2. wait a month(?) until Twitch emails about it
3.
...

### Anything else?

Looks like just changing out `TWITCH_FOLLOWS_ENDPOINT` in `streamtypes.py` to `helix/channels/followers`, and looking for the `total` key in the response would get the total # of followers of that broadcast.

**Comment by CrystalENVT** [comment]
+1

I also received an email about this within the past day. The endpoint has been deprecated since Feb 2023 apparently, so they are emailing as notice that it's being used
