### ISSUE TITLE
[p]version command won't embed if repo has a non-HTTPS remote address

### ISSUE THREAD

**Issue by calebj** [Cog-Creators/Red-DiscordBot#626]
I narrowed down a problem I was getting on the [p]version command for both regular and selfbots, where it would say "I need the `Embed links` permission to send this."
As it turns out, Discord doesn't allow non-HTTP protocols in the `url` field of embeds.

**Comment by tekulvw** [comment]
Caleb, I love you.

**Comment by calebj** [comment]
Funnily enough, markdown links with other protocols work just fine.

**Comment by skeith** [comment]
Does this mean, generally embed won't accept non HTTPS in the `url` fields?

**Comment by calebj** [comment]
Correct. A message will not send if it contains a non-http[s] link such as ftp:// in `url`.
