### ISSUE TITLE
Switch lmgtfy to our own fork of NatoBoram/lmgtfy

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#6268]
Let's use this by forking it, deploying our own version through GH pages, and then finally switching the command to use it.

> I've come across this project and has a demo we could use, which, doesn't track you, and actually redirects you to Google. https://github.com/NatoBoram/lmgtfy
> 
> https://natoboram.github.io/lmgtfy/search?q=Red-DiscordBot&btnK=Google+Search

_Originally posted by @DJTOMATO in https://github.com/Cog-Creators/Red-DiscordBot/issues/6255#issuecomment-1813247161_

**Comment by DJTOMATO** [comment]
You can use my instance if you want (I honestly never tried github pages so idk how to set it up)
https://lmgtfy.lena.moe

Alternative I've also made a cog with custom endpoint command
https://github.com/DJTOMATO/glas-cogs/tree/main/googleit

**Comment by Jackenmen** [comment]
I purposefully said that we need to fork it since I want to keep this in our own infrastructure to ensure that it's reliably available.

**Comment by Jackenmen** [comment]
The fork is up, some references still need to be updated but it is already deployed:
https://github.com/Cog-Creators/lmgtfy

**Comment by NoPlagiarism** [comment]
What about moving it to lmgtfy.discord.red?

**Comment by Jackenmen** [comment]
It is a possibility if @Kowlin is up for it but I was trying to limit the maintainer time needed to proceed with this.

**Comment by Jackenmen** [comment]
> The fork is up, some references still need to be updated

I updated references and added a more proper copyright notice to the page, #6269 can now be merged once it's reviewed.
