### ISSUE TITLE
`streamalert list` is not updated for new Discord's markdown

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#6273]
### What component of Red (cog, command, API) would you like to see improvements on?

Streams

### Describe the enhancement you're suggesting.

Discord has updated Markdown to support header & lists, whatever else they've added too...

However, this broke the `streamalert list` command in the process, because the output of the command return a list that would not work well with Discord's new Markdown functionalities.

**It would look like that:**
![image](https://github.com/Cog-Creators/Red-DiscordBot/assets/61093863/ac68bc68-b178-4924-b6db-8e7fc63dd72d)

**But now look like this**
![image](https://github.com/Cog-Creators/Red-DiscordBot/assets/61093863/7c924c38-963a-4251-aa3c-68964795f0da)

Feel free to suggest a new output syntax to respect.
Either rewrite the command output, or simply escape the markdown for the "-" character.

**Comment by palmtree5** [comment]
I'll attempt to work on this this weekend. It seems like it should be an easy fix
