### ISSUE TITLE
Official stream cog does not work

### ISSUE THREAD

**Issue by GameAreaCZ** [Cog-Creators/Red-DiscordBot#6275]
### What Red version are you using?

3.5.4

### What were you trying to do?

I set the Twitch API key, add a streamer to the streamalert list and wanna get a alert/notification when he started a stream.

### What did you expect to happen?

To have a notification in set channel.

### What actually happened?

Nothing. No notification or post in a Discord channel. No mention. This error in the console:

[12:08:12] ERROR    [red.core.cogs.Streams] An error has occurred with Streams. Please report it.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/container/.local/lib/python3.11/site-packages/redbot/cogs/streams/stre │
│ ams.py:833 in check_streams                                                  │
│ ❱  833                         embed, is_rerun = await stream.is_online()    │
│ /home/container/.local/lib/python3.11/site-packages/redbot/cogs/streams/stre │
│ amtypes.py:414 in is_online                                                  │
│ ❱ 414             return self.make_embed(final_data), final_data["type"] ==  │
│ /home/container/.local/lib/python3.11/site-packages/redbot/cogs/streams/stre │
│ amtypes.py:450 in make_embed                                                 │
│ ❱ 450         embed.addfield(name=("Followers"), value=humanize_number(dat │
│ /home/container/.local/lib/python3.11/site-packages/redbot/core/utils/chat_f │
│ ormatting.py:593 in humanize_number                                          │
│ ❱ 593     return format_decimal(val, locale=get_babel_regional_format(overri │
│ /home/container/.local/lib/python3.11/site-packages/babel/numbers.py:480 in  │
│ format_decimal                                                               │
│ ❱  480     return pattern.apply(                                             │
│ /home/container/.local/lib/python3.11/site-packages/babel/numbers.py:1179 in │
│ apply                                                                        │
│ ❱ 1179             value = decimal.Decimal(str(value))                       │
╰──────────────────────────────────────────────────────────────────────────────╯
InvalidOperation: [<class 'decimal.ConversionSyntax'>]

### How can we reproduce this error?

1. Set streams cog.
2. Set Twitch key.
3. Set streamer to a list for mention and alert to a Discord channel (bazimcz Twitch channel was added only).
4. Let the streamer start a stream.
5. Wait for a notification.

**Comment by Kowlin** [comment]
This has been resolved in 3.5.5
