### ISSUE TITLE
Mute a person who has left the server doesn't work.

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#6277]
### What Red version are you using?

3.4.5

### What were you trying to do?

Mute a person who as left the server;

### What did you expect to happen?

Mute the selected person.

### What actually happened?

Nothing happened...

### How can we reproduce this error?

1.Mute a person who has left the server
2.Nothing happened

**Comment by Kowlin** [comment]
A user who has left the server cannot be muted. Also closing this due the fact that its 7 months old and not an issue in reality.
