### ISSUE TITLE
Add a start_dm option to SimpleMenu

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Red-DiscordBot#6282]
In order to support `[p]help` with a button menu in DMs, `SimpleMenu` needs to be able to be sent as a DM to a particular user [[Ref](https://github.com/Cog-Creators/Red-DiscordBot/pull/5375#issuecomment-1874666094)]. The current `SimpleMenu.start` method accepts a `Context` object, which is incompatible with this behavior. `SimpleMenu` should be given a new method `.start_dm(user: discord.User)`, which sends the menu as a direct message to that user.

**Developer note:**
`SimpleMenu` currently stores `self.ctx` in `.start`, however it does not appear to ever be used. The other two attributes set by `.start` (`message` and `author`) will be possible to set in this method.

Unblocks #5375

**Comment by yeetbruises** [comment]
I would like to take on this issue as my first GitHub contribution. I have experience in python discord bots so I think I could solve this.

**Comment by Jackenmen** [comment]
@Flame442 any reason we shouldn't consider expanding `.start()` to allow passing `discord.User` instead of creating another method? It's mostly just an alternative design but I feel like it may be a bit more aligned with how we generally do these kinds of APIs in Red wherever it makes sense?

**Comment by Flame442** [comment]
I don't have strong opinions about which option is better, see https://github.com/Cog-Creators/Red-DiscordBot/pull/5375#issuecomment-1874660248 for where I asked Trusty what he thought the best approach was.

**Comment by yeetbruises** [comment]
Thank you :)

**Comment by yeetbruises** [comment]
@Flame442 Am I going in the right direction with this snippet I've added thus far? 

`async def start_dm(self, user: discord.User):
        """
        Used to start displaying the menu in a direct message.

        Parameters
        ----------
            user: 'discord.User'
                Send the message to a particular user.
        """
        self.author = user
        kwargs = await self.get_page(self.current_page)
        self.message = await user.send(**kwargs)`

**Comment by Flame442** [comment]
(Context deleted)
If you need help working on the issue, please ask in the #coding channel of the [red server](https://discord.gg/red) (without pinging any particular user).
