### ISSUE TITLE
[Suggestion] A way to reset server's economy

### ISSUE THREAD

**Issue by belguawhale** [Cog-Creators/Red-DiscordBot#629]
Title says it all. Currently I can use economyset to set an individual user's balance but I don't see an easy way to reset the entire server. Casino has a casino wipe command.

**Comment by Twentysix26** [comment]
`[p]bank reset`

**Comment by belguawhale** [comment]
Is the command owner-only? This is what I see when I do >bank:
```>bank

Bank operations

Commands:
  balance  Shows balance of user.
  register Registers an account at the xcubed bank
  set      Sets credits of user's bank account
  transfer Transfer credits to other users

Type >bank command for more info on a command.
You can also type >bank category for more info on a category.```

Maybe the version being used is old? How can I check the version of the bank module?

**Comment by Eslyium** [comment]
checks.serverowner_or_permissions(administrator=True)

Meaning either your bot owner, server owner, or you have the administrator permission in order to reset
