### ISSUE TITLE
Icecast not working

### ISSUE THREAD

**Issue by HvyMtlMtnMan** [Cog-Creators/Red-DiscordBot#6293]
### What Red version are you using?

3.5.5

### Cog name

Audio

### Command name

play

### What did you expect to happen?

Tested with https://kathy.torontocast.com:1480/stream & https://s5.ssl-stream.com:8022/stream
play https://s5.ssl-stream.com:8022/stream would start streaming the icecast radio stream to my connected discord voice channel

### What actually happened?

![Screenshot 2024-02-18 111436](https://github.com/Cog-Creators/Red-DiscordBot/assets/159820640/3ceec276-ab61-452f-8403-c9da26485d4c)

### How can we reproduce this error?

run the audio play command with one of the above stream urls
2.
3.
...

**Comment by aikaterna** [comment]
Use [p]audioset restrict to toggle on the ability to use non-commercial sites for playback. Come visit us at discord.gg/red in the support channel if you have more issues.
