### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by mrvaghani** [Cog-Creators/Red-DiscordBot#630]
Unable to install Basic + Audio Requirements using option 1
Successfully able to install audio requirements 64bit using option 4

OS: Windows 7 Ultimate Service Pack 1
Python:(32-bit) Version 3.6.150.0
Get version 2.11.1

Here is the log file attached with the error I got:
[audioError.txt](https://github.com/Twentysix26/Red-DiscordBot/files/789080/audioError.txt)

Let me know if you require any further information.
Thanks,
mrvaghani

**Comment by Twentysix26** [comment]
You need python 3.5
Edit: Make sure to uninstall 3.6 if you don't need it

**Comment by mrvaghani** [comment]
Confirmed that after installing Python 3.5.3, I no longer get the error.

NOTE: I had to remove my previous installation of 3.6.0 before I was able to get it to work.

Thank you @Twentysix26
