### ISSUE TITLE
Issue installing on FreeBSD due to an outdated package requirement of aspw.

### ISSUE THREAD

**Issue by beowuff** [Cog-Creators/Red-DiscordBot#6301]
### What Red version are you using?

3.5.5

### What were you trying to do?

Install Red Discord bot on FreeBSD.

### What did you expect to happen?

I expected the bot to be installed and work.

### What actually happened?

There is an error building apsw version 3.43.1.0.

In file included from src/apsw.c:81:
      /tmp/pip-install-z48nrgwg/apsw_2a28832101604043ad1986fe93684845/sqlite3/sqlite3.c:119499:13: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
        for(i=0; i<sizeof(yDbMask); i++) if( m[i] ) return 0;
                 ~^~~~~~~~~~~~~~~~
      src/apsw.c:105:10: fatal error: 'alloca.h' file not found
      #include <alloca.h>
               ^~~~~~~~~~
      1 warning and 1 error generated.
      error: command '/usr/bin/cc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for apsw
Failed to build apsw
ERROR: Could not build wheels for apsw, which is required to install pyproject.toml-based projects

### How can we reproduce this error?

1. On an installed and updated FreeBSD 14.0 box.
2. Install sudo apt -y install python git openjdk-17-jre vim
3. Run python -m pip install -U Red-DiscordBot

### Anything else?

The issue appears to be that Red is relying on an outdated version of aspw. It is trying to build 3.43.1.0. The latest version is 3.45.1. Note this version build fine on FreeBSD if I call it directly by pip to install.

**Comment by Jackenmen** [comment]
We do not provide support for BSD systems. We will bump dependencies whenever we make the next release but we do not plan release dates in advance.
