### ISSUE TITLE
Can no longer play yt tracks

### ISSUE THREAD

**Issue by jar349** [Cog-Creators/Red-DiscordBot#6306]
### What Red version are you using?

3.5.5

### What were you trying to do?

the `.search` command:
![Image](https://github.com/Cog-Creators/Red-DiscordBot/assets/290154/1cfb8026-cb03-4919-8f22-7e2bed60a1e0)

the `.play` command: 

![Image](https://github.com/Cog-Creators/Red-DiscordBot/assets/290154/bd7a7cf8-a438-4b2e-8bb8-d1c042f7cfa4)

the `.sing` command: 

![Image](https://github.com/Cog-Creators/Red-DiscordBot/assets/290154/353f4477-026c-49c9-87ae-2454ee9d0dc1)

the `.traceback` command:

![Image](https://github.com/Cog-Creators/Red-DiscordBot/assets/290154/0bfb330e-02a7-45af-8cf8-3fcb3ea20d1c)

the server console log:

![Image](https://github.com/Cog-Creators/Red-DiscordBot/assets/290154/071081bf-4fc4-4b3a-85b7-c3c503c94736)

### What did you expect to happen?

I expected the bot to be able to play yt tracks.

### What actually happened?

nothing found

### How can we reproduce this error?

I don't know how I got into this state.  I don't know if it's just me or something changing on the yt side that causes red to fail.

**Comment by aikaterna** [comment]
Fixed when #6305 is merged and a new Red release is made.
