### ISSUE TITLE
[Audio] Audioset restrict user-facing alert message could be improved

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#6347]
### What component of Red (cog, command, API) would you like to see improvements on?

Audio

### Describe the enhancement you're suggesting.

Currently the bot is set to deny non-commerical links by default, which returns a message to the user that "This URL is not allowed." when trying to use something like an http stream or a Discord file link, leading to quite a few support questions relating to how to play these types of links. 

I feel that this message could be improved in letting the user know that the bot owner can toggle off this restriction, but I'm also not sure if there should be more information presented informing people why this restriction is in place before advising to turn it off.

### Anything else?

Maybe something like this, whether the added message is in the body of the embed, or the footer. My vote is for the embed description as the footer placement looks a bit long.

Unable To Play Tracks
That URL is not allowed.
The bot owner can remove this restriction by using [p]audioset restrict.

**Comment by DJTOMATO** [comment]
#6348 should fix this issue.
