### ISSUE TITLE
Track Error - Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by stefanusade** [Cog-Creators/Red-DiscordBot#6389]
### What Red version are you using?

3.5.9

### Cog name

Audio

### Command name

play

### What did you expect to happen?

Bot playing song

### What actually happened?

Track error: Sign in to confirm you’re not a bot
![image](https://github.com/Cog-Creators/Red-DiscordBot/assets/85295874/9345d52b-d7a9-4aa3-b178-cc755eec5c4e)

### How can we reproduce this error?

1.
2.
3.
...

**Comment by BenCos17** [comment]
known issue 
#4505 covers it

**Comment by Kowlin** [comment]
Duplicate of #4505.
