### ISSUE TITLE
[Suggestion] Let the bot assign roles/permissions

### ISSUE THREAD

**Issue by Bawbd** [Cog-Creators/Red-DiscordBot#639]
Hello,

I would like to have commands to assign role and permissions to users.

Something like : !mod role moderator Bob

Is it even possible ?

Would you consider it ?

Thanks in advance for the help.

**Comment by Jan200101** [comment]
Cant you use Discord for that ?

**Comment by Bawbd** [comment]
Well I would like to give members permissions to use the bot (that has permissions) to do it without giving them permissions on the server itself.

**Comment by skeith** [comment]
It's all dependent on what you want the user to use on the bot. Most of the time, normal user ( that @ everyone role ) can already use the bot on most user level commands.

Can you elaborate your question with an example case?

**Comment by Bawbd** [comment]
I would like to give moderators the possibility to assign roles but only by using the bot, not by giving them the permissions in Discord.

For example, "moderator A" assign the role "Member" to "guest 1".

!mod role "guest 1" Member

**Comment by skeith** [comment]
If not mistaken, that is achievable using `adminset modrole <role-you-want-as-a-mod>`

then if there's any modrole permission command to give role available, that role can use it.

Need more research on this since I this example case is unique

**Comment by Bawbd** [comment]
These commands only give permissions on the bot itself, not on the server.

**Comment by skeith** [comment]
True, but if there's a cog that is usable by modrole to give role to others, it can be used for your case.

Stop talking about the server, aren't we talking about a role to give role?

**Comment by Bawbd** [comment]
I want a command to give server permissions to an user with the bot.

I'm not sure if I'm clear enough.

**Comment by skeith** [comment]
your comment above is not the same with your first comment.
at first you want assigning role without giving MANAGE ROLES

now you want SERVER PERMISSIONS which I translate to MANAGE SERVER

**Comment by Bawbd** [comment]
Managing the roles is a server permissions...

I want to give "manage permissions" to the bot only, so users that don't have "manage permissions" can use the bot to give other members roles.

Is that clear ?

**Comment by skeith** [comment]
That is what this comment of mine mean

```
If not mistaken, that is achievable using adminset modrole <role-you-want-as-a-mod>

then if there's any modrole permission command to give role available, that role can use it.

Need more research on this since I this example case is unique```

**Comment by Kowlin** [comment]
Allow me to interrupt. What you're looking for a 3rd party cog. As of now, there currently is no cog that can do what you requested. (Having moderators assign roles to their users) This is something I want to work on. But I cannot give you any promises or ETA

**Comment by Bawbd** [comment]
Ok thanks.

**Comment by tekulvw** [comment]
Actually `Admin` in the Squid plugins repo has an `addrole` command

**Comment by Twentysix26** [comment]
I'm most likely not adding this feature anytime soon. I feel like the interface on both desktop and mobile is now polished enough and this type of operation is a nuisance to do through text commands. I see no benefits.
