### ISSUE TITLE
Cannot remove "Aikaterna's curated tracks"

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#6409]
### What Red version are you using?

3.5.10

### Cog name

Audio

### Command name

[p]playlist delete 42069

### What did you expect to happen?

The playlist gets deleted

### What actually happened?

'''No access to playlist.
You do not have the permissions to manage Aikaterna's curated tracks (42069) [Global].''' and it's not deleted.

### How can we reproduce this error?

1.[p]playlist list
2.[p]playlist delete 42069

### Anything else?

I'm aware that there must be at least one playlist.  I want it to be my playlist though.  It should be possible to delete the default as long as at least one other playlist exists.

I'd settle for an ability to hide it from the [p]playlist list command too.

**Comment by aikaterna** [comment]
That playlist is not removable. You can set your own Red playlist to be the autoplay playlist with [p]audioset autoplay playlist.
