### ISSUE TITLE
Autorestarting doesn't work on Debian 8.7

### ISSUE THREAD

**Issue by Sorgrum** [Cog-Creators/Red-DiscordBot#643]
Trying to get autostarting to work. The bot runs fine without autorestarting. 
```
Feb 28 11:50:28 myserver systemd[1]: Starting Red-DiscordBot...
Feb 28 11:50:28 myserver systemd[1]: Started Red-DiscordBot.
Feb 28 11:50:28 myserver systemd[30786]: Failed at step CHDIR spawning /usr/bin/python3.5: No such file or directory
Feb 28 11:50:28 myserver systemd[1]: red.service: main process exited, code=exited, status=200/CHDIR
Feb 28 11:50:28 myserver systemd[1]: Unit red.service entered failed state.
```
However, 
```
$ ls /usr/bin/python3.5
/usr/bin/python3.5
```
I think this is an issue with systemd. I read somewhere that it won't work if the file has a period in the name. Is this a fixable issue?

Versions: 
* Systemd
  * `systemd 215 +PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR`

**Comment by Kowlin** [comment]
``Feb 28 11:50:28 myserver systemd[30786]: Failed at step CHDIR spawning /usr/bin/python3.5: No such file or directory`` means that python3.5 reported that there is no file at the target, make sure that you're in the right location.

**Comment by Sorgrum** [comment]
I'm not sure I understand. The file does exist. If I run `ls /usr/bin/python3.5` I don't get a `No such file or directory` error. But if I type just `/usr/bin/python3.5`, I do get `bash: /usr/bin/python3.5: No such file or directory`

**Comment by Kowlin** [comment]
The target being the bot directory, Python3.5 cannot find the bot directory.

**Comment by Sorgrum** [comment]
It seems /usr/bin/python3.5 is a symlink, but the place it's pointing to doesn't exist. 

How can I make sure that I'm in the right directory if I'm trying to run it using systemd?

**Comment by Kowlin** [comment]
Python is fine. Its working like intended, *however* Python cannot find the bot directory, this means that the ``WorkingDirectory`` and ``ExecStart`` are wrong.

If you want me to help out with more accuracy, please share the system.d script here.

**Comment by Sorgrum** [comment]
Doh! Completely missed editing the red.service file. That cleared up the issue. Thanks!
