### ISSUE TITLE
[Audio] Bug and Suggestions

### ISSUE THREAD

**Issue by jonyroda97** [Cog-Creators/Red-DiscordBot#644]
### Bug
- Bot owner isn't marked as a listener.
If the autodisconnect on empty channel is enabled and if the owner is the only one on the channel, the bot disconnects after the set time.

### Suggestions
- On [p]song command show the current time that is playing.

- Multi playlists on queue.
Random playing between the playlists queued (but not like 1 from playlist A other from playlist B and then from playlist A again. Really randomised from all the songs).

- Auto Update Youtube Playlists.
I know it can be made with the scheduler cog but would be easier if it is implemented in the audio cog.

- Add a better queued response. 
This is good when you want to know who queued the sound and have the bot command messages delete enabled. Maybe something like: 
"\<user> queued in  \#<queue_position> \<title>
 (\<link>)"
Example: 
jonyroda97 queued in  \#800 **_Post Malone - Congratulations ft. Quavo_**
(https://www.youtube.com/watch?v=SC4xMk98Pdc)

- In #366 a way to export most replayed links to a youtube playlist (only youtube links)

**Comment by jonyroda97** [comment]
More things to the #623 rewrite list

**Comment by Twentysix26** [comment]
I can't seem to reproduce the bug.

**Comment by jonyroda97** [comment]
i will try to find out how it happened

**Comment by Twentysix26** [comment]
Added the suggestions to #623
Feel free to reopen if you have more details about that issue
