### ISSUE TITLE
[Audio] Stops Playing Audio Randomly

### ISSUE THREAD

**Issue by RageSugar** [Cog-Creators/Red-DiscordBot#645]
When using bot to play music from YT. at times bot will stop playing audio but status continues to display as though it is playing a song.  It randomly will stop playing at random times.  When trying to tell bot to stop, it will act as though no song is playing though status update states it is.

When trying to get bot to restart playing music by using any commands; play, queue, playlist start; no audio will play though the bot will state it has been queued.  Only solution is to shutdown the bot entirely and restart it, but problem will reoccur easily.

**Comment by Jan200101** [comment]
Maybe the Computer running your Bot has a unstable Internet connection

**Comment by tekulvw** [comment]
This may be related to a known Discord bug. Sometimes when the bot disconnects from any voice channel in any server it will stop playing in all servers. There's not a whole lot you can do about it except for making sure that your requirements are up to date and hoping for a fix on the Discord side of things.

**Comment by RageSugar** [comment]
Sucks it might be related to a discord side issue.  While my IPS can be a POS, the errors seem more along the lines of discord being the problem.  Oh well, just have to wait and hope it gets resolved one day.
