### ISSUE TITLE
[Audio] Separate timeout for lavalink downloading

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Red-DiscordBot#6460]
### What component of Red (cog, command, API) would you like to see improvements on?

Audio

### Describe the enhancement you're suggesting.

Currently there is a single timeout for the combined Lavalink downloading and starting up.
https://github.com/Cog-Creators/Red-DiscordBot/blob/d3887b595fc5ca0a2dd5e8dce6bc244174473c07/redbot/cogs/audio/core/tasks/lavalink.py#L61-L64

https://github.com/Cog-Creators/Red-DiscordBot/blob/d3887b595fc5ca0a2dd5e8dce6bc244174473c07/redbot/cogs/audio/manager.py#L491-L492

It'd be nice if there was a separate timeout specifically for downloading so that those with slow connections can still use managed Lavalink

**Comment by Flame442** [comment]
As a workaround, Lavalink is able to be downloaded manually and placed into the correct folder to bypass the timeout of Red downloading it. This still allows the node to be managed (except for auto updating).

There are enough people who come with questions about the timeout that it is something that should probably be addressed, but I don't believe splitting the timeout as described would change anything unless the timeout time is also changed. If splitting would cause it to succeed, then all that would be needed to make the cog work is a `[p]reload`, as it would have already downloaded Lavalink on the first launch, but would have timed out during the startup process. The next launch would not need to download, so it would finish the startup process in time.
