### ISSUE TITLE
Error with audio cog

### ISSUE THREAD

**Issue by mizabmdgg** [Cog-Creators/Red-DiscordBot#6469]
i just try load an audio cog but,

red-discordbot  | [2024-11-01 14:46:46] [WARNING] PyLav.Environment: /config/pylav.yaml does not exist - This is not a problem if it does then the environment variables will be read from it
red-discordbot  | [2024-11-01 14:46:47] [ERROR] PyLav.Environment: Cannot write to /config/pylav.yaml
red-discordbot  | [2024-11-01 14:46:47] [INFO] piccolo.engine.base: Running Postgres version 0.0
red-discordbot  | /data/cogs/Downloader/lib/piccolo/engine/base.py:159: Warning: Unable to connect to database - [Errno 111] Connection refused
red-discordbot  |   version_number = await self.get_version()
red-discordbot  | [2024-11-01 14:46:47] [ERROR] red: Package loading failed
red-discordbot  | Traceback (most recent call last):
red-discordbot  |   File "/data/cogs/Downloader/lib/piccolo/utils/sync.py", line 19, in run_sync
red-discordbot  |     return asyncio.run(coroutine)
red-discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 186, in run
red-discordbot  |     raise RuntimeError(
red-discordbot  | RuntimeError: asyncio.run() cannot be called from a running event loop
red-discordbot  | 
red-discordbot  | During handling of the above exception, another exception occurred:
red-discordbot  | 
red-discordbot  | Traceback (most recent call last):
red-discordbot  |   File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 189, in _load
red-discordbot  |     await bot.load_extension(spec)
red-discordbot  |   File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1684, in load_extension
red-discordbot  |     lib = spec.loader.load_module()
red-discordbot  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "", line 605, in _check_name_wrapper
red-discordbot  |   File "", line 1120, in load_module
red-discordbot  |   File "", line 945, in load_module
red-discordbot  |   File "", line 290, in _load_module_shim
red-discordbot  |   File "", line 721, in _load
red-discordbot  |   File "", line 690, in _load_unlocked
red-discordbot  |   File "", line 940, in exec_module
red-discordbot  |   File "", line 241, in _call_with_frames_removed
red-discordbot  |   File "/data/cogs/CogManager/cogs/audio/__init__.py", line 5, in 
red-discordbot  |     from pylav.extension.red.utils.required_methods import pylav_auto_setup
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/extension/red/utils/required_methods.py", line 17, in 
red-discordbot  |     from pylav.core.client import Client
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/core/client.py", line 64, in 
red-discordbot  |     from pylav.events.manager import DispatchManager
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/events/manager.py", line 6, in 
red-discordbot  |     from pylav.events import api, base, node, player, plugins, queue, track
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/events/player.py", line 11, in 
red-discordbot  |     from pylav.nodes.node import Node
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/nodes/node.py", line 32, in 
red-discordbot  |     from pylav.nodes.api.responses import rest_api
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/nodes/api/responses/rest_api.py", line 13, in 
red-discordbot  |     from pylav.nodes.api.responses.track import Track
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/nodes/api/responses/track.py", line 8, in 
red-discordbot  |     from pylav.storage.database.tables.tracks import TrackRow
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/storage/database/tables/tracks.py", line 12, in 
red-discordbot  |     from pylav.storage.database.tables.misc import DATABASE_ENGINE
red-discordbot  |   File "/data/cogs/Downloader/lib/pylav/storage/database/tables/misc.py", line 25, in 
red-discordbot  |     DATABASE_ENGINE = PostgresEngine(
red-discordbot  |                       ^^^^^^^^^^^^^^^
red-discordbot  |   File "/data/cogs/Downloader/lib/piccolo/engine/postgres.py", line 374, in __init__
red-discordbot  |     super().__init__(
red-discordbot  |   File "/data/cogs/Downloader/lib/piccolo/engine/base.py", line 105, in __init__
red-discordbot  |     run_sync(self.prep_database())
red-discordbot  |   File "/data/cogs/Downloader/lib/piccolo/utils/sync.py", line 24, in run_sync
red-discordbot  |     return future.result()
red-discordbot  |            ^^^^^^^^^^^^^^^
red-discordbot  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
red-discordbot  |     return self.__get_result()
red-discordbot  |            ^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
red-discordbot  |     raise self._exception
red-discordbot  |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
red-discordbot  |     result = self.fn(*self.args, **self.kwargs)
red-discordbot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
red-discordbot  |     return runner.run(main)
red-discordbot  |            ^^^^^^^^^^^^^^^^
red-discordbot  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
red-discordbot  |     return self._loop.run_until_complete(task)
red-discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
red-discordbot  |   File "/data/cogs/Downloader/lib/piccolo/engine/postgres.py", line 419, in prep_database
red-discordbot  |     await self._run_in_new_connection(
red-discordbot  |   File "/data/cogs/Downloader/lib/piccolo/engine/postgres.py", line 523, in _run_in_new_connection
red-discordbot  |     connection = await self.get_new_connection()
red-discordbot  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "/data/cogs/Downloader/lib/piccolo/engine/postgres.py", line 478, in get_new_connection
red-discordbot  |     return await asyncpg.connect(**self.config)
red-discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "/data/cogs/Downloader/lib/asyncpg/connection.py", line 2329, in connect
red-discordbot  |     return await connect_utils._connect(
red-discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "/data/cogs/Downloader/lib/asyncpg/connect_utils.py", line 1017, in _connect
red-discordbot  |     raise last_error or exceptions.TargetServerAttributeNotMatched(
red-discordbot  |   File "/data/cogs/Downloader/lib/asyncpg/connect_utils.py", line 991, in _connect
red-discordbot  |     conn = await _connect_addr(
red-discordbot  |            ^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "/data/cogs/Downloader/lib/asyncpg/connect_utils.py", line 828, in _connect_addr
red-discordbot  |     return await __connect_addr(params, True, *args)
red-discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "/data/cogs/Downloader/lib/asyncpg/connect_utils.py", line 873, in __connect_addr
red-discordbot  |     tr, pr = await connector
red-discordbot  |              ^^^^^^^^^^^^^^^
red-discordbot  |   File "/data/cogs/Downloader/lib/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
red-discordbot  |     tr, pr = await loop.create_connection(
red-discordbot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
red-discordbot  |   File "uvloop/loop.pyx", line 2039, in create_connection
red-discordbot  |   File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
red-discordbot  | ConnectionRefusedError: [Errno 111] Connection refused

i dont know what to do, pls help

Red version        │ 3.5.13
Discord.py version │ 2.4.0

**Comment by yamikaitou** [comment]
That is a 3rd party cog, you'll need to seek help from the Pylav author

**Comment by mizabmdgg** [comment]
> That is a 3rd party cog, you'll need to seek help from the Pylav author

what? oh my bad, i think it`s default cog

**Comment by yamikaitou** [comment]
The bot does come with an Audio cog, but that traceback shows pylav. If you don't want to use that one, you can uninstall it and then load the built-in audio cog
