### ISSUE TITLE
Centos 7 Installer script

### ISSUE THREAD

**Issue by samppanja** [Cog-Creators/Red-DiscordBot#649]
This automates installing the bot on centos 7.
Tested on "vanilla" centos 7.
All it basically does is install dependencies for building ffmpeg and python3.5.

https://gist.github.com/pepsifire/4e7db7544ce1b3e654d417f83cfd2bcb

If you have sudo timeout enabled, (sudo asks password if no commands were used in a while) you have to retype the password after building ffmpeg.
Current workaround: use options 2,3 and 4.

Would be nice if someone else could test this too and report if it works.

**Comment by skeith** [comment]
You don't need these I think
```
	sudo yum -y install python35u-3.5.2
```

Also what's the difference between `sudo yum -y install python35u-pip` and
```
wget https://bootstrap.pypa.io/get-pip.py
sudo python3.5 get-pip.py
```

**Comment by samppanja** [comment]
Yeah it seems that
`sudo yum -y install python35u-3.5.2`
is incorrect
also there is no difference between (it's literally using the script it seems)
`python35u-pip` and `get-pip-py` but its there so it automatically gets updated to the newest supported version.

> Name        : python35u-pip
Arch        : noarch
Version     : 9.0.1
Release     : 1.ius.centos7
Size        : 9.2 M
Repo        : installed
From repo   : ius
Summary     : A tool for installing and managing Python packages
URL         : https://pip.pypa.io
License     : MIT
Description : Pip is a replacement for `easy_install
            : <http://peak.telecommunity.com/DevCenter/EasyInstall>`_.  It uses
            : mostly the same techniques for finding packages, so packages that
            : were made easy_installable should be pip-installable as well.

I think it's just nicer to have it update with the system.

**Comment by tekulvw** [comment]
Out of curiosity, does [pyenv](https://github.com/pyenv/pyenv) work on CentOS?

**Comment by skeith** [comment]
@pepsifire so if the user upgrade it via `pip -install -U pip` it is the same as if they use `yum` to uograde right?

**Comment by Pjinky** [comment]
The script is missing ffmpeg-devel "yum -y install ffmpeg ffmpeg-devel"

**Comment by samppanja** [comment]
@Pjinky how about you look at the script and see that it compiles it
@skeith yes its practically the same but that could break it if it's executed, not sure though

**Comment by Pjinky** [comment]
For some reason mine missed it then...?

**Comment by MiniJennJenn** [comment]
shhh be nice

**Comment by palmtree5** [comment]
@Pjinky did you select the option to install ffmpeg in the menu the script provides?

**Comment by Kowlin** [comment]
done in https://github.com/Twentysix26/Red-Docs/commit/0902417a129ee153040ce4969a2d90fdaacc415a
