### ISSUE TITLE
how to change owner id

### ISSUE THREAD

**Issue by P4rtyguy** [Cog-Creators/Red-DiscordBot#653]

**Comment by ghost** [comment]
Ok so in Discord you run [p]set owner. Then you goto console and verify the account that you are giving owner to.

**Comment by P4rtyguy** [comment]
but there is already other owner "old account"

**Comment by Stylite** [comment]
Ok so on the new account run [p]set owner and in console confirm it. That will switch it from the "old account" to the "new account"

**Comment by P4rtyguy** [comment]
thanks :)
