### ISSUE TITLE
[Suggestion] Add Picarto to stream cog

### ISSUE THREAD

**Issue by Kyrislian** [Cog-Creators/Red-DiscordBot#656]
As the title says :3 Would love to see Picarto included in the stream cog as it's widely used by artists!

**Comment by Kowlin** [comment]
API Documentation: https://gist.github.com/Tschrock/a980c557c8bfdf020228a5f07e176f61

Requires API key.

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/5b885b82c4071abb43088521d2c254f9c863ec4a
