### ISSUE TITLE
keep getting an error when i try to install req

### ISSUE THREAD

**Issue by KatameUzaki** [Cog-Creators/Red-DiscordBot#659]
So recently i had to factory restore my pc and i was trying to redownload all the prgrams and stuff i had before the restore Red discord bot was one of them but i keep getting this dang eror message and i dont know what is causing it any feed back will greatly appreciated
Here is a screen shot
![red](https://cloud.githubusercontent.com/assets/26378769/23849793/e6c8d044-07aa-11e7-8449-cb7fde9554b6.png)

**Comment by Twentysix26** [comment]
Python 3.5 needed.

**Comment by palmtree5** [comment]
https://www.python.org/downloads/release/python-353/

**Comment by Twentysix26** [comment]
I assume this is solved.
