### ISSUE TITLE
Sytax error

### ISSUE THREAD

**Issue by zeonyphus** [Cog-Creators/Red-DiscordBot#66]
It wont run, this is all I know.

`E:\Bots\Red-DiscordBot>python red.py
  File "red.py", line 35
    async def on_ready():
        ^
SyntaxError: invalid syntax`

**Comment by jaw3l** [comment]
install discord.py first

**Comment by zeonyphus** [comment]
Oh okay thanks I forgot to download that

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/wiki/Troubleshooting
see "Invalid syntax"
