### ISSUE TITLE
[Suggestion] Deletion of messages after time

### ISSUE THREAD

**Issue by ModdyLP** [Cog-Creators/Red-DiscordBot#664]
Hello,

can you add an option, that the bots delete the invoking messages and his own messages after 30 seconds? Also it would be nice if you can add that the bot can delete messages, which are older than 14 days. I think you can delete the messages with seperated delete requests instead of an bulk request. 

Best Regards
ModdyLP

**Comment by Kowlin** [comment]
Congratz! This is already been done for you with ``modset deletedelay``! This will delete the command message, as for deleting messages older then 14 days, last time I checked we're waiting for the endpoint from Discord for that.

**Comment by Twentysix26** [comment]
This doesn't sound implementable in a proper way, if we want to avoid breaking current cogs. We can't distinguish messages that aren't supposed to be deleted so this would have major side effects. Closing.
