### ISSUE TITLE
HTTPException when using "[p]reason" command

### ISSUE THREAD

**Issue by CRASNY** [Cog-Creators/Red-DiscordBot#665]
`Error in command 'reason' - HTTPException: BAD REQUEST (status code: 400)`

> [19/03/2017 00:10] ERROR red on_command_error 344: Exception in command 'reason'.
> Traceback (most recent call last):
>   File "lib\discord\ext\commands\core.py", line 50, in wrapped
>     ret = yield from coro(*args, **kwargs)
>   File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\mod.py", line 989, in reason
>     reason=reason)
>   File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\mod.py", line 1464, in update_case
>     msg = await self.bot.get_message(channel, case["message"])
>   File "lib\discord\client.py", line 1474, in get_message
>     data = yield from self.http.get_message(channel.id, id)
>   File "lib\discord\http.py", line 198, in request
>     raise HTTPException(r, data)
> discord.errors.HTTPException: BAD REQUEST (status code: 400)

This is happening when I try to add a reason to a mod-log case with the latest version of mod.py. Any ideas? Thanks a lot for working on Red, it's a great bot.

**Comment by Twentysix26** [comment]
Is this for any (old and new) case or just a particular one?
