### ISSUE TITLE
Bot refuses to autorestart without console interaction

### ISSUE THREAD

**Issue by Isaiahfeldt** [Cog-Creators/Red-DiscordBot#666]
As the titles says, running the bot in "autorestart" mode and using the #shutdown command results in the bot turning off and staying off until action is taking in the console. 

`Task was destroyed but it is pending!`
`task: <Task pending coro=<Streams.stream_checker() running at C:\MYDIRECTORY_BLAHBLAH\Red-DiscordBot\cogs\streams.py:465> wait_for=<Future pending cb=[Task._wakeup()]>>`
`Red has been terminated. Exit code: 0`
`Press enter to continue.`

Tested with stock Red-DiscordBot on a commercial-grade server and sure enough it still happens. 

----
**What was supposed to happen:**
Ran bot in autorestart mode expecting it to auto restart after shutdown or crash.

**What actually happned:**
Console demands I press a key to continue the shutdown process, therefore eliminating the usefulness of a autorestart function.

**Comment by Twentysix26** [comment]
This is by design. You are asking for a shutdown and it shuts down, regardless of the restart mode.  
Use `[p]restart`
