### ISSUE TITLE
[YouTube] Extra methods of adding songs to que.

### ISSUE THREAD

**Issue by ghostnegotiator** [Cog-Creators/Red-DiscordBot#674]
Hello there,

Is it possible to get the youtube cog being able to search trough the following method:

!yt qUVG3BQIFBk

This would greatly improve for people with more or less experience with the bot.

When using "!yt qUVG3BQIFBk" it produces the following error:

```
Mar 22 14:43:10 Dockerbox python3.5[24624]: Make sure to keep your bot updated. Select the 'Update' option from the launcher.
Mar 22 14:43:43 Dockerbox python3.5[24624]: Task exception was never retrieved
Mar 22 14:43:43 Dockerbox python3.5[24624]: future: <Task finished coro=<Audio.queue_manager() done, defined at /home/rdash/red/cogs/audio.py:2027> exception=AttributeError("'NoneType' object has no attribut
Mar 22 14:43:43 Dockerbox python3.5[24624]: Traceback (most recent call last):
Mar 22 14:43:43 Dockerbox python3.5[24624]: File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
Mar 22 14:43:43 Dockerbox python3.5[24624]: result = coro.send(None)
Mar 22 14:43:43 Dockerbox python3.5[24624]: File "/home/rdash/red/cogs/audio.py", line 2060, in queue_manager
Mar 22 14:43:43 Dockerbox python3.5[24624]: song = await self._play(sid, url)
Mar 22 14:43:43 Dockerbox python3.5[24624]: File "/home/rdash/red/cogs/audio.py", line 810, in _play
Mar 22 14:43:43 Dockerbox python3.5[24624]: song = await self._guarantee_downloaded(server, url)
Mar 22 14:43:43 Dockerbox python3.5[24624]: File "/home/rdash/red/cogs/audio.py", line 606, in _guarantee_downloaded
Mar 22 14:43:43 Dockerbox python3.5[24624]: self.downloaders[server.id].duration_check()
Mar 22 14:43:43 Dockerbox python3.5[24624]: File "/home/rdash/red/cogs/audio.py", line 256, in duration_check
Mar 22 14:43:43 Dockerbox python3.5[24624]: log.debug("duration {} for songid {}".format(self.song.duration,
Mar 22 14:43:43 Dockerbox python3.5[24624]: AttributeError: 'NoneType' object has no attribute 'duration'
```

**Comment by Twentysix26** [comment]
What's wrong with `[p]play` / `[p]queue` and the full URL? `[p]yt` is not for URLs

**Comment by ghostnegotiator** [comment]
There's nothing wrong with that although with this additional regex would ease up allot on the community where the discord bot is going to run on since it has 1000+ on its current user base.

**Comment by Twentysix26** [comment]
I can't say I have ever seen anyone attempt that. People either copy the full URL (which is even less hassle than copying just the ID) or play it by using the title. I don't see the use of this.

**Comment by ghostnegotiator** [comment]
Basically due the size of the community + nature of the collaboration of that community it would be great to have such feature with the bot. And ease up on moderation and the embedded links (I know it can be disabled trough permissions) hence for safe keeping would be pretty great addition. Not just for the Discord server I am talking about but would also would be useful for other servers as well who preffer this way to que the songs.

**Comment by Twentysix26** [comment]
The only valid point you brought up is embeds. Users can avoid them by wrapping the URL in `< >` or you can, as you pointed out, disable embeds through permissions.  
You could also decide to remove the commands' message after a few seconds with the already existing options.  
I'm not particularly interested in adding this to the current Audio cog, especially as it goes against what the `[p]yt` command is for.  
We might consider this for the audio rewrite that is in progress.
