### ISSUE TITLE
Git: Unknown option: -C

### ISSUE THREAD

**Issue by Brandjuh** [Cog-Creators/Red-DiscordBot#676]
I have this problem a few weeks now and I do not know how to fix this on centos-release-6-8.el6.centos.12.3.x86_64.

When I want update my cogs and I typ !cog update then I get this error:

```
Downloading updated cogs, please wait... done.  No updates to apply. 
The following repos failed to update: 
pluginname: Error resetting to HEAD
```

and in the console:

```
Unknown option: -C
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]
```

**Comment by calebj** [comment]
What version of Git are you running?

**Comment by Brandjuh** [comment]
[root@srv1 ~]# git --version
git version 1.7.1
[root@srv1 ~]#


Package git-1.7.1-4.el6_7.1.x86_64 already installed and latest version
Nothing to do

**Comment by Twentysix26** [comment]
The `-C` flag was introduced back in git 1.8.5 (2013). We make extensive use of it.

Update your git.

**Comment by Brandjuh** [comment]
I didn't had this problem before. It just started random out of know where. No system changes also.

**Comment by skeith** [comment]
can't you just try updating your git then report back if the problem still persist?

**Comment by Brandjuh** [comment]
I would not posted this problem if I didn't tried to update git. As you can see I had post the shell output. 

Instead if giving saying: "Update git" and close the topic you can give me at least a hint where I can look to force a update. Not everybody is that good in linux. 

Yes then I reply on a closed topic. But I will look somewhere else for the support.

**Comment by skeith** [comment]
Red Hat Enterprise Linux, Oracle Linux, CentOS, Scientific Linux, et al.

RHEL and derivatives typically ship older versions of git. You can download a tarball and build from source, or use a 3rd-party repository such as the IUS Community Project to obtain a more recent version of git.

Source : https://git-scm.com/download/linux

I was in assumption that you are tech savvy since you used Centos

**Comment by Kowlin** [comment]
huh, quite surprising that RHEL ship with an outdated version of Git. I'm meeting a SysAdmin who works with RH and I'll ask him what to do in this scenario.

**Comment by Twentysix26** [comment]
I gave you the solution to your issue. I don't know why you're under the impression that it's my duty to teach you how to use your own operating system. Perhaps stick to one you're familiar with next time.

**Comment by Brandjuh** [comment]
For people with not that huge experience in CentOs because they have a VPS with DirectAdmin (for a little website as example) but are willing to learn how to update git. This one is working for me. 
http://slashsarc.com/2013/01/install-git-1-8-x-on-rhel-5-and-6/

@Twentysix26 I do understand why you are saying, but its just the way how its looks. "Update git" bam closed. You did read that it was saying it was up-to-date. Instead of closing it you could say. 

"You need to update your git from another source, since there are more possible solutions and linux builds you need to look for..... Since its not related to a update of red, I do not provide more support and close the ticket."

That's the friendly version. 

Problem solved.

**Comment by Brandjuh** [comment]
Quote from discord:
> I want give you my excuse for my behavior on my help question on github. I am reading it back, its not >good what I said. I had a really bad day since a good friend is deceased and I did reflect that to you. >Again, sorry!
