### ISSUE TITLE
Failed to load cogs.audio

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#679]
I'm using VPS with CentOS 7. The problem is "Failed to load cogs.audio" on console and message from bot when I type _!load audio_. Message here: _Cog was found and possibly loaded but something went wrong. Check your console or logs for more information._ 😕

**Comment by Twentysix26** [comment]
>Check your console or logs for more information.

Please do and report here.

**Comment by ghost** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/6854256/24410495/7da8fa46-13d3-11e7-9f9a-060c83f642c8.png)

**Comment by Twentysix26** [comment]
You need either ffmpeg or avconv for it to work.

**Comment by ghost** [comment]
Thanks! 😃
