### ISSUE TITLE
Suggestion: Handle permission errors better.

### ISSUE THREAD

**Issue by Shigbeard** [Cog-Creators/Red-DiscordBot#68]
So, basically I keep getting errors when people try to use the bot in a channel it doesn't have perms to chat in/etc.

These errors silently fail operations such as !ignore channel all due to the fact that they cannot say something in that chat room.

Perhaps if (during that session), the bot discovers it doesn't have permission to do something with a text channel, it "temporarily" ignores that channel, until told to restart.

At the very least, an easier-to-understand error should be provided. Having a full screen of traceback doesn't help when you could easily just say "Red couldn't read/write a message from/to channelnamehere, are you sure you have permission?"

For reference...

![http://i.imgur.com/2PBwosP.png](http://i.imgur.com/2PBwosP.png)

**Comment by tekulvw** [comment]
Can be done by overriding `on_error`, planning to get to this in #187
