### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Tazer89** [Cog-Creators/Red-DiscordBot#680]
File "red.py", line 80
    async def send_message(self, *args, **kwargs):
            ^
SyntaxError: invalid syntax

**Comment by Jan200101** [comment]
what python version are you using ?

**Comment by Tazer89** [comment]
Python 3.4.2

**Comment by Jan200101** [comment]
Red is build for Python 3.5 and above

**Comment by Kowlin** [comment]
Red requires Python 3.5+, for more information. See our [docs](https://twentysix26.github.io/Red-Docs/)
