### ISSUE TITLE
Issue with the starwars trivia questions

### ISSUE THREAD

**Issue by Harmelodic** [Cog-Creators/Red-DiscordBot#683]
One of the questions queries how many clones were ready on Kamino.

The current answer is 1000000, however this is incorrect, it's actually 200000.

Source: https://www.youtube.com/watch?v=3dovd1clLJ4&feature=youtu.be&t=1m54s

**Comment by MiniJennJenn** [comment]
Thanks, will be fixed in the next trivia PR

**Comment by Twentysix26** [comment]
Fixed in #772
