### ISSUE TITLE
[Economy] Leaderboard should display current username

### ISSUE THREAD

**Issue by Twentysix26** [Cog-Creators/Red-DiscordBot#687]
Right now it displays the one stored in the account's data, which dates back to when the user first signed up

**Comment by Chovin** [comment]
what do you want to do with users that leave? 
Want to keep the username they had before they left or don't show those users in the leaderboard?

**Comment by Twentysix26** [comment]
I think it might make more sense for them not to show up

**Comment by Kowlin** [comment]
*cugh* ``member.diplay_name``

**Comment by Twentysix26** [comment]
Decided to use `.display_name` in the local leaderboard, name + discrim in the global one. People who left won't be displayed.
