### ISSUE TITLE
Cannot find command 'git'

### ISSUE THREAD

**Issue by GhostHatsuneMikuChan** [Cog-Creators/Red-DiscordBot#688]
I have a error saying this: Error [WinError 2] The system cannot find the file specified while executing command git clone -q git://github.com/Rapptz/discord.py.git C:\Users\Dad\AppData\Local\Temp\pip-build-hck7qw73\discord.py
Cannot find command 'git'

**Comment by Twentysix26** [comment]
You need git installed and in PATH. If you already installed it and checked the PATH settings reboot your system.
