### ISSUE TITLE
Suggestion: Allow whitespace/newlines in customcommand body

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#69]
Multiline replies from custom commands are turned into 1 liners because of the way *text is handled. Quick fix is to use context message contents instead of the text arg and strip out the !addcom and command name from the first part of the contents string.

Or change how *text works? Not sure what'd be involved in that but having *text give you a string body which the user can then split() might be better.

**Comment by Twentysix26** [comment]
Aaand done :)
