### ISSUE TITLE
In the audio cog, does the local command even mean anything?

### ISSUE THREAD

**Issue by athraxkobal** [Cog-Creators/Red-DiscordBot#690]
I don't know what it does. Someone explain?

The local command is pretty useless to me, as it does nothing.
Only has list and start as sub commands if I remember correctly.

**Comment by palmtree5** [comment]
have you done `[p]help local`?

**Comment by Jan200101** [comment]
local allows you to play local audio tracks

**Comment by Twentysix26** [comment]
https://twentysix26.github.io/Red-Docs/red_audio/

**Comment by athraxkobal** [comment]
palm, it only lists the list and start subcommand.
Senty, I know.
Twentysix, I'll check it out.

**Comment by athraxkobal** [comment]
Ah, now I see. Thanks buddy.
