### ISSUE TITLE
Bot music stops randomly

### ISSUE THREAD

**Issue by SweggyMelonPie** [Cog-Creators/Red-DiscordBot#691]
I have a youtube playlist that my bot is playing and for no reason it stops randomly. I have updated everything, have all the requirements and even reinstalled the bot completly along with python and this shows up when the music stops.
![discord bot error](https://cloud.githubusercontent.com/assets/19377968/24583517/f2742b6c-171a-11e7-9bea-11e909589855.PNG)

**Comment by Kowlin** [comment]
Discord closed the connection between the bot and the voice server. There was no reason given for this. (See last line of the error) Sadly due the nature of this error there is nothing we can do.

**Comment by SweggyMelonPie** [comment]
Ok thanks for clarifying
