### ISSUE TITLE
Music Stoping Randomly

### ISSUE THREAD

**Issue by LacroyPlays** [Cog-Creators/Red-DiscordBot#692]
The Music Stoping Randomly

**Comment by Stylite** [comment]
Can you post what you use in console

**Comment by LacroyPlays** [comment]
i just did ;;play the song i wanted

**Comment by Stylite** [comment]
What you see in the command prompt/console. Can you post that

**Comment by LacroyPlays** [comment]
the discord chat

**Comment by LacroyPlays** [comment]
?

**Comment by LacroyPlays** [comment]
it cuts out then plays again

**Comment by Stylite** [comment]
No in the command prompt window

**Comment by LacroyPlays** [comment]
i dont have a command promt window

**Comment by LacroyPlays** [comment]
i use discord

**Comment by Stylite** [comment]
Are you hosting the bot and could you come to the discord support channel at discord.gg/red

**Comment by LacroyPlays** [comment]
sure'

**Comment by LacroyPlays** [comment]
i dont host the bot

**Comment by Stylite** [comment]
Then you can't fix the issue. Just try and change discord region for the voice channel.

**Comment by LacroyPlays** [comment]
ok thanks for your help mate :)
