### ISSUE TITLE
[DIY FIX] .txt playlist to .json

### ISSUE THREAD

**Issue by bbassie** [Cog-Creators/Red-DiscordBot#694]
Why? The content of the file is already JSON so why make it .txt?

1. Replace ".txt" with ".json" in the file "<red discord bot location>/cogs/audio.py"
2. Change on line 666,
 From:
 ```PYTHON
 old_playlists = [f[:-4] for f in os.listdir(path)
 ```
To:
```PYTHON
old_playlists = [f[:-5] for f in os.listdir(path)
```
3. Change on line 670,
From:
```PYTHON
new_playlists = [f[:-4] for f in os.listdir(path)
```
To:
```PYTHON
new_playlists = [f[:-5] for f in os.listdir(path)
```
Note this is a DIY fix some problems may occur (it worked for me and just wanted to share and maybe you guys can make it so it is like this in the new update?)

**Comment by Twentysix26** [comment]
I am aware of the inconsistency. It may be dealt with in [the rewrite](https://github.com/Twentysix26/Red-DiscordBot/pull/616). I see no reason to change it now and cause issues with existing playlists.
