### ISSUE TITLE
Bot crashing on using !next command to change song [Crashlog + reproductible at will]

### ISSUE THREAD

**Issue by nobodie** [Cog-Creators/Red-DiscordBot#696]
Bot is Fresh installed (new user here), updated everything as adviced.

I am connected to discord with a friend, we are 2 in the voice channel, playing music.

Playing a song from youtube => Playing a second one that gets queued => using command !next to switch to the second song => my mate doesnt use !next because the threshhold is met => bot crashes with the following error :

> future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at lib\discord\voice_client.py:269> exception=ConnectionClosed('WebSocket connection is closed: code = 1002, no reason.',)>
> Traceback (most recent call last):
>   File "lib\discord\gateway.py", line 635, in poll_event
>     msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
>   File "C:\Users\bastien\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py", line 352, in wait_for
>     return fut.result()
>   File "lib\websockets\protocol.py", line 299, in recv
>     raise ConnectionClosed(self.close_code, self.close_reason)
> websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1002, no reason.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "lib\discord\voice_client.py", line 276, in poll_voice_ws
>     yield from self.ws.poll_event()
>   File "lib\discord\gateway.py", line 638, in poll_event
>     raise ConnectionClosed(e) from e
> discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1002, no reason.

As far as I have seen, it happens everytime we test it (tested 4 times in a row).

PS : Markdown for code seems not to work, or I used it badly so had to quote it instead, sorry for that

**Comment by tekulvw** [comment]
`next` isn't actually a command provided by the audio cog. I'm assuming you meant either `skip` or you've created an alias that calls `skip`.

Regardless, the error you've mentioned is not something we can stop, it's signifying that the discord voice server has forcibly closed your connection without telling you a reason. I'm also gonna guess that this problem has gone away for you since you haven't tried to bump the issue since April.
