### ISSUE TITLE
fuzzysearch recommendations for !help

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Red-DiscordBot#697]
suggestion:

!help playing

non-fuzzy example:
```
No command called "playing" found. Did you mean..

1   [p]audioset thumb       Toggles displaying song thumbnail where applicable
2   [p]audiostat servers    Number of servers currently playing.
3   [p]queue                Queues a song to play next. Extended functionality in `[p]help`
4   [p]set game             Sets Red's playing status
5   [p]stop                 Stops a currently playing song or playlist. CLEARS QUEUE.
```

additionally, for my lazy self:

4 Sublime Text

```
Done.
```
(invoked [p]set game Sublime Text)

**Comment by Kowlin** [comment]
I would like this but yyee... then we will have the problem of our "we don't have help in Red" and I kinda like that.

**Comment by Chovin** [comment]
I agree..
Maybe as a separate cog...

**Comment by calebj** [comment]
If you want to do this for commands normally, you can use `on_command_error` and checking if it is `commands.CommandNotFound`, I think. The additional cog would need to pull in dependencies like [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) for comparison of keys and docstrings loaded from `bot.commands` and subcommands for command groups.

To replace `[p]help`, you can unload the command. I figured out the code to reload the regular command from discord.py, which can be put in this hypothetical cog's `__unload` method.

**Comment by Kowlin** [comment]
Judging from the above example I think this is meant to be only run on the ``help`` command.

**Comment by Kowlin** [comment]
To be done in V3's new help formatter.
