### ISSUE TITLE
Mod cog is becoming huge (and essential)

### ISSUE THREAD

**Issue by Twentysix26** [Cog-Creators/Red-DiscordBot#700]
## The problem
The mod cog is becoming huge and covers too many functionalities.  
It contains features that do not belong there and, worse, core functions that shouldn't be possible to deactivate.  

It its current state it contains:
* Moderation commands
* A full fledged mod-log (with a pending PR that turns it into an API)
* Some logging features (names, nicknames, etc)
* Filters / spam prevention
* Global blacklist / whitelist
* Commands to set server's admin role and mod role. While of course related to moderation, these roles are used by all cogs and the commands used to set them shouldn't be stuck in mod.py
* Settings such as autodeletion of commands

And I'm probably forgetting something.

This isn't good, the user should be free to disable the mod cog without losing core functionalities. At the moment, disabling mod.py means losing the admin / mod role checks that all cogs use.
This also limits customizability. If you want auto command deletion it means that you're also getting everything else.

## Proposed solution
Let's start with moving some functions out. The first ones to go are the ones listed above that do not belong in mod.py at all.
Moving the modlog to its own cog might be preferable too, although not strictly necessary, as I expect most people who use it also use our moderation commands.
Thoughts? Design suggestions?

## Status:

- [x] Moved whitelist commands to owner cog
- [x] Moved modrole / adminrole commands to owner cog, under `[p]set`

**Comment by palmtree5** [comment]
If modlog is to be moved to its own cog, then mod needs to make sure it's loaded. Also I'll have to update my PR accordingly

**Comment by palmtree5** [comment]
I'd say the settings, the mod/admin role setting commands, and the global blacklist/whitelist should be moved out of mod (probably to owner)

**Comment by Twentysix26** [comment]
@palmtree5 That's the plan, already in the PR

**Comment by palmtree5** [comment]
Got it. On the other stuff, I'm not sure the logging features necessarily belong in mod. I'd say filters/spam prevention stuff could stay where it is though

**Comment by palmtree5** [comment]
Thinking about the idea of separating modlog. On loading mod (or any other cog that would use the modlog), we'd need to ensure the modlog cog is loaded or else fail to load and tell the user why. And if someone tries to unload the modlog, we need to handle unloading any cogs that depend on it as well (which means probably maintaining a manual registry of what cogs depend on it as a settings file for modlog)

**Comment by palmtree5** [comment]
I'm thinking server/channel ignore/unignore could also be moved elsewhere

**Comment by palmtree5** [comment]
Ok, so despite my PR (#709) moving ignore and unignore to Owner, maybe it's time to consider throwing in another default cog that is always loaded and cannot be unloaded unless it's a reload (core.py). This would contain things that should be available all the time but that perhaps don't fit in the theme of owner (for example: ignore and unignore). Maybe there's other commands that could go in this hypothetical new cog too

**Comment by palmtree5** [comment]
Another candidate for core.py: Cog-Creators/Cog-Board/issues/25

Since it's likely the checks would be done in red.py

Actually, maybe the per-server modrole/adminrole/prefix settings could also be moved there as well

If cogs ever become per-server, the server-specific commands for turning cogs on and off could probably go in core.py as well

**Comment by tekulvw** [comment]
@palmtree5 @Twentysix26 do we need this anymore?

**Comment by Twentysix26** [comment]
I don't have plans for further debloating

**Comment by palmtree5** [comment]
I've been splitting things between files in the rewrite (though they're still in `cogs/mod`) and then loading each using `bot.add_cog` in the package's `__init__.py`

**Comment by tekulvw** [comment]
Okay so the decisions have been made and this issue can be closed?

**Comment by Twentysix26** [comment]
👌
