### ISSUE TITLE
extension : web control interface

### ISSUE THREAD

**Issue by JordanB-1337** [Cog-Creators/Red-DiscordBot#702]
I believe I may have mentioned this on Discord, but it was washed away after a different discussion was posted shortly after.

So basically my idea is to have a similar interface to mee6/dyno/dab and have it be hosted on localhost.
The heiarchy would be similar to the existing way Red works.
I can make mockups in Balsamiq if nessessary don't know if something as low-level as this would be right.

**Comment by Twentysix26** [comment]
We have no plans for this at the current time.

**Comment by JordanB-1337** [comment]
I know, I'm trying to make it as a cog.

**Comment by JordanB-1337** [comment]
but thanks anyway for the response
