### ISSUE TITLE
Pip problem.

### ISSUE THREAD

**Issue by ZoruaQWERTY** [Cog-Creators/Red-DiscordBot#705]
Lately I've had a problem installing Pip, but I've tried many things:
Using the installer on Red and many things without Red.
If anyone can help, that would be great!

**Comment by Stylite** [comment]
Can you show what console says and join the discord server so you can help faster. https://discord.gg/red

**Comment by ZoruaQWERTY** [comment]
No it's downloaded Pip red has downloaded it but cmd never notices it and it just says pip is a unknown batch file.

**Comment by Stylite** [comment]
What os are you

**Comment by ZoruaQWERTY** [comment]
Windows 10.

**Comment by Kowlin** [comment]
Incase you just installed python (and with it pip) you might have to restart your system for the changes to apply.

**Comment by ZoruaQWERTY** [comment]
I've waited for a week or 2 before saying anything.

**Comment by Kowlin** [comment]
The only problem i can think of then is that you installed python without adding it to the path. To resolve this you have to reinstall python with the path option enabled. See our windows docs for more information.

**Comment by tekulvw** [comment]
Have you rebooted since you installed Python? Windows path sometimes doesn't update til that happens...Because, y'know, windows

**Comment by ZoruaQWERTY** [comment]
But I've re installed python multiple times.
I even tried downloading 3.4.2 and that didn't work.

**Comment by ZoruaQWERTY** [comment]
Yes, I have rebooted, multiple times.

**Comment by ZoruaQWERTY** [comment]
![capturetemp](https://cloud.githubusercontent.com/assets/27345267/24955664/444f9fe8-1f7c-11e7-87de-9f3cd747077b.PNG)

**Comment by tekulvw** [comment]
Go to control panel > search for "environment" > view/edit your system environment variables > double click/edit/view PATH and see if the main Python folder is in there AS WELL AS "MAIN_FOLDER/Scripts"

**Comment by tekulvw** [comment]
Uhh..What exactly isn't working then

**Comment by ZoruaQWERTY** [comment]
You know that you need Pip to install certain cogs?
Aka Pip just decides not to work.

**Comment by tekulvw** [comment]
How about `python -m pip`

**Comment by ZoruaQWERTY** [comment]
That doesn't work at all.
On python it self it says invalid syntax.
On cmd unrecognized batch file.

**Comment by tekulvw** [comment]
I don't believe you, screen shot it

**Comment by ZoruaQWERTY** [comment]
Tek, when I go over there all I see in there is 
![capturetemp](https://cloud.githubusercontent.com/assets/27345267/24955880/22a0995a-1f7d-11e7-8cf8-8e8bfe38d313.PNG)

**Comment by tekulvw** [comment]
And then do `where python.exe`

**Comment by ZoruaQWERTY** [comment]
Okay then.
![capturetemp](https://cloud.githubusercontent.com/assets/27345267/24955915/42f29ffa-1f7d-11e7-96bb-2382de992142.PNG)
![capture2](https://cloud.githubusercontent.com/assets/27345267/24955942/5c59597a-1f7d-11e7-8190-1d0c72a505bd.PNG)

**Comment by ZoruaQWERTY** [comment]
In what line Tek?

**Comment by tekulvw** [comment]
Edit user path and see if it's in there

**Comment by ZoruaQWERTY** [comment]
Ok

**Comment by tekulvw** [comment]
How the hell did you get a Python interpreter open?

**Comment by ZoruaQWERTY** [comment]
That's only Python command line and CMD.
Btw it's all the same if I edit it though.

**Comment by tekulvw** [comment]
Python "command line" is really named the Python interpreter. When I've told you to do commands I meant for them to be done on the actual command line. Now, how did you get the Python interpreter open?

**Comment by ZoruaQWERTY** [comment]
All I did was put in the search bar Python and found it there.

**Comment by ZoruaQWERTY** [comment]
That's why  I did on CMD and there just to avoid confusion though.

**Comment by tekulvw** [comment]
Well this means that you don't have Python in path. So, do as kowlin suggested and reinstall WITH THE PATH CHECK BOX MANUALLY TICKED

**Comment by ZoruaQWERTY** [comment]
What path should I set it as then?

**Comment by Chovin** [comment]
[![image](https://cloud.githubusercontent.com/assets/17536161/24956351/90740280-1fca-11e7-96f1-9c43d7e78a2f.png)](https://twentysix26.github.io/Red-Docs/red_install_windows/)

You should let the installer set it for you. see the red box near the bottom.
If that doesn't work, let us know.

Next time, please head over to our [support server](https://discord.gg/red)
We are getting a ton of notifications from this thread :P

**Comment by ZoruaQWERTY** [comment]
Okay then.

**Comment by ZoruaQWERTY** [comment]
Re installed it on the path.

**Comment by ZoruaQWERTY** [comment]
Oh yay that made Pip work?!

**Comment by ZoruaQWERTY** [comment]
Thank you!
