### ISSUE TITLE
[cogs programming help] Mentioning user

### ISSUE THREAD

**Issue by rxdqw** [Cog-Creators/Red-DiscordBot#711]
Sorry for posting this here but I do not know where else to post this.
How do I get the bot to mention the user who posted the message using
await self.bot.say() ?

**Comment by Zephyrkul** [comment]
For future reference, there is a coding channel in the [official Red server](https://discord.gg/red). I highly recommend you join it.
As for user mentions, you can mention the member who used the command by using `ctx.message.author` to get the member, then `author.mention` to get a string that will mention that member when sent in a message.
If you have any further questions, please take it to the channel mentioned above. It's a lot easier to answer you there, we have commands that can give you useful links, and it doesn't result in spawning a bunch of GitHub issues and comments to them.

**Comment by Kowlin** [comment]
The answer seems good enough for me. Not sure if we're supporting coding on our Github since its purely dedicated to core red. like Zephyrkul said, feel free to visit the coding channel on our Discord server.
