### ISSUE TITLE
Trivia Suggestion

### ISSUE THREAD

**Issue by BMCSamael** [Cog-Creators/Red-DiscordBot#712]
Add a trivia set option for the asyncio I added below.  Players were complaining about when a lot of players know the answer there was no delay between Correctly answered questions and the next.  I added a stock sleep of 5 seconds but it might be an interesting adjustment to the bot.

        if has_guessed:
            self.current_line = None
            self.status = "correct answer"
            self.scores[message.author] += 1
            msg = "You got it {}! **+1** to you!".format(message.author.name)
            await self.bot.send_message(message.channel, msg)
            #added to slow down correct answer spam
            await asyncio.sleep(5)

**Comment by Twentysix26** [comment]
You can make a pull request if you think it might be a good addition, so people can try it out. I haven't seen much of a problem from my tests.
