### ISSUE TITLE
Cogs stuck in limbo while unloading / reloading

### ISSUE THREAD

**Issue by Jan200101** [Cog-Creators/Red-DiscordBot#714]
sometimes a cog gets stuck in limbo and you are unable to unload it.
Loading that cog again results in errors because the command its trying to add is already loaded.

There is nor reliable method of reproduction but reloading a cog often enough should result in the same behavior

**Comment by tekulvw** [comment]
This is a problem inherent in Python and d.py. Not a whole lot we can do about it.
