### ISSUE TITLE
[Suggestion] Add ability to make economy global.

### ISSUE THREAD

**Issue by copycat114** [Cog-Creators/Red-DiscordBot#715]
I would really like the option to make users' bank balances retain across all servers that the bot is on.

**Comment by Twentysix26** [comment]
To be decided for #781

**Comment by tekulvw** [comment]
It looks like this is going to be included in 781

**Comment by palmtree5** [comment]
https://github.com/Cog-Creators/Red-DiscordBot/commit/4923ffe98a998f546118f517e6c6a83f4a1bb678
