### ISSUE TITLE
Frequent errors with audio.py

### ISSUE THREAD

**Issue by CRASNY** [Cog-Creators/Red-DiscordBot#717]
Can anyone explain what's causing these?

`Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py:2048> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py", line 2085, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py", line 482, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'`

**Comment by Zephyrkul** [comment]
Update your bot and all its requirements (option 3 of the launcher).

**Comment by CRASNY** [comment]
I've updated. Is there anything specific that would be causing this? I could try to more persistently, manually update it if so.

**Comment by tekulvw** [comment]
Unless there's any additional information you can provide I'm closing this as it's a repeat of #609
