### ISSUE TITLE
Missing Image cog after update

### ISSUE THREAD

**Issue by jandauz** [Cog-Creators/Red-DiscordBot#722]
Updated Red and bot no longer responds to gif or imgur commands. I did a [p]help and noticed that the Image cog was missing.

![image](https://cloud.githubusercontent.com/assets/1077395/25176881/c4e5ec42-24cd-11e7-827d-ff811e9666c8.png)

**Comment by skeith** [comment]
Do `[p]load image`

**Comment by jandauz** [comment]
Thank you! That worked.
