### ISSUE TITLE
'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by inph8** [Cog-Creators/Red-DiscordBot#723]
This error, among an `ExtractorError`, are constantly being thrown when using the Audio module on a brand new, fresh install of Red:

> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "lib\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
>     video_id, player_url, s
>   File "lib\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflpMRrqq/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflpMRrqq/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Task exception was never retrieved
> future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py:2027> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
> Traceback (most recent call last):
>   File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py", line 2085, in queue_manager
>     await self._download_next(server, curr_dl, next_dl)
>   File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py", line 482, in _download_next
>     if curr_dl.song.id != next_dl.song.id:
> AttributeError: 'NoneType' object has no attribute 'id'
> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "lib\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
>     video_id, player_url, s
>   File "lib\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflpMRrqq/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflpMRrqq/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Task exception was never retrieved
> future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py:2027> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
> Traceback (most recent call last):
>   File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py", line 2085, in queue_manager
>     await self._download_next(server, curr_dl, next_dl)
>   File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py", line 482, in _download_next
>     if curr_dl.song.id != next_dl.song.id:
> AttributeError: 'NoneType' object has no attribute 'id'
> ERROR: Signature extraction failed: Traceback (most recent call last):
>   File "lib\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
>     video_id, player_url, s
>   File "lib\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
>     raise ExtractorError('Cannot identify player %r' % player_url)
> youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflpMRrqq/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>  (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflpMRrqq/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Task exception was never retrieved
> future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py:2027> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
> Traceback (most recent call last):
>   File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py", line 2085, in queue_manager
>     await self._download_next(server, curr_dl, next_dl)
>   File "C:\Users\Craig\Documents\Red-DiscordBot\cogs\audio.py", line 482, in _download_next
>     if curr_dl.song.id != next_dl.song.id:
> AttributeError: 'NoneType' object has no attribute 'id'

Why is this happening and how can I either prevent it or suppress these errors from flooding my console?

**Comment by Twentysix26** [comment]
Try updating the requirements from the launcher

**Comment by inph8** [comment]
I just updated Red and requirements from launcher (as Administrator) and I'm still getting the same errors. These errors happen right after each other, and continue to happen even while songs are playing if that's any help.

**Comment by Twentysix26** [comment]
Are you sure the update is succeeding? Can you provide the song URL that causes that?

**Comment by inph8** [comment]
Yes, update succeeds, here's my console log:

> ==========================
> Red Discord Bot - Launcher
> ==========================
> 
> Status: Basic + audio requirements installed
> 
> Update:
> 
> Red:
> 1. Update Red + requirements (recommended)
> 2. Update Red
> 3. Update requirements
> 
> Others:
> 4. Update pip (might require admin privileges)
> 
> 0. Go back
> > 1
> Already up-to-date.
> 
> Red has been updated
> Updating requirements...
> Collecting pip (from -r requirements.txt (line 1))
>   Using cached pip-9.0.1-py2.py3-none-any.whl
> Collecting discord.py[voice] from git+git://github.com/Rapptz/discord.py.git#egg=discord.py[voice] (from -r requirements.txt (line 2))
>   Cloning git://github.com/Rapptz/discord.py.git to c:\users\craig\appdata\local\temp\pip-build-vuv33l1b\discord.py
> Collecting youtube_dl (from -r requirements.txt (line 3))
>   Using cached youtube_dl-2017.4.17-py2.py3-none-any.whl
> Collecting imgurpython (from -r requirements.txt (line 4))
>   Using cached imgurpython-1.1.7.tar.gz
> Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]->-r requirements.txt (line 2))
>   Using cached aiohttp-1.0.5-cp35-cp35m-win_amd64.whl
> Collecting websockets<4.0,>=3.1 (from discord.py[voice]->-r requirements.txt (line 2))
>   Using cached websockets-3.3-py33.py34.py35.py36-none-any.whl
> Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 2))
>   Using cached PyNaCl-1.0.1-cp35-none-win_amd64.whl
> Collecting requests (from imgurpython->-r requirements.txt (line 4))
>   Using cached requests-2.13.0-py2.py3-none-any.whl
> Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
>   Using cached multidict-2.1.4-cp35-cp35m-win_amd64.whl
> Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
>   Using cached chardet-3.0.2-py2.py3-none-any.whl
> Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
>   Using cached async_timeout-1.2.0-py3-none-any.whl
> Collecting six (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
>   Using cached six-1.10.0-py2.py3-none-any.whl
> Collecting cffi>=1.1.0 (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
>   Using cached cffi-1.10.0-cp35-cp35m-win_amd64.whl
> Collecting pycparser (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
>   Using cached pycparser-2.17.tar.gz
> Installing collected packages: pip, multidict, chardet, async-timeout, aiohttp, websockets, six, pycparser, cffi, PyNaCl, discord.py, youtube-dl, requests, imgurpython
>   Running setup.py install for pycparser ... done
>   Running setup.py install for discord.py ... done
>   Running setup.py install for imgurpython ... done
> Successfully installed PyNaCl-1.0.1 aiohttp-1.0.5 async-timeout-1.2.0 cffi-1.10.0 chardet-3.0.2 discord.py-0.16.7 imgurpython-1.1.7 multidict-2.1.4 pip-9.0.1 pycparser-2.17 requests-2.13.0 six-1.10.0 websockets-3.3 youtube-dl-2017.4.17
> 
> Requirements setup completed.
> Press enter to continue.

The error doesn't seem to be triggered by specific songs. I got an error while playing this URL for the first time: https://www.youtube.com/watch?v=IC-bSbXZBcU - However, when playing the song again I get no errors.

These errors don't seem to cause errors in the playback, but they do a number on the console in terms of spam.

**Comment by Twentysix26** [comment]
Odd. The `Cannot identify player` error is usually very specific to outdated `youtube_dl`. I see that you have updated it though. And of course I can play the URL just fine

**Comment by tekulvw** [comment]
@inph8 do you have any other information you can provide to help us replicate the problem? It's been identified already in #609 but I'd like to make sure it's not a significantly different cause before I close this issue.
