### ISSUE TITLE
[Downloader]{patch_notes_handler} returns fatal with non HEAD branch

### ISSUE THREAD

**Issue by Ryonez** [Cog-Creators/Red-DiscordBot#725]
When updating a cog for a non head branch, the update succeeds, but no patch notes are shown.
Looking at the console, you can find:
```fatal: Invalid revision range d8d33dbc26fe526f103025b8a5ff642c87a2b582..```
Running the command through git seem to return the expected patch note

Command:
```git -C Z:\Programming\Python\Red-dev\data\downloader\ryo-cogs log --relative-date --reverse d8d33dbc26fe526f103025b8a5ff642c87a2b582.. Z:\Programming\Python\Red-dev\data/downloader/ryo-cogs\\seen\\seen.py```

This returns:
```commit 462675b9655161e3467f3b306fb765bfb9666889
Author: Ryonez <Ryonez@users.noreply.github.com>
Date:   62 minutes ago

    Commit fix search
```

Please note, this contains information about my own dev environment.

**Comment by palmtree5** [comment]
yeah, that command you posted works on my side as well and shows the same output. Though I'm getting an error pulling updates when doing cog update though that's probably on my end

**Comment by palmtree5** [comment]
yeah, turns out I was running a different copy of downloader lol

**Comment by Ryonez** [comment]
Mhm, I found when testing the code I messed up the main dev bot I use. So now I have a "scrap" one for this.

Problem is, if git's returning it, then this isn't the command red is running.

**Comment by Ryonez** [comment]
Started playing with changing the command run. 
```cmd = ["git", "commit"]```

Returns
```prolog
Patch Notes for ryo-cogs/seen
=============================
On branch develop
Your branch is up-to-date with 'origin/develop'.
Changes not staged for commit:
    modified:   cogs/downloader.py

Untracked files:
    cogs/seen.py
    lib/
    start_red.bat
    start_red_autorestart.bat

no changes added to commit
```

**Comment by Ryonez** [comment]
I found that the way repos are being added could lead to
multiple path separators being used within the "file" and "folder"
strings. This was brought about by "/" being used statically in some
locations of the downloader and the use of "os.path.join" in others.
However, it while the windows operating system, can handle this, the git
program installed cannot.
I've resolved this is by making the "patch_notes_handler" recreate the paths needed when it's called.

**Comment by Ryonez** [comment]
Implemented path changes from @palmtree5, correct some bugs introduced by it
Accounted for systems already affected by prior incorrect paths saved to "repos.json".
Updated pull request.

**Comment by AraHaan** [comment]
oh, I tbh have been working on an plugin downloader and installeer for my bot as well. But doing suck requires the system for it to work to be robust. I would also have to be able to cache the version of the plugins installed so they can be updated as well. However the whole plugin system for it is all an WIP. However because of the fact my bot's core consist of only classes and the main client class to help with all the cogs, all of it's events are actually registered in it's ``logs.py`` plugin. However I too have been trying my butt off to make an community that can help me like Red's.

**Comment by Twentysix26** [comment]
@AraHaan  I'm glad to hear you're working on something similar but I'm not sure how it's relevant to this issue
