### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by go-go-gadget** [Cog-Creators/Red-DiscordBot#732]
Hi,

Every so often, I get this error and it stops me specifically being able to play music. Is this an issue my end or with the app?

Thanks

**Comment by ticcedtac** [comment]
It's on your end/discord.py.

**Comment by go-go-gadget** [comment]
Any idea what would cause it?

**Comment by Pierce01** [comment]
I had this problem on my laptop, fixed it buy using it on my desktop/vps. Though usually its either the computer or internet connection. Make sure your anti virus isnt blocking any outward going connections.

**Comment by go-go-gadget** [comment]
Nothing seems to get rid of it for good. It works for a while then just reoccurs, and only seems to be with music

**Comment by Kowlin** [comment]
Closing this issue, something beyond of our control is interacting with the connection between Red and Discord.
