### ISSUE TITLE
[Suggestion] Audio Queues before and after song

### ISSUE THREAD

**Issue by MythicProjectz** [Cog-Creators/Red-DiscordBot#734]
I was wondering if you can add an option (probably a toggle) that shows what song is playing when the song finishes. 

So lets say a song is playing and another one is queued, now the song ends and it displays which song is now playing instead of using [p]queue every time to find out what song is playing. 

Would be highly appreciated, thanks in advanced if this ever gets implemented!

**Comment by Twentysix26** [comment]
Commonly requested feature already in #623
