### ISSUE TITLE
[Mod] deleterepeats causes embeds to be filtered

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#735]
As the titles says, ``deleterepeats`` causes embeds to be deleted due the fact that ``message.content`` is empty. Best fix in my opinion would be to check if the message has a embed and ignore the message entirely and do not let it count to the ``deleterepeats`` limit

**Comment by palmtree5** [comment]
nah, embeds shouldn't be ignored. Instead, the contents of the embed should be checked to see if it's a duplicate (other than probably the color used)

**Comment by Kowlin** [comment]
Whoops, forgot to reply on this. ~~The reason I want this ignored is due the fact that some bots have static embeds, and embeds can generally not be made by users. I guess this will be the only way to let other bots... Shit...~~ Lets just ignore bots, problem solved 👍

**Comment by palmtree5** [comment]
oh, true. Didn't think about it that way. Though if a selfbot starts spamming and it shows up as a bot, that could be a problem

**Comment by Twentysix26** [comment]
Selfbots aren't bot accounts so that wouldn't be a problem
