### ISSUE TITLE
Problem with 'cog repo add'.

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#742]
**Umm.. hello?** I tried to install 3rd party repository. My first problem was not installed requirements for cog. I installed them but after installation second problem showed up. I added repo (!cog repo add Maybe-Useful-Cogs https://github.com/AznStevy/Maybe-Useful-Cogs) and bot asked me to write 'I agree'. I did it but the problem is 'Error in command 'cog repo add'. Check your console or logs for details'.

Requirements for cog:

- MongoDB
- `pip3 install numpy scipy pillow pymongo`

To run pip3 I installed this:
- `sudo yum install python34-setuptools`
- `sudo easy_install-3.4 pip`

![bez tytulu](https://cloud.githubusercontent.com/assets/6854256/25558786/51c9618a-2d2e-11e7-9aaf-4fb7d6a8cfa6.png)

Sorry for my English if something is wrong with him. **Thanks for help!**
P.S. I just started my adventure with CentOS, SSH etc.

**Comment by Twentysix26** [comment]
#676

**Comment by ghost** [comment]
Ehh.. https://cdn.discordapp.com/attachments/295509122600927244/308004780679233557/S70430-241809.jpg

**Comment by ghost** [comment]
Ok, it's working! I restarted vps.
