### ISSUE TITLE
`apt install` should be `apt-get install` in debian install instructions

### ISSUE THREAD

**Issue by gnarf** [Cog-Creators/Red-DiscordBot#744]
I had pasted the install instructions from [here](https://twentysix26.github.io/Red-Docs/red_install_debian/) and then ran into trouble when things didn't work... It should be `apt-get update` and `apt-get install`

**Comment by Kowlin** [comment]
Fixed in https://github.com/Twentysix26/Red-Docs/commit/7be11006d2ee895a2675dfc49c38686320388569
