### ISSUE TITLE
[Streams] streamset twitchtoken does nothing

### ISSUE THREAD

**Issue by jbltx** [Cog-Creators/Red-DiscordBot#746]
I registered a bot application in my Twitch profile, then i copied the Client-ID and launched the command : 
`[p]streamset twitchtoken <my-ID>`

Unfortunately, the command does nothing, there's no answer, and no error in the log... 
I thought it worked without notifiying, but when I try a `twitch` command it says the Client-ID is not set.

I checked the json settings file and indeed nothing about the token is inside it.

Is it related to the callback URL ? I just put "http://localhost".

Thank you.

**Comment by Twentysix26** [comment]
Check if you're the owner of the bot in the console.

**Comment by jbltx** [comment]
Indeed, i just set it mine and works fine, sorry for the dumb question 😞 

This is a great bot, keep it up !
