### ISSUE TITLE
Bot stucks in case of sfx spamming

### ISSUE THREAD

**Issue by scerelli** [Cog-Creators/Red-DiscordBot#749]
It seems that the bot stucks when multiple people write at the same time `!sfx name`. 
What happens is that it doesn't leave the chat and it doesn't reproduce sounds. Do you have an idea on how to solve this problem?

**Comment by Kowlin** [comment]
We do not support 3rd party cogs, please seek the creator in this [Discord server](https://discord.gg/GET4DVk).
