### ISSUE TITLE
[suggestion] FIX cleanup messages [number]

### ISSUE THREAD

**Issue by tim-vandenbosch** [Cog-Creators/Red-DiscordBot#750]
**Problem:**
It has come to my attention that a lot of people are complaining about not being able to delete/empty an entire textchat.
That's why I've tried to make a workaround that works on slowly deleting messages from the chat. _(There is already the option of using the slow-mode)_

_Why cleanup doesn't work for some reasons:_
-The date of the message is older than 2 weeks.
-This is to not overload the discord servers.

**Solution:**
Slowing down the deletion from the start,
this gives the people to delete what they want and Discord servers load will lower.

**Code:**  _/cogs/mod.py -> @cleanup.command(...) async def messages(self, ctx, number: int):_
ex. : cleanup messages [number]

**Previous**
>if is_bot:
>            await self.mass_purge(to_delete)
>        else:
>            await self.slow_deletion(to_delete)

**Solution**
>if is_bot:
>  await self.slow_deletion(to_delete)
>else:
>  self.bot.say("Something went wrong with deleting.")

**Comment by tekulvw** [comment]
The problem with deleting everything is not necessarily that it puts a load on discord server, afaik that is negligible, but the fact that deleting everything significantly fragments the database that discord runs on. When they originally introduced the bot mass deletion API they did in fact allow you to delete everything you wanted but the moment they realized the performance impact down the line from database fragmentation they limited it. There's a blog post explaining this floating around somewhere but I don't have it on hand.

**Comment by tekulvw** [comment]
Not to mention that (I'm pretty sure) bots are required to use the mass purge endpoint and your logic change solution breaks deletion support for self bots.

**Comment by Twentysix26** [comment]
Implementing this is trivial. I haven't for the reasons that @tekulvw explained
