### ISSUE TITLE
Audio Glitching, Freezing then resuming playback

### ISSUE THREAD

**Issue by kakious** [Cog-Creators/Red-DiscordBot#752]
The bot kinda glitches and the audio cuts out for a second or two, then resumes. Do I need log files or anything?

**Comment by Twentysix26** [comment]
One or more of the following:
- Connection issues on your end
- Not enough bandwidth to stream audio to Discord
- Under powered hardware
- The server's voice region might be too far: try switching to a closer one in the server's settings
