### ISSUE TITLE
[Mod] Check message date for bulk cleaning

### ISSUE THREAD

**Issue by Fr6jDJF** [Cog-Creators/Red-DiscordBot#753]
`Error in command 'cleanup text'. Check your console or logs for details.`
\\
`discord.errors.HTTPException: BAD REQUEST (status code: 400): You can only bulk delete messages that are under 14 days old`

**Comment by QingyuChai** [comment]
Discord does not allow you to bulk delete messages that are older than 2 weeks. You will have to do it manually.

**Comment by QingyuChai** [comment]
Not really sure what you are asking, so I just clarified the error.

**Comment by tekulvw** [comment]
@palmtree5 has this check been added to your V3 mod rewrite?

**Comment by palmtree5** [comment]
This has been implemented in https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/cogs/cleanup/cleanup.py
