### ISSUE TITLE
Discord bot on Raspberry pi

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#754]
Hey guys,
After a lot of research i found out the best, easiest and the cheapest way to run discord bots 24/7 are raspberry pi's so I bought one which was the Raspberry pi zero w thinking i would be able to run the bot on it but after configuring everything and setting the bot up i found out the Raspberry pi zero w can't handle playing music, I'am thinking about upgrading to a Raspberry pi 2 model b.
I was wondering if you guys think a Raspberry pi 2 model b would be able to run 1/2 music bots before i waste any more money.
I wasn't sure where i could post this so i figured you guys are experts at discord bots and you might have an idea of what I could do.
Any kind of feedback would be very appreciated. Thank you!

**Comment by Twentysix26** [comment]
A raspberry pi 2b is the bare minimum for audio to work properly

**Comment by Kowlin** [comment]
For more information see the following [link](https://twentysix26.github.io/Red-Docs/red_install_raspbian/)
