### ISSUE TITLE
Python issue (cog related)

### ISSUE THREAD

**Issue by Evo-c** [Cog-Creators/Red-DiscordBot#756]
-

**Comment by 4Kaylum** [comment]
This isn't a Red issue, this is a Python issue. If you're having problems making a cog, you can join the API Discord (https://discord.gg/discord-api) or try the Red Discord's #coding channel (https://discord.gg/red).

Furthermore, you haven't described how the code doesn't work, just that it _doesn't_, which isn't really the correct way to go about asking for help. What exactly is the issue? Is it always saying the server is offline? Is the code not running? Is the command not being registered by the bot? Etc.
