### ISSUE TITLE
How to update Red on Raspbian?

### ISSUE THREAD

**Issue by nimiane** [Cog-Creators/Red-DiscordBot#759]
I've googled around to see if I could get this answered elsewhere without having to post here. I apologize in advance because I know this is probably an inappropriate place to do this.
I've already gotten Red set up on my Pi and it's been running for a few weeks now. I want to keep it updated, but I don't know what I need to type into the console to update it.
Any help would be greatly appreciated. Thanks!

**Comment by Artucuno** [comment]
i have a Raspbian i just go `python3 launcher.py` then use `3` or `4` if this helps tell me ok :)

**Comment by Artucuno** [comment]
@nimiane

**Comment by nimiane** [comment]
Oh, thanks so much! I was using "python3 red.py" to run Red, but your suggestion shows the console I used to see on my PC. Very much appreciated. 👍 :)

**Comment by Artucuno** [comment]
np happy to help @nimiane :D
