### ISSUE TITLE
[p]local start <playlist> followed by [p]play <youtube_video> creates an infinite audio loop

### ISSUE THREAD

**Issue by gle80** [Cog-Creators/Red-DiscordBot#763]
Hello!

I'm using the last version of Redbot on a Raspberry Pi 3 running Raspbian.
In order to play a short sound, I have created a small mp3 file using Audacity and moved it to a subfolder in the "/data/audio/localtracks/" folder.
I have then created the following alias : [p]alias add playmp3 local start <subfolder_name>.

When using this alias [p]playmp3 and then using [p]play <youtube_video>, both sounds are playing correctly but once the youtube video has been played, Redbot automatically restarts the cycle endlessly until a [p]stop.

Has anyone experienced a similar issue, or could this be related to my config?

Thanks!

**Comment by Zephyrkul** [comment]
Do you have the queue set to repeat? Try doing `[p]repeat` and see if that helps.
Also, may I recommend the use of [FlapJack-Cogs](https://github.com/flapjax/FlapJack-Cogs)'s SFX cog? Sounds like that may be more useful for your use case.

**Comment by tekulvw** [comment]
Yes this is expected functionality. The playlist turns on repeat mode and when you use `play` it clears the queue and adds just the one song. Use the `repeat` command to stop it from repeating.

**Comment by Tobotimus** [comment]
Closing as per @tekulvw's comment
