### ISSUE TITLE
Record Voice channel audio to file

### ISSUE THREAD

**Issue by iMxAndyy** [Cog-Creators/Red-DiscordBot#764]
If I recall correctly I remember seeing this or something similar on a to-do list for Red but I can't find it now. So i thought I'd suggest it anyway. 

It would be very useful for the bot to be able to record audio to file.
This was a feature native to teamspeak that we are really missing since we moved to discord and it would be great if Red could solve this issue for us.

**Comment by Twentysix26** [comment]
The underlying library has no voice receive support. This is unfeasible as of now.
