### ISSUE TITLE
Filtering is fairly ineffective

### ISSUE THREAD

**Issue by spAnser** [Cog-Creators/Red-DiscordBot#767]
There is a lot of ways around filtered words. Easiest being editing the message. But another easy method is simply using accented characters.

Maybe a to remove accented characters from the message to test against the filtered word list could be beneficial to mass filtering things without having to add all the possible accented variations to the filtered list.

http://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript

There is a couple of solutions in that stackoverflow including a 1 liner.

```javascript
const message = "Crème Brulée"
message.normalize('NFD').replace(/[\u0300-\u036f]/g, "")
> 'Creme Brulee'
```

**Comment by Twentysix26** [comment]
The filter is not supposed to completely replace the need for human moderation. If someone is going out of their way to evade the filter by using accented letters clearly some kind of intervention is in order.  
If it's not accented letters, it's punctuation between characters. If it's not that, it's writing words that are pronounced similar to banned ones. Where do we stop checking, exactly?

**Comment by spAnser** [comment]
While I understand there is an abundance of ways to get around the filter and that you can't implement all possible solutions to the bot. Adding a few simple ways of detecting some ways is more effective than adding none.

That said it wouldn't be hard to just paste this in the version I might decide to run.

**Comment by Twentysix26** [comment]
I added the check on message edit 👍
