### ISSUE TITLE
Dependencies not installing on Ubuntu 17.04

### ISSUE THREAD

**Issue by ThatTalkingEnder** [Cog-Creators/Red-DiscordBot#775]
I was getting Red up for a friend. But when I went to install the dependencies, it gave me a few errors. I can copy and paste them if it would help (which I know it will, so i'll put it in the comments).

**Comment by ThatTalkingEnder** [comment]
> 1
Collecting pip (from -r requirements.txt (line 1))
  Using cached pip-9.0.1-py2.py3-none-any.whl
Collecting discord.py[voice] from git+git://github.com/Rapptz/discord.py.git#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning git://github.com/Rapptz/discord.py.git to /tmp/pip-build-a4lq214y/discord.py
Collecting youtube_dl (from -r requirements.txt (line 3))
  Using cached youtube_dl-2017.5.23-py2.py3-none-any.whl
Collecting imgurpython (from -r requirements.txt (line 4))
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]->-r requirements.txt (line 2))
  Using cached aiohttp-1.0.5-cp35-cp35m-manylinux1_x86_64.whl
Collecting websockets<4.0,>=3.1 (from discord.py[voice]->-r requirements.txt (line 2))
  Using cached websockets-3.3-py33.py34.py35.py36-none-any.whl
Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 2))
Collecting requests (from imgurpython->-r requirements.txt (line 4))
  Using cached requests-2.14.2-py2.py3-none-any.whl
Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached chardet-3.0.3-py2.py3-none-any.whl
Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached async_timeout-1.2.1-py3-none-any.whl
Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached multidict-2.1.5-cp35-cp35m-manylinux1_x86_64.whl
Collecting cffi>=1.1.0 (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
  Using cached cffi-1.10.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting six (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
Installing collected packages: pip, chardet, async-timeout, multidict, aiohttp, websockets, pycparser, cffi, six, PyNaCl, discord.py, youtube-dl, requests, imgurpython
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/share/python-wheels/setuptools-32.3.1-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python3.5/distutils/command/install.py", line 273, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base

An error occurred and the requirements setup might not be completed. Consult the docs.

Press enter to continue.

**Comment by ThatTalkingEnder** [comment]
https://pastebin.com/7N4ZHqvw

**Comment by tekulvw** [comment]
Do `pip3 install -U pip` then try again (you may need sudo).

**Comment by ThatTalkingEnder** [comment]
Works perfectly. Thank you!

**Comment by josipledic** [comment]
Thanks!
