### ISSUE TITLE
[p] playlist queue playlistname youtubeURL does not work

### ISSUE THREAD

**Issue by joshstricklin** [Cog-Creators/Red-DiscordBot#778]
When I use [p] playlist queue playlistname youtubeURL the expected result is that the selected song will a) play next and b) get added to the playlist permanently. Instead it adds "None" to the end of the queue and the actual song does not get added to the playlist OR the queue.

**Comment by tekulvw** [comment]
I do believe your expectations and what the documentation tells you will happens are two entirely different things. If you would like to change this functionality feel free to submit a PR.

![image](https://cloud.githubusercontent.com/assets/3731082/26511759/a8b24190-4220-11e7-8c75-9a86d165db9d.png)

**Comment by joshstricklin** [comment]
Thanks for the reply!

I see how I looked over that. I now understand it shouldn't write to the disk.

However, it also does NOT add a song to the playlist loop - it adds a blank song titled "None." to the queue instead of the intended song and will skip that item when it gets to it in the queue.

**Comment by tekulvw** [comment]
Have you tried using the command correctly (without playlist name before the URL)?
