### ISSUE TITLE
Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by RageSugar** [Cog-Creators/Red-DiscordBot#787]
So the bot was working fine.  I keep it up to date, checked python and I am running 3.5.3 and for about a week now it has not been working regarding playing audio.  The bot will queue the song correctly, go into the voice channel, the icon will turn green, and the status will show the song is currently playing, but there is no audio.

Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at C:\Users\Cayle\Desktop\VixenBot\Red-DiscordBot\cogs\audio.py:2102> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at C:\Users\Cayle\Desktop\VixenBot\Red-DiscordBot\cogs\audio.py:1975> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at C:\Users\Cayle\Desktop\VixenBot\Red-DiscordBot\cogs\audio.py:2106> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_manager() running at C:\Users\Cayle\Desktop\VixenBot\Red-DiscordBot\cogs\audio.py:1927> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by tekulvw** [comment]
Unless you've got an error to go along with this there's not much we can do. These messages are just warnings and give us no information to help us fix the issue.

**Comment by RageSugar** [comment]
That's the weird thing, it wasn't giving any errors at all.  This is all it really gave me after each restart when it wasn't playing the audio.  I'll go ahead and close this though since seems not much to be done and hope it's just discord being annoying.

**Comment by tekulvw** [comment]
>This is all it really gave me after each restart when it wasn't playing the audio.

Ahh, these messages are common warnings that may pop up on restart. They have nothing to do with audio not working.
