### ISSUE TITLE
WinError 10054

### ISSUE THREAD

**Issue by Augustaeum** [Cog-Creators/Red-DiscordBot#788]
So one of my bots posted this error yesterday:`ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host redbot` and stopped playing audio, the rest of the bot worked just fine and even reloading the audio cog manually with `!load audio` did not fix it, forcing me to restart it.

**Comment by tekulvw** [comment]
Very creative and informative title.

As the error would suggest, the bot's connect to a remote host (in this case Discord Voice server) was closed by the remote host (in this case Discord). Not a whole lot we can do about it.
