### ISSUE TITLE
Search YouTube

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#79]
I think it would be really nice to be able to search YouTube.

Examples:
`!youtube kazoo kid trap remix`
`!yt dank memes`

I'm lazy and don't want to have to go all the way to my browser just to pull up a clip for people. :D

**Comment by jaw3l** [comment]
+1, would be great

**Comment by Twentysix26** [comment]
Implemented to !play and !queue

**Comment by ghost** [comment]
Not exactly what I meant. I want the functionality of `!ytsearch` basically, as we discussed in chat on Discord.

Can you please re-open this issue? If not, I can create a new one.

**Comment by Corgi** [comment]
+1, am missing this functionality

**Comment by irdumbs** [comment]
can you give an example of what the output of this command would be? it may be a simple solution a few PRs down the line

**Comment by Corgi** [comment]
Personally, just having the bot spit out the first result on a search on youtube as a url would be great.

![](https://i.gyazo.com/85807d2c49f348068a44d7084bed3ca8.png)

**Comment by ghost** [comment]
Basically what @Corgi said. If you check out Gravebot (node.js though), it's basically the same idea as that screenshot. Does require using the API from Google, IIRC.

**Comment by tekulvw** [comment]
Encompassed by #185
