### ISSUE TITLE
[p]cogs confusion

### ISSUE THREAD

**Issue by Sitryk** [Cog-Creators/Red-DiscordBot#794]
I have seen multiple people that get confused between [p]cogs and [p]cog 

If a sub command is given to `[p]cogs` it could point to `[p]cog` or other, this is only a minor issue just thought it might make sense to add this

**Comment by tekulvw** [comment]
Adding this would not be a trivial thing, it would be really hacky and personally I don't see some people not noticing the `s` to be a significant reason to try to implement this. If you've got ideas for renaming the `cog` command feel free to suggest them.
