### ISSUE TITLE
Mobile YouTube links are not considered valid links

### ISSUE THREAD

**Issue by Shigbeard** [Cog-Creators/Red-DiscordBot#80]
As it says on the tin. Lets say a user was using the mobile Discord app, and decided to play a youtube link. By default, they will give a link in this format: https://m.youtube.com/watch?v=S6WfnPdjEZ4

Red will report that the link is not allowed, despite it being a simple matter of replacing m.youtube.com with www.youtube.com (incase whatever is retrieved is exclusive to the desktop version of the site).

Some compatibility layer between mobile and desktop users would be appreciated.

**Comment by Shigbeard** [comment]
Further adding to this issue, if a valid youtube url is entered without the www prefix, it is assumed to be invalid, as well as non secure connections.

As www is a prefix, it should be ignored or ingorable.

**Comment by Shigbeard** [comment]
For reference:

![http://i.imgur.com/hfraQoj.png](http://i.imgur.com/hfraQoj.png)

**Comment by ghost** [comment]
Currently you can edit a file to make those links allowed. I'll pull up the exact file in a bit if no one else mentions it first.

I definitely think mobile and http links should be allowed by default though. 👍

**Comment by Twentysix26** [comment]
@xnaas data/audio/accepted_links.json

And yeah, they should be allowed by default

**Comment by ghost** [comment]
Thanks @Twentysix26 <3

**Comment by tekulvw** [comment]
Encompassed by #185
