### ISSUE TITLE
[V3] Adding support for appending help from custom commands.Converter

### ISSUE THREAD

**Issue by DeltaSigma130** [Cog-Creators/Red-DiscordBot#800]
This may be too niche, but having argument processing help through commands.Converter has been helpful to me.  Here's some code that I've been using.
```python
def command_arg_help(**cmdkwargs):
    def internal_func(f):
        helps = []
        for param in inspect.signature(f).parameters.values():
            if issubclass(param.annotation, commands.Converter):
                arg_help = getattr(param.annotation, 'arg_help')
                if arg_help is not None:
                    helps.append(arg_help)
        if helps:
            if f.__doc__:
                helps.insert(0, f.__doc__)
            f.__doc__ = '\n'.join(helps)
        @wraps(f)
        async def wrapper(*args, **kwargs):
            return await f(*args, **kwargs)
        return commands.command(**cmdkwargs)(wrapper)
    return internal_func

**Comment by DeltaSigma130** [comment]
Then, inside the commands.Converter class:
```python
class ChampConverter(commands.Converter):
    arg_help = '''More help '''

**Comment by DeltaSigma130** [comment]
And then the decorator:
```python
    @command_arg_help(aliases=('bio',))
    async def champ_bio(self, *, champ : ChampConverterDebug):

**Comment by DeltaSigma130** [comment]
I don't know Markdown isn't working as expected to close code blocks

**Comment by tekulvw** [comment]
I like the idea but not this exact implementation. I think I'll come up with a slightly modified one for V3 in the next week or two.

**Comment by DeltaSigma130** [comment]
No problem.  That was just the first implementation idea that came to me that seemed to work for my use case but still be general enough.  Many other ways to accomplish the same thing.

**Comment by tekulvw** [comment]
I think we're going to go with the ideas in #967, having the bot respond when an argument conversion has failed rather than appending converter information to the help. It'll likely be more useful to the end user that way.
