### ISSUE TITLE
fails on installing requirments

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#801]
no expert on python
https://pastebin.com/XW935a6w

using python 3.5.2 on debian 8.7 (jessie)

**Comment by palmtree5** [comment]
Your issue can be fixed by [reading the install docs for Debian](http://twentysix26.github.io/Red-Docs/red_install_debian/)

**Comment by tekulvw** [comment]
Seconding the above and closing.
