### ISSUE TITLE
Is there a COG for deleting my own messages

### ISSUE THREAD

**Issue by mikeparadinas** [Cog-Creators/Red-DiscordBot#805]
I want to search through a channel or entire server, and delete all my own messages.
Can bots make use of the Search feature yet?

**Comment by mikeparadinas** [comment]
d

**Comment by mikeparadinas** [comment]
dasdsa

**Comment by tekulvw** [comment]
Q: "Is there a cog?"
A: This repository (and it's issues) do not deal with third party cogs. Please make your way into the COG support server or to https://cogs.red

Q: "Can bots make use of the search feature?"
A: This is a question more appropriate for discord.py, the library used to communicate with the Discord servers. AFAIK however, the Discord devs have not opened up a "search" function to bot developers and as such there is no native way of doing search from within the bots.

Also, even though you delete your own bump comments it still pings all of the contributors, I am sure you are aware of this. It is annoying and frowned upon, you'll get your answer when we get around to it.
