### ISSUE TITLE
[Core V3] Should we add cog paths to sys path?

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#816]
## The Problem
Everytime you use `!load cogname` internally we have to turn that name into `cogs.cogname` before we can ship it to d.py and get it loaded. That means that we have `"cogs." +` sprinkled throughout the core bot code and it makes everything quite fragile and hard to improve/extend.

## My conceptual solution
Add cog path(s) to sys path. This will allow us to use `importlib` to systematically find cog modules wherever they may be. It will also allow us to have *multiple* cog paths. For you cog developers out there this means that you can add your repo folder to the list of known cog paths and you will not have to copy/paste your cog file into the bot folder in order to test anymore.

## The problem with the solution
If the bot owner has installed a python package with the same name as your cog, your cog will NOT be found and loaded (probably, we might be able to pull some magic to make this happen but I'm not sure on that yet).

## What are your thoughts?

**Comment by palmtree5** [comment]
Yeah, I like this idea. It would certainly make development easier in terms of testing. As for the problem, that would be a big issue, especially if the installed package is needed for a cog to work (if not, then theoretically the unneeded package could just be uninstalled but obviously that's not the best solution to that). Perhaps [this StackOverflow post](https://stackoverflow.com/questions/15720593/python-two-modules-and-classes-with-the-same-name-under-different-packages) could be of some assistance here?

**Comment by tekulvw** [comment]
I think there may be a way to have multiple cog paths without adding them to `sys.path`. It will take some further exploration to determine if it's actually possible though.

Would this functionality be a shoo-in if it can be done without modifying `sys.path`?

**Comment by mikeshardmind** [comment]
it is worth noting you can also put specific paths at the _beginning_ of the path spec with:

`import sys`

`sys.path[0:0] = ['/foo']`

`import bar`

but this comes with other problems of possible misuse by cog creators.

**Comment by tekulvw** [comment]
Right, the issue with that however is that it's liable to allow cogs to shadow packages installed by pip or packages available in the cwd.

My idea to do this without modifying `sys.path` is to (ab)use [this](https://docs.python.org/3/library/importlib.html#importlib.util.spec_from_file_location) function from `importlib`.

**Comment by tekulvw** [comment]
I have to override d.py's `load_extension` function to abuse the `importlib` stuff because the utilities I need in order to be able to load modules not in `sys.path` only exist in 3.5+. I still think this is doable but it's a bit of a bigger engineering challenge.
