### ISSUE TITLE
Add non-shared server bot blacklist and/or whitelist

### ISSUE THREAD

**Issue by Aioxas** [Cog-Creators/Red-DiscordBot#822]
As name implies, add the ability for a bot owner to blacklist someone from using the bot, similar to hackban, but said person can stay in the server(s). Not sure if this would be needed on whitelist as well.

This would be done using the user.id. An example could be something like this:

```python

    @blacklist.command(name="hackadd")
    async def _blacklist_hackadd(self, uid):
        """Adds user to Red's global blacklist.
        For use if the owner doesn't share a server with the offending user."""
        if uid not in self.global_ignores["blacklist"]:
            self.global_ignores["blacklist"].append(uid)
            self.save_global_ignores()
            await self.bot.say("User has been blacklisted.")
        else:
            await self.bot.say("User is already blacklisted.")
```

This could be done either for v2 or v3. If the idea is too nonsensical, it can be scrapped out then.

**Comment by Twentysix26** [comment]
My solution (#1068) is slightly different, as in you can't input any number you want and the user has to at least share one server with the bot, but I think it covers the majority of use cases. Waiting for more reviews on it.

**Comment by Aioxas** [comment]
looks good 26, it covers the case of gibberish number adding that I might have missed. I guess we can close this when that gets accepted or something

**Comment by Twentysix26** [comment]
Merged
