### ISSUE TITLE
Missing exception or change elif to else

### ISSUE THREAD

**Issue by Opicaak** [Cog-Creators/Red-DiscordBot#823]
At line 389 in economy.py change elif to else or add exception.

**Comment by palmtree5** [comment]
Nope, that's not actually necessary there. All cases are covered properly (if the credits argument for `bank set` is not valid (for example, is something like `+f`), then the command's help output is posted instead due to an invalid argument

**Comment by Twentysix26** [comment]
Try to focus on giving details about the problem when opening an issue. When proposing code changes consider a PR. As it stands this issue doesn't help at all.
