### ISSUE TITLE
[Streams] Twitch Community support

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#824]
For whoever is up for the task, I've done some digging into Twitch Communities and see if we can support them in Streams. And that answer would be yes.

For this we require the Client ID and a new accept header to access the Twitch community API
``Accept: application/vnd.twitchtv.v5+json``
from there we can grab the Community ID required to resolve it into the streams API, we do that by calling the following URL and grabbing the ``_id``
``https://api.twitch.tv/kraken/communities?name=<CommunityName>``
After that we call the Streams API
``https://api.twitch.tv/kraken/streams?community_id=<CommunityID>``

This should return a list with active streams for the active communities.

**Comment by palmtree5** [comment]
Gonna work on this today

**Comment by palmtree5** [comment]
This is implemented in #782
