### ISSUE TITLE
Why is it not working? I think I installed everything and im using python 3.5.0

### ISSUE THREAD

**Issue by ThePqtatoGalaxy** [Cog-Creators/Red-DiscordBot#827]
https://i.gyazo.com/a64e784b1d0045c39a622e67ae8d910a.png
I restarted and installed git python and node.js but it says this so do I need to restart again or something else?

**Comment by Stylite** [comment]
Run as sudo and try again

**Comment by tekulvw** [comment]
First, he's on windows.

Second, what command prompt are you using? CMD.exe or mingw or cmder (or any other)?

**Comment by ThePqtatoGalaxy** [comment]
this one https://i.gyazo.com/faafd808b6d77bf48a99f8369b091cc2.png

**Comment by ThePqtatoGalaxy** [comment]
Also if you have developer mode on you can turn on ubuntu commands

**Comment by ThePqtatoGalaxy** [comment]
Windows developer mode

**Comment by palmtree5** [comment]
FYI: you don't need node.js to run Red

**Comment by boswelja** [comment]
or
You could try running the command it tells you to use

**Comment by Stylite** [comment]
Complete shot in the dark. Can you try python -m pip install --upgrade setuptools or python easy_install -U setuptools

**Comment by Stylite** [comment]
did that work for you

**Comment by mayokek** [comment]
Maybe try doing `python3 -m pip install` method

**Comment by tekulvw** [comment]
Please join the support server if you're still experiencing issues.
