### ISSUE TITLE
How would I go about creating a cog that takes one parameter and simply outputs some text based on what the parameter is?

### ISSUE THREAD

**Issue by calzonees** [Cog-Creators/Red-DiscordBot#843]
I'm very sorry, I'm sure there are loads of these here. I know next-to-nothing about python and discord.py. Any help would be appreciated. Thank you.

EDIT: If you need further information, the command is for mafia. It would take a role name as a parameter and return its description.

**Comment by Twentysix26** [comment]
[This might help you](https://github.com/Twentysix26/Red-DiscordBot/blob/9f290dbdc79f47fe50e74e7cc3db8ab3f2631554/cogs/owner.py#L510).  
[Discord.py's repository](https://github.com/Rapptz/discord.py/) is a more appropriate place for this kind of questions.
