### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by nuxcodex** [Cog-Creators/Red-DiscordBot#846]
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/Red-DiscordBot/cogs/audio.py", line 1632, in _queue
    await ctx.invoke(self.play, url_or_search_terms=url)
  File "lib/discord/ext/commands/context.py", line 112, in invoke
    ret = yield from command.callback(*arguments, **kwargs)
  File "/root/Red-DiscordBot/cogs/audio.py", line 1361, in play
    await self._join_voice_channel(voice_channel)
  File "/root/Red-DiscordBot/cogs/audio.py", line 648, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel,"

**Comment by palmtree5** [comment]
`The voice channel may be full. Otherwise, try changing the server's region
Try a different server region or wait. This is most likely an issue on discord's end.`

**Comment by nuxcodex** [comment]
don't work

**Comment by nuxcodex** [comment]
it worked yesterday pls help

**Comment by tekulvw** [comment]
"or wait."

Looks like that's your next option. As you were told this is likely a Discord voice server issue and is nothing that we can fix.

**Comment by nuxcodex** [comment]
okay

**Comment by nuxcodex** [comment]
on my discord it says: Error in command 'queue'. Check your console or logs for details.

**Comment by nuxcodex** [comment]
i don't think it's the discord

**Comment by tekulvw** [comment]
The error that you posted above is. If you have a different error please go to the support server and we'll deal with it there.
