### ISSUE TITLE
[Rewrite] Launcher

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#850]
Any suggestions for the rewrite when it comes to the launcher?

**Comment by boswelja** [comment]
Not sure if this was already a thing or not, but what about checking for updates on launcher start?

**Comment by tekulvw** [comment]
It's been a thing for about a year now, it's harder than it sounds to get right.

**Comment by tekulvw** [comment]
If #853 goes through we'll need to have users select a "cog install" path where downloader will put installed cogs. This should default to `~/.config/something` on mac/*nix and `%appdata%/somewhere` on windows.

**Comment by boswelja** [comment]
What about a way to install / uninstall cogs from the launcher as well?

**Comment by tekulvw** [comment]
Right now that's only possible if cogs are loaded prior to launcher start

**Comment by Kowlin** [comment]
Actually I was thinking of a method of adding autostarting systems (like pm2 and supervisord) into the launcher. This seems like a good thing to pick up for it, check what is installed. And provide options accordingly

**Comment by Jan200101** [comment]
pm2 requires root permissions to add a task to autostart that could be a problem

**Comment by Kowlin** [comment]
Yet another reason to use Supervisor 😏

**Comment by palmtree5** [comment]
Could be a good thing though one would need to generate files for that.
I've actually looked into this myself to some extent

**Comment by Twentysix26** [comment]
Considering the variety of process managers, the need for root, the amount of stuff that can go wrong with automating this, I think it's better to leave this to the user. They installed a bot on a Linux vps, I'm sure they can spend 2 additional minutes looking at a 5 steps tutorial

**Comment by palmtree5** [comment]
>I'm sure they can spend 2 additional minutes looking at a 5 steps tutorial

That I've seen multiple people manage to screw up in various methods. Automating at least the creation of such a file could potentially reduce issues caused by people making incorrect changes or failing to change certain things in the files (for example, username/group or python path). Even if we manage to clarify our docs to reduce these issues, someone will probably still manage to screw it up despite that.

That being said, my thought would be to have them as options in the launcher that only appear for linux users (maybe even reducing it to things actually supported by the version and distro they're running (example: don't show Upstart as an option for users on Ubuntu 16.04+) so as to help deter selecting an incorrect option). Then once they've chosen an option, we proceed to generate the needed file and tell them exactly where to move it to (or move it there for them using something that would look like `subprocess.call(["sudo", "-k", "mv", os.path.join(os.getcwd(), "red.service"), os.path.join(os.path.sep, "etc", "systemd", "system", "red.service")])`) and tell them what command to use to enable autorestart

**Comment by Kowlin** [comment]
A info debugger for the launcher. A formatted list to be copied to another GitHub issue or the support that. Including stuff like the Python version running, the current Git SHA1 hash, FFmpeg/PyNaCl status, OS information (OS and 32/64bit), User.

As always, feel free to throw more stuff down below ;)

**Comment by tekulvw** [comment]
Can you add support for asking users for a cog install directory (where should downloader put installed cogs?) because this will be supported with #853. It would also be useful to ask where people want to put their data because that's next on my list after I finish 853.

**Comment by tekulvw** [comment]
@palmtree5 has implemented this, please post new issues for future suggestions
