### ISSUE TITLE
[Suggestion] Bot Owner Should Bypass Disabled Commands

### ISSUE THREAD

**Issue by AriRexouium** [Cog-Creators/Red-DiscordBot#854]
As the title suggests.

**Comment by tekulvw** [comment]
Not gonna happen. Disabled means disabled not "disabled except for x, y, z...". If you want to lock down commands for owner use only I'd suggest looking at the Permissions cog from Squid-Plugins.

**Comment by AriRexouium** [comment]
Alright, thanks.
