### ISSUE TITLE
[Rewrite] voice permissions don't seem to work properly for checks

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#857]
Was testing some stuff with the mod rewrite relating to voice moderation commands and was getting permissions errors even though both the bot and I have the required permissions (and I'm the server owner of the server I'm testing in (not to mention the bot's owner)). Could be on our end, could be on d.py's, I'm not sure at this point

**Comment by tekulvw** [comment]
Can you give a sample of small code in which the issue is reproducible?

**Comment by palmtree5** [comment]
```python
@commands.command()
@commands.guild_only()
@checks.admin_or_permissions(mute_members=True, deafen_members=True)
@commands.bot_has_permissions(mute_members=True, deafen_members=True)
async def voiceban(self, ctx: commands.Context, user: discord.Member, *, reason: str=None):
```
and

```python
@commands.command()
@commands.guild_only()
@checks.admin_or_permissions(mute_members=True, deafen_members=True)
@commands.bot_has_permissions(mute_members=True, deafen_members=True)
async def voiceunban(self, ctx: commands.Context, user: discord.Member, *, reason: str=None):
```

and

```python
@mute.command()
@commands.guild_only()
@checks.mod_or_permissions(mute_members=True)
async def voice(self, ctx: commands.Context, user: discord.Member, *, reason: str = None):
```
On the very last one there, it just outputs help

The other two lead to an error saying that I don't have permissions to run the commands even though I do

**Comment by palmtree5** [comment]
http://i.imgur.com/A2cLfC8.png is what I see with `voiceban` and `mute voice`

**Comment by tekulvw** [comment]
Issue was found and resolved.
