### ISSUE TITLE
quick issues to consider fixing - modrole + playlists

### ISSUE THREAD

**Issue by MiniJennJenn** [Cog-Creators/Red-DiscordBot#858]
since irdumb suggested I put this here...

1.the blurb under modset should be moved over to the [p]set menu now that the role command has been moved from [p]modset to [p]set

2. edit the built in playlists since apparently some of the videos are private now

3. not so quick: i found a convo in 05/2016 between kowlin and 26 saying that [p]shuffle would work on local audio. It doesn't appear to be the case anymore?

**Comment by palmtree5** [comment]
specifically removed the mod and admin roles from the `modset` settings display (will be implemented when #785 is merged)

**Comment by Kowlin** [comment]
1. Solved in #785 
2. Fixing in V3
3. Fixing in V3
