### ISSUE TITLE
IS there a adminset command if yes, i can't see it?

### ISSUE THREAD

**Issue by stardriver56** [Cog-Creators/Red-DiscordBot#859]
Just a simple query
does redbot have a adminset command if yes i cant see it on command list.

**Comment by retke** [comment]
`!set defaultadminrole`

**Comment by laggron42** [comment]
Check in /Red/cogs/admin.py __without editing__ in the line 108 if there is no `hidden=True` argument 
```
    @adminset.command(pass_context=True, name="selfroles")
```
This line

**Comment by stardriver56** [comment]
sry but i cant see a admin.py

**Comment by Kowlin** [comment]
What exactly are you trying to do? I'm having a hard time figuring out on what you want.

**Comment by laggron42** [comment]
You didn't installed the cog, how would it work ? I'm getting the commands you will need to type to install it

**Comment by Chovin** [comment]
are you trying to set a person/role as an admin to your bot? If so,
`[p]set` has an `adminrole` subcommand

if you don't see an `adminrole` in the `set` command, you probably aren't the owner of the bot.
`[p]set owner` will help you with that as long as you are the owner of the machine the bot is on.

**Comment by stardriver56** [comment]
i want to use a certain command called  addrole which is under adminset command. my friend can use it but i cant and we have same bot.
so i want you guys to help me to make sure like is there truly a command called adminset or addrole.
and i checked it is not a cc or alias

**Comment by Chovin** [comment]
if you type `[p]help adminset` and is says there isn't a command, then there isn't a command.

your friend likely has the admin cog https://cogs.red/cogs/?search=admin

**Comment by laggron42** [comment]
Type this
```
!cog repo add Squid-Plugins https://github.com/tekulvw/Squid-Plugins
```
Accept and type this
```
!cog install Squid-Plugins admin
```
Type yes to load and `!help` to get the new commands

**Comment by stardriver56** [comment]
all right i will do it hope it works 
thx to everyone for replying

**Comment by Twentysix26** [comment]
@Chovin For future reference, `[p]set adminrole` doesn't need bot owner permissions, just server owner
