### ISSUE TITLE
[Red v3]  Failure to Identify git HEAD

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#867]
attempting to launch red from a directory other than red's fails. 
it is trying to find it in the current working directory rather than the directory red is in

`$ env/bin/python3.5 Red-v3/main.py `
results in:

`fatal: Not a git repository (or any of the parent directories): .git`
some interaction during setup and then
`Traceback (most recent call last):
  File "Red-v3/main.py", line 99, in <module>
    init_sentry_logging(sentry_log)
  File "/home/ubuntu/git/Rv3/Red-v3/core/sentry_setup.py", line 35, in init_sentry_logging
    release=fetch_git_sha(str(Path.cwd()))
  File "/home/ubuntu/git/Rv3/env/lib/python3.5/site-packages/raven/versioning.py", line 25, in fetch_git_sha
    'Cannot identify HEAD for git repository at %s' % (path,))
raven.exceptions.InvalidGitRepository: Cannot identify HEAD for git repository at /home/ubuntu/git/Rv3
`

**Comment by tekulvw** [comment]
Just like with V2, V3 is still dependent on CWD being the bots folder. This ought to change and we're working on it but for now that's the way it is.

**Comment by tekulvw** [comment]
No longer applicable to V3
