### ISSUE TITLE
Error when playing audio

### ISSUE THREAD

**Issue by jaw3l** [Cog-Creators/Red-DiscordBot#87]
Im getting this error after play some song ^

```
Cannot write to a WebSocket in the CLOSED state
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_manager() running at C:\Users\Administrato
r\Desktop\red\cogs\audio.py:583> wait_for=<Future pending cb=[Task._wakeup
()]>>
```

and then its restarting the bot..

**Comment by Twentysix26** [comment]
Might be random connection issues on your end or Discord's servers (DDOS'd just a few hours ago)

**Comment by Asute** [comment]
Since there is no reply (and yes, it's connection issues for the bot), this will be closed o/
