### ISSUE TITLE
Future of the Economy Bank

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#871]
So the question here is what to do with the bank. Currently in V2 the bank is accessible only through the Economy cog itself, which makes it a hassle to get to and means any cog that depends on the bank automatically depends on Economy. This is an issue because we have undefined load order of cogs and tbh some people just may not want Economy.

### Proposed Solution 1
V3 Downloader has implemented a little know feature for shared libraries. We can make use of this for the bank and make it available to every cog with a single import:

`from cog_shared import bank`

### Proposed Solution 2
We can make the bank available from within core Red which means that it would be accessible with this line:

`from core import bank`

### Secondary problem
In Palm's Economy rewrite he currently has the bank implemented as a cog with a few commands (to change bank name, currency name, make it global). Should the bank remain with those commands or should they be implemented in Economy (and as a consequence, all alternative economies)?

### Thoughts?

**Comment by Kowlin** [comment]
Both these solutions share 1 core problem though. And that is interaction from a user standpoint. Lets take our current method of working with Eco. A user runs the ``bank register`` command, and a account gets made for him. However with Eco unloaded a user cannot do this. And ye, checks exist to make sure that a user account exists. But by doing this you won't be able to discover if Eco is loaded. At least that is what has been rolling trough my head.

But solution 1 seems like a better one, gives more clarity on what has been used for the cog.

**Comment by tekulvw** [comment]
Unless we say screw registering...and when the user first does something that modifies their bank account they get the current default value plus/minus whatever that action did.

**Comment by palmtree5** [comment]
Yeah, I'd just create an account for them when they try to do something that would modify their account if they don't already have an account rather than forcing them to run a command to register

**Comment by palmtree5** [comment]
https://github.com/palmtree5/Red-DiscordBot/commit/d06d7d45e78fac600f4bd7f108e6b26718a13ac7

**Comment by tekulvw** [comment]
@Redjumpman I'm curious of your thoughts on this

**Comment by AmusingThrone** [comment]
I find proposition 2 to be a better solution. While many people may not want Slots or Economy, this solution really doesn't affect the bot owner as they just don't need to have any cog that uses Economy. 

The `bank register` command is something that I found weird to begin with. A bank account should be created the moment a user uses a command that has to interact with the bank, a solution that can better solved by having this feature in core.

**Comment by tekulvw** [comment]
For the record: Solution 2 has already been implemented in #781 alongside the removal of `bank register`.

**Comment by palmtree5** [comment]
Done with https://github.com/Cog-Creators/Red-DiscordBot/commit/4923ffe98a998f546118f517e6c6a83f4a1bb678
