### ISSUE TITLE
Triggers trigger on different bot

### ISSUE THREAD

**Issue by LJack2k** [Cog-Creators/Red-DiscordBot#873]
Yes I know that Red doesn't respond to other bots. And yes that's because you could have loops. But consider the following situation. I'm running several minecraft games that have their own bots (not red) as a bridge between minecraft and discord. I want to be able to create triggers that react on things that happen in the ingame chat. But this doesn't work because Red doesn't respond on other bots. Sadly. What could be a solution? Make it configurable so that by default the trigger doesn't respond, but when set to true it will respond on other bots. If there is paranoia for loops, its even possible to demand a 5 sec cooldown on a bot trigger, or higher. Or maybe to allow/disallow only certain bots. I think there are enough options to make this work and have it 'safe'. 

I do love Red. Its serving us very well. Thanks for your hard work on it.

**Comment by Twentysix26** [comment]
I assume you're referring to my trigger cog.
This is the wrong repository for this issue. You can open a new issue [here](https://github.com/Twentysix26/26-Cogs/)
