### ISSUE TITLE
Redbot thinks it needs to check streams, and it crashes. 

### ISSUE THREAD

**Issue by Faoulon0224** [Cog-Creators/Red-DiscordBot#874]
Lately I haven't been able to keep redbot up for more then a few hours without restarting it. The problem is, it thinks it needs to check streams. however, I haven't ever attempted to track streams. Is there any way I can just delete that code, or at least make it so the bot won't check for streams?

error message here: https://pastebin.com/kzQJQU6i

**Comment by Twentysix26** [comment]
You're misinterpreting the traceback, it's just a generic crash due to (most likely) connection issues. Use the launcher or any [autorestart](https://twentysix26.github.io/Red-Docs/red_guide_linux_autostart/) solution.
