### ISSUE TITLE
[Audio] Queue is cleared seemingly randomly 

### ISSUE THREAD

**Issue by UnimatrixZeroOne** [Cog-Creators/Red-DiscordBot#881]
Every now and then, the queue is completely wiped when no one cleared it. It may be after a certain number of songs are added, but I'm not positive. There is nothing listed in the red.log

**Comment by UnimatrixZeroOne** [comment]
Well, turns out it actually wipes the queue if it's executed in-between songs. The YT command does the same.

**Comment by tekulvw** [comment]
That's intended behavior. When you use `!play` or `!yt` we assume that you want to play that song instead of the playlist and while that assumption may not hold true all the time, it certainly does most of the time.
