### ISSUE TITLE
[V3 Downloader] Some suggestions for Downloader

### ISSUE THREAD

**Issue by skeith** [Cog-Creators/Red-DiscordBot#885]
I ~~collected~~ thought of these ideas that ~~should~~ might make Downloader more friendly

- Add `Installed` flag to `[p]cog list [repo-name]`
- Show required pip package for each cog (from info.json) to `[p]cog list [repo-name]` so people can install them just in case the auto requirements install failing OR there is compatibility issue (https://github.com/python-pillow/Pillow/issues/2639)

That's all for now

**Comment by tekulvw** [comment]
Fully implemented with #1826 and #1827
