### ISSUE TITLE
No module named discord.ext

### ISSUE THREAD

**Issue by ElijahKSmith** [Cog-Creators/Red-DiscordBot#89]
So, whenever I start up the new version of the bot, I get this error: `Traceback (most recent call last):
  File "C:\Users\(username)\Desktop\Discord Bot\Red-DiscordBot\red.py", line 1, in <module>
    from discord.ext import commands
ImportError: No module named 'discord.ext'`

I have no idea what is going on. this is a new module I take it, because the old version of the bot does not use it. I've followed all the instructions on the installation page, my computer says all of the modules from the installation page are installed. Did I miss something, or am I just stupid?

**Comment by Twentysix26** [comment]
`pip3 uninstall discord.py`

`pip3 install git+https://github.com/Rapptz/discord.py@async`

**Comment by ElijahKSmith** [comment]
Thanks, that fixed it!

**Comment by omarskywalker** [comment]
i keep getting this 
 HTTP error 404 while getting https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
