### ISSUE TITLE
need to clear dir, I think

### ISSUE THREAD

**Issue by SeriouslyKnowNothing** [Cog-Creators/Red-DiscordBot#892]
Completely new to this coding thing and having issues with a bot setup.

Every time I try to DL red-bot through GIT I get the following error.

fatal: destination path 'Red-DiscordBot' already exists and is not an empty directory.

Please advise and keep it idiot friendly. Completely new to this :)

**Comment by Jan200101** [comment]
a directory named Red-DiscordBot exists already.
Either you already cloned it or you made a folder called that

**Comment by tekulvw** [comment]
Delete the `Red-DiscordBot` folder from your current directory.

**Comment by SeriouslyKnowNothing** [comment]
Already cloned it, clone error of some sorts so followed advise to uninstall and re-clone. Thats when this error started.

Any way to delete that directory? First attempt failed to create the run.bat executable for the bot.
