### ISSUE TITLE
Add new startup flag to use real pip (global pip) install instead of local lib folder

### ISSUE THREAD

**Issue by skeith** [Cog-Creators/Red-DiscordBot#896]
On v2, the `cog install` install requirements to `lib` folder. This is good for single bot, but I host several bots on one server and installing it to global pip install location is better. I assume v3 would also behave the same way so I am suggesting an extra flag to start `red.py` (I still prefer running red directly) and `launcher.py` that skips local `lib` folder and use global pip install

I hope my wording is understandable

**Comment by Kowlin** [comment]
I think this could be solved with the shared cog folders.

**Comment by tekulvw** [comment]
Naw, it won't be. This option is good especially for those using a virtual environment. We may also want to make the lib install dir modifiable.
