### ISSUE TITLE
Discord keeps failing to load the Audio Cog

### ISSUE THREAD

**Issue by ElijahKSmith** [Cog-Creators/Red-DiscordBot#90]
Even after installing all prerequisites, even after downloading all of the files and placing them in their corresponding folders. I still get the same error: `Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit. Failed to load: cogs.audio`

I don't understand. I've even tried downloading the source files from the original website and installing them with the executable provided. What am I doing wrong?

**Comment by Twentysix26** [comment]
Both the opus library (the .dll file) AND the python installation must be either 32 bit or 64 bit. The direct link to the opus library provided in the wiki is 32 bit.

**Comment by ElijahKSmith** [comment]
Where is the 64bit download for Opus? I fail to see it on their website...

**Comment by tekulvw** [comment]
https://cdn.discordapp.com/attachments/133049553984159745/155762132179222529/libopus-0.dll
