### ISSUE TITLE
[Config Driver] MongoDB support

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#905]
Right now I'm working on implementing mongoDB support in Red V3. The working concept I'm going with is that each cog with a given name get's it's own database within mongo. Then we have collections for global/guild/member etc. data inside each database.

I think I have the driver completed but I can't really integrate it until #880 (and by extension #879) have been discussed, tested, changes made, and merged. If you're looking for mongo support in V3 (and other db backends), please test those PRs and report back your findings.

tekulvw/Red-DiscordBot@058a90e63534ee5b4015e829b8a98a068466eb81
Branch name is `V3/feature/mongodriver`

**Comment by Kowlin** [comment]
Closing in favor of #972
