### ISSUE TITLE
[Config] Asynchronous getters

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#906]
Right now config only requires `await`ing when you're setting/saving data which made sense for json, since data is already in memory there's no need to await getters. However when we attempt to support more data backends (read: mongo) in order to asynchronously use them we need asynchronous getters.

Are there any opinions/reasons to not switch to asynchronous getters?

**Comment by Twentysix26** [comment]
I see it as necessary if the goal is to have an interface that works for every driver

**Comment by tekulvw** [comment]
Fixed with #907
