### ISSUE TITLE
[Docs V3] We need install docs

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#910]
Right now the process to install v3 is fairly simple, just checkout `V3/develop` install the requirements from `requirements.txt`.You use `python main.py` to run the bot because we have no launcher. These docs can be fairly minimal but they are definitely important.

They should be made as a new rst file in the `docs/` directory.

**Comment by laggron42** [comment]
Still needed ?

**Comment by aikaterna** [comment]
#1005 has the current docs so far.

**Comment by palmtree5** [comment]
Closing per #1005
