### ISSUE TITLE
[Trivia V3] Main discussion thread

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#918]
Please comment here if there are any general comments/suggestions you may have for the V3 rewrite of trivia.

**Comment by Tobotimus** [comment]
### How do we want to handle payouts?

Payouts (through the bank API) have been discussed and suggested in the past. I've implemented a simple system (see #915) where the winner gets a certain number of credits based on the amount of questions they answer correctly, and a predetermined "payout multiplier" set by the bot owner or server admin (depending on the bank's global settings). The payout only occurs if there are at least 3 non-bot users who are playing. 

If anyone has any objections or different ideas in mind, comment them here :smile:

**Comment by MiniJennJenn** [comment]
^sounds good to me as long as it's toggleable ofc.

Suggestions people are interested in:

1. leaderboard or some sort of score tracker/stats.... 
- by percentage? raw numbers?
- organized by category? overall, individual categories? how would this factor into point 2 below...
- at least 3 nonbot users before points start to count?

2. a way to combine categories, or use all available questions at once

3. separate repo?

**Comment by palmtree5** [comment]
I'm thinking separate repo for the trivia lists and just have a command or something to download the list (probably have one to update them too)

**Comment by Chovin** [comment]
I also had a little payout system with a customizable little payout formula. Besides per-question multiplier and overall "participation bonus", iirc there was also a settable bonus for 1st, 2nd, and "the rest" place. The results board after a trivia game would reflect that.

Something to think about adding as well?

Would it be possible to add trivia lists to downloader so they can be handled by the [p]cog command as well? Or would allowing lists to be spread out amongst author repos be too much? Tbh, I think I like trivia as it is now, in a single "community repo"

**Comment by tekulvw** [comment]
any new thoughts on this?

**Comment by Tobotimus** [comment]
Author credits for trivia lists were mentioned, I support it

**Comment by MiniJennJenn** [comment]
Just tell me what format is needed and I can add them in per list

**Comment by Liquidus00** [comment]
I did my own questions and answers based on video games. Lot of her are difficult and I think it will be great to have a hint option in order not frustrate players.

A simple exemple :

"What is the name of the Creator of Metal Gear Solid ?" 

Hint (after some seconds) : H__eo Ko__ma

Eventually a second hint : Hi_eo Koj_ma

Answer : Hideo Kojima

**Comment by tekulvw** [comment]
No longer necessary
