### ISSUE TITLE
[Core V3] A lot of checks are broken

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#923]
Thought I'd shed some light on some bugs regarding checks. I'm anticipating much of these to be rewritten anyway (esp. the core checks) however fixing these now will help, since they are a pain when testing rewritten cogs.

- Global checks are all failing because of async getters
- Core checks are spewing errors because of async getters
- Bank checks just aren't checks

**Comment by palmtree5** [comment]
Not sure how bank checks aren't checks. The way I wrote them is such that they use the core checks (which one is checked is dependent on whether the bank is global or not) to do the checks rather than reinventing the wheel and writing checks from scratch

**Comment by Tobotimus** [comment]
@palmtree5 I could understand their logic, but the predicates were calling decorators as if they were functions. Decorators take functions as arguments, and they don't return true or false like a predicate does. Either way, I tested them and they let a no-permissions user use `bank set` and `bank reset`.

I'm sure there is a better way to encapsulate the checks so we don't have to write them all from scratch like you say. Perhaps we could add `bot.is_admin(member)` and `bot.is_mod(member)`, much like we have `is_owner`.

**Comment by Tobotimus** [comment]
This would be an elegant solution, but unfortunately it won't work.
```py
def check_global_setting_admin():
    if await bank.is_global():
        return checks.is_owner()
    else:
        return checks.admin_or_permissions(manage_guild=True)
```

We can't `await` anything in a decorator, we can only do so if we pass a predicate into `commands.check`.

**Comment by tekulvw** [comment]
I will be rewriting these checks when I get around to implementing permissions. I'll be sure to keep this in mind when redesigning the system.
