### ISSUE TITLE
ConnectionClosed: WebSocket connection is closed: code = 1001

### ISSUE THREAD

**Issue by mantvydasBra** [Cog-Creators/Red-DiscordBot#930]
So I when I write `!play (link)` bot joins voice channel, but doesn't do anything. When you type `!queue` bot says there's nothing on queue. Here's log: https://pastebin.com/uYfJyNey

**Comment by mantvydasBra** [comment]
Ok, I fixed it my self

**Comment by Twentysix26** [comment]
@mantaikas9 
Please remember to post what fixed your problem when closing an issue, even if it's just "I restarted it and it worked".  
There's nothing worse than finding a thread closed with "nvm figured it out" when you're attempting to solve something

**Comment by mantvydasBra** [comment]
Ok, so I first was running the bot on VPS but then it ended. Afterwards I figured out how to install Ubuntu on my phone and tried to install redbot. By far I can see that when I turn the bot on my mobile   and discord on my pc - everything works. But if I use discord on my phone then music seems to be not working.
