### ISSUE TITLE
Error When Trying to Install Basic Requirements

### ISSUE THREAD

**Issue by Gedankenexper1ment** [Cog-Creators/Red-DiscordBot#933]
Installed red (so far) per documentation on windows 7

Get this error:

![image](https://user-images.githubusercontent.com/31137150/29466328-800ca056-840a-11e7-8a97-df2ff473ac9e.png)

Any ideas?

**Comment by pgaetani** [comment]
Uninstall Python 3.6 and install 3.5. As per the documentation.

**Comment by Gedankenexper1ment** [comment]
I'll try that, thank you.

**Comment by Gedankenexper1ment** [comment]
Worked! Thank you!
