### ISSUE TITLE
Config docs issue

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#936]
http://i.imgur.com/FdowiQS.png

In that screenshot, the docstring for `register_guild` was copied and pasted, without changes, to `register_member`, `register_role`, and `register_user`. That should be changed (by making the appropriate edits to the docstrings for those three functions in `core/config.py`).

**Comment by Ellimistdev** [comment]
Does this still need to be addressed? Is @Tobotimus going to make a PR?

**Comment by Kowlin** [comment]
At this point making a pr is fine. I will judge it on a first come, first serve basis.

**Comment by Tobotimus** [comment]
@endotnick No, the "help wanted" tag is to encourage new people to contribute, and I'm not really new, so you're welcome to make a PR

**Comment by palmtree5** [comment]
Fixed by #1022
