### ISSUE TITLE
[Core] Introduction of Data Manager

### ISSUE THREAD

**Issue by tekulvw** [Cog-Creators/Red-DiscordBot#938]
With the PRs #879 and #880 I've created this concept of a data manager, something that allows you to change physical locations of where you want data stored (which is something we haven't had before). It fixes two big issues, first your data no longer has to be in the same folder as the bot files, and second it now gets rid of the need to set the CWD to the bot's folder.

### Why is this important?

If (when) we get pip installation working, we cannot store data inside the folder where the bot is installed. These PRs eliminate that problem but they do introduce new things that need to be discussed and decided.

"Config" is a high level, abstracted way to interact with cog data. It is highly dependent on knowing where to look and save data *during* the config object creation. This means that in order for config to work we must know where (and how) data is being saved.

### Possible solutions

We know we're probably going to want two scripts, one to generate the information that config needs and one to actually run the bot, so the question is what will the first script generate.

1. The script could generate a file named `config.json` in the CWD that contains the information necessary to get the bot up and running.

2. To more nicely support multiple bots, the script could ask for an instance name and save multiple sets of startup information in a single `config.json` which would be placed somewhere like `~/.config` or `%APPDATA%`

### What's in this new config file?

Things like:

- What type of storage you're using (json/db)
- Any necessary information for that storage type (like credentials)
- If using json, the location where you wish to store data

### Thoughts?

**Comment by Jan200101** [comment]
how about having a folder for each bot in `%APPDATA%`(or `~/.config`) which red uses based on set environment variables and/or flags

For example

If you start red normaly e.g.
`python3.5 red.py`
then it saves under `%appdata%/Red-Discordbot/default` or `%appdata%/Red-Discordbot/red` (again this is a example)


If you then start red using e.g. (flag is a example and should get a more fitting name)
`python3.5 red.py --bot blue`
where it then saves `%appdata%/Red-Discordbot/blue`
this is seperate from the default red data


the variable would check for a variable like `defaultred` where it then checks that variable to see what folder to get the data from.

**Comment by tekulvw** [comment]
I think that fits into the second solution, instead of having different folders (for just the config files, you will be able to set different data folders for each bot) it's just different json entries within the same file.

And I think we may just require a positional command line argument to determine which bot to run. e.g.:

`python redbot` - runs default
`python redbot second_bot` - runs the bot named "second_bot"

**Comment by Jan200101** [comment]
What about migrating existing data?

**Comment by tekulvw** [comment]
Existing V3 data? That's not within the scope of this issue or PR #879. However that should be discussed on #880 after #879 is merged.

**Comment by Jan200101** [comment]
I mean existing V2 data.
A lot of people that are already unfamiliar with getting python to work will have a hard time merging their old installation with the new one

**Comment by tekulvw** [comment]
That's not within the scope of this issue or either of the two PRs. At the moment we have no plans on supporting data migration from V2 -> V3.

**Comment by palmtree5** [comment]
I think solution 2 is the better option here as it centralizes the config needed for launching Red rather than the user needing to specify it every time (or be in the directory where it was originally created). I like the idea of having something in the path to be able to run Red by just doing something like `launchred saltbot` or `launchred red` and it'll find the entries in `~/.config/redconf.json` (or on Windows, `%LOCALAPPDATA%` or `%APPDATA%` (the first points to `<sysdrive>:\Users\username\AppData\Local`, the second point to `<sysdrive>:\Users\username\AppData\Roaming`)) and then will launch Red based on those settings

**Comment by tekulvw** [comment]
This has already been implemented. Docs explaining the installation and setup process are on the way.
