### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by josiec09** [Cog-Creators/Red-DiscordBot#94]
When i got to start the bot i get the following, i have made sure i have everything required installed. i was running the bot fine before the last major code changes.

C:\Users\User\Desktop\Red-DiscordBot>chcp 65001
Active code page: 65001

C:\Users\User\Desktop\Red-DiscordBot>python red.py
Traceback (most recent call last):
  File "red.py", line 30, in <module>
    formatter = commands.HelpFormatter(show_check_failure=False)
TypeError: **init**() got an unexpected keyword argument 'show_check_failure'

C:\Users\User\Desktop\Red-DiscordBot>pause
Press any key to continue . . .

**Comment by Twentysix26** [comment]
I'm not sure how that would even happen without an outdated discord.py

`pip3 uninstall discord.py`
`pip3 install git+https://github.com/Rapptz/discord.py@async`

**Comment by josiec09** [comment]
thats what is was, i thought i updated it but i must not of
