### ISSUE TITLE
[Core V3] Internationalization/Localization support

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#940]
There's two parts to this:

- Localizing the documentation
- Localizing the bot

For the documentation, http://docs.readthedocs.io/en/latest/localization.html covers what needs to be done on the RTD side of things to support that

As for the bot, something will need to be written to allow for this but the actual translating needs people who are familiar with languages other than English to contribute translations

We will also need a page in the docs on contributing translations.

Feel free to leave suggestions here on this subject

**Comment by Kowlin** [comment]
Hmm, what I always thought to this subject was to apply as an open source project to a community i18n provider. To allow us to use their service including automatic transmitting of strings to the project. [Such as this one](https://www.transifex.com)

**Comment by pgaetani** [comment]
Isn't Transifex paid? Something like Pootle, perhaps? Though I'd be fine with the RTD method of doing things, been waiting for that.
http://docs.translatehouse.org/projects/pootle/en/latest/index.html

**Comment by tekulvw** [comment]
The idea of relying on a third party service for the bot to work doesn't really sound good to me. I'll be working on this tonight and I'll be working on a V1 iteration based on translation files.

**Comment by palmtree5** [comment]
TBH the bot would work without the third-party translation service, it just would be English only. For other languages, yes, it would be reliant but we're gonna be relying heavily on others to translate anyway

**Comment by palmtree5** [comment]
This will cover #706 btw

**Comment by palmtree5** [comment]
See #948

**Comment by tekulvw** [comment]
Bot's been translated, not sure about the docs for now.
