### ISSUE TITLE
cogs.streams returns streams as being online when they can't reach the site

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#95]
Because of twitch_online returning string "error" when it fails to call aiohttp, bot will spam every stream registered in cogs.streams as online for that service.

239:     `async def twitch_online(self, stream):`
....
251:        `except:`
252: `return "error"`

text command to call twitch stream status will say online when it can't reach the service:

39 `online = await self.twitch_online(stream)`
40 `if online:`
41 `await self.bot.say("http://www.twitch.tv/{} is online!".format(stream))`

and so will the stream_checker function that is called with a timer:

 279               `online = await self.twitch_online(stream["NAME"])`
 280               `if online and not stream["ALREADY_ONLINE"]:`

I would submit a pull request but I can't into git

**Comment by Twentysix26** [comment]
Thanks, fixed just a few minutes ago
