### ISSUE TITLE
[i18n] Translation guidelines

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#955]
As more people start translation Red. A issue has risen, the need for guidelines on translation. What do and don't we translate and how do we go with setting those. 

### Server or Guild
Right now the source files both have server and guild. Its better to stick with one for consistency. Which one should we pick? I personally think server since its seen on the Discord UI this way.

### Translate core keywords
Core keywords (the ones described in the glossary, yes we have a glossary) are keywords such as ``server``, ``cog`` and so on. Should we translate these?
If we don't translate these, this could be confusing for the end user. However if we do translate them, then it could cause a problem for supporting a user.

**Comment by laggron42** [comment]
![](https://cdn.discordapp.com/attachments/160386989819035648/352844660445806602/Sans_titre.png)
welp, there are two identical lines, one with each word

**Comment by Jan200101** [comment]
imo Server is a more commonly used word which more users will understand

**Comment by laggron42** [comment]
about the `cog` word, I really think we should keep that word, as it is really difficult to translate (the only thing I could give is module) and it will confuse support team (I don't want to handle all of the french users lol)

**Comment by Kowlin** [comment]
While I'm thinking about it, do we have any plans for the help descriptions?

**Comment by Twentysix26** [comment]
I think "guild" shouldn't ever show up in anything user facing. Discord calls guilds "servers" in the UI and that's what we should stick with.  

Regarding translation guidelines, I think some terms, like "cog", should stay in English for consistency. 
It's used a lot in Red, even in command names and I think translating it would result in more harm than good due to the confusion that would arise. I've seen 100% literal translations in other products before and I'm really not fond of it, some terms are just better left in the original language.

**Comment by Kowlin** [comment]
For the translation guidelines a list of what words shouldn't be translated seems like a good idea. ``Cog`` would atleast be on this list.

**Comment by laggron42** [comment]
What I suggest to do not be translated : 
- `cog`
- `repo` (need to keep Github's words)
- `guild` where `server` is also in (some lines are duplicated, one with the `guild` word, the other with `server`

Also for the translated version, we should add a note like `If you need support go on red server and speak english` or add the french users to mention if they don't know english

**Comment by tekulvw** [comment]
Is this necessary anymore? Should we dedicate a docs page to this?

**Comment by Kowlin** [comment]
Nope, will do down the line when V3 is closer to release.
