### ISSUE TITLE
Pirate English translation

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#956]
I know a lot of you talked about it, as a joke, but a lot of website already does that, as Facebook, which is the best for me (I don't like facebook). I took some screenshots original english/pirate english to give you ideas, it's epic!

<img width="176" alt="1b" src="https://user-images.githubusercontent.com/23153234/29937695-bb96198c-8e86-11e7-8562-d4af2326d841.png">
<img width="179" alt="1" src="https://user-images.githubusercontent.com/23153234/29937703-bf102bc0-8e86-11e7-9e5b-22410a036fe9.png">
--------------------------------
<img width="193" alt="2b" src="https://user-images.githubusercontent.com/23153234/29937710-c7260c9e-8e86-11e7-833d-e4175c08b47d.png">
<img width="234" alt="2" src="https://user-images.githubusercontent.com/23153234/29937714-c93b0c50-8e86-11e7-9c3f-578975504b97.png">
--------------------------------
<img width="446" alt="3b" src="https://user-images.githubusercontent.com/23153234/29937719-cbfb54ea-8e86-11e7-90d5-382a9bf7fa19.png">
<img width="446" alt="3" src="https://user-images.githubusercontent.com/23153234/29937722-cd37666e-8e86-11e7-833f-9141bf3d086a.png">
--------------------------------
<img width="336" alt="4b" src="https://user-images.githubusercontent.com/23153234/29937725-cf8b1ca8-8e86-11e7-9e64-05844ac0ea1c.png">
<img width="399" alt="4" src="https://user-images.githubusercontent.com/23153234/29937738-db658be4-8e86-11e7-9210-e25eb0672f39.png">
--------------------------------
<img width="488" alt="5b" src="https://user-images.githubusercontent.com/23153234/29937742-debde6d8-8e86-11e7-9974-ad9742989a56.png">
<img width="453" alt="5" src="https://user-images.githubusercontent.com/23153234/29937744-e0214e02-8e86-11e7-9c3e-b7e8263a275f.png">
--------------------------------
<img width="378" alt="6b" src="https://user-images.githubusercontent.com/23153234/29937752-e308aeb2-8e86-11e7-972a-acfca5427268.png">
<img width="387" alt="6" src="https://user-images.githubusercontent.com/23153234/29937755-e48219d6-8e86-11e7-9248-99efc2c36d4f.png">
--------------------------------
<img width="201" alt="7b" src="https://user-images.githubusercontent.com/23153234/29937759-e84366b0-8e86-11e7-9479-a30d7bb9dc3b.png">
<img width="209" alt="7" src="https://user-images.githubusercontent.com/23153234/29937762-e9ac5908-8e86-11e7-8e29-7c22f0edbdf2.png">
--------------------------------
<img width="254" alt="8b" src="https://user-images.githubusercontent.com/23153234/29937764-ed172a6e-8e86-11e7-9d96-b5d6ac3e6395.png">
<img width="372" alt="8" src="https://user-images.githubusercontent.com/23153234/29937765-ee6e48ac-8e86-11e7-812b-09051502e47f.png">
--------------------------------
<img width="334" alt="9b" src="https://user-images.githubusercontent.com/23153234/29937769-f185daa0-8e86-11e7-80de-9e9789042c29.png">
<img width="341" alt="9" src="https://user-images.githubusercontent.com/23153234/29937774-f36189fa-8e86-11e7-9343-ce6db1cbb6f9.png">
--------------------------------
<img width="678" alt="10b" src="https://user-images.githubusercontent.com/23153234/29937778-f809eb64-8e86-11e7-98f1-c479b7eacf11.png">
<img width="696" alt="10" src="https://user-images.githubusercontent.com/23153234/29937781-fcdb9b7e-8e86-11e7-9052-698e75f2fb2d.png">
--------------------------------

Have fun having ideas for Red!

**Comment by DannyB5544** [comment]
I would pay for this. (Don't make me pay for this)

Great idea though

**Comment by retke** [comment]
Here are other screenshots from Minecraft Pirate version

![1a](https://user-images.githubusercontent.com/23153234/29961479-147240ca-8f00-11e7-968d-964b1707f3c5.png)
![1b](https://user-images.githubusercontent.com/23153234/29961477-146ece90-8f00-11e7-9c4b-f5c4c3c5ffc4.png)
-------------------
![2a](https://user-images.githubusercontent.com/23153234/29961478-146f1ce2-8f00-11e7-911a-197f67c27768.png)
![2b](https://user-images.githubusercontent.com/23153234/29961480-147336ec-8f00-11e7-9381-8c2b9c5d1773.png)
-------------------
![3a](https://user-images.githubusercontent.com/23153234/29961481-147362de-8f00-11e7-8805-819a386c810b.png)
![3b](https://user-images.githubusercontent.com/23153234/29961482-1473a24e-8f00-11e7-8b63-1f825c631766.png)
-------------------
![4a](https://user-images.githubusercontent.com/23153234/29961484-1485ade0-8f00-11e7-8e50-2247cc185c6c.png)
![4b](https://user-images.githubusercontent.com/23153234/29961483-1485b268-8f00-11e7-9106-8894fe2d5c32.png)
-------------------
![5a](https://user-images.githubusercontent.com/23153234/29961486-148c0cee-8f00-11e7-8698-2e464e14b6e2.png)
![5b](https://user-images.githubusercontent.com/23153234/29961488-148c76a2-8f00-11e7-9de9-91a035d983d3.png)
-------------------
![6a](https://user-images.githubusercontent.com/23153234/29961487-148c2d46-8f00-11e7-8bfa-2a4ed9789ac8.png)
![6b](https://user-images.githubusercontent.com/23153234/29961485-148b9bce-8f00-11e7-9b9e-adc460e5f285.png)
-------------------
![7a](https://user-images.githubusercontent.com/23153234/29961489-149a87a6-8f00-11e7-9f38-b9e64f357eaa.png)
![7b](https://user-images.githubusercontent.com/23153234/29961490-149ad1de-8f00-11e7-84f4-88bcbfaf4241.png)
-------------------
![8a](https://user-images.githubusercontent.com/23153234/29961491-149fa2cc-8f00-11e7-93a9-2d327f3ad3a8.png)
![8b](https://user-images.githubusercontent.com/23153234/29961494-14a3ba1a-8f00-11e7-9384-dc547f1e24ea.png)
-------------------
![9a](https://user-images.githubusercontent.com/23153234/29961492-14a22524-8f00-11e7-8dc3-fddac4b85c1b.png)
![9b](https://user-images.githubusercontent.com/23153234/29961493-14a30840-8f00-11e7-879a-0800b92fd857.png)
-------------------
![10a](https://user-images.githubusercontent.com/23153234/29961495-14af69e6-8f00-11e7-978b-98e6c3d4a21e.png)
![10b](https://user-images.githubusercontent.com/23153234/29961496-14b03efc-8f00-11e7-8a24-588b49b2e684.png)

**Comment by Jan200101** [comment]
👍

**Comment by Kowlin** [comment]
Please stop sending screenshots... This isn't Imgur.

**Comment by laggron42** [comment]
@Kowlin that was just for giving ideas... ok maybe that's shitpost

**Comment by Kowlin** [comment]
Done. See Crowdin.
