### ISSUE TITLE
[V3] Launcher rewrite + Oauth2 authentification

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#957]
Hello, I have some ideas about what the new Red V3 launcher could look like and also an Oauth2 authentification usage.

## Launcher

Instead of having a terminal based launcher, where you move using numbers, we could make a window that would have a better control and possibilities. 
![5b](https://user-images.githubusercontent.com/23153234/29979321-4b622eb6-8f45-11e7-826b-e1acd26dd9e5.png)
A red text is a comment

Here is a little photo edit I made, showing how I think this should look like. I know it's a lot of work and it probably won't be done, but I gave you my ideas (and I spent 2 hours making this photo). This also could be a website, why not ?

## Oauth2 connexion

Referring to what I said before, when creating Red, we could link the user to connect himself to discord account and then have his name, avatar, servers... as Mee6 bot does. This could also allow us to have a database of the users and block them if they break the rules, as removing credits. Here is [the doc](https://discordapp.com/developers/docs/topics/oauth2#scopes) for Discord's connexions.

**Comment by Kowlin** [comment]
For oauth, we simply have no need for that setup. The reason Mee6 does it is because it wants some vital information about the user. Unlike Mee6, we don't require this information for full functionality.

**Comment by Electromaster232** [comment]
I agree with Kowlin on the OAuth. The launcher (GUI Style) would be really cool, but if we're staying with Python our only options are Tkinter or PyGame, both of which are very difficult to use.

**Comment by tekulvw** [comment]
Gonna say "no" on this for now, may revisit down the line.
