### ISSUE TITLE
Music cog is not starting

### ISSUE THREAD

**Issue by NeutralPlasma** [Cog-Creators/Red-DiscordBot#965]
Hello im having problem like when i start bot it says that i have 10/11 active cogs and when i type (prefix)play   (/play) nothing happens but when i do /help it sends me help but there is not music help?

**Comment by laggron42** [comment]
the audio cog is not loaded, type `[p]load audio` and the commands will show

**Comment by NeutralPlasma** [comment]
ok

**Comment by NeutralPlasma** [comment]
Thanks man
