### ISSUE TITLE
[Cog] [Economy] [Request] Multiple Currencies and Payouts depending on Roles

### ISSUE THREAD

**Issue by HushTD** [Cog-Creators/Red-DiscordBot#966]
I suggest adding more options to the Economy.py cog. I think it'd help some servers who use it a lot, eventually possibly creating things like currency exchange and stock markets via fan cogs. The second thing is diffrent payouts depending on roles (ex. Regulars get more currency than @everyone). That would be very appreciated (I am looking for some ways for multiple currencies for my server and multiple paydays depending on roles mostly)

**Comment by palmtree5** [comment]
I'm going to go ahead and work on implementing the suggestion of different paydays depending on roles.

**Comment by tekulvw** [comment]
What's the progress on this @palmtree5?

**Comment by palmtree5** [comment]
On second thought, I think this might be better served as a third-party cog
