### ISSUE TITLE
[V3] Meaningful responses to bad command arguments

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#967]
Right now, when a "Bad Argument" is passed into a command (i.e. when a `commands.Converter` fails), the bot simply responds with the help message. This doesn't really tell the user why the command failed, and I've seen many users be stumped by this.

I have two ideas for solutions:
1. Respond saying exactly what conversion failed, e.g. if a `commands.MemberConverter` fails, it responds with _Member "[user]" not found_
2. Make the help message contain better documentation for command arguments.

Disadvantages of each solution:
1. Relies on a meaningful message being passed into `commands.BadArgument` when a conversion fails, which brings up potential issues with custom converters (there are no guidelines on how `commands.BadArgument` should be used).
2. A more meaningful help message is still fairly ambiguous. The point of error messages is for the user to know exactly what went wrong, not just throwing a bunch of help docs in their face.

**Comment by Tobotimus** [comment]
For reference, these are the messages passed into `commands.BadArgument` for all situations I found in discord.py.

Converting arguments (`commands.converter` module):
- When a `commands.MemberConverter` fails: _Member "{}" not found_
- When a `commands.UserConverter` fails: _User "{}" not found_
- ... and so on for all other converters in the `commands.converter` module, except for:
- When a `commands.ColourConverter` fails: _Colour "{}" is invalid_
- When a `commands.InviteConverter` fails: _Invite is invalid or expired_

Parsing arguments (`commands.view` module):
- Unexpected EOF whilst parsing a quoted argument: _Expected closing "_
- Invalid char after closing a quoted argument: _Expected space after closing quotation_
- Quote mark being in the middle of an argument: _Unexpected quote mark in non-quoted string_

Those last 3 error messages seem far too technical to be sending to the user. Which makes solution 1 more difficult :worried:

**Comment by Kowlin** [comment]
Absolutely doable. However I think its the best if this is done on a per command basis, due the fact that commands require different arguments.

**Comment by Tobotimus** [comment]
[discord.py#773](https://github.com/Rapptz/discord.py/pull/773) could help us out here, pending a merge

**Comment by mikeshardmind** [comment]
Without any additional info, and that PR still open months later in discord.py, is this worth putting in `redbot.core.commands` @Tobotimus ?

**Comment by Tobotimus** [comment]
@mikeshardmind Good point! I hadn't actually thought of that. ~~We could probably do it by just overriding `commands.Command.transform()`, by calling the super and catching `commands.BadArgument`.~~ Edit: after further inspection it looks a bit trickier than that, but I'm sure it's doable. Edit 2: `commands.Command.do_conversion` is what I was looking for!

**Comment by tekulvw** [comment]
Fixed with #1817
