### ISSUE TITLE
Error "You don't have the requirements to start Red"

### ISSUE THREAD

**Issue by EndreEndi** [Cog-Creators/Red-DiscordBot#974]
C:\Users\attil\Desktop\Red-DiscordBot>pushd C:\Users\attil\Desktop\Red-DiscordBot\

C:\Users\attil\Desktop\Red-DiscordBot>"C:\Users\attil\AppData\Local\Programs\Python\Python36-32\python.exe" launcher.py --start
Starting Red...
You don't have the requirements to start Red. Install them from the launcher.

C:\Users\attil\Desktop\Red-DiscordBot>pause
Press any key to continue . . .

**Comment by EndreEndi** [comment]
what requirements i need to instal? 1, 2, 3 or 4?

**Comment by Priultimus** [comment]
1 for with music, *also I think you should be asking this in https://discord.gg/red* or 2 for without music
then 4 if your computer isn't extremely old and 3 if it is

**Comment by Twentysix26** [comment]
@MateiGamingYTB Whatever you need. That's the point of it being multiple choice

**Comment by palmtree5** [comment]
Also don't use 3.6 on Windows. The docs specifically say to use 3.5 on Windows

**Comment by Kowlin** [comment]
Closing. 9 days have passed since the last author reply.
