### ISSUE TITLE
Suggestion: M3U support.

### ISSUE THREAD

**Issue by 7thChimera** [Cog-Creators/Red-DiscordBot#975]
I recently downloaded and set up your bot for local media playback for audio files but Red doesn't currently have the flexibility i'm looking for, so for now, i'm just using Virtual Audio Cables. 

Problem: When configuring Red's media directory, I noticed that it could only play media from one sub-folder down. So my first line of thought was.. 'hmm maybe i can keep my music organized where it was, and just create a singular directory full of M3U files for Red to read from that way it can play media from everywhere on my Music HDD regardless of what directory the music was actually located in.' <-- this train of thought just didn't work.

Potential Solutions:

1.) Implement M3U extensions so I can create a folder for playlist files without having to copy all of my music into one folder, which leads to me running out of HDD space or me completely messing up the order my albums are arranged in.

2.) Completely redo the code and have it to where it can search your media via reading ID3 tags of any mp3 files located in ALL sub-directories of the media folder that you set up when you set Red up.

I think the first solution would work the best, short term. Long term goal would be #2 as it would probably require a lot of work. Can you guys implement M3U support?

**Comment by tekulvw** [comment]
See #623
