### ISSUE TITLE
Question - Does Red create music artist/song output?

### ISSUE THREAD

**Issue by go-go-gadget** [Cog-Creators/Red-DiscordBot#977]
Apologies in advance if this is not the place to ask (feel free to delete if it is).

I'm wondering if Red creates any kind of text file output with details on the song that is currently playing? I'm asking because I'd like to integrate it with a program like Snip so that I can show the song that is playing on a live stream. Thanks.

**Comment by Kowlin** [comment]
Apologies for the very late reply. I just got the time to work trough some issue backlogs. Sadly enough that's a no. Red doesn't output the song to a file.
