### ISSUE TITLE
Bot doesn't auto-join voice channel

### ISSUE THREAD

**Issue by BrianStiner-zz** [Cog-Creators/Red-DiscordBot#978]
I have made a music_bot, and am able to give it some commands through private messages, 
but when I join a voice channel, as the owner, it doesn't follow me.
I've tried usual issues such as updating it, (no updates to get)
but I'm now in a pickle.

**Comment by palmtree5** [comment]
Try doing any command that would make it play audio while you're in a voice channel (in a server). Then it will join you. It doesn't join automatically when you join a voice channel

**Comment by palmtree5** [comment]
https://discord.gg/red
