### ISSUE TITLE
[V3] File of commands to execute on boot

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#984]
I imagine something that could execute functions or commands on bot/package start, like the `.xinitrc` file in Archlinux does (executes all of the commands wrote in the file when a user session is started). A general file for red and other files for the packages (to let them independent, and work correctly when you reload one) or, why not, categorize them in a single file, for example, like this:

```Py
# This is not a correct code, just to show you what I have in mind

Red: # executed when the bot is ready (package independent)
    bot.load("audio")
    bot.send(myChannel, "Red is now online")

Audio: # will be executed when the audio package is loaded
    bot.join_channel(id)
    bot.command("play radio portal loop 10h") 
```

**Comment by pgaetani** [comment]
Correct me if I'm wrong, but would this not require the bot's command methods to be exposed in some way to the shell? Where would we get the context to do all this from?

**Comment by laggron42** [comment]
The Red file can or not be launched after cog's loading, depends on what you're planning to do (the staff, not the user), and there is no context, yes, so you have to define everything (get the server, then the channel...). This would need to have a function that can let you call a command and get the result (or not) as a value, I don't know if this is implemented but this would be cool, like we could make some add-on to packages without editing, just importing them in a new package or use them in the starting file. And the thing you can't do with a normal package (and a `on_load` function) is that you can define separately commands for every package.

**Comment by pgaetani** [comment]
I think that would be better handled by an internal utility that could execute code in on-load events. 
I ran into the same hurdle (and subsequent telling off) when trying to expose command methods via an RPC.
Something along the lines of scheduler (internal cron for red pls), but more advanced and with more events being handled, would be nice.

In any case, that would probably be handled as a separate cog, or perhaps part of admin, or perhaps we're both talking out of our asses : P I expect Will or Palm to come tell us off soon.

**Comment by palmtree5** [comment]
To my knowledge, there is no event triggered on loading a cog.

**Comment by Tobotimus** [comment]
No, there isn't, there is no need for one; if you want code to be executed on cog load you can include it in the cog's `__init__`. This has always been a feature.

**Comment by laggron42** [comment]
But this won't let the user do it without editing the core files, that's what I wanted: a function that everyone can modify without any troubles

**Comment by Tobotimus** [comment]
Sorry I misread and thought you were talking about custom cogs, not core cogs. In that case, I can see the value in an `on_cog_load` event, and that wouldn't even be too hard to implement. I don't really like the idea of this whole file thing, why not just add this functionality to cogs?

This event may not be received by your cog on startup however, as it would depend on the order of cogs loading. In that case you can just use the cog's `__init__` to carry out the functions in place of the event.

**Comment by tekulvw** [comment]
No plans to implement, would require mocking d.py objects which is a pain.
