### ISSUE TITLE
More complex playlist manipulation on local file playlists

### ISSUE THREAD

**Issue by gh0un** [Cog-Creators/Red-DiscordBot#985]
Currently there is no real way to display how many songs are in queue if you play files from a local folder.

It would be quite handy to be able to display that queue, and also manipulate it (remove certain songs via queue number, move certain song in queue to be next up and so on).

There is little to no way to interact with a local file playlist rn.

**Comment by Kowlin** [comment]
A more complex system will likely come to V3 audio, this won't be added to V2 audio though.
