### ISSUE TITLE
Test Command Error

### ISSUE THREAD

**Issue by CDAGaming** [Cog-Creators/Red-DiscordBot#987]
File "c:\users\tonyg\appdata\local\temp\pip-build-w6aoew\red-discordbot\setup.py", line 52
        def glob_locale_files(path: Path):
                                  ^
    SyntaxError: invalid syntax

**Comment by palmtree5** [comment]
Can you provide a bit of info? Specifically:

Python version:

Windows version:

**Comment by kakious** [comment]
We figured it out. We were running a old version of python and that was causing the issue.

**Comment by CDAGaming** [comment]
Yup, closing as solved. (Forgot to do so earlier)
