### ISSUE TITLE
Features Request support for new discord bot accounts

### ISSUE THREAD

**Issue by josiec09** [Cog-Creators/Red-DiscordBot#99]
So now that Discord will be releasing an official API documentation soon and have added Bot Accounts will you be adding support for Bot accounts so with can have a bot in multiple voice channels at the same time and all the other features they will be adding?

> Post from Discord Devs

Bot accounts are live, and official API documentation is coming soon!

But, before we release it en-mass, you can try it out by manually creating an OAuth2 Application and converting an existing bot user to it, or creating a new bot user for it. The guide below assumes you're on OSX/Linux (or have curl/cygwin on windows) There will be a to do UI for all this in the documentation. If you are unfamiliar with the concepts in the tutorial below, wait for the documentation to come out!

How to create an application (this is the same API used to create an Application in Stanislav's example above)

```
curl -H 'Authorization: YOUR_TOKEN' \
     -H "Content-Type: application/json" \
     -X POST -d '{"name": "YOUR BOT NAME HERE"}' \
     https://discordapp.com/api/oauth2/applications
```

You should get back:
{"secret": "XXX", "redirect_uris": [], "description": "", "name": "YOUR BOT NAME HERE", "id": "YYY", "icon": null}

Keep the secret secret, and the id safe. You've successfully created your Application!

Now, you can either convert a user to a bot, or create a new bot account (note the id is your applicationid`): 

```
curl -H 'Authorization: YOUR TOKEN' \
     -H "Content-Type: application/json" \
     -X POST -d '{"token": "YOUR BOT USERS TOKEN"}' \
     https://discordapp.com/api/oauth2/applications/:id/bot
```

You should get back:

```
{"username": "Mewsick", "bot": true, "token": "YOUR BOTS NEW TOKEN", "avatar": "338f4d9d97056ae22c4a3feab5f0da07", 
"discriminator": "1550", "id": "132254000253894656"}
```

To create a fresh bot account, just don't provide a token. It will use your application name as the username for the bot.(edited)
NOTE:
- Converting a user account to a bot account is irreversible. USE CAUTION!
- Bot accounts:
  - do not have a password, or e-mail. This means you cannot reset the password to regain the token (a way to reset this token will be available soon)
  - are unable to accept invites, and are only able to join a guild via the oauth 2 flow (more on this soon).
  - are unable to have friends.
- However, bot accounts:
  - are able to be connected to multiple voice channels at the same time.
  - have a fancy [bot] tag beside their name.
  - will have higher per-server rate limits.
  - and be able to do much more (as we roll out this feature).
    So, you've created a bot, and you want to add it to servers now. How this happens is simple, just make a link to the authorize page with your application's id & the bot scope.

https://discordapp.com/oauth2/authorize?&client_id=YYYY&scope=bot

(You can invite my bot to your server by using this link to check it out: https://discordapp.com/oauth2/authorize?&client_id=157730590492196864&scope=bot)

Additional URL parameters:
- permissions: An integer containing the permission bits set that you want the bot to have.
  - guild_id: If you know the specific guild ID you want the bot to join.
- ... there are more, that will be released with the official docs!(edited)
  >

**Comment by Twentysix26** [comment]
It will in the feature, it's not up to me to implement it. The bot is using discord.py and its author is going to support bot accounts when they're released and not in "beta" anymore.
