### ISSUE TITLE
Traceback on play command with youtube URL

### ISSUE THREAD

**Issue by Kingyo** [Cog-Creators/Red-DiscordBot#991]
Hi,

I'm running Red on a docker container with the latest image of python. When I try to play a local playlist it works correctly, but when I type [p]play http://youtube.com/watch?v=XXXX the bot stop and I have this stack:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/cogs/audio.py", line 260, in run
    self.get_info()
  File "/app/cogs/audio.py", line 291, in get_info
    process=False)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 777, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1598, in _real_extract
    if 'token' not in video_info:
TypeError: argument of type 'NoneType' is not iterable
```

I installed all the correct requirements and tried on different docker's images.
If you have any ideas on how to resolve this...

Thanks in advance.

**Comment by calebj** [comment]
It would help if you linked the specific video. Also, post the version of youtube-dl you're using (and make absolutely sure all of that is up to date, the library breaks a lot when youtube changes things).

**Comment by Kingyo** [comment]
Fast answer! This is the link https://www.youtube.com/watch?v=_JHRfYYGySA
This is the version of my package installed:
aiohttp==1.0.5
async-timeout==1.4.0
beautifulsoup4==4.6.0
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
discord.py==0.16.11
idna==2.6
imgurpython==1.1.7
multidict==3.2.0
pycparser==2.18
PyNaCl==1.0.1
requests==2.18.4
six==1.11.0
urllib3==1.22
websockets==3.4
youtube-dl==2017.9.24

**Comment by calebj** [comment]
I have no problems downloading or playing that video, and your versions look fine. It's possible that youtube doesn't like your IP address. Are you on a VPS or your own machine?

**Comment by Kingyo** [comment]
That's it, why didn't I think about that before? I'm on my server so yes it's blocked by youtube...
Thanks for your help! I'll try to fix that if I can and post how I did it!

**Comment by calebj** [comment]
Yeah, that happens sometimes. Usually it'll go away after a while.
