### ISSUE TITLE
Blacklisted user can still give red commands

### ISSUE THREAD

**Issue by BaIthamel** [Cog-Creators/Red-DiscordBot#993]
I have added a user to the blacklist with
!blacklist add <user>
and !blacklist list shows they are in it however they are still able to give the bot commands.

**Comment by palmtree5** [comment]
I can't reproduce this

**Comment by BaIthamel** [comment]
Turns out someone was playing silly buggers and long story short the guy on the blacklist wasn't the guy still using commands.
