### ISSUE TITLE
[Audio] Improper handling of playlist URLs in 'play' command

### ISSUE THREAD

**Issue by DetermineAbsurd** [Cog-Creators/Red-DiscordBot#997]
A friend was trying to play a single song, but had a list url. Upon using `<p>play <url>` the bot joined, but started to download the entire playlist. Once it had finished downloading (determined by watching the cache folder manually for changes) it did nothing and when we attempted to queue another song, it stated that it was downloading a file. Attempting to view the queued playlist with `<p>queue` was met with the message "Nothing queued on this server". After awhile, it disconnected on it's own from the channel with this error in the console:
```
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at <PATH_TO_BOT>\cogs\audio.py:2136> exception=KeyError('107578843795030016',)>
Traceback (most recent call last):
  File "<PATH_TO_BOT>\cogs\audio.py", line 2175, in queue_manager
    song = await self._play(sid, url, channel)
  File "<PATH_TO_BOT>\cogs\audio.py", line 874, in _play
    song = await self._guarantee_downloaded(server, url)
  File "<PATH_TO_BOT>\cogs\audio.py", line 674, in _guarantee_downloaded
    while self.downloaders[server.id].is_alive():
KeyError: '107578843795030016'
```
I shutdown the bot with `<p>shutdown` and the bot shutdown with Exit Code 0, but before it did, this was output in the console
```
data/audio/cache\PL0zTGNAmpgmfKtrWTweyjpBvoozBjgxXN: No such file or directory
```

The link to the playlist is [this](https://youtu.be/4fB0_1s38Sc?list=PL0zTGNAmpgmfKtrWTweyjpBvoozBjgxXN) if that helps.

**Comment by tekulvw** [comment]
Not fixing on V2.
