### ISSUE TITLE
doesnt install

### ISSUE THREAD

**Issue by dombnexengr** [Cog-Creators/Red-DiscordBot#999]
doesnt install at all

**Comment by palmtree5** [comment]
Have you followed [the docs](http://twentysix26.github.io/Red-Docs/)?

**Comment by Twentysix26** [comment]
Please post helpful details when you open an issue

**Comment by dombnexengr** [comment]
ofc i try to install it as the details sayed

2017-10-09 22:37 GMT+03:00 Twentysix <notifications@github.com>:

**Comment by Kowlin** [comment]
We can only go so far for diagnosing a problem, please meet us half way here and actually explain what your issue is. Since by saying "I did it what it said" we won't get anywhere. Feel free to open a new issue.
